### ISSUE TITLE
incorrecct function

### ISSUE THREAD

**Issue by beanhacker** [nats-io/nats-server#1002]
- [ ] Defect
 - [ ] Feature Request or Change Proposal
 
## Defects 

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ ] Included `gnatsd -DV` output
 - [ ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)
 
#### OS/Container environment:
  WINDOWS
#### Steps or code to reproduce the issue:
  i add websocket feature to this code, but report "Incorrect Function" error
  codes test demo as below:  
	helloHandler := HelloHandler{}
    http.Handle("/hello1", helloHandler)
    http.HandleFunc("/hello2", hello)
    fmt.Println("go here...")
	http.ListenAndServe("0.0.0.0:8080", nil)

#### Expected result:
      listen will continue, no error reported.
#### Actual result:
    c:\test\backend\src\github.com\nats-io\nats-server>main.exe
[1556] 2019/05/21 18:26:04.657200 [?[32mINF?[0m] Starting nats-server version 2.0.0-RC12
[1556] 2019/05/21 18:26:04.668085 [?[32mINF?[0m] Git commit [not set]
go here...
Incorrect function.

**Comment by derekcollison** [comment]
We will be adding websocket support in a future release.
