### ISSUE TITLE
NATS client parser error depending on what machine a client connects from

### ISSUE THREAD

**Issue by Zannith** [nats-io/nats-server#1010]
Seeing the following error on NATS server on client connect: `Client parser ERROR, state=0, i=90: proto='"X-WS-Ver: 1.0\r\nX-WS-EP-Ver: 1.5."...'`
 
This happens when any client attempts to connect other than my own machine. For example I have three machines, A B and C. Each one has a NATS server and can connect to the server on its localhost. However machine A is the only one that can hit B and C without causing the above exception. If B tried to connect to A or C the NATS servers on those machines would give that error.

The code being used to connect is the same across all three machines. (Except the ip's they are connecting to)

This isn't really an issue with nats server then, but some system level thing I am missing which affects how a client connects. Problem is I have no idea what.

debug info:

```
[38108] 2019/05/22 16:11:08.890830 [DBG] ip:x - cid:1 - Client connection created
[38108] 2019/05/22 16:11:08.891811 [TRC] ip:x - cid:1 - ->> [CONNECT {"verbose":false,"pedantic":false,"tls_required":false,"name":"","lang":"go","version":"1.7.2","protocol":1,"echo":true}]
[38108] 2019/05/22 16:11:08.891811 [TRC] ip:x - cid:1 - <<- [-ERR Unknown Protocol Operation]
[38108] 2019/05/22 16:11:08.892796 [ERR] ip:x - cid:1 - Error reading from client: Client Parser ERROR, state=0, i=130: proto='"X-WS-Ver: 1.0\r\nX-WS-EP-Ver: 1.5."...'
[38108] 2019/05/22 16:11:08.892796 [TRC] ip:x - cid:1 - <<- [-ERR Parser Error]
[38108] 2019/05/22 16:11:08.892796 [DBG] ip:x - cid:1 - Client connection closed
```

**Comment by kozlovic** [comment]
@Zannith NATS Server has its own protocol with NATS clients. It looks here that the server receives from a client something that it does not understand. Which NATS client library are you using? Is it happening all the time or following a reconnect?
Is there anything in between your clients and those servers? Like a load balancer, firewall, etc?

**Comment by Zannith** [comment]
This was with both a Java library, a GO library, and a Node library. This happens on every client attempt to connect. All three of our machines are on the same corporate network. All should have the same firewall configuration. (Although I do not actually have access to manage that). Adjusting corporate proxy settings seemed to have no effect. There is nothing else I am aware of between the clients and servers

**Comment by sasbury** [comment]
X-WS-Ver really looks like an HTTP header which isn't something the NATS clients would send themselves.

**Comment by Zannith** [comment]
@sasbury Yea I believe it is. It's like some other message is being kicked off from the nats client attempting connection. My experience here is pretty limited and I have no idea what it might be from the information available

**Comment by derekcollison** [comment]
There is some proxy or something in between that is not just transparently forwarding TCP or TLS traffic to the NATS server. If you are doing NON-TLS, sometimes switching to TLS can avoid the proxy injection.

**Comment by derekcollison** [comment]
NATS servers that are not running TLS can be connected to and interacted with just using TELNET.

https://nats.io/documentation/internals/nats-protocol/

**Comment by Zannith** [comment]
You were right about switching to tls. The issue is always a proxy isn't it. Thank you for pointing me in the right direction!

**Comment by derekcollison** [comment]
First blame DNS, then a proxy or firewall - lol
