### ISSUE TITLE
Evaluation of use GitLab CI as CI environment

### ISSUE THREAD

**Issue by tnir** [nats-io/nats-server#1017]
- [x] Feature Request or Change Proposal

During KubeCon EU 2019 Barcelona, @tnir and @wallyqs discussed possibilities of migration of nats-io CI (including coverage reports) in person.

Very initial inception was just done at https://github.com/tnir/nats-server/pull/1 (used my personal namespace instead of PR on @nats-io because I have no permissions on it)

/cc @wallyqs @tnir

**Comment by rigtorp** [comment]
We use GitLab CI at work and it's been great. It will be useful since you can easily use different container images to run CI for different distributions. So you'll be able to say that CentOS 7/8 and Alpine are supported platforms and nats-server should build and pass tests on them.

**Comment by tnir** [comment]
I tried some inception in my own namespace (GitHub and Travis CI (.com)) with `COVERALLS_REPO_TOKEN` in Travis CI environment variable.
But `master` branch does not look stable to me. https://travis-ci.com/tnir/nats-server/branches
Can you help me about this @wallyqs ?

## Notes
- nats-io is on travis-ci.org https://travis-ci.org/nats-io/nats-server/branches
- tnir/nats-server is on travis-ci.com (new Travis CI environment) https://travis-ci.com/tnir/nats-server/branches

**Comment by wallyqs** [comment]
Thanks @tnir, correct we still have a few flaky tests in the repo that we need to take a look at fixing. We'll take a look at those, sorry for the inconvenience...

**Comment by bruth** [comment]
There are no plans to migrate to GitLab CI. The current plan is transitioning from Travis to GitHub Actions.
