### ISSUE TITLE
PINGXXXXXXXXX\rXXXXXXX\n is a valid PING request

### ISSUE THREAD

**Issue by rigtorp** [nats-io/nats-server#1034]
See https://github.com/nats-io/nats-server/blob/7f284df44940ca138c763154f5a26c2507c3b19d/server/parser.go#L555

Shouldn't the parser validate that only trailing whitespace is allowed?

**Comment by derekcollison** [comment]
It could, we will make sure you don't overflow the control line but otherwise were tolerant.

**Comment by rigtorp** [comment]
@derekcollison Ok, so this is on purpose. I'm curious about the reasoning behind being so lenient? Looks like NATS protocol is a Redis-style protocol. Was a faster to parse and safer to implement TLV type protocol considered?

**Comment by derekcollison** [comment]
Apologies what is TLV?

This parser is pretty darn fast, can process over 18M msgs/sec and has almost zero allocations in most passes, so we are happy with it. Being text based makes building clients a bit easier IMO and promotes the client ecosystem. I am general considered a performance geek and have written plenty of binary protocols, I am happy with this one for the most part.

**Comment by rigtorp** [comment]
Tag/Type-Length-Value, https://en.wikipedia.org/wiki/Type-length-value. Example https://www.batstrading.com/resources/membership/BATS_MC_PITCH_Specification.pdf (check page 13). This is also how PNG and many other formats are designed.

The drawback of being so lenient with whitespace and being case insensitive is that it constrains the parser to operate byte by byte. For example if uppercase was required and excess whitespace disallowed we could do this:
```c
void parse(char *first, char *last) {
  if (last - first < 4) {
    return;
  }
  uint32_t tag;
  memcpy(&tag, first, 4);
  switch (tag) {
  case AS_U32("INFO"):
  case AS_U32("PING"):
  etc
  }
}
```
Forcing all command lengths to 4 byte multiple would also help. `atoi` is PITA to implement in FPGA.

**Comment by derekcollison** [comment]
Yes we avoid atoi and do our own. Be interested in how this compares speed wise to what exists now if you send it just PING\r\n.

**Comment by rigtorp** [comment]
I'm closing this since this is intended behavior. Thanks for the interesting discussion.
