### ISSUE TITLE
Add REST-style API

### ISSUE THREAD

**Issue by rigtorp** [nats-io/nats-server#1036]
#### Use Case:
- My shell scripts in crontab needs to publish messages and do request over NATS
- I receive webhooks request that I'd like to publish to NATS
 
#### Proposed Change:
Ignoring auth and timouts considerations (needs to be worked out).

If I perform a POST request to https://nats/pub/SUBJECT the POST payload will be published to SUBJECT

If I perform a POST request to https://nats/req/SUBJECT the POST payload will be used as a request to SUBJECT, the reply will be returned as response to the request.

#### Who Benefits From The Change(s)?

Anyone who wants to easily interact with NATS from systems which don't allow persistent connections to NATS (CGI PHP PYTHON, shell scripts)

#### Alternative Approaches

User develops in-house REST bridge.

**Comment by derekcollison** [comment]
Possibly look at https://nats.io/blog/resgate_nats/

**Comment by rigtorp** [comment]
That looks a bit different than what I was looking for. Solace REST API is more what I am looking for https://docs.solace.com/RESTMessagingPrtl/Solace-REST-Overview.htm

Using curl to publish messages and send requests would be great.

**Comment by derekcollison** [comment]
We have had quite a few requests for this in some form or fashion, will take a deeper look. You could also write a simple program in Node.js or Go that does this I believe as well, if so inclined ;)

**Comment by rigtorp** [comment]
Yes and I probably will. But builtin REST and websocket support would be useful.

**Comment by derekcollison** [comment]
We agree, just a matter of priorities.

**Comment by beanhacker** [comment]
as nats is a fastest message  server i have ever tested, so i wan to imple a chat server based on nats, this will be best chat server for ever, but your team do not add this interface for us originally, all things can not do from web, that seriously limit the nats's use scenes, we need a highest priority for websocket api, 3Q

**Comment by derekcollison** [comment]
It is on our list for later in the year or early 2020. If you want that priority changed we are open to NRE based contracts for things we do plan to do.

**Comment by beanhacker** [comment]
even we do not need single chat bot server for ever, every thing based on nats, can complish what chat && bot && web notify server did ever, b/s will be one room.

**Comment by kgorin8** [comment]
Is this planned for release yet?

**Comment by ripienaar** [comment]
Websocket support is in our current master and released in nightly docker releases, it should be available in our next release somewhere near end of year.

**Comment by kgorin8** [comment]
> Websocket support is in our current master and released in nightly docker releases, it should be available in our next release somewhere near end of year.

what about REST?

**Comment by ripienaar** [comment]
Not planned at present.
