### ISSUE TITLE
Bug: Gateway connection with auth works only in one direction

### ISSUE THREAD

**Issue by wutkemtt** [nats-io/nats-server#1037]
- [ X ] Defect
 - [ ] Feature Request or Change Proposal
 
## Defects 

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ ] Included `gnatsd -DV` output
 - [ X ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)
 
#### Versions of `gnatsd` and affected client libraries used:
Nats-Server 2.0 RC 14

#### OS/Container environment:
Standalone NATS: Windows Server 2016
Nats Cluster: Azure AKS

#### Steps or code to reproduce the issue:
I want to connect to clusters via gateway connections. My 3 node cluster is running in Azure AKS, while I want to connect a single NATS running on an on-premise Windows Server 2016. I configured the gateway connections as described in the documentation with an authorization section to use a usernam/password for the connections. 
The outbound connection from standalone nats to the clusters works as configured. The returning inbound connection from the cluster does not work, because of an authorization error. 
It seems that the cluster do not use the configured authorization for the outgoing connection to the standalone nats.
 
#### Expected result:
All gateway connections are using the sam configured username and password and the connections could be established.
 
#### Actual result:
The outbound connection from standalone nats to the clusters works as configured. The returning inbound connection from the cluster does not work, because of an authorization error. 
It seems that the cluster do not use the configured authorization for the outgoing connection to the standalone nats. When I disable the authorization on the standalone nats the connection could be established.

Standalone NATS config:
`#Gateway configuration
gateway {
    name: "mynats-local"
    listen: 0.0.0.0:5222

    authorization {
        user: "gwuser"
        password: "gwpass"
    }
    reject_unknown: true

    gateways: [
        {name: "mynats", url: "nats-gateway://gwuser:gwpass@mynats-1:5222"},
        {name: "mynats", url: "nats-gateway://gwuser:gwpass@mynats-2:5222"},
        {name: "mynats", url: "nats-gateway://gwuser:gwpass@mynats-3:5222"}
    ]
}`

Cluster NATS config:
`#Gateway configuration
gateway {
    name: "mynats"
    listen: 0.0.0.0:5222

    authorization {
        user: "gwuser"
        password: "gwpass"
    }
    
    gateways: [
        {name: "mynats", url: "nats-gateway://gwuser:gwpass@mynats-1:5222"},
        {name: "mynats", url: "nats-gateway://gwuser:gwpass@mynats-2:5222"},
        {name: "mynats", url: "nats-gateway://gwuser:gwpass@mynats-3:5222"}
    ]
}`

Log-Output standalone NATS:
`[11684] 2019/06/07 11:50:37.437312 [DBG] Connecting to explicit gateway " mynats " (mynats-3:5222) at 10.xxx.xxx.xxx:5222 (attempt 1)
[11684] 2019/06/07 11:50:37.437312 [INF] Connecting to explicit gateway " mynats " (mynats-3:5222) at 10.xxx.xxx.xxx:5222 (attempt 1)
[11684] 2019/06/07 11:50:37.453312 [INF] 10.xxx.xxx.xxx:5222 - gid:10 - Creating outbound gateway connection to " mynats "
[11684] 2019/06/07 11:50:37.467313 [DBG] 10.xxx.xxx.xxx:5222 - gid:10 - Gateway connect protocol sent to " mynats "
[11684] 2019/06/07 11:50:37.467313 [INF] 10.xxx.xxx.xxx:5222 - gid:10 - Outbound gateway connection to " mynats " (XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX) registered
[11684] 2019/06/07 11:50:40.307157 [INF] 10.xxx.xxx.xxx:37528 - gid:193 - Processing inbound gateway connection
[11684] 2019/06/07 11:50:40.320158 [ERR] 10.xxx.xxx.xxx:37528 - gid:193 - authentication error - User ""
[11684] 2019/06/07 11:50:40.320158 [INF] 10.xxx.xxx.xxx:37528 - gid:193 - Gateway connection closed`

Log-Output NATS cluster:
`
[1] 2019/06/07 09:50:37.995689 [DBG] Attempting reconnect for gateway " mynats-local "
[1] 2019/06/07 09:50:38.047934 [DBG] Connecting to implicit gateway " mynats-local " (10.xxx.xxx.xxx:5222) at 10.xxx.xxx.xxx:5222 (attempt 1)
[1] 2019/06/07 09:50:38.047953 [INF] Connecting to implicit gateway " mynats-local " (10.xxx.xxx.xxx:5222) at 10.xxx.xxx.xxx:5222 (attempt 1)
[1] 2019/06/07 09:50:38.062281 [INF] 10.xxx.xxx.xxx:5222 - gid:9349 - Creating outbound gateway connection to " mynats-local "
[1] 2019/06/07 09:50:38.075414 [DBG] 10.xxx.xxx.xxx:5222 - gid:9349 - Gateway connect protocol sent to " mynats-local "
[1] 2019/06/07 09:50:38.075476 [INF] 10.xxx.xxx.xxx:5222 - gid:9349 - Outbound gateway connection to " mynats-local " (XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX) registered
[1] 2019/06/07 09:50:38.088483 [ERR] 10.xxx.xxx.xxx:5222 - gid:9349 - Gateway Error 'Authorization Violation'
[1] 2019/06/07 09:50:38.088499 [INF] 10.xxx.xxx.xxx:5222 - gid:9349 - Gateway connection closed `

**Comment by derekcollison** [comment]
The standalone server only needs one connection to the 3 node cluster. The cluster itself will form outbound to your single server for all nodes.

You might consider using leafnodes instead.

https://nats-io.github.io/docs/whats_new/whats_new_20.html#leaf-nodes
https://nats-io.github.io/docs/leafnodes/leafnode_conf.html

**Comment by kozlovic** [comment]
@wutkemtt This is not how you configure gateways. Gateways are meant to connect several clusters. So say that you have a cluster A and want to connect it to cluster B.
You would have something like:
```
gateway {
  name: "A"
  listen: "0.0.0.0:5222"
  gateways: [
      {
         name: "B"
         urls: [
              "nats://<clusterB_host_1>:5222",
              "nats://<clusterB_host_2>:5222",
              "nats://<clusterB_host_3>:5222",
         ]
  ]
}
```
Then cluster B would look like this:
```
gateway {
  name: "B"
  listen: "0.0.0.0:5222"
  gateways: [
      {
         name: "A"
         urls: [
              "nats://<clusterA_host_1>:5222",
              "nats://<clusterA_host_2>:5222",
              "nats://<clusterA_host_3>:5222",
         ]
  ]
}
```
You can find more information [here](https://nats-io.github.io/docs/gateways/gateway.html).

**Comment by wutkemtt** [comment]
Hi,
thanks for explaining the intended gateway config. Seems the documentation is a littlebit misleading here.

What if the cluster B should accept all gateway connections, because it acts as a central cluster where all satellite clusters should connect to?

I don't want to configure all those satellite gateway connections in cluster B. Furthermore each satellite cluster shouldn't know about the other satellite clusters. 

Is this a possible configuration based on the current version?

Best regards,
Matthias
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 13.06.19, 21:05, Ivan Kozlovic <notifications@github.com> schrieb:
@wutkemtt This is not how you configure gateways. Gateways are meant to connect several clusters. So say that you have a cluster A and want to connect it to cluster B.
You would have something like:
gateway {
  name: "A"
  listen: "0.0.0.0:5222"
  gateways: [
      {
         name: "B"
         urls: [
              "nats://<clusterB_host_1>:5222",
              "nats://<clusterB_host_2>:5222",
              "nats://<clusterB_host_3>:5222",
         ]
  ]
}

Then cluster B would look like this:
gateway {
  name: "B"
  listen: "0.0.0.0:5222"
  gateways: [
      {
         name: "A"
         urls: [
              "nats://<clusterA_host_1>:5222",
              "nats://<clusterA_host_2>:5222",
              "nats://<clusterA_host_3>:5222",
         ]
  ]
}

You can find more information here.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/nats-io/nats-server/issues/1037?email_source=notifications\u0026email_token=AK4USMD77A6XEYZJ37PSTGTP2KLATA5CNFSM4HVXYOMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXUXKPY#issuecomment-501839167",
"url": "https://github.com/nats-io/nats-server/issues/1037?email_source=notifications\u0026email_token=AK4USMD77A6XEYZJ37PSTGTP2KLATA5CNFSM4HVXYOMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXUXKPY#issuecomment-501839167",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by kozlovic** [comment]
As Derek mentioned, for hub and spoke design, leafnode are more suited. Gateways are supposed to form a "full mesh" of clusters.

**Comment by wutkemtt** [comment]
Thanks, we will re-arrange our cluster design regarding this new information.


-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 13.06.19, 21:49, Ivan Kozlovic <notifications@github.com> schrieb:
As Derek mentioned, for hub and spoke design, leafnode are more suited. Gateways are supposed to form a "full mesh" of clusters.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/nats-io/nats-server/issues/1037?email_source=notifications\u0026email_token=AK4USMEOHAMW4KLTN4TPVHDP2KQDRA5CNFSM4HVXYOMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXU2ZIQ#issuecomment-501853346",
"url": "https://github.com/nats-io/nats-server/issues/1037?email_source=notifications\u0026email_token=AK4USMEOHAMW4KLTN4TPVHDP2KQDRA5CNFSM4HVXYOMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXU2ZIQ#issuecomment-501853346",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Allan-Nava** [comment]
Is there any example ??
