### ISSUE TITLE
FR: exclusively tls connect option

### ISSUE THREAD

**Issue by paravz** [nats-io/nats-server#1044]
- [ ] Defect
 - [ x] Feature Request or Change Proposal
  
#### Use Case:
Allow TLS/SNI aware load balancing of nats traffic using reverse proxies (cloud ELBs, nginx and alike).
As seen in https://github.com/nats-io/nats-server/issues/291, in order to front nats-server with SSL-terminating AWS ELB, changes to nats client are required and nats-server has to be modified or run in plantext mode.
SNI based routing of nats traffic using nginx ssl_preread http://nginx.org/en/docs/stream/ngx_stream_ssl_preread_module.html is not working without changes to nats-server and nats-client.

#### Proposed Change:
Introduce a new non-default configuration option (and/or a command line switch) to enable TLS-only communication between nats client and server.

Perhaps `--force-tlsonly' ?

#### Who Benefits From The Change(s)?
Anyone who wants to run TLS-enabled nats-server behind a reverse proxy.

#### Alternative Approaches
Maintain custom nats clients and servers with TLS only enabled, as outlined for python and golang in https://github.com/nats-io/nats-server/issues/291

**Comment by derekcollison** [comment]
If the intermediate is only redirecting at the TCP level should work. If they do not then they are terminating TLS on their own which we do not suggest.

**Comment by paravz** [comment]
Yes, it works on TCP level. But that's not the scenario this tries to solve.
