### ISSUE TITLE
export readOperatorJWT

### ISSUE THREAD

**Issue by ripienaar** [nats-io/nats-server#1050]
#### Use Case

User who embed NATS would want to be able to set up accounts, having this exported will greatly simplify things by making it easier to set trusted operators

https://github.com/nats-io/nats-server/blob/54fefe36c633e26d67f3525584131c14ebbd6d3f/server/opts.go#L608
 
#### Proposed Change:
 
Export readOperatorJWT

#### Who Benefits From The Change(s)?

People who embed nats
 
#### Alternative Approaches

everyone reimpliment this code

**Comment by ripienaar** [comment]
I think we'd also need `validateTrustedOperators` as that sets all the TrustedKeys

**Comment by ripienaar** [comment]
and server.processTrustedKeys sets server.trustedKeys none of which are exported. I dont think people who embed nats can today set up accounts properly

**Comment by derekcollison** [comment]
Do you have a config file or want to configure the server options programmatically?

**Comment by ripienaar** [comment]
Programmatically

**Comment by derekcollison** [comment]
ok will fix.
