### ISSUE TITLE
Shutdown Demo nats server

### ISSUE THREAD

**Issue by marshallwalker** [nats-io/nats-server#1051]
I've connected to the demo NATS server at nats://demo.nats.io and subscribed on '>' this allows me to see all messages and I've come to the realization that some people are using the DEMO nats server to send sensitive data including but not limited to BANK INFORMATION..

**Comment by derekcollison** [comment]
Yes the NATS demo servers are wide open for experimentation and no production traffic or personal information should be sent on this system.

**Comment by DreadKyller** [comment]
I think you misunderstood. He is aware that no personal or production traffic should be sent on the system. He is informing you that there are people doing so. There is some user using the demo NATs server to sending information that currently shows Names, Social Security Numbers, emails, and phone numbers as well as insurance company names and IDs, possibly for processing insurance claims. The information is unencryped and very dangerous to have going over the public servers.

Marshall is not the one sending this data, someone else is, he simply noticed it while subscribing to the ">" channel. He's asking if there's anything you can do to stop this particular user's traffic, like blocking an IP.

**Comment by derekcollison** [comment]
I understood what he was saying. The server is open to use as one sees fit. I agree with you that it's very unfortunate to have someone using it to test out with people's personal data. However, we do not have a practice of blocking people at this point unless a law has been broken. Hopefully the person will realize and stop the behavior. I looked earlier this am and did not see any traffic like that.

**Comment by derekcollison** [comment]
I just did the following which killed the app that looked suspicious. Hopefully if they have logs they will see it.

`> nats-pub -s demo.nats.io UPDATED.person.email "PLEASE DO NOT SHARE PUBLIC INFORMATION ON THIS NATS DEMO SERVER =derek"`
