### ISSUE TITLE
Nats Cluster TLS connections

### ISSUE THREAD

**Issue by zackws** [nats-io/nats-server#1058]
Hello all, 

We tried setting up a NATS cluster with TLS, we got some errors like:
Bad certificate...
unknown authority ... and so one.

Did anyone try setting a cluster using TLS before? if Yes could you please show us how did you do that?

Thanks.

**Comment by ripienaar** [comment]
The errors are unfortunately not helpful, but yes I successfully run it.

bad cert = probably a certificate that isnt allowed to make client connections or make listening connections depending on context
unknown authority - you need to add the cafile

**Comment by zackws** [comment]
Thanks,
Just to make us understand the concept, I'm trying to do a cluster of 2 Nats server on the same machine with this configuration file:
#tls {
  #cert_file: "./nats.crt"
  #key_file:  "./nats.key"
 # timeout:   2
#}

cluster {
  listen: Broker0:1222

  tls {
    # Route cert
    cert_file: "./certs/server-cert.pem"
    # Private key
    key_file:  "./certs/server-key.pem"
    # Optional certificate authority verifying connected routes
    # Required when we have self-signed CA, etc.
    ca_file:   "./certs/ca_broker0.pem"
  }
  # Routes are actively solicited and connected to from this server.
  # Other servers can connect to us if they supply the correct credentials
  # in their routes definitions from above.
  #routes = [
  #  nats-route://localhost:1211
  #]
}

PS: for the second server, i ve just uncommented the routes and changed the cluster port.

* I'm getting this error now:
**seed:**
 TLS route handshake error: tls: failed to verify client's certificate: x509: certificate specifies an incompatible key usage
**worker**
TLS route handshake error: remote error: tls: bad certificate

So, have you been familiar with this errors? I'think we dont understand how the TLS works.
Thanks alot.

**Comment by ripienaar** [comment]
Please edit the comment, select each code snippet individually and hit the "insert code" button so it becomes readable :)

**Comment by ripienaar** [comment]
`certificate specifies an incompatible key usage` tells you that you made your certificate and did not specify the correct roles for the certificate, certificates can be resrtricted to server only, client only etc - meaning you cant use a client only certificate to open a listening port and secure a network service.  But if you are giving it to NATS to open its port with - you will need the right roles set

bad cert is probably the other half of the same error - just the other side of the connection saying its not sure whats up but something is up.

Maybe show us output of `openssl x509 -in cert.pem -text -noout`

**Comment by wallyqs** [comment]
@zackws here is a guide I wrote for creating these certs some time ago: https://gist.github.com/wallyqs/ee5693740592c3eee2f72faab706489b  if using cfssl for creating the certs make sure that you specify `"server auth"` as part of the usages for the routes to avoid the `incompatible key usage` error:

```
                "usages": [
                    "signing",
                    "key encipherment",
                    "server auth",
                    "client auth"
                ]
```

**Comment by zackws** [comment]
@wallyqs Thanks a lot, but I couldnt ispire myself from your tutorial, could you just help me to do a network bridge for two NATS server in TLS please?
Regards,

**Comment by wallyqs** [comment]
@zackws what tool are you more familiar to generate the TLS certs? can you share more about the environment where creating the NATS cluster?

**Comment by zackws** [comment]
@wallyqs Yes sure! So i'm using openssl to generate the certs in 2 ubuntu VMs on Azure cloud, each VM has a NATS servre installed.

Thanks.

**Comment by csi21** [comment]
Hi, sorry to intrude on the discussion. I am having a similar problem, just wondering if you were able to solve it.

Thanks

**Comment by matthiashanel** [comment]
@csi21, we have recently changed our documentation to include an explanation of the ins/outs of certificates (and a way to generate them).
https://docs.nats.io/nats-server/configuration/securing_nats/tls#self-signed-certificates-for-testing
would you say that helps?

**Comment by csi21** [comment]
yes, thank you! @matthiashanel

**Comment by bruth** [comment]
Closing as resolved.
