### ISSUE TITLE
Support InsecureSkipVerify again

### ISSUE THREAD

**Issue by ripienaar** [nats-io/nats-server#1062]
- [x] Feature Request or Change Proposal
 
#### Use Case:

Internal use, testing, enterprise systems running in black box style appliances we cant change and countless other situations make having the option to disable TLS verify worth having.

Discussions with @derekcollison centered around Ruby got burned lets not reproduce the mistakes but I think the situation is not the same.  Ruby got burned because many widely used libraries DEFAULTED to essentially `InsecureSkipVerify=true` thus making the whole internet more insecure.  What I am asking is not to default to that, but not to remove the support for this feature.  This does not make the world worse and gives people who make a specific decision to disable it the ability to do so. Ruby internally also had issues where they would not do hostname verification even when OpenSSL::SSL::VERIFY_PEER is configured.  Again not the issue here, you are by default at an appropriate security level - but people should have the choice to opt out of that.  Especially those who vendor the server
 
#### Proposed Change:
 
https://github.com/nats-io/nats-server/blob/94071d32a98d86d26431ee9405e6b0f19b1994c5/server/server.go#L312-L316

https://github.com/nats-io/nats-server/blob/94071d32a98d86d26431ee9405e6b0f19b1994c5/server/gateway.go#L234-L236

https://github.com/nats-io/nats-server/blob/94071d32a98d86d26431ee9405e6b0f19b1994c5/server/gateway.go#L244-L246

Remove that restriction.

**Comment by kozlovic** [comment]
We are looking into this.
