### ISSUE TITLE
memory increase in clustered mode

### ISSUE THREAD

**Issue by ripienaar** [nats-io/nats-server#1082]
This is a follow on from https://github.com/nats-io/nats-server/issues/1065

While looking into the above issue I noticed memory growth, we wanted to focus on one issue at a time so with 1065 done I looked at the memory situation.  The usage patterns and so forth is identical to 1065.

![12 hours](https://i.imgur.com/TwPlClx.png)

Above is 12 hours, now as you know I embed your broker into one of my apps and I run a bunch of things in there.  However in order to isolate the problem I did a few things:

1. Same version of everything with the same usage pattern on a single unclustered broker does not show memory growth
1. Turning off all the related feature in my code where I embed nats-server when clustered I still see the growth
1. I made my code respond to SIGQUIT to write memory profiles on demand so I can interrogate a running nats server

The nats-server is `github.com/nats-io/nats-server/v2                                 v2.0.3-0.20190723153225-9cf534bc5e97`

From above memory dumps when comparing 6 hours apart dumps I see:

8am:
```
(pprof) top10
Showing nodes accounting for 161.44MB, 90.17% of 179.04MB total
Dropped 66 nodes (cum <= 0.90MB)
Showing top 10 nodes out of 51
      flat  flat%   sum%        cum   cum%
   73.82MB 41.23% 41.23%    73.82MB 41.23%  github.com/nats-io/nats-server/v2/server.(*client).queueOutbound
   29.18MB 16.30% 57.53%    29.68MB 16.58%  github.com/nats-io/nats-server/v2/server.(*Server).createClient
   19.60MB 10.95% 68.48%    19.60MB 10.95%  math/rand.NewSource
   15.08MB  8.42% 76.90%   140.30MB 78.37%  github.com/nats-io/nats-server/v2/server.(*client).readLoop
    6.50MB  3.63% 80.53%       12MB  6.70%  github.com/nats-io/nats-server/v2/server.(*client).processSub
    5.25MB  2.93% 83.46%    11.25MB  6.28%  github.com/nats-io/nats-server/v2/server.(*Sublist).Insert
    4.01MB  2.24% 85.70%    65.85MB 36.78%  github.com/nats-io/nats-server/v2/server.(*client).processInboundClientMsg
    3.50MB  1.95% 87.65%     3.50MB  1.95%  github.com/nats-io/nats-server/v2/server.newLevel
    2.50MB  1.40% 89.05%     2.50MB  1.40%  github.com/nats-io/nats-server/v2/server.newNode
       2MB  1.12% 90.17%        2MB  1.12%  github.com/nats-io/nats-server/v2/server.(*client).addSubToRouteTargets
```

1pm

```
(pprof) top10
Showing nodes accounting for 185.64MB, 90.87% of 204.29MB total
Dropped 69 nodes (cum <= 1.02MB)
Showing top 10 nodes out of 46
      flat  flat%   sum%        cum   cum%
   86.33MB 42.26% 42.26%    86.33MB 42.26%  github.com/nats-io/nats-server/v2/server.(*client).queueOutbound
   30.19MB 14.78% 57.04%    30.69MB 15.02%  github.com/nats-io/nats-server/v2/server.(*Server).createClient
   25.75MB 12.60% 69.64%   165.05MB 80.79%  github.com/nats-io/nats-server/v2/server.(*client).readLoop
   19.60MB  9.59% 79.24%    19.60MB  9.59%  math/rand.NewSource
    6.50MB  3.18% 82.42%    12.55MB  6.14%  github.com/nats-io/nats-server/v2/server.(*client).processSub
    5.25MB  2.57% 84.99%    11.25MB  5.51%  github.com/nats-io/nats-server/v2/server.(*Sublist).Insert
    4.02MB  1.97% 86.95%    73.70MB 36.08%  github.com/nats-io/nats-server/v2/server.(*client).processInboundClientMsg
    3.50MB  1.71% 88.67%     3.50MB  1.71%  github.com/nats-io/nats-server/v2/server.newLevel
    2.50MB  1.22% 89.89%     2.50MB  1.22%  github.com/nats-io/nats-server/v2/server.newNode
       2MB  0.98% 90.87%        2MB  0.98%  github.com/nats-io/nats-server/v2/server.(*client).addSubToRouteTargets
```

**Comment by ripienaar** [comment]
```
(pprof) list queueOutbound
Total: 179.04MB
ROUTINE ======================== github.com/nats-io/nats-server/v2/server.(*client).queueOutbound in /go/pkg/mod/github.com/nats-io/nats-server/v2@v2.0.3-0.20190723153225-9cf534bc5e97/server/client.go
   73.82MB    73.82MB (flat, cum) 41.23% of Total
         .          .   1356:           if c.out.s != nil && cap(c.out.s) >= int(c.out.sz) {
         .          .   1357:                   c.out.p = c.out.s
         .          .   1358:                   c.out.s = nil
         .          .   1359:           } else {
         .          .   1360:                   // FIXME(dlc) - make power of 2 if less than maxBufSize?
   59.73MB    59.73MB   1361:                   c.out.p = make([]byte, 0, c.out.sz)
         .          .   1362:           }
         .          .   1363:   }
         .          .   1364:   // Determine if we copy or reference
         .          .   1365:   available := cap(c.out.p) - len(c.out.p)
         .          .   1366:   if len(data) > available {
         .          .   1367:           // We can't fit everything into existing primary, but message will
         .          .   1368:           // fit in next one we allocate or utilize from the secondary.
         .          .   1369:           // So copy what we can.
         .          .   1370:           if available > 0 && len(data) < int(c.out.sz) {
         .          .   1371:                   c.out.p = append(c.out.p, data[:available]...)
         .          .   1372:                   data = data[available:]
         .          .   1373:           }
         .          .   1374:           // Put the primary on the nb if it has a payload
         .          .   1375:           if len(c.out.p) > 0 {
         .          .   1376:                   c.out.nb = append(c.out.nb, c.out.p)
         .          .   1377:                   c.out.p = nil
         .          .   1378:           }
         .          .   1379:           // Check for a big message, and if found place directly on nb
         .          .   1380:           // FIXME(dlc) - do we need signaling of ownership here if we want len(data) < maxBufSize
         .          .   1381:           if len(data) > maxBufSize {
         .          .   1382:                   c.out.nb = append(c.out.nb, data)
         .          .   1383:                   referenced = true
         .          .   1384:           } else {
         .          .   1385:                   // We will copy to primary.
         .          .   1386:                   if c.out.p == nil {
         .          .   1387:                           // Grow here
         .          .   1388:                           if (c.out.sz << 1) <= maxBufSize {
         .          .   1389:                                   c.out.sz <<= 1
         .          .   1390:                           }
         .          .   1391:                           if len(data) > int(c.out.sz) {
         .          .   1392:                                   c.out.p = make([]byte, 0, len(data))
         .          .   1393:                           } else {
         .          .   1394:                                   if c.out.s != nil && cap(c.out.s) >= int(c.out.sz) { // TODO(dlc) - Size mismatch?
         .          .   1395:                                           c.out.p = c.out.s
         .          .   1396:                                           c.out.s = nil
         .          .   1397:                                   } else {
   14.08MB    14.08MB   1398:                                           c.out.p = make([]byte, 0, c.out.sz)
         .          .   1399:                                   }
         .          .   1400:                           }
         .          .   1401:                   }
         .          .   1402:                   c.out.p = append(c.out.p, data...)
         .          .   1403:           }
```

**Comment by ripienaar** [comment]
I should mention I do appear to have gained 10 new long running connections in this period - but connection counts are basically flat things come and then go again soon after. There's no correlated growth in number of connections, subscriptions or go routines that track this trend line.

**Comment by derekcollison** [comment]
If the route connection is dropped and allowed to immediately re-establish itself, does it affect the memory usage? Is that possible to try?

**Comment by ripienaar** [comment]
well, i firewalled it for a while till routez showed both dropped, after that it never recovered it looped basically forever on 

```
"10.60.18.180:65353 - rid:9597 - Readloop processing time: 5.002888972s","time":"2019-07-25T14:17:26Z
"10.60.18.180:65353 - rid:9597 - Router connection closed"
"10.60.18.180:65357 - rid:9599 - Route connection created"
"10.60.18.180:6164 - rid:9600 - Route connection created"
"10.60.18.180:6164 - rid:9600 - Router connection closed"
"10.60.18.180:65357 - rid:9599 - Slow Consumer Detected: WriteDeadline of 5s exceeded with 2 chunks of 131059 total bytes."
```

retarting one fixed this loop but unfortunately then 1/2 of the 7k clients connected to the remaining one and so balooned the memory.

I'll have to try another way I guess

**Comment by derekcollison** [comment]
Hmm, odd. How many subscriptions did you have approximately at that point that would need to be transferred over to the remote?

**Comment by ripienaar** [comment]
51373 subscriptions were roughly 50:50 shared.

I kepts the firewall up for a good 15 minutes and the one node showed no connections in routez for most of that, during that time its memory didnt drop. But tbh its just not really a good test the way this went down, I'll try something else tomorrow morning when the problem have come back

**Comment by ripienaar** [comment]
this is pretty ugly but this is the graph of memory while the route was dropped 

![](https://imgur.com/BWacG2D.png)

route dropped at 16:09, its not big enough of a drop imo to say that dropping the route cleared away the consumed memory - might have after some GC cycles or something, alas thats the best i can tell from this attempt :)

**Comment by derekcollison** [comment]
What version of Go?

**Comment by ripienaar** [comment]
go1.12.6

**Comment by derekcollison** [comment]
Be interested to see if this changes at all with 1.11.x

**Comment by kozlovic** [comment]
We should clarify if we think this is a "leak" or simply the Go GC being "lazy". We could add manual call to runtime.GC() to clear that up, or I guess tune `GOGC=` env?

**Comment by ripienaar** [comment]
if its a go behaviour then my unclustered one should also be going up in memory consumption - thats my gut feel about this anyway, same patterns (though fewer nodes) its stable and flat.  Same binary with clustering enable its growing consistently over a day

**Comment by kozlovic** [comment]
Well no, because in cluster mode, you have the route that needs to send things, which would not be there in unclustered mode. My point is that if you were to let the thing go for much longer, would it continue to grow for ever (leak) or then stabilize (GC thing). Adding manual runtime.GC() would affect performance, but as a test, would reassure us if this is simply a GC thing or a leak.
Furthermore, is the output from alloc_space or inuse_space?

**Comment by ripienaar** [comment]
During 1065 I let it run for 4 days it just went up - but that could well have been 1065 contributing.  I will build with 1.11.x and we can compare and sure we can leave it over a weekend.

**Comment by ripienaar** [comment]
I can probably also take another cluster and configure up 1.11.x there leaving this one to 1.12.6. I think our next smallest cluster is around 10k clients

**Comment by ripienaar** [comment]
From the normal probmetheus exporter gathered data its `go_memstats_heap_inuse_bytes`

**Comment by ripienaar** [comment]
![](https://i.imgur.com/BSwZRgE.png)

just for completeness really, here's the same code over 6 hours unclustered, here I have only 1.1k clients and unfortunately long running clients come and go as its a lab so its less stable in client counts than the problem set but you can see its just flat basically.

**Comment by ripienaar** [comment]
fwiw memory increase remains on the same trajectory on 1.12.6, we can probably discount "lazy" gc.

**Comment by kozlovic** [comment]
You probably meant on 1.11.x? Anyway, looking at this at the moment...

**Comment by ripienaar** [comment]
I have not had a chance to recompile to 1.11.x I am using 1.12.6 for these.  Had a production issue today so not had time to do that.

**Comment by kozlovic** [comment]
Using the setup described in other issue with 2 docker running official image v2.0.2 and 10 nats-rply and your script to send requests. Will let this run for a while and see. I run the servers with `-profile 6060` and then collect the heap with this:
```
wget -q http://<ip>:6060/debug/pprof/heap
```
then to check inuse_space:
```
iMacSynadia:~ ivan$ go tool pprof --inuse_space heap 
File: nats-server
Type: inuse_space
Time: Jul 26, 2019 at 5:21pm (MDT)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 53.75MB, 99.08% of 54.25MB total
Showing top 10 nodes out of 22
      flat  flat%   sum%        cum   cum%
   39.24MB 72.34% 72.34%    44.74MB 82.48%  github.com/nats-io/nats-server/server.(*Server).createClient
       4MB  7.38% 79.72%        4MB  7.38%  github.com/nats-io/nats-server/server.(*Server).saveClosedClient
       3MB  5.53% 85.25%        3MB  5.53%  github.com/nats-io/nats-server/server.(*client).processSub
    2.50MB  4.61% 89.86%     2.50MB  4.61%  github.com/nats-io/nats-server/server.(*client).queueOutbound
    1.50MB  2.77% 92.63%     1.50MB  2.77%  fmt.Sprintf
       1MB  1.84% 94.47%        1MB  1.84%  sync.NewCond (inline)
       1MB  1.84% 96.31%     3.50MB  6.45%  github.com/nats-io/nats-server/server.(*client).initClient
    0.50MB  0.92% 97.23%     0.50MB  0.92%  github.com/nats-io/nats-server/server.(*client).processRemoteSub
    0.50MB  0.92% 98.16%        1MB  1.84%  github.com/nats-io/nats-server/server.(*Sublist).Match
    0.50MB  0.92% 99.08%     1.50MB  2.77%  github.com/nats-io/nats-server/server.(*client).getAccAndResultFromCache
```
Will run that from time to time and also do same for second server.
I am also checking the "mem" from `/varz`.

Will keep you posted.

**Comment by ripienaar** [comment]
I got time to rebuild code with 1.11 and same memory growth observed

**Comment by derekcollison** [comment]
ok thanks, we will track it down.

**Comment by kozlovic** [comment]
@ripienaar Just to let you know that I can reproduce the growth when in cluster mode. Trying hard to track this down since this weekend. Will update you as soon as I find something. Thanks for the patience.

**Comment by ripienaar** [comment]
@kozlovic thats good news, thank you :)

**Comment by kozlovic** [comment]
@ripienaar We have tracked down the reason for the memory increase. It should be somehow bounded: the reason is that connections are retained due to a route cache referencing some subscriptions, and therefore the subs' connection. That is somehow normal, but the connection's buffer were not cleared on connection close, so that caused that memory from being still reachable. We are working also in trying to prune closed subscriptions from this cache from time to time. Stay tune for a branch/PR you could test from if desired.

**Comment by kozlovic** [comment]
I have merged a fix for this in master (which closed automatically the issue, I have re-opened it). If you get a chance to test from master, it would be great. Will give you a chance to experiment before closing this issue. Thanks again for the report.

**Comment by ripienaar** [comment]
nice thanks a lot, I have done a build and rolled it out, should know in the morning how it turned out

**Comment by derekcollison** [comment]
Great, thanks RI.

**Comment by ripienaar** [comment]
I see some growth still, between `Time: Jul 30, 2019 at 6:50pm (CEST)` and `Time: Jul 31, 2019 at 7:56am (CEST)` I get:

```
(pprof) top10
Showing nodes accounting for 130.65MB, 90.90% of 143.73MB total
Dropped 47 nodes (cum <= 0.72MB)
Showing top 10 nodes out of 30
      flat  flat%   sum%        cum   cum%
   30.25MB 21.05% 21.05%    30.25MB 21.05%  github.com/nats-io/nats-server/v2/server.(*client).queueOutbound
   23.65MB 16.45% 37.50%    24.81MB 17.26%  github.com/nats-io/nats-server/v2/server.(*Server).createClient
   21.72MB 15.11% 52.61%   101.33MB 70.50%  github.com/nats-io/nats-server/v2/server.(*client).readLoop
   20.61MB 14.34% 66.95%    20.61MB 14.34%  math/rand.NewSource
   11.42MB  7.95% 74.89%    16.92MB 11.77%  github.com/nats-io/nats-server/v2/server.(*Sublist).Insert
    6.50MB  4.52% 79.42%     6.50MB  4.52%  github.com/nats-io/nats-server/v2/server.(*Server).saveClosedClient
       6MB  4.18% 83.59%    16.38MB 11.39%  github.com/nats-io/nats-server/v2/server.(*client).processSub
       5MB  3.48% 87.07%        5MB  3.48%  runtime.malg
       3MB  2.09% 89.16%        3MB  2.09%  github.com/nats-io/nats-server/v2/server.newNode
    2.50MB  1.74% 90.90%     2.50MB  1.74%  github.com/nats-io/nats-server/v2/server.newLevel
```

```
(pprof) top10
Showing nodes accounting for 142.29MB, 90.42% of 157.37MB total
Dropped 38 nodes (cum <= 0.79MB)
Showing top 10 nodes out of 33
      flat  flat%   sum%        cum   cum%
   30.85MB 19.61% 19.61%   114.96MB 73.05%  github.com/nats-io/nats-server/v2/server.(*client).readLoop
   30.75MB 19.54% 39.15%    30.75MB 19.54%  github.com/nats-io/nats-server/v2/server.(*client).queueOutbound
   24.65MB 15.67% 54.81%    25.82MB 16.41%  github.com/nats-io/nats-server/v2/server.(*Server).createClient
   21.11MB 13.41% 68.22%    21.11MB 13.41%  math/rand.NewSource
   11.42MB  7.26% 75.48%    16.92MB 10.75%  github.com/nats-io/nats-server/v2/server.(*Sublist).Insert
    6.50MB  4.13% 79.61%     6.50MB  4.13%  github.com/nats-io/nats-server/v2/server.(*Server).saveClosedClient
       6MB  3.81% 83.42%    16.38MB 10.41%  github.com/nats-io/nats-server/v2/server.(*client).processSub
       5MB  3.18% 86.60%        5MB  3.18%  runtime.malg
       3MB  1.91% 88.51%        3MB  1.91%  github.com/nats-io/nats-server/v2/server.(*client).addSubToRouteTargets
       3MB  1.91% 90.42%        3MB  1.91%  github.com/nats-io/nats-server/v2/server.newNode
```

Built with `go1.12.6`

You can see the average creeping up in this graph, it's vastly improved but we still got some unexpected growth

![](https://i.imgur.com/b0ZAd0S.png)

**Comment by derekcollison** [comment]
Thanks will take a look. Be good to eliminate normal GC params.

**Comment by ripienaar** [comment]
Thanks, not sure what you mean with `Be good to eliminate normal GC params.` though

**Comment by derekcollison** [comment]
Let see if growth stops at some point and where. Also default values on 1.12.x IIRC will let the app use more memory by default.

**Comment by kozlovic** [comment]
Yes, from the inuse_space report, it doesn't look like it is growing much, so I would let this run for longer. The overall process usage may increase but if you see the inuse_space stable, there is not much we can do.
Note that the fix is not removing the cache, so there will still be objects referenced.

**Comment by ripienaar** [comment]
Agree its not growing by a lot - but by its nature this is software that should basically run forever right? A leak of around 30MB/day where many connections come and go is quite significant.

**Comment by kozlovic** [comment]
Yes, but if possible I would like to see it run longer. If the inuse_space is not growing (like it used to) then we have to look more of tuning of the GC.. the point is that if the memory is not in use and still process size is growing, it has to be that the GO runtime does not want to release the memory back because it thinks that it is going to be used again. 
I am not arguing that there is still not a problem, but need to look at the inuse_space top report to see if there is growth there.

**Comment by ripienaar** [comment]
Sure no problem, as is I'll leave them for however long you like its not going to cause us imminent issues.

**Comment by kozlovic** [comment]
Thank you for all the help!

**Comment by vickov** [comment]
A

**Comment by ripienaar** [comment]
I had a look, things appear to be a bit more flat today though still on the up.  Lets leave it till next week and we will have a solid set of data.

**Comment by ripienaar** [comment]
![](https://i.imgur.com/61ozKJQ.png)

above is July 30 to August 5th, long running connections have remained stable while of course constant coming and going of short lived ones.

```
(pprof) top10
Showing nodes accounting for 155.04MB, 89.45% of 173.33MB total
Dropped 37 nodes (cum <= 0.87MB)
Showing top 10 nodes out of 40
      flat  flat%   sum%        cum   cum%
   44.98MB 25.95% 25.95%    44.98MB 25.95%  github.com/nats-io/nats-server/v2/server.(*client).queueOutbound
   33.87MB 19.54% 45.50%   132.91MB 76.68%  github.com/nats-io/nats-server/v2/server.(*client).readLoop
   26.16MB 15.09% 60.59%    27.83MB 16.06%  github.com/nats-io/nats-server/v2/server.(*Server).createClient
   20.10MB 11.60% 72.19%    20.10MB 11.60%  math/rand.NewSource
    9.92MB  5.72% 77.91%    14.92MB  8.61%  github.com/nats-io/nats-server/v2/server.(*Sublist).Insert
    6.50MB  3.75% 81.66%    16.58MB  9.57%  github.com/nats-io/nats-server/v2/server.(*client).processSub
       5MB  2.89% 84.55%        5MB  2.89%  runtime.malg
    3.50MB  2.02% 86.57%     3.50MB  2.02%  github.com/nats-io/nats-server/v2/server.newLevel
    2.50MB  1.44% 88.01%        3MB  1.73%  github.com/nats-io/nats-server/v2/server.(*Server).saveClosedClient
    2.50MB  1.44% 89.45%     2.50MB  1.44%  github.com/nats-io/nats-server/v2/server.addNodeToResults
```

**Comment by derekcollison** [comment]
ok past 8/3 would you consider that flat? Look like it may have settled on its GC cycle IMO.

WDYT?

**Comment by ripienaar** [comment]
Does appear so. I am concerned that you do not forget entirely a connection or subscription related data. That will only go up to the right in time. Why did we not fully forget that cached data?

I am out this week so I will leave it running and see how it trends but I am not really super comfortable that the problem is gone gone.

**Comment by derekcollison** [comment]
I think leaving it running is good. We have a cache in the readloop on each end of a route that we use without locks (only readloop accesses) for quick lookup of accounts and result sets etc. That is where the memory for a disconnected client was still camping out per se. 

We could look at being more aggressive at cleaning the cache of dead items, but the cache itself is bound, so in theory that will stop. Your use case was filling up items with very short lived connections.

**Comment by ripienaar** [comment]
gonna close this, i think it stabalizes just takes a long time.
