### ISSUE TITLE
Support Msg.PartitionKey for QueueSub 

### ISSUE THREAD

**Issue by haoch** [nats-io/nats-server#1083]
Is possible for NATS to support partition key for QueueSub so that Subscriber instances could handle all message in the same __partition key__ __in order__? It will be good to scale up for lots of use cases.

`msg{seq, key}`

If key provided:

```
Pub*.Send([msg{1, 1}, msg{2, 1}, msg{2,2}, msg{3,3}, ...]) 

=> NATS Server =>

Sub1.Receive([msg{1,1}, msg{2,1}]) // Key: 1
Sub2.Receive([msg{2,2}]) // Key: 2
Sub3.Receive([msg{3,3}]) // Key: 3
```

If key not provided, then use `round-robin` strategy.

**Comment by derekcollison** [comment]
Want to get a bit more information on what you are trying to achieve. I believe you can do that today by sending to different subs and having queue groups for each sub, but I may be missing the actual use case.

Just for clarity, why does a single subject and single DQ not work atm?

**Comment by haoch** [comment]
The queue group does not guarantee `groupBy` semantics. 
For example like events with the session id, and having multiple publishers and multiple subscribers instances (may have more for scale) in a single subject and single DQ, it will not guarantee events in the same session-id will always go the same subscriber instance.

**Comment by derekcollison** [comment]
Should sessionid be part of the publish to subject with a default if one is not present?

**Comment by haoch** [comment]
The default value may be null. My point is lots of people would like to use NATS as a lightweight solution to replace Kafka in kubernetes, but key-based partition with order guarantee is not supported in NATS.

**Comment by derekcollison** [comment]
Yes understood, I am not sure its that important with a proper system so am trying to understand whether it is a use case we should really consider or a limitation of Kafka.

**Comment by haoch** [comment]
I think it's a common horizontal scalability pattern required by lots of typical use cases needing a message affinity key.

**Comment by tylertreat** [comment]
FWIW in Kafka messages are partitioned on the _client_, so ultimately it's the client's responsibility for deciding which partition to write a message to. I think having a bit more control over queue group behavior could be nice in NATS, but you can implement behavior similar to Kafka at a higher level by partitioning a NATS subject (e.g. "foo" => "foo.0", "foo.1", "foo.2", etc.) and having publishers assign messages to a partition (e.g. hash a message attribute and mod by number of partitions). This gives you full control over the partition assignment, and you can scale consumption of a partition as normal with a queue group (assuming you don't need in-order processing—if you do, you can only have a single consumer anyway).

See [this](https://github.com/liftbridge-io/liftbridge/issues/81) for an example of how I'm planning to do this on top of NATS in Liftbridge.

**Comment by kozlovic** [comment]
@haoch None of this would be possible without introducing either message headers (which we have resisted to do so far) or change the client-to-server protocol.
As Derek and Tyler have mentioned, you can partition by sending to sub-subjects of your choosing. I do understand that you mention the need for receiving messages on a given partition in order, which would force you to have a single consumer (which I think you understand), but the server would not prevent from starting multiple consumers on a given subject.

**Comment by haoch** [comment]
I understand that NATS stands for low-level messaging transport, but it's also not a good way to keep compatibility and management work to the application side. Is there any middleware upon NATS help about such semantics? Without changing the protocol, it could have an internal KeyedMsg{key, msg} wrapper based on existing NATS protocol.

**Comment by wallyqs** [comment]
@haoch maybe you could combine queue subscriptions and unique inboxes subscriptions for this? Just an example, but you could have a number of queue subscribers that can be horizontally scaled up/down that reply with their own inbox against which the messages can be sent in order: https://gist.github.com/wallyqs/3c2a92e1fee8ee1a086c0a8a1af01712

**Comment by haoch** [comment]
@wallyqs Thanks, it works but I just think it may be more nature if the middleware infra to support internally. Anyway, thanks everyone @derekcollison @kozlovic @tylertreat!
