### ISSUE TITLE
Misleading error message: Unable to start NATS Server in Go Routine

### ISSUE THREAD

**Issue by tehsphinx** [nats-io/nats-server#1097]
- [ ] Defect
 - [x] Feature Request or Change Proposal
 
## Feature Requests
 
Note: for all details (including Code) see my [StackOverflow question](https://stackoverflow.com/questions/57464569/unable-to-start-nats-server-in-go-routine-while-testing). 

#### Use Case:
When testing I want a nats server instance per test. I started and stopped it per test so a fix port seemed fine at first. 

#### Proposed Change:
I then got the error message "Unable to start NATS Server in Go Routine". The problem seemed to be that the port I gave to the NATS test server was already in use.
 
#### Who Benefits From The Change(s)?
Developers running into the same issue.
 
#### Alternative Approaches
What about an error message when starting the server if it was actually able to bind to the port?

**Comment by derekcollison** [comment]
You can start a server with -1 for the port and it will allocate the port dynamically. To connect in your test use `s.ClientURL()` to pass to `nats.Connect()`

**Comment by tehsphinx** [comment]
@derekcollison: This is not about solving my issue. I've solved that a long time ago.

This is about a misleading error message (to put it nicely, because the error message is actually wrong!!):

Incorrect error message:
"Unable to start NATS Server in Go Routine"

**Comment by derekcollison** [comment]
ok I guess we are all used to it from running so many tests. Will reopen and leave here. Feel free to submit a PR if its a high priority for you.

**Comment by ilyadt** [comment]
The solution for me was to add 
`GODEBUG=x509sha1=1` before command

P.S. go1.18.3

**Comment by derekcollison** [comment]
Closing for now, feel free to re-open if needed.
