### ISSUE TITLE
Feature Request: Subject syntax for wildcard exclusion, specific multiple subject subscription/publish

### ISSUE THREAD

**Issue by ieichen137** [nats-io/nats-server#1099]
- [ ] Defect
 - [x] Feature Request or Change Proposal
 
## Feature Requests

I would like two new syntax options for subjects, one which allows you to exclude a token from being included in wildcard subscriptions, and a second which allows publishing/subscribing to a finite set of matching tokens. 

#### Use Case:

For wildcard exclusion,  this provides a mechanism for filtering or protecting subjects in an open or shared system from the publish/client side
For example, assuming an Exclamation point is the syntax

`!secrettoken.base.opt1.flob`

Without knowing `!secrettoken`, you could not subscribe to `*.base.opt1.flob`, or `>` and get messages from that subject. 

This syntax could also be used to make specific subjects intentional. 

For example. subjects
```
log.info
log.error
log.debug
log.!sys
```

To get all regular logs, you can subscribe to `logs.*`, but to obtain system logs, you have to subscribe to `logs.!sys` explicitly(or *.!sys, since non-excluded tokens are still wildcard ready)

For multiple specific subject publish, we have several job types which each perform a very specific function and so listen on a single subject, but the data the jobs operate on may be applicable to multiple job types. It would be helpful to be able to perform a single publish to more than one subject. for example 

`jobs.[add multiply]`

which would send to the `jobs.add` and `jobs.multiply` queue specifically. 

Multiple specific subscribe would work the same way. Rather than a wildcard sub
`logs.*` 

you could sub to `logs.[info error]` which would exclude `logs.sys` or `logs.debug` etc... if the subjects exist.  
 
#### Proposed Change:

I would like a syntax similar to the following, perhaps enabled by an 
`--enable-enhanced-subjects` flag or separate `--enabled-wildcard-excludes`,  `--enable-multiple-publish`, `--enable-multiple-subscribe` flags to make these features optional 

##### Wildcard Exclusion

This would support something like the following. Using the examples from your docs
Given the subjects:
```
time.us
time.us.east
time.us.east.atlanta
time.eu.east
time.eu.warsaw
```

I would like to add some kind of syntax for the following (the exclamation point is just an example) 
```
time.!sa.east
!time.us.east
!time.eu.east
```
The effect, a subscriber subscribing to subject `time.*.east` or `time.*`, or `>` would receive messages from 
`time.us.east, time.eu.east`
or
`time.us`
or
```time.us
time.us.east
time.us.east.atlanta
time.eu.east
time.eu.warsaw
```
respectively. 

To Subscribe to the subjects with the excluded tokens:
`time.!sa.*`, `time.!sa.east`, `!time.*.east`, `!time.us.east`
would subscribe you to
`time.!sa.east` for the first two examples, and 
```
!time.us.east
!time.eu.east
```
and 
`!time.us.east`
for the last two examples respectively

##### Specific Multiple Subject Subscription/Publish
For this case I will just use the basic subject examples again

```
time.us.east
time.us.west
time.us.central
time.us.mtn
time.eu.east
time.eu.west
```
and I would like to be able to subscribe to all east and west with something like the following

`time.*.[east west]`
which would subscribe me to 

```
time.us.east
time.us.west
time.eu.east
time.eu.west
```

And publishing. If i want to send messages to us and eu east and west

`time.[us eu].[east west]`

or for simplicity just to us east west

`time.us.[east west]

#### Who Benefits From The Change(s)?
 
Anyone who would like enhanced flexibility in subjects. 

The wildcard exclusions enable client side control over route protections in an open system. You have to mean to get the message to get the message.

The multi specific publish could be accomplished by two or more successive pubs to different subjects of course, but the option would be convenient. 

The multi specific subscribe would allow the client/server to ignore unwanted messages up front. 

Instead of sub to logs.* and only wanting info and debug, you sub to logs.[info debug] and are only sent those messages. 

#### Alternative Approaches

Open to any syntax options as long as they are simple and easy. I understand some of this, probably the wildcard excludes, would create a performance hit, so open to other considerations of course. 

#### Post-Script

Thank you for reading this. Will continue to make great use of this system regardless.

**Comment by derekcollison** [comment]
I believe with NATS 2.0 this is *mostly* already possible.

For instance, you can allow subscriptions via authorization to only include the subjects you want, however a client application can present a wildcard, but will only get what they are allowed to get.
In the example below, a user can subscribe to `foo.*`, but will not receive anything on `foo.SECRET`. 

![image](https://user-images.githubusercontent.com/90097/63108954-ec9a7800-bf3c-11e9-8e78-61adaaeee51b.png)

**Comment by ieichen137** [comment]
First, thanks for your comment. Is this something that can be done dynamically between publishers/subscribers? or is this a server side configuration only? The docs here: https://nats-io.github.io/docs/nats_server/authorization.html, if this is what you are referencing, make me think you have to have this staticly defined at the server level. But I could easily be misinterpreting.

**Comment by derekcollison** [comment]
You can configure statically, or present these as user JWTs for NATS 2.0.

https://nats-io.github.io/docs/nats_tools/nsc/nsc.html#user-authorization

**Comment by ieichen137** [comment]
My goal was to allow publishers to dynamically create their own separate communication paths for subscribers, but after reading through more of the docs, I think using the jwts with the nats-account-server extended or coupled another microservice the publishers can use to register accounts and generate/update/remove jwts on the fly for users should accomplish this and shouldn't be too much work. Then if I ever need to restrict publishers too, that groundwork will be there. 

I still think the subject syntax additions would be useful(because I always like more flexibility), but I think I can proceed this direction for now.

**Comment by derekcollison** [comment]
Thanks for the feedback, always great to hear from the community.
