### ISSUE TITLE
Suggestion: Continuous Fuzzing

### ISSUE THREAD

**Issue by yevgenypats** [nats-io/nats-server#1104]
Hi, I'm Yevgeny Pats Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- [go-fuzz](https://github.com/dvyukov/go-fuzz) fuzzers (This is generic step not-connected to fuzzit)
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [fuzzitdev/example-go](https://github.com/fuzzitdev/example-go) and you can see an example of "in the wild" integration [prometheus/prometheus](https://github.com/prometheus/prometheus), [coredns/coredns](https://github.com/coredns/coredns), [google/syzkaller](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

Cheers,
Yevgeny

**Comment by derekcollison** [comment]
I think that would be great! Fuzzers for the protocols would be the best fit IMO. We have 4.

1. Client
2. Routes
3. Gateways
4. LeafNodes

**Comment by yevgenypats** [comment]
Hi @derekcollison Cool! thanks for pinpointing the interesting components, that will save me some time.

Also, I need to mention that we have a [reward program](https://fuzzit.dev/2019/08/12/announcing-rewards-for-go-rust-oss-projects/) in case you have time/want to implement this yourself I would be happy to reward you as well as get unbiased feedback on how smooth the integration was. Let me know what you prefer.

**Comment by derekcollison** [comment]
Will take a look and circle back.

**Comment by yevgenypats** [comment]
Closing as fuzzit was acquired by GitLab
