### ISSUE TITLE
Can't create a nats-server process inside a windows service?

### ISSUE THREAD

**Issue by xzzh999** [nats-io/nats-server#1113]
- [x] Defect

## Defects 

 - [x] Included `gnatsd -DV` output
 

#### Versions of `gnatsd` and affected client libraries used:
```
nats-server: v2.0.2
```

#### OS/Container environment:
```
windows 7 64bit
```

#### Steps or code to reproduce the issue:
```
1. create a simple windows service proc in go, mark as A

2. create nats-server proc inside A, mark as B, with options -DV -l D:\\test.log
```
#### Expected result:
```
A and B both works fine
```
#### Actual result:
```
"nats server wait returned, err: exit status 1"

the log file is created, but empty.
```

**Comment by kozlovic** [comment]
@xzzh999 Not sure if you closed it by mistake or found out what was wrong, but in case here is some information about running NATS Server as a Windows service: https://nats-io.github.io/docs/nats_server/windows_srv.html

**Comment by xzzh999** [comment]
@kozlovic 
Thank you.

But i want to create the nats-server process inside a windows service, here is the error:
```
The service process could not connect to the service controller.
```
maybe i can change the code to enable my request.

**Comment by kozlovic** [comment]
Sorry I am not sure I fully understand what you are saying. You can run nats-server as a service, and I posted the link how to register it on Windows.
If you have your own process that happens to embed nats-server, your process would still need to implement Windows specific APIs to be running as a service. If you want to take advantage of the NATS Server doing that for you, you need to invoke `Run(*Server)`. Here is a very simple example of a program embedding NATS Server and hardcoding some of the options:
```
package main

import (
	"github.com/nats-io/nats-server/logger"
	"github.com/nats-io/nats-server/server"
)

func main() {
        // Following is not required, but since in this example we are using syslog,
        // the logging will be displayed in the Event Viewer Applications logs. Changing the
        // name here so that it is displayed as "testservice" and not "NATS-Server"
	server.SetServiceName("testservice")
	logger.SetSyslogName("testservice")

	opts := server.Options{}
	opts.Host = "127.0.0.1"
	opts.Port = 4223
	opts.Debug = true
	opts.Trace = true
	opts.Syslog = true
	s, err := server.NewServer(&opts)
	if err != nil {
		panic(err.Error())
	}
	defer s.Shutdown()
	s.ConfigureLogger()
	server.Run(s)

        // Do something...
}
```
You could build this way:
```
go build -o testservice.exe main.go
```
Then, register and then start the service:
```
sc.exe create testservice binPath="c:\test\testservice.exe"
sc.exe start testservice
```
In the event viewer you will see in the Applications logs, syslog events for this process.

Let me know if this is what you were trying to do.

**Comment by xzzh999** [comment]
@kozlovic thank you very much.

I already have done all the above, both make nats-server run as a windows service and managed as a child process inside another windows logic service. 
```
1> nats-service  ------------> run as a windows services -------------> [OK]

2> some another my windows service ----> 
create nats-server as a child process (not service,
 but just a child process inside a  service) ------->
[OK, if  i modified the running start code]
```
why i want do this? because there is a top service (windows service) and i want to use it to manage many sub child processes, like a watchdog, i maybe want to create same child progresses instance, so i need this.

**Comment by xzzh999** [comment]
my top level service just like [gosuv](https://github.com/codeskyblue/gosuv), which managed many child processes.

**Comment by kozlovic** [comment]
@xzzh999 So was `Run(*Server)` what was missing and you are ok now? I am not sure I understand if you still have a problem or not..

**Comment by xzzh999** [comment]
@kozlovic 
it's ok, not any problems， i just want a custom service 
spawn a nat-server processs which is not a service or an interactive session.

i just modified the `service_windows.go`, like this:
```
// Run starts the NATS server as a Windows service.
func Run(server *Server) error {
	server.start()
	return nil

	// commented follow codes, because I am 
	// inside a custom service but I don't want to run 
	// as a service or an interactive session, but as a child process
	// inside a custom service.

        // --------------------------------------------------------------
	// if dockerized {
	// 	server.Start()
	// 	return nil
	// }
	// run := svc.Run
	// isInteractive, err := svc.IsAnInteractiveSession()
	// if err != nil {
	// 	return err
	// }
	// if isInteractive {
	// 	run = debug.Run
	// }
	// return run(serviceName, &winServiceWrapper{server})
        // --------------------------------------------------------------
}
```

if u can add an option of this situation using, that will be nice.

**Comment by kozlovic** [comment]
Oh I see. So you are not embedding the NATS Server (in that you are not running it as a go routine), but you are starting the nats-server.exe process.

As you can see from the code that you have commented out, there is actually a workaround for your situation that does not involve commenting out code, simply ensure that the spawned process' environment variable `NATS_DOCKERIZED` is set to `1`.

The `init()` in this file searches for an environment variable:
```
func init() {
	if v, exists := os.LookupEnv("NATS_DOCKERIZED"); exists && v == "1" {
		dockerized = true
	}
}
```
And if set to `1`, `Run()` will call `server.Start()`:
```
// Run starts the NATS server as a Windows service.
func Run(server *Server) error {
	if dockerized {
		server.Start()
		return nil
	}
        ...
```
This was done for our Docker image (https://github.com/nats-io/nats-server/pull/544) but could work for you.

**Comment by xzzh999** [comment]
@kozlovic 
ok, that's good~

**Comment by navono** [comment]
@kozlovic thank you for the solution.

I've been struggling with this problem for half day. Check my env, my code, my configuration again and again, but no clue.

**Comment by kozlovic** [comment]
@navono I cannot tell from your comment if you had a problem and then found this GH report that gave you the solution or if, even with the solution presented here, you still have an issue?

**Comment by navono** [comment]
Yes, I found the solution frome this. What I want to say is that before finding this issue, I spend a lot of time to check my code.
