### ISSUE TITLE
connections keep increasing to max_connections

### ISSUE THREAD

**Issue by YoninL** [nats-io/nats-server#1114]
- [x] Defect
 - [ ] Feature Request or Change Proposal
 
## Defects 

connections number reached to max_connections (100), and then dropped due to nats server's reload mechanism, but it will reach to limit again every one hour, have to restart manually to make it back to normal. There's no sudden requests increase on both nats streaming and client side.

![image](https://user-images.githubusercontent.com/5434031/64222702-9f8a4000-cf03-11e9-8e4b-84b7ba070020.png)

 
#### Versions of `gnatsd` and affected client libraries used:
nats server 1.4.1
nats streaming server 0.12.0

nats server config:
```
listen: 0.0.0.0:4222
http: 0.0.0.0:8222
authorization {
    user:     *****
    password: *****
    timeout:  1
}

cluster {
    listen: 0.0.0.0:6222
    authorization {
        user: ******
        password: ******
        timeout: 0.5
    }
    routes = [
        nats://******:******@172.239.5.99:6222
        nats://******:******@172.239.6.99:6222
    ]
}
debug:   false
trace:   false
logtime: true
max_connections: 100
max_control_line: 512
max_payload: 65536
write_deadline: "2s"
```

#### OS/Container environment:
OS: Ubuntu 16.04.4 LTS
Docker image: nats:1.4.1 + nats-streaming:0.12.0

#### Steps or code to reproduce the issue:
Unknown yet, will enable debug mode and monitor.

#### Expected result:
Connections number is stable

#### Actual result:
Sometime it reaches to max_connections limit and  can't back to normal unless manually restart it.

**Comment by derekcollison** [comment]
Might be useful to see what `http://localhost:8222/connz?sub=1` reports when the maximum is hit.

**Comment by YoninL** [comment]
Hard to catch the moment as I don't know how to reproduce it, will try.
BTW, from logic side, do you have any ideas about the behavior?

**Comment by kozlovic** [comment]
@YoninL I see that you plan to enable debug mode. I think that this is the right thing to do to see what is causing this increase of connections count. My first reaction would be to think that this is external (meaning applications creating connections). I don't think that the server itself would cause the count to increase on its own.

**Comment by YoninL** [comment]
Thanks, but my fix is to restart nats servers, not nats streaming or applications, immediately after I restarted nats servers (9:21 in my time yesterday), connections number became stable, that's why I thought it may be caused by nats server itself.

**Comment by kozlovic** [comment]
Well, NATS itself would create only route connections. So even if route drops and gets recreated, it should continue growing. It will either succeed in recreating, or wait 1 sec and try again. But the previous failed connection would not count as an active connection.

**Comment by YoninL** [comment]
Didn't see this issue anymore, and we've upgraded to Nats 2, close this issue.

**Comment by derekcollison** [comment]
Thanks for the update. And thanks for upgrading.
