### ISSUE TITLE
Options.MaxPending is defined as int64 but used as int32

### ISSUE THREAD

**Issue by cv711** [nats-io/nats-server#1118]
- [x] Defect
 - [ ] Feature Request or Change Proposal
 
## Defects 

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ ] Included `gnatsd -DV` output
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)
 
#### Steps or code to reproduce the issue: 
```
package main

import (
	"math"
	"time"

	"github.com/nats-io/nats-server/v2/server"
	natsc "github.com/nats-io/nats.go"
)

func main() {
	svc, _ := server.NewServer(&server.Options{
		MaxPending: math.MaxInt32 + 1,
	})
	svc.ConfigureLogger()
	go func() {
		time.Sleep(1 * time.Second)
		opts := natsc.GetDefaultOptions()
		conn, _ := opts.Connect()

		_, _ = conn.Subscribe("*", nil)
		conn.Flush()
	}()
	svc.Start()
}
```
 
#### Expected result:
It's less than math.MaxInt64 so it should run without any issues.
 
#### Actual result:
 Exits with this error: 
`[75524] [INF] 127.0.0.1:52013 - cid:1 - Slow Consumer Detected: MaxPending of -503316480 Exceeded`
 
#### Proposed Change:
 Either change `Options.MaxPending` to `int32` or use it as `int64` in the codebase.

#### Who Benefits From The Change(s)?
 Everyone

**Comment by kozlovic** [comment]
@derekcollison In https://github.com/nats-io/nats-server/commit/af78552549743e9b8400b8ec6a5f6204468adaef, you changed client.out.mp from `int` to `int32`, which in 64bit platform went from int64 to int32. If limit of signed 32bit is acceptable for max pending, we should fail/warn if user specify more than 2GB as max pending.

**Comment by derekcollison** [comment]
I could see max pending possibly being allowed to be > 2GB. WDYT?

**Comment by kozlovic** [comment]
Possibly, so we need to change the `client.out.mp` to be int64.

**Comment by derekcollison** [comment]
Yea, understood.
