### ISSUE TITLE
NATS Cluster Routing

### ISSUE THREAD

**Issue by philipfoulkes** [nats-io/nats-server#1120]
Request for Help

We're planning on using Nats as our messaging system for one of our new solutions. We've previously used Nats standalone as a means for microservices running on a single server to communicate with each other. For one of our newer solutions, we would like to run a Nats cluster.

For our new solution, we have a number of servers, and any one of those can receive requests from external systems (via HTTP, for instance). Once received by a server, this request is processed by a set of microservices. In the majority of the cases, all of the required microservices run on the same server. There's a handful of cases where particular microservices can only run on a subset of the servers. We're also planning on running a Nats instance on each of the servers.

We thought of using a Nats cluster to handle routing messages to servers where microservices are running. What we would prefer is, if Nats can directly deliver a message to a subscriber, then Nats should _always_ do this, otherwise, it should send the message to a neighbouring Nats instance within the cluster. We're trying to reduce the amount of network traffic, and response latency, as much as possible such that we can have a good user experience for our service. We're using queue groups, so only one microservice subscribed to a subject should receive the message.

Consider the diagram below. If Application 01 on Server 01 would like to send a message to Application 02 on subject _foo_, as Application 02 is running on Server 01, the message should _always_ be delivered to Application 02 running on Server 01.

However, if Application 01 on Server 03 would like to send a message to Application 02 on subject _foo_, this message can be delivered to Application 02 running on either Server 01 or Server 02.

![Nats](https://user-images.githubusercontent.com/44870662/64722609-1e1c4a00-d4cf-11e9-8c64-ff084cfb6095.png)

Thus, is it possible to force a Nats server to deliver to local subscribers (if available), and then as a second preference, deliver messages to remote subscribers via the cluster? We're planning on using no_advertise: true and the firewall to force each microservice to connect to its local Nats instance.

**Comment by derekcollison** [comment]
Gateways will do what you want.

https://nats-io.github.io/docs/gateways/#queue-subscriptions

So instead of a route connection between the NATS servers, use a GW connection instead.

**Comment by philipfoulkes** [comment]
Thank-you. I will try that.

**Comment by philipfoulkes** [comment]
Using gateway connections works as we require it to work. Thanks for the assistance.

**Comment by derekcollison** [comment]
Great to hear!
