### ISSUE TITLE
behaviour to create a cluster on a random port fails due to different option parsing

### ISSUE THREAD

**Issue by aricart** [nats-io/nats-server#1128]
Previous version of nats-server allowed the creation of clusters on random ports by:
`nats-server --http_port -1 --cluster nats://127.0.0.1:-1 --port -1 --ports_file_dir /tmp` with the ports file describing where the cluster lives. This is enables automated tests to be more reliable for other platforms that cannot inline the server process.

**Comment by derekcollison** [comment]
ok will have @wallyqs look at it. Do you recall which version it used to work in or when it broke?

**Comment by aricart** [comment]
I proposed a PR for it.

**Comment by derekcollison** [comment]
Did not see a PR show up, hmm..

**Comment by aricart** [comment]
"the branch is building"

**Comment by aricart** [comment]
> ok will have @wallyqs look at it. Do you recall which version it used to work in or when it broke?
https://github.com/nats-io/nats-server/releases/tag/v2.0.0 works correctly.

**Comment by aricart** [comment]
Ivan checked -the issue is downstream from changes in go.

**Comment by kozlovic** [comment]
https://github.com/golang/go/issues/33632
