### ISSUE TITLE
  In high concurrency, data will be lost ?

### ISSUE THREAD

**Issue by ayaya118** [nats-io/nats-server#1134]
In high concurrency, data will be lost ?

**Comment by ripienaar** [comment]
Not typically no, perhaps you can expand on your question a bit - like if you saw some issues.

**Comment by derekcollison** [comment]
Data loss in a NATS system can come in several ways.

1. Consumer is marked as a slow consumer by a server and disconnected (most common)
2. Application crashes
3. Network partitioning (core NATS server will not hold onto messages)
4. Server crashes (highly unlikely)

If you are seeing data loss I would investigate in that order.

https://nats-io.github.io/docs/nats_admin/slow_consumers.html

**Comment by derekcollison** [comment]
Will close for now, feel free to re-open if not addressed.
