### ISSUE TITLE
Publish High Frequency Data Not Working

### ISSUE THREAD

**Issue by chimirala** [nats-io/nats-server#1145]
Hi Team,

I am trying to build high-frequency architecture using NATS server. I have market data client which sends around 500-1000messages/sec. 

I have downloaded latest version of NATS server couple of days back and publishing the same to server. Publishing of data is working fine, however, there is a data loss on subscription. Currently, we have only one publisher and one subscriber.

Could you assist why we have a data loss. 

Regards
BNS

**Comment by derekcollison** [comment]
Sure happy to help. Feel free to send us a gist that shows the problem, or describe in more detail.

Some things we see with simple tests.

1. If you use two different connections, make sure you know the subscription has been processed before sending. Use Flush().
2. Subscriber is a slow consumer and get's disconnected. Monitor in your client, or run server with `-m <port>` and open your browser to localhost:<port>. Check varz for slow_consumer totals.

We have a benchmarks under test in the server repo, the Go client also has a benchmark program that we also suggest using to gain a good understanding of what a single server can do on your hardware.

**Comment by chimirala** [comment]
> 
> 
> Sure happy to help. Feel free to send us a gist that shows the problem, or describe in more detail.
> 
> Some things we see with simple tests.
> 
>     1. If you use two different connections, make sure you know the subscription has been processed before sending. Use Flush().
> 
>     2. Subscriber is a slow consumer and get's disconnected. Monitor in your client, or run server with `-m <port>` and open your browser to localhost:. Check varz for slow_consumer totals.
> 
> 
> We have a benchmarks under test in the server repo, the Go client also has a benchmark program that we also suggest using to gain a good understanding of what a single server can do on your hardware.

Hey Sorry, publish and subscribe is working fine. We had a small glitch in code and it resolved now. Thanks.

**Comment by derekcollison** [comment]
Great to hear, let us know if we can help in anyway further.
