### ISSUE TITLE
How to connect to nats-server running in a docker container in Kubernetes which runs nats:latest image?

### ISSUE THREAD

**Issue by emailtovamos** [nats-io/nats-server#1151]
- [X ] Question
 - [ ] Feature Request or Change Proposal
 
#### Steps or code to reproduce the issue: 

- Run a docker container in Kubernetes using a file like this: https://pastebin.com/R2atnc2F
- Corresponding service file like this: https://pastebin.com/U9X57vyS
- Try to connect by address "nats:4222" which doesnt work

 
#### Actual result:
 Error

**Comment by wallyqs** [comment]
Hi @emailtovamos you can try with the following statefulset to get started: https://gist.github.com/wallyqs/c566c856b7119645fd7e11056374c584

**Comment by emailtovamos** [comment]
Thanks @wallyqs . Any tips on how exactly I can connect to the server then? I am using Go and wanted to connect to it at the address something like `nats:4222`. 
I can see there is service, configmap, statefulset . If I simply `apply` this file, will I be able to connect to the server by `nats:4222`? 
e.g. `conn, err := nats.Connect("nats:4222")`
Also whats the use of configmap here?

**Comment by wallyqs** [comment]
yeah you should be able to connect using the name of the service, so in your code something like `nats.Connect("nats:4222")` should work.  The configmap is the configuration for the nats server used instead of command line parameters

**Comment by derekcollison** [comment]
In Go the default port is 4222, so you only really need 

```go
nc, err := nats.Connect("nats")
```

**Comment by emailtovamos** [comment]
@derekcollison So do you mean running these two deployment and service file (https://pastebin.com/R2atnc2F, https://pastebin.com/U9X57vyS) only should let me use the command `nc, err := nats.Connect("nats")` ? 
If not I will simply apply the bigger file mentioned above. Thanks.

**Comment by emailtovamos** [comment]
It works for me now. My main issue was not getting the namespaces right. A service from namespace A was trying to connect to nats which was in namespace B by simply calling "nats". I made them in the same namespace and they work fine. Otherwise it would have to be called by nats.B and not just nats. 

Thank you both for your time!

**Comment by emailtovamos** [comment]
I am having an issue after I injected Linkerd proxy into my service to load balance. I get error 
```
error: "read tcp 10.X.10.3:56918->10.X.16.77:4222: i/o timeout"   
message: "could not connect to nats" 
``` 

What changes should I make to ensure nats connection is fine in the presence of load balancing proxies?

**Comment by derekcollison** [comment]
We discourage putting any proxies or load balancers between NATS clients and servers. NATS already knows how to connect to multiple servers and gossips between servers and clients on topology changes. So no proxy or LB needed. 

If this is a requirement, you can use a proper L4 technology like HAProxy etc.
