### ISSUE TITLE
How to create docker high available cluster?

### ISSUE THREAD

**Issue by codinggg** [nats-io/nats-server#1152]
Hello! I want to create a nats docker cluster.  I looking for follow example:
https://nats-io.github.io/docs/nats_docker/#clustering-with-docker 

It can be created but not high available. my client have a pub and a sub, my pub connet to serverA and sub connect to serverB, when I stop serverB,  sub client show's error:
**Disconnected due to:EOF, will attempt reconnects for 10m** 
It not automatic connect to another peers.

I use follow example test is high available.
https://nats-io.github.io/docs/nats_admin/upgrading_cluster.html#cluster-upgrading
I use before step, stop serverB, sub show:
**Disconnected due to:read tcp 192.168.1.24:5523->192.168.1.24:4333: wsarecv: An existing connection was forcibly closed by the remote host., will attempt reconnects for 10m
Reconnected [nats://192.168.56.1:4444]
[#6] Received on [abc]: '<<>'
[#7] Received on [abc]: '<<>'** 

Have something I have missing?

**Comment by wallyqs** [comment]
Hi @codinggg thanks for the report, in the original example it would not have been possible to failover automatically because the advertisements from the server would have been for ips in the docker network and the connection was being made against the host port.  I have updated the example in the docs instead so that a `network` is used so that the clients in the network can discover and reconnect to any of the members: https://github.com/nats-io/docs/blob/f0c3fe1be9e21ca5b576c2a9f51646e4a53f87f1/nats_docker/README.md

**Comment by derekcollison** [comment]
Let us know if we can close this one.

**Comment by codinggg** [comment]
I don't know what's wrong, it still unworking.
I open three command console, use following command:

> (1)$ docker run --name nats --network nats --rm -p 14222:4222 -p 8222:8222 nats

> (2)$ docker run --name nats-2 -p 24222:4222 --network nats --rm nats --cluster nats://0.0.0.0:6222 --routes=nats://r user:T0pS3cr3t@nats:6222

> (3)$ docker run --name nats-1 -p 34222:4222 --network nats --rm nats --cluster nats://0.0.0.0:6222 --routes=nats://r user:T0pS3cr3t@nats:6222

I use pub-sub for testing:

> nats-pub.exe -s "nats://192.168.1.132:14222" "hello" "--->"

> nats-sub.exe -s "nats://192.168.1.132:24222" "hello"

when I close (2) , sub client print following and waiting:
```
[#11] Received on [hello]: '--->'
[#12] Received on [hello]: '--->'
Disconnected due to:EOF, will attempt reconnects for 10m
```
docker image inspect:
```
$ docker inspect nats
    {
        "Id": "sha256:40662693f96a5a3f18a214bfe1be7f489f8f0fad235417a63d91962eb8e4ee13",
        "RepoTags": [
            "nats:latest"
        ],
        "RepoDigests": [
            "nats@sha256:7b7abb3d0ec279b864525c94b5b7476385c5a6fa3e1a8ff3c1f9ce9b4d86c958"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2019-09-20T22:22:47.362150497Z"
    }
```

**Comment by wallyqs** [comment]
@codinggg what is happening is that the `nats-sub.exe` is connecting from the host network using the ip address but the server is creating a full mesh using the ips from the Docker network and there does not seem to be connectivity from the host network to the docker network.  If you try with a container that is in the same Docker network, you can confirm that it would be able to reconnect:

```sh
docker run --network nats --rm -it synadia/nats-box
~ # nats-sub -s nats://nats:4222 hello &
Listening on [hello]
```

Another alternative would be to use `--client_advertise <host ip>` so that the host ips are advertised instead when creating the cluster:

```sh
$ docker run --name nats --network nats --rm -p 14222:4222 -p 8222:8222 nats --client_advertise <host ip>

$ docker run --name nats-2 -p 24222:4222 --network nats --rm nats --cluster nats://0.0.0.0:6222 --routes=nats://r user:T0pS3cr3t@nats:6222 --client_advertise <host ip>

$ docker run --name nats-1 -p 34222:4222 --network nats --rm nats --cluster nats://0.0.0.0:6222 --routes=nats://r user:T0pS3cr3t@nats:6222 --client_advertise <host ip>
```

**Comment by codinggg** [comment]
@wallyqs  Thank you for your help! I testing nats client and server in same network is working great.  And I try the second ways out has some error: I run up first server be ok, but when I try to run up second server, It show me:
`[ERR] Error trying to connect to route (attempt 1): dial tcp 172.19.0.2:6222: connect: connection refused`

All trace is it:

> docker run --name nats --network nats --rm -p 4222:4222 -p 8222:8222 nats --client_advertise 192.168.1.24
> [1] 2019/10/21 03:30:29.635881 [INF] Starting nats-server version 2.1.0
> [1] 2019/10/21 03:30:29.635952 [INF] Git commit [1cc5ae0]
> [1] 2019/10/21 03:30:29.636478 [INF] Listening for client connections on 0.0.0.0:4222
> [1] 2019/10/21 03:30:29.636518 [INF] Server id is NB5YFTRZTNRS2NAPZCD7F3WWGQ63J5O6MZZ3RRJ4IY7CHLXOMJTJYPUI
> [1] 2019/10/21 03:30:29.636524 [INF] Server is ready

> docker run --name nats-2 -p 14222:4222 --network nats --rm nats --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222 --client_advertise 192.168.1.24
> [1] 2019/10/21 03:30:36.313880 [INF] Starting nats-server version 2.1.0
> [1] 2019/10/21 03:30:36.313947 [INF] Git commit [1cc5ae0]
> [1] 2019/10/21 03:30:36.314366 [INF] Listening for client connections on 0.0.0.0:4222
> [1] 2019/10/21 03:30:36.314387 [INF] Server id is NA3L3SXGQ3VQ6SEAGFNOSFHHGP62S2FQPHVW6LEDSI4L4QTZIABKEHYL
> [1] 2019/10/21 03:30:36.314393 [INF] Server is ready
> [1] 2019/10/21 03:30:36.314490 [INF] Listening for route connections on 0.0.0.0:6222
> [1] 2019/10/21 03:30:36.316297 [ERR] Error trying to connect to route (attempt 1): dial tcp 172.19.0.2:6222: connect: connection refused

I can't find much more explain with `client_advertise`  on the internet, ` 192.168.1.24` is my nats pub and sub address,  what wrong it is ?

**Comment by wallyqs** [comment]
@codinggg here is the complete example using client advertise:

```sh
docker run --name nats --network nats --rm -p 4222:4222 -p 8222:8222 nats --cluster nats://0.0.0.0:6222 --client_advertise $HOST_IP

docker run --name nats-2 -p 4223:4223 --network nats --rm nats -p 4223 --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222 --client_advertise $HOST_IP

docker run --name nats-1 -p 4224:4224 --network nats --rm nats -p 4224 --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222 --client_advertise $HOST_IP
```

You can confirm that it worked by making a simple connection using telnet or netcat against one of the ports, then you would see that the ips that are advertised are the host ips, in my case for example:

```sh
telnet 127.0.0.1 4222
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
INFO {"server_id":"ND5NT2Y3ESYKMQRHCPMSQE4CFFHZYYMPCYHTXTR5FZQTJ2FIMRDW7AML","version":"2.1.0","proto":1,"git_commit":"1cc5ae0","go":"go1.12.9","host":"192.168.11.13","port":4222,"max_payload":1048576,"client_id":3,"connect_urls":["192.168.11.13:4222","192.168.11.13:4224","192.168.11.13:4223"]} 
```

**Comment by codinggg** [comment]
@wallyqs It works! Thank you for your kindly help again!  😄
