### ISSUE TITLE
What's the plan for nats-server support for TLS1.3?

### ISSUE THREAD

**Issue by longwallstreet** [nats-io/nats-server#1155]
Hello
The highest version of nats-server currently supporting TLS is 1.2.
What's the plan for nats-server support for TLS1.3?
Thanks.

**Comment by derekcollison** [comment]
Its on our list but we are waiting for go 1.13.2 to be released. Currently we do release builds with 1.12.x

**Comment by longwallstreet** [comment]
Thanks
