### ISSUE TITLE
During CONNECT, client may receive from server PING before initial PONG

### ISSUE THREAD

**Issue by kozlovic** [nats-io/nats-server#1174]
Lots of client implementations during the connect process send a  CONNECT protocol followed by a PING and expect the server to send the PONG (or -ERR) before they return to the user that the connection is created.
While the server is processing the client's CONNECT, and if Connz() is requested, it is possible that the server sends a PING (to compute RTT) before the initial PONG (in response to client PING) is sent back, causing the client to report:
```
nats: expected 'PONG', got 'PING'
```

**Comment by creotiv** [comment]
during heavy testing i still see this error for Go client

**Comment by wallyqs** [comment]
@creotiv are you testing with TLS connections?

**Comment by creotiv** [comment]
without.
