### ISSUE TITLE
Native open-metrics/prometheus support

### ISSUE THREAD

**Issue by wpjunior** [nats-io/nats-server#1193]
- [X] Feature Request or Change Proposal
 
#### Use Case:
Nowadays many of projects has adopted Prometheus (open-metrics) to monitoring standard for Cloud-Native systems,  ie: kubernetes, envoy, jaeger, all these projects could you easy pull metrics with Prometheus, without specific exporter.

#### Proposed Change:

Embed all metrics logic into nats-server, deprecating prometheus-exporter.

#### Who Benefits From The Change(s)?

End-users could easy setup nats-server in their clouds without setup a specific component, such as as easy as other CNCF projects.

**Comment by OneCricketeer** [comment]
I'd also like like to advocate for pushing out statsd metrics rather than polling from Prometheus

**Comment by derekcollison** [comment]
Surveyor is current direction.
