### ISSUE TITLE
JetStream build errors on Windows

### ISSUE THREAD

**Issue by znbang** [nats-io/nats-server#1213]
- [x] Defect
 - [ ] Feature Request or Change Proposal
 
## Defects 

jetstream branch build errors on Windows:
 ```
mem_windows.go:36:31: undefined: kernel32 
mem_windows.go:45:12: cannot use msx.ullTotalPhys (type uint64) as type int64 in return argument
```
 
#### Versions of `nats-server` and affected client libraries used:

jetstream branch

#### OS/Container environment:

Windows 10

**Comment by derekcollison** [comment]
Can you confirm this can be closed?

**Comment by znbang** [comment]
yes, thanks.

**Comment by derekcollison** [comment]
Thanks for the contribution.
