### ISSUE TITLE
Is there a limitation on minimum number of servers for nats cluster ?

### ISSUE THREAD

**Issue by rohsaini** [nats-io/nats-server#1222]
**Usecase:**
I want to use 2-node nats cluster and have found it to be working. I want to confirm if it is appropriate to use such type of model.
What could be the possible downsides of this approach?

I will be deploying my own split-brain algorithm which will make sure subscriber always talk to publisher of same nats server.

Also, I understand nats uses mesh clustering, any specific clustering algorithm used for it? Can you please explain a little how exactly it works.

**Comment by derekcollison** [comment]
NATS supports multiple topologies for arbitrary large super clusters. You can extend these super clusters with leafnodes as well to mix and match ownership/operator status or authentication systems.

Read more here: https://docs.nats.io/whats_new_20#global-deployments

**Comment by derekcollison** [comment]
For the original mesh clusters, there is no limit per se but smaller ones were the original design intent. Depends on what you are scaling for to be honest.

**Comment by rohsaini** [comment]
Thanks @derekcollison . So minimum 3 nodes  or odd number nodes is not mandatory for a NATs server cluster. I will go ahead with 2 nodes cluster for my production.
Also, Since NATs streaming server uses raft, it needs minimum 3 nodes. Please correct me if wrong.

**Comment by ripienaar** [comment]
You need 3 only if you deploy NATS Streaming in clustered mode, it supports other modes that does not need it like a Active/Standby scenario - and performance is a lot better in those cases.

**Comment by rohsaini** [comment]
Thanks @ripienaar . Got it. What are those other modes? Are you referring to fault tolerance?

**Comment by ripienaar** [comment]
yes, fault tolerance

**Comment by rohsaini** [comment]
Thanks @ripienaar
