### ISSUE TITLE
how to start by sytemctl

### ISSUE THREAD

**Issue by hellojukay** [nats-io/nats-server#1237]
```shell
wget https://github.com/nats-io/nats-server/releases/download/v2.1.2/nats-server-v2.1.2-amd64.rpm
yum install nats-server-v2.1.2-amd64.rpm -y
```
after install nat-server , how to start it . i am using it in production.

**Comment by ripienaar** [comment]
Unfortunately the current RPM has no service related files, you'd have to make those.

**Comment by derekcollison** [comment]
For which system?

We have this - https://github.com/nats-io/nats-server/blob/master/util/nats-server.service
