### ISSUE TITLE
Support resolving SRV Record for routing addresses

### ISSUE THREAD

**Issue by JoHuang** [nats-io/nats-server#1247]
## Feature Requests
Resolving SRV Record for routing addresses

#### Use Case:
It's in AWS ECS env. I would like to setup a small seed container with SRV record, and let other eats-servers connecting to the seed server at startup. However, nats-server seems cannot resolve SRV records. 

#### Proposed Change:
Resolve SRV record first, and then try to connect to route addresses.
Just like what nats-js client does. https://github.com/nats-io/nats.js/issues/248

#### Who Benefits From The Change(s)?
Who works in a limited IP addresses env.

**Comment by derekcollison** [comment]
This still an issue in a modern server?

**Comment by bruth** [comment]
@JoHuang Feel free to reopen if this is still relevant.
