### ISSUE TITLE
Enhancement: retry binding to IPs that do not exist yet.

### ISSUE THREAD

**Issue by jamiesonbecker** [nats-io/nats-server#1255]
- [ ] Defect
 - [x] Feature Request or Change Proposal
 
 
#### Use Case:

Currently, attempting to bind to an IP that is not (yet) configured results in an immediate fail without retries. For example,

   Error listening on port: 192.168.99.99:4222, "listen tcp 192.168.1.1:4222: bind: cannot assign requested address"
 
#### Proposed Change:
 
Suggestion that nats-server either retries continuously (perhaps only if `-D` is not specified), or use the same `--connect_retries` or another parameter (`--bind-retry`?) enables the use of NATS in situations where it's unclear or unknowable when an interface has been initialized (such as when a unit script dependency occurs asynchronously.)

#### Who Benefits From The Change(s)?

More complex cluster usages. 

#### Alternative Approaches

Watch for the interface to come up before launching `nats-server`, or using different (VPN, mesh networks, etc) interfaces that allow synchronous dependency unit/init scripts.

**Comment by derekcollison** [comment]
This is mostly done with supporting infra. Modern systems usually prefer individual processes to fail fast. 

So for instance on systemd or on rc (for alpine) you let the system know we can't run until the network is present.

For things like k8s you can do something similar and have k8s or systemd etc restart if the process fails.

**Comment by jamiesonbecker** [comment]
Agreed, but (for example) with zerotier (and probably with wireguard, openvpn, etc), it's not always clear when the interface is up. In other words, the _network_ is present, which the mesh network interfaces (virtual NICs) depend on, but they will still take a certain amount of time to come online.

**Comment by jamiesonbecker** [comment]
updated comment @derekcollison

**Comment by derekcollison** [comment]
Thanks for the additional information. Much appreciated.
