### ISSUE TITLE
LeafNode TLS issues with mixed IP/Hostnames

### ISSUE THREAD

**Issue by rbboulton** [nats-io/nats-server#1256]
- [x] Defect
 - [ ] Feature Request or Change Proposal
 
## Defects 

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included `nats-server -DV` output
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)
 
#### Versions of `nats-server` and affected client libraries used:
nats-server version 2.1.2

#### OS/Container environment:
WSL Ubuntu 18.04.3 LTS

#### Steps or code to reproduce the issue:
Attached bash script showing the steps I performed to reproduce the issue. 
[tlsname_repro.txt](https://github.com/nats-io/nats-server/files/4090525/tlsname_repro.txt)

For simplicity I reproduced this issue using loopback addresses, the same issue presents itself for 
normal IP addresses/hostnames.

ServerA: Cert SAN: "localhost"
- LeafNode 
  - listen 127.0.0.1:7422
  - advertise localhost:7422
 
ServerB: Cert SAN: "127.0.0.2"
- LeafNode 
  - listen 127.0.0.2:7422
  - advertise 127.0.0.2:7422

When a leafnode tries to connect to ServerB (127.0.0.2) we get:
[ERR] 127.0.0.2:7422 - lid:1 - TLS handshake error: x509: certificate is not valid for any names, but wanted to match localhost

The problem appears to be caused by leafnode.go using the tlsName "localhost" for all TLS validation. I tried disabling the saveTLSHostname and this specific issue is resolved. I'm not sure what other use cases are impacted by disabling this functionality though.

Attached logs for leaf node: [logs.zip](https://github.com/nats-io/nats-server/files/4090509/logs.zip)
 
#### Expected result:
Remote LeafNode connections should work to ServerA using hostname and ServerB using IP address.

#### Actual result:
 When defining a remote leafnode using IP address the connection fails TLS validation

**Comment by rbboulton** [comment]
I changed the example so that it stops ServerA before ServerB to demonstrate the same issue occurs when reconnecting to ServerB.

[leaflogs.zip](https://github.com/nats-io/nats-server/files/4090597/leaflogs.zip)
[tlsname_repro.txt](https://github.com/nats-io/nats-server/files/4090599/tlsname_repro.txt)

**Comment by derekcollison** [comment]
ok should be fixed. Feel free to re-open if that is not the case.

**Comment by rbboulton** [comment]
Thanks, just gave it a quick spin and it seems to do the trick.
