### ISSUE TITLE
syslog support on Windows

### ISSUE THREAD

**Issue by SkinnySackboy** [nats-io/nats-server#1259]
We have started using NATS / NATS Streaming which so far appears to be working rather well.

We would now like to configure logging, in particular remote logging using syslog. While we have been able to get remote logging to work with the Windows Event Log, when using syslog we had no such luck. 

The only way we managed to get it to work was by logging to the Windows Event Log and then installing a seperate Event Log->syslog forwarder, but it would be much easier for us if we were able to log directly to syslog without installing/maintaining additional processes.

Is logging to syslog something that is officially supported in the Windows version?

**Comment by ColinSullivan1** [comment]
I'll check this out.  Is there a particular windows syslog tool you'd recommend for testing?

**Comment by ColinSullivan1** [comment]
@SkinnySackboy ,

Thanks for raising this issue, and I understand forwarding log messages from the event log is cumbersome.  Unfortunately syslog on windows is not supported.

The NATS server is written in go which [does not support](https://github.com/golang/go/blob/9f1d55c4e73dbaff1f118df7125a2cd4401fcb8e/src/log/syslog/doc.go#L19) syslog functionality on windows builds.  This is why we chose to implement syslog as windows events to achieve some level of parity.  Should go implement a windows syslog in the future, we may consider this but at this time we'll keep things as they are.

More discussion about windows and syslog in golang can be found [here](https://github.com/golang/go/issues/1108) and [here](https://go-review.googlesource.com/c/go/+/2953/).

I wish I had a better answer for you.  We'll be happy to help you look at other options (just reopen the issue), although it looks like you've found a workaround with forwarding the event log.

**Comment by SkinnySackboy** [comment]
Many thanks @ColinSullivan1 just wanted to make sure there wasn't a simpler solution we were missing - we can live with the event log forwarding.
