### ISSUE TITLE
Add a configuration option to rollover or truncate log file

### ISSUE THREAD

**Issue by wutkemtt** [nats-io/nats-server#1279]
[ ] Defect
 [X] Feature Request or Change Proposal
 
#### Use Case:
The NATS log file can grow to gigabytes when it is not cleared or deleted manually or via cron job.

#### Proposed Change:
Add a configuration option to rollover the log file on a daily or similar base or based on a fix maximum size.

#### Who Benefits From The Change(s)?
As the log file is locked by the NATS service it could not rolled over by a cron or manually without stopping the service first. Having a configuration option for this would make the life of all NATS operators much easier.

**Comment by ripienaar** [comment]
I think `LogSizeLimit` does what you want, its a recent addition in https://github.com/nats-io/nats-server/pull/1202

**Comment by kozlovic** [comment]
@wutkemtt Yes, as @ripienaar mentioned, this feature is available in NATS Server 2.1.4 (https://github.com/nats-io/nats-server/releases/tag/v2.1.4) and NATS Streaming Server 0.17.0 (https://github.com/nats-io/nats-streaming-server/releases/tag/v0.17.0) (PR #https://github.com/nats-io/nats-streaming-server/pull/1018)

**Comment by wutkemtt** [comment]
That will solve our problem, thanks.
We will upgrade to the newest version immediately.
