### ISSUE TITLE
A simple question about sublist

### ISSUE THREAD

**Issue by johnsiu2016** [nats-io/nats-server#1294]
If I have N subscriptions over M nodes, each of them subscribe X subject. How much memory the cluster will consume?

number of subjects * subject size * number of nodes
or
number of subjects * subject size

Thanks

**Comment by derekcollison** [comment]
Subscriptions are fairly lightweight, so not sure you need to concern yourself with that, however you should test yourself it its important. If you have M = 3, and say server A and server B and server C, and you have clients connected to server A those subjects will be duplicated on B and C, but only once per subject/subscription regardless of how many duplicates are on server A.

**Comment by johnsiu2016** [comment]
so the equation for memory consumption of the cluster is roughly equal to 
number of subjects * number of nodes? I came cross this question just because I saw https://github.com/akka/akka/issues/23357

thanks anyway!

**Comment by derekcollison** [comment]
Number of Subscriptions + ((Number Servers -1) * Unique subjects)
