### ISSUE TITLE
Increasing number of threads 

### ISSUE THREAD

**Issue by arun11299** [nats-io/nats-server#1302]
- [x ] Defect
 - [ ] Feature Request or Change Proposal
 

 - [ x] Included `nats-server -DV` output
 - [ ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

The issue is increasing thread count when the system is "relatively" idle. Nats server starts with around 17 threads and after around 30 mins, the thread count increases to 55. And after about 4 hours, it has reached to 71. All in the so called relatively idle state.

In this idle state, the processes are doing very minimum ping and pong requests. See the nats-top result below.

My questions are:
1. Why is the thread usage increasing when so minimal work is being done ?
2. The issue is we have a global metrics checker, for which the threshold for all processes is set to 50, as that should be more than enough for the kind of work we do. So, we end up getting threshold crossing events for Nats server.
3. Have also pasted the configuration file used and the command arguments we pass along with Nats server.

Thanks in advance!!

**Nats Config:**

```
> [amuralid@amuralid-master:/localdisk…1-mgmt-vm-lp-2/nats]$ cat nats.conf
> // Copyright 2019 RIFT Inc
> max_payload: 67108864
> 
```

**Nats arguments:**

`args_list = [exe_path, "-c", config_file_path, "-m", "8444", "-l", log_path, "--debug"]
`
**-DV Output**
```
[amuralid@amuralid-master:/net/homes…me1/amuralid/go/bin]$ /localdisk/amuralid/container/ub/master/rift2/.build/ub18_debug/install/usr/rift/usr/bin/nats-server -DV
[1106] 2020/03/05 17:18:22.412096 [INF] Starting nats-server version 2.0.0
[1106] 2020/03/05 17:18:22.412166 [DBG] Go build version go1.11.10
[1106] 2020/03/05 17:18:22.412171 [INF] Git commit [not set]
[1106] 2020/03/05 17:18:22.412253 [INF] Listening for client connections on 0.0.0.0:4222
[1106] 2020/03/05 17:18:22.412258 [INF] Server id is NBSNSLMJ7H5BDQRPS73VFCNZOWGBMBYVBMSZED4JMNPXODKIJT6BGNI4
[1106] 2020/03/05 17:18:22.412262 [INF] Server is ready
[1106] 2020/03/05 17:18:22.412271 [DBG] Get non local IPs for "0.0.0.0"
[1106] 2020/03/05 17:18:22.412398 [DBG]  ip=10.110.4.6

``` 
**Nats top output**
```
NATS server version 2.0.0 (uptime: 4h9m40s)
Server:
  Load: CPU:  2.0%  Memory: 14.6M  Slow Consumers: 0
  In:   Msgs: 19.0K  Bytes: 2.5M  Msgs/Sec: 0.0  Bytes/Sec: 0
  Out:  Msgs: 44.8K  Bytes: 5.5M  Msgs/Sec: 0.0  Bytes/Sec: 0

Connections Polled: 30
  HOST             CID    SUBS    PENDING     MSGS_TO     MSGS_FROM   BYTES_TO    BYTES_FROM  LANG     VERSION  UPTIME   LAST ACTIVITY
  ::1:33128        5      0       0           0           0           0           0           C        2.1.0    4h9m39s  2020-03-05 13:08:04.26647882 +0000 UTC
  127.0.0.1:46370  6      10      0           0           1.5K        0           188.5K      python3  0.10.0   4h9m39s  2020-03-05 17:17:37.650263094 +0000 UTC
  127.0.0.1:46372  7      10      0           0           0           0           0           python3  0.10.0   4h9m39s  2020-03-05 13:08:04.269567142 +0000 UTC
  127.0.0.1:46374  8      4       0           0           0           0           0           python3  0.10.0   4h9m39s  2020-03-05 13:08:04.28167677 +0000 UTC
  127.0.0.1:46376  9      21      0           0           4.4K        0           650.4K      python3  0.10.0   4h9m39s  2020-03-05 17:17:41.862616553 +0000 UTC
  127.0.0.1:46379  10     11      0           0           0           0           0           python3  0.10.0   4h9m39s  2020-03-05 13:08:04.26856251 +0000 UTC
  127.0.0.1:46380  11     11      0           0           0           0           0           python3  0.10.0   4h9m39s  2020-03-05 13:08:04.268654953 +0000 UTC
  127.0.0.1:46384  12     2       0           0           0           0           0           python3  0.10.0   4h9m39s  2020-03-05 13:08:04.27004513 +0000 UTC
  127.0.0.1:46382  13     19      0           0           4.4K        0           650.4K      python3  0.10.0   4h9m39s  2020-03-05 17:17:41.862061191 +0000 UTC
  127.0.0.1:46386  14     16      0           8.8K        1.5K        1.4M        165.2K      python3  0.10.0   4h9m39s  2020-03-05 17:17:39.548959936 +0000 UTC
  127.0.0.1:46388  15     3       0           0           0           0           0           python3  0.10.0   4h9m39s  2020-03-05 13:08:04.26894017 +0000 UTC
  127.0.0.1:46390  16     0       0           0           0           0           0           python3  0.10.0   4h9m39s  2020-03-05 13:08:04.269772687 +0000 UTC
  127.0.0.1:46392  17     27      0           35.1K       0           4.0M        0           python3  0.10.0   4h9m39s  2020-03-05 17:17:42.084945408 +0000 UTC
  127.0.0.1:46394  18     11      0           0           0           0           0           python3  0.10.0   4h9m39s  2020-03-05 13:08:04.271032305 +0000 UTC
  127.0.0.1:46396  19     7       0           0           1.5K        0           174.0K      python3  0.10.0   4h9m39s  2020-03-05 17:17:41.280464006 +0000 UTC
  127.0.0.1:46398  20     2       0           0           0           0           0           python3  0.10.0   4h9m39s  2020-03-05 13:08:04.278716059 +0000 UTC
  127.0.0.1:46404  22     19      0           0           4.4K        0           650.4K      python3  0.10.0   4h9m39s  2020-03-05 17:17:42.084945408 +0000 UTC
  127.0.0.1:46402  23     3       0           0           0           0           0           python3  0.10.0   4h9m39s  2020-03-05 13:08:04.281193493 +0000 UTC
  127.0.0.1:46406  24     3       0           0           0           0           0           python3  0.10.0   4h9m39s  2020-03-05 13:08:04.281234716 +0000 UTC
  127.0.0.1:46412  25     0       0           0           0           0           0           python3  0.10.0   4h9m39s  2020-03-05 13:08:04.28079764 +0000 UTC
  127.0.0.1:46408  26     4       0           0           0           0           0           python3  0.10.0   4h9m39s  2020-03-05 13:08:04.281359259 +0000 UTC
  127.0.0.1:46410  27     2       0           0           0           0           0           python3  0.10.0   4h9m39s  2020-03-05 13:08:04.280998367 +0000 UTC
  127.0.0.1:46414  28     0       0           0           0           0           0           python3  0.10.0   4h9m39s  2020-03-05 13:08:04.280658062 +0000 UTC
  127.0.0.1:46416  29     11      0           499         998         2.9K        80.4K       python3  0.10.0   4h9m39s  2020-03-05 17:17:20.073555878 +0000 UTC
  127.0.0.1:46418  30     3       0           0           0           0           0           python3  0.10.0   4h9m39s  2020-03-05 13:08:04.281872134 +0000 UTC
  127.0.0.1:46420  31     4       0           0           0           0           0           python3  0.10.0   4h9m39s  2020-03-05 13:08:04.28267901 +0000 UTC
  127.0.0.1:46422  32     2       0           0           0           0           0           python3  0.10.0   4h9m39s  2020-03-05 13:08:04.29191144 +0000 UTC
  127.0.0.1:46424  33     2       0           499         499         17.5K       2.9K        python3  0.10.0   4h9m39s  2020-03-05 17:17:20.072149961 +0000 UTC
  ::1:33188        35     0       0           0           0           0           0           C        2.1.0    4h9m38s  2020-03-05 13:08:05.270186006 +0000 UTC
  ::1:33196        36     2       0           0           0           0           0           C        2.1.0    4h9m37s  2020-03-05 13:08:06.307786528 +0000 UTC

```

#### OS/Container environment:
Ubuntu Bionic, Docker (version 19.03.3) container, 64 bit

**Comment by matthiashanel** [comment]
Hello Arun

In go, the language the nats-server is written in, there are no threads.
However, at some point go has to interact with the operating system. 
In our case this is mostly for networking.

The threads you are seeing correspond to:
a) Number of logical cores to execute go routines.
b) And the number of parallel system calls (threads from a.) manage to issue

I gathered that from the [runtime](https://golang.org/pkg/runtime/) documentation. Specifically:
> The GOMAXPROCS variable limits the number of operating system threads that can execute user-level Go code simultaneously. 
> There is no limit to the number of threads that can be blocked in system calls on behalf of Go code; 
> those do not count against the GOMAXPROCS limit. 

Unfortunately I was not able to find when or if go ever lets of these threads.
So b. form above should probably be restated as:
b) And the **max** number of parallel system calls threads from a. managed to issue **at one point in the past**.

That is probably the most important point:
At one point in time your system used X cores (say you start all clients at the same time).
Now, much later, there is not a lot going on but go has not disposed of the threads.

I tested this:
Started clients had them do some work
As expected the thread count went up.
The clients exited.
The thread count remained unaltered and did **NOT** go down.
To make sure we are not leaking go routines etc,... I killed the server.
As expected there where fewer, a lot fewer than threads.

Throughout the 4 hours you mention, was your system always this idle? Or is it idle just now?
Through my reading and experimentation I believe a spike in traffic may have caused the thread count to go up. Then go does not let go of them.

As a consequence, looking at the thread count may not be a good measurement for highly concurrent go programs such as nats-server.
This may have been a valid measure for programs in languages that expose threads.
In go, threads are used so the program is not blocked waiting for system calls to return.

> Disclaimer: We do **NOT** generally recommend altering GOMAXPROCS. 
> **!!! Lowering it WILL slow down your system significantly !!!**
> ** changing the metric is more appropriate **

That said, if you set it to one, there are only so many system calls that can happen at any given point in time.
As a workaround you could try reducing GOMAXPROCS (export GOMAXPROCS=8) 

I tested this:
I have 16 cores on my system so GOMAXPROCS has a default value of 16.
I set an internal thread limit to 35 and ran a benchmark causing the server to hit just that limit.
As expected the server was killed.
Halving GOMAXPROCS allowed my test to constantly remain below 35 threads.
Setting GOMAXPROCS to 1 brought the test to a crawl.

@kozlovic pointed out this [article](https://medium.com/a-journey-with-go/go-goroutine-os-thread-and-cpu-management-2f5a5eaf518a) explaining go routines thread relationship 

Let me know if this is helping - Matthias

**Comment by arun11299** [comment]
@matthiashanel 
Thanks for the detailed answer. Very much appreciate that.
I kind of was expecting this behaviour as Python concurrent.Threadpool also has this behaviour when max_workers is not capped i.e it would at max create some multiple of number of cores available in the system.
Since we are container based application, the bare metal has 64 or more CPUs. So, the thread creation would also be higher.

BTW, I checked with latest version i.e 2.1.4, there also thread used increases during idle time, but not as much as 2.0.0

I think for now, its best for me to not cap the thread using GOMAXPROCS. Please do let me know if we do need to cap it on high end bare metal servers.

Thanks.

**Comment by matthiashanel** [comment]
@arun11299 
Agreed!

Anything that alters timing of a. probably will impact how many threads in excess of GOMAXPROCS you'll see. Upgrading your go version probably will too. This is not under our control.

There is a theoretical limit on how many cores you can throw at a problem ([Amdahl's Law](https://en.wikipedia.org/wiki/Amdahl%27s_law)) 
Heat is a physical limitation. Processors get slowed down when too many are running.
Then there are side effects due to caching. Real cores or hyper threads...
I've seen system performance increase due to work batches getting bigger when individual components became slower. 
All of the above heavily depends on your particular workload. 
That is during peaks how many: connections publishing/subscribing, same vs different subjects, wildcards, what's the communication pattern....

So, there is a value of GOMAXPROCS that probably is **too big**. 
There is also a value of GOMAXPROCS that is **too small**. 

A value of 4 being reasonable has been quoted to me.
My general recommendation would be to **only modify** GOMAXPROCS when you are **benchmarking and testing the outcome** as well.

If with the upgrade to 2.1.4 you do not run into your problem any more, I'd leave it as is as the system seems to be doing it's job.
If your GOMAXPROCS is very large and you run into the metrics checker again, consider reducing the value but do test if your **non idle workloads** are still being served adequately.

Here is a [snippet](https://stackoverflow.com/questions/17853831/what-is-the-gomaxprocs-default-value) of code that you can use do check what GOMAXPROCS on your box, in your container is. Just start that program in the container where you run nats-server.

Glad I could help - Matthias

Ok to close this issue?

**Comment by arun11299** [comment]
Thanks @matthiashanel 
Yes, will close this issue. Thanks.
