### ISSUE TITLE
monitoring only shows up to TLS 1.2 info (version, cipher)

### ISSUE THREAD

**Issue by burner-account** [nats-io/nats-server#1313]
- [X] Feature Request or Change Proposal

## Component
Monitoring
  
## Feature Requests
I would love to see my monitoring showing correct info for TLS 1.3 connz.

### currently
TLS 1.3 version shown as Unknown [304]
TLS 1.3 cipher shown as Unknown [%x]

### proposed
TLS 1.3 version shown as 1.3
TLS 1.3 ciper shown as value from cipherMap

### changes
This would require few changes:

a ) Extend the switch statement in
`func tlsVersion(ver uint16) string` in server/server.go
to also check for the TLS 1.3 version constant.
```
// from "tls"
VersionTLS13 = 0x0304
```

b) Extend the ciperMap and cipherMapByID to include the new TLS 1.3 constants in server/ciperhsuites.go.

```
// from "tls"
TLS_AES_128_GCM_SHA256       uint16 = 0x1301
TLS_AES_256_GCM_SHA384       uint16 = 0x1302
TLS_CHACHA20_POLY1305_SHA256 uint16 = 0x1303
```

c) Just a matter of taste: The TLS version 0x0304 represented as "Unknown [304]" in the JSON output of the connz route might be considered misleading. I would prefer it being prefixed with some indication of base 16 encoding like "0x". see `func tlsVersion(ver uint16) string` in server/server.go.

From my point of view it seems these changes would not introduce new problems.

**Comment by derekcollison** [comment]
Thanks, and agree. Will update.
