### ISSUE TITLE
Support SPIFFE x.509 SVIDs for client authentication

### ISSUE THREAD

**Issue by colek42** [nats-io/nats-server#1325]
- [ ] Defect
 - [X] Feature Request or Change Proposal
 
## Feature Requests

The SPIFFE specification creates a URI entry in the SAN field  ref: https://github.com/spiffe/spiffe/blob/master/standards/X509-SVID.md#7-conclusion
 
#### Use Case:

Integrate NATS authorization with SPIFFE identity documents

#### Proposed Change:

add ```hasSANs := len(cert.URIs) > 0``` and logic to https://github.com/nats-io/nats-server/blob/e126a1f9d83a96d8c48d06718cf392ca7fba6cbd/server/auth.go#L536

ref:  https://golang.org/src/crypto/x509/x509.go#L744
 
#### Who Benefits From The Change(s)?

Users using SPIFFE for identity (i.e. Istio users)
 
#### Alternative Approaches

Consume the client library ref: https://github.com/spiffe/go-spiffe for a SPIFFE specific implimentation

**Comment by wallyqs** [comment]
Thanks for sharing I will take a look.
