### ISSUE TITLE
Subject Hierarchy is consuming more CPU

### ISSUE THREAD

**Issue by rishikeshbedre** [nats-io/nats-server#1328]
- [ * ] Defect
 - [ ] Feature Request or Change Proposal
 
#### Versions of `nats-server` and affected client libraries used:
Nats-Server: v2.1.2
Nats-client: nats.js: v1.4.8

#### OS/Container environment:
Environment: Both nats-server and client are containers.
RAM: 8GB
CPU: intel celeron 1.83GHz

#### Steps or code to reproduce the issue:
I am running this benchmark script present in [nats.js repo](https://github.com/nats-io/nats.js/blob/master/benchmark/pub_sub_perf.js) with little modification to include and exclude subject hierarchy. **I am running these tests with user authorization like username and password with permission for particular subject for publish and subscribe.**

For Example: 
1) Without subject hierarchy:
     Publish on subject 'test' and Subscribe on subject 'test'.
     Result is around 70k messages/second with 27% CPU usage.

2) With Subject hierarchy:
    Publish on subject such as 'test.1' , 'test.2' , .... and subscribe on subject 'test.>' 
    Result is around 50k messages/second with 114% CPU usage.

Is this a expected behavior?
 
#### Observation:
I guess the subject match for each publish and subscribe with subject hierarchy is consuming CPU. Can you change this behavior to improve the performance?

**Comment by derekcollison** [comment]
This example will thrash the L1 no lock cache for the client and cause a cache miss and call into the shared sublist structure, hence the increase in CPU and lower performance.

I can look into this case as I actually have it on my todo list for request/response which defaults to this pattern, meaning the reply subjects are one use only.

**Comment by vinayxbox** [comment]
Isn't it the issue with subject string comparison for wildcard subscription ?
I also faced this issue.

**Comment by derekcollison** [comment]
The routing algorithms have several layers. The fastest is an L1 style cache that has no locking for when the subject space does not change much and their are certain publish subjects that repeat with high probability.

If that misses we ask the sublist structure to match the subject to all subscriptions, this can utilize an internal L2 style cache that does have locking around it. The matching literal or wildcard at this branch is not significant. You can test that by modifying the second test slightly and keeping the wildcard subscription but send the same subject, say `test.22` every time. You should see performance that matches the first scenario you test.

**Comment by derekcollison** [comment]
Closing for now, feel free to re-open if needed.
