### ISSUE TITLE
extra non wildcard response subscription sent on leaf node restart

### ISSUE THREAD

**Issue by matthiashanel** [nats-io/nats-server#1349]
- [x] Minor Defect
 - [ ] Feature Request or Change Proposal
 
## Defects 
This setup is very similar to #1344 instead of response type singleton, it uses response type stream. 

Two servers are started with below configuration:
`nats-server -c good -DV` and `nats-server -c evilinc.cfg -DV`

`nats-rply -s "nats://evil:pwd@0.0.0.0:4222" foo leaf` connects to evilinc
`nats-req -s "nats://good:pwd@0.0.0.0:5222" from_evilfoo hub` connects to good
and request reply works.

When the server evilinc is restarted I see an extra (non wildcard) subscription `_R_.xxx.yyy` sent to it.
Without any need server good sends this on reconnect.
This subscription is a response associated with the last request prior to restart.
This subscription is also unnecessary as the wildcard `_R_.xxx.>` is sent too.
Furthermore,  I have never observed such a subscription being sent outside of restart. (not before, nor after restart)

The screenshot contains comments // which where added by me.
![Screen Shot 2020-04-14 at 3 10 19 PM](https://user-images.githubusercontent.com/19881388/79620543-2f20df80-80de-11ea-8706-3b1876b09153.png)

Config
```bash
19:09:32  ~/test/cfg/test  cat good.cfg
listen: 127.0.0.1:5222

accounts: {
    INTERNAL: {
        users: [
            {user: good, password: pwd}
        ]
        exports: [{service: "foo", response: stream}]
	    imports: [
            {
                service: {
                    account: EXTERNAL
                    subject: "evilfoo"
                }, to: from_evilfoo
            }
        ]
    },
    EXTERNAL: {
        users: [
            {user: evil, password: pwd}
        ]
        exports: [{service: "evilfoo", response: stream}]
	    imports: [
            {
                service: {
                    account: INTERNAL
                    subject: "foo"
                }, to: goodfoo
            }
        ]
    },
}

leafnodes {
	remotes = [
        {
            url:"nats://127.0.0.1:4223"
            account:"EXTERNAL"
        },
    ]
}
 19:09:35  ~/test/cfg/test  cat evilinc.cfg
listen: 127.0.0.1:4222

accounts: {
    INTERNAL_EVILINC: {
        users: [
            {user: evil, password: pwd}
        ]
        exports: [{service: "foo", response: stream}]
	    imports: [
            {
                service: {
                    account: EXTERNAL_GOOD
                    subject: "goodfoo"
                }, to: from_goodfoo
            }
        ]
    },
    EXTERNAL_GOOD: {
        users: [
            {user: good, password: pwd}
        ]
        exports: [{service: "goodfoo", response: stream}]
	    imports: [
            {
                service: {
                    account: INTERNAL_EVILINC
                    subject: "foo"
                }, to: evilfoo
            }
        ]
    },
}

leafnodes {
	port: 4223
	authorization {
    	account:"EXTERNAL_GOOD"
	}
}
 19:09:35  ~/test/cfg/test 
```

**Comment by derekcollison** [comment]
Thanks, will try to reproduce in similar tests to the others.

**Comment by derekcollison** [comment]
I think this is addressed in jetstream branch. But wanted you to confirm.

**Comment by derekcollison** [comment]
This has been fixed.
