### ISSUE TITLE
Load balancing: one nats pod doesn't get any messages after restart in Kubernetes

### ISSUE THREAD

**Issue by emailtovamos** [nats-io/nats-server#1359]
- [x] Question
 
I have been using nats in Kubernetes following [this recommended statefulset](https://gist.github.com/wallyqs/c566c856b7119645fd7e11056374c584) which was suggested in [this issue 
](https://github.com/nats-io/nats-server/issues/1151) 

I have 3 replicas, `nats-0`, `nats-1`, `nats2`. 
Recently I restarted `nats-0`. However now `nats-0` doesn't get any requests but `nats-1` and `nats-2` do keep getting messages. 

1 - What can I do to resolve this? Is there any load balancing logic already in place or does it have to be taken care of by me? 

2 - Also if I need to increase instances, can I simply add nats-3 just like the other ones have been added? 

Thanks.

**Comment by wallyqs** [comment]
Hi @emailtovamos are there clients with subscriptions connected to `nats-0`? Maybe all nodes reconnected to nats-1 and nats-2 so there is no traffic on nats-0?

**Comment by emailtovamos** [comment]
Hi @wallyqs , 
The connection happens through the service, something like: 
`nc, err := nats.Connect("nats:4222")`

So there is not direct connection to a pod but rather the service should be able to connect to `nats-0` at some point which it doesn't even after I restart my service.

**Comment by matthiashanel** [comment]
The load balancing logic that is currently in place is essentially this:
The client picks a server at random and connect, they pick another one when that connect does not work.

When you restart a pod, your clients will connect to other servers.
When add a server (increase instances), clients will learn about it, and will try to connect to it when they need to reconnect again.

If you started a new server first, then shut down an old one, you'd get the behavior you describe.

**Comment by emailtovamos** [comment]
Thanks @matthiashanel for the details! 

> When add a server (increase instances), clients will learn about it, and will try to connect to it when they **need** to reconnect again.

This `need` can refer to when there is too many requests right? Otherwise messages won't work even though there is a new nats pod. 

> If you started a new server first, then shut down an old one, you'd get the behavior you describe.

I didn't fully understand it. Could you explain a bit more? 
Thanks!

**Comment by emailtovamos** [comment]
Thanks @matthiashanel , yes this explanation makes sense. 

I just want to clarify in my own words to see if I fully understood:
The NATS client doesn't "know" about the available servers when it is already connected and working right? And if a server goes down THEN it will try to find what other servers are available and then connect to one of them? 

I am asking because it seems that only when the currently connected servers are fully loaded, that is when the "free" 4th server will be utilised in the above example. So the load balancing isn't really active during the time the 4th server waits.

**Comment by matthiashanel** [comment]
@emailtovamos Almost ;-) When a client is connect to a server this server will tell the client about new server. But that client has a perfectly fine connection and thus does not need to connect to another server quite yet. 
Yes, if a server goes down, it will connect to one of the remaining ones. (this includes the new one)

Can you elaborate what you mean by fully loaded? 
Are you setting limits? 
Is this also the case when you start the 4th server first, wait a bit for it to be up, and then kill an old server?
What is your exact observation?
I'm starting to get a hunch of what might be up.

**Comment by matthiashanel** [comment]
@kozlovic , I think what happens here is that we shuffle server on initial Connect, when adding a new server it's added to the end of the list. In > 2 server scenarios without a prior restart, this causes the new server to not be next pick ever. If limits are present it'd cause to fail over to the next (an older) server, hit a connection limit, only after it checked connections, then get to the new server. Inserting at a random location between indexex [1:len-1] seems warranted, what do you think?

**Comment by emailtovamos** [comment]
Thanks @matthiashanel 

There was no limits set in the beginning. Everything was happening fine. Then at some point `nats-0` went down because the Kubernetes node which had this pod decided to restart. This happens from time to time in Kubernetes. 

The thing is that the "new" messages after this restart which were supposed to be sent to `nats-1` & `nats-2` didn't seem to work. I know this because in my grafana dashboard, I saw a sharp decrease in the numbers. This led me to think if the reconnection is truly happening properly or not. 

If this sounds confusing, then let me know. I will reorganise my thoughts and will try to present in a better manner. :) 

BTW I never started a 4th server. I always had only `nats-0`, `nats-1` & `nats-2`. After `nats-0` went down and came back up, it didn't receive any requests where my doubt regarding load balancing came out. But this is more clear now. 

Also if there is no limits set and no new client which need any connection or reconnection, then the restarted `nats` pod will simple sit idle?

**Comment by kozlovic** [comment]
@matthiashanel Where the "new" server is put in the list would not make a difference. When nats-0 went down, clients that were connected there already reconnected to nats-1 or nats-2. 

@emailtovamos It is true that once nats-0 is restarted, unless you get new connections or disconnects from existing applications, there is no rebalancing of connections. But that should not be an issue unless your servers cannot service properly existing clients.
Also, are you using client_advertise or not? I see that you provide "nats:4222" as the URL, but I wonder if the servers are configured to return a specific address. If not, the server resolves its non local IP addresses (assuming your server config uses "0.0.0.0" for the listen spec) and sends that to clients. Sometimes, those IPs will make no sense to the clients because they may not be reachable.
An easy way to check is to have a telnet session point to one of the server. You will see a `connect_urls` field in the INFO that list all the IPs that clients should use to connect to the cluster.

**Comment by matthiashanel** [comment]
@kozlovic for the situation of @emailtovamos you are right. But if I added a server first it would make a difference, would it not?

**Comment by kozlovic** [comment]
It would be the next to be picked, as opposed to an existing server, so I guess yes it would help level the number of connections, but again, only for clients that would reconnect. During the initial connect, the library goes through the list of servers given by the user, but it does also process the connect_urls from the INFO, so if we apply the same logic, this will change the list we are currently walking, not sure if this is ok or not (that is, should library first go through the user list vs discovered list).

**Comment by matthiashanel** [comment]
@kozlovic , in the code where we add server at the end, we also remove server.

**Comment by kozlovic** [comment]
But we remove only the implicit (the discovered) ones. But regardless, I think the code is safe and if not could be fixed to take into consideration that the list is changing as it is being walked.

**Comment by emailtovamos** [comment]
@kozlovic 
Thanks for the details! 
> Also, are you using client_advertise or not? 

No, I don't use `client_advertise`. I looked at the documentation [here](https://github.com/nats-io/nats.docs/blob/master/nats-server/flags.md#server-options) but don't fully understand how it works and how exactly to use it. Can you give an example? I basically use [this](https://gist.github.com/wallyqs/c566c856b7119645fd7e11056374c584) file which has the Kubernetes `service`, `statefulset` & `configmap`. 

>You will see a connect_urls field in the INFO that list all the IPs that clients should use to connect to the cluster.

Yes I do see 3 IP addresses after I port-forwarded nats Kubernetes service and did `telnet localhost 4222`.

**Comment by kozlovic** [comment]
You don't have to use client_advertise, I was just asking if you were using it. Are those IPs that are returned reachable from your applications? If so, then you don't have to do a thing. If not, it would then make sense to have client_advertise so that each server returns this address (host:port) as opposed to the local resolve of its IPs.

**Comment by bruth** [comment]
Closing as stale.
