### ISSUE TITLE
Add missing metadata keys to monitoring port subsz JSON

### ISSUE THREAD

**Issue by davidkemper** [nats-io/nats-server#1371]
Unlike the other `*z` (e.g., `connz` and `varz`), `subsz` is missing the `server_id` key.

It is also missing `now`.

There are probably other metadata fields that could be added, but these are the notable omissions.

Here is a recent `subsz` payload:

```
{
  "num_subscriptions": 0,
  "num_cache": 0,
  "num_inserts": 0,
  "num_removes": 0,
  "num_matches": 0,
  "cache_hit_rate": 0,
  "max_fanout": 0,
  "avg_fanout": 0
}
```

**Comment by derekcollison** [comment]
Also time, etc.

So server id and name and now fields.

**Comment by derekcollison** [comment]
And if we do not already  an account filter arg we can send.

**Comment by matthiashanel** [comment]
@derekcollison I would make subsz work like all the others meaning return everything.
In a separate issue add account args to all were applicable. 
That is add it to connz too

**Comment by derekcollison** [comment]
What do you mean everything? This is about subs but agree we need server id and name and now timestamp for request.

**Comment by matthiashanel** [comment]
I'll add the fields but also address #1357 

/subs like /connz should return all subscriptions, irrespective of account. 
Then I will also add an option to (/subsz and /connz to query by account) and expose via system events as well.

**Comment by derekcollison** [comment]
subsz is currently not a pageable destination, so you can not return any dynamic sized lists here.
Subsz totals should be for all accounts I agree, it may just be $G. Take care at holding the servers locks, probably snapshot s.accounts and go one by one asking them (or the sl) for the stats.
