### ISSUE TITLE
configuration reload that changes the system account does not take effect everywere

### ISSUE THREAD

**Issue by matthiashanel** [nats-io/nats-server#1372]
The reason for this is that config reload recreates all accounts including the system account  but does not change the pointer server.sys.account and it's copy server.sys.client.acc (taken by internalSendLoop).

Below config change changes the field to from CONNECT to DISCONNECT, then calls reload.
While the server is running, the change does not take effect.

As far as I can tell, JWT code actually updates the account instead of creating a new one.
I don't think we should allow modifying the system account.
While the config may seem contrived for now, it's hard to say that the pointer in question will always remain being used this way. Meaning future usages of c.acc may introduce another problem.

With the below config before and after reload, this subscriber will only receive the CONNECT event. `nats -s nats://user:pwd@localhost:4222 sub ">"`

Config before/after reload
```bash
> cat test.cfg
listen: localhost:4222
accounts: {
    USERS {
        users: [
            {user: "user", password: "pwd"}
        ]
        exports: [{service: "test"}]
    },
    SYS: {
        users: [
            {user: admin, password: changeit}
        ]
        imports: [
            {service: {account: USERS, subject: "test"}, to: "$SYS.ACCOUNT.USERS.CONNECT"},
        ]
    },
}
system_account: SYS
> vi test.cfg
> nats-server --signal reload
> cat test.cfg
listen: localhost:4222
accounts: {
    USERS {
        users: [
            {user: "user", password: "pwd"}
        ]
        exports: [{service: "test"}]
    },
    SYS: {
        users: [
            {user: admin, password: changeit}
        ]
        imports: [
            {service: {account: USERS, subject: "test"}, to: "$SYS.ACCOUNT.USERS.DISCONNECT"},
        ]
    },
}
system_account: SYS
>
```

**Comment by derekcollison** [comment]
This works if SYS not the system account I would imagine.

**Comment by matthiashanel** [comment]
@derekcollison , yes that works. The reason that works is that on reload (even if nothing changes) all accounts are re-generated consistently. The problem is that 'setSystemAccount(acc *Account) ' is not called. Not saying that it should, but this causes the problem. Essentially everything started by setSystemAccount will work with the old pointer and ignore reload.

Reload always detects a change when there is an import/export relationship present.
deep equal returns false probably because: Pointer values are deeply equal if they are equal using Go's == operator or if they point to deeply equal values.

**Comment by derekcollison** [comment]
So we should detect changes to system account on reload and handle separately is what you are suggesting yes?

**Comment by matthiashanel** [comment]
Yes, either by:
* prevent a new pointer: by making system account changes illegal (maybe simpler)
* using the new pointer: by stoping what setSystemAccount did and starting it again 
* updating the old pointer: by doing what updateAccountClaims does for the system account
