### ISSUE TITLE
On reload update accounts instead of replacing them

### ISSUE THREAD

**Issue by matthiashanel** [nats-io/nats-server#1388]
After discussion with Ivan:
The failure mode of forgetting to update smth is an easier one than forgetting to copy accumulated state. 

Later I also ran into the following data race on client.acc which can happen on reload for old clients. 

WARNING: DATA RACE
Write at 0x00c000099a78 by goroutine 152:
  github.com/nats-io/nats-server/server.(*Server).reloadAuthorization.func2()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/reload.go:1039 +0x34a
  sync.(*Map).Range()
      /home/travis/.gimme/versions/go1.14.2.linux.amd64/src/sync/map.go:333 +0x155
  github.com/nats-io/nats-server/server.(*Server).reloadAuthorization()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/reload.go:1027 +0xaa8
  github.com/nats-io/nats-server/server.(*Server).applyOptions()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/reload.go:940 +0x20d
  github.com/nats-io/nats-server/server.(*Server).reloadOptions()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/reload.go:689 +0x225
  github.com/nats-io/nats-server/server.(*Server).Reload()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/reload.go:630 +0x39d
  github.com/nats-io/nats-server/server.reloadUpdateConfig()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/reload_test.go:1636 +0x126
  github.com/nats-io/nats-server/server.TestConfigReloadAccounts()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/reload_test.go:4277 +0x71e
  testing.tRunner()
      /home/travis/.gimme/versions/go1.14.2.linux.amd64/src/testing/testing.go:991 +0x1eb
Previous read at 0x00c000099a78 by goroutine 548:
  github.com/nats-io/nats-server/server.(*client).processInboundClientMsg()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/client.go:2828 +0x2ec
  github.com/nats-io/nats-server/server.(*Server).internalSendLoop()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/events.go:284 +0x723

**Comment by matthiashanel** [comment]
```
WARNING: DATA RACE
Read at 0x00c001594d78 by goroutine 738:
  github.com/nats-io/nats-server/server.(*client).processInboundClientMsg()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/client.go:2828 +0x2ec
  github.com/nats-io/nats-server/server.(*Server).internalSendLoop()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/events.go:284 +0x723
Previous write at 0x00c001594d78 by goroutine 959:
  github.com/nats-io/nats-server/server.(*Server).reloadAuthorization.func2()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/reload.go:1039 +0x34a
  sync.(*Map).Range()
      /home/travis/.gimme/versions/go1.14.2.linux.amd64/src/sync/map.go:333 +0x155
  github.com/nats-io/nats-server/server.(*Server).reloadAuthorization()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/reload.go:1027 +0xaa8
  github.com/nats-io/nats-server/server.(*Server).applyOptions()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/reload.go:940 +0x20d
  github.com/nats-io/nats-server/server.(*Server).reloadOptions()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/reload.go:689 +0x225
  github.com/nats-io/nats-server/server.(*Server).Reload()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/reload.go:630 +0x39d
  github.com/nats-io/nats-server/server.reloadUpdateConfig()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/reload_test.go:1636 +0x126
  github.com/nats-io/nats-server/server.TestConfigReloadAccounts()
      /home/travis/gopath/src/github.com/nats-io/nats-server/server/reload_test.go:4278 +0x7e3
  testing.tRunner()
      /home/travis/.gimme/versions/go1.14.2.linux.amd64/src/testing/testing.go:991 +0x1eb
```

**Comment by matthiashanel** [comment]
PR   #1393 made the data race less likely to happen in our existing unit tests, but it does not remove the actual problem.

**Comment by derekcollison** [comment]
This still relevant?

**Comment by matthiashanel** [comment]
It is. Given how involved it seems (on reload, updating existing accounts instead of re-creating them) I would not put it very high on the list of priorities.

**Comment by derekcollison** [comment]
Should we close or leave open?

**Comment by matthiashanel** [comment]
Close, addressing this is probably too far out.
