### ISSUE TITLE
Expose oldest message timestamp in api

### ISSUE THREAD

**Issue by Ryner51** [nats-io/nats-server#1396]
## Feature Request
Expose oldest message timestamp in api

#### Use Case:
Ability to see what the oldest message is and compare that to what the max age of the stream is to see how close messages will be removed. 

#### Proposed Change:
Add first_message_ts in StreamState
https://github.com/nats-io/jsm.go/blob/master/api/streams.go#L140

#### Who Benefits From The Change(s)?
Anyone wanting to see what the oldest message in a stream is.

**Comment by derekcollison** [comment]
I would imagine we add both to mirror first and last sequence.

**Comment by Ryner51** [comment]
That would make sense. I could see value of seeing the age of the latest message as well as the oldest.

**Comment by derekcollison** [comment]
I have most of this working, question for @ripienaar I have this as UTC time but noticed that StoredMsg (when we get directly from a stream) is uint64 nanos.

**Comment by ripienaar** [comment]
Hmm probably best to try have ITC everywhere at least on API and so forth - all advisories etc have it that way

**Comment by derekcollison** [comment]
I was wrong, we are good.

**Comment by derekcollison** [comment]
ok implemented.

**Comment by ripienaar** [comment]
Thanks, jsm and nats utility also updated, closing this
