### ISSUE TITLE
Use custom DNS server

### ISSUE THREAD

**Issue by israellot** [nats-io/nats-server#1418]
## Feature Request
Ability to specify a custom DNS server to resolve cluster hosts.

#### Use Case:
Discovery of host using a custom dns server, ie Consul.

I have a nats cluster running alongside a consul cluster. I would like to use consul dns interface for seed node discovery. That would be easily done if I could tell nats which dns server to query.

**Comment by kozlovic** [comment]
Could you elaborate in how you would want that to be done? Are you embedding the NATS Server and would want to use their library to do DNS lookups?

**Comment by israellot** [comment]
I'm running NATS binaries, not embedding.
I have a cluster orchestrated by Consul and Nomad and I would like to instruct NATS to use  Consul's DNS server as resolver for cluster discovery, in other words, I need NATS to use a dns server different from the system one, possibly not on port 53 either. Currently I have to use dnsmasq to forward .consul requests from lookpback#53, but that's not possible in production in my case.

**Comment by ripienaar** [comment]
Just for reference do you have examples of other applications that has such a setting? I assumed this was your use case but I have not really seen many systems support custom resolvers as you suggest.
