### ISSUE TITLE
QueueSubscriptions stop working with leafnode

### ISSUE THREAD

**Issue by HeavyHorst** [nats-io/nats-server#1421]
If I extend my cluster with a LeafNode and then connect QueueSubscribers to the LeafNode everything works fine at first.

If I stop one of the subscribers (ctrl+c) all other subscribers stop receiving data. As soon as I restart any QueueSubscriber, they all work again.

I don't see this behavior without the leafnode.

Here is my little test case:

```go
package main

import (
	"fmt"
	"log"

	nats "github.com/nats-io/nats.go"
)

func main() {
	nc, err := nats.Connect(nats.DefaultURL)
	if err != nil {
		log.Fatal(err)
	}
	defer nc.Close()

	// Channel Subscriber
	ch := make(chan *nats.Msg)
	_, err = nc.ChanQueueSubscribe("queueTest1", "q1", ch)
	for v := range ch {
		fmt.Println(string(v.Data))
	}

}
```

**Comment by derekcollison** [comment]
How many queue subscribers? Where are they connected? Does it matter which one you kill?

Thanks for the report, will look into it with a bit more information.

**Comment by HeavyHorst** [comment]
I tested this with 2 and 3 queue subscribers all connected to the same leaf node. Doesn't matter which one i kill.

I publish directly to the cluster and not to the leaf node.

**Comment by derekcollison** [comment]
Thanks will take a look.

**Comment by derekcollison** [comment]
What version are you running? I just put together a quick test and it passes fine from master.

**Comment by derekcollison** [comment]
Here is what I plugged into the leafnode_test.go file under nats-server/test

```go
// https://github.com/nats-io/nats-server/issues/1421
func TestLeafNodeQueueSubscriberUnsubscribe(t *testing.T) {
	ca := createClusterWithName(t, "A", 3)
	defer shutdownCluster(ca)

	sl, _ := runSolicitLeafServer(ca.opts[1])
	defer sl.Shutdown()

	checkLeafNodeConnected(t, ca.servers[1])

	var received int32
	var conns []*nats.Conn

	// Connect 5 queue subscribers to the LN.
	for i := 0; i < 5; i++ {
		nc, err := nats.Connect(sl.ClientURL())
		if err != nil {
			t.Fatalf("Error on connect: %v", err)
		}
		conns = append(conns, nc)
		nc.QueueSubscribe("test", "dq", func(m *nats.Msg) {
			atomic.AddInt32(&received, 1)
		})
		nc.Flush()
	}

	// Connect the publisher to a cluster server.
	nc := clientForCluster(t, ca)

	// Send 10 messages
	for i := 0; i < 10; i++ {
		nc.Publish("test", nil)
	}

	waitForMsgs := func(expected int32) {
		checkFor(t, time.Second, 10*time.Millisecond, func() error {
			if r := atomic.LoadInt32(&received); r != expected {
				return fmt.Errorf("Only received %d messages out of %d", r, expected)
			}
			return nil
		})
	}

	waitForMsgs(10)

	// Now randomly kill off a queue subscriber.
	lc := conns[rand.Intn(len(conns))]
	lc.Close()

	// Send 10 more messages
	for i := 0; i < 10; i++ {
		nc.Publish("test", nil)
	}

	waitForMsgs(20)
}
```

**Comment by HeavyHorst** [comment]
I'm running v2.1.7 on all nodes.

This is my leafnode config:

```
leafnodes {
    remotes = [
        {
          urls: ["nats-leaf://nats02.edupool.cloud"]
          credentials: "blablabla.creds"
        },
    ]
}
```

and this is my publisher:

```
package main

import (
	"log"
	"time"

	"github.com/Pallinder/go-randomdata"
	"github.com/docker/docker/pkg/namesgenerator"
	nats "github.com/nats-io/nats.go"
)

func main() {
	nc, err := nats.Connect("tls://.....", nats.UserCredentials("......."))
	if err != nil {
		log.Fatal(err)
	}
	defer nc.Close()

	ec, _ := nats.NewEncodedConn(nc, nats.JSON_ENCODER)

	sendCh := make(chan map[string]interface{})
	ec.BindSendChan("hello", sendCh)

	for {
		me := map[string]interface{}{"Name": namesgenerator.GetRandomName(0), "Age": randomdata.Number(10, 90), "Address": randomdata.Address()}
		sendCh <- me
		time.Sleep(20 * time.Millisecond)
	}
}
```

**Comment by kozlovic** [comment]
I can reproduce. Will submit a PR later this morning.

**Comment by derekcollison** [comment]
What was incorrect about my test @kozlovic ? Specific to NGS?

**Comment by kozlovic** [comment]
No, I tried local with single server accepting LN, then create a LN connection. Create 2 queue subs of the same group on the spoke server, then stop one of the queue sub. I can see that we send `LS+ foo q1 1` (down from 2) followed by `LS- foo` that is because we call `srv.updateLeafNodes(acc, sub, -1)` in the loop that is supposed to deal with plain subs only and then we call that again with queue subs.

**Comment by derekcollison** [comment]
Wonder why my test did not show. Regardless good catch and thanks to @HeavyHorst for the report!

**Comment by kozlovic** [comment]
Because you did not wait for the close of the client to actually be processed. A simple sleep of 50ms shows the problem using your test.

**Comment by derekcollison** [comment]
Well there you go.. ;)

**Comment by wallyqs** [comment]
Thanks @HeavyHorst somewhat unrelated to the original issue since not the root cause, but using an unbuffered channel can also cause to drop messages so better to allocate a buffer to the channel (sharing just in case).

```go
	ch := make(chan *nats.Msg, 8192)
	_, err = nc.ChanQueueSubscribe("queueTest1", "q1", ch)
```
