### ISSUE TITLE
Continuous fuzzing

### ISSUE THREAD

**Issue by AdamKorcz** [nats-io/nats-server#1442]
#### Use Case:
[This bug](https://github.com/nats-io/nats-server/pull/1441) was found by use of a fuzz test, and fuzzing the parser is an effective way to search for other crashes in the nats-server. 

#### Proposed Change:
I have written a fuzzer for the parser. I propose to include it in the nats-server repository and setup continuous fuzzing through oss-fuzz. This will allow Google to run the fuzzer continuously to look for bugs. oss-fuzz is a free service that is offered with an implied expectation that bugs are found, so that the resources spent on fuzzing nats-server are put to good use. If any bugs are found, maintainers are emailed a link to a detailed bug report.

#### Who Benefits From The Change(s)?
All nats users

**Comment by AdamKorcz** [comment]
Is it possible to ask kindly for feedback on this?

**Comment by derekcollison** [comment]
Please submit PR, we would be happy to take a look!

**Comment by matthiashanel** [comment]
@AdamKorcz we would welcome such a PR. The only thing would be new dependencies, but @wallyqs has recently found a way to separate out test dependencies.
