### ISSUE TITLE
Print configuration file used in startup banner

### ISSUE THREAD

**Issue by kozlovic** [nats-io/nats-server#1451]
## Feature Request
Report the name of the configuration file being loaded by the server.

#### Use Case:
One of the docker image is incorrectly not using the provided configuration file by default.
Having the config file being used printed would have helped users notice this issue faster.
See https://github.com/nats-io/nats-docker/issues/36

#### Proposed Change:
If a configuration file is specified, print it in the banner.

#### Who Benefits From The Change(s)?
People deploying a NATS Server and want to make sure that proper configuration file is being used.

#### Alternative Approaches
N/A

**Comment by rmoriz** [comment]
IMHO it should explicitly say the fact when no configuration file is used (e.g. "no configuration file provided, using default configuration" ) as this would have made the related issue with the alpine docker image easier to spot.



Von meinem iPhone gesendet

**Comment by kozlovic** [comment]
@rmoriz Knowing that from now on we would print if a configuration file is used, would not the absence of the statement in the log be enough?
That being said, I can certainly what you suggest, except that it should probably be simply" No configuration file provided", because you can still provide configuration through command line parameters, so it is not "using default configuration".
