### ISSUE TITLE
Binding monitoring port to localhost causes an error

### ISSUE THREAD

**Issue by aleybovich** [nats-io/nats-server#1456]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ ] Included `nats-server -DV` output
 - [ ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:
2.1.7

#### OS/Container environment:
Alpine linux 3.11

#### Steps or code to reproduce the issue:
Set monitoring port in `/etc/nats/nats-server.conf` as per https://docs.nats.io/nats-server/configuration/monitoring#enable-monitoring-from-the-configuration-file

```
port: 4222

http_port: localhost:8222
```

Start nats server: `nats-server ----config /etc/nats/nats-server.conf`

#### Expected result:
Server successfully starts

#### Actual result:
Error: `nats-server: /etc/nats/nats-server.conf:3:1: interface conversion: interface {} is string, not int64`

**Comment by derekcollison** [comment]
just do this..

`http: localhost:8222`

**Comment by aleybovich** [comment]
@derekcollison  right, I confused `http` and `http_port` settings. Thank you!
