### ISSUE TITLE
PHP Client for NATS Server & NATS Streaming

### ISSUE THREAD

**Issue by ljfreelancer88** [nats-io/nats-server#1462]
Hi! Is there any plan to develop a PHP Client for NATS Server & NATS Streaming? There is an existing Community package but it's not that stable and not actively maintain. I wish, someone in NATS team will add these two, since you already know the in and outs of NATS, it will be easier for us to find solutions or support from NATS team.

Thank You in advance.

**Comment by alifpay** [comment]
Hi!
you can try
https://github.com/kitech/php-go

**Comment by haohello** [comment]
Any update on this? Since there are over 80% of the websites are powered by PHP, not sure why you guys choose not to support PHP?
