### ISSUE TITLE
server safety

### ISSUE THREAD

**Issue by ximply** [nats-io/nats-server#1468]
when I telnet a auth required nats-server, server will loging out some server info to console,just like as follows:
![image](https://user-images.githubusercontent.com/3693445/84340207-bf593d80-abd2-11ea-8d82-80e74aa36c76.png)

I think the server should hide these info for safety.

**Comment by derekcollison** [comment]
The client ip is the ip from the machine you used to telnet. It is not disclosing any information that is not already known or easily identifiable.

For the connect_urls, that is the server advertising the other servers in the cluster, that is by design.

**Comment by ximply** [comment]
As a user,  these info is ok, but hackers?

**Comment by derekcollison** [comment]
Again the client_ip is the client's ip from where the connection is coming, they already know this.

For the other servers in a cluster, trivial to find without this information with simple port scan, so not protecting anything here.

**Comment by kozlovic** [comment]
@ximply If you don't want to see the connect_urls in the INFO block, then you can disable client advertising with `--no_advertise` or option `no_advertise` in the `cluster{}` block in config file.
But in that case it means that the client libraries will not learn about other servers in the cluster and would have to specify the whole cluster urls in their connect() call to be able to reconnect to any of the node in the cluster.

**Comment by ximply** [comment]
Within the LAN network, connect_urls  are useful, but within the WAN network and nats-servers behind the tcp proxy( such as haproxy), connect_urls  are privte IPs and they are not useful, so, in this case connect_urls or other sensitive infomations should be hide  for safety.

**Comment by kozlovic** [comment]
As I said, you can disable if you wish, but you can't hide it from the INFO if they are enabled. I understand your concerns, but this is how NATS has been designed originally: after accepting a TCP connection, the server sends the INFO first. The client reads and also gets if TLS/auth is required, etc..
With websocket support in master (not in official release but avail as nightly builds: https://hub.docker.com/u/synadia), the server will do TLS right away and so the INFO will be sent on an encrypted connection. I am not suggesting that you should use websocket just for that though.

**Comment by ximply** [comment]
@kozlovic thanks.

**Comment by ripienaar** [comment]
If running behind a load balancer - which I know we dont recomment - this leaks the LB internal IP and internal IP space of the servers.

**Comment by derekcollison** [comment]
no_advertise will not send the server URLs, or are you talking about something else?

**Comment by ripienaar** [comment]
Client IP would be that if the LB

**Comment by derekcollison** [comment]
Ah I see what you are saying.
