### ISSUE TITLE
Bug when consuming msgs but not ack-ing using jetstream

### ISSUE THREAD

**Issue by kushtrimjunuzi** [nats-io/nats-server#1502]
In order to reproduce this issue you need to run this program twice. First run after it publish 2 msgs you can terminate, then on a second run you have to wait ~1-2 min for CPU to spike and that's coming from nats server.
Nats server and jsm.go are latest version I just pulled today.

As you can see in the program I'm not ack-ing (m.Respond(nil)), if I do then everything works.

```
package main

import (
	"context"
	"fmt"
	"log"

	"time"

	"github.com/nats-io/jsm.go"
	"github.com/nats-io/nats.go"
)

func main() {

	nc, err := nats.Connect("localhost:4222")
	if err != nil {
		log.Fatal(err)
	}
	defer nc.Close()

	jsm.SetConnection(nc)

	stream, err := jsm.NewStreamFromDefault(
		"ORDERS",
		jsm.DefaultStream,
		jsm.StreamConnection(jsm.WithConnection(nc)),
		jsm.FileStorage(),
		jsm.MaxAge(24*time.Hour),
		jsm.Subjects("ORDERS.*"),
	)
	if err != nil {
		log.Fatal(err)
	}

	defer stream.Delete()

	nc.Publish("ORDERS.test", []byte("something"))
	nc.Publish("ORDERS.test", []byte("something"))

	ctx, cancel := context.WithTimeout(context.Background(), time.Hour*1)
	defer cancel()

	c, err := jsm.NewConsumer("ORDERS",
		jsm.DurableName("PULL"),
		jsm.FilterStreamBySubject("ORDERS.test"),
		jsm.StartAtSequence(1),
	)
	if err != nil {
		log.Fatal(err)
	}

	readPullMsg(c, ctx)
	if err := c.Delete(); err != nil {
		log.Fatal(err)
	}
}

func readPullMsg(c *jsm.Consumer, ctx context.Context) {
	state, err := c.DeliveredState()
	if err != nil {
		fmt.Println(err)
		return
	}
	pendingMsgs, err := c.PendingMessageCount()
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println("durableName:", c.DurableName(), "consumerSeq:", state.ConsumerSeq, "streamSeq:", state.StreamSeq, "startSequence:", c.StartSequence(), "pendingMsgs:", pendingMsgs)
	for {
		m, err := c.NextMsg(jsm.WithContext(ctx))
		if err != nil {
			log.Println(err)
			break
		}

		fmt.Printf("msg data: %s\n", m.Data)
		//m.Respond(nil)
	}
}

**Comment by kushtrimjunuzi** [comment]
After running the life saving tool pprof (thanks go team) I was able to figure out where is the issue and it is recursive call in consumer.go checkPending func right [here](https://github.com/nats-io/nats-server/blob/master/server/consumer.go#L1412).
I'll check tomorrow if I have time to send a patch if not then next week.

**Comment by kushtrimjunuzi** [comment]
I was able to debug further and I noticed that calculating the next scheduler for checkPending is producing negative value and that was the core issue why is entering on recursive state. I changed that line to default config.AckWait 
```
if len(o.pending) > 0 {
		o.ptmr.Reset(o.ackWait(0)) 
```
and now it is working as expected, not sure if that has some side effect, probably @derekcollison can help on that since he added that part in this [commit](https://github.com/nats-io/nats-server/commit/4d62a7237de1722e396c56ea31d92420da64e44e)

**Comment by derekcollison** [comment]
Thanks, I will take a look at this and hopefully have a fix for you later today. Thanks.
