### ISSUE TITLE
Must nats-rply and nats-req be connected to the gateway between the two clusters?

### ISSUE THREAD

**Issue by linyuan0** [nats-io/nats-server#1518]
I deployed two clusters, cluster A and cluster B. Each cluster has a gateway and a server, and A and B are connected through the gateway. Use the nats client for testing, nats-rply connects to the gateway under cluster A, and nats-req connects to the gateway under cluster B, so that it can respond to normal requests; if nats-rply connects to the server under cluster A (not the gateway), nats -rply can receive the requested message, but nats-req cannot receive the response message.
**I want to ask is it necessary to connect both req and rply to the gateway? Can nats support requests and responses for non-gateway connections in the future?**

**Comment by nuharaf** [comment]
maybe permission on _INBOX ?

**Comment by ripienaar** [comment]
Generally you don’t have a designated gateway in a cluster. All machines in a cluster should have the gateway configuration settings.

**Comment by linyuan0** [comment]
@ripienaar Okay, it seems that you have to pass the gateway to respond to the message.

**Comment by ripienaar** [comment]
reply can run on any server and request on any server.  If it doesn't work it seems your cluster is not correctly setup

**Comment by kozlovic** [comment]
@linyuan0 To connect 2 clusters to each other, each node in the cluster needs to have the same gateway configuration. For gateways to work, each node must have an outbound gateway connection to any node to the remote cluster. So if you specify `gateway{}` in only one node of a given cluster, this is a misconfiguration and messages routing between cluster won't work.
