### ISSUE TITLE
Will sending a message too fast cause the message to be lost?

### ISSUE THREAD

**Issue by linyuan0** [nats-io/nats-server#1520]
I use nats-bench to test the sending and receiving of messages, but I find that sometimes the number of messages sent is more than the ones received; when sending messages too fast, if nats-server is too late to process, will some messages be discarded?
How does nast-server handle this situation? Is it guaranteed that the amount sent and received is the same?

**Comment by ripienaar** [comment]
NATS will protect the server from over demanding clients by disconnecting them if they are too slow to consume messages.  So for example if a consumer falls behind the publisher and the backlog is too big the consumer can be disconnected with messages being lost.

**Comment by linyuan0** [comment]
@ripienaar OK，thanks a lot.

**Comment by ripienaar** [comment]
Read here https://docs.nats.io/developing-with-nats/events/slow

**Comment by linyuan0** [comment]
@ripienaar OK
