### ISSUE TITLE
Listen on TLS and non TLS on different port

### ISSUE THREAD

**Issue by lucj** [nats-io/nats-server#1541]
## Feature Request

Use different ports to get plain text and encrypted traffic

#### Use Case:

This will allow to use a NATS cluster for:
- non encrypted communication between internal clients (same VPC)
- encrypted communication when clients are external to the VPC

The logic behind this request is to allow external clients to subscribe to subject published internally. When internal access does not always need to be encrypted, external access must be. 

Having 2 different ports will also allow to restrict authorized CIDR for non encrypted / encrypted communication in an independent way.

#### Proposed Change:

Allow several *listen* instructions in the configuration file, each one with its own tls configuration.  

#### Who Benefits From The Change(s)?

An application using NATS internally and which needs to open up the NATS cluster to the external world.

#### Alternative Approaches

Not really sure the best alternative approach without any operational overhead.

**Comment by derekcollison** [comment]
Currently we allow this in the main branch on the same port. We have a design for CIDR restrictions that still needs to be coded up.

**Comment by ripienaar** [comment]
The typical scenario is that corp security people will want to CIDR restrict traffic to the different ports, rather than every app implement their own CIDR restrictions that's why I also think a model of multiple listening ports is a better fit

**Comment by lucj** [comment]
Indeed, a typical use case would be to have NATS running within an AWS VPC and using Security Group to only open TLS access so the node can be reached securely from the outside, and adding a CIDR restricted access in the SG as well. 
Cluster’s nodes would also listen on non encrypted port for all the VPC internal communications.

**Comment by ripienaar** [comment]
Lots to consider here, we'd need per port advertising options and per port tls options at least, probably some others

**Comment by zubairalimansoor** [comment]
> 
> 
> What version of the server?
> What does the server print out when running with `-DV` when trying to connect with the TLS client?

Thank you for your reply, I am using 2.23 and I don't see anything on server when I use tls client but there is exception in C# tls client "A secure connection is requested" and its description says "The exception that is thrown when a secure connection is requested but not required"

it looks like something need to be adjusted in tls client. Here is code to create tls client connection. If I disable  "allow_non_tls" in server config then tls client works but non tls client does not work. 

  public IConnection CreateConnection(eNatsConnType conType)
        {
            Options opts = ConnectionFactory.GetDefaultOptions();
            opts.Url = "tls://localhost:4222";

            opts.AllowReconnect = true;
            opts.Name = "DF";
            opts.Timeout = ConstantNatsConnection.TimeOut;

            opts.MaxReconnect = Options.ReconnectForever;
            opts.MaxPingsOut = 3;
            opts.PingInterval = 1000 * 3;

            opts.DisconnectedEventHandler += handleDisconnect;
            opts.ReconnectedEventHandler += handleReconnect;

            if (conType == eNatsConnType.Secure)
            {
               opts.Secure = ConstantNatsConnection.SecureConnection;

                X509Certificate2 cert = new X509Certificate2(ConstantNatsConnection.ClientCert, ConstantNatsConnection.ClientCertPwd);
                opts.AddCertificate(cert);
                opts.TLSRemoteCertificationValidationCallback = verifyServerCert;
            }

            return new ConnectionFactory().CreateConnection(opts); // I get exception on this line
        }

**Comment by zubairalimansoor** [comment]
I have solved it by modifying C# client. Parameter "tls_available" need to be handled in C# client. If C# client wants to establish tls connection and tls_available is also true, it should initiate tls based connection.

**Comment by m3nowak** [comment]
@derekcollison 
Is the feature request from original comment implemented? In my k8s deployment, I'd like to force every connection from outside to use TLS while allowing local ones to use plain connection. The only solution I could come up with is setting up a local, unexposed leaf node. Am I missing something?
