### ISSUE TITLE
Router connection closed: Duplicate Route 

### ISSUE THREAD

**Issue by Vedadiyan** [nats-io/nats-server#1551]
I am trying to create a cluster and I get this message in the console right after the third connection to the cluster. 

` Router connection closed: Duplicate Route `

This is how it happens. (Environment: CentOS, Docker)

`docker run --rm --name NATS-Seeder --network NATS  -p 6222:6222 nats --cluster nats://0.0.0.0:6222`

`docker run --rm --name NATS-01 --network NATS -p 6333:6222 nats  --cluster nats://0.0.0.0:6222 --routes nats://192.168.75.100:6222`

Until this point everything goes well, but right after the following joins the cluster. NATS-01 and NATS-Seeder show `Router connection closed: Duplicate Route` message.

`docker run --rm --name NATS-02 --network NATS -p 6444:6222 nats  --cluster nats://0.0.0.0:6222 --routes nats://192.168.75.100:6222`

The actual question is, should I just ignore that? because I can imagine why it happens, they are soliciting routes!

**Comment by wallyqs** [comment]
Yes this is an log message that can be ignored. NATS clustering has always behaved that way, we are just trying to be more clear on the reason why routes get disconnected in recent releases.

**Comment by Vedadiyan** [comment]
@wallyqs 👍 
Thank you, NATS vs. Kafka according to experience, NATS the winner!
