### ISSUE TITLE
Question: nats subscription count

### ISSUE THREAD

**Issue by pananton** [nats-io/nats-server#1557]
Can you please tell me how nats server cluster deals with huge amount of simple (not nats-streaming) subscriptions? I have a bunch of simple servers holding a small  amount (approx 1000) of connections with my online clients for a total of 130 000 clients right now (expect no more then 1 million in the future). Servers are connected to a two 3-node nats clusters in distinct data centers joined in a supercluster. Now I wish to create a separate subscription for each of online client to avoid additional routing inside my code. Can nats server lost performance because of big memory usage or face much slower internal message routing because of an increased number of subscriptions? How much memory consumes each subscription (will the memory usage grow significantly non-linear)? What's the top border of subscription count for nats server to operate fast as usual?

**Comment by pananton** [comment]
It's an IM application with well known functionality: IMs, profile management. contact lists etc. We have separate servers for holding direct connections with small part of users (about 300-500 users per server) for a total of 100 000 - 130 000 simultaneous online users. For each user I'd like to create a subscription like "user.*.<user_id>" to handle distinct types of events (like user.im.<user_id>, user.contact_added.<user_id> etc). So each online user adds 1 subscription to nats cluster. Of course, I can implement this in a different way (either subscribing without <user_id> part and then filtering events or creating a separate server that "knows" where each of online user is located and redirecting event to corresponding presence server). - but all of them are worse then directly subscribing to concrete user events (harder to  implement and require additional re-sends).

**Comment by derekcollison** [comment]
I would create an account for processing user messages and have the user's account (possibly one for all users) to import these such that the user_id and context are secure but transparent to the user. Meaning the user sends a message to `user.add_contact` and the backend service receives `user.<user_id>.add_contact`.

**Comment by pananton** [comment]
Probably I do not understand well your proposal... The problem is not in processing messages received from user app, it's about the delivering of various external events to him (also note, that <user_id> is a placeholder for actual numeric user id). For example when user's profile is updated on the website event is published to `user.on_profile_updated.123456789` where 123456789 is an actual identifier of user whos profile is changed. When user 123456789 client application signs in, subscription to subject `user.*.123456789` is created to act as a sink for *concrete* user events. So later when user changes profile on the website, event will be delivered to his client app (mobile or desktop).
I read nats account documentation again and can't find how accounts can help me in this case. If each user of my system has a nats account, then yes, I will be able to configure export/import for them. But that's not an option (number of registered users is huge). Even in this case I'd like to prohibit direct user connections to nats cluster for several reasons:
* security - we face DoS attacks from time to time and cracked clients with erroneous behaviour and I'm worried about such clients connected directly to main component of the system (nats cluster)
* sometimes we need to reconnect all current users which can be done gently in our design - users get disconnected by small portions at a fixed time intervals

Maybe I'm missing something about nats accounts and you can explain a little more how you suggest to use them?

**Comment by derekcollison** [comment]
I understand your concerns on direct connect, but NATS can handle that and does have a lame duck mode which will drain client connections over a period of time.

What I was suggesting for the accounts was one for the back end processing of user events that have the complete subject like `user.on_update.1234` and then all users are in their own account and only send updates to `user.on_update` which is a service import for the back end account.

**Comment by OS-venkataashok** [comment]
theme:- Allow teams to subscribe to NATS events

we have lot of users, they are open to subscribe our NATS events.

But I need to enable a NATS server for subscribing events with authentication for all users, but creating new credentials and creating keys for all users not possible.

but all users has to subscribe my events,

what will be the best way.

please explain in detailed way, because I am new to It as well as I didn't found more detailed documentation in web also.

**Comment by derekcollison** [comment]
Create a single user or nkey with the permissions you desire and share that with all users who want to subscribe to the events.

https://docs.nats.io/running-a-nats-service/configuration/securing_nats/authorization#examples

**Comment by OS-venkataashok** [comment]
do you have any sample code that, we can connect to the NATS server with the URL, username & password.

**Comment by derekcollison** [comment]
nats://ivan:s3cr3t!@localhost:4222

**Comment by derekcollison** [comment]
Have you checked the examples directory here? https://github.com/nats-io/nats.py

**Comment by OS-venkataashok** [comment]
yes, its not working, because i need to login with ca.crt also.

**Comment by OS-venkataashok** [comment]
windows

**Comment by OS-venkataashok** [comment]
i am trying to connect to my NATS cluster, with username, password, ca.crt file, url --using python in winodws machine

with comand line i can able to connect
but with python i a not connecting

**Comment by derekcollison** [comment]
I might suggest jumping on the NATS slack channels, @wallyqs might also be able to point you to a working example.
