### ISSUE TITLE
Question: upgrading nats server

### ISSUE THREAD

**Issue by pananton** [nats-io/nats-server#1558]
Can you please tell me is there any way to determine whether older nats server version can work with a new one? I have a 3 node cluster and now wish to upgrade nats servers to a newer version. I'd like to restart them one after another because do not want my system to go offline even for a short period of time (as specified here https://docs.nats.io/nats-server/nats_admin/upgrading_cluster). So at some moment my cluster will be comprised of servers with distinct versions. I expect that this can be a problem in general case. Will it? For example currently I have version 2.1.6 and wish to move to 2.2.0 when it will be released.

**Comment by ripienaar** [comment]
You should be find to do rolling upgrades within major versions.  In otherwords v 2.1.x to 2.2.x you can just do a rolling upgrade.  You cannot do a rolling upgrade from 1.x to 2.x as the route protocols have changed.

**Comment by pananton** [comment]
Thanks!
