### ISSUE TITLE
The problem of the lock in client struct in nats-server

### ISSUE THREAD

**Issue by wooviet** [nats-io/nats-server#1559]
I wrote two test programs using go client, one for request and one for subscription. The subscription program uses 5000 connections, and each connection subscribes to 50 topics. The publishing program uses 5000 connections, and each connection loops to publish messages to the corresponding 50 topics. I found a lot of timeout (2 seconds) messages in this case.
So I recompiled nats-server v2.1.7 and added some logs to observe the time-consuming operation. I found that there is only one sync.Mutex in the client struct. This lock is used in many places and the granularity of the lock is big. It takes a long time to acquire the lock in the deliverMsg function, it is about a few seconds when the timeout message starts to appear, and it seems to be getting longer and longer. so please tell me what is going on? Which member does this lock protect? Why is there only one lock?

**Comment by derekcollison** [comment]
Processing messages inbound for a client mostly does not require locks, only when sending outbound to a client. Also for actual I/O the locks are not held.

For the timeouts, what timeout are you referring to?

For the 50 subscribe topics, what do the topics look like? Is one published message go to all the subscriptions?

**Comment by wooviet** [comment]
func (nc *Conn) Request(subj string, data []byte, timeout time.Duration) (*Msg, error)，the timeout I said refers to the third parameter of this function.
The subject I used when testing is like this: subject1, subject2, ... ,subject250000. For example, there are 5000 connections, and each connection subscribes to 50 topics, with a total of 250,000 from subject1 to suject250,000. Another 5000 connections are used for publishing, and each publisher sends messages to 50 topics at the same time. Because the request function is used, every time a message is published, it will wait for a reply, and the timeout happens here.
I also found that the client type that is very slow to acquire locks is ROUTER. I used three machines to deploy a nats cluster.

**Comment by wallyqs** [comment]
Could it be possible that the data got delivered to the clients and was pending to be processed by the client? One way to check that could be with:
https://github.com/nats-io/nats.go/blob/master/nats.go#L3641

**Comment by wooviet** [comment]
I tested it again, the returned pMsgs and pBytes are 0. The client can process data.

**Comment by derekcollison** [comment]
Would you be willing to share your program and we can take a look?

How did you deploy the NATS cluster? What size network links are you working on?

**Comment by wooviet** [comment]
Test code and nats-server config files:
[https://github.com/wooviet/nats-tools](url)

This is my test command:
./mysub -s nats://192.168.13.101:4222,nats://192.168.13.103:4222,nats://192.168.13.106:4222 -t -n 5000 -ns 100
./mypub -s nats://192.168.13.101:4222,nats://192.168.13.103:4222,nats://192.168.13.106:4222 -np 5000 -ns 100 -nm 10000 -t 500 testmsg

I want to use nats as a communication system, one million users, each user subscribes to a topic, users can receive messages from any user in time and ensure that the messages are delivered reliably. A user generally only sends messages to a small number of users.

**Comment by derekcollison** [comment]
Thanks will take a look.

**Comment by wallyqs** [comment]
Hi @wooviet, thanks for sharing the code. I think you may have stumbled upon some interesting behavior from the Go client when there is a lot of contention when making the first `Request` from same client. As you may have found out there are two types of requests modes in the client, and the current default one creates a single subscription that processes all the requests, which is an improvement over the classic style when there was a single subscription for each one the requests.

The problem in the test is that for example when you run something like:

: go run mypub.go -s nats://18.189.29.253:4222 -np 100 -ns 100 -nm 10000 -t 500 testmsg

In the test you are creating 100 NATS clients with each having another 100 goroutines  sharing the same client to make requests (so 10_000 goroutines in total in that case). So when all the 100 goroutines race to make the first request from the same client, sometimes all those goroutines that attempted to make the first request will get blocked until the request deadline hits.  As a workaround, just for the purposes of this test you could make an initial request as in this commit so that you initialize the internal async request handler before the 100 goroutines start without the request handler being initialized: 
https://github.com/wallyqs/nats-tools/commit/1d3a211ca62c8850cc7ff3d2398de8eac2536e6c#diff-25482995d219fed37573d90c6990edf2R146

Or also, you could extend the deadline of the first  request: 

https://github.com/wallyqs/nats-tools/commit/1d3a211ca62c8850cc7ff3d2398de8eac2536e6c#diff-25482995d219fed37573d90c6990edf2R235

I think those couple of additions might improve the mileage of the bench, but let me know if you find something else.

**Comment by wooviet** [comment]
Thank you very much, I will retest.

**Comment by gowxw** [comment]
> Hi @wooviet, thanks for sharing the code. I think you may have stumbled upon some interesting behavior from the Go client when there is a lot of contention when making the first `Request` from the same client. As you may have found out there are two types of requests modes in the client, and the current default one creates a single subscription that processes all the requests, which is an improvement over the classic style when there was a single subscription for each one the requests.
> 
> The problem in the test is that for example when you run something like:
> 
> : go run mypub.go -s nats://18.189.29.253:4222 -np 100 -ns 100 -nm 10000 -t 500 testmsg
> 
> In the test you are creating 100 NATS clients with each having another 100 goroutines sharing the same client to make requests (so 10_000 goroutines in total in that case). When all the 100 goroutines race to make the first request from the same client, sometimes all those goroutines that attempted to make the first request will get blocked until the request deadline hits. As a workaround, just for the purposes of this test you could make an initial request as in this commit so that you initialize the internal async request handler before the 100 goroutines start without the request handler being initialized:
> [wallyqs/nats-tools@1d3a211#diff-25482995d219fed37573d90c6990edf2R146](https://github.com/wallyqs/nats-tools/commit/1d3a211ca62c8850cc7ff3d2398de8eac2536e6c#diff-25482995d219fed37573d90c6990edf2R146)
> 
> Or also, you could extend the deadline of the first request:
> 
> [wallyqs/nats-tools@1d3a211#diff-25482995d219fed37573d90c6990edf2R235](https://github.com/wallyqs/nats-tools/commit/1d3a211ca62c8850cc7ff3d2398de8eac2536e6c#diff-25482995d219fed37573d90c6990edf2R235)
> 
> I think those couple of additions might improve the mileage of the bench, but let me know if you find something else.

Interested in this test and the change 

After read the diff , noticed two changes:
1. warm up   [https://github.com/wallyqs/nats-tools/blob/1d3a211ca62c8850cc7ff3d2398de8eac2536e6c/mypub.go#L146](url)

2. sleep 1 Millisecond between each goroutine kicked off  [https://github.com/wallyqs/nats-tools/blob/1d3a211ca62c8850cc7ff3d2398de8eac2536e6c/mypub.go#L166](url)

I don't think warm up request can solve this issue , it  just save time for following requests bypass initNewResp  [https://github.com/nats-io/nats.go/blob/97eff70ce7475b3941ee1a929567eb2515bbe2a8/nats.go#L2961](url)

but, the sleep interval may take a big improvement, 1 Millisecond is enough for a goroutine to copy the msg to bufio , and avoid lock race between goroutines.

**Comment by wallyqs** [comment]
Thanks for taking a look @gowxw, you might be onto something though I actually noticed the test to fare better when spending more time in the setup for the first request followed by making the burst of request as in the test.  Made some updates to the test to add flush previous to sending the N requests and timeout errors were gone:

https://github.com/wallyqs/nats-tools/commit/a56761b1e29b6d35858d1b2f0e0bbc410d898d21#diff-25482995d219fed37573d90c6990edf2R152-R168

with:

```
mypub.go -s nats://18.189.29.253:4222 -np 100 -ns 100 -nm 10000 -t 500 testmsg
mysub.go -s nats://3.21.230.203:4222 -t -n 100 -ns 101 # <- btw possible off by one error here?
```

**Comment by derekcollison** [comment]
Closing as this is not server.
