### ISSUE TITLE
can nats support websocket now?

### ISSUE THREAD

**Issue by beanhacker** [nats-io/nats-server#1560]
hi,
   i saw that ws feature has committed, but no release  has published right now, can nats support websocket now?

**Comment by derekcollison** [comment]
Yes by using a nightly docker image or building yourself. If you don't have Go installed you can get a binary build of what is at the head of main via the following.

`curl -Lsf 'http://gobinaries.com/nats-io/nats-server' | sh`

**Comment by derekcollison** [comment]
Then @aricart can point you to docs to get started.

**Comment by aricart** [comment]
@beanhacker our javascript client for WebSocket is here https://github.com/nats-io/nats.ws.
A built version of the library is available via `npm` - there is actually detailed steps on how to get started if you clone the repo - https://github.com/nats-io/nats.ws#installation.

**Comment by beanhacker** [comment]
@derekcollison do you have windows version of nats? or windows will not be supported after this version?

**Comment by derekcollison** [comment]
Windows has always been supported. However prior to an official release you may have to build yourself. Our nightly builds are docker images.

**Comment by beanhacker** [comment]
I have run it up in ws mode, thank you all!
