### ISSUE TITLE
Allow TCP/IP keepalives to be configured or disabled

### ISSUE THREAD

**Issue by cbrake** [nats-io/nats-server#1561]
#### Use Case:

Recent Go versions set the TCP/IP keep alive to 15s:

https://www.reddit.com/r/golang/comments/d7v7dn/psa_go_113_introduces_15_sec_server_tcp/

With client and server running on a single machine, I observed both the client and server sending TCP/IP keep alive packets every 15s

Slack Discussions:

https://natsio.slack.com/archives/C069GSYFP/p1597409473119300
https://natsio.slack.com/archives/C069GSYFP/p1595884776470400

![image](https://user-images.githubusercontent.com/402813/90259296-c5101100-de17-11ea-8f08-9ef831bab517.png)

#### Proposed Change:

Add a configuration option to set the TCP/IP keepalive on new connections to something other than 15s. It seems with NATS PING/PONG, TCP keepalive is redundant.

The Go client already has a configuration option:

```go
	nats.SetCustomDialer(&net.Dialer{
			KeepAlive: -1,
	}),
```
I am currently testing with the following hack:

https://github.com/cbrake/nats-server/commit/dad8b74f14c7c89062891f729ce750c6ae4e8a4f

If there is a possibility that a PR that implements a proper configuration option being merged, I would be glad to work on PR, otherwise, I will maintain a fork for my projects.

#### Who Benefits From The Change(s)?

This change would be useful for IoT system that connect over cellular modems. In this case, the TCP keepalive would add up to a significant amount of bandwidth. 

352 bytes * 4/min * 60min/hr * 24hr/day * 30day/mon = 60825600 bytes/mo = ~60MB/mo just for TCP keep alive.

Monthly budget for these systems is typically 10-100MB/month.

Initial testing on a cellular network shows that 2m Nats ping/pong is adequate to keep connection alive.

One person on the reddit thread above suggested 5m timeouts (300s).

Other references to keep alive:

https://en.wikipedia.org/wiki/Keepalive

For reference, NATS ping/pong is around 284 bytes, so:

every 2m: ~6MB/mo
every 5m: ~2.4MB/mo
every 15m: ~800K/mo

**Comment by derekcollison** [comment]
Default behavior should be that the keepalives are off. You can use a custom dialer to turn on if you want, although there are two value for keepalive and they should not be the same as Golang does.

**Comment by philpennock** [comment]
That's what this PR does.  Except it's incomplete, I misread the Go source earlier and for some reason was left with the impression that only the listener side needed this fix.  The client side needs it too.  Will update the PR shortly.

**Comment by cbrake** [comment]
test nats-server with #1562 in my use case -- looks good here. Thanks for fix!
