### ISSUE TITLE
Slack no longer available?

### ISSUE THREAD

**Issue by andrewbanchich** [nats-io/nats-server#1563]
When I try to join the Slack server via [this link](https://github.com/nats-io/nats-server#contact) or via the link in the GitHub issue item, it says:

```
This deployment is no longer available.

ZEIT Now 1.0 has been shut down. As part of this, all ZEIT Now 1.0 Deployments are now inaccessible.

If you are the owner of this ZEIT Now 1.0 Project, click here to learn more →
```

**Comment by cbrake** [comment]
try: https://natsio.slack.com/

**Comment by gcolliso** [comment]
This is for the NATS automated invite for Slack. I am working on the issue - thanks for the report @andrewbanchich. If you need an invite to the NATS Slack please let us know.

**Comment by andrewbanchich** [comment]
Thanks! Yes I would like an invite please.

**Comment by gcolliso** [comment]
here you go @andrewbanchich https://join.slack.com/t/natsio/shared_invite/zt-41e6tnmb-qCt63606MKR1YxIHZf4ICA

**Comment by gcolliso** [comment]
Updated the URL to resolve to standard Slack self-invite. Closing this issue for now but if a problem arises please reopen.

**Comment by manifest** [comment]
Hey @gcolliso,
I've got into the same problem.

> This link is no longer active
> To join this workspace, you’ll need to ask the person who originally invited you for a new link.

How can I join the Slack?
Thanks.

**Comment by gcolliso** [comment]
@manifest I have updated the Slack invite URL. Please advise should you have any issues.
Thank you for the notification.

**Comment by manifest** [comment]
I've joined the Slack.
Thank you.
