### ISSUE TITLE
JetStream: durable restart resends last stored message

### ISSUE THREAD

**Issue by kozlovic** [nats-io/nats-server#1580]
#### Versions of `nats-server` and affected client libraries used:
- From main, rev: d7946169454a724c7aab47d4aa301a5983811ad2

#### OS/Container environment:
- All

#### Steps or code to reproduce the issue:
- Create a stream:
```
&StreamConfig{
   Name:      streamName,
   Storage:   FileStorage, // same if it was mem storage
   Subjects:  []string{"foo"},
   Retention: InterestPolicy,
}
```
- Add a durable consumer with this config:
```
&ConsumerConfig{
   DeliverSubject: inbox,
   DeliverPolicy:  DeliverNew,
   AckPolicy:      AckNone,
}
```
- While the consumer is running send 2 messages M1 and M2, they are received. 
- Stop the consumer, which means delete the subscription on the given inbox (but do not delete the durable JS consumer).
- Send 2 more messages M3 and M4
- Restart the durable with a new inbox attached
- It will receive M2, M3 and M4.
- You can now stop and restart it, it will keep receiving M4.

#### Expected result:
- Receive only M3 and M4 after the first restart, nothing after the second.

#### Actual result:
- The last stored message is always redelivered.

**Comment by wallyqs** [comment]
Fixed via #1581
