### ISSUE TITLE
Support DNS discovery of DNS names on routes

### ISSUE THREAD

**Issue by israellot** [nats-io/nats-server#1586]
## Feature Request
Support resolving DNS names for routes and using resolved ips, excluding self ip.

#### Use Case:
Boostraping a NATS cluster using Consul 

#### Proposed Change:
Resolve DNS names instead of directly calling net.DialTCP() for routes

#### Who Benefits From The Change(s)?
Environments that use DNS as service discovery, including Consul clusters.

**Comment by kozlovic** [comment]
@israellot If you know how to build from the main branch and would like to have a go to see if that meet your requirements, the PR has been merged.

**Comment by israellot** [comment]
Great @kozlovic , I'm impressed with the fast response on this issue. 
Thank you very much, I'll give it a try.

**Comment by kozlovic** [comment]
@israellot Any update? Would appreciate feedback and see if that resolved your issue (and not creating new ones ;-) )

**Comment by israellot** [comment]
@kozlovic I can confirm now that the solution indeed meet my requirements. Deploying a NATS cluster using Consul for node discovery became straightforward. 

The only minor issue is that Consul listens for DNS queries on port 8600 by default, and it's standard practice to keep it that way since binding to port 53 would require root privileges. 
If there was a way to configure NATS to use a specific ip:port address for dns queries, it would eliminate the need of running dnsmasq or bind9 just to capture dns queries on port 53 and forwarding them to Consul.
Of course, that is not a blocker by any means.

There's an old issue for that already (https://github.com/nats-io/nats-server/issues/1418)

**Comment by kozlovic** [comment]
But I don't see how we can do that? Meaning that we use Go buit-in to do name resolution, and I see nowhere where I could specify the servers' port. Go would for instance read resolv.conf on Linux and add `:53` to each server present. I can't seem to override that.
If you were to run NATS Server from your own code, then I could have made the route's `resolver` public and the `netResolver` a public interface, but then it would be the user responsibility to implement the `LookupHost(ctx context.Context, host string) ([]string, error)` function.
There may be libraries that implement DNS lookups, and that allows to provide the servers with different ports, but I am not sure we would have plans to have a dependency on such library, or alternatively have to implement DNS lookups ourselves.

**Comment by kozlovic** [comment]
But if you run the executable, as of now, I don't see how your request for a "custom DNS" would work.

**Comment by israellot** [comment]
You are right, It would require an internal dns lookup integration. 
As I've said, it's just a minor issue, and the current solution is more than capable. 
Thank you

**Comment by lionello** [comment]
FYI, Go now allows you to specify your own Dialer to override the network connection. See https://pkg.go.dev/net#Resolver
