### ISSUE TITLE
Add a tag map to the server configuration

### ISSUE THREAD

**Issue by davidkemper** [nats-io/nats-server#1588]
## Feature Request

Add support for an arbitrary key/value map for configuration properties per server.

#### Use Case:

From an ops perspective it is useful to be able to associate meta-tags to an instance that would be queryable through the various mechanisms supported by the server.

The server name (which defaults to the server id) is a singular instance of why you'd want to tag an instance with more human-friendly metadata. But there are many other examples.

- Tag the server with the latitude and longitude of its data center.
- Tag the server with its cloud, region, and availability zone.
- Tag the server with its environment (e.g., test or production).

Note that we wouldn't expect this tagging to be unmanageably large, nor to change often. Perhaps limits as to number of tags and key/value sizing would be reasonable.

#### Proposed Change:

Add a string to string key/value dictionary to the nats server configuration. Read it on startup, and perhaps re-read it during reload signal processing. Emit its values in, say, `varz`, and/or make it queryable through server messages.

#### Who Benefits From The Change(s)?

Anyone who needs more domain-specific tagging in a large cloud of nats servers.

#### Alternative Approaches

The configured server name could be used as a key or key fragment to some external key/value store. But that adds extra moving parts where none might be needed.

**Comment by matthiashanel** [comment]
@davidkemper I assume you'd want to be able to see those tags in say /routez or /leafz as well. 
Meaning the'd be communicated to other servers so that these tags can be shown.

We export monitoring endpoints as subjects and added the ability to filter responders. 
I'd assume it'd be useful being able to filter based on tags as well. @ripienaar would you agree?
