### ISSUE TITLE
Can we use image synadia/nats-server:nightly to start using WebSockets ?

### ISSUE THREAD

**Issue by dmitrydiavita** [nats-io/nats-server#1610]
Hi, due to comment https://github.com/nats-io/nats-server/pull/1309#issuecomment-696979217
Can we use image `synadia/nats-server:nightly` to start using WebSockets or we need to make build of nats-server ourselfs from master ?
We are asking because of build description https://hub.docker.com/r/synadia/nats-server
> If you're looking for public builds of the NATS.io nats-server fit for general consumption, then you're in the wrong place.

**Comment by kozlovic** [comment]
If you want an "official" release, then you will need to wait for the release to be officially released (available in the github release page or `https://hub.docker.com/_/nats`. If you want to start using Websocket but are ok using a nightly build from the main branch, then you can use the `synadia/nats-server:nightly` docker image or build yourself from source.

**Comment by mgyong** [comment]
@kozlovic Is there an example of how we can use the websocket feature directly from the browser? I found this old in browser nats websocket based client but it is very old https://github.com/isobit/websocket-nats

**Comment by nuharaf** [comment]
@mgyong [nats.ws examples](https://github.com/nats-io/nats.ws/tree/master/examples)
