### ISSUE TITLE
Protocol demo with socat

### ISSUE THREAD

**Issue by minayko** [nats-io/nats-server#1615]
**Context**

I just tried to follow the [protocol demo](https://docs.nats.io/nats-protocol/nats-protocol-demo) with socat instead of telnet.

`socat TCP:demo.nats.io:4222 -`

```
pub foo.bar 5
hello
```

**Result**

`Client parser ERROR, state=30, i=5: proto='""...'`

**Question**

Do you know what might explain this difference between telnet and socat?

Thanking you,
Sorry if this question is not asked in the right place.

**Comment by wallyqs** [comment]
This is fails because socat for some reason does not include the `\r` in the message (`MSG_END_R` state in the parser), so it gets disconnected because of malformed protocol (happens as well with websocat).

**Comment by kozlovic** [comment]
You can add this as an option:
```
socat TCP:demo.nats.io:4222,crnl -
```
this will insert CRLF instead of LF alone.

**Comment by minayko** [comment]
I understand, thank you very much!
