### ISSUE TITLE
expose slow consumer counts as well as other close reasons in monitoring & system events

### ISSUE THREAD

**Issue by matthiashanel** [nats-io/nats-server#1618]
## Feature Request
Why where clients disconnected is a good indicator to what might be wrong.
The only way to obtain this so far is looking at closed connections.
We should provide an easier way to obtain this information for either dedicated close reasons (such as slow consumer) or all of them. 

#### Use Case:
Quicker debugging and per account stats.

#### Proposed Change:
keep counts of close reasons per account. 
keep count of all close reasons per server.

#### Who Benefits From The Change(s)?
Ppl trying to find out why their applications get disconnected.

**Comment by derekcollison** [comment]
Accessible from connz via system account.
