### ISSUE TITLE
JetStream: AckExplicit message removed while durable consumer "offline"

### ISSUE THREAD

**Issue by kozlovic** [nats-io/nats-server#1627]
Have 2 durable consumers on the same stream.
Both consumers filter on the same subject and use explicit ack.
Send 2 messages, each consumer receive and ack.
Stop the subscription on the 2nd durable.
Send 2 more messages.
First subscription receives and acks.
"Restart" 2nd subscription (update the 2nd durable with new delivery subject)
No message is received, the stream info shows that there are no message in the stream (message 3 and 4 have been removed).

**Comment by derekcollison** [comment]
Let me know if you are doing any work here like writing a test, if not will take a look in a few.

**Comment by kozlovic** [comment]
I am writing a test (I did sent you a note on Slack)

**Comment by kozlovic** [comment]
Created the PR just with the test. See comment in the PR about other issues related to the removal of messages from the stream.

**Comment by kozlovic** [comment]
Closed by #1628
