### ISSUE TITLE
--no_advertise flag documented twice with different descriptions

### ISSUE THREAD

**Issue by Soha-Albaghdady** [nats-io/nats-server#1647]
Hi, 

We have notice that the `--no_advertise` flag is documented twice once in [1] described as "Do not advertise known cluster information to clients" and once in [2] described as "When set to true, do not advertise this server to clients" . We have checked in code and were only able to find the [flag](https://github.com/nats-io/nats-server/blob/e846dab45dad399eefb0ac46b05be7c92c56e568/main.go#L70) as a cluster option which matches the former description in the documentation.

We are raising the question because the option has been recently added to the nats-release with this [PR](https://github.com/cloudfoundry/nats-release/commit/8cd7d93a8fc29d8226a31a5aecd87e8701da3c0e). The flag is introduced with the description "When configured to true, this nats server will not be advertised to any nats clients." and we are not sure how to consume it.

Could you please clarify what is exactly the expected behaviour if the flag is set to true? which of these descriptions is valid? 

[1] https://docs.nats.io/nats-server/flags#cluster-options
[2] https://docs.nats.io/nats-server/configuration/clustering/cluster_config

**Comment by kozlovic** [comment]
The flag and configuration file option do the same: if the no_advertise is set to false, the server will not communicate its client URL (host:port where clients can connect) to the rest of the cluster. Therefore, this URL will not be gossiped to clients, which therefore cannot help clients automatically reconnect to this discovered server.

**Comment by domdom82** [comment]
it's funny. the doc says the exact opposite:
> When set to true, do not advertise this server to clients.

**Comment by domdom82** [comment]
I guess @Soha-Albaghdady 's point is: does it not advertise *only itself* to the cluster or does it not advertise *anything* (including other cluster members)?

**Comment by kozlovic** [comment]
Sorry, yes, `no_advertise` set to true disables the advertisement to clients.

**Comment by stefanlay** [comment]
In this case the sentence "Do not advertise known cluster information to clients" is in my opinion misleading. I would understand in the following way: The server does not send any cluster information at all to its clients, also not the information about other servers in the cluster. Additionally, it does not state if other servers send information about the server to their clients.

**Comment by kozlovic** [comment]
Ok, so the configuration parameter is per server. In a cluster, it is expected that all members of the cluster have the same value, but it is not enforced nor mandatory.

A server that has `no_advertise` set to `true` means that it is not going to advertise its client URL to the other members of the cluster. If all members have the same setting, it means that a client that connects to 1 server does NOT get sent the list of other URLs that it could reconnect to in the cluster. An application needs therefore to provide the list of all servers that it wants the library to be able to connect or reconnect to.

**Comment by Soha-Albaghdady** [comment]
Hi @kozlovic, thanks alot for your reply. Now it's clear what the option mean and it fits the first description in the ticket. We would suggest to remove/adapt the second description for consistency and to avoid the confusion.
