### ISSUE TITLE
Publish with headers and subscribe with no headers

### ISSUE THREAD

**Issue by dawid-nowak** [nats-io/nats-server#1650]
I have been using Rust 0.8.0 client to publish messages to a topic, and the latest Java client from Maven to subscribe to the same topic. It took me a while to figure out that Java client doesn't support headers just yet. 

The question I have is what is going to be a default behaviour going forward where SDKs have different capabilities. If publishes sends a payload with headers:
should the subscriber get the payload without headers 
or perhaps that subscriber shouldn't be allowed to connect at all 
or perhaps the subscriber will only get the messages which were published without headers

Best regards

**Comment by derekcollison** [comment]
The plan is to have all major clients supporting headers prior to next server release which will be 2.2.

Right now the system understands if a client can not process headers and those are stripped and sent to the older clients.

**Comment by derekcollison** [comment]
We will get java updated. 

/cc @RichardHightower
