### ISSUE TITLE
username/password not checked

### ISSUE THREAD

**Issue by carr123** [nats-io/nats-server#1691]
cluster {
listen: 10.91.26.227:4244
authorization: {// i want nats clients to connect with this user/password
    user: mquser,
    password: fe8945md
}
routes = [
    nats-route://mquser:fe8945md@10.91.26.225:4244
    nats-route://mquser:fe8945md@10.91.26.226:4244
  ]
}

I start a nats-server cluster, and expect clients to login with password.

        servers := []string{"nats://10.91.26.225:4222", "nats://10.91.26.226:4222", "nats://10.91.26.227:4222"}
	mqPub, err = nats.Connect(
		strings.Join(servers, ","),
		nats.UserInfo("myname", "password"), //this passwd is wrong
	)

when i set wrong passwd in go-client ,it still can talk to the nats-server, and can pub/sub messages.

where am i wrong ?  thanks.

**Comment by matthiashanel** [comment]
We do have multiple authorization blocks for different purposes.
The one you have here is part of the cluster section and is for routes.
For the client one you want the authorization block outside the cluster section.

**Comment by carr123** [comment]
thanks
