### ISSUE TITLE
JetStream - stream info reports `state.first_seq` as the next sequence to be assigned rather than the first available

### ISSUE THREAD

**Issue by aricart** [nats-io/nats-server#1700]
## Defect

There was a change recently to JetStream where stream status is not showing the correct value for `first_seq` on
nats-server: v2.2.0-beta.30 (build from master)
```
  await jsm.streams.create("ORDERS", {
    storage: StorageType.File,
    subjects: ["orders.>"],
    retention: RetentionPolicy.WorkQueue,
  });

  await nc.request("orders.new", jc.encode(1));
  await nc.request("orders.new", jc.encode(2));
  await nc.request("orders.new", jc.encode(3));
  await nc.request("orders.new", jc.encode(4));
  await nc.request("orders.new", jc.encode(5));

  let info = await jsm.streams.info("ORDERS");
  assertEquals(info.state.first_seq, 1); <==== ZONK this is reporting as 6
  assertEquals(info.state.last_seq, 5);
```

**Comment by derekcollison** [comment]
@ripienaar Can you take a quick look for me?

**Comment by ripienaar** [comment]
This seems fine to me, here's a work queue with 5 messages, info is right:

```json
{
  "config": {
    "name": "TEST",
    "subjects": [
      "js.in.test.\u003e"
    ],
    "retention": "workqueue",
    "max_consumers": -1,
    "max_msgs": -1,
    "max_bytes": -1,
    "max_age": 0,
    "max_msg_size": -1,
    "storage": "file",
    "discard": "old",
    "num_replicas": 1,
    "duplicate_window": 120000000000
  },
  "state": {
    "messages": 5,
    "bytes": 215,
    "first_seq": 1,
    "first_ts": "2020-11-11T09:29:08.889685076Z",
    "last_seq": 5,
    "last_ts": "2020-11-11T09:29:12.211457079Z",
    "consumer_count": 0
  }
}
```

Current master

**Comment by tchopper** [comment]
I found this behaviour too whilst implementing an exporter on jsz to prometheus. 

`          
"state": {
            "messages": 0,
            "bytes": 0,
            "first_seq": 184,
            "first_ts": "1970-01-01T00:00:00Z",
            "last_seq": 183,
            "last_ts": "2021-05-20T04:13:44.7143978Z",
            "consumer_count": 1
          }
`

Taken directly from jsz endpoint. On v2.2.4.

**Comment by derekcollison** [comment]
When you purge a stream the first_seq is the next first sequence to be assigned.
