### ISSUE TITLE
Facing issue while using `nats-account-server` and Multi tenancy using accounts

### ISSUE THREAD

**Issue by masudur-rahman** [nats-io/nats-server#1701]
I have been using `nats-account-server` and Multi Tenancy using accounts.

I have an `admin` account and a user for `admin` account.

Now, create a new `account` named `A` & a `user`.
	- Add `Export` stream to this account [subject "Example"]
	- `Import` this stream from `admin` account [as "A.Example"]
	- Then store both account to `nats-account-server` using `Go` code.

If I now subscribe to "A.Example" channel from `admin` account and publish message to "Example" channel from user account, `A`, it works perfectly (`admin` subscription receives the message)

But the problem is, if I now create another `account` named `B` and create `Export` ["Example"], `Import` ["B.Example"] just like previously done, it doesn't work (`admin` account doesn't receive the the message sent by the `B`).
`NATS-Server` doesn't retrieve `admin` account from `nats-account-server` (for AUTH) this time, it uses previously fetched account.

Another thing, if I create more than one account at a time and add stream `Export`, `Import` just like previously done and then try to `pub/sub`, it still doesn't work.
This time it shows `Authentication Error` for the admin account.

### Here are my server configuration files:

**nats-account-server.conf**
```
operatorjwtpath: "KO.jwt"

http {
    port: 9090
}

store {
    dir: "/tmp/as_store",
    readonly: false,
    shard: true
}
```

```sh
$ nats-account-server -c nats-account-server.conf`
```

**nats-server.conf**
```
host: 0.0.0.0
port: 4222
operator: "KO.jwt"
resolver: URL(http://localhost:9090/jwt/v1/accounts/)
system_account: ABW44DI4WWQGEXMD3PVXWRFZMIOPHCEZBI32OBBOBRF6ESM2UZ5MHV27
websocket: {
  host: 0.0.0.0
  port: 9222
  no_tls: true
}
```

```sh
$ nats-server -c nats-server.conf
```

**How should I overcome this situation?**

**Comment by derekcollison** [comment]
Closing for now, feel free to re-open if needed.
