### ISSUE TITLE
 Support user-defined encryption and decryption methods for Username/Password authorization

### ISSUE THREAD

**Issue by peaka9** [nats-io/nats-server#1708]
Hello,
       As we know, Nats uses bcrypted passwords for Username/Password authorization. Would it be possible to use Go plugins to allow users define their own encryption and decryption for Username/Password authorization?

**Comment by derekcollison** [comment]
Modern NATS (2.x) prefer Nkeys which prevents the system from ever having any keys or passwords. We also support pulling user identity from a client certificate, and finally if they do not fit your needs you can be a custom authentication module.

https://github.com/nats-io/nats-server/blob/master/server/auth.go#L40
