### ISSUE TITLE
Authorization question

### ISSUE THREAD

**Issue by SkinnySackboy** [nats-io/nats-server#1713]
We've got a scenario where several hundreds of clients connect to a NATS (NATS Streaming to be precise) server, currently without security. The vast majority of these connections are read-only and never need to publish.

Now that we are adding security using usernames/passwords, is it possible to specify a single shared account for read-only clients to be used by hundreds of clients? Would `no_auth_user` be the way to go?

Thanks in advance.

**Comment by kozlovic** [comment]
@SkinnySackboy Yes, `no_auth_user` could work for that. Here is a very simple configuration (probably not complete) of what this could look like:
```
authorization {
   users [
     {user: stan, pass: stan, permissions: {publish: ">", subscribe: ">"}}
     {user: u1, pass: p1, permissions: {publish: ["_STAN.discover.>", "_STAN.acks.>", "_STAN.pub.*.foo", "_STAN.close.*"], subscribe: ">"}}
     {user: np, pass: p2, permissions: {publish: {deny: "_STAN.pub.>"}, subscribe: ">"}}
   ]
}

no_auth_user: "np"
```
The first user would be for the streaming server (`nats-streaming-server -c c.conf -user stan -pass stan`). It is allowed to publish and subscribe on everything.

The user `u1` would be allowed to connect and publish only on channel "foo". For instance:
```
go run examples/stan-pub/main.go -s nats://u1:p1@localhost:4222 foo msg1
```
Trying to publish on `bar` would fail.

The third user `np` has permissions to subscribe on everything and publish on everything except on "streaming" channels. Note the `*` can either be a NUID or the cluster id based on how the server is running. This is why I put `*` here.

If your existing app only consumer, they don't have to provide a user. The `no_auth_user` would cause the server to use `np` and so given them the right to subscribe on everything but not all them to publish on streaming channels.

I have tried this with the latest NATS Streaming v0.19.0 and it works as described above.
Note that there may be a need to allow/deny more subjects, I may have missed some cases.

**Comment by SkinnySackboy** [comment]
Many thanks for the highly detailed reply, much appreciated @kozlovic
