### ISSUE TITLE
router parser error in leaf node configuration

### ISSUE THREAD

**Issue by wuddl6** [nats-io/nats-server#1743]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [v ] Included `nats-server -DV` output
 - [ ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:
2.2.0-beta.33 (master branch a3af4915)

#### OS/Container environment:
windows 10
nats-rply/nats-req

#### Steps or code to reproduce the issue:

There are two clusters, a srv cluster and a leaf cluster.
Each cluster has 2 nodes. (srv-1,2/leaf-1,2)
The two clusters are connected by leaf connections.

The configures are as follows:

srv-1
```
port: 4222
http: 8222
cluster {
    name: "ncs"
    port: 6222
    routes: [
        nats://localhost:6222
        nats://localhost:6223
    ]
}
leafnodes {
    port: 7422
}
```

srv-2
```
port: 4223
http: 8223
cluster {
    name: "ncs"
    port: 6223
    routes: [
        nats://localhost:6222
        nats://localhost:6223
    ]
}
leafnodes {
    port: 7423
}
```

leaf-1
```
port: 4212
http: 8212
leafnodes {
    remotes = [ 
        { 
          urls: [
                "nats-leaf://localhost:7422",
                "nats-leaf://localhost:7423"
            ]
        }
    ]
}
cluster {
    port: 6212
    name: "ncs"
    routes: [
        nats://localhost:6212
        nats://localhost:6213
    ]
}
```

leaf-2
```
port: 4213
http: 8213
leafnodes {
    remotes = [ 
        { 
          urls: [
                "nats-leaf://localhost:7422",
                "nats-leaf://localhost:7423"
            ]
        }
    ]
}
cluster {
    port: 6213
    name: "ncs"
    routes: [
        nats://localhost:6212
        nats://localhost:6213
    ]
}
```

1) nats-rply subscribe 'foo' on srv-2
2) nats-req publish messages longer than 100 bytes continuously on leaf-2

#### Expected result:

nats-req receives all responses.

#### Actual result:

nats-req doesn't  receive some response, and router parser error logged at nats-server

![error](https://user-images.githubusercontent.com/74340852/100057843-8dc7ec00-2e6b-11eb-9d02-b9c2234619ef.PNG)

error log on srv-1
```
[21800] 2020/11/24 14:19:32.405357 [[31mERR[0m] [::1]:6223 - rid:8 - Route Error 'Unknown Protocol Operation'
[21800] 2020/11/24 14:19:32.405357 [[32mINF[0m] [::1]:6223 - rid:8 - Router connection closed: Parse Error
```

 error log on srv-2
```
[18616] 2020/11/24 14:19:32.405357 [[31mERR[0m] [::1]:30043 - rid:7 - Router parser ERROR, state=40, i=157: proto='""...'
[18616] 2020/11/24 14:19:32.405357 [[32mINF[0m] [::1]:30043 - rid:7 - Router connection closed: Protocol Violation
```

Full logs are attatched.
[route-error-log.zip](https://github.com/nats-io/nats-server/files/5587877/route-error-log.zip)

**Comment by kozlovic** [comment]
@wuddl6 I wrote a test suite test based on your description and can indeed reproduce. I am looking at this. Thanks for the report.
