### ISSUE TITLE
Wildcard for zero-or-many (zero-or-one)

### ISSUE THREAD

**Issue by pananton** [nats-io/nats-server#1757]
## Feature Request
Nats provides 2 wildcrads:
* "*" for any topic (exactly one)
* ">" for any topics (one or many)

It would be nice if nats also supported wilcard that matches zero or many topics (and probably additional one that matches zero or one topic for completness)

#### Use Case:

We use nats for rpc in our project because it is fast, easily configurable and directly provides loose coupling. We try to make subject extensions backward-compatible. For example, we have subjects "topic1.subtopic1", "topic1.subtopic2", ... , "topic1.subtopicN" and a service that handles messages from "topic1.subtopic1". We also expect that later we would like to add more topics to the tail of "topic1.subtopic1" which will provide more information for routing.

For example, we have subject "user.profile_updated" to which user profile updates are published and handled by user profile service. Some time later we decide to specifically handle situation when user's email has changed - for example, send ownership verification email. For that case we can publish to "user.profile_updated.email_updated" when email was actually changed and implement a new email verification service that will subscribe to this generalized subject to send verification email. Note, that actions that should be performed by the user profile service (for example, store new profile to db) still should be taken, i.e. user profile service still should receive messages published to "user.profile_updated.email_updated" (in that case we think of topics comprising subject as a C++ polymorphic methods). But there is no simple way to implement this: subscribing to "user.profile_updated.>" can't be used (messages published to "user.profile_updated" will not be received).

Our current solution:
* services always subscribe to subjects with trailing ">" ("user.profile_updated.>")
* publishers always should add fake "eof" topic at the end ("user.profile_updated.eof", "user.profile_updated.email_updated.eof")

As you see, this is not ideal solution that requires all publishers to follow rule specified above.

#### Proposed Change:

Add at least one new wildcard that matches zero or many topics (for example, "$" ("*" will be better because it has the same meaning in regexp, but it is already taken, "+" can be confusing because it means 1 or many in regexp))

#### Who Benefits From The Change(s)?

If this feature will be implemented then above case will be trivial: just subscribe to "user.profile_updated.$"

#### Alternative Approaches

None

**Comment by derekcollison** [comment]
Subscriptions should be viewed as fairly cheap. So given a callback function foo, I would create two subscriptions and point them to the same callback. One for `user.profile_updated` and one for `user.profile_updated.*`. You can quickly look at the inbound subject to branch appropriately.

**Comment by pananton** [comment]
Note, that email_changed also can be not the last topic later. So in you example, second susbcription should be to user.profile_updated.> . Anyway, yes, this will work. But:
* doubles subscription number because it's our general approach and we do not know which parts of the system will require modifications in the future; even if subscription is cheap doubling them when there are for example then 100 000 of them can be undesirable
* It requires additional logic (very simple though) in subscriber's code
* It is also more error-prone (do not forget to create wildcarded subscription etc)

**Comment by derekcollison** [comment]
I would not worry about 100k subscriptions. And if you know you can have 1 or 2 trailing tokens might even suggest you do 3 subscriptions.

We can take a look but the subject routing system is well baked and any change there would need to very carefully scrutinized from not only a design standpoint but also the code change of course.

**Comment by pananton** [comment]
Thanks!

**Comment by kozlovic** [comment]
Just for info, this is what MQTT does with the `#` wildcard. That is, a subscription on `foo/#` would receive messages on `foo/bar`, `foo/bar/baz`, but also on `foo`.
For MQTT support in NATS Server, I did not have the equivalent, so I resort to do just that, subscribe on `foo.>` and `foo`.

**Comment by pananton** [comment]
Hello @kozlovic . Thanks for answer too. But this solution still looks a little bit "non-natural" (can't explain better). My own solution (with trailing eof) I do not like either. But I understand that this can be a lot of work while the feature is probably not interesting for the most of the community.

**Comment by kozlovic** [comment]
Clearly, I would have made use of that for the MQTT integration (in NATS Server itself), but as Derek explained, this is quite a change in the sublist and support across a super cluster. Not a simple task.
