### ISSUE TITLE
can nats publish ignore one or more subscribes? thanks!

### ISSUE THREAD

**Issue by beanhacker** [nats-io/nats-server#1762]
hi,
   i meet this case: after client publish msg to server, server will save message to db,  then the server should publish the structed msg to all the subscribes except the sender. now the client can allways recv message sended from it, this may waste much traffic
on the fly. so what should i do with this?

**Comment by wallyqs** [comment]
Check the no echo functionality from the clients: https://pkg.go.dev/github.com/nats-io/nats.go#NoEcho

**Comment by beanhacker** [comment]
what i mean is when publish，can send to one topic except some clients？

**Comment by nuharaf** [comment]
I dont think there is that option, what can be done is to design the subject such that it only subscribed by the client you want.

**Comment by kozlovic** [comment]
Or setup permissions so that the clients you don't want to receive messages on a given subject don't have permissions to do so: https://docs.nats.io/nats-server/configuration/securing_nats/authorization
