### ISSUE TITLE
Account setting issue in leaf node configuration

### ISSUE THREAD

**Issue by wuddl6** [nats-io/nats-server#1766]
Hello, Thanks for the quick response always.
Please answer the following two issues.

## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included `nats-server -DV` output
 - [ ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:
2.2.0-beta.33 (master branch 5168e3b1) / 2.1.7-release

#### OS/Container environment:
windows 10

#### Steps or code to reproduce the issue:

There are two nats server, ncs and foo. two servers are connected by leaf node.
**config - ncs**
```
port: 4222
http: 8222
leafnodes {
    port: 7422
}
```
**config - foo**
```
port: 4202
http: 8202
leafnodes {
    port: 7402
    remotes = [ 
        { 
            urls: [
                "nats-leaf://localhost:7422",
            ]
            account: NCS
        }
    ]
}
Accounts: {
    FOO: {
        users: [
            {user: foo, password: foo}
        ]
        exports: [
            {stream: >}
            {service: >}
        ]
        imports: [
            {stream: {account: NCS, subject: _INBOX.>}}
        ]
    },
    NCS: {
        users: [
            {user: ncs, password: ncs}
        ]
        exports: [
            {stream: _INBOX.>}
        ]
        imports: [
            {stream: {account: FOO, subject: >}}
            {service: {account: FOO, subject: foo}}
        ]
    }
}
no_auth_user: foo
```

I intended to:
- foo can send messages of any subject to ncs and receive responses.
- ncs can send only messages of subject 'foo' to foo and receive responses.

And I tested it as follows.

(1) subscribe
> nats-rply -s=nats://localhost:4222 a a-rply
> nats-rply -s=nats://localhost:4202 foo foo-rply
> nats-rply -s=nats://localhost:4202 koo koo-rply

(2) request
> nats-req -s=nats://localhost:4222 foo hello
> nats-req -s=nats://localhost:4222 koo hello
> nats-req -s=nats://localhost:4202 a hello

#### Expected result:
> nats-req -s=nats://localhost:4222 foo hello -> send message and receive response
> nats-req -s=nats://localhost:4222 koo hello -> cant't send message
> nats-req -s=nats://localhost:4202 a hello -> send message and receive response

#### Actual result:
> nats-req -s=nats://localhost:4222 foo hello -> send message and receive response 
> nats-req -s=nats://localhost:4222 koo hello -> cant't send message
> nats-req -s=nats://localhost:4202 a hello -> can't receive response (defect)

I tried the same test on the release-2.1.7 version and it was the expected result.

-DV log :  [foo.log](https://github.com/nats-io/nats-server/files/5657117/foo.log), [ncs.log](https://github.com/nats-io/nats-server/files/5657119/ncs.log)

#### Steps or code to reproduce the issue:

I added the service import configuration to account ncs as shown below.
The following error occurred in the release version
```nats-server:foo.conf:37:52: Duplicate service import subject "", previously used in import for account "FOO", subject "foo"```

There is no error in the beta version.
Which is the correct behavior? Does the nats server support multi import services?

**config - foo**
```
port: 4202
http: 8202
leafnodes {
    port: 7402
    remotes = [ 
        { 
            urls: [
                "nats-leaf://localhost:7422",
            ]
            account: NCS
        }
    ]
}
Accounts: {
    FOO: {
        users: [
            {user: foo, password: foo}
        ]
        exports: [
            {stream: >} # FOO->NCS
            {service: >}
        ]
        imports: [
            {stream: {account: NCS, subject: _INBOX.>}}
        ]
    },
    NCS: {
        users: [
            {user: ncs, password: ncs}
        ]
        exports: [
            {stream: _INBOX.>}
        ]
        imports: [
            {stream: {account: FOO, subject: >}}
            {service: {account: FOO, subject: foo}}
            {service: {account: FOO, subject: goo}} #added
            {service: {account: FOO, subject: hoo}} #added
        ]
    }
}
no_auth_user: foo
```

**Comment by kozlovic** [comment]
@wuddl6 Thank you for the report. If you were to use the tip of the main branch you would find that your configuration would not be accepted because it is determined that it creates a cycle. We added some cycle detection *after* the commit you are used for your tests.

**Comment by wuddl6** [comment]
@kozlovic Thank you for answer.

I checked the commit history and tested latest version.
As far as I understand it, doesn't it support importing the same subject between accounts from version 2.2?
We are designing a service using NATS.
How can I configure it to work as I intended?
 - foo can send messages of any subject to ncs and receive responses.
 - ncs can send only messages of subject 'foo' to foo and receive responses.
I think I can't use wildcard stream and have to write the subject explicitly...

And Is it right to support multiple statements of service import mentioned in 'Issue 2'?

**Comment by matthiashanel** [comment]
@wuddl6 the canonical answer would be to put functionalities that tightly coupled into one account. Same answer as import management in many programming languages.
Mind sharing why FOO imports inboxes? 

The cycle is due to ">" covering _INBOX.> as well. 
So you could break the cycle by exporting say "myprefix.>" instead of ">" (and use myprefix in your apps)
You could also break the cycle by

**Comment by wuddl6** [comment]
@matthiashanel , @kozlovic 
FOO imports _INBOX.> to receive response from NCS.

I used "NCS.>" instead of ">" and tested. (latest master version)

nats-rply -s=nats://localhost:4222 NCS.a a-rply
nats-req -s=nats://localhost:4202 NCS.a hello

But still, the message was not delivered, and the log bellow was left on the foo server.
```
[PUB NCS.a _INBOX.Lhj0089eJY4ML71BYQxl8c.g1i84N9a 5]
[23168] 2020/12/11 14:46:44.678988 [[33mTRC [0m] [::1]:13535-cid:5-"v1.11.0:go:NATS Sample Requestor"-<<- MSG_PAYLOAD: ["hello"]
[23168] 2020/12/11 14:46:44.678988 [[33mTRC [0m] [::1]:7422-lid:2-->> [LMSG NCS.> + _INBOX.Lhj0089eJY4ML71BYQxl8c.g1i84N9a NATS-RPLY -22 5]
```
I guess the subject of LMSG is wrong.
If the client subscribe to NCS.a on foo server (port 4202) as account 'NP', the message is delivered well.

**Comment by matthiashanel** [comment]
@wuddl6 if you export things as service you get the response bit without having to explicitly allow the _INBOX.>

Thus I'd do the following config with the `ncs.` prefix to avoid a cycle with `foo`. 

```
port: 4202
Accounts: {
    FOO: {
        users: [
            {user: foo, password: foo}
        ]
        exports: [
            {service: foo} #ncs can send only messages of subject 'foo' to foo and receive responses.
        ]
        imports: [
            {service: {account: NCS, subject: ncs.>}} # foo can send messages of any subject to ncs and receive responses.
        ]
    },
    NCS: {
        users: [
            {user: ncs, password: ncs}
        ]
        exports: [
            {service: ncs.>} #foo can send messages of any subject to ncs and receive responses.
        ]
        imports: [
            {service: {account: FOO, subject: foo}} # ncs can send only messages of subject 'foo' to foo and receive responses.
        ]
    }
}
```

with this config I can start a requestor in foo and a replier in ncs and get this

* foo can send messages of any subject to ncs and receive responses.
```
> nats reply -s nats://ncs:ncs@localhost:4202 "ncs.>" world
14:26:14 Listening on "ncs.>" in group "NATS-RPLY-22"
14:26:15 [#0] Received on subject "ncs.bar":

hello
^C14:28:49
Draining...
14:28:49 Exiting
>
```

```
> nats req -s nats://foo:foo@localhost:4202 ncs.bar hello
14:26:15 Sending request on "ncs.bar"
14:26:15 Received on "_INBOX.kTivoEhchcD0QFUODL4yKW.tSr7lgUA" rtt 1.22128ms
world

>
```

* ncs can send only messages of subject 'foo' to foo and receive responses.
```
> nats reply -s nats://foo:foo@localhost:4202 "foo" world
14:31:37 Listening on "foo" in group "NATS-RPLY-22"
14:31:55 [#0] Received on subject "foo":

hello
^C14:32:00
Draining...
14:32:00 Exiting
>
```

```
> nats req -s nats://ncs:ncs@localhost:4202 foo hello
14:31:55 Sending request on "foo"
14:31:55 Received on "_INBOX.ktDc1SamHH70p8l3QRKDEC.y7DWPJqr" rtt 525.25µs
world

```

But I'd generally ask myself if the responder to the subject foo needs to be running in the same account as the other logic running in FOO that communicates with NCS? I wonder if it's possible to move that into a separate account. 
(In theory that should allow you to drop the `ncs.` prefix, but I ran into an [issue](https://github.com/nats-io/nats-server/issues/1769) that I hope is fixed soon)

```
cat ac.cfg
port: 4202
Accounts: {
    FOO-RESP: {
        users: [
            {user: resp, password: resp}
        ]
        exports: [
            {service: foo} #ncs can send only messages of subject 'foo' to foo-resp and receive responses.
        ]
    }
    FOO: {
        users: [
            {user: foo, password: foo}
        ]
        imports: [
            {service: {account: NCS, subject: ncs.>}} # foo can send messages of any subject to ncs and receive responses.
        ]
    },
    NCS: {
        users: [
            {user: ncs, password: ncs}
        ]
        exports: [
            {service: ncs.>} #foo can send messages of any subject to ncs and receive responses.
        ]
        imports: [
            {service: {account: FOO-RESP, subject: foo}} # ncs can send only messages of subject 'foo' to foo-resp and receive responses.
        ]
    }
}
no_auth_user: foo
```

```
nats reply -s nats://resp:resp@localhost:4202 "foo" world
14:38:53 Listening on "foo" in group "NATS-RPLY-22"
14:38:54 [#0] Received on subject "foo":

hello
14:38:57 Disconnected due to: EOF, will attempt reconnects for 10m

```

```
nats req -s nats://ncs:ncs@localhost:4202 foo hello
14:38:54 Sending request on "foo"
14:38:54 Received on "_INBOX.5r74hjAUluebhRgUUzM0Yf.I3uFqPE3" rtt 491.763µs
world

```

It's probably not as simple as my example below might have it appear, but if not, what imports/exports between FOO and FOO-RESP would be needed?
Also, since FOO imports everything from NCS, merge them?

**Comment by wuddl6** [comment]
1. Avoiding the cycle
Since one client provides foo service and uses the service of NCS, it cannot be separated into FOO and FOO_RESP.
but I think I can do it with your advice. Thank you for the detailed explanation.
 
2. (Important) Incocrrect delivery of LMSG
The problem is reproduced even in a simple configuration as shown below.
```
port: 4222
http: 8222
leafnodes {
    port: 7422
    authorization {
        account: A
    }
}
Accounts: {
    A: {
        users: [
            {user: a, password: a}
        ]
    }
}
no_auth_user: a
```
```
http: 8202
leafnodes {
    port: 7402
    remotes = [ 
        { 
            urls: [
                "nats-leaf://localhost:7422",
            ]
            account: NCS
        }
    ]
}
Accounts: {
    FOO: {
        users: [
            {user: foo, password: foo}
        ]
        exports: [
            {stream: >}
        ]
    },
    NCS: {
        users: [
            {user: ncs, password: ncs}
        ]
        imports: [
            {stream: {account: FOO, subject: >}}
        ]
    }
}
no_auth_user: foo
```
```
C:\work\go\bin\src-test3>nats-rply -s=nats://localhost:4222 a rply
Listening on [a]
```
```
C:\work\go\bin\src-test3>nats-req -s=nats://localhost:4202 a hello
nats: timeout for request
```
```
[30740] 2020/12/15 10:13:58.501946 [[33mTRC[0m] 127.0.0.1:33064 - cid:8 - "v1.11.0:go:NATS Sample Requestor" - <<- [PUB a _INBOX.0nMgR0z54anxas3RYTKlFE.EBARrAio 5]
[30740] 2020/12/15 10:13:58.502924 [[33mTRC[0m] 127.0.0.1:33064 - cid:8 - "v1.11.0:go:NATS Sample Requestor" - <<- MSG_PAYLOAD: ["hello"]
[30740] 2020/12/15 10:13:58.502924 [[33mTRC[0m] 172.18.96.219:7422 - lid:7 - ->> [LMSG > + _INBOX.0nMgR0z54anxas3RYTKlFE.EBARrAio NATS-RPLY-22 5]
```
I think subject of LMSG should be 'a', not '>'
Please check this.

**Comment by kozlovic** [comment]
I have added a test to demonstrate the issue in the branch: https://github.com/nats-io/nats-server/tree/leafnode_stream_imports. The test is TestLeafNodeStreamImport. cc @derekcollison 

That being said, just to make sure: using streams here is not the right approach to do request/reply, it should be services. The test I have created simply does a subscribe on "a" on "server1" and a publish on "a" on server 2. The message is indeed not received.

**Comment by wuddl6** [comment]
Please check the current status of the 'issue 1'
and please answer about 'issue 2' too.

**Comment by matthiashanel** [comment]
@wuddl6 we fixed issue number 2. Thanks for bringing it to our attention.
As for issue 1, did you manage to get it working with my suggestions?

**Comment by wuddl6** [comment]
@matthiashanel  
Issue 2) I confirmed that it was fixed. Thank you.
Issue 1) I understood the 'avoiding the cycle'. What I asked is about 'multi service import' in the main-text. Is this feature will be supported in version 2.2?
