### ISSUE TITLE
Imports service with wildcards in version 2.2 ?

### ISSUE THREAD

**Issue by yanel** [nats-io/nats-server#1780]
I've notice that nats-server version 2.2.0 support wildcards on import service in Multi Tenancy using Accounts.

Can someone confirm this and give more information on it ?

Does this feature will be supported with Clustering and Super-cluster with Gateways ?

Thanks in advance.

**Comment by derekcollison** [comment]
Yes full wildcard and full mapping support will be available for exports/imports in 2.2
