### ISSUE TITLE
Binary for Apple silicon ?

### ISSUE THREAD

**Issue by imrefazekas** [nats-io/nats-server#1784]
## Feature Request
Binary for apple silicon.

#### Use Case:
I have a MacBook Air M1 and would love to run nats-server natively. 
Go released 1.16beta which is available for ARM64  as well. 

Maybe not an official release but some intel hogy to make it at home would. be also awesome to see.

**Comment by imrefazekas** [comment]
I've made an Apple silicon binary from master branch:

https://www.dropbox.com/s/6nfkszygadf4a9a/nats-server-master-darwin-arm64.zip?dl=0

Hope it helps a few people....

**Comment by derekcollison** [comment]
We will begin building them when Go 1.16 is released. For now folks can build the binaries themselves.
