### ISSUE TITLE
publish same subject with multiple clients will lead to lower performance

### ISSUE THREAD

**Issue by hl3w22bupt** [nats-io/nats-server#1786]
I have a cluster with 3 nats nodes. and I use nats-bench tool to publish and subscribe to test the performance
There are 3 subscription with nats-bench CLI:
nats-bench -np 0 -ns 1 -n 100000000 -s nats://127.0.0.1:4421 foo
nats-bench -np 0 -ns 1 -n 100000000 -s nats://127.0.0.1:4421 foo
nats-bench -np 0 -ns 1 -n 100000000 -s nats://127.0.0.1:4421 foo

And, When I publish with CLI:
nats-bench -np 1 -n 100000000 -s nats://127.0.0.1:4421 foo
I got the result: 
> Starting benchmark [msgs=100000000, msgsize=128, pubs=1, subs=0]
> Pub stats: 1,265,771 msgs/sec ~ 154.51 MB/sec

but when I increase the publish client to 2, I got lower performance
nats-bench -np 2 -n 100000000 -s nats://127.0.0.1:4421 foo
> Starting benchmark [msgs=100000000, msgsize=128, pubs=2, subs=0]
> Pub stats: 994,603 msgs/sec ~ 121.41 MB/sec
>  [1] 497,817 msgs/sec ~ 60.77 MB/sec (50000000 msgs)
>  [2] 497,306 msgs/sec ~ 60.71 MB/sec (50000000 msgs)
>  min 497,306 | avg 497,561 | max 497,817 | stddev 255 msgs

I test multiple times with different size of publish client, when the publish size is 1, the performance is the best

I read the code, I found the function client.deliverMsg have a lock operation and the granularity of the lock is really too big. Could you consider to refine the granularity of the lock.  I am not sure that is the root cause, but it is really weird, why it performs worse when increasing the publishing client size

Thanks and waiting for your response : )

**Comment by kozlovic** [comment]
@hl3w22bupt Thank you for the report. I have been trying to reproduce this to no avail, so it may have to do with the versions/platform/Go versions.

- OS: macOS Mojave
- Server: 2.1.9 (built with Go 1.14.10) and from main branch (Go 1.14.2)
- Client: From main branch
- Go: 1.14.2

Here are typical results (I have ran many):
```
$ go run examples/nats-bench/main.go -np 1 -ns 0 -n 100000000 foo
Starting benchmark [msgs=100000000, msgsize=128, pubs=1, subs=0]
Pub stats: 950,646 msgs/sec ~ 116.05 MB/sec
```
```
$ go run examples/nats-bench/main.go -np 2 -ns 0 -n 100000000 foo
Starting benchmark [msgs=100000000, msgsize=128, pubs=2, subs=0]
Pub stats: 958,695 msgs/sec ~ 117.03 MB/sec
 [1] 479,608 msgs/sec ~ 58.55 MB/sec (50000000 msgs)
 [2] 479,350 msgs/sec ~ 58.51 MB/sec (50000000 msgs)
 min 479,350 | avg 479,479 | max 479,608 | stddev 129 msgs
```
I have tried with a cluster of 3, but since in your report all clients connect to the same server, it does not make a difference. So I then was running with single server.

Could you provide more details about versions/platform, etc..? Thanks!

**Comment by hl3w22bupt** [comment]
@kozlovic Thanks for your response.

Here is my versions/platform info

- OS: Debian 4.14.81
- Server: nats-server: v2.1.8
- Client: From main branch
- Go： 1.15.5

And by the way, in your situation, the performance seems the exactly same whatever 1 publisher or 2.
It confused me much, from my observation, there is one goroutine in server side to handle one publisher client connection, and the publisher was constrained by TCP sliding window, as I observed that Send-Q(send socket buffer) in nats-bench publish side and RecvQ(recv socket buffer) in nats-server side through netstat tool. So I think that increasing the publisher client size will improve the throughput consequently, but it seems doesn't work.

![image](https://user-images.githubusercontent.com/3297112/103393029-a65aae80-4b5b-11eb-9c00-c054b62d9504.png)

Thanks again and happy new year

**Comment by hl3w22bupt** [comment]
Ok, icic , thanks for your answer @kozlovic
