### ISSUE TITLE
Improve API Error Response Structure for Better Programmatic Error Handling

### ISSUE THREAD

**Issue by jon-whit** [nats-io/nats-server#1811]
## Feature Request
The Jetstream API errors do not return a unique error code per path in the current design. This makes it difficult to programmatically react to specific Jetstream errors. I'd like to see the Jetstream API introduce unique error codes per specific error returned.

#### Use Case:
As an example, when I want to create a consumer and the consumer I am creating references a stream that does not exist, I'd like to be able to check the Jetstream API error against a specific uuid code that identifies the fact that the `"stream does not exist"`. Right now with the HTTP code approach, if the HTTP code is overloaded by multiple return paths, then my application cannot really take the appropriate action (unless it parses the error description in some way).

#### Proposed Change:
It would be nice to change the API error structure to something like:

```
{
    "code": "<uuid>",
    "cause": {...}, // underlying error (the error raised by the underlying application; whose fields are subject to change)
    "description": "<description>"
}
```

#### Who Benefits From The Change(s)?
Me, and other developers trying to programmatically react to certain error cases when trying to interact with the Jetstream API. 

For more information, @ripienaar and I had a long conversation about this on [this](https://natsio.slack.com/archives/CM3T6T7JQ/p1609872359263800) slack thread.

**Comment by ripienaar** [comment]
So to summary the problem, toda we have for example `jsNotFoundErrorI()` that makes a generic 404 and you dont know if it means stream not found, consumer not found, template not found or what.

So I am not sure if we should do a huge breaking change now on this one.

Today we have 

```
type ApiError struct {
	Code        int    `json:"code"`
	Description string `json:"description,omitempty"`
}
```

We can add a field here `Kind string` and put in there something like `stream_not_found`, `consumer_not_found` etc, we promise we wont change these strings - effectively they are subject to SemVer - but the descriptions as they are today are not part of any SemVer promises.

This - adding 1 field and not changing any existing fields - doesnt break anything but gets you what you want I think?

**Comment by derekcollison** [comment]
The enclosing type tells you what the 404 pertains to IIRC. Meaning stream or consumer etc. The enclosing advisory has that type IIRC.

**Comment by ripienaar** [comment]
> The enclosing type tells you what the 404 pertains to IIRC. Meaning stream or consumer etc. The enclosing advisory has that type IIRC.

Unfortunately only true in broad strokes, does a 404 from consumer info mean stream or consumer is missing? Could be either.

I dont want to paint us into a corner where people rely on our user friendly strings like `consumer not found`, I'd rather have the freedom to change those, translate them, expand them etc - but add a field thats part of the API promises that one can go - the 404 from consumer info relates to the stream not existing.

**Comment by ripienaar** [comment]
In my initial work around API errors I designed it so that each error would have a code like `NATS0001` or something, this identifier would be the machine consumable way to figure out what is going, including this ambiguity here, the rest is human friendly fluff subject to change, translation, local locale etc

I also added to those errors some extra information - things like where to go for help, so that the cli can do something like `nats error NATS0001` and users can discover more about it and we have doc links and such.

**Comment by jon-whit** [comment]
@ripienaar any progress on this? We just had a scenario the other day pop up where the error code `500` was overloaded and therefore our application was handling the error improperly. Had we been using the error description/message we could have handled it just fine, but since we are not making a contract with the error descriptions/messages we merely rely on the error code. We need a better programmatic way to handle overloaded error cases.

**Comment by ripienaar** [comment]
We havnt had time to look at this, been focussing on stability and perf.

Perhaps 2.2.2 or 2.2.3.

Out of curiosity, can you tell us what the case was you found?

**Comment by ripienaar** [comment]
I took a bit of a stab at this for us to have something to talk about you can see it here https://github.com/nats-io/nats-server/compare/master...ripienaar:1811

With this we have:

```
{"type":"io.nats.jetstream.api.v1.stream_create_response","error":{"code":500,"kind":"JS18","description":"stream name already in use"}}
```

The intention then is to make the `Kind` be a stable API and description and code not be stable.

This is especially useful like in the cases with errors with tokenised strings them since there you couldnt even string compare the descriptions, but they would have stable `Kind`s

**Comment by ripienaar** [comment]
@jon-whit do you have any feedback on this? We could aim this for 2.2.3 perhaps given some feedback on the approach

**Comment by jon-whit** [comment]
@ripienaar sorry for the late response. I think your proposal above looks great. It gives us a stable field to trigger off of that isn't overloaded, which is why I raised this issue in the first place. So that'd be great.

I do have some minor recommendations though.. What field is the primary indicator to the client that a request can or should be retried? Is it the `Code` or the `Kind`? If the code field is not stable, then that would change client expectations if they executed retry logic around it. For example, a client naively interpreting a 500 status `code` would be left to believe that they might retry the request and it may change the outcome. In this case though the outcome is non-transient and will continue to lead to the same error.

This is actually why I really like [Google's approach to errors](https://cloud.google.com/apis/design/errors). 

> Google APIs must use the canonical error codes defined by google.rpc.Code. Individual APIs must avoid defining additional error codes, since developers are very unlikely to write logic to handle a large number of error codes. For reference, handling an average of 3 error codes per API call would mean most application logic would just be for error handling, which would not be a good developer experience.

Additional error details assist clients further in handling errors and are specific to the API serving the error. This is an _in addition to_ sort of spec that helps client error handling be more specific for a given API.

> Additional error detail types should only be introduced if they can assist application code to handle the errors. If the error information can only be handled by humans, rely on the error message content and let developers handle it manually rather than introducing additional error detail types.

**Comment by ripienaar** [comment]
Hmm, I think in our case the 4xx or 5xx is there to tell you the catagory of code, 500s can be retried, 400s not etc.  The Kind tells you specifics (you probably cant retry a JS18 because of the particular of that error).  I see how that's not super useful though.

In specific terms, how would you change the returned structure?

```
{
  "type":"io.nats.jetstream.api.v1.stream_create_response",
  "error":{
    "code":500,
    "kind":"JS18",
    "description":"stream name already in use"
  }
}```

**Comment by derekcollison** [comment]
40x means client issues, 50x means server issue.

**Comment by jon-whit** [comment]
> Hmm, I think in our case the 4xx or 5xx is there to tell you the catagory of code, 500s can be retried, 400s not etc. The Kind tells you specifics (you probably cant retry a JS18 because of the particular of that error). I see how that's not super useful though.
> 
> In specific terms, how would you change the returned structure?
> 
> ```
> {
>   "type":"io.nats.jetstream.api.v1.stream_create_response",
>   "error":{
>     "code":500,
>     "kind":"JS18",
>     "description":"stream name already in use"
>   }
> }```
> ```

In this case, it makes sense to me that the code should be a 404 (Bad Request) because the client is attempting to create a duplicate stream (with different settings but the same name). The `Kind` is then a field that the developer can manually resolve or in cases where the client is dynamically creating streams (don't know of such uses-cases but it's possible) the client could automatically regenerate a new stream name with a different name because of the `JS18` error.

Point is, I think the approach you've stated is a fair approach so long as it's decoupled from the `Code` for retry logic. Retry logic should _not_ be driven around `Kind`. It should merely be used to provide additional details so a client can programmatically handle cases where the returned status code is the same between two different calls.

**Comment by derekcollison** [comment]
I think client retry could utilize both, but I understand the desire for a more concrete error code vs description.

**Comment by scottf** [comment]
yes, any variety of a specific error code is fine. Looking them up would be a bonus, or could just reference a doc somewhere.

**Comment by ripienaar** [comment]
We merged this one in https://github.com/nats-io/nats-server/pull/2168 and will soon have some CLI tools to assist etc, so I'll close this now that we're over the initial bump.  Rest is ongoing maintenance and moving this into other parts of the code.
