### ISSUE TITLE
For JetStream management responses, send unformatted, minimal JSON.

### ISSUE THREAD

**Issue by scottf** [nats-io/nats-server#1829]
## Feature Request
Use unformatted, minimal JSON in JetStream management responses.

#### Use Case:
When the server responds to JetStream management requests the JSON is formatted with CR/LF and indentation spaces. This white-space ends up making up about 25% of the total number of bytes. On a fairly minimal message today, there are about 650 total bytes, of which about 160 are formatting.

#### Who Benefits From The Change(s)?
Reduces the number of bytes in client-server communication, improving performance.

**Comment by derekcollison** [comment]
We have discussed. I am ok with it if R.I. agrees. Maybe add an option to have the pretty print version but default to packed?

**Comment by ripienaar** [comment]
Also in favour of not indenting it. Not sure if it’s worth adding a config option

**Comment by ripienaar** [comment]
We might key off a header instead. Django for example takes the standard accept header with attributes like `Accept: application/json; indent=4`, we could do similar?

**Comment by derekcollison** [comment]
I think that is reasonable.

**Comment by derekcollison** [comment]
This be for all JSON payloads coming from the server yes? Not just JetStream ones that are new.

**Comment by ripienaar** [comment]
That would be nice yes - the server status requests etc too yes

**Comment by derekcollison** [comment]
Looping in @kozlovic just want his opinion real quick unless I missed something.

**Comment by kozlovic** [comment]
@derekcollison No objection to the request.
