### ISSUE TITLE
how to do healthcheck NATS server

### ISSUE THREAD

**Issue by imtiazpk** [nats-io/nats-server#1903]
## Feature Request
I want to check the health of NATS Server. 

#### Use Case:
I have following architecture. I want to check the health of of NATS Server in API Gateway and other service so that I can consider my API Gateway health if NATS server is not healthy. I can send unhealthy to load balancer and it can send request to other nodes. Please suggests a way how to check the health of NATS server.

                                     [VM1 - > API Gateway - > NATS Server -> Micro services ]
Load balance    ---->   [VM2  -> API Gateway  -> NATS Server -> Micro services ]  
                                     [VM3  -> API Gateway  -> NATS Server -> Micro services ]

**Comment by ripienaar** [comment]
The server can listen on an http port. Check that’s up. 

https://docs.nats.io/nats-server/configuration/monitoring

**Comment by imtiazpk** [comment]
@ripienaar 
Thanks. We can use HTTPS as well does it require any certificate. We are already using certificate for NATS Server client port 4222. Does that will be automatically used for 8222 port as well. What exactly we need to check to send request on 8222 port and it is returns 200 it means NATS is functional and healthy. Anything else we need to do?

**Comment by ripienaar** [comment]
You can enable https - see docs - but also plain is fine. 

If you request /varz and it returns 200 I think it’s fine. 

You should ideally check 4222 but obviously it’s not http so it’s harder. You can do a normal TCP health check on 4222 and look for the INFO line. This will cause many log lines though.

**Comment by imtiazpk** [comment]
what if I able to connect with the 4222 port on the same pattern my service uses .NET client for NATS and it connection is successful it means NATS health is OK and If I want stats I can hit http port?

**Comment by ripienaar** [comment]
Correct yes

of course if you have a complex network of nats clusters all connected this won’t tell you about overall health. Then you need to actively send messages over the network to test paths etc

**Comment by ripienaar** [comment]
But as you said just for local health earlier suggestions will work

**Comment by imtiazpk** [comment]
Thanks.  I will then use 4222 port. Each time health check executes it will connect, subscriber, send message, received the same message, disconnect. If everything executed gracefully it means health is ok.

**Comment by ripienaar** [comment]
yes if your API Gateway is capable of such a deep test then thats ideal.  Will close this one for now feel free to reopen if you have questions.

**Comment by imtiazpk** [comment]
I just implement the health check connect with NATS 4222 using C# NATS client and then disconnect this. My load balancer check the health of my service after 10 seconds with timeout of 5 seconds. Sometime NATS connection takes time like 5 to 10 seconds in that case load balancer health check timeouts and it consider the node unhealthy if it is healthy. I am using NATS 2.0.4 version and C# Nuget package NATS.Client(0.10.1). Why connection is taking that much time. I have enabled the NATS debug and Trace log and it is sending the connection after 10 seconds here are the logs.

[3144] 2021/06/18 09:08:28.739213 [DBG] fe80::e534:d449:555:3a21:64199 - cid:108 - Client connection created
[3144] 2021/06/18 09:08:28.739213 [DBG] fe80::e534:d449:555:3a21:64199 - cid:108 - Starting TLS client connection handshake
[3144] 2021/06/18 09:08:28.746398 [DBG] fe80::e534:d449:555:3a21:64199 - cid:108 - TLS handshake complete
[3144] 2021/06/18 09:08:28.746398 [DBG] fe80::e534:d449:555:3a21:64199 - cid:108 - TLS version 1.2, cipher suite TLS_RSA_WITH_AES_128_CBC_SHA
[3144] 2021/06/18 09:08:38.919788 [TRC] fe80::e534:d449:555:3a21:64199 - cid:108 - <<- [CONNECT {"verbose":false,"pedantic":false,"user":"admin","pass":"[REDACTED]","ssl_required":true,"name":"","auth_token":"","lang":".NET","version":"0.0.1","protocol":1,"jwt":"","nkey":"","sig":"","echo":true}]
[3144] 2021/06/18 09:08:38.985878 [TRC] fe80::e534:d449:555:3a21:64199 - cid:108 - <<- [PING]
[3144] 2021/06/18 09:08:38.985878 [TRC] fe80::e534:d449:555:3a21:64199 - cid:108 - ->> [PONG]
[3144] 2021/06/18 09:08:38.986906 [DBG] fe80::e534:d449:555:3a21:64199 - cid:108 - Client connection closed
