### ISSUE TITLE
JS: advisories subject doesn't follow standard prefix

### ISSUE THREAD

**Issue by aricart** [nats-io/nats-server#1917]
The advisories subject is `$JS.EVENT.ADVISORY.>`, prefix is `$JS.API`.
To be consistent with other $JS subjects, likely it should be `$JS.API.EVENT.ADVISORY.>`

**Comment by ripienaar** [comment]
I don’t agree. They aren’t API. Why would they need to be consistent?

**Comment by ripienaar** [comment]
Being seperate means its much easier to avoid mistakes, I can give surveyor access to `$JS.EVENT.>` safely knowing no mistake gives it access to any API, if it was `$JS.API.<something>` its just a bit easier to fat finger something, also API implies changing things.

**Comment by aricart** [comment]
well if you want to create higher level services that supervise, the advisories are useful. If we are going to have the notion of a prefix - I am ok with this having a different prefix but at least we are consistent in that there is a prefix.

**Comment by ripienaar** [comment]
For sure, though where is this coming up? From what I know we're roughly doing nothing with these past what the CLI is doing? 

Agree we need prefixes though - CLI doesnt support them yet atm, but we totally should.

**Comment by aricart** [comment]
I noticed while implementing. :)
