### ISSUE TITLE
CONSUMER.INFO does not return filter subject

### ISSUE THREAD

**Issue by scottf** [nats-io/nats-server#1939]
#### Versions of `nats-server` and affected client libraries used:
nats-server: v2.2.0-beta.92

#### OS/Container environment:
Windows 10 / Ubuntu 20.04.2 LTS

#### Expected result:
Consumer info request returns filter subject.

#### Steps or code to reproduce the issue:

1. Check the stream:
```
> nats stream info test-stream
    ...
	Subjects: test-subject
```

2. Create the durable consumer:
```
Request:
$JS.API.CONSUMER.DURABLE.CREATE.test-stream.test-consumer
{
	"stream_name": "test-stream",
	"config": {
		"durable_name": "test-consumer",
		"deliver_subject": "_INBOX.LF6A1TyXncQuCH3jX5oWkZ",
		"deliver_policy": "all",
		"opt_start_seq": 0,
		"ack_policy": "explicit",
		"ack_wait": 30000000000,
		"max_ack_pending": 65536,
		"filter_subject": "test-subject",
		"replay_policy": "instant",
		"rate_limit": 0
	}
}
```

3. Check the consumer:
```
> nats consumer info test-stream test-consumer
    ...
    Durable Name: test-consumer
```

4. Get the consumer info:
```
Request:
$JS.API.CONSUMER.INFO.test-stream.test-consumer

Response:
	{
		"type": "io.nats.jetstream.api.v1.consumer_info_response",
		"stream_name": "test-stream",
		"name": "test-consumer",
		"created": "2021-02-25T13:09:03.3166804Z",
		"config": {
			"durable_name": "test-consumer",
			"deliver_subject": "_INBOX.LF6A1TyXncQuCH3jX5oWkZ",
			"deliver_policy": "all",
			"ack_policy": "explicit",
			"ack_wait": 30000000000,
			"max_deliver": -1,
			"replay_policy": "instant",
			"max_ack_pending": 65536
		},
		"delivered": {
			"consumer_seq": 0,
			"stream_seq": 0
		},
		"ack_floor": {
			"consumer_seq": 0,
			"stream_seq": 0
		},
		"num_ack_pending": 0,
		"num_redelivered": 0,
		"num_waiting": 0,
		"num_pending": 0,
		"cluster": {
			"leader": "NBENMA2CRXVLQETLH3CCEXGXVOMZHB5FQWNW4TRONG5ZWHZ6UM5DE4JW"
		}
	}
```

**Comment by ripienaar** [comment]
If the filter subject is a direct match for the stream subject we don't store the filter subject - there's no point since it would match all messages and we'd just waste time processing this.

I think though thats not the right thing to do because later I might edit the stream to add additional subject and we'd now have lost the fact you only cared for this one subject.  So we probably should.

https://github.com/nats-io/nats-server/blob/cc038a6d950cae02bc14b3a2bef70ca552d7ec13/server/consumer.go#L297-L299

wdyt @derekcollison

**Comment by derekcollison** [comment]
We could take that optimization out. Feel free to yank it and submit PR.

**Comment by ripienaar** [comment]
https://github.com/nats-io/nats-server/pull/1940
