### ISSUE TITLE
Creation an invalid 2 node JetStream cluster is allowed

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats-server#1957]
Minor UX issue - I was able to create a useless 2-node JS cluster - have seen users try this.  Adding another server later will create a valid JS cluster so this is a poorly done configuration but not necessarily 100% invalid.

This is primarily a doc item although for UX we could print a warning message when two JS candidates are found and only 1 route is configured.  e.g. `Detected possible invalid 2 node JetStream cluster.`

### Configs

Server 1
```
server_name=s1
listen=4222
http=8222

jetstream {
   store_dir=storage/s1
}

cluster {
  name: c1
  listen: 127.0.0.1:6222
  routes: [
    nats-route://127.0.0.1:6333
  ]
}
```

Server 2
```
server_name=s2
listen=4333
http=8333

jetstream {
   store_dir=storage/s2
}

cluster {
  name: c1
  listen: 127.0.0.1:6333
  routes: [
    nats-route://127.0.0.1:6222
  ]
}
```

**Comment by ripienaar** [comment]
Derek wants to support 2 node clusters. Effectively 2 cluster super-clusters are the same.

**Comment by derekcollison** [comment]
I think this can be valid in some situations. Especially with auto-remediation turned back on.
