### ISSUE TITLE
Question about changing max_payload

### ISSUE THREAD

**Issue by jonaaah** [nats-io/nats-server#1967]
Hi there, it looks like the non-streaming version of the nats server allows you to override the max message size of 1MB through max_payload parameter, is this correct?

The question we have is, if we change the maximum nats message size, does this result in any increased memory usage that we should be aware of? We weren't sure if extra memory or disk would be used to allocate space for allowing for increased message sizes even if messages remain small, or if the footprints just grow as the messages grow?

Our target systems have somewhat limited resources.

**Comment by kozlovic** [comment]
The bigger the message max payload, the bigger buffer is needed to read the whole message from the socket and then enqueueing it to outbound connections that are interested.
But NATS server does not "store" messages in memory (except for the actions described above).
