### ISSUE TITLE
Add unique identifier to api error responses

### ISSUE THREAD

**Issue by scottf** [nats-io/nats-server#1975]
## Feature Request
Add unique identifier to api error responses

#### Use Case:
When calling CONSUMER.INFO.%s.%s and an error is returned we have to check the string description to determine which was the problem, the stream or the consumer, since both errors are 404

```
io.nats.jetstream.api.v1.consumer_info_response 404 consumer not found
io.nats.jetstream.api.v1.consumer_info_response 404 stream not found
```

#### Proposed Change:
Add a field to the error object to hold a unique numeric code

#### Who Benefits From The Change(s)?
Clients can identify specific errors faster and without relying on string comparison.

**Comment by ripienaar** [comment]
My plan was to do this after GA as it’s an addition so would be safe. 

Duplicate issue here https://github.com/nats-io/nats-server/issues/1811

**Comment by scottf** [comment]
Duplicate issue here #1811
