### ISSUE TITLE
get CONSUMER.NAMES with filter does not filter

### ISSUE THREAD

**Issue by scottf** [nats-io/nats-server#1977]
## Question, might be DEFECT

get CONSUMER.NAMES with filter does not filter

[jetstream.log.txt](https://github.com/nats-io/nats-server/files/6103742/jetstream.log.txt)

#### Versions of `nats-server` and affected client libraries used:
nats-server: v2.2.0-RC.6

#### OS/Container environment:
Windows 10 / Ubuntu 20

#### Steps or code to reproduce the issue:
1. Create a stream
```
StreamInfo{created=2021-03-08T19:39:02.766719800Z[GMT],
    StreamConfiguration{name='stream-1', subjects=[subject-101, subject-102]
```

2. Add some consumers

```
ConsumerInfo{stream='stream-1', name='durable-101-1'
    ConsumerConfiguration{durable='durable-101-1', ... filterSubject='subject-101'}

ConsumerInfo{stream='stream-1', name='durable-102-1'
    ConsumerConfiguration{durable='durable-102-1', ... filterSubject='subject-102'}

ConsumerInfo{stream='stream-1', name='durable-102-2'
    ConsumerConfiguration{durable='durable-102-2', ... filterSubject='subject-102'}
```

3. Get list of consumers without filter:
```
CONSUMER.NAMES.stream-1 | {"offset":0}
    durable-101-1
    durable-102-1
    durable-102-2
```

4. Get list the consumers with a filter, all return the same response as if no filter was supplied.
```
CONSUMER.NAMES.stream-1 | {"offset":0,"subject":"no-match"}
CONSUMER.NAMES.stream-1 | {"offset":0,"subject":"subject-101"}
CONSUMER.NAMES.stream-1 | {"offset":0,"subject":"subject-102"}
```

#### Expected result:

Filter consumer by matching filter subject

#### Actual result:

All consumers for stream, regardless of filter subject.

**Comment by ripienaar** [comment]
Where did you see you can specify a `subject` there? I do not believe this is a supported feature at all?

**Comment by derekcollison** [comment]
I don't think we have that supported in the server.
