### ISSUE TITLE
Define a log level.

### ISSUE THREAD

**Issue by Zyqsempai** [nats-io/nats-server#1983]
Hello,
From the [documentation](https://docs.nats.io/nats-server/configuration/logging) I can see that there is a way to increase the verbosity of the logs(-DV flag at least) I see no way how can I decrease it, or in other words to define the log level.
Currently, based on the logs, I can say that default is `INFO` level, but sometimes it's too noisy, especially in the gateway mode, it produces a huge amount of logs, which increases the load of the logs collectors, and so on.
Here is the example:
```
2021-03-09 18:34:13 | [7] 2021/03/09 16:34:13.662515 [INF] - gid:3329916 - Gateway connection closed: Client Closed
-- | --
  |   | 2021-03-09 18:34:13 | [7] 2021/03/09 16:34:13.662403 [INF] - gid:3329916 - Processing inbound gateway connection
  |   | 2021-03-09 18:34:13 | [7] 2021/03/09 16:34:13.366238 [INF] - gid:3329913 - Gateway connection closed: Client Closed
  |   | 2021-03-09 18:34:13 | [7] 2021/03/09 16:34:13.366062 [INF] - gid:3329913 - Processing inbound gateway connection
  |   | 2021-03-09 18:34:12 | [7] 2021/03/09 16:34:12.662926 [INF]  - gid:3329905 - Gateway connection closed: Client Closed
  |   | 2021-03-09 18:34:12 | [7] 2021/03/09 16:34:12.662824 [INF]  - gid:3329905 - Processing inbound gateway connection
  |   | 2021-03-09 18:34:12 | [7] 2021/03/09 16:34:12.523955 [INF]  - gid:3329904 - Gateway connection closed: Client Closed
  |   | 2021-03-09 18:34:12 | [7] 2021/03/09 16:34:12.523898 [INF]  - gid:3329904 - Processing inbound gateway connection
  |   | 2021-03-09 18:34:12 | [7] 2021/03/09 16:34:12.419422 [INF]  - gid:3329903 - Gateway connection closed: Client Closed
```

Is there a way to switch to `ERROR` for example?
If no, is it possible to request such a feature, I would be glad even to contribute to it.
Thanks in advance.

**Comment by kozlovic** [comment]
ERROR, like INF, cannot be suppressed. Only debug (DGB) and trace (TRC) can.
In the specific case, I would not focus on too much tracing but instead why gateway connections are opened and closed so frequently. It is either a misconfiguration, or you maybe have clients trying to connect to the gateway port? (I doubt, since then you would see an ERR such as `[ERR] [::1]:54018 - gid:6 - attempted to connect to gateway port`, unless you have filtered it out in your report).

**Comment by Zyqsempai** [comment]
Thanks a lot for your fast response.

**Comment by kozlovic** [comment]
Have you verified if you have a misconfiguration or it is clients (or others) trying to connect to the gateway port?
As I mentioned, there is no way currently to suppress INF or ERR logging, and I am not sure we have plan to do that. Let me know if this issue can be closed.

**Comment by Zyqsempai** [comment]
@kozlovic Thank you for pointing, It was a health check who tried to connect so intense. Now I see that it make sense to keep such level for logs, even on INF level it can show and help to detect some problems.
You can close the issue.
Thanks a lot.
