### ISSUE TITLE
Monitoring: connz do not store slow consumers.

### ISSUE THREAD

**Issue by Zyqsempai** [nats-io/nats-server#1990]
Hi,
We try to detect slow consumers in our infrastructure, we get the next lines in the logs:

```
2021-03-10 15:08:19 | [6] 2021/03/10 13:08:19.103505 [INF] - cid:3749634 - Slow Consumer Detected: WriteDeadline of 2s exceeded with 1 chunks of 4237 total bytes.
```
but when we try to find the client name by `cid` with the next request `/connz?state=closed&cid=3749634` we get empty connections response, in the non closed connections it's also not found.
Is it well-known behavior or facing some issue or misconfiguration? 
Thanks in advance.

**Comment by kozlovic** [comment]
Based on the `cid` which is an incremental number any time a client connects, I think that you have either a lot of clients, or a lot of clients that connect/disconnect. The `state=closed` maintains only about 1000 closed connections. So if your clients create/close connections in a very rapid way, it is possible that the client you are looking for is already gone.

**Comment by Zyqsempai** [comment]
Again, thank you for your response, and explanation. You're right, looks like we have a lot of extra connections, and again it's related to health checks, we still trying to find a proper endpoint for it.
You can close the issue, thanks a lot.

**Comment by ripienaar** [comment]
If you have a system account enabled the server publishes events related to each connection and disconnection.

You can use `nats event` to view these or subscribe to `$SYS.ACCOUNT.*.CONNECT` and `$SYS.ACCOUNT.*.DISCONNECT`
