### ISSUE TITLE
Missing SHUTDOWN system event when server is shut down using nats-server --signal stop=<pid>

### ISSUE THREAD

**Issue by matthiashanel** [nats-io/nats-server#2031]
in a cluster with 2 or more server,
subscribe to "\$SYS.SERVER.>"
when you shut down a server (that is not the one the subscriber is connected to) using ctrl+c
then the subscriber receives a message like this:
```
[#22] Received on "$SYS.SERVER.NDHDOZ55WNGZKPXULZFY7AMRR6CEATFL3LHWCF5CPJP3ETEJP7ZVJUHF.SHUTDOWN"
{"name":"srv-A-4223-4226","host":"localhost","id":"NDHDOZ55WNGZKPXULZFY7AMRR6CEATFL3LHWCF5CPJP3ETEJP7ZVJUHF","cluster":"test-cluster","ver":"2.2.1.RC7","seq":15,"jetstream":true,"time":"2021-03-23T19:06:19.644494Z"}
```
If the same is done using `nats-server --signal stop=<pid>` instead of `ctrl+c`, no such message is received

**Comment by kozlovic** [comment]
I don't think this is an issue since "stop" means SIGKILL which can't be trapped if I am not mistaken: https://docs.nats.io/nats-server/nats_admin/signals
User should use `--signal quit=<pid>` to quit the server gracefully so it has a chance to send the event.

**Comment by derekcollison** [comment]
Did not pick up on this at first. @matthiashanel I think this can be communicated and this issue closed yes?

**Comment by matthiashanel** [comment]
Agreed!
