### ISSUE TITLE
Support Scoop installation

### ISSUE THREAD

**Issue by Hanggi** [nats-io/nats-server#2063]
I found that nats-server only support choco install on Windows,

Could you please support scoop install?

Thank you.

**Comment by Hanggi** [comment]
Any updates?

Thank you.

**Comment by Lemorz56** [comment]
Sorry for bumping an old thread, I have created a manifest for scoop to install nats-server as it would be quite handy for me. 

Originally i was looking at choco but that package seems outdated which led me to find this issue. The scoop manifest also has the ability to auto-update via github releases without having to maintain the manifest file every time you make a release.

Anyway, I forked scoop's manifest repo and added nats-server which you can see here: https://github.com/Lemorz56/Main/commit/3ac8e1523e379c54db3fb8dd796637457015848d
I wanted to check with you if I would be allowed to make a PR to add this manifest to the official scoop bucket 😄

**Comment by scottf** [comment]
Completed https://github.com/ScoopInstaller/Main/pull/3962
