### ISSUE TITLE
stream expired messages are mot removed from consumer pending ack list

### ISSUE THREAD

**Issue by ripienaar** [nats-io/nats-server#2083]
A stream with age limits on the messages will remove messages once they hit that time.  However any messages that at that point were not acked on a consumer will continue to be considered as ack outstanding.

If the max ack outstanding is reached by such a consumer/stream the consmer is forever dead as it can never recover from that scenario.

Here is a stream that recently expired all its messages:

```
State:

             Messages: 0
                Bytes: 0 B
             FirstSeq: 101
              LastSeq: 100 @ 2021-04-08T11:09:40 UTC
     Active Consumers: 1
```

And a consumer on the same stream

```
State:

   Last Delivered Message: Consumer sequence: 100 Stream sequence: 10
     Acknowledgment floor: Consumer sequence: 0 Stream sequence: 0
         Outstanding Acks: 10 out of maximum 10
     Redelivered Messages: 10
     Unprocessed Messages: 0
```

At this point the consumer will never again deliver messages even if new messages are added to the stream

**Comment by derekcollison** [comment]
Meaning even when they are properly acked if the stream had expired them they are still considered pending?

**Comment by ripienaar** [comment]
I dont know about that and I dont think it applies, this is specifically about unacked messages that are - while waiting for ack - expired from the stream

**Comment by derekcollison** [comment]
Those ack's are still outstanding from the viewpoint of the consumer. They were valid when delivered and I believe the ack is still required. If the consumer acks does it work properly?

**Comment by ripienaar** [comment]
They do not go away even after ack wait is past. I dont know if acking one of those will work, clients are crashed or whatever.

**Comment by derekcollison** [comment]
I will check that after ack wait has expired they are cleaned up.
