### ISSUE TITLE
the messeges  are deleted  after rm consumer on InterestPolicy stream

### ISSUE THREAD

**Issue by GuangchaoDeng** [nats-io/nats-server#2097]
1、create stream:t24 and consumer:t24，The details are as follows:

Configuration:

             Subjects: t24
     Acknowledgements: true
            Retention: File - Interest
             Replicas: 1
       Discard Policy: New
     Duplicate Window: 2m0s
     Maximum Messages: unlimited
        Maximum Bytes: unlimited
          Maximum Age: 0.00s
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited

State:

             Messages: 0
                Bytes: 0 B
             FirstSeq: 0
              LastSeq: 0
     Active Consumers: 0
     
     Configuration:
    
            Durable Name: t24
        Delivery Subject: t244
             Deliver All: true
              Ack Policy: All
                Ack Wait: 30s
           Replay Policy: Instant
         Max Ack Pending: 3
    
    State:
    
       Last Delivered Message: Consumer sequence: 0 Stream sequence: 0
         Acknowledgment floor: Consumer sequence: 0 Stream sequence: 0
             Outstanding Acks: 0 out of maximum 3
         Redelivered Messages: 0
         Unprocessed Messages: 0

2、pub 11 messeges to subject ：t24; Subscribe to subject: t244, get 3 messages, and don't reply to ack.

The details are as follows:

`[leaf_1@host5 nats-cli]$ ./nats  -s nats://leaf_1:leaf_1@localhost:5222 sub t244`
`22:29:14 Subscribing on t244`
`[#1] Received JetStream message: consumer: t24 > t24 / subject: t24 / delivered: 1 / consumer seq: 1 / stream seq: 1 / ack: false`
`1`

`[#2] Received JetStream message: consumer: t24 > t24 / subject: t24 / delivered: 1 / consumer seq: 2 / stream seq: 2 / ack: false`
`2`

`[#3] Received JetStream message: consumer: t24 > t24 / subject: t24 / delivered: 1 / consumer seq: 3 / stream seq: 3 / ack: false`

Configuration:

        Durable Name: t24
    Delivery Subject: t244
         Deliver All: true
          Ack Policy: All
            Ack Wait: 30s
       Replay Policy: Instant
     Max Ack Pending: 3

State:

   Last Delivered Message: Consumer sequence: 3 Stream sequence: 3
     Acknowledgment floor: Consumer sequence: 0 Stream sequence: 0
         Outstanding Acks: 3 out of maximum 3
     Redelivered Messages: 0
     Unprocessed Messages: 7

Configuration:

             Subjects: t24
     Acknowledgements: true
            Retention: File - Interest
             Replicas: 1
       Discard Policy: New
     Duplicate Window: 2m0s
     Maximum Messages: unlimited
        Maximum Bytes: unlimited
          Maximum Age: 0.00s
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited

State:

             Messages: 10
                Bytes: 341 B
             FirstSeq: 1 @ 2021-04-10T14:27:26 UTC
              LastSeq: 10 @ 2021-04-10T14:27:41 UTC
     Active Consumers: 1
3、rm consumer ： t24，The stream  details are as follows:

Configuration:

             Subjects: t24
     Acknowledgements: true
            Retention: File - Interest
             Replicas: 1
       Discard Policy: New
     Duplicate Window: 2m0s
     Maximum Messages: unlimited
        Maximum Bytes: unlimited
          Maximum Age: 0.00s
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited

State:

             Messages: 7
                Bytes: 239 B
             FirstSeq: 4 @ 2021-04-10T14:27:30 UTC
              LastSeq: 10 @ 2021-04-10T14:27:41 UTC
     Active Consumers: 0
**Why are the 3 un ack messages of stream: t24 deleted? Is this normal?**

**Comment by ripienaar** [comment]
As stated on slack:

An interest based stream keeps messages - any messages - only as long as there are consumers. When there are no consumers no messages are kept. Even unacked ones. 

The stream doesn’t actually have a clue if a message is acked since ack is a consumer thing anyway.

**Comment by GuangchaoDeng** [comment]
This means that unconsumed messages that have been cached will always be cached; data that has been consumed by the consumer, no matter whether it is acked or not, deleting the consumer will delete the consumed messages？ @ripienaar

**Comment by ripienaar** [comment]
Deleting the *last* consumer will delete the messages, Interest based means keep message as long as anyone has interest - or til limits such as age/size is met.

**Comment by GuangchaoDeng** [comment]
In the above test, the stream has only one consumer, I deleted it

**Comment by GuangchaoDeng** [comment]
Active Consumers: 0

**Comment by ripienaar** [comment]
Sorry, can you please state what the problem is you are experiencing, not with just pasting a bunch of state outputs, but describe what the problem is.

**Comment by GuangchaoDeng** [comment]
”Deleting the last consumer will delete the messages, Interest based means keep message as long as anyone has interest - or til limits such as age/size is met.”-----it means all the messeges  will be deleted after i delete the last consumer。but int the bug description above，i  only create one cosnumer of the stream，then i  deltete the consumer,but the left messeges  exist in the stream  。I don't know if I understand it right

**Comment by ripienaar** [comment]
OK, will investigate

**Comment by ripienaar** [comment]
Appears to be a number of problems:

 1. When no active consumers are present, all messages should be deleted but its not
 2. When messages are deleted by interest based streams they are considered as deleted sometimes

**Comment by derekcollison** [comment]
The considered deleted for interior messages that were removed when the interest was ack'd that is normal, that is how they present in the stream info.

For the other that is a bug, looking now.

**Comment by derekcollison** [comment]
Believe this is handled now. Deleted messages from interior deletes of a stream is normal. Fixed the other issue with pull based consumers.

If I am mistaken feel free to re-open.
