### ISSUE TITLE
Readloop processing time and Slow consumer Detected

### ISSUE THREAD

**Issue by emas80** [nats-io/nats-server#2112]
We are running a cluster with 3 nodes on Kubernetes, the nats version is `2.1.7`.
We had an issue the last night were the delivery of most of the messages was delayed by seconds, instead of being almost instant,
Checking the logs of the nats pods, I can see it plenty of 

```
Readloop processing time: 8.412502572s
```
and
```
Slow Consumer Detected: WriteDeadline of 2s exceeded with 287 chunks of 18065757 total bytes.
```
This was across all of them.

The entire cluster was processing - according to the Prometheus metrics - about 2.2k messages in per second, which were becoming between 4k and 20k messages out.
Each pod was receiving between 1 and 1.5MB in and sending between 1 and 2MB out (between 1k and 10k messages on each pod), those numbers were scraped by Prometheus and are just to give a general idea on the amount of traffic. The traffic changes a lot even every few seconds because it might happen that now we are sending one message to thousands of subscribers, and one second later a few messages to just a couple of subscribers, and the messages have different sizes etc.

I would need some help in understanding what those messages exactly mean and which changes we might want to do to our setup in order to fix the problem.

We should be able to replicate the issue on a test cluster by simulating some traffic, but as for now I have no idea what to change in our setup, and I would end up blindly adding more pods or more CPU/Memory until the logs disappear. 

I understand that the `Slow Consumer` means one (or more) of the clients was not consuming the messages quickly enough - for different reasons, does that imply that the messages were dropped? Or just that the client were slow at processing them?
I don't understand what the `Readloop processing` means? Are the two things connected?
We have seen the number of the slow consumers going up and increasing with time, why weren't they disconnected from the server?

**Comment by wallyqs** [comment]
Hi @emas80, starting in NATS v2.2 we have bumped the default of `write_deadline` from 2s to 10s which we have found to be working better in v2.0 series.  When you get a slow consumer, yes that means that the client will be disconnected by the server.   A Readloop processing WARN means that there are some conditions where a client reading from the server is taking more than 2 seconds, it could have been due to a pause in the server for some external reason, how many CPUs are allocated for the NATS Server at least 2?

**Comment by emas80** [comment]
We were thinking at increasing the `write_deadline` as we have burst of 1k messages that need to be sent, and according to the doc that seems to help.

We are reserving 6 cores to each of the pods, they actually use up to 4 at peak, but that night one of them went up to 6. We give them 8GB of ram, and it normally is enough, but we had two pods using up to 20GB each after a surge in the messages being processed, and at that point they weren't basically working anymore and we had to restart them.

After the restart of the nats server pods, everything went back to normal - no more slow consumers. It seems as if the restart killed the slow consumers, which did not reconnect/were not slow anymore. And that is strange, because we have the automatic reconnection on every consumer, and the consumers seemed perfectly fine during the entire time.

We do not understand why the server did not kill the consumers before - it those were causing so many issues. And why in order to improve the situation we had to restart the servers, while the consumers seemed perfectly fine and they stopped "being slow" after the server restart.

**Comment by ripienaar** [comment]
When it logs WriteDeadline it disconnects the client, that does not prevent them from reconnecting.  Generally it's best to show us the entire log lines not just fragments, what what you gave us we arent sure what is struggling.

If you run NATS and you are putting a lot of traffic through it I would not artificualy limit its resources personally.

How big are the messages you send?

**Comment by emas80** [comment]
The messages size can be between 1kb up to 15k/20kb, with the great majority being towards 1kb.
The logs are literally a never ending stream of 
```
[INF] 10.8.33.4:6222 - rid:411 - Slow Consumer Detected: WriteDeadline of 2s exceeded with 99 chunks of 6184441 total bytes.
```
and 
```
[WRN] 10.8.2.36:45682 - cid:297 - Readloop processing time: 7.653471541s
```
every few seconds.
I assume the SlowConsumer contains the IP of the NAT server, while the Readloop contains the one of the consumer.
From the logs, there was basically nothing before 7.26, while everything started at around 7.35.

We send burst of messages every few minutes, at peaks it can be also 20k messages every few minutes (the ones sent in burst are very small).
I would try to increase `write_deadline` expecially if the default value is now 10s instead of 2s.

I've seen v2.2 is out, I do not find any guide for the upgrade, is it safe to just run the new version or is there anything we should be aware of? Is it backwards compatible like 1.x/2.x?


![Up to 7.36](https://user-images.githubusercontent.com/2953749/115048132-26214480-9ed1-11eb-93f0-3e1cb86b8dc0.png)
![After 7.36](https://user-images.githubusercontent.com/2953749/115048210-3afdd800-9ed1-11eb-9802-cedcd1365357.png)

**Comment by derekcollison** [comment]
Yes you can just run 2.2.1 in place of 2.1.7.

Seems the network across the routes is being overwhelmed to me.

**Comment by cpiotr** [comment]
A comment from@wallyqs explains that the read loop refers to client reading from the server.
However, the read loop code seems to increment stats for in_XXX counters: https://github.com/nats-io/nats-server/blob/v2.6.5/server/client.go#L1175 and I'd like to clarify which path of message passing is taking long when the warning pops up.

Context: we're seeing a readloop warnings for a number of client connections followed by one connection being marked as a slow consumer and getting closed.

**Comment by neilalexander** [comment]
FYI, you've just responded to a GitHub issue that last had activity three and a half years ago and you've just linked to `client.go` from a three-year-old release.

If you have a problem, please first upgrade to the latest version and then if it still happens, open a new issue.
