### ISSUE TITLE
Upgrade from v2.1.9 cause error in embedded nats-streaming on start

### ISSUE THREAD

**Issue by ymkins** [nats-io/nats-server#2141]
## Defect

After upgrade from nats-server v2.1.9 to v2.2.0, or v2.2.1
the embedded nats-streaming-server fails to start with message
"request error detecting another server instance: nats: no responders available for request"

#### Versions of `nats-server` and affected client libraries used:
github.com/nats-io/nats-server/v2 v2.2.0
github.com/nats-io/nats-server/v2 v2.2.1

#### OS/Container environment:
Linux 5.10.0-1023-oem #24-Ubuntu SMP Thu Apr 15 13:46:37 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

#### Steps or code to reproduce the issue:
* embed nats-streaming

Tests prepared here:
https://github.com/ymkins/embed_nats_streaming

There are git tags can be used to load tests with different versions of `nats-server`.
It worked with nats-server-v2.1.9.
And it fails with nats-server-v2.2.0 and nats-server-v2.2.1.

#### Expected result:
all tests pass

#### Actual result:
tests fails on start embedded server with message
"request error detecting another server instance: nats: no responders available for request"

**Comment by kozlovic** [comment]
@ymkins Please subscribe to this issue instead: https://github.com/nats-io/nats-streaming-server/issues/1180

**Comment by kozlovic** [comment]
@ymkins Try to vendor nats.go to v1.10.0 to see if that works, but as directed in the streaming issue I posted, we will update nats streaming server (and stan.go) with code supporting "no responders" when nats.go v1.11.0 is officially released.
