### ISSUE TITLE
varz endpoint no longer reports the correct number of subscriptions

### ISSUE THREAD

**Issue by harrisa1** [nats-io/nats-server#2176]
## Defect

This change https://github.com/nats-io/nats-server/pull/2074/commits/e24e54c5a3796e10a0ed1d9a51da70edf2379300 appears to never reset the value to zero. So it grows continually (my server set up currently shows well over 200k subscriptions using the varz endpoint when in fact it is just ~400 which is reported correctly by the subz endpoint).  Since prior to this change it set `v.Subscriptions = s.gacc.sl.Count()` it reset the value every time, but now it uses `v.Subscriptions += acc.sl.count` which means it repeatedly adds the value to the total, but never resets the value to zero prior to starting the range loop.

#### Versions of `nats-server` and affected client libraries used:

2.2.2

#### Steps or code to reproduce the issue:

Hit the /varz monitoring endpoint and then hit it a second time (or more)

#### Expected result:

The subscription count will be constant (assuming no subscription changes).

#### Actual result:

The subscription count grows with every single request.

**Comment by kozlovic** [comment]
Let me know if this addresses it and I will close this issue.

**Comment by harrisa1** [comment]
LGTM, I didn't see an issue for it, so wasn't sure it had been noticed yet.  You can close if you want.

**Comment by kozlovic** [comment]
@harrisa1 No worries. It was discovered as part of issue #2170. I am closing this issue now.
