### ISSUE TITLE
How to provide origin header when connecting a leafnode server via websocket?

### ISSUE THREAD

**Issue by wutkemtt** [nats-io/nats-server#2207]
Currently we are testing NATS leafnode connections via websocket. This is a very cool feature and important to us, as it could reduce the infrastructure costs a lot.
I saw the "allowed_origins" parameter in the websocket config block and tried it out. Unfortunately I don't know how to provide the matching value from the leafnode side, there is no config option. 
Our NATS server logs the following error: "websocket handshake error: origin not allowed: origin not provided".
With the restriction commented out the connection works as expected. 
Could you describe, how we have to provide the origin info (client's request Origin header) to the server?

**Comment by kozlovic** [comment]
And here is the PR for the doc part: https://github.com/nats-io/nats.docs/pull/259

**Comment by wutkemtt** [comment]
Thanks for the explanation and the pull request. Will try to secure the origin by using the ssl verify feature beneath the authentication.
