### ISSUE TITLE
Feature Request: Description for Streams and Consumers

### ISSUE THREAD

**Issue by typecampo** [nats-io/nats-server#2215]
#### Use Case:
Better support monitoring to determine the the "who" of a stream or consumer.

#### Proposed Change:
Add description fields for stream/consumer. Right now, only Durable consumers/streams have names. Ephemeral consumers show up as random generated names.

#### Who Benefits From The Change(s)?
Everyone

#### Alternative Approaches
Allow naming of ephemeral consumers

**Comment by ripienaar** [comment]
Thanks @typecampo will get this one in, it's been in the back of my mind for a while already

**Comment by typecampo** [comment]
I think I would also like to see named sources too. Instead of hiding the consumer, allow for it to be shown as "this is the consumer for source."

**Comment by ripienaar** [comment]
Yeah that exact feature is what put this in my mind too and not liking the hidden consumers

**Comment by ripienaar** [comment]
https://github.com/nats-io/nats-server/pull/2377
