### ISSUE TITLE
Add option to load server TLS key passphrase from a file (or URL) 

### ISSUE THREAD

**Issue by joelguevara** [nats-io/nats-server#2256]
## Feature Request 
This issue re-opens the original feature request https://github.com/nats-io/nats-server/issues/450. 

#### Use Case:
As a user/administrator, I need to start nats with a TLS certificate and supply the private key's passphrase via configuration (not interactively), because I am using an automated service to configure and start nats.

#### Proposed Change:
Add a configuration option (command-line and config-file), e.g. --tls_password_file to specify a file/URL containing a passphrase (or list of pass phrases) to be used when loading the server certificate key. See for example NGINX's ssl_password_file parameter

#### Who Benefits From The Change(s)?
Any user/organization that wishes to use TLS-secured nats instance(s).

#### Alternative Approaches
The user could create a wrapper script that starts up nats, reads the passphrase from some URL, and supplies the passphrase via redirection of stdin. However, this would be less user-friendly, potentially error-prone, (even) less secure, and may create debugging confusion should things go awry.

**Comment by derekcollison** [comment]
I generally am ok with a practice established by projects like NGINX or HAProxy. However, this feels like we are defeating the whole purpose of the passphrase to increase security. Especially if its a file on same machine, what is the difference?

I get security teams have rules and they wield quite a bit of power but this concerns me.

Looping in our head of security practices though who is much smarter than I on these subjects.

/cc @philpennock

**Comment by philpennock** [comment]
We should not aim to copy every misfeature which exists, and I am pegging this one as an actively dangerous misfeature, sorry.

If you want the passphrase stored on disk, then encrypting the private key is providing a false sense of security and guiding people into harmful practices.  I prefer that we stay honest and just use unencrypted keys on disk, or put work into supporting PKCS11 so as to support HSMs.  This would allow people to use the TPM in a system to protect the encrypted key on disk.

**Comment by joelguevara** [comment]
Closing this request based on feedback
