### ISSUE TITLE
Rename gnatsd 'nats-server'

### ISSUE THREAD

**Issue by mcqueary** [nats-io/nats-server#226]
Includes both the executable and the repo name.

From Derek's Google Groups post:

> When NATS began life back in October of 2010 as a ruby server and client, the server was called nats-server. As NATS moved from a base of Ruby to the Go language in 2012 (Almost exactly 2 yrs apart from the first Ruby commit), we wanted to distinguish the new server and so prefixed it with a 'g' for Go and took a traditional daemon naming approach with a 'd' suffix, hence gnatsd.
> 
> The Ruby server has been deprecated for some time now, and even though we still see some uses of it, I would like to propose moving and renaming gnatsd to nats-server. There will also be some work around the directory structuring to easily embed a server (which is possible today and a pattern we use ourselves) in other Golang programs. Binary releases of the server, which also will change slightly with a top-level directory (instead of just dumping gnatsd, README, LICENSE, etc into CWD), will include a symlink for gnatsd to support backward compatibility for some time.
> 
> Would like feedback on this proposal from the community.

**Comment by derekcollison** [comment]
Not really, docker image will still be nats and will run the server on its own, so no impact.

**Comment by mcqueary** [comment]
This may not work as intended due to restrictions on Go import package names (no hyphens), combined with the restriction that import names must be the same as the actual pathnames under $GOPATH/src.

**Comment by derekcollison** [comment]
Will delay post 0.8.0.

**Comment by aaronjheng** [comment]
Any plans ?

**Comment by derekcollison** [comment]
We have so far decided to leave as is.. Thoughts?

**Comment by aaronjheng** [comment]
I perfer nats-server or natsd personally. I just don't see the meaning of a "g" prefix for Go.

**Comment by vtolstov** [comment]
+1 for nats-server

**Comment by mhilbrunner** [comment]
I prefer gnatsd because "nats" is very hard to google. Even "natsd" gets lots of implicit results for network address translation things. "natsserver" would be fine, but I don't mind gnatsd.

**Comment by derekcollison** [comment]
Server was renamed to nats-server for the v2.0.0.release.

**Comment by baoyachi** [comment]
Changing the name to nats-server is the reason why I am confused about gnatsd's name. I found the answer here. 🍻
