### ISSUE TITLE
hub and spoke setup with JS (with domains) in spokes only do not behave as expected.

### ISSUE THREAD

**Issue by matthiashanel** [nats-io/nats-server#2262]
This is from a user reporting on slack:

hub and two spoke leafnode setup 
I am not sure if cluster or single server, but I suspect single server will be fine.
Single server in hub has no JS enabled.
Each leaf node has JS enabled and it's own unique domain name.

Because the single server in the hub has no JS enabled, the appropriate deny clauses are not inserted.
Therefore each JS operates independently but are reachable through $JS.API.
Which is why when the user creates a stream, it is created in both domains. 

The current workaround was to enable JS in the hub and set a domain name. 
Then everything works as expected.
However, having to enable JS in the hub so that that does not happen seems odd and cumbersome. 

**Potential fix**
I suggest we exchange JS domain names within the cluster/supercluster. (empty counts as well)
On leaf node connections we exchange that name and insert the deny clauses when they differ along a LN connection.

**Comment by derekcollison** [comment]
Will think through this one a bit, thanks for the info..

**Comment by derekcollison** [comment]
Fixed via #2261

**Comment by matthiashanel** [comment]
After a conversation about this we decided to reopen it again.

**Comment by matthiashanel** [comment]
closed accidentally. need to test before doing so
