### ISSUE TITLE
MQTT connect event

### ISSUE THREAD

**Issue by carr123** [nats-io/nats-server#2270]
hello, i recently deployed an mqtt broker based on nats-server. thanks to nats2.2, that's a great work.
is there any way i can get notified when an mqtt client is connected, disconnected ?
thanks.

**Comment by derekcollison** [comment]
The system account will generate advisories for all connect events.

So under account section add in credentials so you can access the system account over a normal NATS connection.

```conf
	accounts {
		# Your accounts here	    
		$SYS { users = [ { user: "admin", pass: "s3cr3t!" } ] }
	}
```

Then use nats cli and subscribe to ">" and see all the activity etc.

**Comment by carr123** [comment]
@derekcollison thanks.
I cretate a sys account to monitor connection events, topic to subscribe :  $SYS.ACCOUNT.*.CONNECT
i indeed received some events.
but there's still some information lack in the json response.

this's the captured events:

{
    "type":"io.nats.server.advisory.v1.client_connect",
    "id":"EQQaY51LaXry0CEPYKspXf",
    "timestamp":"2021-07-31T00:56:39.78182281Z",
    "server":{
        "name":"server1",
        "host":"10.91.22.116",
        "id":"NDUDZ4X4WPUMC4NDMTKEIRXYLL4TYDGUOVVE6YTEBM756LA3VQKHDCO2",
        "cluster":"cluster1",
        "ver":"2.3.2",
        "seq":78976,
        "jetstream":true,
        "time":"2021-07-31T00:56:39.781975899Z"
    },
    "client":{
        "start":"2021-07-31T00:56:39.781281138Z",
        "host":"10.91.52.55",
        "id":72,
        "acc":"MQTTUSER",
        "user":"mqtt_u1",
        "jwt":"123456"
    }
}


this is a concept of "clientid" in mqtt protocal,  currently it's not captured. i need the MQTT clientid to distinguish different devices.
thanks a lot.

**Comment by derekcollison** [comment]
Will loop in @kozlovic who drives most of our MQTT efforts.

**Comment by kozlovic** [comment]
I am re-opening this issue so we can track. I will see if we can add a new field that will be applicable to MQTT clients so that the client_id can be reported.

**Comment by anviod** [comment]
### Online/Offline Notification 
```bash
//  topic:   $SYS/broker/connection/clients/online

w := &mqttWriter{}
mqttWritePublish(w, 0, false, false, "$SYS/broker/connection/clients/online", 0, []byte(cp.clientID))

```

**Comment by kozlovic** [comment]
@anviod Thanks for the comment. However NATS Server support for MQTT does not mean that NATS Server behaves like some other MQTT brokers. For instance, "`$SYS/` has been widely adopted as a prefix to topics that contain Server-specific information or control APIs" to quote the specification, but the specification does not mandate a server to produce such messages.

NATS uses system events already, and I think that we could add to the existing CONNECT/DISCONNECT even the missing client ID as @carr123 requested.

**Comment by carr123** [comment]
@kozlovic  looking forward to new server release.
BTW,  those fields appear in  CONNECT/DISCONNECT events should also show up in  http://xxxxx:8222/connz monitoring endpoints if they could and vice versa.

**Comment by kozlovic** [comment]
> BTW, those fields appear in CONNECT/DISCONNECT events should also show up in http://xxxxx:8222/connz monitoring endpoints if they could and vice versa.

Understood.

**Comment by imranrazakhan** [comment]
@carr123 @kozlovic 
I also deployed NATS with MQTT and it was showing me slow consumer in logs like below

` mid:419588 - Slow Consumer Detected: WriteDeadline of 10s exceeded with 1 chunks of 59500 total bytes.`

To identify slow consumer I tried following

`https://x.x.x.x/connz?state=closed`

As NATS is deployed in Kubernetes, it showed all connection with same IP (10.244.1.1), which is of flannel interface, So its hard to identify consumer/client on base of IP, its good to have clientID available in `/connz` and also we could filter on base of that.

Please let me know if i suppose to create new issue.

```
 {
      "cid": 329382,
      "ip": "10.244.1.1",
      "port": 56378,
      "start": "2021-08-18T10:10:57.462224014Z",
      "last_activity": "2021-08-19T09:20:37.189096215Z",
      "stop": "2021-08-19T09:20:37.895799543Z",
      "reason": "Client Closed",
      "rtt": "0s",
      "uptime": "23h9m40s",
      "idle": "0s",
      "pending_bytes": 0,
      "in_msgs": 8339,
      "out_msgs": 0,
      "in_bytes": 1167460,
      "out_bytes": 0,
      "subscriptions": 0
    },
    {
      "cid": 329386,
      "ip": "10.244.1.1",
      "port": 41310,
      "start": "2021-08-18T10:10:58.367403069Z",
      "last_activity": "2021-08-19T09:20:37.793768877Z",
      "stop": "2021-08-19T09:20:37.793900009Z",
      "reason": "Write Error",
      "rtt": "0s",
      "uptime": "23h9m39s",
      "idle": "0s",
      "pending_bytes": 546,
      "in_msgs": 8762940,
      "out_msgs": 27214330,
      "in_bytes": 2050824659,
      "out_bytes": 6854416639,
      "subscriptions": 9
    },
    {
      "cid": 329390,
      "ip": "10.244.1.1",
      "port": 44164,
      "start": "2021-08-18T10:11:01.741472837Z",
      "last_activity": "2021-08-19T09:20:37.403495776Z",
      "stop": "2021-08-19T09:20:37.405845397Z",
      "reason": "Read Error",
      "rtt": "0s",
      "uptime": "23h9m35s",
      "idle": "0s",
      "pending_bytes": 0,
      "in_msgs": 3950973,
      "out_msgs": 50953956,
      "in_bytes": 284928540,
      "out_bytes": 12983534776,
      "subscriptions": 180
    },
```
