### ISSUE TITLE
Reload programmatically defined options

### ISSUE THREAD

**Issue by mullerch** [nats-io/nats-server#2272]
## Feature Request

Provide a way to dynamically load a new configuration provided programmatically.

#### Use Case:

Same use case a for Server.Reload, but programmatically (without a configuration file).

#### Proposed Change:

Either by providing a Server.Load(Option) or by providing public versions of the options (implementing the hot-swap interface)

In case of a Server.Load(Option), we may have the need of a function to get the full options, as Option must have all its properties set it would be difficult to change only a single option without that.

The option.Reload(Server) version is more specific and therefore probably less error-prone. It also makes sense as when configuration is given programmatically, granularity would generally be higher.

#### Who Benefits From The Change(s)?

nats-server users that don't use a configuration file

**Comment by taigrr** [comment]
This would be extremely helpful for dynamically adding and removing users from the pool. Bumping!

**Comment by derekcollison** [comment]
This might help.

https://github.com/nats-io/nats-server/blob/main/server/client.go#L770

**Comment by taigrr** [comment]
Thanks, @derekcollison . I might be missing something, but client is a private struct, right? So I would still need to modify nats-server code to make use of the referenced function as it's not available from outside. I'm working on a PR right now that provides `server.ReloadOptions(option)` (public) and uses the same logic as the existing `Reload`() function. I will submit it now, without any tests, and plan to update it to include any tests you'd like me to write. (I see there are many for `Reload`, and I'm not sure how many need to be duplicated for `ReloadOptions`)
