### ISSUE TITLE
reload failed for leafnode configuration

### ISSUE THREAD

**Issue by philpennock** [nats-io/nats-server#2273]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [X] Included `nats-server -DV` output
 - [X] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

(Derek said this is a bug and to file a report, during a debugging meeting for another issue)

#### Versions of `nats-server` and affected client libraries used:

* nats-server: `v2.3.0-beta.1`
* client library: whatever @wallyqs was using

#### OS/Container environment:

Ubuntu 20.04 LTS inside systemd

#### Steps or code to reproduce the issue:

```
systemctl kill --signal=HUP jsngs@pennock_cheddar.service
journalctl -u jsngs@pennock_cheddar.service -f
```

#### Expected result:

Debugging output enabled, per @derekcollison 

#### Actual result:

```
Jun 09 15:23:47 ip-10-32-164-190 nats-server[42869]: [42869] 2021/06/09 19:23:47.373862 [ERR] Failed to reload server configuration: config reload not supported for LeafNode: old={ 0    [] 0 <nil> 0 false map[]  false 1s [0xc0000fe3c0] <nil> 0 0 <nil>}, new={ 0    [] 0 <nil> 0 false map[]  false 1s [0xc0000fe320] <nil> 0 0 <nil>}
```

**Comment by wallyqs** [comment]
Likely related to using leafnode remotes
