### ISSUE TITLE
Provide the option to use ed448 when generating nats credentials

### ISSUE THREAD

**Issue by kwtj43** [nats-io/nats-server#2286]
## Feature Request
Provide the option to use ed448 when generating nats credentials

#### Use Case:  
Some companies require more than 128 bits for crypto algorithms.

#### Proposed Change:  
Provide a pure go option to improve the strength of credential files (ex. https://pkg.go.dev/github.com/otrv4/ed448).

#### Who Benefits From The Change(s)? 
Users of nats (security benefit).

**Comment by philpennock** [comment]
Not all "bits" of security are equivalent.  For NATS, wire privacy comes from the use of TLS.  The JWTs are used for identity and signing permissions grants.

I think some degree of algorithmic agility is good to have, proven out.  I'm not sure that Ed448 vs Ed25519 is buying any meaningful degree of extra security in the event of a Break severe enough to make Ed25519 undesirable.

I think Synadia's stance here should be "it's open source, patches welcome" but that it's not a pressing priority for us to spend our resources implementing this.  It's a great way for someone outside Synadia to become a contributor.
