### ISSUE TITLE
JetStream: wrong source name when creating stream causes repeated warning

### ISSUE THREAD

**Issue by kozlovic** [nats-io/nats-server#2307]
- Created a stream "SOURCE"
- Created a stream "DEST" with a source named "Source" (instead of "SOURCE").
- Server reports: `[WRN] JetStream error response for create source consumer: stream not found (10059)` every 6 seconds or so.

Deleting the misconfigured "DEST" stream stops the warning.

/cc @nats-io/core

**Comment by derekcollison** [comment]
This is the correct behavior.
