### ISSUE TITLE
failed test case: TestJetStreamClusterSuperClusterPeerReassign

### ISSUE THREAD

**Issue by dtest11** [nats-io/nats-server#2312]
1. master branch 
2.  TestJetStreamClusterSuperClusterPeerReassign 
https://pipelines.actions.githubusercontent.com/3VXrhR0zc2IgzLOXCwRMCM0ckpumfBkabEvhk9p7TIYNfFhfXE/_apis/pipelines/1/runs/5131/signedlogcontent/3?urlExpires=2021-06-24T17%3A25%3A56.2911031Z&urlSigningMethod=HMACV1&urlSignature=3%2BpCskZvwfzlyT9xo0hDOuMzn%2ByWI4BT9KE8FDY%2Fh%2FA%3D

jetstream_cluster_test.go:4388: Unexpected publish error: nats: no response from stream

maybe `SetGatewaysSolicitDelay(10 * time.Millisecond) ` is not valid

**Comment by derekcollison** [comment]
We see this one flap from time to time, but most of the time passes, especially locally.

On our list to clean up. Thanks.
