### ISSUE TITLE
embedded NATS server

### ISSUE THREAD

**Issue by biskit** [nats-io/nats-server#2319]
hello,
congrats on releasing Jetstream. 

as a current nats-streaming-server user, i embed it https://docs.nats.io/nats-streaming-server/embedding, so can deliver a single binary to my users, alleviating the need to manually install/start/stop/monitor another process.

is such a facility available in NATS 2.0? since NSS starts an internal NATS 1.0 server anyways, I'm guessing it's just missing documentation for 2.0?

thanks!

**Comment by derekcollison** [comment]
JetStream is built into the server itself.

**Comment by biskit** [comment]
i understand -js gets jetstream.
can I do something like
```
stand "github.com/nats-io/nats-streaming-server/server"
s, err := stand.RunServer("mystreamingserver")
```
in my code to run it as a thread in my binary.

**Comment by derekcollison** [comment]
Yes you can embed the server in an application.
