### ISSUE TITLE
embedding NATS server in customer program

### ISSUE THREAD

**Issue by biskit** [nats-io/nats-server#2320]
hello,
I like to embed NATS server in my own program and start as a thread or fork a process and start NATS. This makes one download and demo/eval easy. It was super easy with NATS-Streaming like this https://docs.nats.io/nats-streaming-server/embedding and this:
```
stand "github.com/nats-io/nats-streaming-server/server"
s, err := stand.RunServer("mystreamingserver")
```
can i do same with NATS 2.0.
#2319

**Comment by wallyqs** [comment]
Yes you can do something similar, you can base from example from how it is started in the tests:

```go
import "github.com/nats-io/nats-server/v2/server"

...
o := server.Options{}
o.Host = "127.0.0.1"
o.Port = 4222
o.JetStream = true
o.ServerName = fmt.Sprintf("NODE_%d", i)
tdir, err := ioutil.TempDir(os.TempDir(), fmt.Sprintf("%s_%s-", o.ServerName, clusterName))
if err != nil {
	t.Fatal(err)
}
o.StoreDir = tdir
srv := server.RunServer(&o)
```

https://github.com/nats-io/nats-server/blob/22b60bdbe6baad8b4e73b2916c91397746c89658/server/jetstream_test.go#L84-L91

**Comment by biskit** [comment]
thanks @wallyqs. what I was looking for.
