### ISSUE TITLE
[JS] getLastBySubject functionality doesn't work unless the stream is CREATED with a wildcard subject or multiple subjects

### ISSUE THREAD

**Issue by aricart** [nats-io/nats-server#2329]
## Defect

Using nats-server 2.3.1

If you create a stream with a non wildcard subject, and modify by adding a wildcard subject or another subject, so the resulting stream looks like this:

```javascript
{
  name: "5PYSBLS7BW933CKC49XKBX",
  subjects: [ "5PYSBLS7BW933CKC49XKBX.A", "5PYSBLS7BW933CKC49XKBX.B" ],
  retention: "limits",
  max_consumers: -1,
  max_msgs: -1,
  max_bytes: -1,
  max_age: 0,
  max_msgs_per_subject: 100,
  max_msg_size: -1,
  discard: "old",
  storage: "file",
  num_replicas: 1,
  duplicate_window: 120000000000
}
```
And send a request for the last message on one of the subjects:
```
< PUB $JS.API.STREAM.MSG.GET.5PYSBLS7BW933CKC49XKBX _INBOX.5PYSBLS7BW933CKC49XKEX.5PYSBLS7BW933CKC49XKYF 43␍␊{"last_by_subj":"5PYSBLS7BW933CKC49XKBX.A"}␍␊
```

The server will respond with the last message on the stream:
```
> MSG _INBOX.5PYSBLS7BW933CKC49XKEX.5PYSBLS7BW933CKC49XKYF 1 237␍␊{"type":"io.nats.jetstream.api.v1.stream_msg_get_response","message":{"subject":"5PYSBLS7BW933CKC49XKBX.B","seq":4,"hdrs":"TkFUUy8xLjANCk5hdHMtRXhwZWN0ZWQtTGFzdC1TZXF1ZW5jZTogMw0KDQo=","data":"YmI=","time":"2021-06-30T13:42:15.979551Z"}}␍␊
```

This functionality works correctly if the stream is created with more than one subject or with a wildcard.

**Comment by derekcollison** [comment]
Update to a multi-subject tracked stream is what does not work. If you start a file stream currently with a single non-wildcard subject we setup the underlying filestore to not track.  When you update to introduce more subjects we do not update the filestore to track.

Will fix.
