### ISSUE TITLE
Nat (jestream) can't create consumer for subject with 3 or more sub subjects

### ISSUE THREAD

**Issue by kamilgregorczyk** [nats-io/nats-server#2342]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

docker setup for faulty version:

```
version: "3"
services:
  jet-stream:
    image: nats:alpine3.14
    command: --js --cluster_name jet-stream
    ports:
      - 4222:4222
```

#### Steps or code to reproduce the issue:

Create stream

```nats str add DomainEvents --subjects "domainEvents.*" --ack --max-msgs=-1 --max-bytes=-1 --max-age=1y --storage file --retention limits --max-msg-size=-1 --discard=old```

Create consumer with filter `domainEvents.User.UserCreatedEvent` which does not work: 
```nats con add DomainEvents NEW --filter domainEvents.User.UserCreatedEvent --ack explicit --pull --deliver all --max-deliver=-1 --sample 100```

Im getting:
```nats: error: Consumer creation failed: consumer filter subject is not a valid subset of the interest subjects```

this works (filter `domainEvents.User`:
```nats con add DomainEvents NEW --filter domainEvents.User --ack explicit --pull --deliver all --max-deliver=-1 --sample 100```

I could get away by creating a consumer with just `User.UserCreatedEvent` but I wanted to use `domainEvents.*` in the stream  setup so I wouldn't have to collect all the variations of the subjects that could go under that stream, in other words, I would need to have a statically defined list of all the possible subjects like `User.UserCreatedEvent` `User.UserSomeFieldUpdatedEvent` in the stream config which is not possible due to dynamic way of creating new models. Doing `domainEvents.*` would solve that issue for me

**Comment by ripienaar** [comment]
The error is correct because x.* matches only x.y, x.z etc not x.y.z

you want to use x.> in the stream to match any level below x

**Comment by kamilgregorczyk** [comment]
Thanks, will try!

**Comment by kamilgregorczyk** [comment]
works perfectly! had some issues because of already created consumers in wrong configuration but after recreating the stream it worked as expected, thanks for fast response
