### ISSUE TITLE
Question: Jetstream cluster per kubernetes namespace

### ISSUE THREAD

**Issue by ddseapy** [nats-io/nats-server#2343]
is it possible to deploy multiple jetstream clusters (each in it's own namespace)?  looking at the nack helm chart it asks for a single nats url and asks for cluster-wide access (https://github.com/nats-io/k8s/blob/master/helm/charts/nack/templates/rbac-jetstream-controller.yml).

if possible I'm wanting to declare CRDs cluster-wide and let each namespace deploy their own NATS jetstream cluster.

if this is possible, is it desired to run the jetsream controller cluster-wide with the ClusterRole/ClusterRoleBinding and somehow specify multiple url's for the jetstream clusters?  Or should the jetstream controller be installed in each namespace with Role/RoleBindings && is there a flag to tell the controller to just look in it's own namespace for resources it watches?

it looks like nats-operator is similar to what i'm looking for, but doesn't appear it supports jetstream clusters yet 
` If looking for JetStream support, this is currently only available in the Helm charts`
(https://github.com/nats-io/nats-operator#nats-operator)

**Comment by ddseapy** [comment]
Closing, as this is more of a nack question.  but looks like it might be hardcoded: https://github.com/nats-io/nack/blob/32a9813d1f7f21f36969e0c55b707370659d2656/pkg/jetstream/generated/informers/externalversions/factory.go

**Comment by derekcollison** [comment]
JetStream is a system wide service per NATS domain but each account can enable and limit as it sees fit. 

When you create multiple NATS domains using leafnodes you also can create multiple JetStream domains that are accessible via any connection point in the extended system.

This video can help with those concepts and what is possible. @wallyqs can help with the K8S integration and our Helm chart.

https://www.youtube.com/watch?v=0MkS_S7lyHk
