### ISSUE TITLE
Allow clients with nkeys to authentication without declaring all of them in config

### ISSUE THREAD

**Issue by playerx** [nats-io/nats-server#2358]
Hello, We're building B2C product and plan to connect all client devices (mobile apps & browsers) to the nats server (via ws).

## Config
`nats.config` looks like this:
```
websocket {
  port: 8080
  no_tls: true
}

accounts: {
  JOK: {
    default_permissions = {
      publish = ["hello"]
      subscribe = ["_INBOX.>"]
    }

    users: [
      {
        user: public,
        password: '123',
        permissions: {
          publish = ["hello"]
          subscribe = ["_INBOX.>"]
        }
      },

      {
        user: micro,
        password: '1234',
        permissions: {
          publish = ">"
          subscribe = ">"
        }
      }

      {
        # EZ - Admin
        nkey: 'UBB526E4CQQUPTXNPW4WW6PFIPRQGHTCD7WICVB4NK3SZTEUZMWKSOHK',
        permissions: {
          publish = ">"
          subscribe = ">"
        }
      }
    ]
  }
}

system_account: JOK
no_auth_user: public
```

## Listening events
It's important for us to catch client connected & disconnected events on the server, so JOK is a system_account and we use command:
```
nats --user micro --password 1234 sub "\$SYS.ACCOUNT.JOK.>" 
```
To receive `$SYS.ACCOUNT.JOK.CONNECT` and `$SYS.ACCOUNT.JOK.DISCONNECT` messages

## Client app
client app uses nkeys & generates new key pair. The code looks something like this:
```
const kp = nkeys.createUser()
const seed = kp.getSeed()

const nc = await connect({
  servers: ['ws://localhost:8080'],
  authenticator: nkeyAuthenticator(seed),
})
```
We use nkeys to have an unique id (public key) for each connection, which will be known:
*  on the client side before the connection will be started
* on the server side events `CONNECT` and `DISCONNECT`, we read this data from the message content: `client.user`

## Problem
`no_auth_user: public` has no effect when we use unique nkeys. nats returns `Authorization Violation`. On the other hand it's impossible for us to register all client nkeys in server config, because it's B2C app.

Authentication works:
* If we don't use authentication at all
* If we use public user credentials

But in this case we don't have an unique string sent from the client app to the nats server, which we will receive on `CONNECT` and `DISCONNECT` events. `CONNECT` & `DISCONNECT` event for all client client app connections looks the same and we didn't find the way to provide some extra data to identify somehow which user's session was disconnected.

## Questions
As I've checked in the documentation nkeys can't be used with `no_auth_user`, so my question will be:
* Is it something that will be changed in the future to support such case scenario: to have unknown connections from the ws and to identify them individually by nkeys (public keys)? // I think it will be really powerful feature for nats server
* Is there any way to identify each ws connection by some unique id, which will be known on the client side as well? And to receive this unique id in `CONNECT` and `DISCONNECT` events?

🤔

**Comment by playerx** [comment]
After checking the data I found this:

Client-side:
```
nc.protocol.info.client_id
```

Server-side (`$SYS.ACCOUNT.JOK.CONNECT`):
```
msg.client.id
```

I think those two are the same, only problem I see is that it has `integer` value and I don't know if I can rely on it, can I be sure that it will be unique always?

**Comment by aricart** [comment]
have you looked at authenticating with JWT?

**Comment by aricart** [comment]
@playerx I just connected this issue with our discussion in slack. The main issue here is that nkey authentication is intended as a user/name password replacement, where the identity of the client is proven on connecting since the client has to demonstrate possession of his user key. The other downside as you point out is that it is not a distributed configuration, so the server configuration would need to be aware of all possible users.

I think the solution is to really understand that NATS authentication at this scale is not the nats-server issuing permissions or collaborating on this, but rather enforcing some external system that vouches for you and provides the authentication token that you can use. Since the number of clients is not clamped, this means you have to use decentralized authentication, and that rolls you back in to JWT.

**Comment by aricart** [comment]
> Client-side:
> 
> ```
> nc.protocol.info.client_id
> ```

This is simply a local identifier for the connection.

**Comment by playerx** [comment]
Hi @aricart, thanks for feedback, it was really useful. I've tried JWT authentication and it works great!

Here is the configuration I use now:
```
websocket {
  port: 8080
  no_tls: true
}

// Operator "Test Operator"
operator: eyJ0eXAiOiJqd3QiLCJhbGciOiJlZDI1NTE5In0.eyJqdGkiOiJaT08yUTRDUUcyNlpURUZDQkxFQVlEVTZZTFNLNkFLNTc2QVpQQTdXQVlCTzQyM1RTTEVBIiwiaWF0IjoxNjI2MTYzNzM2LCJpc3MiOiJPQ1QzWUFHS09NSlVOQkdGVTY0UEVVSlBIWEpXTERYTVpYVzRRV1A1VjdSSVRFNTM0SFlWSTRCRSIsIm5hbWUiOiJUTyIsInN1YiI6Ik9DVDNZQUdLT01KVU5CR0ZVNjRQRVVKUEhYSldMRFhNWlhXNFFXUDVWN1JJVEU1MzRIWVZJNEJFIiwidHlwZSI6Im9wZXJhdG9yIiwibmF0cyI6e319.Ld2vpfuAAmdiX0VAK571nxYQUDcFFmrr9z1b538lqQYjyxYRdtqFFRj1WUzUi8_UyXVjVQvIIajPN_ySghDhBg

resolver: MEMORY

resolver_preload: {
  // Account "Test Account"
  AC6HQT6NUX5LVVQTN5GVMYBR7SLVNWF3IJ7QNPZ4ZVXARPY5BLRSQ4I7: eyJ0eXAiOiJqd3QiLCJhbGciOiJlZDI1NTE5In0.eyJqdGkiOiJPU1VNR0VGS09KWFBPVENYNTJDRzdGNFdXQjVDVDNRVU1MQzRBUlBDSkJCVVFGVVU1Tk5BIiwiaWF0IjoxNjI2MTYzOTA4LCJpc3MiOiJPQ1QzWUFHS09NSlVOQkdGVTY0UEVVSlBIWEpXTERYTVpYVzRRV1A1VjdSSVRFNTM0SFlWSTRCRSIsIm5hbWUiOiJUQSIsInN1YiI6IkFDNkhRVDZOVVg1TFZWUVRONUdWTVlCUjdTTFZOV0YzSUo3UU5QWjRaVlhBUlBZNUJMUlNRNEk3IiwidHlwZSI6ImFjY291bnQiLCJuYXRzIjp7ImxpbWl0cyI6eyJzdWJzIjotMSwiY29ubiI6LTEsImxlYWYiOi0xLCJpbXBvcnRzIjotMSwiZXhwb3J0cyI6LTEsImRhdGEiOi0xLCJwYXlsb2FkIjotMSwid2lsZGNhcmRzIjp0cnVlfX19.6pjb9t82exHbVegIHJCTwkFcGnxi04a33keY3sSUzQuVJvEIt3eZHHIndxYkrE7GzyiBKMm1w9KAXlJmsXLEDA
}

system_account = AC6HQT6NUX5LVVQTN5GVMYBR7SLVNWF3IJ7QNPZ4ZVXARPY5BLRSQ4I7
```

I create and sign jwt in nodejs process, on the fly. There was one problem `jsonwebtoken` doesn't support `ed25519`, so I created one [function](https://gist.github.com/playerx/4f2e41a4376ac72ae9e352baa2a19ae8) for signing and creating full jwt, based on your repo (https://github.com/nats-io/jwt).

Here is one last problem which will be great to be solved and nats will be perfect solution!

## Problem
Authentication with JWT works, also I set userId in JWT and I receive full jwt in `CONNECT` & `DISCONNECT` events. Everything is OK here. Problems starts when I receive individual messages from this authenticated connection:

I've code like this to listen messages in the micro service:
```ts
this.nc.subscribe(route, {
  callback: async (err, msg) => {
    if (err) {
      return
    }

    // here I need to get browser client's public key & full jwt token to extract userId
  }
})
```
In theory `nats-server` has the data about publisher's access token and I should be able to read it from `msg` variable somehow, but I didn't find the way for it.

The only thing I found is: `msg.publisher?.options?.authenticator()`, but it returns micro-service's user information, not browser's one.

Right now I have a workaround to send the same JWT as a part of every message, next validate it after receiving and next extract the information I need. But I don't like this workaround because it takes more traffic and more CPU time on every message.

Can you share if there is the way to read browser client's JWT token from the msg variable? or at least browser client's public key?

🤔

**Comment by anupriya17** [comment]
I came up with using headers until message supports browser info.

https://github.com/nats-io/nats.ws#headers

**Comment by playerx** [comment]
@anupriya17 I've solved the problem without headers. @derekcollison 's commend helped me: https://github.com/nats-io/nats-server/issues/1173#issuecomment-548090412

The way it works now:
I add `userId` and `sessionId` in the route like this:

```js
route:
`app.joker.command.join.${userId}.${sessionId}`
```

and user has permission like this in JWT:
```ts
{
   ...
        nats: {
          pub: {
            allow: isAdmin
              ? ['>']
              : [
                  `app.*.command.*.${userId}.${sessionId}`,
                  `app.*.command.*.*.${userId}.${sessionId}`,
                  `app.*.command.*.*.*.${userId}.${sessionId}`,
                  `app.*.query.*.${userId}.${sessionId}`,
                  `app.*.query.*.*.${userId}.${sessionId}`,
                  `app.*.query.*.*.*.${userId}.${sessionId}`,
                ],
          },
          sub: {
            allow: isAdmin
              ? ['>']
              : [
                  `channel.everyone.>`,
                  `channel.JOKER.>`,
                  `channel.${publicKey}.>`,
                  `channel.${userId}.>`,
                  `app.*.event.>`,
                  '_INBOX.>',
                ],
          },
}
```

This way I can always be sure that last two parts from the subject are userId and sessionId always, and user can't cheat.

Another user can't use my sessionId because he will need JWT with that sessionId as well and he can get it only from my api. He can't change his JWT because signature will become invalid this way.

It looks perfect this way, it took some time but now I'm happy and closing the issue :) It will be great to have a section about it somewhere in the JWT authentication doc page ✌🏻

**Comment by derekcollison** [comment]
Looks good. Minor note, by default permissions are wide open, so technically no need for `allow: [">"]`, that is the default mode.

Cheers..

**Comment by anupriya17** [comment]
> @anupriya17 I've solved the problem without headers. @derekcollison 's commend helped me: [#1173 (comment)](https://github.com/nats-io/nats-server/issues/1173#issuecomment-548090412)
> 
> The way it works now: I add `userId` and `sessionId` in the route like this:
> 
> ```js
> route:
> `app.joker.command.join.${userId}.${sessionId}`
> ```
> 
> and user has permission like this in JWT:
> 
> ```ts
> {
>    ...
>         nats: {
>           pub: {
>             allow: isAdmin
>               ? ['>']
>               : [
>                   `app.*.command.*.${userId}.${sessionId}`,
>                   `app.*.command.*.*.${userId}.${sessionId}`,
>                   `app.*.command.*.*.*.${userId}.${sessionId}`,
>                   `app.*.query.*.${userId}.${sessionId}`,
>                   `app.*.query.*.*.${userId}.${sessionId}`,
>                   `app.*.query.*.*.*.${userId}.${sessionId}`,
>                 ],
>           },
>           sub: {
>             allow: isAdmin
>               ? ['>']
>               : [
>                   `channel.everyone.>`,
>                   `channel.JOKER.>`,
>                   `channel.${publicKey}.>`,
>                   `channel.${userId}.>`,
>                   `app.*.event.>`,
>                   '_INBOX.>',
>                 ],
>           },
> }
> ```
> 
> This way I can always be sure that last two parts from the subject are userId and sessionId always, and user can't cheat.
> 
> Another user can't use my sessionId because he will need JWT with that sessionId as well and he can get it only from my api. He can't change his JWT because signature will become invalid this way.
> 
> It looks perfect this way, it took some time but now I'm happy and closing the issue :) It will be great to have a section about it somewhere in the JWT authentication doc page ✌🏻

Thanks and we ended up similar as well and we use headers for meta data
