### ISSUE TITLE
Subscriptions to streams which are imported with a wildcard subject and a prefix do not work correctly

### ISSUE THREAD

**Issue by DamianoChini** [nats-io/nats-server#2361]
## Defect
In Accounts configuration, if I import a stream from another account, with a subject containing a wildcard and any prefix, subscribers that subscribe to a subject respecting the prefix combined with the wildcard, do not receive any message.
In particular, given an import like the following `{stream: {account: ACCOUNT_X, subject: > }, prefix: myprefix}`, subscribers using a subject which is constructed with `*` instead of `myprefix` and any string instead of `>` (e.g. `*.test`) seem to not receive any message.

#### Versions of `nats-server` and affected client libraries used:
nats-server: v2.3.2

#### OS/Container environment:
CentOS Linux release 7.9.2009 (Core)

#### Steps or code to reproduce the issue:
1. Use this nats-server accounts configuration 
```
accounts: {
  ACCOUNT_X: {
    users: [
      {user: publisher}
    ]
    exports: [
      {stream: >}
    ]
  },
  ACCOUNT_Y: {
    users: [
      {user: subscriber}
    ]
    imports: [
      {stream: {account: ACCOUNT_X, subject: > }, prefix: myprefix}
    ]
  }
}
```
2. Configure a nats client with username `subscriber` to subscribe to `*.testsubject`
3. With a nats client with username `publisher`, publish a message on the subject `testsubject`

#### Expected result:
I expect that `subscriber` receives the event published by `publisher`

#### Actual result:
The subscriber does not receive any message

**Comment by matthiashanel** [comment]
I can reproduce the issue. 

These subjects work: `>`, `myprefix.*`, `myprefix.>`, `myprefix.test`, `*.>`
These don't: `*.*`, `*.test`

**Comment by matthiashanel** [comment]
The issue happens in `addShadowSubscriptions`, where the subject of the subscriber is compared with the import subject `myprefix.>` (both ways).
`>` is NOT Subset of `myprefix.>` but IS subset the other way around.
`myprefix.*` is subset of `myprefix.>`
`myprefix.>` is identical to (subset of) `myprefix.>`
`myprefix.test` is subset of `myprefix.>`
`*.>` is NOT subset of `myprefix.>` but IS subset the other way around

`*.*` is NOT subset of `myprefix.>` but is NOT subset the other way around either
`*.test` is NOT subset of `myprefix.>` but is NOT subset the other way around either
