### ISSUE TITLE
Not Acking a message before Purging stream prevents redeliver of subsequent Non acked message for consumer

### ISSUE THREAD

**Issue by sloveridge** [nats-io/nats-server#2392]
## Defect
Following issue was reported on slack:

> whenever I purge the stream and publish a message on the stream then a consumer gets a message only once even if I did not send ack signal. Before I purge, stream and consumer act as I expected. But whenever I do as following, a consumer cannot get the same message more than once. 
pub message --> sub (no ack) --> purge stream --> pub message --> sub(no ack) --> wait for ack wait time --> sub(no ack) << cannot get message
When I check the stream there is still 1 message but consumer just can’t get that message

Go code to reproduce this behaviour below.

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x ] Included `nats-server -DV` output
 - [x ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:
Version:  2.3.3-beta
Git:      [19bfef59]
Go build: go1.16.6

Tested with github.com/nats-io/nats.go v1.11.1-0.20210714175522-2b2bb8f326df

#### OS/Container environment:
Using synadia/nats-server:nightly

#### Steps or code to reproduce the issue:
```
package main

import (
	"fmt"
	"github.com/nats-io/nats.go"
	"time"
)

func main() {
	nc, _ := nats.Connect(nats.DefaultURL)
	defer nc.Drain()
	js, _ := nc.JetStream()
	fmt.Println("\n-- Ack Before Purge --")
	test(js, true)
	fmt.Println("\n-- No Ack Before Purge --")
	test(js, false)
}

func test(js nats.JetStreamContext, ack bool) {
	js.AddStream(&nats.StreamConfig{
		Name:     "foo",
		Subjects: []string{"foo.*"},
	})
	defer js.DeleteStream("foo")
	js.Publish("foo.a", []byte("show once"))
	sub, _ := js.SubscribeSync("foo.*", nats.AckWait(2*time.Second), nats.DeliverAll(), nats.AckExplicit())
	defer sub.Unsubscribe()
	next(sub, ack) // No ack / nack here is the issue
	js.PurgeStream("foo")
	fmt.Println("*Stream Purged*")
	js.Publish("foo.a", []byte("show twice"))
	next(sub, false)
	next(sub, false)
}


func next(sub *nats.Subscription, ack bool) {
	m, err := sub.NextMsg(5 * time.Second)
	ci, _ := sub.ConsumerInfo()
	if err == nats.ErrTimeout {
		fmt.Printf("should not see (Ack Pending: %d)\n", ci.NumAckPending)
	} else {
		if ack {
			m.Ack()
		}
		fmt.Printf("%s (Ack Pending: %d)\n", m.Data, ci.NumAckPending)
	}
}
```

#### Expected result:
Message published after purge should be redelivered after ack wait when not acknowledged

-- Ack Before Purge --
show once (Ack Pending: 1)
*Stream Purged*
show twice (Ack Pending: 1)
show twice (Ack Pending: 1)

-- No Ack Before Purge --
show once (Ack Pending: 1)
*Stream Purged*
show twice (Ack Pending: 1)
show twice (Ack Pending: 1)

#### Actual result:
Message published after purge **NOT** being redelivered after ack wait when not acknowledged

-- Ack Before Purge --
show once (Ack Pending: 1)
*Stream Purged*
show twice (Ack Pending: 1)
show twice (Ack Pending: 1)

-- No Ack Before Purge --
show once (Ack Pending: 1)
*Stream Purged*
show twice (Ack Pending: 1)
should not see (Ack Pending: 1)

**Comment by derekcollison** [comment]
Thanks for the excellent detailed info, much appreciated! Will take a look.
