### ISSUE TITLE
is there a way to check account dynamically ?

### ISSUE THREAD

**Issue by carr123** [nats-io/nats-server#2398]
i have a legacy MQTT project. recently i try to replace it using nat-server MQTT broker.
the mqtt user and password are not constant. they contain timestamps. on the server side, user & password are checked by a special algorithm.
so, is there anyway to check nats account/password programably ?
thanks.

**Comment by kozlovic** [comment]
@carr123 If I understand correctly, your MQTT application provides "random" user name and passwords. By random I mean that there are some part of it that are timestamps as you said, so you would not be able to create a finite list of users in the NATS Server config that would be allowed to connect. Is that correct? (If so, I wonder how you were doing with your previous MQTT broker)

If my understanding is correct, then the only way to "dynamically" check authorization would be for you to repackage the NATS Server running as a go routine and provide a CustomClientAuthentication option. There is a test in the server that demonstrates how to use it: https://github.com/nats-io/nats-server/blob/fd9e9480dad9498ed8109e659fc8ed5c9b2a1b41/server/server_test.go#L612

**Comment by carr123** [comment]
@kozlovic Yes, that's exactly what i want.
do you mean that i need to build my own nats-server binary with CustomClientAuthentication method to replace the official release ?

**Comment by kozlovic** [comment]
@carr123 Correct. Any "personalized" code to decide if a username is allowed to connect need to be done from an embedded version where you can run your own authentication code.
