### ISSUE TITLE
When dealing with accounts or domains, a single ACK can acknowledge multiple messages.

### ISSUE THREAD

**Issue by matthiashanel** [nats-io/nats-server#2402]
across accounts as well as domains, stream and durable names can be duplicated. 
Furthermore $JS.ACK.> is not bound to a domain/api prefix. 
Therefore the information provided when acking is not sufficient. 
Furthermore this may cause excess traffic.

Ideally this would be moved under $JS.API.>

Alternatives:
1) we add the denies to be `$JS.>` instead of `$JS.API.>` and add a mapping `$JS`->`$JS.<domain>`. This would effectively freeze API as part of the prefix. It would break installations where ppl altered the prefix to not end in API. 
This is a guess, but so far I wouldn't expect this to happen often. 

2) Or add more denies and mappings similar to what `$JS.API` does to `$JS.ACK`. just for `$JS.ACK` -> `$JS.<domain>.ACK.>`
I assume this needs to be done for `$JS.FC` as well as `$JS.SNAPSHOT.` 
For `$JS.EVENT.` we may need a deny only, but not mapping as this is a stream and not a service.

In either case clients would have to start using the api prefix for acks/fc as well.

**Comment by derekcollison** [comment]
$JS.API.> is a global export, so putting it under there force it through that path. We do have an exception to this that we handle for GetNextMsg() for pull subscribers, so not impossible, but need to be careful.

If we did move it under $JS.API without and domain mangling at that level, I am not sure that is enough.. Need to think about it some more.

**Comment by derekcollison** [comment]
Also if we change number of tokens all clients will need to be update to parse the msg metadata. Not saying this is a reason not to do it, just something we need to consider.

**Comment by matthiashanel** [comment]
I just realized that the following may have issues, but perhaps it give you and idea?

I wouldn't mess with the tokens or rearrange them in any way.
I would alter what the API prefix is from `$JS.API` to `$JS` 
Thus when domains are used the new prefix would be `$JS.<domain>`

In the server, I would also change the mapping from `$JS.API.>` <--> `$JS.<domain>.API.>` to `$JS.>` <--> and `$JS.<domain>.>` (hope that works as it is technically still covered by deny, so perhaps we'd need more specific deny clauses)
In the server, Instead of denying, `$JS.API.>`, I would add more denies for `$JS.API.>.` `$JS.ACK.>.` , `$JS.SNAPSHOT.>.` 

Clients would have to strip API if provided as last token from the prefix.
All calls, including ack would get the new prefix.

**Comment by bruth** [comment]
Closing given #2411 was stated as a fix.
