### ISSUE TITLE
User authorization in leafnode connection doesn't work in v2.3.4

### ISSUE THREAD

**Issue by wchajl** [nats-io/nats-server#2415]
## Defect
+  user authorization doesnt work in leafnode connection when account(created by nsc) in central cluster has jetstream enabled.
+  after I changed my image from `nats:2.3.4-alpine` to `nats:2.2.6-alpine3.13` ,it backs to work
 - [ ] Included `nats-server -DV` output
 - [ ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:
docker image : nats:2.3.4-alpine
natscli : the latest dev version 

#### OS/Container environment:
Linux mpc-ubuntu-server 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
#### Steps or code to reproduce the issue:
![EMU`D04KL{GA9Q16W})P DF](https://user-images.githubusercontent.com/42642319/128327447-95e39dc9-e31c-4c5f-bc7c-9e41ec5393b0.png)

1. use nsc to create 3 accounts as follow ,and each account has 4 users.
```
a: {
   jetstream:enable
   users:[
   {a1,deny-pubsub:test.a1},
   {a2,deny-pubsub:test.a2},
   {a3,deny-pubsub:test.a3},
   {a4,deny-pubsub:test.a4},
   ]
}

b: {
   users:[
   {b1,deny-pubsub:test.b1},
   {b2,deny-pubsub:test.b2},
   {b3,deny-pubsub:test.b3},
   {b4,deny-pubsub:test.b4},
   ]
}

c: {
   jetstream:enable
   users:[
   {c1,deny-pubsub:test.c1},
   {c2,deny-pubsub:test.c2},
   {c3,deny-pubsub:test.c3},
   {c4,deny-pubsub:test.c4},
   ]
}
```

2. establish a central cluster of 3 nodes.each node uses nats-based-resolver and preload the accounts above.
3. deploy 4 leafnodes(leaf1~leaf4) connecting to the central cluster . each node has three account named A,B,C 
```
leafnode connection :
leaf1 
A->a1->a
B->b1->b
C->c1->c

leaf2
A->a2->a
B->b2->b
C->c2->c
....
```
4. use client1 to sub test.a1 in leaf1(account :A) while client2 to pub msg to test.a1 in leaf2(account:A)
5. use client3 to sub test.b1 in leaf1(account :B) while client4 to pub msg to test.b1 in leaf2(account:B)
6. use client5 to sub test.c1 in leaf1(account :C) while client6 to pub msg to test.c1 in leaf2(account:C)

#### Expected result:
client1,3,5 can't receive msg sent by client2,4,6

#### Actual result:
client 2,4,6 successed  to pub msg 
client1,5 received the msg sent by client 2,6
client 3 cant receive msgs sent by client 4

**Comment by wchajl** [comment]
I write a docker-compose to deploy this .

**Comment by wchajl** [comment]
I write a docker-compose to deploy this .
[test.tar.gz](https://github.com/nats-io/nats-server/files/6937550/test.tar.gz)

**Comment by matthiashanel** [comment]
@wchajl I can reproduce the issue have an idea where this may be coming from. 

The issue can be boiled down to two server.
Server HUB, in operator mode, accepts leaf node connections.
Server LEAF, has a configured account A and has a remote for A to Server HUB, using credentials with a deny pub/sub clauses.

When this trace is present in LEAF (triggered by JS enabled), the deny pub/sub clauses does not take effect. 
```
[15184] 2021/08/09 10:51:00.550881 [INF] Adding deny export of "$JS.API.>" for leafnode configuration on "A" that bridges system account
```

**Comment by wchajl** [comment]
@matthiashanel
Get it , I have retried this with v2.3.0 ,it doesn't take effect as well.  But it works in v2.2.6,  may be it's related to the merge `Changes to leafnodes and JetStream #2261`  ?  is this a bug or we can't use the deny pub/sub clause like this ? thanks!

v2.2.6
```
[1] 2021/08/10 01:31:50.687274 [INF] Adding deny export of "$JS.API.>" for leafnode configuration on "A" that bridges system account
[1] 2021/08/10 01:31:50.687280 [INF] Adding deny import of "$JS.API.>" for leafnode configuration on "A" that bridges system account
[1] 2021/08/10 01:31:50.687298 [DBG] 172.19.0.7:7422 - lid:9 - Authenticating with credentials file "/nats/creds/a.creds"
[1] 2021/08/10 01:31:50.687865 [DBG] 172.19.0.7:7422 - lid:9 - Remote leafnode connect msg sent
[1] 2021/08/10 01:31:50.692012 [DBG] 172.19.0.7:7422 - lid:9 - Not permitted to import service $JS.API.> on behalf of A/
[1] 2021/08/10 01:31:50.692022 [DBG] 172.19.0.7:7422 - lid:9 - Not permitted to subscribe to $JS.API.> on behalf of A/
```
reply in leaf1 with creds a1
```
houston@mpc:~$  nats -s nats://a1:a1@localhost:17422 reply test.a1  msg_from_leaf1_a1
09:44:00 Listening on "test.a1" in group "NATS-RPLY-22"


```

request in leaf2 with creds a2 
```
houston@mpc:~$ nats -s nats://a1:a1@localhost:27422 req test.a1 msg_from_leaf2_a2
09:34:03 Sending request on "test.a1"
nats: error: nats: no responders available for request, try --help
``` 

v2.3.4
```
[1] 2021/08/10 01:46:09.655652 [INF] Adding deny export of "$JS.API.>" for leafnode configuration on "A" that bridges system account
[1] 2021/08/10 01:46:09.655669 [DBG] 172.21.0.6:7422 - lid:7 - Authenticating with credentials file "/nats/creds/a.creds"
```
reply in leaf1 with creds a1
```

houston@mpc:~$  nats -s nats://a1:a1@localhost:17422 reply test.a1  msg_from_leaf1_a1
09:47:43 Listening on "test.a1" in group "NATS-RPLY-22"
09:47:47 [#0] Received on subject "test.a1":

msg_from_leaf2_a2
09:47:47 cnt: 0
09:47:49 [#1] Received on subject "test.a1":

msg_from_leaf2_a2
09:47:49 cnt: 1
```

request in leaf2 with creds a2 
```
houston@mpc:~$ nats -s nats://a1:a1@localhost:27422 req test.a1 msg_from_leaf2_a2
09:47:47 Sending request on "test.a1"
09:47:47 Received on "_INBOX.tOrqXcs5JTIEzNoFHfzoSJ.MBirBSO1" rtt 2.390445ms
msg_from_leaf1_a1

houston@mpc:~$ nats -s nats://a1:a1@localhost:27422 req test.a1 msg_from_leaf2_a2
09:47:49 Sending request on "test.a1"
09:47:49 Received on "_INBOX.ygp841sC3vsFQTnEHKqC8u.GgqQ2EVO" rtt 1.788151ms
msg_from_leaf1_a1
```

**Comment by matthiashanel** [comment]
@wchajl I made the initial change that took permissions stored in user jwt into account. This is why in even earlier versions it is not working either. This change was subsequently undone when we set JetStream permissions, and thus erasing existing ones, instead of merging them. But I have a PR out and expect it to land soon.
