### ISSUE TITLE
MQTT: support MQTT over WebSocket

### ISSUE THREAD

**Issue by Etran-H** [nats-io/nats-server#2433]
#### Proposed Change:
support http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718127
`mqtt {
    port: 1883
    ws_port: 9001
}`

#### Who Benefits From The Change(s)?
The web application does not support native TCP connection. 
MQTT over WebSockets allows you to receive MQTT data directly into a web browser.

**Comment by kozlovic** [comment]
Closed with #2735
