### ISSUE TITLE
Question: sharding based on subject

### ISSUE THREAD

**Issue by pananton** [nats-io/nats-server#2440]
Hello! Can you please tell me whether nats-server supports sharding by message subject? Looks like it does not so the second question is whether there is a plan to add shrading support in the future? Or may be alternative way exists to simulate sharding somehow for subscriptions to the same subject?

**Comment by derekcollison** [comment]
If you want to scale out the applications that can process messages yes that is supported and is called queue groups.

https://docs.nats.io/developing-with-nats/receiving/queues

Also NATS servers can form any topology from a single server, to a local cluster, to a geo diverse super cluster and you can extend any of those with leafnodes to mix and match SaaS and owned and operated. Queue groups work on all configurations and do not need any changes to server configs, all application controlled.

**Comment by pananton** [comment]
Queue group is not the same as sharding AFAIK because it chooses subscriber randomly for each matching message. By sharding I mean that message goes to a dedicated subscriber in a group. Of course this requires some identifier in message which is used to determine node responsible for processing messages with this id (most primitive way is to use `id mod N ` where N is number of shards).

**Comment by pananton** [comment]
Currently client libraries can be used to set custom header fields in NATS message. Probably one way to implement such sharding can be to provide well-known header storing message id and use it to determine subscriber to which all messages with this id should be sent.

**Comment by ripienaar** [comment]
At present we have no feature what can do what you want seamlessly. We are working on something but it’s very early phase you can see here https://github.com/nats-io/nats-architecture-and-design/pull/36 there is no implementation or ETA

for now I suggest you calculate your share at publish time and put a shard token in tbe subject. This way you can have multiple subscribers each always getting the same shard. By no means perfect but that’s about the best option for the moment

**Comment by pananton** [comment]
Thanks, I'm already working on the solution. Ask you because I was worried that official solution can soon (in several month) become available (but if I understood correctly it is not).

**Comment by ripienaar** [comment]
I think "several month" accurately describes a realistic expectation for when it might land fully complete, though this is a very commonly requested feature

**Comment by derekcollison** [comment]
Say you have a stream, and it has subjects "foo" and "bar" and "baz".

You can create a consumer that filters by subject, say "bar", you can then attach queue subscribers (NATS core queue subscribers) to process all messages in the stream with a subject of "bar" with only members from the group attached to the consumer filtering on "bar".
