### ISSUE TITLE
MQTT duplicated message received

### ISSUE THREAD

**Issue by carr123** [nats-io/nats-server#2447]
i perform some  mqtt tests against  nats-server v2.3.4, the MQTT client library is "github.com/eclipse/paho.mqtt.golang".
the nats-server deployed in a 3 nodes cluster.
a mqtt client as a message receiver, a mqtt client as a message sender, a nats client as a message sender.
everything runs well at the begining.  sometime later, the receiver get 3 copies of the message sent.
each time i send a message,  the receiver print 3 same messages  almost at the same time, no matter the message sender is a mqtt client or a nats client.
i try many versions of "github.com/eclipse/paho.mqtt.golang",  problem still there.
i test the same case against other mqtt broker, everything is ok.
if i use a nats client reveiver instead of a mqtt client reveiver, then send message through a mqtt client sender, it's OK, only one copy of message is received.
so, i guess it's not the MQTT client's fault.  somthing maybe wrong with the nats-server.
BTW, i did some nats nodes restart during the test.
would you take a look at it ?

**Comment by carr123** [comment]
i stop the nats-cluster, delete all data that jetstream use.   then restart the cluster. it is a  clean server now.
i perform the test again, this time everything is ok.  mqtt client receives exactly one copy of the message sent to the server.

**Comment by derekcollison** [comment]
I am increasingly concerned that something is wrong with your setup that is causing issues. We need to understand your setup in detail before proceeding. 

Would also be good to try to recreate this issue on a separate NATS system then the one you are running.

**Comment by carr123** [comment]
yes, i guess this issue could be the same as jetstream pull message bug.

**Comment by carr123** [comment]
same issue reported. close this one.

**Comment by imranrazakhan** [comment]
@carr123 @derekcollison  I am also suspecting same issue(duplicate) in my environment, but i could not able to reproduce after clean start. 
I have deployed 3 node cluster in K8S and i am suspecting if we remove/add node (i mean delete/scale down one pod) it results in this behaviors. But will try to reproduce.

**Comment by carr123** [comment]
@imranrazakhan this issue is not easy to reproduce.   I didn't find it today, during half an hour test.
