### ISSUE TITLE
invite me to nats-io slack community

### ISSUE THREAD

**Issue by rmros** [nats-io/nats-server#2457]
Hi,
please invite me to nats-io Slack community
email: rm.rostami@gmail.com

**Comment by derekcollison** [comment]
Just go here, its open!

https://slack.nats.io/

**Comment by rmros** [comment]
@derekcollison 
its said : The email address must match one of the domains
i have not any email that match with them,

**Comment by derekcollison** [comment]
Hmm, looping in @gcolliso here to help out, but our Slack channel is open and public for all, so not sure what is going on.

**Comment by rmros** [comment]
@gcolliso please send to me slack community invitation
email: rm.rostami@gmail.com

**Comment by gcolliso** [comment]
@rmros our link had expired for automatic invites. Please try [slack.nats.io](https://slack.nats.io) again and advise should you have an issue.

**Comment by vainkop** [comment]
Please advise how to get an invite to . 
Currently I see either "This link is no longer active" when I go to slack.nats.io 
or "myemail doesn’t have an account on this workspace." when I go to link provided on cncf slack natsio.slack.com
