### ISSUE TITLE
unable to connect using wss client

### ISSUE THREAD

**Issue by zubairalimansoor** [nats-io/nats-server#2458]
I am getting this error when I enable tls for websocket . Could you please guide how exactly wss can be used ? what need to be done client side? in example I just see url starts with wss instead of wss in case of tls. Please note that I am using tls without authentication. 

TLS handshake error from 127.0.0.1:56566: remote error: tls: unknown certificate authority

server config for websockets
 tls {
       cert_file: "./certs/server-cert.pem"
      key_file:  "./certs/server-key.pem"
	  timeout: 2
     }

**Comment by derekcollison** [comment]
Seems like you are using an intermediary CA. You need to include that in the config as well.
ca_file is what you need.

https://docs.nats.io/nats-server/configuration/securing_nats/tls

**Comment by zubairalimansoor** [comment]
I have included ca_file, still same error. Will self signed certificate work in this case ? on client side do I need to use certificate as well?

**Comment by kozlovic** [comment]
Which client are you using to connect? (Go, nats.ws, etc..). The error here is that the *client* cannot verify the server's certificate. So yes, client needs either the CA or a way to disable server cert verification.

**Comment by zubairalimansoor** [comment]
I am using this nats.ws https://github.com/nats-io/nats.ws

**Comment by kozlovic** [comment]
I am transferring this issue there so you can get better help on how to achieve this.
