### ISSUE TITLE
Question: Request with 2 Repliers no queue group edge case

### ISSUE THREAD

**Issue by wilstoff** [nats-io/nats-server#2485]
I'm writing some test cases around nats (in nats.c and nats.net) and having a weird behavior with requesting while multiple replying subscribers are listening on the same topic.  I am using an outdated version of the server, so it may have been fixed/changed, but am curious because I see the behavior in both C#/C, so I'm assuming it is with the server but may also be common amongst the clients.  Mostly I'm wondering what is the intended behavior.   Currently if I have 2 subscribers racing towards the same reply, 1 should win out, but what happens because of the inbox, both messages get to the client, but the client does not deduplicate it.  So if I request 2 messages the order of operations are as followed.

```
Replier B: 
Message="Subscribed to topic"; Topic="nats_test.request_reply.78b1a0d7-0739-4ef7-ac42-6e373335a4ba"; ClientId=47658;

Replier C:
Message="Subscribed to topic"; Topic="nats_test.request_reply.78b1a0d7-0739-4ef7-ac42-6e373335a4ba"; ClientId=4496;

Requester A:
sends "sent1."
sends "sent2."

Replier B:
receives "sent1." and replies with "sent1.replied"
receives "sent2." and replies with "sent2.replied"

Replier C:
receives "sent1." and replies with "sent1.replied"
receives "sent2." and replies with "sent2.replied"

Requester A:
receives "sent1.replied"
receives "sent1.replied"
(the 2 sent2.replied aren't received because i only requested 2 messages but am getting 4)
```

Now this somewhat makes some sense because of the reply topics below (some output messages on my test), but i'm not getting the correct message for the 2nd response:
```
Replier B:
Called callback on sent1. Reply Topic: _INBOX.T9FCC5QG266K4CE23JHSDJ.0
Called destroy on sent1.

Replier C:
Called callback on sent1. Reply Topic: _INBOX.T9FCC5QG266K4CE23JHSDJ.0
Called destroy on sent1.

Replier B:
Called callback on sent2. Reply Topic: _INBOX.T9FCC5QG266K4CE23JHSDJ.1
Called destroy on sent2.

Replier C:
Called callback on sent2. Reply Topic: _INBOX.T9FCC5QG266K4CE23JHSDJ.1
Called destroy on sent2.

Requester A:
Called destroy on sent1.replied
Called destroy on sent1.replied

Expected equality of these values:
  std::string(response->data())
    Which is: "sent1.replied"
  "sent2.replied"
```

One issue is in the nats.c client this leaks memory because I can never receive these messages through the request function, and asan outputs, while the C# client returns the same incorrect result for the second request:
```
=4864==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 134 byte(s) in 1 object(s) allocated from:
    #0 0x3f37b8 in malloc (/build/bstoffel/LaserBuild/BT.Messaging/IntegrationTests/BT.Messaging.IntegrationTests+0x3f37b8)
    #1 0x7ffff7bb36e9 in natsMsg_create (/usr/local/lib64/libnats.so.2.4+0x1d6e9)

SUMMARY: AddressSanitizer: 134 byte(s) leaked in 1 allocation(s).
```

So my question really is, what is the intended behavior with 2 racing replying subscriptions?  I would expect that the clients or server would dedup the message on the inbox since it seems to have a incrementing "requestid" and can easily determine that it already received this message and not forward it back to the request caller when they request a second message, but it doesn't seem that case in both C# or C.

In C this may be related to something like this https://github.com/nats-io/nats.c/issues/457 but not exactly, and I wasn't able to find any nats-server bug fixes that referenced this exactly to know if it is worth me upgrading the server and testing this again.

Versions:
C# nats.net (0.12.0)
nats-server (2.1.2)
nats-c (2.4.0)

**Comment by kozlovic** [comment]
For the C client, you should upgrade to the latest (v3.1.0) or at the very least v2.5.1.

That being said, description is a bit confusing, so maybe showing some code would help. Since we don't know how you are doing requests, it is difficult to answer what is expected or not.

For instance, if you call `natsConnection_Request()` then yes, you would receive only 1 reply, regardless how many responders sent a response.
But if you setup your own subscription on the "reply" subject, then it is up-to-you to decide how may replies you want to receive.

Again, please show some code so we can help better.

**Comment by wilstoff** [comment]
sorry will do, the tests are at a higher level through our own custom interface (hides the fact whether its nats or stan or whatever), so the layer that gets back down to the actual c code will take me some time to make it useful to you.  Will update shortly.

**Comment by wilstoff** [comment]
Ok was recreating the code in C#, and found out my initial tests had a bug in it, and C# is working as expected.  Therefore since only seeing it in C code and since there's bugs related to it that have since been fixed, I will try upgrading nats-c first and then re-run the tests.   Thanks for your quick replies.  Here's the rough code that works in C# but wouldn't work on nats-c v2.4.0.

```
        [Test]
        public void TwoReplierSameTopic()
        {
            var guid = Guid.NewGuid().ToString();
            var clientId = Guid.NewGuid().ToString();
            var topic = $"testing.reqreply.{_guid}";
            var configurationRetriever = new MessagingConfigurationRetriever();
            var natsConnectionOptions = NatsOptionsFactory.Create().Build(configurationRetriever.HostsAndPorts, clientId);
            var natsConnection1 = new ConnectionFactory().CreateConnection(natsConnectionOptions);
            var natsConnection2 = new ConnectionFactory().CreateConnection(natsConnectionOptions);
            var natsConnection3 = new ConnectionFactory().CreateConnection(natsConnectionOptions);

            var replySubscription1 = natsConnection1.SubscribeAsync(topic, (sender, args) =>
            {
                args.Message.Respond(Encoding.ASCII.GetBytes(Encoding.ASCII.GetString(args.Message.Data) + "replied"));
            });
            replySubscription1.Start();
            natsConnection1.Flush();

            var replySubscription2 = natsConnection2.SubscribeAsync(topic, (sender, args) =>
            {
                args.Message.Respond(Encoding.ASCII.GetBytes(Encoding.ASCII.GetString(args.Message.Data) + "replied"));
            });
            replySubscription2.Start();
            natsConnection2.Flush();

            var response1 = Encoding.ASCII.GetString(natsConnection3.Request(topic, Encoding.ASCII.GetBytes("sent1.")).Data);
            var response2 = Encoding.ASCII.GetString(natsConnection3.Request(topic, Encoding.ASCII.GetBytes("sent2.")).Data);

            Assert.That(response1, Is.EqualTo("sent1.replied"));
            Assert.That(response2, Is.EqualTo("sent2.replied"));
        }
```

**Comment by kozlovic** [comment]
@wilstoff Ok, keep us posted. If you still can reproduce with simple code and latest C client, please open an issue on https://github.com/nats-io/nats.c repo. Note, I am releasing v3.1.1 as I type this, but v3.1.1 (compared to v3.1.0) contains a fix specific to JetStream, so that would not affect your test.

**Comment by wilstoff** [comment]
As a follow up, I upgraded to 3.1.1 today and see no memory leaks and the test case passes correctly in C++.  Again thanks for your help.
