### ISSUE TITLE
Ability to publish to a kv style topic only if empty

### ISSUE THREAD

**Issue by ripienaar** [nats-io/nats-server#2494]
#### Use Case:

Today we have `Nats-Expected-Last-Subject-Sequence` that limits publishing to a stream if the previous message had a specific sequence

Along the same lines it would be useful to ensure only the first client can write a message when the subject is empty.

We discussed maybe (ab)using `Nats-Expected-Last-Subject-Sequence:0` but decided not to, so maybe `Nats-Expected-Empty-Subject:1`

A sample use case could be for example registering a schema that relates to a specific topic, the first publisher to this topic should register the subject but that's true only ever once.

This setting should probably only be accepted in `max_msgs_per_subject > 0` stream

**Comment by derekcollison** [comment]
Thinking more about this I think the original suggestion should work.

Nats-Expected-Last-Subject-Sequence: 0

**Comment by ripienaar** [comment]
It needs to mean a subject we have never seen or one that we have seen and purged out. 

But yeah I think that’s quite a obvious way to do it

**Comment by derekcollison** [comment]
Working on it now.
