### ISSUE TITLE
not able start nats-server in windows 7 machine

### ISSUE THREAD

**Issue by rabeeshcharles** [nats-io/nats-server#2509]
link to downloading the package - https://github.com/nats-io/nats-server/releases/download/v2.5.0/nats-server-v2.5.0-windows-amd64.tar.gz

Could someone help on this?

**Comment by aricart** [comment]
Isn't windows 7 an unsupported product? End of life was Jan 2020...

**Comment by rabeeshcharles** [comment]
Yes its life will be over.
Then the nats-server.exe will not be run in the windows 7 machine ah?
Just I need to know whether it can run or not?

plz give me a idea..

**Comment by kozlovic** [comment]
I can verify that it starts on Windows 10. I don't have a Windows 7 to test with.

You write: "not able to start". What is the error reported?

**Comment by rabeeshcharles** [comment]
Yes for windows 10 ,its working fine
In windows 7, It does not produce any error while starting exe file

**Proof**
-------
![image](https://user-images.githubusercontent.com/30102705/132953620-b77dead8-5ac7-40b0-a5a5-09036fdd25dc.png)

**Comment by kozlovic** [comment]
@rabeeshcharles I would recommend that you check the system event log just after trying to start the server.

**Comment by bruth** [comment]
Closing as stale.
