### ISSUE TITLE
Server websocket.go crash

### ISSUE THREAD

**Issue by byazrail** [nats-io/nats-server#2510]
Hello there,

I have been using version 2.4.0 for 2 days.
Error occurred 2 times, I am sending the error output.

```
systemctl status nats-sever response;
Sep 11 18:15:50 nats-2.system.com nats-server[7961]: /root/nats-server-2.4.0/server/websocket.go:275 +0x6a6
Sep 11 18:15:50 nats-2.system.com nats-server[7961]: github.com/nats-io/nats-server/v2/server.(*client).readLoop(0xc024660c80, 0x0, 0x0, 0x0)
Sep 11 18:15:50 nats-2.system.com nats-server[7961]: /root/nats-server-2.4.0/server/client.go:1142 +0x48e
Sep 11 18:15:50 nats-2.system.com nats-server[7961]: github.com/nats-io/nats-server/v2/server.(*Server).createWSClient.func1()
Sep 11 18:15:50 nats-2.system.com nats-server[7961]: /root/nats-server-2.4.0/server/websocket.go:1219 +0x3b
Sep 11 18:15:50 nats-2.system.com nats-server[7961]: created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine
Sep 11 18:15:50 nats-2.system.com nats-server[7961]: /root/nats-server-2.4.0/server/server.go:2867 +0xc5
```

log errors line;
`wid:1087296 - "v1.3.0:nats.ws" - Slow Consumer Detected: WriteDeadline of 5s exceeded with 844 chunks of 1723747 total bytes`

**Comment by byazrail** [comment]
New crash logs;

```
Sep 12 20:15:30 nats-1 nats-server: github.com/nats-io/nats-server/v2/server.(*client).wsHandleControlFrame(0xc028425300, 0xc00d343400, 0x8, 0xe59c40, 0xc000208cd0, 0xc0146ad5c0, 0x40, 0x40, 0x40, 0x4, ...)
Sep 12 20:15:30 nats-1 nats-server: /root/nats-server-2.4.0/server/websocket.go:433 +0x4e5
Sep 12 20:15:30 nats-1 nats-server: github.com/nats-io/nats-server/v2/server.(*client).wsRead(0xc028425300, 0xc00d343400, 0xe59c40, 0xc000208cd0, 0xc0146ad5c0, 0x40, 0x40, 0x0, 0x0, 0x0, ...)
Sep 12 20:15:30 nats-1 nats-server: /root/nats-server-2.4.0/server/websocket.go:275 +0x6a6
Sep 12 20:15:30 nats-1 nats-server: github.com/nats-io/nats-server/v2/server.(*client).readLoop(0xc028425300, 0x0, 0x0, 0x0)
Sep 12 20:15:30 nats-1 nats-server: /root/nats-server-2.4.0/server/client.go:1142 +0x48e
Sep 12 20:15:30 nats-1 nats-server: github.com/nats-io/nats-server/v2/server.(*Server).createWSClient.func1()
Sep 12 20:15:30 nats-1 nats-server: /root/nats-server-2.4.0/server/websocket.go:1219 +0x3b
Sep 12 20:15:30 nats-1 nats-server: created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine
Sep 12 20:15:30 nats-1 nats-server: /root/nats-server-2.4.0/server/server.go:2867 +0xc5
```

**Comment by kozlovic** [comment]
@byazrail Thank you for the second crash log, it makes much more sense and is helpful that the first. I *think* I understand what's going on there and will work on a test/fix tomorrow. Will keep you posted.

**Comment by byazrail** [comment]
@kozlovic Thank you, I added a restart policy on systemctl, and I can't follow it all the time. I will update when there is a solution. Have a nice day...

**Comment by kozlovic** [comment]
@byazrail Not sure if you can compile from source, otherwise, you could try with nightly docker image (the one that is going to be built tonight). I have fixed what I believe was the issue in PR 2519.
To get the nightly docker image: `docker pull synadia/nats-server:nightly`

**Comment by byazrail** [comment]
@kozlovic Thank you.

I adapted the codes you corrected myself.
I'll compile and switch to prod.
I will share the result.

docker pull synadia/nats-server:nightly Thank you very much for this image, but I cannot use the release version because I have my own authorization.
I manipulated server/auth.go by myself, I compile each version when it comes.

**Comment by kozlovic** [comment]
Ok, no problem. Please keep me posted.

**Comment by byazrail** [comment]
@kozlovic Everything seems fine with this update 👍

**Comment by kozlovic** [comment]
@byazrail Thank you for letting me know.
