### ISSUE TITLE
Should programmatically adding a stream be idempotent?

### ISSUE THREAD

**Issue by jnmoyne** [nats-io/nats-server#2527]
For defining and then using streams there are two options: either consider the creation/deletion of streams a purely administrative thing (i.e. a nats administrator defines and manages the streams using for example natscli, and client applications only try to use streams and not define them themselves), or consider that application developers can create/delete streams directly using library calls such as js.AddStream (or a mixture of both).

If going with the first (administrative) option you would want js.AddStream to _not_ be idempotent (meaning  you try to add a stream that is already defined (even if the attributes of the stream you are trying to define actually match the attributes of the stream already defined) the call should return an error).

If going with the second (applications can also directly create their streams) then you would want js.AddStream to _be_ idempotent (meaning that if there is already a stream defined but it matches the attributes of the stream you are trying to create then the call should not return an error (i.e. js.AddStream is idempotent) as it is more convenient for the developer because otherwise they would have to write the boilerplate code of checking if the stream is already defined and then comparing the attributes of the stream you want to define with those of the already defined stream in order to figure out whether you can still move on and start using the stream or error out).

**Comment by ripienaar** [comment]
Thinking back our thinking was that users migth have microservices starting up - 100s of them - and not pre-create streams, we'd like which ever comes up first make the stream and the rest be treated idempotently.

That was the thinking around the behavior of single server, we probably didnt correctly implement same behaviour in clustered but it seems like a good thing to be idempotent.

**Comment by derekcollison** [comment]
Sounds reasonable. @kozlovic does this violate any assumptions for MQTT?
Who can do these changes?

**Comment by kozlovic** [comment]
Yes, it would possibly have an effect on MQTT since, as you may remember, we recently made a change that if stream create returns OK, then we try to transfer old mqtt session individual streams to single stream. It can be fixed, I guess with a lookup, but just stating the impact.

**Comment by jnmoyne** [comment]
Seem we have consensus (should be idempotent), and the difference in behavior when connected to a cluster (https://github.com/nats-io/nats-server/pull/2535) is now done, so closing this issue.
