### ISSUE TITLE
support deferred message

### ISSUE THREAD

**Issue by carr123** [nats-io/nats-server#2541]
## Feature Request
is there any plan to support deferred message in jetstream ?
deferred message means a message stays in the server for a given time before it can be consumed.

#### Use Case:
task schedule

**Comment by derekcollison** [comment]
Just got asked that on Slack. No specific plans but happy to consider if others think its worthwhile.

**Comment by carr123** [comment]
it's not an urgent nor an inportant feature.

**Comment by derekcollison** [comment]
Let's keep it open since we have had a few requests.

**Comment by c16a** [comment]
I've created #2731 if anyone wants to take a look at.
