### ISSUE TITLE
raft node cost too much memory

### ISSUE THREAD

**Issue by carr123** [nats-io/nats-server#2559]
nats-server:  v2.6.0(built with go version go1.17) , linux amd64, 3-node cluster.

launch 6000 mqtt clients(qos=1, cleansession=false), after they are all connected, close them all.
then watch one of the 3 nodes memory status.

the following data are captured when the cluster are idle (no heavy clients online)

(pprof) top
Showing nodes accounting for 4986.53MB, 97.12% of 5134.26MB total
Dropped 156 nodes (cum <= 25.67MB)
Showing top 10 nodes out of 29
      flat  flat%   sum%        cum   cum%
 4849.73MB 94.46% 94.46%  4903.10MB 95.50%  github.com/nats-io/nats-server/v2/server.(*Server).startRaftNode
  103.14MB  2.01% 96.47%   104.14MB  2.03%  github.com/nats-io/nats-server/v2/server.(*Server).createInternalClient
   12.64MB  0.25% 96.71%    35.24MB  0.69%  github.com/nats-io/nats-server/v2/server.(*Sublist).Insert
   10.90MB  0.21% 96.93%    35.43MB  0.69%  github.com/nats-io/nats-server/v2/server.(*client).processRemoteSub
       6MB  0.12% 97.04%    82.53MB  1.61%  github.com/nats-io/nats-server/v2/server.(*stream).addConsumerWithAssignment
    2.50MB 0.049% 97.09%    55.17MB  1.07%  github.com/nats-io/nats-server/v2/server.(*client).readLoop
       1MB 0.019% 97.11%    52.67MB  1.03%  github.com/nats-io/nats-server/v2/server.(*client).parse
    0.62MB 0.012% 97.12%  4951.68MB 96.44%  github.com/nats-io/nats-server/v2/server.(*jetStream).processConsumerAssignment
         0     0% 97.12%    40.22MB  0.78%  github.com/nats-io/nats-server/v2/server.(*Account).EnableJetStream
         0     0% 97.12%    40.86MB   0.8%  github.com/nats-io/nats-server/v2/server.(*Server).EnableJetStream

(pprof) list startRaftNode
Total: 5.01GB
ROUTINE ======================== github.com/nats-io/nats-server/v2/server.(*Server).startRaftNode in D:\project\src\github.com\nats-io\nats-server\server\raft.go
    4.74GB     4.79GB (flat, cum) 95.50% of Total
         .          .    338:   }
         .          .    339:   if ps == nil {
         .          .    340:           return nil, errNoPeerState
         .          .    341:   }
         .          .    342:
       4MB        4MB    343:   n := &raft{
         .          .    344:           created:  time.Now(),
         .          .    345:           id:       hash[:idLen],
         .          .    346:           group:    cfg.Name,
         .          .    347:           sd:       cfg.Store,
         .          .    348:           wal:      cfg.Log,
         .          .    349:           wtype:    cfg.Log.Type(),
         .          .    350:           track:    cfg.Track,
         .          .    351:           state:    Follower,
         .          .    352:           csz:      ps.clusterSize,
         .          .    353:           qn:       ps.clusterSize/2 + 1,
         .          .    354:           hash:     hash,
         .          .    355:           peers:    make(map[string]*lps),
         .          .    356:           acks:     make(map[uint64]map[string]struct{}),
         .          .    357:           pae:      make(map[uint64]*appendEntry),
         .          .    358:           s:        s,
         .    33.71MB    359:           c:        s.createInternalSystemClient(),
         .          .    360:           js:       s.getJetStream(),
         .          .    361:           sq:       sq,
       1MB        1MB    362:           quit:     make(chan struct{}),
       1MB        1MB    363:           wtvch:    make(chan struct{}, 1),
  512.05kB   512.05kB    364:           wpsch:    make(chan struct{}, 1),
       1MB        1MB    365:           reqs:     make(chan *voteRequest, 8),
       1MB        1MB    366:           votes:    make(chan *voteResponse, 32),
  380.81MB   380.81MB    367:           propc:    make(chan *Entry, 8192),
    1.48GB     1.48GB    368:           entryc:   make(chan *appendEntry, 32768),
    1.43GB     1.43GB    369:           respc:    make(chan *appendEntryResponse, 32768),
    1.44GB     1.44GB    370:           applyc:   make(chan *CommittedEntry, 32768),
       1MB        1MB    371:           leadc:    make(chan bool, 8),
  512.05kB   512.05kB    372:           stepdown: make(chan string, 8),
         .          .    373:           observer: cfg.Observer,
         .          .    374:   }
         .          .    375:   n.c.registerWithAccount(sacc)
         .          .    376:
         .          .    377:   if atomic.LoadInt32(&s.logging.debug) > 0 {
         .          .    378:           n.dflag = true
         .          .    379:   }

**Comment by derekcollison** [comment]
Thanks and we are aware. We wanted to stabilize JetStream from a functionality standpoint first but we do realize we have some opportunities to improve resources with large numbers of JetStream assets.

We will be improving for sure as we move forward. 

If there is something that is blocking you from utilizing in production let's jump on a call and discuss how best to support you.

**Comment by derekcollison** [comment]
For pprof you are doing inuse vs alloc correct?

**Comment by carr123** [comment]
hi，i was trying to find out what caused memory arise when there are many mqtt connections.
i used "go tool pprof -inuse_space http://xxxxx:5555/debug/pprof/heap".
i guess, it's the golang GC problem, the go channels(entryc, respc,  applyc) keep too much memory even if when they are empty.
i will try to find if there's a workaround.
mqtt feature now is not in my production use. when it's stable,  i would use it to replace legacy mqtt broker.
i agree with you that jetstream should be stabilized first.
looking forward to your great work ！

**Comment by derekcollison** [comment]
Yes we have plans to replace channels, will happen in next couple of months I would imagine.

Team has a love / hate relationship with channels as do I. But not that we are stabilizing pretty well we can take the opportunity to improve, like here: https://github.com/nats-io/nats-server/commit/eab45b404a891d941eb87069101c16b843b875d8

Thanks for your patience and support, greatly appreciated.

**Comment by carr123** [comment]
hi, for the time being i made a little modification on github.com\nats-io\nats-server\server\raft.go
this time, i make 12000 mqtt connections to the cluster, all succeed, and the total memory usage is 1/3 of the original code :)
i wonder whether this modification could bring some side effect .

-------------------------------------------------------------------------------------------------
// propc:    make(chan *Entry, 8192),
// entryc:   make(chan *appendEntry, 32768),
// respc:    make(chan *appendEntryResponse, 32768),
// applyc:   make(chan *CommittedEntry, 32768),
propc:  make(chan *Entry, 64),
entryc: make(chan *appendEntry, 64),
respc:  make(chan *appendEntryResponse, 64),
applyc: make(chan *CommittedEntry, 64),


// select {
// case propc <- &Entry{EntryAddPeer, []byte(peer)}:
// default:
// 	return errProposalFailed
// }
propc <- &Entry{EntryAddPeer, []byte(peer)}

**Comment by derekcollison** [comment]
Will just effect peak performance and throughput. We will be replacing channels here as I mentioned.

**Comment by carr123** [comment]
@derekcollison  seems your new release have replaced channels with queue.  congratulations !
BTW, in the passed few month,  i wrote my own mqtt server (only Qos0 supported ), replying on nats pub/sub for message exchanging. that's super cool. thanks again.
i will do more test against jetstream when i have free time.

**Comment by derekcollison** [comment]
Thank @kozlovic!

Great work from him and the team! From our own internal testing we kept performance and reduced memory usage on idle assets by > order of magnitude.
