### ISSUE TITLE
Incorrect number of subscriptions in v2.5.0

### ISSUE THREAD

**Issue by sanathkumarbs** [nats-io/nats-server#2566]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x ] Included nats.go version
 - [ x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats.go` and the `nats-server` if one was involved:
Issue seen in: `github.com/nats-io/nats-server/v2 v2.5.0`
Issue previous not seen in: `github.com/nats-io/nats-server/v2 v2.3.4`

#### OS/Container environment:
`Linux and Mac`

#### Steps or code to reproduce the issue:

For `v2.3.4`
1. go get `nats-server` at `v2.3.4` 
2. Create a `goroutine` based server
3. Check for total subscriptions
4. Expect `0` as number of subscriptions created

For `v2.5.0`
1. go get `nats-server` at `v2.5.0` 
2. Create a `goroutine` based server
3. Check for total subscriptions
4. Seeing `2` as the total number of subscriptions

#### Expected result:
Expected `0` as number subscriptions, as no subscriptions were created. 

Are the `2` subscriptions expected? It seems like something has changed between `v2.3.4` and `v2.5.0`

#### Actual result:
Seeing `2` as the total number of subscriptions

#### Script 
```
package main

import (
	"fmt"

	natsSrvTest "github.com/nats-io/nats-server/v2/test"
)

func main() {
	s := natsSrvTest.RunRandClientPortServer()
	defer s.Shutdown()

	fmt.Printf("Total Subscribers: %v \n", s.GlobalAccount().TotalSubs())
}

```

The two binaries are generated with the code here: https://github.com/sanathkumarbs/testnats

**Comment by sanathkumarbs** [comment]
@wallyqs, I see. Thank you for the info! 

We were just surprised when we upgraded to `v2.5.0` as all our tests started to fail when it came to subscriptions. 

If this is the intended behavior, I don't think this is a bug then. Feel free to close it.

**Comment by wallyqs** [comment]
OK closing for now then 🙂
