### ISSUE TITLE
JS stream sources allow filters that are invalid

### ISSUE THREAD

**Issue by aricart** [nats-io/nats-server#2592]
Currently, it is possible to create a stream with a source that filters on subjects that cannot possibly exist in the source.
This telegraphs into an error on the consumer when trying to find a stream to bind to. Instead, it likely should fail on stream creation.

```javascript
  const { ns, nc } = await setup(jetstreamServerConf({}, true));
  const jsm = await nc.jetstreamManager();

  await jsm.streams.add({
    name: "other",
    subjects: ["updates.>"],
    retention: RetentionPolicy.Limits,
  });

  const si = await jsm.streams.add({
    name: "workers",
    subjects: ["workers.*.*"],
    retention: RetentionPolicy.Workqueue,
    max_msgs_per_subject: 1,
    sources: [
      {
        name: "other",
        filter_subject: "updates.x.*",
      },
    ],
  });

  console.log(si);

  await cleanup(ns, nc);
```

**Comment by ripienaar** [comment]
I dont think we really have a choice since we cannot be guaranteed to figure this out at create time - the source might not exist, the source might be remote and unreachable, the source might be in a different account and we dont have info api access

**Comment by derekcollison** [comment]
Those streams even of they existed could be updated to change the subject set as well.
So we chose to not enforce on sources and mirrors.
