### ISSUE TITLE
How to disable file store for jetstream

### ISSUE THREAD

**Issue by innorfui** [nats-io/nats-server#2594]
I am evaluating NATS with MQTT and deployed single node NATS-2.6.1 in Kubernetes.

I configured jetstream like below, as I didn't mentioned `store_dir` so i am expecting it will not use file store

```
jetstream {
  max_mem: 3Gi
}
```

But at the start of NATS its showing Store Directory: "/tmp/nats/jetstream". 

1- Can we completely disable file store? As in K8S we may not need file storage.
2- Does disabling file store will improve throughput?

```
[INF] Starting nats-server
[INF] Version: 2.6.1
[INF] Git: [c91f0fe]
[INF] Name: nats-0
[INF] Node: S1Nunr6R
[INF] ID: NAFWIB25ZD7FE5CNCFZYQBHMWHZS7RD4QB2MT3VQON64Q6RWF26XHVAM
[WRN] Plaintext passwords detected, use nkeys or bcrypt
[INF] Using configuration file: /etc/nats-config/nats.conf
[INF] Starting JetStream
[INF] _ ___ _____ ___ _____ ___ ___ _ __ __
[INF] _ | | __|_ _/ __|_ _| _ \ __| /_\ | \/ |
[INF] | || | _| | | \__ \ | | | / _| / _ \| |\/| |
[INF] \__/|___| |_| |___/ |_| |_|_\___/_/ \_\_| |_|
[INF]
[INF] https://docs.nats.io/jetstream
[INF]
[INF] ---------------- JETSTREAM ----------------
[INF] Max Memory: 3.00 GB
[INF] Max Storage: 126.31 GB
[INF] Store Directory: "/tmp/nats/jetstream"
[INF] -------------------------------------------
[INF] Starting http monitor on 0.0.0.0:8222
[INF] Listening for MQTT clients on mqtt://0.0.0.0:1883
[INF] Listening for client connections on 0.0.0.0:4222
[INF] Server is ready
[INF] Creating MQTT streams/consumers with replicas 1 for account "$G"
```

**Comment by kozlovic** [comment]
In general, I think you would need to explicitly specifying max_file to 0:
```
max_file: 0
```
By defaults, limits are set to `-1` which means unlimited. Having `max_file` set to 0 should really disable it.

However, the MQTT code creates assets with explicitly using FileStorage. There is currently no way to configure MQTT to not use file storage...

**Comment by kozlovic** [comment]
@innorfui We are evaluating make the selection of the type of storage (and possibly replicas count) an option in the mqtt{} configuration block. Would that help you think?

**Comment by innorfui** [comment]
@kozlovic Yes that will help me, But main intention to disable is to achieve better throughput, So I want to know will this improve performance? as disabling file store will definitely avoid lot of IO.

**Comment by derekcollison** [comment]
Closing for now, feel free to re-open if needed.
