### ISSUE TITLE
JetStream resource limits exceeded for server

### ISSUE THREAD

**Issue by biskit** [nats-io/nats-server#2599]
I get this message, where my config is like this:

```bash
#!/bin/bash
cd ~/nats-server
cat <<-EOF > /tmp/natsstrJS.cf
port: 4223
http_port: 8223
max_payload: 10485760
server_name: "xxxcluster"
jetstream: {
    storedir: "/tmp/xxxdata"
    max_memory_store: 1073741824
    max_file_store: 10737418240
}
EOF
./nats-server -c /tmp/natsstrJS.cf
```

its been running for a day adding data at steady rate. 

Once this message occurs, if I stop and start nats, this message reappears and it seems to reload all the messages in filestore back into memory. 

I have configured the stream like this:
```
        _, err = js.AddStream(&nats.StreamConfig{
                Name:     "ORDERS",
                Subjects: []string{"ORDERS.*"},
        })
```

I like to keep my messages around for a day and discard them after that.

my `nats-streaming-server` config looks like this and never hit this issue:

```bash
#!/bin/bash
OS=`uname`
if [ $OS == "Darwin" ]; then
    cd ~/nats-streaming-server-v0.12.0-darwin-amd64
    cat <<- EOF > /tmp/natsstr.cfg
http_port: 8222
max_payload: 10485760
streaming: {
    cluster_id: "xxx-cluster"
    store: "file"
    dir: "/temp/xxxdata"

    store_limits: {
       max_age: "24h"
       max_channels: 10000
       channels : {
           query.>: {
                 max_inactivity: "5m"
           }
           alert.>: {
                 max_inactivity: "5m"
           }
           temp.>: {
                 max_inactivity: "5m"
           }
       }
    }
}
EOF
    # ./nats-streaming-server -sc /tmp/natsstr.cfg
    nohup ./nats-streaming-server -sc /tmp/natsstr.cfg > ./nats.log 2>&1 &
fi
```

How do I achieve the same config  (I know the channel stuff is not there), but for the rest?

**Comment by kozlovic** [comment]
If you want to set a max age for the messages, you need to do so:
```
_, err = js.AddStream(&nats.StreamConfig{
    Name:     "ORDERS",
    Subjects: []string{"ORDERS.*"},
    MaxAge: 24*time.Hour,
})
```
As for "max_channels", I don't think that there is an equivalent: @derekcollison can you limit in JetStream the number of subjects? Either overall or within the above stream?
As for "max_inactivity", I know for sure that this is not available in JetStream.

**Comment by biskit** [comment]
I'm testing after I raised this issue with these settings
```
                MaxAge: time.Duration(24*time.Hour),
                Retention: nats.LimitsPolicy,
                Storage: nats.FileStorage,
```
and seems to hold.

its probably because it's not exceeding the 1G memory threshold (actually, when it did print the `JetStream resource limits exceeded for server` message, the virtual memory used was 4.3G).

however, why is memory being an issue when I'm using a filestore?

**Comment by biskit** [comment]
I have set `max_memory_store: 0` and I see it reporting 
`[36156] 2021/10/12 09:10:58.446931 [INF]   Max Memory:      12.00 GB`

I guess that's the system's available memory. Does it mean it will consume all of it, given a chance?

**Comment by derekcollison** [comment]
Please upgrade to 2.6.1 or nightly. That issue IIRC was resolved.

**Comment by derekcollison** [comment]
Could you share /tmp/natsstrJS.cf?

**Comment by derekcollison** [comment]
What size messages are you sending?

**Comment by derekcollison** [comment]
Hmm, I just ran simple test with nats cli with 10s max age and worked fine, and I know we have lots of tests for this base behavior.

What does `nats s info` for that stream report?

**Comment by derekcollison** [comment]
Make sure if you can to be running latest nats cli as well. Thanks.

**Comment by biskit** [comment]
I'm running 0.0.26 version of nats-cli

I run the ORDERS test with 1 min retention and it did as it should.

```
./nats --server nats://localhost:4223 s info ORDERS
Information for Stream ORDERS created 2021-10-15T18:16:19-05:00

Configuration:

             Subjects: ORDERS.*
     Acknowledgements: true
            Retention: File - Limits
             Replicas: 1
       Discard Policy: Old
     Duplicate Window: 1m0s
     Maximum Messages: unlimited
        Maximum Bytes: unlimited
          Maximum Age: 1m0s
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited


State:

             Messages: 501
                Bytes: 26 KiB
             FirstSeq: 1 @ 2021-10-15T23:16:19 UTC
              LastSeq: 501 @ 2021-10-15T23:16:19 UTC
     Active Consumers: 5
```

```
./nats --server nats://localhost:4223 s info ORDERS
Information for Stream ORDERS created 2021-10-15T18:16:19-05:00

Configuration:

             Subjects: ORDERS.*
     Acknowledgements: true
            Retention: File - Limits
             Replicas: 1
       Discard Policy: Old
     Duplicate Window: 1m0s
     Maximum Messages: unlimited
        Maximum Bytes: unlimited
          Maximum Age: 1m0s
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited


State:

             Messages: 0
                Bytes: 0 B
             FirstSeq: 502
              LastSeq: 501 @ 2021-10-15T23:16:19 UTC
     Active Consumers: 4
```


but, the other stream, not so.

```
./nats --server nats://localhost:4223 s info XXX
Information for Stream XXX created 2021-10-06T18:10:47-05:00

Configuration:

             Subjects: XXX.*
     Acknowledgements: true
            Retention: File - Limits
             Replicas: 1
       Discard Policy: Old
     Duplicate Window: 2m0s
     Maximum Messages: unlimited
        Maximum Bytes: unlimited
          Maximum Age: 1d0h0m0s
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited


State:

             Messages: 654,593
                Bytes: 9.7 GiB
             FirstSeq: 1,883,926 @ 2021-10-13T15:57:50 UTC
              LastSeq: 2,538,518 @ 2021-10-15T23:16:46 UTC
     Active Consumers: 21
```

I'm happy to quash the stream, clean the storage and start from the top. Would you like me to do that?

**Comment by derekcollison** [comment]
Maybe snapshot and backup the stream and restore it and see if that fixes it. Has this stream existed for awhile through multiple updates etc?

**Comment by biskit** [comment]
data gets homed elsewhere. so i can wipe it.

question: this laptop goes to sleep at nights. does that affect some kind of calculation of time or clock you guys deal with?

**Comment by derekcollison** [comment]
The Go runtime has monotonic timers that should account for this.

If you add another message to the stream does that kick in the expiration?

I will try to experiment with ctrl-Z a server for extended period to see for myself.

**Comment by biskit** [comment]
> The Go runtime has monotonic timers that should account for this.

Here's the read me on it:

>  Operating systems provide both a “wall clock,” which is subject to changes for clock synchronization, and a “monotonic clock,” which is not. The general rule is that the wall clock is for telling time and the monotonic clock is for measuring time. Rather than split the API, in this package the Time returned by time.Now contains both a wall clock reading and a monotonic clock reading; later time-telling operations use the wall clock reading, but later time-measuring operations, specifically comparisons and subtractions, use the monotonic clock reading. 

So, what does the nats-server use?

> If you add another message to the stream does that kick in the expiration?

no. it gets added at a continous rate.

**Comment by derekcollison** [comment]
The test I did where I control-Z the server for over an hour with a message TTL of 1min worked fine.

**Comment by biskit** [comment]
can you do the same by putting the machine to sleep. if laptop close lid or something. c+Z only backgrounds the process does not stop the clock.

**Comment by biskit** [comment]
the only other explanation is data reaches 10Gb before `clock time` is 24hrs. but I have to discount that because over a wall time of 3 days, it should have.

**Comment by derekcollison** [comment]
I believe this was fixed and we forgot to close this one.
