### ISSUE TITLE
NATS message in and message out are not in order

### ISSUE THREAD

**Issue by imranrazakhan** [nats-io/nats-server#2604]
**Environment:**  
NATS-2.6.1  with MQTT and standalone

In my use case one device is sending measurements after every 10ms and expectation is NATS send to consumer in same order/sequence but I am observing its not following it

**Device to Broker:**
As you observe measurements are coming after every 10ms
![image](https://user-images.githubusercontent.com/8535886/136572770-5d1ed611-27a3-4f84-9248-01475c9b7955.png)

**Broker to Consumer:**
As you can see its clubbing messages in one packet
![image](https://user-images.githubusercontent.com/8535886/136572970-0e1eb0b3-fa47-4850-9a09-fc328339825f.png)

Intention is to receive measurements after every 10ms, but here it skip one interval and send two messages on next interval, Mostly this happen due to tcp_nodelay setting, But as per my understanding NATS is developed in go and it enabled this setting by default.

You may wonder about different IP of broker, First pic IP are real and second Pic IPs are from kubernetes network.

**Comment by kozlovic** [comment]
No, Nagle's is a packet every 250ms and is disabled by default on Go. I am suspecting k8s networking at play here. But regardless, although I don't think that you would not be receiving a message every 10ms with not much load, there is no guarantee.

**Comment by kozlovic** [comment]
Closing this issue at this time. Please update if you want me to re-open it.
