### ISSUE TITLE
Report a coding issue that uses reference to loop iterator variable

### ISSUE THREAD

**Issue by guodongli-google** [nats-io/nats-server#2628]
In the following code
https://github.com/nats-io/nats-server/blob/3fbf9ddcbc6a8c40d278aec1e65981299febbad3/server/ocsp.go#L578-L589
Within the loop `for i, remote := range sopts.LeafNode.Remotes {...}`, variable `i` is shared by all the loop iterations, as described in the Go specification (https://golang.org/ref/spec).
At function closure `func(tc *tls.Config) {...}`, the reference to `i`, i.e. `&i`, is used to index `sopts.LeafNode.Remotes`. However all instances of `&i` within the loop may refer to the last loop index. As a consequence, `configs` may hold multiple closures that refer to the same `i`.

```go
	for i, remote := range sopts.LeafNode.Remotes {
		o := &tlsConfigKind{
				apply: func(tc *tls.Config) {
					sopts.LeafNode.Remotes[i].TLSConfig = tc
				},
			}
		configs = append(configs, o)
	}
```

A simplified bug reproducer is available at:
https://play.golang.org/p/_nZKm0RuDh9

A fixe is to avoid reusing the shared variable node:

```go
	for i, remote := range sopts.LeafNode.Remotes {
		i := i // avoid sharing
		o := &tlsConfigKind{
				apply: func(tc *tls.Config) {
					sopts.LeafNode.Remotes[i].TLSConfig = tc
				},
			}
```

A similar issue is at:
https://github.com/nats-io/nats-server/blob/3fbf9ddcbc6a8c40d278aec1e65981299febbad3/server/ocsp.go#L550-L562

**Found by #deepgo**

**Comment by wallyqs** [comment]
Thanks a lot @guodongli-google for the detailed report and repro instructions! A fix would be part of the following PR: 
- https://github.com/nats-io/nats-server/pull/2632
Also, I'm curious on the static analyzer used to find this issue, is there more info about `deepgo` somewhere?
