### ISSUE TITLE
Multi Tenancy with jwt accounts not working properly

### ISSUE THREAD

**Issue by masudur-rahman** [nats-io/nats-server#2635]
### System Information
- `nats-server` => `nats:2.6.1-alpine` with `nats-server --config /etc/nats-config/nats.conf` flag
- `nats-account-server` => v1.0.0 ( `URL Account Resolver` )
- `clustering` enabled with 3 replicas
- Multi Tenancy enabled using jwt accounts

### Client Libraries and Versions
- `jwt` => v2.0.3
- `nats.go` => v1.12.3
- `jsm.go` => v0.0.26
- `nkeys` => v0.3.0

### Current Condition
We have multiple accounts in `account-account-server` and we are continuously generating new accounts and storing them in `nats-account-server`.
We have notification enabled in `nats-account-server`
```
nats: {
  servers: ["nats://nats.server:4222"],
  usercredentials: "/nats/creds/sys.creds"
}
```

We have `service` type `export/import` in accounts.
Say, an admin account with export of a particular channel and multiple user accounts with import of that particular channel.

### Issues we are facing
In some point, we had to update the exports/imports for every accounts and pushed them to the `account-server`. But it doesn't seem to work.

Then we created a new admin account with same `export` channel as the previous admin account and updated all the user accounts to point their import to the new admin.
All the account were updated in the `account-server`.

Still not working. If we publish a message to the specified channel from a user account, I don't recieve it on the new admin account. In fact I still recieve it on the previous admin account.

But if I create multiple new accounts with export/import within them, it works how it's supposed to be.

**I think existing users aren't being updated in the `nats-server`.
Is there any way, we could manually boost a `account reloader` in the nats server ?**

### Sample NATS Account with export/import
```json
{
  "jti": "XI4BEBSB...6NKWUQ",
  "iat": 1634532506,
  "iss": "ODIAE6RO...B6YV7X",
  "name": "Admin",
  "sub": "ACQP4UE3...ZJJWQH",
  "nats": {
    "exports": [
      {
        "name": "events.>",
        "subject": "events.>",
        "type": "service",
        "response_type": "Stream"
      }
    ],
    "limits": {
      "subs": -1,
      "data": -1,
      "payload": -1,
      "imports": -1,
      "exports": -1,
      "wildcards": true,
      "conn": -1,
      "leaf": -1,
      "mem_storage": -1,
      "disk_storage": -1,
      "streams": -1,
      "consumer": -1
    },
    "default_permissions": {
      "pub": {},
      "sub": {}
    },
    "type": "account",
    "version": 2
  }
}
```

```json
{
  "jti": "KKGIDXX6...Y24ATA",
  "iat": 1634615268,
  "iss": "ODIAE6RO...B6YV7X",
  "name": "user-x",
  "sub": "AAWPCAM2...LIZPPI",
  "nats": {
    "imports": [
      {
        "name": "events.>",
        "subject": "events.>",
        "account": "ACQP4UE3...ZJJWQH",
        "local_subject": "events.>",
        "type": "service"
      }
    ],
    "limits": {
      "subs": -1,
      "data": -1,
      "payload": -1,
      "imports": -1,
      "exports": -1,
      "wildcards": true,
      "conn": -1,
      "leaf": -1,
      "mem_storage": 4194304,
      "disk_storage": 8388608,
      "streams": 5,
      "consumer": 10
    },
    "default_permissions": {
      "pub": {},
      "sub": {}
    },
    "type": "account",
    "version": 2
  }
}
```

**Comment by matthiashanel** [comment]
@masudur-rahman is the suggested workaround ok for you? does it resolve your issue?

**Comment by masudur-rahman** [comment]
@matthiashanel , sorry for taking too long.

Thank you for the information.
But for the moment we are sticking to our existing `NATS URL Resolver`.
