### ISSUE TITLE
How we can manage messages by nats-box?

### ISSUE THREAD

**Issue by edarha** [nats-io/nats-server#2641]
I run command `nats stream info` and `nats stream view`. With `nats stream info` show total messages is 0, but When I run `nats stream view` have a lot of messages. Anyone can help me to understand it?

![Screenshot from 2021-10-21 08-28-07](https://user-images.githubusercontent.com/36435846/138233006-327163e9-e951-4f60-874e-919f6eded3f3.png)
![Screenshot from 2021-10-21 08-26-33](https://user-images.githubusercontent.com/36435846/138233017-0c1dbe0f-65d1-4657-9902-c26fbf721e86.png)

**Comment by derekcollison** [comment]
Closing for now, feel free to re-open if needed.
