### ISSUE TITLE
JetStream Cluster becomes inconsistent: catchup for stream stalled

### ISSUE THREAD

**Issue by aksdb** [nats-io/nats-server#2642]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ ] Included `nats-server -DV` output
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:

`nats:2.6.2-alpine`

#### OS/Container environment:

k8s

#### Context

* I don't know how this problem arises, but it happens every few hours or days at max.
* The production system this is captured on has a message rate of about 1/s, with a few bursts every few hours of maybe 5/s  (at least according to Grafana).
* The cluster consists of three nodes, and a stream with 3 replicas.
* After hours/days, one of the nodes start emitting `Catchup for stream '$G > corejobs' stalled`
* All consumers, where this node is the leader, stop getting messages.
* I dumped the jetstream data directory so you can get a look at the current state.

#### Steps or code to reproduce the issue:

* Start the cluster with the data and config provided [here](https://cloud.aksdb.de/s/ecg53yRQ2C8ps3n).
* Make sure, `nats-cluster-2` is **not** the leader. (use `nats stream cluster step-down` if necessary)
* Send a message to the stream: `nats pub core.jobs.notifications.SendPush foobar`
* Observe the logs of `nats-cluster-2` (which now throws warnings)

Additionally:
check the message count in the stream; when `nats-cluster-2` is the leader, it differs from when `nats-cluster-0` or `nats-cluster-1` are leaders.

#### Expected result:

Either:
1. All three nodes have the same data.
1. The node which can't catch up is marked faulty and steps down from all leader positions

Also:
JetStream should always be able to recover from inconsistent states (especially if there is still a majority of healthy nodes around).

#### Actual result:

* The cluster thinks it's healthy.
* One node doesn't receive any data anymore.

Additionally: depending on who becomes leader, the amount of messages varies (obviously, since it's no longer synching).
Node0: 310 messages, Node1: 310 messages, Node2: 81 messages

**Comment by variadico** [comment]
I'm able to reproduce the issue on my Linux laptop, with the 2.6.2 Go binaries (f7c3ac5), using the provided configs and data: https://cloud.aksdb.de/s/ecg53yRQ2C8ps3n.

Here's how I setup the issue.
```
# Terminal 1
$ nats-server-2.6.2 -D -c nats0.conf

# Terminal 2
$ nats-server-2.6.2 -D -c nats1.conf

# Terminal 3
$ nats-server-2.6.2 -D -c nats2.conf

# Terminal 4 (this triggers the issue)
$ nats pub core.jobs.notifications.SendPush foobar
```

After publishing, this is what we get.
```
# Terminal 1
RAFT [EEUOgTxU - C-R3F-TZm4O8z6] Finished catching up

# Terminal 2
RAFT [FFfB0Dc4 - S-R3F-bSTo304i] Finished catching up

# Terminal 3
[WRN] Got stream sequence mismatch for '$G > corejobs'
[DBG] SYSTEM - System connection closed: Internal Client
[DBG] RAFT [VpUo9efM - S-R3F-bSTo304i] Deleted
[DBG] RAFT [VpUo9efM - S-R3F-bSTo304i] AppendEntry did not match 136 37194 with 0 0
[DBG] RAFT [VpUo9efM - S-R3F-bSTo304i] Truncating and repairing WAL
[DBG] RAFT [VpUo9efM - S-R3F-bSTo304i] Canceling catchup subscription since we are now up to date
[DBG] RAFT [VpUo9efM - S-R3F-bSTo304i] Pausing apply channel
[DBG] RAFT [VpUo9efM - S-R3F-bSTo304i] Paused, not applying 37194
[WRN] Catchup for stream '$G > corejobs' stalled
```

There is also this line in nats2 logs that seems suspicious. It's printed _before_ the `nats pub` is executed. Maybe there was an issue with a previous operation that is causing an issue with the `nats pub`. 🤔 
```
[DBG] JetStream cluster failed to delete msg 96351 from stream "corejobs" for account "": stream store EOF
```

This is the full log for nats2: https://gist.github.com/variadico/cf7ef670ec642d160cb6b270ff59a85e

**Comment by canuckasaurus** [comment]
We seem to be having a really similar issue to this... but running on 2.10.10.
