### ISSUE TITLE
TestServer helper function

### ISSUE THREAD

**Issue by piotrkowalczuk** [nats-io/nats-server#267]
Hi,

one of my services is using gnatsd, and it's only dependency that i have to start separately instead of being spawned during tests in memory.

Limitations of current approach:
- `Server.Run()` returns no `error`
- `Server.Shutdown()` returns no `error`
- `Options` does not accept to pas custom `net.Listener`, and by passing `0` for port it is getting `4222` instead of any available.

Some changes in this api is necessary to be able to expose such function `func TestServer(t *testing.T) (net.Addr, io.Closer)`

Are you open for such PR?

**Comment by derekcollison** [comment]
I believe passing -1 will get you any available for the port.

For the embedded server, I believe what we need to do is create a new package that has a cleaner API using the APIs in /server.

**Comment by derekcollison** [comment]
I might even argue this functionality could be part of the NATS client package.

**Comment by piotrkowalczuk** [comment]
`func TestServer(t *testing.T) (net.Addr, io.Closer)` is just syntactic sugar. Same way `Server` could implement `io.Closer` and `Run`/`Shutdown`  could return an error.

**Comment by mcqueary** [comment]
See also #451

**Comment by derekcollison** [comment]
Closing this as being stale. Feel free to reopen.
