### ISSUE TITLE
Allow modification of some JS push consumer settings

### ISSUE THREAD

**Issue by jnmoyne** [nats-io/nats-server#2670]
The request is for being able to alter the MaxAckPending value for an existing push consumer, as it is possible in STAN.

Use case: when you deploy a larger number of workers than the current MaxAckPending value, you are not making use of all your available workers and you need to adjust that value.

Looking further ahead, it could also be interesting to allow adjusting AckWait, Description, RateLimit and MaxDeliver

**Comment by derekcollison** [comment]
Linked to #2603

**Comment by derekcollison** [comment]
Looked a bit, this would require adding a new API to update consumers.

**Comment by ripienaar** [comment]
We should allow these to be changed:

 * description
 * ack_wait
 * max_deliver
 * sample_freq
 * max_ack_pending
 * max_waiting
 * stretch goal: headers_only
 * stretch goal: filter_subject, we've had requests for this in addition to filter_subject being a array of subjects
 * stretch goal: allow ack_policy to move beetween all and explicit

Stretch goals are optional, nice to have, things users have asked that I thought were weird etc.

**Comment by derekcollison** [comment]
- [x] description
- [x] ack_wait
- [x] max_deliver
- [x] sample_freq
- [x] max_ack_pending
- [x] max_waiting
- [x] stretch goal: headers_only
- [ ] stretch goal: filter_subject, we've had requests for this in addition to filter_subject being a array of subjects
- [ ] stretch goal: allow ack_policy to move beetween all and explicit
