### ISSUE TITLE
When stream has no leader, how do I fix it?

### ISSUE THREAD

**Issue by HappyUncle** [nats-io/nats-server#2673]
How do I fix the benchstream_memory stream

![image](https://user-images.githubusercontent.com/20750625/140303164-d79900f9-eda4-4e5c-bcfc-005c874d4e78.png)

**Comment by ripienaar** [comment]
It depends on many factors, can you please look in the servers logs if anything there mentions this stream? Also what versions server pls

**Comment by HappyUncle** [comment]
The log was deleted. And I want to know, Is there any command to fix it? Such as force election of leader

**Comment by ripienaar** [comment]
No, it’s constantly trying to force an election leader and failing to do so for some reason.

**Comment by derekcollison** [comment]
Closing for now but feel free to re-open as needed.
