### ISSUE TITLE
A slow/disconnected subscriber can cause publishing to become blocked

### ISSUE THREAD

**Issue by lukedodd** [nats-io/nats-server#2679]
## Defect

With 1 publisher and multiple subscribers I have observed that under certain circumstances a subscriber 
which is slow/has a poor connection can block publishing (so preventing other subscribers from receiving data).

### Reproduction

It is possible to reproduce this with a local `nats-server` and `nats-cli`.

 - Run `nats-server` (default config/no arguments)
 - Start publishing messages ever 20ms of ~20kb: `./nats --trace pub test --count=-10000000 --sleep=20ms "{{Random 20000 20000}}"`
 - Start subscribing (just print out the message number to make the drops obvious) `./nats sub test | grep Received`
 - Start a second subscriber, `./nats sub test | grep Received`. Cause this subscriber to simulate a disconnect by suspending the process (i.e. pressing `CTRL+Z` in the terminal.)

After a few seconds, at the same time, the first subscriber stops receiving messages, the publisher stops sending (message count stops increasing). This lasts for  about 10 seconds.

I also see the following in the nats console logs.

```
[129148] 2021/11/05 11:45:56.973798 [INF] 127.0.0.1:50642 - cid:12 - "v1.12.0:go:NATS CLI Version 0.0.26" - Slow Consumer Detected: WriteDeadline of 10s exceeded with 1 chunks of 20020 total bytes.
[129148] 2021/11/05 11:45:56.973825 [WRN] 127.0.0.1:50616 - cid:10 - "v1.12.0:go:NATS CLI Version 0.0.26" - Readloop processing time: 10.000846205s
```

I've tested this on Ubuntu 20.04 with `nats-server` 2.6.4 and `nats-cli` 0.0.26.

The largish message size is required to trigger the issue.

Suspending the nats-cli is a crude way to simulate a subscriber with a connection issue  - but I have seen this happens in more realistic/reasonable situations (standard slow subscribers/poor network conditions).

### Investigation/Potential Fix

I am not familiar with golang or the nat-server codebase- but here's my attempt at figure out what is going on.

Using a shorter write deadline option makes the drop/blockage shorter - but there are still gaps of write deadline length when the subscriber disconnects.

I think the client `readLoop` for the publisher calling `flushClientsWithCheck` is causing the issue. When flushing messages to the subscriber the publisher `readLoop` ends up being blocked for the duration of `WriteDeadline`. The attempt to avoid this by using a time budget does not work since the heuristic of using the `Last flush time for Write` to guess how long the flush will take fails under the disconnect condition.

I verified this by changing the `budget` that `flushClientsWithCheck` is called with to zero in `client.go` - so clients are only notified, not flushed. i.e: 

```
@@ -1204,9 +1204,9 @@ func (c *client) readLoop(pre []byte) {
                // if applicable. Routes and Gateways will never
                // spend time flushing outbound in place.
                var budget time.Duration
-               if c.kind == CLIENT {
-                       budget = time.Millisecond
-               }
+               //if c.kind == CLIENT {
+               //      budget = time.Millisecond
+               //}
 
                // Flush, or signal to writeLoop to flush to socket.
                last := c.flushClientsWithCheck(budget, true)
```
(This might have performance implications but is the simplest way to fix it - assuming my reasoning here is correct.)

After I made this change I cannot reproduce the issue. When suspending a subscriber we see the `Slow consumer` log - but no slow `Readloop processing` warning.

**Comment by kozlovic** [comment]
@derekcollison Should we have a new option that disable sending in place (but keep default behavior as it is today)?

**Comment by derekcollison** [comment]
Let's run the benchmark suite against it with no budget and see the impact, maybe just turn that off completely.

**Comment by kozlovic** [comment]
I would say we remove. Here are some results:

Ran bench for `Sub` (since we want to measure when a pub sends to sub). I ran with `count=3` and then ran `benchstat` to make sure the variance was ok. Here "old" is main, "new" is the change:
```
benchstat old.txt 
name                    time/op
_____________PubSub-16  184ns ± 0%
_____PubSubTwoConns-16  184ns ± 1%
___PubSubAccsImport-16  188ns ± 0%
_____PubTwoQueueSub-16  206ns ± 1%
____PubFourQueueSub-16  206ns ± 1%
___PubEightQueueSub-16  206ns ± 0%
_PubSub512kTwoConns-16  228µs ± 0%
__DenyMsgNoWCPubSub-16  184ns ± 0%
_DenyMsgYesWCPubSub-16  184ns ± 0%
```
With the change:
```
 benchstat new.txt 
name                    time/op
_____________PubSub-16  180ns ± 0%
_____PubSubTwoConns-16  179ns ± 0%
___PubSubAccsImport-16  184ns ± 0%
_____PubTwoQueueSub-16  200ns ± 0%
____PubFourQueueSub-16  200ns ± 0%
___PubEightQueueSub-16  201ns ± 1%
_PubSub512kTwoConns-16  178µs ± 0%
__DenyMsgNoWCPubSub-16  180ns ± 0%
_DenyMsgYesWCPubSub-16  179ns ± 1%
```
Then comparing the two:
```
 benchcmp old.txt new.txt 
benchmark                           old ns/op     new ns/op     delta
Benchmark_____________PubSub-16     184           181           -1.69%
Benchmark_____________PubSub-16     184           181           -1.69%
Benchmark_____________PubSub-16     183           180           -1.97%
Benchmark_____PubSubTwoConns-16     183           180           -1.80%
Benchmark_____PubSubTwoConns-16     185           179           -3.46%
Benchmark_____PubSubTwoConns-16     183           179           -2.18%
Benchmark___PubSubAccsImport-16     189           183           -3.28%
Benchmark___PubSubAccsImport-16     189           184           -2.33%
Benchmark___PubSubAccsImport-16     188           184           -2.13%
Benchmark_____PubTwoQueueSub-16     204           199           -2.40%
Benchmark_____PubTwoQueueSub-16     208           200           -3.80%
Benchmark_____PubTwoQueueSub-16     205           201           -2.05%
Benchmark____PubFourQueueSub-16     208           199           -4.09%
Benchmark____PubFourQueueSub-16     205           201           -2.05%
Benchmark____PubFourQueueSub-16     206           200           -3.05%
Benchmark___PubEightQueueSub-16     207           202           -2.42%
Benchmark___PubEightQueueSub-16     205           200           -2.68%
Benchmark___PubEightQueueSub-16     206           201           -2.48%
Benchmark_PubSub512kTwoConns-16     226928        178428        -21.37%
Benchmark_PubSub512kTwoConns-16     227611        177800        -21.88%
Benchmark_PubSub512kTwoConns-16     228414        178062        -22.04%
Benchmark__DenyMsgNoWCPubSub-16     183           180           -1.58%
Benchmark__DenyMsgNoWCPubSub-16     184           180           -1.80%
Benchmark__DenyMsgNoWCPubSub-16     184           180           -1.96%
Benchmark_DenyMsgYesWCPubSub-16     184           179           -2.72%
Benchmark_DenyMsgYesWCPubSub-16     184           179           -2.61%
Benchmark_DenyMsgYesWCPubSub-16     184           180           -2.01%
```

For `Pub` alone, I am getting a bit too much variance in the main branch even more than changes, but here are the results:
```
benchstat old.txt 
name                    time/op
______Pub0b_Payload-16    65.3ns ± 0%
______Pub8b_Payload-16    64.8ns ± 1%
_____Pub32b_Payload-16    69.7ns ± 1%
____Pub128B_Payload-16    81.8ns ± 3%
____Pub256B_Payload-16    88.8ns ± 1%
______Pub1K_Payload-16     208ns ± 1%
______Pub4K_Payload-16     764ns ± 1%
______Pub8K_Payload-16    1.51µs ± 1%
_____Pub32K_Payload-16    5.88µs ± 5%
__AuthPub0b_Payload-16     148ns ± 0%
```
With the change:
```
enchstat new.txt 
name                    time/op
______Pub0b_Payload-16    62.6ns ± 1%
______Pub8b_Payload-16    63.4ns ± 1%
_____Pub32b_Payload-16    68.7ns ± 2%
____Pub128B_Payload-16    79.6ns ± 2%
____Pub256B_Payload-16    88.7ns ± 2%
______Pub1K_Payload-16     216ns ± 3%
______Pub4K_Payload-16     756ns ± 1%
______Pub8K_Payload-16    1.49µs ± 1%
_____Pub32K_Payload-16    5.74µs ± 2%
__AuthPub0b_Payload-16     149ns ± 0%
```
The compare:
```
benchcmp old.txt new.txt 
benchmark                           old ns/op     new ns/op     delta
Benchmark______Pub0b_Payload-16     65.1          62.4          -4.10%
Benchmark______Pub0b_Payload-16     65.4          63.2          -3.41%
Benchmark______Pub0b_Payload-16     65.3          62.0          -5.04%
Benchmark______Pub8b_Payload-16     64.9          63.7          -1.86%
Benchmark______Pub8b_Payload-16     64.4          62.9          -2.28%
Benchmark______Pub8b_Payload-16     65.0          63.5          -2.40%
Benchmark_____Pub32b_Payload-16     69.2          69.7          +0.59%
Benchmark_____Pub32b_Payload-16     69.4          69.0          -0.56%
Benchmark_____Pub32b_Payload-16     70.4          67.5          -4.04%
Benchmark____Pub128B_Payload-16     83.6          81.0          -3.19%
Benchmark____Pub128B_Payload-16     79.3          78.5          -1.07%
Benchmark____Pub128B_Payload-16     82.5          79.2          -3.98%
Benchmark____Pub256B_Payload-16     88.5          90.4          +2.09%
Benchmark____Pub256B_Payload-16     88.5          87.1          -1.54%
Benchmark____Pub256B_Payload-16     89.4          88.7          -0.85%
Benchmark______Pub1K_Payload-16     207           209           +0.92%
Benchmark______Pub1K_Payload-16     209           219           +4.83%
Benchmark______Pub1K_Payload-16     207           221           +6.42%
Benchmark______Pub4K_Payload-16     758           758           +0.01%
Benchmark______Pub4K_Payload-16     773           752           -2.73%
Benchmark______Pub4K_Payload-16     762           758           -0.62%
Benchmark______Pub8K_Payload-16     1523          1505          -1.18%
Benchmark______Pub8K_Payload-16     1506          1489          -1.13%
Benchmark______Pub8K_Payload-16     1494          1489          -0.33%
Benchmark_____Pub32K_Payload-16     5668          5837          +2.98%
Benchmark_____Pub32K_Payload-16     5811          5676          -2.32%
Benchmark_____Pub32K_Payload-16     6148          5717          -7.01%
Benchmark__AuthPub0b_Payload-16     148           149           +0.74%
Benchmark__AuthPub0b_Payload-16     148           149           +0.68%
Benchmark__AuthPub0b_Payload-16     149           149           +0.47%
```

**Comment by derekcollison** [comment]
Let's remove it then all together. Thanks @kozlovic

**Comment by GuanYin108** [comment]
Is that related to #2631

**Comment by lukedodd** [comment]
> Is that related to #2631?

Initially I thought it wasn't since there was no read loop processing logging warning in your report (otherwise I would have linked to it). On further thought I think it could be similar - since the slow consumer could slow down sending to the other consumers via this mechanism (just not enough to trigger the `Readloop processing time` warning.

Could be worth testing with the proposed fix?

**Comment by kozlovic** [comment]
@GuanYin108 @lukedodd Most likely. It is not a surprised to me knowing how the server sends messages from producers to matching subscriptions' connections. Any delay TCP sending to one client could have affected the others in the list, and possibly causing "readLoop" warnings in the go routine from which the server reads data from the producer.
