### ISSUE TITLE
Support to create/update streams as part of server startup

### ISSUE THREAD

**Issue by vishaltripathi24** [nats-io/nats-server#2681]

**Comment by ripienaar** [comment]
While yes it's desirable to capture configuration like this in a configuration file, the nats server configuration is not the right place for that.

NATS can be clustered or even super clustered, the leader of the JetStream system can move around the super cluster at will.  So the question is out of 10s of servers, which one is the authoritive? How do they reconcile differences in configuration between their configurations?

You cannot really think of JetStream as a "server" its more a "service", so it's better your operators manage the streams using something like [Terraform](https://registry.terraform.io/providers/nats-io/jetstream/latest), as a sever level configuration I am afraid it does not really make a lot of sense.

**Comment by iamolegga** [comment]
I've been searching for this feature in the docs and google for a couple of hours and finally landed here 😀

Declarative configuration of streams and consumers is available through k8s manifests and terraform resources. But I don't understand what's the difference with .conf file if it will contain the same description.

Right now for local development with a single server one should either create startup script  or run nats on minikube + manifests or even run terraform 🤯 to have streams and consumers preconfigured. Why not add the same feature out of the box with a cli argument?

> So the question is out of 10s of servers, which one is the authoritive? How do they reconcile differences in configuration between their configurations?

@ripienaar I believe we can ask the same question about other current parameters in config, can't we? Maybe check if it can be merged without conflicts or throw error when more than one configs are provided, etc.

@derekcollison could you consider reopen this issue?

**Comment by derekcollison** [comment]
I still feel strongly this does not belong in server configs.

**Comment by jnmoyne** [comment]
Put all your stream JSON configs in files in a directory and then create a small shell script that calls `nats stream add --config xxx.json` for each of those JSON stream config files in the directory for example?

(you can get the JSON config for an existing stream using nats, e.g.: `nats stream info streamname --json | jq .config > streamname.json`)

**Comment by ripienaar** [comment]
Or use terraform.
