### ISSUE TITLE
Duplicate messages due to overlapping leafnode connections

### ISSUE THREAD

**Issue by maxarndt** [nats-io/nats-server#2694]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ ] Included `nats-server -DV` output
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:

* nats-server `v2.6.2`
* natscli `0.0.26`

##### Description

* Account A exports certain topics.
* Account B imports a topic of Account A
* Account A has leafnode connections between some clusters
* Account B has leafnode connections which overlap with the leafnode connections of Account A

If these points apply it can bring you duplicate messages in Account B.

##### Example

* Account A is account `arndtmx`
* Account B is account `tim`
* Account A (`arndtmx`) exports `arndtmx.>`
* Account B (`tim`) imports `arndtmx.>`
* Account A (`arndtmx`) has leafnode connections between `EU <-> Central <-> APAC` 
* Account B (`tim`) has leafnode connections between `EU <-> Central <-> APAC`

```
[user@nats-0 ~]$ nsc describe account -n arndtmx
+--------------------------------------------------------------------------------------+
|                                   Account Details                                    |
+---------------------------+----------------------------------------------------------+
| Name                      | arndtmx                                                  |
(some lines skipped...)
+-------------------------------------------------------------------------------------------+
|                                          Exports                                          |
+-----------+--------+-----------+--------+-------------+----------+-------------+----------+
| Name      | Type   | Subject   | Public | Revocations | Tracking | Description | Info URL |
+-----------+--------+-----------+--------+-------------+----------+-------------+----------+
| arndtmx.> | Stream | arndtmx.> | Yes    | 0           | N/A      |             |          |
+-----------+--------+-----------+--------+-------------+----------+-------------+----------+

[user@nats-0 ~]$ nsc describe account -n tim
+--------------------------------------------------------------------------------------+
|                                   Account Details                                    |
+---------------------------+----------------------------------------------------------+
| Name                      | tim                                                      |
(some lines skipped...)
+--------------------------------------------------------------------------------+      
|                                    Imports                                     |      
+--------------+--------+--------------+-------+---------+--------------+--------+
| Name         | Type   | Remote       | Local | Expires | From Account | Public |
+--------------+--------+--------------+-------+---------+--------------+--------+
| arndtmx.>    | Stream | arndtmx.>    |       |         | arndtmx      | Yes    |
+--------------+--------+--------------+-------+---------+--------------+--------+
```

![duplicate-msgs-censor](https://user-images.githubusercontent.com/8988283/142181875-46d61886-4726-403b-b5ff-a4f76cd85ab9.png)

#### Expected result:
No duplicate messages in account `tim`.

#### Actual result:
Duplicate messages in account `tim`.

**Comment by matthiashanel** [comment]
This is an issue for jwt based use cases where the same account jwt is used in different leaf nodes. 

Possible solutions could be to:

- Tag the message, noteing that this has happened already. (consider, what if the importing account has no remote?)
- Or if the account on both ends of the leaf node connection is identical, skip export processing for accounts this server has other leaf node connections.

**Comment by maxarndt** [comment]
Seems like the behavior changed a bit with release v2.9.6 probably because of https://github.com/nats-io/nats-server/pull/3604.

It's getting closer. There seems to be less duplicates now. 

Reproduced the demo of https://github.com/nats-io/nats-server/issues/2694#issue-1055957932 and the results can be seen below:
![nats-issue-persits-2 9 6](https://user-images.githubusercontent.com/8988283/201295124-efd39355-622b-49b2-a7c3-913b76c782a1.png)

**Comment by Jarema** [comment]
@maxarndt Thanks for the update.
I'm on it, setting up env for the reproduction scenario with the latest server version.
Will get back to you soon.

**Comment by derekcollison** [comment]
Closing for now but feel free to re-open as needed.

**Comment by tbeets** [comment]
Speaking with @maxarndt today, [PR #3751](https://github.com/nats-io/nats-server/pull/3751), and v2.9.11 partially fixed this issue, but some dup receive remains.  Assume PR fixed overlapping responses accounting for some duplication, but there may be a "Gemini" stream export/import existing on both sides of leaf membrane in his environment.
