### ISSUE TITLE
No responder response does not work with leaf nodes and services import/exports in accounts

### ISSUE THREAD

**Issue by mullerch** [nats-io/nats-server#2700]
#### Versions of `nats-server` and affected client libraries used:

- Local server: nats-server 2.6.4 (custom build, go1.17.3)
- Cloud server: nats-server 2.6.4 (docker image)
- Local client:  nats.go v1.13.1 (go1.17.3)
- Remote client : nats.ws 1.5.0

(I use arbitrary names to simplify the reproduction steps description)

#### OS/Container environment:

The setup is quite complex. I'll try to describe it but I guess the error should be not so difficult to localize and does not depend on the whole setup. If it's not reproducible in a simple way, I'll provide more details.

#### Steps or code to reproduce the issue:

**Use case where it works as expected:**
1. Run local server
2. Connect local client to local server with token auth
3. Connect remote client to local server with username/password
4. Send a request from the remote client on a subject with no listeners
5. A 503 error is received

**Use case where is does not work as expected:**
Generate two accounts (A,B) with one user each (A1, B1). Export services from account A (e.g. get.info). Import account A services into B with wildcards and a subject prefix (ex: import get.> on local.get.>)

1. Run cloud server with operator
2. Run local server, connect it to the cloud server as leaf node with account A
3. Connect local client to local server with token auth
4. Connect remote client to cloud server with user B1
5. Send a request from the remove client on a subject imported by account B (e.g. local.get.another-info)

#### Expected result:

- The request is forwarder by the cloud server to the local server
- A 503 error is sent by the local server and received by the remote client

#### Actual result:

- The request is forwarder by the cloud server to the local server :heavy_check_mark: 
- The request times out (TIMEOUT error)

**Comment by derekcollison** [comment]
Service Imports are always on from the owning account perspective. We are aware of this but do not have a solution atm.
