### ISSUE TITLE
Stream state with large interior deletes slow

### ISSUE THREAD

**Issue by ripienaar** [nats-io/nats-server#2706]
When using Max Messages Per Subject style streams interior deletes are the norm, streams can easily build up millions or even 10s of millions of interior deleted messages.

In those cases Stream State API is very slow primarily because we duplicate and sort the list of these interior deletes - even when detail is not requested.

In memory store its not too bad, still we duplicate potentially 10s of millions of uint64s and then sort them - this can take minutes.

https://github.com/nats-io/nats-server/blob/ea48105526db36b566b3afb36ddfacccf3f97f3a/server/memstore.go#L750-L766

In filestore we seem to also do some block level maintenance in the middle of state gathering:

https://github.com/nats-io/nats-server/blob/ea48105526db36b566b3afb36ddfacccf3f97f3a/server/filestore.go#L3386-L3398

In the typical stream state we just discard all these numbers:

https://github.com/nats-io/nats-server/blob/ea48105526db36b566b3afb36ddfacccf3f97f3a/server/stream.go#L3525-L3538

For memory stream its quite easy to optimise this down to only giving or even calculating this list but for disk things are a bit more complex.  We'd need to extend the Store and WAL interfaces State() with a boolean and then carefully go through places where deleted is not needed, or a new form of State() should be added - but I think the design of the current State() functions need a rethink.

**Comment by intech** [comment]
the same problem on 1.5.0 starting to use max_msgs_per_subject=1, very high cpu and io consumption at 150mps.

**Comment by ripienaar** [comment]
@intech sorry, 1.5.0 of what component?

**Comment by intech** [comment]
> @intech sorry, 1.5.0 of what component?

Sorry, 2.6.5

**Comment by derekcollison** [comment]
You observe this getting the stream state or another operation?

**Comment by ripienaar** [comment]
Stream info but it was also reported that adding consumers were slow

**Comment by derekcollison** [comment]
Thanks will get this fixed up and improved.

**Comment by derekcollison** [comment]
Will be working on this one today, again thanks for the patience.
