### ISSUE TITLE
Direct communication with an embedded server

### ISSUE THREAD

**Issue by suazithustra** [nats-io/nats-server#2710]
We have considered a Go client with direct connect to an embedded server but currently have no plans. Will close this for now but feel free to open back up if needed.

_Originally posted by @derekcollison in https://github.com/nats-io/nats-server/issues/758#issuecomment-437087756_

Hello gentlemen. Has anything changed irt this topic yet?

**Comment by derekcollison** [comment]
Still on our list and a few others have expressed interest. Looking for a sponsor at this point if someone wants this prioritized above our current roadmap list.

**Comment by sikmike** [comment]
Hi, just wanted to ask if there was a change on this topic.

**Comment by ripienaar** [comment]
See https://github.com/nats-io/nats.go/blob/14e0c6bdccaac32bd6b9853dcb42a1a386981117/nats.go#L843
