### ISSUE TITLE
Introduce delay before redelivery of nacked messages

### ISSUE THREAD

**Issue by robertmircea** [nats-io/nats-server#2729]
## Feature Request

Possibility to delay re-delivery of nack-ed messages in Jetstream.

#### Use Case:

When a consumer rejects a message with nack and nats server delivers again the message instantly, usually, the event that triggered the message to be rejected the first time doesn't go away so fast and the probability to succeed on a subsequent attempt is quite slim. This behaviour might impede other messages to be processed fast enough and can poison the consumers with unprocessable messages due to external factors.

#### Proposed Change:

The proposal is to allow a configurable delay to be introduced before a nack-ed message is re-delivered. The delay can be either constant (linear back-off) or variable (exponential back-off). This redelivery delay should be configurable in consumer config, but the consumer config setting should be overridable in Nack function per message.

#### Who Benefits From The Change(s)?

Whoever uses Jetstream with worker queue semantic 

#### Alternative Approaches

One might attempt to simulate delay before redelivery by not nacking/acking the message, but this might block consumers for AckWait period of time. Even if this is acceptable for the consumer, the delay obtained this way is a constant period of time.

**Comment by andreib1** [comment]
This sounds a lot like https://github.com/nats-io/nats-server/issues/2042

**Comment by derekcollison** [comment]
This was implemented.
