### ISSUE TITLE
The "max_file_store" option cannot be quoted

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats-server#2754]
## Defect

The server does not process a quoted string of the `max_file_store` option.  It'd be great it if could.

```bash
$ cat quoted.conf 
jetstream {
  max_file_store: "200M"
}

$ nats-server -c quoted.conf
nats-server: quoted.conf:1:0: interface conversion: interface {} is string, not int64
```

Others like this should be checked as well...

**Comment by hooksie1** [comment]
I took a stab at this just because I saw the open issue. Let me know if its not the direction you want to go.

**Comment by hooksie1** [comment]
Ah I missed the "M" part. This doesn't address that.

**Comment by hooksie1** [comment]
Ok I added some logic around parsing the string with a size suffix. Only supports K, M, G, T.

**Comment by AqlaSolutions** [comment]
Is there any documentation on this?
