### ISSUE TITLE
Forwarding headers should not be trusted by default

### ISSUE THREAD

**Issue by philpennock** [nats-io/nats-server#2767]
## Defect

**SECURITY PROBLEM** in _unreleased_ code.

_nb: I was asked for review on the original but didn't see the request until a sweep just now, so this is partly on me for missing it, sorry._

Issue #2734 adds support for `X-Forwarded-For:` headers.  It does this always.  This means that anyone wishing to hide their tracks just needs to include a bogus `X-Forwarded-For:` header.  This is a well-known technique for getting around ACL/logging systems which are too permissive.

#### Versions of `nats-server` and affected client libraries used:

UNRELEASED, but anything including #2734 

`git tag --contains 67c345270cd2b9ba8b62afc2eebee473199b07e2` confirms this is still not in a released version.

#### Expected result:

There should be a configuration block enabling parsing of `X-Forwarded-For:` (XFF) headers, providing a set of CIDR netblocks which as "trusted".  Each purported proxy in turn appends their own idea of the origin IP.  If Mallory includes "X-Forwarded-For: 192.0.2.42" in the original request, then that will still be there when it reaches the target server.

We have to start at the very end (our idea of the origin IP without the header) and check that, then check the header working backwards, checking that it's allowed to tell us of a different origin IP.  And yes, people do chain proxies, particularly once CDNs come into play with ingress and egress XFF stamping.

So the correct algorithm is, in pseudocode:

```
def trusted_forwarder(ip):
  for block in trusted_cidrs:
    if block.family != ip.family:
      continue
    if block.contains(ip):
      return True
  return False

def set_source_ip(request):
  request.source_addr = request.network_source_addr
  if not trusted_forwarder(request.network_source_addr):
    return
  xff = request.headers.find('x-forwarded-for')  # case-insensitive, and consider multiple headers, check spec
  if not xff:
    return
  purported_ips = reverse(httphdr_commalist_split(xff))
  while len(purported_ips) > 1 and trusted_forwarder(purported_ips[0]):
    purported_ips.drop_first()
  request.source_addr = purported_ips[0]
```

A CIDR netblock such as `192.0.2.0/24` is the sanest unit of configuration for a trusted IP, and you can consider treating bare IPs as as /32, (and then there's IPv6 too).  Usually there's a _short_ list of netblocks, at most 3 entries, so it's probably not worth using a trie or anything for matching: just iterate the very short list of configured netblocks.

#### Actual result:

The `X-Forwarded-For:` header is trusted always.

**Comment by kozlovic** [comment]
@philpennock In case it makes a difference, this is just using for the logging of the client remote address in the log but is not used for any ACL or things like that, and is limited to only Websocket clients of course.
This seem quite a bit of changes (config to have CIDRs list, etc..) for just allowing logging of the actual application (when not used maliciously, which was the user request to see the app's IP instead of the proxy). Is that worth all that or should we revert the feature? (as you said it has not been released).

**Comment by philpennock** [comment]
I think for now, revert.  We could always log in _addition_, instead of replacing.

If we add IP ACL rules for the nats-server, then we will want to support this (and proxy protocol) so at that point will want a `trusted_proxies` configuration directive, so this can come back.

**Comment by kozlovic** [comment]
> We could always log in addition, instead of replacing.

I think that could be the best approach...

**Comment by kozlovic** [comment]
And I think I was wrong to say that it was just for logging.. I was using the header's value in c.host, which can be used for source validation, etc... 
I will submit a PR that alter the changes made in the PR and simply add to the logging, not change's c.host.
