### ISSUE TITLE
Getting NATS to work with a Traefik Ingress controller?

### ISSUE THREAD

**Issue by joeldeteves** [nats-io/nats-server#2768]
Hello, just wondering if anyone has managed to get NATS working from behind a [Traefik](https://github.com/traefik/traefik) ingress controller on Kubernetes.

I have configured a TCP Ingress Route in Traefik that points to the NATS service along with a catch-all entrypoint on port 4222 but it just results in an I/O timeout whenever I try to connect using the nats client.

However if I expose the NATS service as a Load Balancer, it works fine - but the problem with this setup  is it breaks the app I'm trying to deploy because it shares a domain name across multiple services.

Thank you,

**Comment by derekcollison** [comment]
In general we do not recommend placing a layer 7 router in between NATS clients and there servers. NATS has its own load balancing and routing and traffic shaping builtin as a core functionality.

**Comment by derekcollison** [comment]
If you feel this is a need for you, you could consider using websockets to connect across those layer 7 systems.

**Comment by joeldeteves** [comment]
> In general we do not recommend placing a layer 7 router in between NATS clients and there servers. NATS has its own load balancing and routing and traffic shaping builtin as a core functionality.

Thank you, I understand.

The problem is that this app I'm using utilizes NATS in its backend and it recycles the same domain 'api.mydomain.com' across multiple backend services.

So when I try to separate the NATS service out to a load balancer it results in a different IP, which of course breaks some of the other components.

I will cross post this issue over to the Traefik github and see if they can provide any sort of workaround.

Thanks again,

**Comment by derekcollison** [comment]
The app recycles the same domain? Not following. Help me understand what you are trying to achieve.

Thanks.

**Comment by joeldeteves** [comment]
> The app recycles the same domain? Not following. Help me understand what you are trying to achieve.
> 
> Thanks.

Hi there, the app uses ```api.mydomain.com``` (I redacted the actual domain for this example).

It has a front end that talks to the backend, but the backend also communicates to external agents which then talk back to the backend through NATS.

Therefore, when I change the A record for ```api.mydomain.com``` to point to the Load Balancer, it fixes my problem with NATS but it breaks the front end.

There are a few other components which relies on the ```api.mydomain.com``` domain to point to the same IP as well.

Hope that makes sense.

Thank you

**Comment by derekcollison** [comment]
Forming a NATS connection from any app should be stable as it can be. If you have only 1 NATS server then that should have a stable name both inside and outside of any deployment framework. 

If its a cluster, you can either use DNS with multiple A records, or only place 2 into DNS as a seed. Once a NATS application connects to a server it will be updated to the complete cluster topology on its own without needing DNS.

**Comment by joeldeteves** [comment]
Thanks for this info @derekcollison. Unfortunately it looks like the front-end sends a request directly from my workstation to ```api.mydomain.com``` when I log in.

Therefore, as soon as the A record is pointed to the NATS load balancer it results in an HTTP 400 error when logging in (it does fix the NATS connections though).

There might not be a way to do this without re-writing parts of the app unfortunately.

**Comment by joeldeteves** [comment]
Hello again @derekcollison - we ended up moving our NATS container and our NGINX container into the same pod, and then exposing them on their own service / load balancer (as one service; this way we can use the same domain to point to both services avoiding putting NATS thru a proxy).

Everything is working great now.

Thanks for your help.
