### ISSUE TITLE
Push consumer with queue group not working

### ISSUE THREAD

**Issue by alexschoeberl** [nats-io/nats-server#2773]
#### Versions of `nats-server` and affected client libraries used:

Starting nats-server
  Version:  2.6.3
  Git:      [530ea6a]
Starting http monitor on 0.0.0.0:8222
Listening for client connections on 0.0.0.0:4222

nats-box v0.6.0

#### Steps or code to reproduce the issue:

I subscribed to _INBOX.Evaluation.new with a queue:
nats --server=$SERVER sub --queue="0" "_INBOX.Evaluation.new"

Then I created this ephemeral push consumer:
Information for Consumer Evaluation > agfIx14I created 2022-01-10T12:15:15Z
Configuration:
    Delivery Subject: _INBOX.Evaluation.new
    Filter Subject: Evaluation.new
    Deliver All: true
    Ack Policy: Explicit
    Ack Wait: 30s
    Replay Policy: Instant
    Maximum Deliveries: 20
    Max Ack Pending: 5
    Flow Control: false
    Unprocessed Messages: 1

The Evaluation stream has a WorkQueue policy.

#### Result:

The unprocessed message never arrives. The consumer keeps existing, even after I stop the sub client.
However, if I subscribe without a queue group, it is working as expected.

**Comment by derekcollison** [comment]
Might I ask you to make sure the issue is still there with 2.6.6? Or the nightly builds?

**Comment by alexschoeberl** [comment]
I see the same behaviour on 2.6.6 / the latest docker image.

Here is the stream configuration:
Information for Stream Evaluation created 2022-01-10T13:50:36Z

Configuration:
     Subjects: Evaluation.*
     Acknowledgements: true
     Retention: File - WorkQueue
     Replicas: 1
     Discard Policy: New
     Duplicate Window: 10m0s
     Maximum Messages: 100
     Maximum Bytes: unlimited
     Maximum Age: 2d0h0m0s
     Maximum Message Size: 98 KiB
     Maximum Consumers: unlimited

State:
     Messages: 1
     Active Consumers: 2

I guess this should work. Or am I missing something?

**Comment by derekcollison** [comment]
With WQ stream I did not think you could create multiple consumers for some reason.

However, if you are trying to do a push based queue group consumer you need to tell the consumer itself about the queue group since it uses that to determine the appropriate interest vs just a plain sub on that subject. That is why they are not being delivered I believe.

**Comment by alexschoeberl** [comment]
What I would like is to have messages in the stream be distributed to one of multiple processes. Each message should only be processed/acked once. I would like to avoid pull-based consumption.

I tried to have one push-based consumer on the subject. The processes share a queue group and subscribe to the delivery subject. Since I don't need to keep the messages after they have been processed, I chose a WQ policy for the stream.

How can I tell the consumer about the queue group? I didn't see an option for this when creating the consumer.

**Comment by derekcollison** [comment]
This sounds to me like a good fit for pull based consumers, why the hesitation on using them?

You can do push based DQ. Just need to register the queue group with the consumer config.
Would also recommending setting MaxAckPending to a number that makes sense for you, since in this setup that is the flow control mechanism.

**Comment by alexschoeberl** [comment]
I decided against pull based consumers, because each of the processes is subscribed to multiple subjects. This does not work nicely with the request-reply pattern that the client libraries use for pull based consumers.

Ah ok, so there is a property called deliver_group on the consumer. I didn't see it in the schema.
https://github.com/nats-io/jsm.go/blob/main/schemas/jetstream/api/v1/consumer_create_request.json

Thanks!
