### ISSUE TITLE
Reduce minimum lame duck duration to 5 seconds

### ISSUE THREAD

**Issue by rytswd** [nats-io/nats-server#2796]
## Feature Request

Currently the lame duck duration is set to minimum of 30 seconds.
https://github.com/nats-io/nats-server/blob/297b44394f92e990da450178cffaa7adecc88837/server/opts.go#L970-L974

This causes a lot of noise when NATS is deployed with a service mesh sidecar, which has its own grace period much shorter than 30 seconds. Unless there is some absolute requirement for 30 second wait time, I'd like to propose shortening the minimum lame duck duration to as short as 5 seconds, or even remove such requirement.

#### Use Case:

When NATS clusters are deployed with additional service mesh sidecars such as Istio, they manage the networking in/outside the Pod. This causes the network traffic out from the main container fail if the sidecar is not running, and this happens at all the shutdown sequence, due to the lame duck duration enforced by the NATS server code.

#### Proposed Change:

It looks like the current 30 seconds is an arbitrary setup, so I'm proposing to reduce this requirement to 5 seconds, or even remove such requirement so that server admin can update as they like.

#### Who Benefits From The Change(s)?

Any server / cluster setup that involves a service mesh sidecar.

#### Alternative Approaches

NA

**Comment by derekcollison** [comment]
Both variables that control this behavior are already configurable at the top level of a config file.

`lame_duck_duration: 30s`
`lame_duck_grace_period: 5s`

Here is the comments from the server code and the default values for both. Will make sure the docs are updated as needed. /cc @gcolliso @jnmoyne 

```
	// DEFAULT_LAME_DUCK_DURATION is the time in which the server spreads
	// the closing of clients when signaled to go in lame duck mode.
	DEFAULT_LAME_DUCK_DURATION = 2 * time.Minute

	// DEFAULT_LAME_DUCK_GRACE_PERIOD is the duration the server waits, after entering
	// lame duck mode, before starting closing client connections.
	DEFAULT_LAME_DUCK_GRACE_PERIOD = 10 * time.Second
```

**Comment by rytswd** [comment]
@derekcollison Sorry I should have been clearer, I understand it's configureable, but cannot be configured to anything lower than 30s, which seems arbitrary. I'd like to stop the Pod as early as 5 seconds after SIGTERM, but when providing the top level config of `lame_duck_duration: 5s`, the server returned an error at startup that this hardcoded minimum 30 seconds.

**Comment by derekcollison** [comment]
Ah apologies. I understand now what you are asking.

I believe the system exits on its own once all clients are moved, so it will not take all of 30 secs if you have only a few clients.

**Comment by rytswd** [comment]
I can see that it shuts down after 20 sec or so for my setup, but it produces a lot of errors due to the sidecar dying earlier than NATS server. With NATS JS cluster setup in place, I get a lot of noisy "Error trying to connect to route ..." for RAFT communication, and I was just hoping to reduce that noise by setting a bit more aggressive shutdown if necessary.

**Comment by kozlovic** [comment]
@rytswd Did you change the grace period? That period is the time the server waits before starting to stop clients. By default it is 10 seconds, which if you did not lower means that nothing would happen for the first 10 seconds. This value has not really a minimum, except that if you set to 0 (or not set) then it uses default. So you could set it to as low as 1 millisecond if you think that can help `lame_duck_grace_period = "1ms"`.
Then, if you don't have many clients, closing those should be quicker than 30 seconds.

That being said, I have no objection removing this limit, but you have to understand that if it is too small for lots of clients, then that is not useful because clients will appear to be disconnected at the same time (and possibly reconnect at the same time).

**Comment by rytswd** [comment]
@kozlovic Thanks, I wasn't aware of that grace period until Derek mentioned of it, so tried it just now - it looks much faster to shut down indeed, and I could suppress the bulk of error messages with this!

For my specific use case, `lame_duck_grace_period` is the solution for me, so I don't require any update on the `lame_duck_duration`. I found it a little strange to force some default value though, so it may be worth removing the limit.
If we were to keep the current limit, it would be good to add a note about it on https://docs.nats.io/running-a-nats-service/configuration#runtime-configuration, along with the mention of `lame_duck_grace_period` which I think is missing in the doc.

**Comment by kozlovic** [comment]
@rytswd Done with https://github.com/nats-io/nats.docs/pull/362

**Comment by rytswd** [comment]
@kozlovic Thanks!
