### ISSUE TITLE
Stream editing with external source cause message multiplying in target stream

### ISSUE THREAD

**Issue by sargikk** [nats-io/nats-server#2801]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included `nats-server -DV` output
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

```
[118] 2022/01/19 14:35:06.298597 [INF] Starting nats-server
[118] 2022/01/19 14:35:06.298643 [INF]   Version:  2.7.0
[118] 2022/01/19 14:35:06.298647 [INF]   Git:      [not set]
[118] 2022/01/19 14:35:06.298654 [DBG]   Go build: go1.17.6
[118] 2022/01/19 14:35:06.298685 [INF]   Name:     NDGUT5AJFRTTN5SZAO765QM3XUPFISJQV7QX4WHYVBF7IZPBIFF7PDKE
[118] 2022/01/19 14:35:06.298694 [INF]   ID:       NDGUT5AJFRTTN5SZAO765QM3XUPFISJQV7QX4WHYVBF7IZPBIFF7PDKE
[118] 2022/01/19 14:35:06.298789 [DBG] Created system account: "$SYS"
```

#### Versions of `nats-server` and affected client libraries used:
nats-server 2.7.0
synadia/nats-box:0.6.0
#### OS/Container environment:
OS: Ubuntu 20.04.2
Docker image: nats:2.7.0-alpine3.15
#### Steps or code to reproduce the issue:
All steps a very similar to the official guide:
https://docs.nats.io/running-a-nats-service/configuration/leafnodes/jetstream_leafnodes#cross-account-and-domain-import
The only difference is that we have to create stream with source, not mirror.

1. Grant permissions like in official cross account guide
2. Create stream with external source, not mirror
3. Update any stream parameter via "nats stream edit", "Duplicate Window" or subjects for example
4. Send any message to source stream with appropriate subject

#### Expected result:

Get 1 message in target stream.

#### Actual result:

Get 2 copies of original message in target stream.
Each update of stream increases number of copies by one.

#### Possible reasons:
Issues #2202 #2209 that introduces iname for using multiple sources with same name.
More precisely old config sources collected by Name.
https://github.com/nats-io/nats-server/blob/297b44394f92e990da450178cffaa7adecc88837/server/stream.go#L1024
And new config sources than compares by iname.
https://github.com/nats-io/nats-server/blob/297b44394f92e990da450178cffaa7adecc88837/server/stream.go#L1028

#### Possible solutions:
Change s.Name to s.iname in:
https://github.com/nats-io/nats-server/blob/297b44394f92e990da450178cffaa7adecc88837/server/stream.go#L1024

### Workarounds
1. Restart server after each stream configuration
2. Provide Nats-Msg-Id for each message, but message copies take disk space and slow down server

**Comment by xieyuschen** [comment]
Hi @sargikk , did you mean that replace all `--mirror` to `--source` for the commands in the tutorial?
I runed the command by myself but didn't find such an issue. Could you give a more detailed command set when you encountered this bug?
Quite thanks

**Comment by matthiashanel** [comment]
@sargikk we believe the issue should be fixed now. Mind verifying with our latest release?
