### ISSUE TITLE
interface conversion: interface {} is string, not int64

### ISSUE THREAD

**Issue by pyprism** [nats-io/nats-server#2807]
I am trying to use v2.7.0.

Here is the config:
$ cat config.conf 
```
listen: "127.0.0.1:4222"
max_payload: "8MB"

authorization {
 token: "randomstrings"
  
}

jetstream {}

server_name: "nats.example.me"
log_file: "/tmp/nats.logs"
logfile_size_limit: "500MB"
```
When I tried to start using `./nats-server -c config.conf`  I got this errors:

```
nats-server: config.conf:13:1: interface conversion: interface {} is string, not int64
config.conf:2:1: interface conversion: interface {} is string, not int64
```

**Comment by kozlovic** [comment]
@pyprism We would need to have a "pass" at all configuration fields that represent a size in bytes and support both the int64 and string representation. There was a PR recently that did that for 2 fields in JetStream: https://github.com/nats-io/nats-server/pull/2777.
We could expand on that one and likely also improve the suffix detection, which is right now very simple `K`, 'M', 'G', 'T', anything else and it would fail.

**Comment by kozlovic** [comment]
Oh, so to answer your question, as of now, it has to be a number, which is the value in bytes without suffixes. So 8MB would be `8388608` (8*1024*1024)

**Comment by pyprism** [comment]
Thank you so much, it works.
