### ISSUE TITLE
Securing stream management

### ISSUE THREAD

**Issue by SkinnySackboy** [nats-io/nats-server#2820]
Hi,

First of all, great job with JetStream. We are long time NATS (Core) users and have recently started prototyping a new project with JetStream. It's hard to understate how happy we are with it, it's almost like it was built just for us. In just a few days we were able to experiment with a replacement for a decade of disparate custom legacy systems, and it just worked. It's brilliant.

On to the question - our use case will require managing (creating, purging, destroying) streams dynamically in code. We are successfully doing this programmatically, so far so good. The question we've got is around security. I'm aware it is possible to secure subjects, but is it possible to secure the management of streams? As in, is it possible to control which user can physically alter the definition of a stream or its subjects programmatically, as I wasn't able to find this in the documentation?

Thanks again

**Comment by derekcollison** [comment]
Thanks for the feedback, always appreciated and nice to hear!

For the JetStream API, we have tried to make the API subject space such that you can use subject permissions to lock pretty much everything down. Happy to provide some guidance here as well.

So for example in creating a stream, that subject is `$JS.API.STREAM.CREATE.<STREAM_NAME>`, so restricting access to that subject will prevent users from being able to create a stream.

The complete API subject list can be found here in code, and we are working hard to increase docs coverage for JetStream.

https://github.com/nats-io/nats-server/blob/main/server/jetstream_api.go#L47

We also have users that utilize account isolation and only export what they want to share for an added level of security.

**Comment by SkinnySackboy** [comment]
Thanks, we'll have a go and let you know if we still can't figure it out.
