### ISSUE TITLE
Stream restore to new name does not calculate NumSubjects

### ISSUE THREAD

**Issue by ripienaar** [nats-io/nats-server#2850]
## Defect

Applying this change to the test suite in order to test restoring a snapshot to a stream with a new name than the original results in the NumSubjects not being calculated:

```
diff --git a/server/jetstream_test.go b/server/jetstream_test.go
index 062750d4..22981e33 100644
--- a/server/jetstream_test.go
+++ b/server/jetstream_test.go
@@ -4479,6 +4479,7 @@ func TestJetStreamSnapshotsAPI(t *testing.T) {
 		t.Fatalf("Expected restore subscription to be closed")
 	}
 
+	rreq.Config.Name = "new_name"
 	req, _ = json.Marshal(rreq)
 	rmsg, err = nc2.Request(strings.ReplaceAll(JSApiStreamRestoreT, JSApiPrefix, "$JS.domain.API"), req, time.Second)
 	if err != nil {
@@ -9292,10 +9293,10 @@ func TestJetStreamPushConsumersPullError(t *testing.T) {
 	}
 }
```

The error is

```
    jetstream_test.go:4520: Did not match states, {Msgs:1 Bytes:46 FirstSeq:1 FirstTime:2022-02-08 07:32:24.191984 +0000 UTC LastSeq:1 LastTime:2022-02-08 07:32:24.191984 +0000 UTC NumSubjects:0 Subjects:map[] NumDeleted:0 Deleted:[] Lost:<nil> Consumers:1} vs {Msgs:1 Bytes:46 FirstSeq:1 FirstTime:2022-02-08 07:32:24.191984 +0000 UTC LastSeq:1 LastTime:2022-02-08 07:32:24.191984 +0000 UTC NumSubjects:1 Subjects:map[] NumDeleted:0 Deleted:[] Lost:<nil> Consumers:1}
```

You can see NumSubjects is 0 should be 1, this only happens when restoring to a new name.

**Comment by derekcollison** [comment]
Changing the name currently does not do the right thing since all the message checksums/hashes will be wrong.

Will take a look and see what we can possibly do, but we will have to rewrite every message block on a restore to redo all hashes to the new key (name).

**Comment by ripienaar** [comment]
Hmm ok. Its the only way to rename but I can prevent that for now if you think it’s a huge deal?

Need to release a cli version that supports recent breaking changes to api 

---
R.I.Pienaar

**Comment by derekcollison** [comment]
Its tied so much to the identity of the stream, that changing it is a form of tampering in some respects. Will make sure you can't change it for now and we can revisit. It would involve scanning and checking every message hash and then recalculating a new one and rewriting each message block back up during a restore.

**Comment by ripienaar** [comment]
OK, then I will remove the CLI feature and error out, that'll unblock  me to ship a update then for friday

**Comment by derekcollison** [comment]
Resolved with https://github.com/nats-io/nats-server/commit/0cc7302be9bc37f0ee45f480e4e4a458b3bb62bf
