### ISSUE TITLE
topic count limitation

### ISSUE THREAD

**Issue by carr123** [nats-io/nats-server#2851]
hi, i can't access NATS Slack, so ask questions here.
is there any topic count limitation in a single nats cluster ?
when more server nodes can be added to the cluster, can it sustain 10 million subscriptions ?

**Comment by derekcollison** [comment]
Why can't you access Slack? Can we send a proper link or invite?

There is a subject limit for a server but can be set to anything you want, juts uses memory.
Many times architectures will have lots of subjects but fewer subscriptions through the use of wildcards and aggregation etc.

**Comment by carr123** [comment]
hi, i am developing a IoT platform. currently we have 10,000 devices, maybe the device count can increase to 1M or 10M or more.  communications are bidirectional between devices and servers.
I want the system to be horizontally scalable as the data traffic grows.
here is my solution:
a. develop my own access-server, it's exposed to IoT devices. it 's stateless and scalable.  it acts as a nats client.
 it translates data between nats cluster and devices. 
b. deploy a single nats cluster.  using pub/sub for communication. 
c. each device will subscribe an unique subject, as we need send commands to a specific device.

i double, whether this design is really horizontally scalable or can sustain data traffic as more devices join in.
if not, do you have any better ideas ?

(due to ISP restrications, i can't access slack, youtube, twitter ... )

**Comment by derekcollison** [comment]
Short answer is yes you can do that. 

I would put the UUID (or equivalent) of the device into the subject and have a wildcard subject for the backend so as to not have number of subs scale with number of devices.

Happy to jump on a call or Zoom to discuss if you think it might help.

**Comment by carr123** [comment]
thanks.  currently, my design is server side subscribes on a wildcard subject, waiting for messages from devices, and each device subscribes its on an uniqe subject(devid as part of the subject) waiting for messages from the server side.

**Comment by derekcollison** [comment]
I would not introduce topology changes or additions due to subscriptions being high.

**Comment by carr123** [comment]
thanks.
