### ISSUE TITLE
How does load balancing work in JetStream?

### ISSUE THREAD

**Issue by seaguest** [nats-io/nats-server#2853]
hi, 

anyone knows how does the load balancing work in jetstream?

I have 3 nodes, if I have only one stream, no matter how many subjects I dispatched messages to, only one node seems on working(and from storage directory I saw it /data/nats/jetstream/\$G/streams/api/), does that mean I should create as many streams as possible in stead of subjects to make the 3 nodes work in balance?

**Comment by derekcollison** [comment]
Are you referencing putting messages into a stream or taking them out via a consumer?

A replicated stream will select a leader via a RAFT algorithm to be authoritative on the sequencing. The other members of the stream will replicate.

For consumers, they need to overlay the peer group for the stream but should be distributed across all stream peers.

**Comment by seaguest** [comment]
@derekcollison 

Publishing messages.

Currently the replicas=1, the behavior is described as above, when I change it to 3, then 3 nodes all work.

I am looking for a best practice for creating streams, should I create as many streams as possible or subject instead? which way is recommended?

**Comment by derekcollison** [comment]
We generally recommend grouping subjects together in a stream vs individual streams if the message grouping makes sense.
