### ISSUE TITLE
embedding nats server

### ISSUE THREAD

**Issue by carr123** [nats-io/nats-server#2866]
hello, when i embed nats server functionality into my own golang project, can i configure nats server not listening on the TCP port (default 4222), instead using golang functions provided by the nats server library to directly talk to it ?   since my code and nats server are now in the same process.
(the tcp port for cluster communication are still needed)

**Comment by derekcollison** [comment]
Not at this time but there is another issue opened around this and a branch with a pipe impl.

**Comment by derekcollison** [comment]
https://github.com/nats-io/nats-server/pull/2360
