### ISSUE TITLE
JetStream $SYS folder keep growing

### ISSUE THREAD

**Issue by nayanparegi** [nats-io/nats-server#2885]
When we create a consumer with filter subject and that subject never got published the consumer sequence remain to 0 and raft folder size for that consumer will grow indefinitely.

**Comment by derekcollison** [comment]
What server version please?
Can you provide more information on the system setup, topology and stream that the consumer is attached to?

**Comment by nayanparegi** [comment]
@derekcollison  we are using 2.7.2.

We are running NATS inside the Kubernetes cluster.

The scenario is like below:
Stream Name: StreamA

Two different services running inside the Kubernetes cluster. Service A is subscribing to MessageA and Service B is subscribing to MessageB using durable subscription with filter subject StreamA.MessageA and StreamB.MessageB.

The different service is publishing MessageA and MessageB. However, frequency of MessageB is very rare, sometime once a week or two. Frequency of MessageA is around 10000 messages per minute.

Now when I look at the storage it is continuously growing unless I receive the any message for subject "MessageB"

When I tried to look at the storage, I found that RAFT group created for consumer for MessageB is growing in storage until it receives the message.

**Comment by derekcollison** [comment]
Can you send us `nats stream info` for that stream and `nats consumer info` for all consumers as well?

Also, there is a fix for staggered but filtered consumers on retention policy streams that was released with 2.7.3, so might be worth considering upgrading if your environment allows.

**Comment by nayanparegi** [comment]
@derekcollison  thanks for your reply. Below is the detail:

Connection Information:

               Client ID: 16718
               Client IP: 127.0.0.1
                     RTT: 152.6145ms
       Headers Supported: true
         Maximum Payload: 2.0 MiB
       Connected Cluster: nats
           Connected URL: nats://127.0.0.1:4222
       Connected Address: 127.0.0.1:4222
     Connected Server ID: NB3A3UAAEU26SGWXD464LT6OKPOQGBTU3PSHTSCN64NFANYPVC5EK4JL
   Connected Server Name: nats-2

JetStream Account Information:

           Memory: 0 B of 1.0 GiB
          Storage: 1.1 GiB of 102 GiB
          Streams: 2 of 10
        Consumers: 1,962 of Unlimited


And below is consumer which is having an issue:

Configuration:

        Durable Name: ********
         Description: ********
    Delivery Subject: _INBOX.WRFfN0AJ4FUjGYhwiQd9I_
      Filter Subject: ********
      Deliver Policy: All
 Deliver Queue Group: ********
          Ack Policy: Explicit
            Ack Wait: 1m0s
       Replay Policy: Instant
     Max Ack Pending: 20,000
        Flow Control: false

Cluster Information:

                Name: nats
              Leader: nats-0
             Replica: nats-1, current, seen 0.37s ago
             Replica: nats-3, current, seen 0.37s ago
             Replica: nats-2, current, seen 0.37s ago

State:

   Last Delivered Message: **Consumer sequence: 0** Stream sequence: 3,812,913
     Acknowledgment floor: Consumer sequence: 0 Stream sequence: 0
         Outstanding Acks: 0 out of maximum 20,000
     Redelivered Messages: 0
     Unprocessed Messages: 0
          Active Interest: Active using Queue Group ********

I will try the new version in one of the QA env and try to reproduce issue there.

**Comment by nayanparegi** [comment]
@derekcollison  I have tried with the latest version in QA. However, it seems not working as expected. I am not able to generate the same load as production, but seems not cleaning up the sys folder.

**Comment by derekcollison** [comment]
Since no messages have been delivered I would suggest deleting and recreating the consumer.

May I ask architecturally why so many consumers? Are they all independent and all processing the same messages or do you use filters to break up the stream messages?

**Comment by nayanparegi** [comment]
@derekcollison I can delete the consumer but there are many consumers, and it will be temporary fix. 

We are using Microservice architecture and there are many services which listen for specific messages (Filter Subject), so those services are creating durable consumers for different type of messages. Some services are aggregation services which listen many messages and right now there is no wildcard pattern I can use so all those services are having multiple consumers with different filter subject.  Are there any issues if we create so many consumers?

**Comment by derekcollison** [comment]
Is the stream work queue or interest based policy and are the consumers durable or ephemeral?

**Comment by nayanparegi** [comment]
@derekcollison  around 100 consumers are durable and other are ephemeral. The RAFT group that are having disk size issue are all of durable consumers.

Regarding Stream work Queue or Interest Based Policy, I am not getting how we can get that information. Below is stream information.

`Configuration:

             Subjects: lf.*
     Acknowledgements: true
            Retention: File - Limits
             Replicas: 4
       Discard Policy: Old
     Duplicate Window: 2m0s
    Allows Msg Delete: true
         Allows Purge: true
       Allows Rollups: false
     Maximum Messages: unlimited
        Maximum Bytes: unlimited
          Maximum Age: 3h0m0s
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited


Cluster Information:

                 Name: nats
               Leader: nats-0
              Replica: nats-2, current, seen 0.04s ago
              Replica: nats-1, current, seen 0.04s ago
              Replica: nats-3, current, seen 0.04s ago

State:

             Messages: 61,141
                Bytes: 100 MiB
             FirstSeq: 4,946,503 @ 2022-03-02T23:42:09 UTC
              LastSeq: 5,007,643 @ 2022-03-03T02:42:01 UTC
     Active Consumers: 286`

Even if you look at the size in above it says 100MB
and account info says

`JetStream Account Information:

           Memory: 0 B of 1.0 GiB
          Storage: 465 MiB of 102 GiB
          Streams: 2 of 10
        Consumers: 1,213 of Unlimited`

But the storage of PV is 13GB.

**Comment by derekcollison** [comment]
From the info this is the line I was looking for..

**Retention: File - Limits**

Please if you do not mind send me `ls -a` of the ./sys directory to my email, derek@nats.io.

**Comment by nayanparegi** [comment]
@derekcollison I have shared the requested details on your email.
