### ISSUE TITLE
Add NIST recommended crypto algorithm for encryption at rest

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats-server#2909]
## Feature Request

A Synadia customer requested the following:

> ...is there a plan to support more cryptographic algorithms for Encryption at Rest? As of today there are only ChaCha-based ones which are not endorsed by NIST and, I think, other organisations (e.g. ENISA). Are there any plans to add AES-based ciphers?

#### Proposed Change:

Add support for NIST recommended algorithms, preferably an AES algorithm but will defer to @philpennock.

#### Who Benefits From The Change(s)?

Users who need to adhere to NIST standards.

**Comment by derekcollison** [comment]
We added AES support awhile back.

**Comment by gedw99** [comment]
AES-128, AES-192, and AES-256 ?

**Comment by derekcollison** [comment]
We use 32 byte hashes for our seeds, so AES-256.
