### ISSUE TITLE
Ability to use TLS connection right away

### ISSUE THREAD

**Issue by kozlovic** [nats-io/nats-server#291]
Even if the server and clients are configured to use TLS, the first protocol message sent from the server to the client(s) is in plain text.

That is, when a client initiates the tcp connection, the server when accepting it, sends its `INFO` protocol message in plain text. This prevents the use of some ssl clients (tooling?) or haproxies that require only TLS traffic.

If this is accepted, all clients supporting TLS would need to be changed.

**Comment by edsiper** [comment]
:+1:

**Comment by dramdass** [comment]
Thanks for filing this. This would also enable tls SNI routing of the box.

**Comment by nogoegst** [comment]
How it can be fixed properly without giant disruptions?
The change in server is just one line, though there are many clients. It should be a major version bump, I guess?

**Comment by kozlovic** [comment]
@nogoegst Agreed that the implications are big. To be honest, this issue was created when users started to experiment with writing their own client or try to debug TLS connections and assumed that the TLS connection was setup right away, when in fact, the server first sends its INFO protocol in plain text. There was also a comment that this would help for TLS SNI routing.

Regardless, if we implement this, it would have to be an option to start the server in such mode. It also means that clients would need an option to instruct them to setup the TLS connection right away.

**Comment by nogoegst** [comment]
@kozlovic Sending any _unauthenticated data_ is definitely not good. :slightly_smiling_face:

How about implementing  mode for normal TLS connections now which can be enabled via some flag? Then in some major version this can become default.

**Comment by nogoegst** [comment]
@ColinSullivan1 I have fixes for all the clients listed under github.com/nats-io/ already. I am looking forward fixing this issue rather sooner than later . Should I create PRs to these repos and link them to this issue?

**Comment by ColinSullivan1** [comment]
@nogoegst , can you open a PR for the [go-nats](https://github.com/nats-io/go-nats) client first, and we can review?

**Comment by doubliez** [comment]
I have set up gnatsd with TLS disabled behind an ELB configured to do TLS termination. I'm not sure if the server issue applies to me (gnatsd is not aware of TLS in my case, traffic between the ELB and gnatsd is in plain text), however I need the ability for clients to initiate a TLS connection right away (as required by the ELB). I opened an issue about that in [node-nats](https://github.com/nats-io/node-nats) (https://github.com/nats-io/node-nats/issues/232).

Is there a timeline on when this will be made possible?

**Comment by derekcollison** [comment]
We will be introducing websocket based transport clients in the future and these can be TLS direct. Will most likely not update core client connections behavior.

**Comment by derekcollison** [comment]
Possibly, but all NATS clients who support TLS do the upgrade. All clients would need to be changed. I'd rather introduce new transports to some clients and have the transport, WS in this case work via TLS from the beginning.

**Comment by antonioaguilar** [comment]
@derekcollison any update on when we could expect the NATS websocket transport? I'm particularly interested on a browser websocket NATS client. Currently, we have to rely on [websocket-nats](https://github.com/isobit/websocket-nats), [ws-nats](https://www.npmjs.com/package/ws-nats) [nats-websocket-gw](https://github.com/orus-io/nats-websocket-gw) and similar library variants.

**Comment by derekcollison** [comment]
Targeting 1H 2019.

**Comment by saadtazi** [comment]
If you are looking for a solution to use TLS right away with the python 3 client, I created a [gist](https://gist.github.com/saadtazi/6ff02f3b38a2bdebbcc28acbe7885145) that worked for us.

**Comment by wallyqs** [comment]
@saadtazi thanks for sharing, interesting...

**Comment by paravz** [comment]
I found this issue while trying to use TLS for ALL traffic between nats client (latency-test) and nats server (v2.0.0), including the initial INFO message. 

I failed so far as changing client alone is not enough, as TLS configured nats server doesn't support such a connection, i get server error message when initial connection in client is `tls.Dial`:
```
[DBG] 127.0.0.12:57804 - cid:4 - Client connection created
[DBG] 127.0.0.12:57804 - cid:4 - Starting TLS client connection handshake
[ERR] 127.0.0.12:57804 - cid:4 - TLS handshake error: tls: received record with version 301 when expecting version 303
[DBG] 127.0.0.12:57804 - cid:4 - Client connection closed
```

PS: more careful reading confirms that in scenario that worked, nats server was not TLS enabled, only ELB in front of it was, thus client only change was enough in that case

**Comment by derekcollison** [comment]
INFO messages to clients are always sent plaintext from server to client on initial connect, even when TLS is required by the server. Therefore NATS does not work well with network proxies that do not proxy direct traffic.

**Comment by azixaka** [comment]
The issue means we can't use NATS in OpenShift as was discovered today. Very unfortunate.

**Comment by derekcollison** [comment]
Any proper layer 4 router will work, but layer 7 routers and load balancers most likely will not. However, again, I would recommend not putting network elements like proxies or load balancers in between NATS clients and servers.

If you absolutely think you must, use a proper layer 4 technology, like HAProxy.

We will do websockets and they will be TLS first. Target is for Q1.

**Comment by tino** [comment]
Given that websocket connections are in, is this now on the table?

I understand that "one should preferably not load balance nats", but adding direct TLS connection (as a default off option to start with) does seem like a good way for people to more easily introduce nats into their infrastructure. 

It would also make it possible to do simple telnet based inspection on a TLS enabled client by terminating the TLS first (locally). (And make this TLS setup a bit less confusing in general I think.)

**Comment by palsivertsen** [comment]
Found this issue while trying to utilize AWS ELB to expose a cluster publicly (nats only, no leafnode, cluster or gateway protocols).

The ACM service can issue certificates for use by other services, but does not expose any keys. This makes it quick and easy to set up secure connections with TLS termination in in the ELB and no messing about with maintaining certificates. Setting things up this way enforces clients to connect using normal TLS and cluster nodes will receive traffic in normal plaintext.

Could be solved by adding support for a new protocol in clients:
```
nats sub -s truetls://demo.nats.io:4443 --trace asd
```
Any client configured with `tls` protocol will use today's handling where the first message is a plaintext `INFO` message and any client using `truetls` protocol will set up TLS right away.

**Comment by yuriyyakym** [comment]
Guys, if you still struggle with this issue, consider using [patch-package](https://www.npmjs.com/package/patch-package). And here is my patch (just single line replacement) for `nats@2.2.0`:
File: `patches/nats+2.2.0.patch`
```js
diff --git a/node_modules/nats/lib/src/node_transport.js b/node_modules/nats/lib/src/node_transport.js
index 7360311..441c8b0 100644
--- a/node_modules/nats/lib/src/node_transport.js
+++ b/node_modules/nats/lib/src/node_transport.js
@@ -97,7 +97,7 @@ class NodeTransport {
     dial(hp) {
         const d = nats_base_client_1.deferred();
         let dialError;
-        const socket = net_1.createConnection(hp.port, hp.hostname, () => {
+        const socket = tls_1.connect(hp.port, hp.hostname, () => {
             d.resolve(socket);
             socket.removeAllListeners();
         });

```

You can, of course, create a better patch with a support of an additional flag passed through options, if needed.

**Comment by yuriyyakym** [comment]
For node.js client consider using package patching as described here: https://github.com/nats-io/nats.js/issues/369#issuecomment-912877897

**Comment by derekcollison** [comment]
Websockets which are supported in several clients, and most importantly can be used as a leafnode connection satisfy this requirement.
