### ISSUE TITLE
Jetstream can't restore after a network breakdown

### ISSUE THREAD

**Issue by wchajl** [nats-io/nats-server#2912]
I’m deploying a Jetstream cluster with 3 nodes in k8s.
It occurs that Jetstream doesn’t work after a network breakdown . 
The same issue occurred yesterday. And it can only resume after manual restarting the  servers.
![Uploading image.png…]()

**Comment by wchajl** [comment]
![MobaXterm_KFJ0WSUM46](https://user-images.githubusercontent.com/42642319/157393609-93948a18-789d-4948-9d05-c33393c07d54.png)

**Comment by ripienaar** [comment]
Please try to copy and paste the logs or download or something. Best to see all the logs

**Comment by wchajl** [comment]
@ripienaar
[idms-dev-nats-2.log](https://github.com/nats-io/nats-server/files/8212710/idms-dev-nats-2.log)

**Comment by ripienaar** [comment]
Thanks that will help so so e look into it

**Comment by derekcollison** [comment]
Which version of the server?

**Comment by kozlovic** [comment]
@wchajl Few questions:
- What type of consumers are you using? push or pull?
- If push, did not notice a lot of pending messages on those? (with `nats c report` or `nats c info` on a particular one)
- Would you be willing to capture some stack traces of the remote servers (not necessarily the one where you see the route slow consumer, but the other side, or both if they both complain)? I notice that you run v2.7.3 and have the monitoring port enabled, so that would mean hitting the `http://host:port/stacksz` endpoint. Alternatively, you could run with the `-profile <port>` enabled and then we can use `go tool pprof http://host:<profile port>/debug/pprof/profile?seconds=5` and you could send us the output file or check it yourself.

If the slow down is due to ack processing on the other side, then PR https://github.com/nats-io/nats-server/pull/2898 will help, but it is not yet merged.

**Comment by wchajl** [comment]
@derekcollison @kozlovic @ripienaar 
thanks for your reply.
we're using nats:2.7.3-alpine. Since the cluster is in use, I just killed these pods to resume. and here are some things may be helperful.
> we are using push consumer.and I noticed there is a lot of pending msgs in the consumer.
> the cluster never restored. subscription from one node can't get msg from another node.
> when publishing msg to the stream ,I wont get response.and it just report "no responder" error.
> stream in other account can be inspected.

**Comment by wchajl** [comment]
@kozlovic
I resumed this cluster by killing the pods  yesterday, so I'm afraid that I cant  get  the stack information . 
+ We are using push consumer. 
+ After restarting the cluster ,  I got the info of consumers  .  There are  losts of messages , but I can't be sure it was the same 
 since jetstream api didn't work that time . I will save the stack log when it happens again.
+ I had tried to  use natscli to sub a subject from one node and pub  a msg from another in that cluster ,and nothing was received. It seems that the cluster connections wouldn't work that time. And when I tried to send  msgs  to a stream , it would report  "no responder" errror, meanwhile stream  in another account can be inspected.

**Comment by bajoben** [comment]
Is this related https://github.com/nats-io/nack/issues/64

**Comment by wchajl** [comment]
@kozlovic 
It  happens again.
[nats-log.log](https://github.com/nats-io/nats-server/files/8312867/nats-log.log)
[stacksz.log](https://github.com/nats-io/nats-server/files/8312868/stacksz.log)

**Comment by kozlovic** [comment]
Also, I would strongly recommend that you use the latest release, since version 2.7.3 had some issues.

**Comment by wchajl** [comment]
@kozlovic 
Thanks for your reply.
We deployed nats-server in three k8s clusters with the storage class of ceph . And the same issue happened in all clusters.
I've updated nats-server to 2.7.4. 
But the jetstream in one cluster seems to be corrupted , I'm not sure whether it's the same cause.  One node in the cluster restores while the other 2 failed and keep restarting,and they cant get restored event after  manually killing them.  
The logs indicates  that there was a panic: corrupt state file . 
I'm pretty confused,could you please give me some suggestions on how to restore the jetstream ? thanks!
[stacksz.log](https://github.com/nats-io/nats-server/files/8329045/stacksz.log)
[nats-1.log](https://github.com/nats-io/nats-server/files/8329046/nats-1.log)
[nats_0_stacksz.log](https://github.com/nats-io/nats-server/files/8329048/nats_0_stacksz.log)
[nats0_previous.log](https://github.com/nats-io/nats-server/files/8329049/nats0_previous.log)

**Comment by derekcollison** [comment]
We need to verify that the ceph setup is correct and the system is not inadvertently sharing the same directory/file from multiple servers.

We have a few folks on our side who are more versed in ceph, and k8s than I.

/cc @philpennock @bwerthmann @caleblloyd

**Comment by kozlovic** [comment]
@wchajl Looks like the 2 stacks that you provided show that the server is actively recovering the state since the routine reading blocks has no indication that it is blocked:
```
goroutine 1 [syscall]:
syscall.Syscall(0x0, 0x7, 0xc004734000, 0xfff12b)
	/home/travis/.gimme/versions/go1.17.8.linux.amd64/src/syscall/asm_linux_amd64.s:20 +0x5
syscall.read(0xc0003098c0, {0xc004734000, 0x0, 0x42c0a0})
	/home/travis/.gimme/versions/go1.17.8.linux.amd64/src/syscall/zsyscall_linux_amd64.go:687 +0x4d
syscall.Read(...)
	/home/travis/.gimme/versions/go1.17.8.linux.amd64/src/syscall/syscall_unix.go:189
internal/poll.ignoringEINTRIO(...)
	/home/travis/.gimme/versions/go1.17.8.linux.amd64/src/internal/poll/fd_unix.go:582
internal/poll.(*FD).Read(0xc0003098c0, {0xc004734000, 0xfff12b, 0xfff12b})
	/home/travis/.gimme/versions/go1.17.8.linux.amd64/src/internal/poll/fd_unix.go:163 +0x285
os.(*File).read(...)
	/home/travis/.gimme/versions/go1.17.8.linux.amd64/src/os/file_posix.go:32
os.(*File).Read(0xc0000b00f0, {0xc004734000, 0xc00016b9b8, 0x44c512})
	/home/travis/.gimme/versions/go1.17.8.linux.amd64/src/os/file.go:119 +0x5e
io.ReadAtLeast({0xaf18e0, 0xc0000b00f0}, {0xc004734000, 0xfff12b, 0xfff12b}, 0xfff12b)
	/home/travis/.gimme/versions/go1.17.8.linux.amd64/src/io/io.go:328 +0x9a
io.ReadFull(...)
	/home/travis/.gimme/versions/go1.17.8.linux.amd64/src/io/io.go:347
github.com/nats-io/nats-server/v2/server.(*msgBlock).loadBlock(0xc0000001a0, {0x0, 0x0, 0x0})
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/filestore.go:3236 +0x136
github.com/nats-io/nats-server/v2/server.(*msgBlock).loadMsgsWithLock(0xc001571860)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/filestore.go:3282 +0x2e9
github.com/nats-io/nats-server/v2/server.(*msgBlock).generatePerSubjectInfo(0xc001571860)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/filestore.go:4415 +0xef
github.com/nats-io/nats-server/v2/server.(*msgBlock).readPerSubjectInfo(0xc001571860)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/filestore.go:4467 +0x394
github.com/nats-io/nats-server/v2/server.(*fileStore).recoverMsgBlock(0xc000392280, {0xaffff8, 0xc00028bba0}, 0x13c5)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/filestore.go:611 +0xff0
github.com/nats-io/nats-server/v2/server.(*fileStore).recoverMsgs(0xc000392280)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/filestore.go:881 +0x858
github.com/nats-io/nats-server/v2/server.newFileStoreWithCreated({{0xc000228750, 0x25}, _, _, _, _}, {{0xc000233370, 0x9}, {0x0, 0x0}, ...}, ...)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/filestore.go:318 +0x774
github.com/nats-io/nats-server/v2/server.(*stream).setupStore(0xc000392000, 0xc00016ca90)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/stream.go:2459 +0x2d5
github.com/nats-io/nats-server/v2/server.(*Account).addStreamWithAssignment(0xc000127d40, 0xc000380018, 0x0, 0x0)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/stream.go:413 +0xdcb
github.com/nats-io/nats-server/v2/server.(*Account).addStream(0xc000233380, 0xc000232930)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/stream.go:264 +0x1d
github.com/nats-io/nats-server/v2/server.(*Account).EnableJetStream(0xc000127d40, 0xe0a3a0)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream.go:1159 +0x2be5
github.com/nats-io/nats-server/v2/server.(*Server).configJetStream(0xc0001c6000, 0xc000127d40)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream.go:630 +0x9c
github.com/nats-io/nats-server/v2/server.(*Server).configAllJetStreamAccounts(0xc0001c6000)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream.go:677 +0x176
github.com/nats-io/nats-server/v2/server.(*Server).enableJetStreamAccounts(0xc00024e370)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream.go:563 +0xb1
github.com/nats-io/nats-server/v2/server.(*Server).enableJetStream(0xc0001c6000, {0x40000000, 0x3200000000, {0xc000232450, 0xf}, {0xc00019e99d, 0xb}})
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream.go:377 +0x919
github.com/nats-io/nats-server/v2/server.(*Server).EnableJetStream(0xc0001c6000, 0xc00016de38)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream.go:189 +0x40c
github.com/nats-io/nats-server/v2/server.(*Server).Start(0xc0001c6000)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/server.go:1759 +0xf65
github.com/nats-io/nats-server/v2/server.Run(...)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/service.go:22
main.main()
	/home/travis/gopath/src/github.com/nats-io/nats-server/main.go:118 +0x2fa
```

Between stacksz.log and nats_0_stacksz.log (which is from the same server), I see a 2 minutes difference in other go routines, but that specific go routine does not show being stuck in one system call, hence my assumption that it is actively recovering.

The nats-1.log shows that it is isolated from the other servers, or that there are routes that are no longer reachable:
```
[12] 2022/03/22 11:21:59.255414 [DBG] Trying to connect to route on idms-native-test-nats-2.idms-native-test-nats.idms-nats.svc.cluster.local:6222 (100.101.145.66:6222)
[12] 2022/03/22 11:21:59.256652 [ERR] Error trying to connect to route (attempt 3923): dial tcp 100.101.145.66:6222: connect: connection refused
[12] 2022/03/22 11:21:59.340148 [DBG] Trying to connect to route on idms-native-test-nats-0.idms-native-test-nats.idms-nats.svc.cluster.local:6222 (100.101.138.72:6222)
[12] 2022/03/22 11:21:59.340604 [ERR] Error trying to connect to route (attempt 255): dial tcp 100.101.138.72:6222: connect: connection refused
```

Regarding the logs, nats0_previous.log, which shows that it started and is a 2.7.4 server, took more than 20 minutes to recover the state for about 10 million messages and 5 consumers:
```
[7869] 2022/03/22 10:55:30.843584 [DBG] Recovering JetStream state for account "CEC"
[7869] 2022/03/22 11:17:41.990194 [INF]   Restored 9,902,004 messages for stream 'CEC > cecstream'
[7869] 2022/03/22 11:17:41.990948 [INF]   Recovering 5 consumers for stream - 'CEC > cecstream'
```
It also shows the panic decoding the consumer state:
```
[7869] 2022/03/22 11:17:42.773338 [DBG] Starting consumer monitor for 'CEC > cecstream > eventPersister2' [C-R3F-YzqQD7aI]
(...)
[7869] 2022/03/22 11:17:42.804898 [ERR] JetStream cluster could not decode consumer snapshot for 'CEC > cecstream > eventPersister2' [C-R3F-YzqQD7aI]
[7869] 2022/03/22 11:17:42.804939 [DBG] Exiting consumer monitor for 'CEC > cecstream > eventPersister2' [C-R3F-YzqQD7aI]
panic: corrupt state file

goroutine 4603 [running]:
github.com/nats-io/nats-server/v2/server.(*jetStream).applyConsumerEntries(0xc0001306e0, 0xc000221000, 0x0, 0x0)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:3167 +0x79c
github.com/nats-io/nats-server/v2/server.(*jetStream).monitorConsumer(0xc000174000, 0xc000221000, 0xc002226a20)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:3134 +0x835
github.com/nats-io/nats-server/v2/server.(*jetStream).processClusterCreateConsumer.func1()
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:2923 +0x25
created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/server.go:3024 +0x87
```
I will let @derekcollison comment on that on what could be done to skip that (maybe delete the corresponding consumer directory?)

Finally, you mentioned that you have deployed in 3 different k8s clusters, are you saying that you have 3 NATS clusters connected with gateways, or is it that you have 1 NATS cluster of 3 nodes, each node running in a k8s cluster? If the former, you need to make sure that each node has a unique server name! The server detects duplicate server names within a cluster, but does not across gateways (this will be the case in the next release).

**Comment by wchajl** [comment]
@kozlovic 
I have 3 isolated nats clusters (dev , native-test , test) ,and each cluster consists of 3 nodes .
+ The logs I uploaded 15 days ago are from dev cluster.  I've upgraded the nats-server to 2.7.3 after the issue occurs, and it worked for a while . 
+ The log/stacks I uploaded 3 days ago are from test cluster . I've upgraded that cluster since then ,and there is now issue report so far.
+ The logs/stacks I uploaded yesterday are from native-test cluster whose nats version is 2.7.4 .  Nodes in this  cluster are restarting , and all nodes report "corrupt state file". 
+ And now the dev cluster is corrupted again.  Looks like  exactly the problem  happened 15 days ago. It could back to work after I manually delete pods . I've upgraded it to 2.7.4. And here is log/stacksz of each node. 
[dev-0.log](https://github.com/nats-io/nats-server/files/8338407/dev-0.log)
[dev-0-stacksz.log](https://github.com/nats-io/nats-server/files/8338410/dev-0-stacksz.log)
[dev-1.log](https://github.com/nats-io/nats-server/files/8338411/dev-1.log)
[dev-1-stacksz.log](https://github.com/nats-io/nats-server/files/8338412/dev-1-stacksz.log)
[dev-2.log](https://github.com/nats-io/nats-server/files/8338415/dev-2.log)
[dev-2-stacksz.log](https://github.com/nats-io/nats-server/files/8338416/dev-2-stacksz.log)

**Comment by wchajl** [comment]
@kozlovic 
Thanks for your advice. But we intend to reserve the gateways so new clusters could join it without modifying current config. 
Maybe I should add some authorization to protect it ？

**Comment by kozlovic** [comment]
@wchajl You should add some protection for sure (unless this is only for dev/test env). Notice that you already see that there are authentication errors ("Gateway connection closed: Authentication Failure") because the process that tries to connect is not sending the proper CONNECT protocol.
If you keep gateways, please make sure that your server names will be unique across the super-cluster.
