### ISSUE TITLE
JetStream memory stream potentially duplicates/redelivers messages during restart

### ISSUE THREAD

**Issue by aksdb** [nats-io/nats-server#3006]
#### Versions of `nats-server` and affected client libraries used:

nats-server 2.8.0 beta 10 (92813d73707a0eaf3d3783939fa56a09ea789d3a)

#### OS/Container environment:

Linux 5.17.1

#### Steps or code to reproduce the issue:

[clustersetup.zip](https://github.com/nats-io/nats-server/files/8419504/clustersetup.zip)
[testsetup.zip](https://github.com/nats-io/nats-server/files/8419507/testsetup.zip)

* Create a jetstream cluster with three nodes
* Run the consumer `go run . -consume`
* Run the producer `go run . -publish`
* Restart node by node
* Stop the producer
* Stop the consumer

https://user-images.githubusercontent.com/2435857/161788087-a3ecfe49-6459-40a8-8848-c8694b409bcd.mp4

#### Expected result:

The output of the consumer should be a sequence without any missing numbers or duplicates. 

#### Actual result:

Some numbers show up twice.

**Comment by kozlovic** [comment]
@aksdb Could you verify more closely in your `out` file that messages are missing as opposed to have duplicates? I ran your test and what I found is that there were the same message twice, in 2 occurrences, which make it look like that some are missing based on the editor line number and the message "number" that you set. If you find the duplicate and remove them, then the line numbers then match.
Now the question is going to be: why do we get duplicates? But if you could first confirm that they are not missing, but they are duplicate, that would help. Thanks!

**Comment by kozlovic** [comment]
To be clear, in one run I made, here is what I saw:
<img width="187" alt="Screen Shot 2022-04-05 at 1 19 12 PM" src="https://user-images.githubusercontent.com/13736691/161833009-540f7d33-03bb-4873-8375-d461caa1fa3d.png">
and that too:
<img width="156" alt="Screen Shot 2022-04-05 at 1 19 27 PM" src="https://user-images.githubusercontent.com/13736691/161833040-875b100b-d753-49f8-bfbb-ef26a232f143.png">
Which then made it look like there were 2 missing:
<img width="159" alt="Screen Shot 2022-04-05 at 1 19 33 PM" src="https://user-images.githubusercontent.com/13736691/161833089-8b5f8391-0a6b-4ffb-8229-e65cbfa2cb4a.png">
.. but it is actually 2 extra. That matches also your output (the ide line numbers is higher than the message counter)

**Comment by aksdb** [comment]
> @aksdb Could you verify more closely in your `out` file that messages are missing as opposed to have duplicates? I ran your test and what I found is that there were the same message twice, in 2 occurrences, which make it look like that some are missing based on the editor line number and the message "number" that you set. If you find the duplicate and remove them, then the line numbers then match. Now the question is going to be: why do we get duplicates? But if you could first confirm that they are not missing, but they are duplicate, that would help. Thanks!

@kozlovic :man_facepalming: you are right, that was a lapse on my side. It indeed duplicates messages.

I'll adjust the issue text and title.

**Comment by kozlovic** [comment]
@aksdb I tried with file store and not able to get the duplicate. I think that duplicates in consumer are still possible (at-least-once delivery) and likely to happen when there is a leader change if the consumer state is not replicated "synchronously" (performance may suffer too much). But I will check with Derek if my understanding is correct or if we should not expect duplicate deliveries in your scenario. Will keep you posted.

**Comment by derekcollison** [comment]
I will take a closer looks since I am right in the middle of this code atm.
