### ISSUE TITLE
Messages targeted to one durable consumer received by another

### ISSUE THREAD

**Issue by cortopy** [nats-io/nats-server#3098]
I'm experiencing issues with the creation of multiple consumers to the same stream. As per the reproduction steps below, when more than one push subscription is created in one stream, a given subscription will receive **ALL** messages targeted to all consumers of the stream.

This has very nasty consequences:

- Other consumers may never get to see messages in the stream
- A consumer may receive many copies of the same message. Please note this is not a situation of messages being re-delivered because of lack of acknowledgement.

The instructions below reproduce the bug using the nats cli, but in my case I was using the rust client and I could see that the [message.jet_stream_message_info](https://docs.rs/nats/latest/nats/struct.Message.html#method.jetstream_message_info) is indeed showing a different consumer name.

#### Versions of `nats-server` and affected client libraries used:

[24] 2022/05/03 19:18:23.879749 [INF] Starting nats-server
[24] 2022/05/03 19:18:23.880663 [INF]   Version:  2.8.0
[24] 2022/05/03 19:18:23.880671 [INF]   Git:      [90721ee]
[24] 2022/05/03 19:18:23.880676 [DBG]   Go build: go1.17.9
[24] 2022/05/03 19:18:23.880719 [INF]   Name:     NAXBRPUY4AAWC5AAXH63WLIIFDRQR7XTA4LKQTUBJPVDSTPLQ4PVHQLV
[24] 2022/05/03 19:18:23.880738 [INF]   ID:       NAXBRPUY4AAWC5AAXH63WLIIFDRQR7XTA4LKQTUBJPVDSTPLQ4PVHQLV

## 1. Create stream

Create stream with `nats stream add my_stream`

```
? Subjects foo
? Storage memory
? Replication 1
? Retention Policy Limits
? Discard Policy Old
? Stream Messages Limit -1
? Per Subject Messages Limit -1
? Total Stream Size -1
? Message TTL -1
? Max Message Size -1
? Duplicate tracking time window 2m0s
? Allow message Roll-ups No
? Allow message deletion Yes
? Allow purging subjects or the entire stream Yes
Stream my_stream was created

Information for Stream my_stream created 2022-05-03T20:13:00+01:00

Configuration:

             Subjects: foo
     Acknowledgements: true
            Retention: Memory - Limits
             Replicas: 1
       Discard Policy: Old
     Duplicate Window: 2m0s
    Allows Msg Delete: true
         Allows Purge: true
       Allows Rollups: false
     Maximum Messages: unlimited
        Maximum Bytes: unlimited
          Maximum Age: unlimited
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited

```

## 2. Publish one message

Publish the first message with `nats pub foo "publication #{{Count}} @ {{TimeStamp}}"`

## 3. Create two consumers
Then create first consumer with `nats consumer add my_stream consumer_one`

```
? Delivery target (empty for Pull Consumers) my_stream
? Delivery Queue Group 
? Start policy (all, new, last, subject, 1h, msg sequence) all
? Acknowledgement policy explicit
? Replay policy instant
? Filter Stream by subject (blank for all) 
? Maximum Allowed Deliveries -1
? Maximum Acknowledgements Pending 0
? Idle Heartbeat 0s
? Enable Flow Control, ie --flow-control No
? Deliver headers only without bodies No
? Add a Retry Backoff Policy No
Information for Consumer my_stream > consumer_one created 2022-05-03T20:15:44+01:00

Configuration:

        Durable Name: consumer_one
    Delivery Subject: my_stream
      Deliver Policy: All
          Ack Policy: Explicit
            Ack Wait: 30s
       Replay Policy: Instant
     Max Ack Pending: 1,000
        Flow Control: false

State:

   Last Delivered Message: Consumer sequence: 0 Stream sequence: 0
     Acknowledgment floor: Consumer sequence: 0 Stream sequence: 0
         Outstanding Acks: 0 out of maximum 1,000
     Redelivered Messages: 0
     Unprocessed Messages: 1
          Active Interest: No interest
```
Create a second consumer with `nats consumer add my_stream consumer_two`

## 4. Subscribe

Subscribe with command `nats consumer sub my_stream consumer_one`

```
Subscribing to topic my_stream auto acknowlegement: true

Consumer Info:
  Ack Policy: Explicit
    Ack Wait: 30s

[20:23:35] subj: foo / tries: 1 / cons seq: 2 / str seq: 2 / pending: 0
publication #1 @ 2022-05-03T20:23:32+01:00

[20:23:35] subj: foo / tries: 1 / cons seq: 2 / str seq: 2 / pending: 0
publication #1 @ 2022-05-03T20:23:32+01:00
```
There you can see that two messages are delivered even though only one was published!!

Then if you run `nats consumer sub my_stream consumer_two` no message is delivered. The message was already delivered and acked in the firsty subscription, so the second consumer never gets to see it

#### Expected result:

Each durable consumer receives messages targeted for that consumer only

#### Actual result:

There seems to be a race condition that the first consumer to subscribe will get all the messages

**Comment by kozlovic** [comment]
You have selected "my_stream" as the delivery subject, I suppose for both consumers, so you are effectively consuming from both at the same time...

**Comment by kozlovic** [comment]
```

Configuration:

        Durable Name: consumer_one
    Delivery Subject: my_stream
```
See above, I wonder if you made the mistake there to select the stream instead of a delivery subject.

**Comment by cortopy** [comment]
In case I'm doing something wrong, following your comments I've just tried:

- setting `foo` as target but this gives error `nats: error: Consumer creation failed: consumer deliver subject forms a cycle (10081)`
- setting `my_stream.>` as target but this one gives error `nats: error: Consumer creation failed: consumer deliver subject has wildcards (10079)`
- setting `my_stream.foo`. I thought this one was the most promising but the behaviour is exactly the same as in my bug report

In my real use case, consumers need to get all messages in the stream, which is why I selected the stream as subject. I'm using event sourcing in a very similar way described here https://www.byronruth.com/implementing-an-event-store-on-nats-part-1/. Instead of "my_stream.foo" I'll have "ORDERS.1" and so the consumers need all messages in "ORDERS"

**Comment by kozlovic** [comment]
Each consumer needs to have its own deliver subject. For instance, you could pick `deliver.consumer_one` for `consumer_one` and `deliver.consumer_two` for `consumer_two`.

With your first approach (same deliver subject), as soon as you created interest on "my_stream", each consumer detected that there was an interest and started to send their message.

**Comment by cortopy** [comment]
I'm a bit confused about what the consumer subject is then. I couldn't find much info in the [docs](https://docs.nats.io/nats-concepts/jetstream/consumers#deliverysubject) and I assumed is the subject of the stream which the consumer is interested in.

So does that mean a publisher has to publish each message twice to  "deliver.consumer_one" and "deliver.consumer_two"?

**Comment by kozlovic** [comment]
No, the stream collects message on "foo" (as per your configuration). The consumers are attached to that stream and will receive all messages from the stream (since no filter subject is used). Since you create "push consumers", the server has to deliver the original messages to a delivery subject that is different that the original subject, otherwise that would create an infinite loop. 
When you publish 1 message to "foo", the server knows that there are 2 consumers interested in it and will "add" this message to each consumer.
When you subscribe to the deliver subject of consumer 1, you will receive messages from consumer 1, and ditto for consumer 2. 
As you can see with the `nats consumer sub` command, you did not have to provide the actual deliver subject, you just provided the stream and consumer name. Under the cover, the library knows which deliver subject is for this consumer and will create a low-level NATS subscription on the consumer's deliver subject, which then will trigger subscription interest which will make the associated consumer start delivering messages to that.

**Comment by cortopy** [comment]
I can see now I was all wrong. Using different consumer targets/subjects works now on my example. But in my application I'm still seeing weird things

I have three durable consumers and now they don't see the messages which are targeted for the others. But in addition to the messages in their "target" they are also getting messages for some consumers with names like "Ojkk3klo" that I don't know where they come from.

If I do `nats consumer info` I can see those consumers listed but I don't create them

**Comment by cortopy** [comment]
on further debugging those extra messages from extra subscriptions are created when I pass the option `--heartbeat 5s`

**Comment by kozlovic** [comment]
But if you have an application consuming, don't run the "nats consumer" commands. How do you create your consumers in your apps? Maybe you simply created ephemerals by not specifying the durable name that is the name of the consumer you created with the CLI (consumer_one and consumer_two).
