### ISSUE TITLE
Suggestion to use Semmle LGTM.com for static analysis

### ISSUE THREAD

**Issue by huornlmj** [nats-io/nats-server#3136]
#### Who Benefits From The Change(s)?  Everyone.

Previous scans and current alerts are available already:
https://lgtm.com/projects/g/nats-io/nats-server/history/

As you can see the number of alerts (red line) has been increasing with the new code (blue line) rather than being reduced.  Some of these alerts could lead to vulnerabilities or weaknesses in the NAT program.

![image](https://user-images.githubusercontent.com/28444739/169272486-ee69cff4-1056-4058-a3ee-dcfe47cffb79.png)

**Comment by derekcollison** [comment]
Believe this service shutdown.
