### ISSUE TITLE
Mappings cannot have spaces in mapping functions

### ISSUE THREAD

**Issue by ripienaar** [nats-io/nats-server#3151]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:

a52f12613e6eb53097d6d563d9b9681b88a037cb

#### OS/Container environment:

Linux EL8

#### Steps or code to reproduce the issue:

Use configuration:

```
mappings = {
  "in.registration.*.>": "registration.{{ partition(5, 1) }}.{{wildcard(1)}}.>"
}
```

```
$ nats-server --config /tmp/server.conf
nats-server: /tmp/server.conf:2:4: Error adding mapping for "in.registration.*.>" to "registration.{{partition(5, 1)}}.{{wildcard(1)}}.>" : invalid subject
```

But if we adjust the subject mapping like this (remove all spaces):

```
mappings = {
  "in.registration.*.>": "registration.{{partition(5,1)}}.{{wildcard(1)}}.>"
}
```

It works.

This is because https://github.com/nats-io/nats-server/blob/a52f12613e6eb53097d6d563d9b9681b88a037cb/server/accounts.go#L618-L621  is checking the transform subject for validity before any parsing is done, I think probably we should remove that check.  Spaces in these mappings greatly improves readability and we specifically supported them in the code when implementing it.

**Comment by derekcollison** [comment]
Feel free to post PR, or @jnmoyne can. Not sure if I put that in there or not but agree the spaces can help when doing more exotic things.

**Comment by derekcollison** [comment]
@jnmoyne can we get a fix for this?

**Comment by jnmoyne** [comment]
Yes, planning on dedicating some time for it this week.
