### ISSUE TITLE
'num_deleted' and 'deleted' values in stream state do not get updated when message with lowest sequence number is removed 

### ISSUE THREAD

**Issue by piotrpio** [nats-io/nats-server#3179]
## Defect
Stream info returns invalid values for `deleted` and `num_deleted` fields if a message with lowest sequence number is removed (it is not included). Attaching output from `nats-server -DV -js` and test code (in go client) to reproduce this issue.
[server-output.txt](https://github.com/nats-io/nats-server/files/8871940/server-output.txt)
[test.txt](https://github.com/nats-io/nats-server/files/8871941/test.txt)

 - [x] Included `nats-server -DV` output
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:
nats-server: v2.8.4

#### Steps or code to reproduce the issue:
1. Create a new stream with file storage
2. Publish some messages on the stream
3. Delete e.g. message with `seq == 3` (does not matter, as long as it's not first)
4. Delete message with `seq == 1`

5. Fetch stream info

#### Expected result:
In the above case, `num_deleted` should be equal to `2`, and `deleted` should have [3, 1].

#### Actual result:
`num_deleted == 1` and `deleted == [3]`

**Comment by ripienaar** [comment]
Derek calls them "interior deletes" else on a 10 billion message stream thats empty we end up listing 10 billion deleted message ids :) as it is I dont see the use for this informatin, but its about the gap.
