### ISSUE TITLE
cross account services that are stream don't forward all responses if an empty payload

### ISSUE THREAD

**Issue by aricart** [nats-io/nats-server#3180]
## Defect

On services that have a `stream` response, any empty payload, will prevent additional messages from getting to the client (only the first will be delivered).

```
jetstream {
  max_file_store: 1048576
  max_memory_store: 1048576
  store_dir: /tmp/jetstream/7BE5KDG11Z23EVN0AK47AG
 }
debug: true
trace: true
accounts {
  JS {
    users [
       {
        user: service
        password: service
       }
     ]
    exports [
       {
        service: next
        response: stream
       }
     ]
   }
  A {
    users [
       {
        user: a
        password: a
       }
     ]
    imports [
       {
        service {
          subject: next
          account: JS
         }
       }
     ]
   }
 }
ports_file_dir: /var/folders/1y/_rk6yz81341g5q8k1vr5nqmw0000gq/T
host: "127.0.0.1"
port: 4222
http: "127.0.0.1:4222"
```

The above configuration exports a service (public or private doesn't matter) - the service can return N number of responses.
Account A imports the service, so it publishes a request to `next`, to which the service responds 10 times, with a payload, all 10 messages will make it through. If instead, the responses had an empty payload, only the first is delivered.

While this is a weird example, the point is that the logic doesn't check for any other differences either. In the case of JetStream, if the request was to a stream that had 10 messages that have no payload, the server will only return the first message, all other messages would be dropped (they also have different reply subjects, so this is not enough to discern that they are indeed valid messages without payloads.

```typescript
Deno.test("me - test", async () => {
  const template = {
    debug: true,
    trace: true,
    accounts: {
      JS: {
        users: [{ user: "service", password: "service" }],
        exports: [
          {
            service: "next",
            response: "stream",
            // accounts: ["A"],
          }
        ],
      },
      A: {
        users: [{ user: "a", password: "a" }],
        imports: [
          {
            service: {
              subject: "next",
              account: "JS"
            },
          },
        ],
      },
    },
  };

  const { ns, nc } = await setup(jetstreamServerConf(template, true), {
    user: "service",
    pass: "service",
  });

  const sc = StringCodec();

  nc.subscribe("next", {
    callback: (err, msg) => {
      for (let i = 0; i < 10; i++) {
        msg.respond(sc.encode(`${i}`));
      }
    },
  });

  const client = await connect({ port: ns.port, user: "a", pass: "a" });
  const inbox = createInbox();
  const csub = client.subscribe(inbox, {
    callback: (err, msg) => {
      console.log(msg.subject);
    },
  });

  client.publish("next", Empty, {reply: inbox});

  await delay(10000);
  await cleanup(ns, nc, client);
});
```

**Comment by derekcollison** [comment]
An empty payload is how the responder signals EOF.

**Comment by aricart** [comment]
if set to chunked or are stream and chunked equivalent? This has significant meaning then because there's no requirements for a stream to contain messages with data...

**Comment by derekcollison** [comment]
Yes that is correct and has always been that way, empty payload signals EOF which signals the server to drop the reply mapping.

**Comment by derekcollison** [comment]
We can discuss the behavior separately, but system works as designed.
