### ISSUE TITLE
restore stream error

### ISSUE THREAD

**Issue by daudcanugerah** [nats-io/nats-server#3199]
nats-server version 2.8.2
natscli version 0.32

nats: error: restore failed: restore failed: error restoring consumer ["history"]: stat /data/jetstream/$G/streams/darksky_forecast_history/obs/history/meta.inf: no such file or directory (10062)

if the stream does not have a consumer restore is sucess
![Screen Shot 2022-05-11 at 00 18 19](https://user-images.githubusercontent.com/34634382/167685808-94c80d47-3bc1-47be-a2e0-843e53d61f24.png)

**Comment by ripienaar** [comment]
Transferred from the CLI since the fix is for the server to not allow these characters in stream or consumer names
