### ISSUE TITLE
Subscribe to $SYS.REQ.ACCOUNT.*.CLAIMS.LOOKUP and respond with the account JWT

### ISSUE THREAD

**Issue by sonlv123** [nats-io/nats-server#3206]
Hi! Thanks for this great project. I'm investigating the possibility of writing my own server account and integrating it with NATS. I found the following passage on https://docs.nats.io/running-a-nats-service/configuration/securing_nats/auth_intro/jwt/resolver
"To serve a requested account JWT yourself and essentially implement an account server, subscribe to $SYS.REQ.ACCOUNT.*.CLAIMS.LOOKUP and respond with the account JWT corresponding to the requested account id (wildcard)."

However, when I connect my server to NATS and subscribe to the subject above, I don't receive any requests. Am I missing some configuration? 

Lastly, When I connect to nats-server, Am I always configure system-account for URL-resolver or nats-resolver?

Thanks a lot!

**Comment by derekcollison** [comment]
Can you share your server config?

**Comment by sonlv123** [comment]
HI @derekcollison . My server config below:

port : 4222

# HTTP monitoring port
monitor_port: 8222

# log
debug: true
trace: true

# cluster
cluster {
  #port = 6223
  #routes [ nats://127.0.0.1:6222 ]
}

#jetstream: enabled

# Operator named SPECO
operator: eyJ0eXAiOiJKV1QiLCAiYWxnIjoiZWQyNTUxOS1ua2V5In0.eyJqdGkiOiJISFVLS05GSkhIWkczQVg3T01DUjdQMlZLTVhLTjVGRE5DQVlaQ1hUSVBZMzJMRlVGSVBBIiwiaWF0IjoxNjU1NTQ1NTgwLCJpc3MiOiJPQTJCWlc1SjVBVUhSNVlLRlNaQ0ZTTFlDU09ORjVIUEhMNVY0S0ZWNTVaWFE1N0NTWU0zUUJSNiIsIm5hbWUiOiJwZWNPUE5ldyIsInN1YiI6Ik9BMkJaVzVKNUFVSFI1WUtGU1pDRlNMWUNTT05GNUhQSEw1VjRLRlY1NVpYUTU3Q1NZTTNRQlI2IiwibmF0cyI6eyJ0eXBlIjoib3BlcmF0b3IiLCJ2ZXJzaW9uIjoyLCJhY2NvdW50X3NlcnZlcl91cmwiOiJuYXRzOi8vbG9jYWxob3N0OjQyMjIiLCJvcGVyYXRvcl9zZXJ2aWNlX3VybHMiOlsibmF0czovL2xvY2FsaG9zdDo0MjIyIl19fQ.lA9MtNwtvydtYv0bbYyuvHeGTCDOFkFDrTwCFPGW0NI5Z-tTVHUB3aomiHxf66tZuZlXw0HYO4CIQs8qBPMvDg
# System Account named SYS
system_account: AA6TQJCOBCBTHQFD6FHSPGAQXUMTLIGSO3TDAKBGZGUBV2RVNGZ2Q2M3

# configuration of the nats based resolver
resolver {
    type: full
    # Directory in which the account jwt will be stored
    dir: './jwt'
    # In order to support jwt deletion, set to true
    # If the resolver type is full delete will rename the jwt.
    # This is to allow manual restoration in case of inadvertent deletion.
    # To restore a jwt, remove the added suffix .delete and restart or send a reload signal.
    # To free up storage you must manually delete files with the suffix .delete.
    allow_delete: false
    # Interval at which a nats-server with a nats based account resolver will compare
    # it's state with one random nats based account resolver in the cluster and if needed,
    # exchange jwt and converge on the same set of jwt.
    interval: "2m"
    # Timeout for lookup requests in case an account does not exist locally.
    timeout: "1.9s"
}


# Preload the nats based resolver with the system account jwt.
# This is not necessary but avoids a bootstrapping system account.
# This only applies to the system account. Therefore other account jwt are not included here.
# To populate the resolver:
# 1) make sure that your operator has the account server URL pointing at your nats servers.
#    The url must start with: "nats://"
#    nsc edit operator --account-jwt-server-url nats://localhost:4222
# 2) push your accounts using: nsc push --all
#    The argument to push -u is optional if your account server url is set as described.
# 3) to prune accounts use: nsc push --prune
#    In order to enable prune you must set above allow_delete to true
# Later changes to the system account take precedence over the system account jwt listed here.
resolver_preload: {
        AA6TQJCOBCBTHQFD6FHSPGAQXUMTLIGSO3TDAKBGZGUBV2RVNGZ2Q2M3: eyJ0eXAiOiJKV1QiLCAiYWxnIjoiZWQyNTUxOS1ua2V5In0.eyJqdGkiOiJIWkNYSk5KR0xWT0VGN05WQ0dEWjNQTEpTVlFVV0I2RkFNQVFVQU1TRVQzMkRVSkpPTkpBIiwiaWF0IjoxNjU1NTQ1Njg0LCJpc3MiOiJPQTJCWlc1SjVBVUhSNVlLRlNaQ0ZTTFlDU09ORjVIUEhMNVY0S0ZWNTVaWFE1N0NTWU0zUUJSNiIsIm5hbWUiOiJTWVMiLCJzdWIiOiJBQTZUUUpDT0JDQlRIUUZENkZIU1BHQVFYVU1UTElHU08zVERBS0JHWkdVQlYyUlZOR1oyUTJNMyIsIm5hdHMiOnsidHlwZSI6ImFjY291bnQiLCJ2ZXJzaW9uIjoyLCJsaW1pdHMiOnsic3VicyI6LTEsImRhdGEiOi0xLCJwYXlMb2FkIjotMSwiaW1wb3J0cyI6LTEsImV4cG9ydHMiOi0xLCJ3aWxkY2FyZHMiOmZhbHNlLCJjb25uIjotMSwibGVhZiI6LTF9LCJkZWZhdWx0X3Blcm1pc3Npb25zIjp7InB1YiI6eyJhbGxvdyI6WyI-Il0sImRlbnkiOltdfSwic3ViIjp7ImFsbG93IjpbIj4iXSwiZGVueSI6W119fSwiaW1wb3J0cyI6W10sImV4cG9ydHMiOltdfX0.uNY7gkm18wugiW4TPgDK34E0icF1rQwZ-t_q9S0NN0WCCC3pB_adQ83dIaXyKA5YklxZGegWhM8tSKfsdCbXDg,
}

**Comment by sonlv123** [comment]
thank @derekcollison , Hi @matthiashanel 
Could the nats-server authenticate and authorize by the account base on subscribing to $SYS.REQ.ACCOUNT.*.CLAIMS.LOOKUP?
If I understand correctly, Please help me give a solution.

**Comment by matthiashanel** [comment]
@sonlv123 are you using the system account to subscribe to this subject?

**Comment by sonlv123** [comment]
@matthiashanel yes, I'm using the system account. Besides I want to use other accounts to authenticate and authorize on the nats-server.

**Comment by matthiashanel** [comment]
Your configuration looks a bit off, you are basically missing the operator and the system account.
When you are using nsc to generate your operator, you can also ask it to generate a resolver config with `nsc generate config`

```
nsc generate config --nats-resolver
nsc generate config --nats-resolver-cache
```

From this I figure, you did not end up using the actual system account when subscribing to $SYS.REQ.ACCOUNT.*.CLAIMS.LOOKUP.
The nats resolver send lookup requests for any account on this account only.

Next question I have is why do you want to write your own account resolver?
The nats resolver in full mode allows you to dynamically generate account jwt as well and upload them with using this subject `$SYS.REQ.CLAIMS.UPDATE` (again using the system account) (This is basically what nsc push does)
As a benefit, the nats resolver also takes on storage for your account jwt.
You can also set expiration in the account jwt and periodically updated it, keeping the account from actually expiring.

Assuming this does not suffice for your use case and you want to generate the account jwt on every lookup.
Then I'd look at the cache resolver. basically the resolver in full mode does not call out if the account jwt is present locally.
With the nats resolver in cache mode you can specify how long the result of a lookup is valid. 
Use `nsc generate config --nats-resolver-cache` to generate

**Comment by sonlv123** [comment]
@matthiashanel thank you for support.

**Comment by matthiashanel** [comment]
> @matthiashanel thank you for your support.

ok to close the issue?
