### ISSUE TITLE
WriteDeadline default value

### ISSUE THREAD

**Issue by 1995parham** [nats-io/nats-server#3219]
I think based on what we have [here](https://docs.nats.io/running-a-nats-service/configuration#connection-timeouts), the write deadline default value is about `2s` but in the code we have `10s` I think. Which one is more suitable for a production environment?

https://github.com/nats-io/nats-server/blob/67a182f98e29e6965589576720196e6139f895ea/server/const.go#L101

**Comment by wallyqs** [comment]
Setting to 10s like the default is what we would recommend for nats-server v2 series.

**Comment by 1995parham** [comment]
So we need to just update the documentation from `2s` to `10s`?

**Comment by wallyqs** [comment]
Yes we should update in the docs…

**Comment by 1995parham** [comment]
Sure, I will create PR there. Thanks
