### ISSUE TITLE
go 1.18 modules are confused about imports of github.com/nats-io/nats.go

### ISSUE THREAD

**Issue by karlmutch** [nats-io/nats-server#3235]
When using the nats server as an embedded server during testing the github.com/nats-io/nats-server/server.test module pulls in github.com/nats-io/go-nats instead of github.com/nats-io/nats.go.

Can this be fixed without using GOPROXY=direct ?  I really would like to use the standard Go Proxy to help with ensuring packages are not tampered with.

```
$ go get -u github.com/nats-io/nats-server@latest
go: downloading golang.org/x/sys v0.0.0-20220701225701-179beb0bd1a1
go: added github.com/nats-io/gnatsd v1.4.1
go: upgraded golang.org/x/sys v0.0.0-20220227234510-4e6760a101f9 => v0.0.0-20220701225701-179beb0bd1a1
$ go mod tidy
go: finding module for package github.com/nats-io/go-nats
go: found github.com/nats-io/go-nats in github.com/nats-io/go-nats v1.8.1
go: github.com/fetchrobotics/fetchcore/fleet_api_server/workflow/event/triggertransport/natstransport/embedded_stan_server imports
        github.com/nats-io/nats-server/server tested by
        github.com/nats-io/nats-server/server.test imports
        github.com/nats-io/go-nats: github.com/nats-io/go-nats@v1.8.1: parsing go.mod:
        module declares its path as: github.com/nats-io/nats.go
                but was required as: github.com/nats-io/go-nats
```

Thanks

**Comment by derekcollison** [comment]
```$ go get -u github.com/nats-io/nats-server/v2@latest```

**Comment by kozlovic** [comment]
@karlmutch Yes, to be clear, you were getting the "v1" version of the server, hence the dependency on "go-nats" when that repo used to be called that way. Since the NATS Server v2 version, in go.mod world, you need to add the `/v2` in the URL as Derek mentioned.
