### ISSUE TITLE
NATS Server Jetstream report has duplicates and wrong output

### ISSUE THREAD

**Issue by sourabhaggrawal** [nats-io/nats-server#3254]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ ] Included `nats-server -DV` output
 - [ ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:
2.8.4

#### OS/Container environment:
Ubuntu 20.04.4 LTS
#### Steps or code to reproduce the issue:
Launched 7 nodes cluster, created 100 streams and 300 consumer per stream.
Ran /nats server report jetstream --creds sys.creds --user user.creds on client.

#### Expected result:
Report should show only 100 streams in total and 30000 consumers in total
#### Actual result:
Report showed 263 streams and 42000+ consumers
Report also has duplicaete.
![Screenshot 2022-07-11 at 1 37 09 PM](https://user-images.githubusercontent.com/70515711/178217804-23576316-961e-4260-abc0-f7bb307d4f69.png)

**Comment by ripienaar** [comment]
Do you mind running this command with `--trace` and pasting the output here? Not a screenshot.

**Comment by sourabhaggrawal** [comment]
@ripienaar 
root@ip-10-195-80-145:/mnt/nats/nats-0.0.33-linux-amd64# ./nats server report jetstream --creds sys.creds --user user.creds --trace
08:32:54 >>> $SYS.REQ.SERVER.PING.JSZ: {}
08:32:54 <<< (646B -> 1006B) {"server":{"name":"perf-node5","host":"0.0.0.0","id":"NDKMR7O3QYBVAHNKOC6GEQFVJDIW2POZ36VEB7HN4STYTYSG42NZOEKZ","cluster":"perf-cluster","ver":"2.8.4","seq":234740,"jetstream":true,"time":"2022-07-11T08:32:54.437597496Z"},"data":{"server_id":"NDKMR7O3QYBVAHNKOC6GEQFVJDIW2POZ36VEB7HN4STYTYSG42NZOEKZ","now":"2022-07-11T08:32:54.437514308Z","config":{"max_memory":30000000000,"max_storage":50000000000,"store_dir":"/var/lib/nats/store/jetstream"},"memory":0,"storage":3207318,"reserved_memory":0,"reserved_storage":0,"accounts":1,"ha_assets":19322,"api":{"total":13073,"errors":0},"streams":58,"consumers":19263,"messages":18584,"bytes":3207318,"meta_cluster":{"name":"perf-cluster","leader":"perf-node5","replicas":[{"name":"perf-node3","current":true,"active":7416612},{"name":"perf-node1","current":true,"active":8177559},{"name":"perf-node2","current":true,"active":7666491},{"name":"perf-node7","current":true,"active":8198605},{"name":"perf-node6","current":true,"active":8121976}],"cluster_size":6}}}
08:32:54 <<< Header: map[Content-Encoding:[snappy]]
08:32:54 <<< (533B -> 723B) {"server":{"name":"perf-node7","host":"0.0.0.0","id":"NCRRUP6PIWHNG2U3KBDX4TUIOHLUAONIIBBCGTM7IBSOW5PMFEOD4THS","cluster":"perf-cluster","ver":"2.8.4","seq":212484,"jetstream":true,"time":"2022-07-11T08:32:54.435404774Z"},"data":{"server_id":"NCRRUP6PIWHNG2U3KBDX4TUIOHLUAONIIBBCGTM7IBSOW5PMFEOD4THS","now":"2022-07-11T08:32:54.435364118Z","config":{"max_memory":25000000000,"max_storage":50000000000,"store_dir":"/var/lib/nats/store/jetstream"},"memory":0,"storage":2633053,"reserved_memory":0,"reserved_storage":0,"accounts":1,"ha_assets":15586,"api":{"total":10236,"errors":0},"streams":42,"consumers":15543,"messages":15252,"bytes":2633053,"meta_cluster":{"name":"perf-cluster","leader":"perf-node5","cluster_size":6}}}
08:32:54 <<< Header: map[Content-Encoding:[snappy]]
08:32:54 <<< (537B -> 721B) {"server":{"name":"perf-node3","host":"0.0.0.0","id":"NDEZTQ2F4HTDQQBEKI3TFJQJEDSTP375A5ZGTCBGUWFP4ECTIBUXKEOU","cluster":"perf-cluster","ver":"2.8.4","seq":237857,"jetstream":true,"time":"2022-07-11T08:32:54.42787989Z"},"data":{"server_id":"NDEZTQ2F4HTDQQBEKI3TFJQJEDSTP375A5ZGTCBGUWFP4ECTIBUXKEOU","now":"2022-07-11T08:32:54.427830189Z","config":{"max_memory":25000000000,"max_storage":50000000000,"store_dir":"/var/lib/nats/store/jetstream"},"memory":0,"storage":3300621,"reserved_memory":0,"reserved_storage":0,"accounts":1,"ha_assets":20124,"api":{"total":8414,"errors":0},"streams":63,"consumers":20060,"messages":19123,"bytes":3300621,"meta_cluster":{"name":"perf-cluster","leader":"perf-node5","cluster_size":6}}}
08:32:54 <<< Header: map[Content-Encoding:[snappy]]
08:32:54 <<< (533B -> 723B) {"server":{"name":"perf-node1","host":"0.0.0.0","id":"NDK57RH5FYT2V3FK6G7ADA5BREA2CKYJJDU6DZOC46H5KEYP3U5DOZHY","cluster":"perf-cluster","ver":"2.8.4","seq":242541,"jetstream":true,"time":"2022-07-11T08:32:54.435371649Z"},"data":{"server_id":"NDK57RH5FYT2V3FK6G7ADA5BREA2CKYJJDU6DZOC46H5KEYP3U5DOZHY","now":"2022-07-11T08:32:54.435315183Z","config":{"max_memory":25000000000,"max_storage":50000000000,"store_dir":"/var/lib/nats/store/jetstream"},"memory":0,"storage":3487282,"reserved_memory":0,"reserved_storage":0,"accounts":1,"ha_assets":20829,"api":{"total":13577,"errors":0},"streams":60,"consumers":20768,"messages":20202,"bytes":3487282,"meta_cluster":{"name":"perf-cluster","leader":"perf-node5","cluster_size":6}}}
08:32:54 <<< Header: map[Content-Encoding:[snappy]]
08:32:54 <<< (532B -> 722B) {"server":{"name":"perf-node6","host":"0.0.0.0","id":"NBFR4R7LOJ5L6DNFLLD5FNP3H5AIXOGTNVKBGHXQ355KMPI7IUKGKOVB","cluster":"perf-cluster","ver":"2.8.4","seq":201139,"jetstream":true,"time":"2022-07-11T08:32:54.436794036Z"},"data":{"server_id":"NBFR4R7LOJ5L6DNFLLD5FNP3H5AIXOGTNVKBGHXQ355KMPI7IUKGKOVB","now":"2022-07-11T08:32:54.436754789Z","config":{"max_memory":25000000000,"max_storage":50000000000,"store_dir":"/var/lib/nats/store/jetstream"},"memory":0,"storage":2353089,"reserved_memory":0,"reserved_storage":0,"accounts":1,"ha_assets":14079,"api":{"total":9532,"errors":0},"streams":40,"consumers":14038,"messages":13634,"bytes":2353089,"meta_cluster":{"name":"perf-cluster","leader":"perf-node5","cluster_size":6}}}
08:32:54 <<< Header: map[Content-Encoding:[snappy]]
08:32:54 <<< (521B -> 707B) {"server":{"name":"perf-node2","host":"0.0.0.0","id":"NDGU2DC6LQLYLBRVVDGEH2RCVSKV6F2GAO6QGLOMXCBUQC5PGCXY5MWN","cluster":"perf-cluster","ver":"2.8.4","seq":206234,"jetstream":true,"time":"2022-07-11T08:32:54.436942215Z"},"data":{"server_id":"NDGU2DC6LQLYLBRVVDGEH2RCVSKV6F2GAO6QGLOMXCBUQC5PGCXY5MWN","now":"2022-07-11T08:32:54.436906405Z","config":{"max_memory":25000000000,"max_storage":50000000000,"store_dir":"/var/lib/nats/store/jetstream"},"memory":0,"storage":2539750,"reserved_memory":0,"reserved_storage":0,"accounts":1,"ha_assets":14784,"api":{"total":9804,"errors":0},"streams":0,"consumers":0,"messages":0,"bytes":0,"meta_cluster":{"name":"perf-cluster","leader":"perf-node5","cluster_size":6}}}
08:32:54 <<< Header: map[Content-Encoding:[snappy]]
08:32:54 <<< (538B -> 722B) {"server":{"name":"perf-node3","host":"0.0.0.0","id":"NDVMMCCJRH44QJ6JDD7LDDP5LYMM2HRDSUCVO3GJWEAVCNQAYKNGEPQ7","cluster":"perf-cluster","ver":"2.8.4","seq":237334,"jetstream":true,"time":"2022-07-11T08:32:54.439258748Z"},"data":{"server_id":"NDVMMCCJRH44QJ6JDD7LDDP5LYMM2HRDSUCVO3GJWEAVCNQAYKNGEPQ7","now":"2022-07-11T08:32:54.439197922Z","config":{"max_memory":25000000000,"max_storage":50000000000,"store_dir":"/var/lib/nats/store/jetstream"},"memory":0,"storage":3300621,"reserved_memory":0,"reserved_storage":0,"accounts":1,"ha_assets":20124,"api":{"total":8400,"errors":0},"streams":63,"consumers":20060,"messages":19123,"bytes":3300621,"meta_cluster":{"name":"perf-cluster","leader":"perf-node5","cluster_size":6}}}
08:32:54 <<< Header: map[Content-Encoding:[snappy]]
08:32:54 >>> Received 7 responses

**Comment by ripienaar** [comment]
It definitely seems to me you have 2 ndes called node3, there are unique responses AND they have unique contents - specifically the ID is unique.

**Comment by sourabhaggrawal** [comment]
Hi @ripienaar I have cross-checked the nodes configuration and each node has unique name.

**Comment by sourabhaggrawal** [comment]
Hi @ripienaar , my bad. One of the node had the same name. 
We were providing the node name in supervisor config for nats  and changed it later,  but missed to reload.
Apologies for the confusion and thank you for helping out. 
Closing this issue.
