### ISSUE TITLE
JetStream - Updating consumer from R3 to R1 doesn't work

### ISSUE THREAD

**Issue by goku321** [nats-io/nats-server#3262]
`nats-server`: v2.8.4
`nats.go`: v1.16.0
`NATS cli`: v0.0.33

#### Step to reproduce:
1. Setup a 3-nodes JetStream cluster.
2. Create a stream with a replica count 3.
3. Create a consumer using `nats.go` client with a replica count 3.
4. Publish and consume some messages.
5. Update the consumer's replica count to 1 using `nats.go` client

#### Expected results
1. Replica count for the consumer should get updated to 1.
2. Consumer should have no replicas or metadata on replica nodes.
3. `nats con info` should not show any replicas field for a R1 consumer

![Screenshot 2022-07-14 at 12 55 36 PM](https://user-images.githubusercontent.com/12848015/178940066-89de7557-ad54-4013-8cce-da23c861e5e3.png)

4. When the leader node is killed while consuming, the client should get a "Consumer Migration" message (since, it is R1 now).

#### Actual results
1. `nats con info` does show replica count as 1 (which is correct)
2. Consumer still have its metadata on other nodes and it's being updated regularly (confirmed with `ls -l`)
3. `nats con info` shows replicas field

![Screenshot 2022-07-14 at 12 54 44 PM](https://user-images.githubusercontent.com/12848015/178939478-409585eb-6c08-41e7-bb17-807607756958.png)

4. When the leader node is killed, the client gets a "Leadership Change" message (that means, it is still > R1)

**Comment by matthiashanel** [comment]
@goku321 I can confirm that this is not implemented

**Comment by goku321** [comment]
Thanks @matthiashanel for confirming. As a workaround, we are creating a new R1 consumer with start sequence and copying its config from the existing R3. Here's the [example code](https://gist.github.com/goku321/5849c8298d5e8577ce7d5572bffbf251). To make sure that this R1 resumes from where the old R3 left, we are setting the start sequence of R1 to `consumerInfo.Delivered.Stream+1` (of R3). I tested this for a few cases and it seems to be working fine. Would there be any case that this might fail?
