### ISSUE TITLE
Migration of a standalone instance to a cluster

### ISSUE THREAD

**Issue by perestoronin** [nats-io/nats-server#3267]
Our production environment currently uses a standalone hub nats jetstream instance that we need to migrate to a cluster nats jetstream, is there any documentation or can anyone provide any feedback or experience with this process? We would like to migrate existing streams / consumers / messages if at all possible.

I have tried migrating the file store over from the standalone instance but:
```
nats s report
Obtaining Stream stats

No Streams defined
```

I am also currently looking at a replicator service as an alternative tools to replicate streams / consumers/ messages from the standalone node jetstream to a fresh jetstream cluster.

Any feedback would be greatly appreciated.

**Comment by derekcollison** [comment]
Use the nats cli to backup the accounts, and all assets. Convert to a clustered setup and then restore all the assets into the cluster.
