### ISSUE TITLE
Add detail to JSStreamNameExistErr

### ISSUE THREAD

**Issue by AndrewDK** [nats-io/nats-server#3273]
The text received by the client on this error
```
JSStreamNameExistErr = 10058,                       ///< Stream name already in use
```
is
```
stream name already in use
```
This issue is to request an update to the error text to something that conveys
```
stream name already exists with different settings
```
...to highlight that calling `AddStream` on a stream name already in use *can* succeed, but doesn't when the existing stream has different settings than are specified in the current call. 

This distinction may be obvious to the caller once it is known, however it was difficult to find supporting documentation, and this simple wording change would have made the problem clear.

**Comment by kozlovic** [comment]
@derekcollison @ripienaar I could easily update the description of `JSStreamNameExistErr` in errors.json and `go generate` to update things. Any objection?

**Comment by kozlovic** [comment]
Hum... good point. I think it is also being used when user tries to restore a stream and this stream already exist, which is not really the same.

**Comment by AndrewDK** [comment]
> Hum... good point. I think it is also being used when user tries to restore a stream and this stream already exist, which is not really the same.

They seem the same, as far as the error is concerned.. whether I'm creating or restoring a stream, if the failure is based on an existing stream with the same name but a different config?

**Comment by kozlovic** [comment]
@AndrewDK In case of restore, the server does not check if config is same or not. It will simply fail to restore if a stream of that name already exists.

**Comment by AndrewDK** [comment]
AFAICT from the code, this specific error is only returned after a config check.
https://github.com/nats-io/nats-server/blob/2c7d04f075b9ad58cc6746758bc899fddb178e91/server/stream.go#L360

Not my codebase, so entirely possible github search has hidden another from me :)

**Comment by AndrewDK** [comment]
Ah, there it is https://github.com/nats-io/nats-server/blob/2c7d04f075b9ad58cc6746758bc899fddb178e91/server/stream.go#L4491

**Comment by kozlovic** [comment]
Right, and also in cluster mode, but yeah, you have to look at NewJSStreamNameExistError() instead of the raw error code.

**Comment by AndrewDK** [comment]
If a new error with the added details is in order, it would be helpful. Thanks for looking into it. Also, looks like there's a helpful [docs PR](https://docs.nats.io/using-nats/developer/develop_jetstream/streams) on the way.

**Comment by ripienaar** [comment]
I would be careful of making a new error for the common case as this is one that users might for sure be checking (I know I do). New error for restore case would be fine though then a wording change on the common one. 

Assuming we can not find wording to handle both
