### ISSUE TITLE
jetstream add  maxfile size configuration

### ISSUE THREAD

**Issue by Doslin** [nats-io/nats-server#3276]
## Feature Request
The JetStream file is too small, resulting in too many files in the stream/msgs directory, which affects performance
I see this file is only 7.1m Max
![image](https://user-images.githubusercontent.com/29807388/179904945-37589f22-8efb-47a6-b141-59db068162de.png)

**Comment by derekcollison** [comment]
This is a fair observation, but what we are optimizing for is when those blocks are loaded into memory. We want to minimize that in very diverse user/account usage scenarios.

Most filesystems these days do not have issue with many files, but we are continually looking to improve the system, but for now memory management, and "run on the bank" scenarios are why we decided on max of 8MB, and for KV might be 2MB IIRC>
