### ISSUE TITLE
When a message reaches the maximum number of deliver, how to automatically delete the message?

### ISSUE THREAD

**Issue by hydaizd** [nats-io/nats-server#3294]
When a message is sent for 3 times, it is still stored and will not be deleted. When the maximum number of deliveries is reached, how do I automatically delete the message , even if no ACK or ACK fails.

Because I can't subscribe to these messages, they don't mean anything to me anymore.

Part of the test code is as follows:
```go
func TestAddJs(t *testing.T) {
	nc := GetJsConnect("nats://127.0.0.1:4222")

	defer nc.Close()

	js, _ := nc.JetStream()

	name := "zdd_test"
	_, err := js.AddStream(&nats.StreamConfig{
		Name:      name,
		Subjects:  []string{"zdd.*"},
		Storage:   nats.FileStorage,
		Retention: nats.WorkQueuePolicy,
	})
	if err != nil {
		fmt.Println(err.Error())
	} else {
		fmt.Println("create ok")
	}
}


func TestConsumersMaxDeliver(t *testing.T) {
	nc := GetJsConnect("nats://127.0.0.1:4222")
	defer nc.Close()

	js, _ := nc.JetStream()

	info, err := js.AddConsumer("zdd_test", &nats.ConsumerConfig{
		Durable:       "zdd_deliver",
		AckPolicy:     nats.AckExplicitPolicy,
		DeliverPolicy: nats.DeliverAllPolicy,
		FilterSubject: "zdd.world",
		MaxDeliver:    3,
		AckWait:       4 * time.Second, 
	})
	if err != nil {
		t.Error(err)
		return
	}
	t.Logf("%+v", info)

	sub, err := js.PullSubscribe("zdd.world", "zdd_deliver")
	if err != nil {
		t.Error(err)
		return
	}

	go func() {
		for {
			msgs, _ := sub.Fetch(10, nats.MaxWait(2*time.Microsecond))
			for _, msg := range msgs {
				t.Logf("[%s] msg: %v", time.Now().Format("2006-01-02 15:04:05"), string(msg.Data))

				//msg.Ack()
			}
		}
	}()

	select {}
}
```

**Comment by derekcollison** [comment]
Two options, do a retention based policy for the stream, IIRC than it will go away. Or, listen for advisories when a message reaches it maximum delivery threshold. The advisory will contain the sequence number and can be deleted directly via that.

Please note we have continued to gather information from users and customers regarding this and in general DLQ semantics and how they might work within JetStream. We will make those changes once we feel we have a good plan.

**Comment by hydaizd** [comment]
Listen for advisories when a message reaches it maximum delivery threshold, the problem has been solved. Thanks.
