### ISSUE TITLE
mqtt nil pointer (without reproducer)

### ISSUE THREAD

**Issue by gebv** [nats-io/nats-server#3313]
Hi
At some time we get an error
![изображение](https://user-images.githubusercontent.com/1389048/182029758-63072e3b-fc0a-40ed-9a8c-29824a0804d7.png)
We do not have a reproducer

Have any ideas why `mqttAccountSessionManager` have is nil?
https://github.com/nats-io/nats-server/blob/66524ed715a72db192ec93465bf24391f7696f3f/server/mqtt.go#L1853

https://github.com/nats-io/nats-server/blob/66524ed715a72db192ec93465bf24391f7696f3f/server/mqtt.go#L3522-L3527

But `mqttAccountSessionManager` is sayed `quick reference to account session manager, immutable after processConnect()`
https://github.com/nats-io/nats-server/blob/66524ed715a72db192ec93465bf24391f7696f3f/server/mqtt.go#L313

In another goroutine trying to work with a client who is not yet ready?
https://github.com/nats-io/nats-server/blob/66524ed715a72db192ec93465bf24391f7696f3f/server/mqtt.go#L2815

Please, any ideas. Thx

PS nats-server v2.8.4

**Comment by derekcollison** [comment]
Thanks will take a look and make sure a fix is in place for the upcoming 2.9 release.

**Comment by kozlovic** [comment]
@gebv I believe that the issue has been identified and fixed in PR #3315. I suspect that you have client(s) that keep connecting using the same "client ID" while clients are still connected. You should have a look at your environment.

**Comment by gebv** [comment]
Thx for quick and detailed response
Have reconnection with the same client ID - it is legacy, WIP migrate from vernemq
Added into v2.8.4 current patch
We'll watch in the sandbox

**Comment by kozlovic** [comment]
> Have reconnection with the same client ID - it is legacy

To be clear, "reconnecting" with the same client ID is not bad, but what is happening is that you have applications connecting with the client ID of a currently connected application. This is causing the currently connected to be evicted by the server (as per spec), but then that client (or another) is again trying to (re)connect with the same client ID, which then the server detects as a "flapping" condition. This should be looked at.

**Comment by gebv** [comment]
@kozlovic for e.g. exists working connection to the client ID. New connection with the same client ID causes disconnect exists connection? Get that right?

**Comment by kozlovic** [comment]
@gebv Correct. From specifications: https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html

Look for `MQTT-3.1.4-2` in the description of the CONNECT protocol response:
```
If validation is successful the Server performs the following steps.

1.     If the ClientId represents a Client already connected to the Server then the Server MUST disconnect the existing Client [MQTT-3.1.4-2].
```

**Comment by gebv** [comment]
@kozlovic i see, thx. This can lead to cyclic reconnections, if there will be a connection from different clients with the same client ID. Have to be careful.
