### ISSUE TITLE
insufficient storage resources available [10047] when updating stream to the same config

### ISSUE THREAD

**Issue by AqlaSolutions** [nats-io/nats-server#3321]
## Defect
I receive `insufficient storage resources available [10047]` error when trying to update stream config to the same value as it is (with 10 GB max size). 

There is enough disk space. NATS log shows max storage 20.49GB, `du -hs jetstream` shows 5.6 GB used, `df` shows 17 GB available on disk. Others streams have total max size of 3 GB. So the total streams size would be 13 GB which is less than 20.49 GB so should be ok. And 17+5.6=22.6GB is available for NATS in total including used 5.6GB.

The workaround is to delete the stream and create again.

 - [ X ] Included `nats-server -DV` output
 - [ - ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

> 
> Starting nats-server
> [1] 2022/08/01 19:08:43.595539 [INF]   Version:  2.7.4
> [1] 2022/08/01 19:08:43.595544 [INF]   Git:      [a86b84a]
> [1] 2022/08/01 19:08:43.595548 [INF]   Name:     redacted
> [1] 2022/08/01 19:08:43.595555 [INF]   Node:     redacted
> [1] 2022/08/01 19:08:43.595560 [INF]   ID:       redacted
> [1] 2022/08/01 19:08:43.595591 [INF] Using configuration file: /data/js.conf
> [1] 2022/08/01 19:08:43.596206 [INF] Starting http monitor on 0.0.0.0:8222
> [1] 2022/08/01 19:08:43.596310 [INF] Starting JetStream
> [1] 2022/08/01 19:08:43.596495 [INF]     _ ___ _____ ___ _____ ___ ___   _   __  __
> [1] 2022/08/01 19:08:43.596518 [INF]  _ | | __|_   _/ __|_   _| _ \ __| /_\ |  \/  |
> [1] 2022/08/01 19:08:43.596522 [INF] | || | _|  | | \__ \ | | |   / _| / _ \| |\/| |
> [1] 2022/08/01 19:08:43.596526 [INF]  \__/|___| |_| |___/ |_| |_|_\___/_/ \_\_|  |_|
> [1] 2022/08/01 19:08:43.596529 [INF]
> [1] 2022/08/01 19:08:43.596542 [INF]          https://docs.nats.io/jetstream
> [1] 2022/08/01 19:08:43.596546 [INF]
> [1] 2022/08/01 19:08:43.596549 [INF] ---------------- JETSTREAM ----------------
> [1] 2022/08/01 19:08:43.596556 [INF]   Max Memory:      23.52 GB
> [1] 2022/08/01 19:08:43.596562 [INF]   Max Storage:     20.49 GB
> [1] 2022/08/01 19:08:43.596566 [INF]   Store Directory: "/data/jetstream"
> [1] 2022/08/01 19:08:43.596569 [INF] -------------------------------------------
> [1] 2022/08/01 19:08:43.597978 [INF]   Restored 3,486 messages for stream '$G > common'
> [1] 2022/08/01 19:08:43.598453 [INF]   Restored 5 messages for stream '$G > redacted'
> [1] 2022/08/01 19:08:43.598903 [INF]   Restored 4 messages for stream '$G > redacted'
> [1] 2022/08/01 19:08:43.599403 [INF]   Restored 0 messages for stream '$G > redacted'
> [1] 2022/08/01 19:08:43.663732 [INF]   Restored 2,285,508 messages for stream '$G > redacted'
> [1] 2022/08/01 19:08:43.663804 [INF]   Recovering 3 consumers for stream - '$G > redacted'
> [1] 2022/08/01 19:08:43.664663 [INF]   Recovering 1 consumers for stream - '$G > redacted'
> [1] 2022/08/01 19:08:43.665430 [INF]   Recovering 112 consumers for stream - '$G > redacted'
> [1] 2022/08/01 19:08:43.686848 [INF] Listening for client connections on 0.0.0.0:4222
> [1] 2022/08/01 19:08:43.687059 [INF] Server is ready

#### OS/Container environment:
docker nats:2.7.4

#### Expected result:
Stream update request should complete successfully.

#### Actual result:
> insufficient storage resources available [10047]

**Comment by derekcollison** [comment]
Please check with latest release version, 2.8.4, or better yet most recent nightly at synadia/nats-server:nightly on docker hub.

**Comment by AqlaSolutions** [comment]
It works with 2.8.4 though I have a performance issue after the update: https://github.com/nats-io/nats-server/issues/3322
