### ISSUE TITLE
Add nkey support to RemoteLeafOpts

### ISSUE THREAD

**Issue by kung-foo** [nats-io/nats-server#3331]
## Feature Request

Add ability configure an nkey programmatically in the leafnode options.

#### Use Case:

We use a NATS server embedded in our client application. It operates as a leaf node, connecting to NGS. The nkey is _not_ stored on disk, and comes from the Windows credential store and is decrypted on demand. When using the nats.go client, we use the `Nkey` option (see https://github.com/nats-io/nats.go/blob/v1.16.0/nats.go#L1066-L1075). As we migrate to an embedded leafnode, we need the same ability to configure the user.

#### Proposed Change:

Add an option similar to the nats.go package with `type SignatureHandler func([]byte) ([]byte, error)`.

#### Who Benefits From The Change(s)?

me :partying_face: 

#### Alternative Approaches

Write the credentials out to a temporary file and hope it gets deleted on panic. And also write them out on every server reconnect...

**Comment by kozlovic** [comment]
So would a function that would accept a nonce ([]byte) and return a JWT (string) and signature ([]byte) would suffice? Since it would be part of a given remote, there is no need to pass to that callback to "identify" the remote, right? (actually, there is no such thing that names a remote, so that would be difficult).

**Comment by kozlovic** [comment]
If above proposal sounds reasonable, I can try to have a PR for review to have a better sense of how this would be used.

**Comment by kung-foo** [comment]
Nice! I tested #3335 and it worked great.
