### ISSUE TITLE
How to dynamically generate user JWT and configure permissions

### ISSUE THREAD

**Issue by qianbeibuzui** [nats-io/nats-server#3410]
$SYS.REQ.CLAIMS.UPDATE

I only know that this topic is mentioned in the document and can be uploaded to JWT
However, the content of the subject transmission is not clear

**Comment by aricart** [comment]
The payload for the message is the updated JWT.

**Comment by qianbeibuzui** [comment]
Usage scenario:
There are 100000 devices that need to be connected to nats-mqtt
I can't manually configure tokens using NSC
How to dynamically generate user JWT and configure permissions?

**Comment by qianbeibuzui** [comment]
> 消息的有效负载是更新的 JWT。

Usage scenario:
There are 100000 devices that need to be connected to nats-mqtt
I can't manually configure tokens using NSC
How to dynamically generate user JWT and configure permissions?

**Comment by bruth** [comment]
An as mentioned by @aricart, the payload is the account JWT. This is described in the example comments, but you can do:

```go
nc.Request("$SYS.REQ.CLAIMS.UPDATE", accountJWT)
```

To update the account on the server. The example also shows how to create users, set permissions, and create the creds file at the end.

**Comment by qianbeibuzui** [comment]
> 正如提到的@aricart，有效负载是帐户 JWT。这在示例注释中进行了描述，但您可以执行以下操作：
> 
> ```go
> nc.Request("$SYS.REQ.CLAIMS.UPDATE", []byte(accountJWT), time.Second)
> ```
> 
> 更新服务器上的帐户。该示例还展示了如何创建用户、设置权限以及最后创建 creds 文件。

Thank you for your patience and detoxification

**Comment by gatspy** [comment]
nats are a good product, but they are a lot of trouble to use
