### ISSUE TITLE
After creating and deleting (a lot of) accounts, Server fail to enable jetstream on new accounts.

### ISSUE THREAD

**Issue by JulienVdG** [nats-io/nats-server#3420]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [X] Included `nats-server -DV` output [nats.log](https://github.com/nats-io/nats-server/files/9459677/nats.log)
 - [X] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:
 - nats-server v2.8.4 (also tested on main v2.9.0-RC.12)
 - nsc version 2.7.2
 - nats cli version 0.0.30

#### OS/Container environment:
 Linux debian 11.4

#### Steps or code to reproduce the issue:
The following shell code :
- Configure a nats server with jwt accounts and a jetstream disk quota of 1G
- Creates an account with 900M disk size.
- Connects to it and check accounts info (ie jetstream is enabled)
- Delete the account on the server
- Creates a second one (same parameters)
- Connects to it : Here jetstream is disabled, the server log includes `Error configuring jetstream for account [xxx/TEST2]: insufficient storage resources available (10047)`

 [commands.txt](https://github.com/nats-io/nats-server/files/9459676/commands.txt)

#### Expected result:
The second account should be jetstream enabled !

#### Actual result:
Jetstream is disabled on the account.

**Comment by derekcollison** [comment]
Thanks for the report.
