### ISSUE TITLE
SubjectsCollide() returns true for non matching subjects  

### ISSUE THREAD

**Issue by piotrpio** [nats-io/nats-server#3422]
## Defect

`SubjectsCollide()` will match subjects which do not match same literal subject (e.g. `foo.*` and `foo.*.bar.>`). That issue impacts  creating consumers with `FilterSubject`, as well as listing streams with subject filter (and probably more).

I added a simple test to verify the issue:
```go
func TestSubectsCollide(t *testing.T) {
	s1 := "foo.*.bar.>"
	s2 := "foo.*"

	res := SubjectsCollide(s1, s2)

        // prints true
	fmt.Println(res)
}
```

**Comment by derekcollison** [comment]
Will take a look. Thanks.

**Comment by derekcollison** [comment]
Fixed thanks.
