### ISSUE TITLE
Client pruning/rebalancing

### ISSUE THREAD

**Issue by mcqueary** [nats-io/nats-server#343]
The server/cluster should be able to rebalance clients after the cluster composition changes, either through adding servers to the cluster, or after a failover event within the cluster.

**Comment by mcqueary** [comment]
Explore connection TTLs to cause clients to reconnect after some period.

**Comment by knspriggs** [comment]
I believe I am seeing this issue with nats 1.2.0. I am dynamically building my `--routes` list via SD, but when I roll the servers and the IPs change some of the servers complain about cluster peers that no longer exist.

```
[1] 2018/08/10 12:46:43.087745 [ERR] Error trying to connect to route: dial tcp 10.X.X.X:6222: i/o timeout
```

**Comment by kozlovic** [comment]
@knspriggs No, this has nothing to do with your issue. I did reply in the slack channel. This issue is when a server shutdown, all clients that are connected to this server will reconnect to another, which is fine. However, when a new server joins the cluster, it will likely be empty of clients. This issue says that it would be nice if some clients would automatically reconnect to that new server to spread the load.

**Comment by knspriggs** [comment]
@kozlovic understood, my mistake. Thank you for the info in the Slack channel.

**Comment by lalloni** [comment]
How is this problem dealt with, nowadays?

**Comment by derekcollison** [comment]
Manually with tooling and operations on servers such as lame duck and config reload on maximum number of connections. We do have plans here to make some of this easier and to drive some more auto switch intelligence from lame duck signaling for clients, hopefully in 1H 2022.

**Comment by lalloni** [comment]
Hi @derekcollison! Thanks for your answer. Can you share an example or more details about the strategy you mentioned?
We are trying to mitigate the issue at this moment and finding it difficult.

**Comment by derekcollison** [comment]
What specific problems are you encountering?

**Comment by derekcollison** [comment]
Might be good to coordinate with @tbeets and Brian to schedule a call.

**Comment by lalloni** [comment]
@derekcollison I would love to have that call with @tdbeets if that could be possible. Please advise on how to proceed.
