### ISSUE TITLE
String envar incorrectly inferred as number

### ISSUE THREAD

**Issue by julian-dolce-form3** [nats-io/nats-server#3431]
## Defect

A String envar that starts with a digit (0-9) followed by the second character being anyone of these...
```
return r == 'k' || r == 'K' || r == 'm' || r == 'M' || r == 'g' || r == 'G' || r == 't' || r == 'T' || r == 'p' || r == 'P' || r == 'e' || r == 'E'
```
and has a length > 2, is incorrectly inferred as a number and not a string.

After stepping through the code [isNumberSuffix()](https://github.com/nats-io/nats-server/blob/c5c8e385abffcc4f0b6911a9ec25f55d2ffcca0d/conf/lex.go#L1141) gets called but I feel like it should only infer it's a number if the suffix is at the end of the string.

 - [x] Included `nats-server -DV` output
 - [x] Included a [Minimal, Complete, and Verifiable example] 

#### Steps or code to reproduce the issue:

Here is a unit test that shows the issue. It can go in `conf/parse_test.go`

```go
func TestEnvVariableString(t *testing.T) {
	ex := map[string]interface{}{
		"foo": "2GP3JZCZ4G7JNWkzBhVYx9ZXtUiu",
	}
	evar := "__UNIQ22__"
	os.Setenv(evar, "2GP3JZCZ4G7JNWkzBhVYx9ZXtUiu")
	defer os.Unsetenv(evar)
	test(t, fmt.Sprintf("foo = $%s", evar), ex)
}
```

#### Expected result:
The test passes

#### Actual result:
Errors with 
```
Received err: variable reference for '__UNIQ22__' on line 1 could not be parsed: Parse error on line 1: 'Expected a top-level value to end with a new line, comment or EOF, but got 'P' instead.'
```

**Comment by kozlovic** [comment]
@julian-dolce-form3 As you can see in parse_test.go, we have a test called `TestEnvVariableStringStartingWithNumber` that catches that we fail if a string (without quotes) starts with a number. To parse the string which starts with a number one would have to use quotes, like in test `TestEnvVariableStringStartingWithNumberUsingQuotes`.
Would that be possible for you to set the env variable surrounded with quotes `'`?
