### ISSUE TITLE
What is the Max Range for Stream Sequence Number & Consumer Sequence Number ?

### ISSUE THREAD

**Issue by hellfire1980** [nats-io/nats-server#3437]
I would like to understand what is the max running number range for both stream sequence and consumer sequence number? Secondly if there is a max limit range, what would happen when the running sequence number reach?

**Comment by ripienaar** [comment]
It's a `uint64`, which is very large indeed, in practise its a bit less than that at around 9007199254740991

**Comment by ripienaar** [comment]
Note this is theoretical its impossible to reach these numbers on many dimensions

**Comment by derekcollison** [comment]
That is signed, unsigned is double that, and at 250k msgs per sec would take you ~2.34M yrs to get to it.. 

2^64 / (250_000*60*60*24*365)

**Comment by ripienaar** [comment]
The number I mentioned is where we exceed the JSON spec max number at which point things will not work. But anyway it’s all theoretical

**Comment by derekcollison** [comment]
Ah gotcha..
