### ISSUE TITLE
Auto-unsubscribe should be atomic with SUB operation

### ISSUE THREAD

**Issue by mcqueary** [nats-io/nats-server#344]
Currently, auto-unsubscribe requires 2 protocol operations:

`SUB <subject> [queue group] <sid>\r\n` 

followed by: 

`UNSUB <sid> [max_msgs]`

Ideally, auto-unsubscribe would be atomic with the subscribe op, e.g.:

 `SUB <subject> [queue group] <sid> [max_msgs]\r\n`

**Comment by simonrussell** [comment]
I'd also put in a similar request for a PUB operation to allow for auto-subscribing to the reply subject, potentially with an optional max_msgs.

**Comment by chiaolun** [comment]
Was this implemented or abandoned? Didn't see any change on https://docs.nats.io/reference/reference-protocols/nats-protocol#sub

**Comment by derekcollison** [comment]
It was not.
