### ISSUE TITLE
Possible regression in pull consumer fetch to maximize batch size

### ISSUE THREAD

**Issue by bruth** [nats-io/nats-server#3455]
In nightly, given a stream that is pre-populated and a pull consumer with two (or more) subscriptions using separate connections, a combined fetch size (between all subscriptions) that is smaller than max ack pending, I am observing varying returned batch sizes rather than the max size.

I tested the same code against the nightly tagged for July 5th and the issue was not observed. I tested the nightly tagged July 6th and the issue is present. Here is the [commit range from July 4-6](https://github.com/nats-io/nats-server/commits/main?since=2022-07-04&until=2022-07-06). Possible suspect is #3241

**Comment by derekcollison** [comment]
Can you share the test?

**Comment by derekcollison** [comment]
This might also be something I am seeing with emulated push experiments using pull consumers and max bytes.

**Comment by bruth** [comment]
This is also using latest Go client on main.

**Comment by derekcollison** [comment]
Thx

**Comment by derekcollison** [comment]
WQ policy make a difference here? If not WQ same result?

**Comment by bruth** [comment]
Interesting you call that out.. it seems to show the symptom even more with WQ than limits, but it still occurs with limits.
