### ISSUE TITLE
Max History Per Key hard limit in KeyValue store

### ISSUE THREAD

**Issue by andrea-tomassi** [nats-io/nats-server#3465]
## Feature Request
According to current specs "Max History Per Key cannot be more than 64".

Is there any tech constraint for such a low number? 

#### Use Case:
Any with a need for an higher history

#### Proposed Change:
unlock the max-history value and allow reading recent history only by selecting the last number of items/by date
e.g. 		nc.keyValue(storeName).history("store-name", 10) should return the lastest 10 items from history

**Comment by derekcollison** [comment]
I think this is a Go client, and other client limitation, not a server one IIRC.

**Comment by derekcollison** [comment]
Believe Go client relaxed this.

**Comment by solita-cristian** [comment]
This is still the case for both NATS client and server libraries 🤔

**Comment by derekcollison** [comment]
This is not enforced by the server, this is a client side thing. @Jarema

**Comment by Jarema** [comment]
This is being discussed here https://github.com/nats-io/nats.go/issues/1365 and as @derekcollison mentioned, we only need to change it on client side. This ticket should remain closed.
