### ISSUE TITLE
Consumer groups get created on the same peer when consumer's replica count = 1

### ISSUE THREAD

**Issue by goku321** [nats-io/nats-server#3469]
When a consumer's replica count is 1, there's no randomisation when selecting a peer. Always the first peer is selected due to which consumers distribution is not uniform across the servers:
https://github.com/nats-io/nats-server/blob/f7cb5b1f0d8802655b789042188db0679a1094d3/server/jetstream_cluster.go#L5953

**Comment by derekcollison** [comment]
Thanks for the contribution!
