### ISSUE TITLE
Add Server defaults for HA asset limits

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats-server#3503]
## Feature Request

Add server wide defaults for limits around JetStream HA Assets in order to prevent an overload of RAFT traffic, etc.

e.g. max_ha_assets=512

The error message could display the option/param to override for convenience.

#### Who Benefits From The Change(s)?

JetStream users, especially those with runaway consumers or applications.

#### Alternative Approaches

a) Set these in account tier configurations
b) Warn when HA Assets reach a predefined limit.

**Comment by derekcollison** [comment]
Was added.
