### ISSUE TITLE
How to view all subjects on one JetStream via nats-box?

### ISSUE THREAD

**Issue by intfish123** [nats-io/nats-server#3505]

**Comment by Jarema** [comment]
If you want to check messages on a stream, regardless of subject, you can use
```
nats stream view
```

if you want to check what subjects given stream is listening to
```
nats stream info
```

Is that what you asked for?

In the future, when you have questions, it's better to them ask in [discussions]https://github.com/nats-io/nats-server/discussions) in relevant repository.

**Comment by ripienaar** [comment]
Latest nats CLI has “nats stream subjects”. Not sure if nats box has that yet.

**Comment by usatenko** [comment]
is it possible to get nats stream subjects from java client? I do not see this function implemented

**Comment by jnmoyne** [comment]
In Java from StreamInfo (you must pass a subjectFilter value such as ">" or allSubjects() in the StreamInfoOptions) you can then call `getStreamState()` which returns a `StreamState` object on which you can then call `getSubjects()`.

**Comment by ripienaar** [comment]
To do nats stream view you need to enable the direct get setting on the stream config.

**Comment by zakk616** [comment]
> To do nats stream view you need to enable the direct get setting on the stream config.

I have re-created stream with `Direct Get` to `true`. 
![image](https://github.com/nats-io/nats-server/assets/26119949/4c0e5bb5-86d6-441e-892a-6ee0acd94e7f)

now when I run `nats str view streamName` ,I encounter the error:
![image](https://github.com/nats-io/nats-server/assets/26119949/b95de042-4806-4f54-894c-01ab6ffff2b1)

**Comment by ripienaar** [comment]
OK, what you're encountering now is a bug - if you're able to run main of the `nats` command it should work, otherwise for now you cannot view a WQ stream when other consumers are present.

Subjects list though will work
