### ISSUE TITLE
Request/idea: expose more internals through NATS protocol

### ISSUE THREAD

**Issue by simonrussell** [nats-io/nats-server#351]
The idea here is to get the ability to see status and potentially control NATS through the NATS connection itself.  So special subjects which show clients connecting/disconnecting, memory usage stats.  Potentially an endpoint to send configuration updates to.

The existing authorisation framework could be used to lock this down, or alternatively a new "admin" role could be introduced so only certain users have access to this info.

**Comment by mcqueary** [comment]
@simonrussell Basically `CONTROL` messages. I like the general idea. @ColinSullivan1 and I have discussed it before, although not recently. Deserves some further discussion, although right now it doesn't seem pressing.

**Comment by simonrussell** [comment]
Yeah, I agree it's not pressing; just seems like it would round things out a bit.

**Comment by derekcollison** [comment]
With the addition of accounts now we have a platform such that the servers can communicate events from an internal account and other accounts can import and have permissions on who can see them, etc.

**Comment by derekcollison** [comment]
We now have system accounts with v2.0.0.
