### ISSUE TITLE
Exit code 1

### ISSUE THREAD

**Issue by pboguslawski** [nats-io/nats-server#3514]
After successfull startup and receiving term signal, nats-server process exits to OS with code 1 not 0:
```
2022/09/30 01:51:51.456360 [INF] Starting nats-server
2022/09/30 01:51:51.456569 [INF]   Version:  2.9.1
2022/09/30 01:51:51.456575 [INF]   Git:      [not set]
2022/09/30 01:51:51.456584 [INF]   Cluster:  [...]
[...]
2022/09/30 01:51:51.456689 [INF] Using configuration file: /etc/nats-server.conf
2022/09/30 01:51:51.457877 [INF] Listening for client connections on 0.0.0.0:4222
2022/09/30 01:51:51.458188 [INF] Server is ready
2022/09/30 01:51:51.458631 [INF] Cluster name is [...]
2022/09/30 01:51:51.458653 [WRN] Cluster name was dynamically generated, consider setting one
2022/09/30 01:51:51.458704 [INF] Listening for route connections on 0.0.0.0:4244
2022/09/30 09:05:37.878218 [INF] Initiating Shutdown...
2022/09/30 09:05:37.878727 [INF] Server Exiting..

# here unexpected subservice exit code 1; should be 0 because no errors occured?
```

**Comment by kozlovic** [comment]
@pboguslawski Although I agree that SIGTERM is supposed to be a normal exit, there is history in why we need to return status 1, and it has to do with some tooling or k8s if I recall correctly. In some situations, if we were to exit(0), the process would not be restarted by manage services. Here is the PR where we made it exit(1): https://github.com/nats-io/nats-server/pull/2103. Maybe @wallyqs will have more details.

I would recommend that you send SIGINT if you want an exit(0).
