### ISSUE TITLE
nats-server missing third flag option for server name in the usage message

### ISSUE THREAD

**Issue by ariel-zilber** [nats-io/nats-server#3521]
## Defect
The printed usage message of server options for the nats server describes two methods of setting up the server Name:

```
    -n, --name <server_name>         Server name (default: auto)
```

However a third "hidden" flag possabilty exists in the opts.go file in the ConfigureOptions method:
```
	fs.StringVar(&opts.ServerName, "n", "", "Server name.")
	fs.StringVar(&opts.ServerName, "name", "", "Server name.")
	fs.StringVar(&opts.ServerName, "server_name", "", "Server name.")
```

Please either remove the third option "server_name" in the ConfigureOptions method in the opts.go file or  update the usage guide

#### Versions of `nats-server` and affected client libraries used:
Latest commited version "37ca972251d517d3ca5a4046b647b1c3824cfeb8"

**Comment by kozlovic** [comment]
Closed by #3527

(Note, in fure PRs, if you add this to your commit message, the issue will auto-close when the PR is merged:
```
Resolves #<number>
```
