### ISSUE TITLE
After lot of restart due to oom nats panic: corrupt state file

### ISSUE THREAD

**Issue by TomasVojacek** [nats-io/nats-server#3535]
## Defect
On nats cluster affected by 
[https://github.com/nats-io/nats-server/issues/3517](https://github.com/nats-io/nats-server/issues/3517)
afer 1115 restarts on container nats server panic on start.

#### Versions of `nats-server` and affected client libraries used:
[56] 2022/10/10 11:11:13.961798 [INF] Starting nats-server
[56] 2022/10/10 11:11:13.961853 [INF]   Version:  2.9.3-beta.1
[56] 2022/10/10 11:11:13.961859 [INF]   Git:      [cb086bce]
[56] 2022/10/10 11:11:13.961863 [DBG]   Go build: go1.19.1
#### OS/Container environment:
AWS EKS 
#### Steps or code to reproduce the issue:
start 3x nats cluster, with slow disks, create jetstream with file storage and 3 replicas. Push more data than disk are able consume, until nats write disk cache cause container to OOM. Since that nats cluster is in OOM loop after while data on disk are corrupted and nats panic.
#### Expected result:
nats and try to recover from last state
#### Actual result:

nats fail to start:
[142] 2022/10/10 11:00:45.333410 [DBG] Exiting consumer monitor for '$G > STX_SERVER_DATA > DB_SERVICE' [C-R3F-OuTvxCQ0]
panic: corrupt state file

goroutine 51 [running]:
github.com/nats-io/nats-server/v2/server.(*jetStream).applyConsumerEntries(0xc00024c000, 0xc000262d80, 0x0?, 0x0)
	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:3992 +0x816
github.com/nats-io/nats-server/v2/server.(*jetStream).monitorConsumer(0xc00024c000, 0xc000262d80, 0xc000251680)
	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:3871 +0xdc6
github.com/nats-io/nats-server/v2/server.(*jetStream).processClusterCreateConsumer.func1()
	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:3585 +0x25
created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine
	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/server.go:3077 +0x85

**Comment by derekcollison** [comment]
Thanks will take a look.

**Comment by kozlovic** [comment]
@TomasVojacek Were there an error with the following pattern:
```
JetStream cluster could not decode consumer snapshot for '%s > %s > %s' [%s]
```
prior to the panic? We could try to get the files for this consumer (with the error I mentioned above, you should get the name of the consumer for which there was the panic) and the files would be under the datastore's "system" account directory. Suppose the system account is named SYS and a consumer is named `C-R3F-0BBfiMRm` (in my env), this would be the directory to get the data from:
```
$ ls -lrt ~/dev/datastore/ds1/jetstream/SYS/_js_/C-R3F-0BBfiMRm/msgs/
total 16
-rw-r-----  1 ivan  staff  85 Oct 10 10:01 1.blk
-rw-r-----  1 ivan  staff  33 Oct 10 10:01 1.idx
```
We could try to see what type of corruption occurred.

Assuming it is real corruption (meaning file "truncated"), then maybe the server should not panic on those cases and try to reset the cluster in hope to be able to recover from the remaining servers? (@derekcollison what do you think?)

**Comment by michele** [comment]
@kozlovic same thing happened to me (v2.8.4) and I've got a message with that pattern (in my case: C-R3F-TV46t2a7), what should I do to understand why it's corrupted?

**Comment by kozlovic** [comment]
@michele The idea would be to find the snapshot entry in the files and see where in decodeConsumerState() it fails. If it is because there were not "enough bytes" then I would consider this a "normal" corruption where the file was not entirely flushed. The only other place I think where it would return "corrupt state" is if the stream sequence is 0 (even after adjusting for ack floor). This would be more of a bug that we would need to figure out.
You could remove the `C-R3F-xxx` directory (after making a copy just in case) and see if this gets recreated with the help of the other servers.

**Comment by MauriceVanVeen** [comment]
Noticing this panic as well within K8S using the Helm charts (https://github.com/nats-io/k8s).

No excessive restarts or even OOM. Running three instances, one with around 1 GB and two with around 700 MB RAM used.
Just doing a `kubectl rollout restart nats` to normally restart the instances.

Weirdly enough this happened to two different instances. First nats-2 complained about one consumer, and then nats-1 complained about another one (see below stacktrace).

```
[67] 2022/10/21 09:09:01.145997 [ERR] JetStream cluster could not decode consumer snapshot for 'stream > diff > area-monitor_0' [C-R3F-lzn0afI4]
panic: corrupt state file

goroutine 1578 [running]:
github.com/nats-io/nats-server/v2/server.(*jetStream).applyConsumerEntries(0xc000270000, 0xc00036c480, 0xc002fbda00?, 0x0)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:3992 +0x816
github.com/nats-io/nats-server/v2/server.(*jetStream).monitorConsumer(0xc000270000, 0xc00036c480, 0xc014864b40)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:3871 +0xdc6
github.com/nats-io/nats-server/v2/server.(*jetStream).processClusterCreateConsumer.func1()
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:3585 +0x25
created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/server.go:3077 +0x85
```

**Comment by MauriceVanVeen** [comment]
Seems like most things became corrupted. Also noticing this:
```
[48] 2022/10/21 09:18:55.185675 [WRN]     Error unmarshalling consumer metafile "/data/jetstream/events/streams/event-stream/obs/event-history-processor/meta.inf": unexpected end of JSON input
```

**Comment by MauriceVanVeen** [comment]
In general it seems that running within Kubernetes / AWS EKS, when NATS is using more memory (when it starts moving up from average 400MB usage towards 1GB). It starts to get slower, our applications to get more JS request/reply-related timeouts and throughput degrading.

Are there things I can do to diagnose this more, the next time it comes up?

**Comment by derekcollison** [comment]
First could you send us a copy of the <STORE-DIR>/<ACCOUNT>/streams/<STREAM>obs directory?
Also what version are you using currently for both the server and the helm chart?
What resource constraints are you placing on the servers?
What instance type are you running?

**Comment by MauriceVanVeen** [comment]
Helm chart: 0.18.1, nats-server: 2.9.3 (`nats:2.9.3-alpine`).
Three NATS nodes running on separate AWS `c6i.xlarge` instances. Attached volumes are gp3 with the default 3000 IOPS and 125MB/s throughput.

Our Helm values: [helm_values.yaml](https://github.com/nats-io/nats-server/files/9840740/helm_values.yaml.txt)
In short, every NATS node runs on their own instance and no other applications are running on it except for NATS itself.

Running 3 streams; with R=3 file-based, TTL of 1h. They receive 3.5k messages/s, 700 messages/s and 50 messages/s. 5 total consumers: respectively 2, 2, and 1 on those streams.

Have quickly re-installed NATS to fix the issue for now. Will report back next week when it triggers again, to share that directory for the instance that reports the corruption.

**Comment by MauriceVanVeen** [comment]
@derekcollison turns out those volumes were still available, so can share the exact files related to those error messages already.

Files related to: https://github.com/nats-io/nats-server/issues/3535#issuecomment-1286685276 (I manually shortened the stream and consumer name in the comment for readability, so they are longer in the zip itself)
[obs-for-stacktrace.zip](https://github.com/nats-io/nats-server/files/9844592/obs-for-stacktrace.zip)

Files related to: https://github.com/nats-io/nats-server/issues/3535#issuecomment-1286692701 (the `meta.inf` file seems to just be empty)
[obs-for-unexpected-end-json.zip](https://github.com/nats-io/nats-server/files/9844594/obs-for-unexpected-end-json.zip)

**Comment by derekcollison** [comment]
Thanks will take a look.

**Comment by derekcollison** [comment]
These were actually ok.

**Comment by MauriceVanVeen** [comment]
Sadly can't collect that data anymore as it's already removed, next time I'll know what to look for.
_(Already messaged privately, just to keep the issue updated)_
