### ISSUE TITLE
Subject mapping doesn't work with MQTT

### ISSUE THREAD

**Issue by ozon2** [nats-io/nats-server#3547]
#### Versions of `nats-server` and affected client libraries used:

```
[53] 2022/10/12 12:53:59.709111 [INF] Starting nats-server
[53] 2022/10/12 12:53:59.709136 [INF]   Version:  2.9.1
[53] 2022/10/12 12:53:59.709145 [INF]   Git:      [2363a2c]
[53] 2022/10/12 12:53:59.709151 [DBG]   Go build: go1.19.1
```

#### OS/Container environment:

Ubuntu 22.04.1 LTS

#### Steps or code to reproduce the issue:

I'm trying to use subject mapping with MQTT and the mapping doesn't work.

My nats server is running with this config:
```
listen: 0.0.0.0:4222
http: 0.0.0.0:8222

server_name: "mqtt_server"

jetstream {
    store_dir=/var/lib/nats/data
    max_file=10Gi
}

mappings = {
  foo: bar
}

mqtt {
   port: 1883
}
```

I subscribe on the topic `bar`:
```sh
docker run --rm --net host hivemq/mqtt-cli sub --topic bar -V 3
```

In another terminal I publish a message to `foo`:
```sh
docker run --rm --net host hivemq/mqtt-cli pub --topic foo -m "test" -V 3
```

#### Expected result:

I expect the message "test" to be received on the topic `bar`.

#### Actual result:

The message is not received on `bar`. I can see the message if I subscribe on `foo` instead but it means there is no mapping.

**Comment by kozlovic** [comment]
@ozon2 Thank you for the report. I am able to reproduce and working on a fix.

**Comment by ozon2** [comment]
Thank you!
