### ISSUE TITLE
Unable to concurrently update a streams config.

### ISSUE THREAD

**Issue by DavidCockerill** [nats-io/nats-server#3551]
## Defect

When trying to concurrently update a streams config not all updates are being honored. 

#### Versions of `nats-server` and affected client libraries used:

2.9.3

#### OS/Container environment:

Mac

#### Steps or code to reproduce the issue:

Using the nats npm package

```
async function updateStream(stream, new_subject, jsm) {
	const si = await jsm.streams.info(stream);
	si.config.subjects.push(new_subject);
	await jsm.streams.update(stream, si.config);
}

async function update() {
	const jsm = await nc.jetstreamManager();

	const stream = 'mystream';
	const subj = 'mystream.*';
	await jsm.streams.add({ name: stream, subjects: [subj] });

	let update_promises = [];
	for (let x = 0; x < 3; x++) {
		update_promises.push(updateStream(stream, x.toString(), jsm));
	}
        
        await Promise.all(update_promises);
	const si = await jsm.streams.info(stream);
	console.log(si.config.subjects);
}

update.then(() =>{}).catch((err) => {console.error(err)})
```

#### Expected result:

I expect all the subjects to be in the streams config
si.config.subjects to equal `[ "mystream.*", "0", "1", "2" ]`

#### Actual result:

si.config.subjects equals `[ "mystream.*", "2" ]`

**Comment by kozlovic** [comment]
I don't think this is a problem with the server. Looking at the code, it looks like it will be updated last with whatever x.toString() value is, which in your example is "2". We can ask @aricart to comment here, but it does not look like you are "augmenting" the list, but simply replacing with whatever last value.

**Comment by aricart** [comment]
Values that are provided are updated as specified. Values that are not updated are used as they are. In the case of the subjects, if you change the config from `["A"]`, to `["B"]`, the library will not merge other subjects for you. You'll need to get the existing values explicitly, and append them, and then supply them as the update.

If it wasn't this way, there would be no way to remove a subject from the stream configuration.

**Comment by kozlovic** [comment]
@DavidCockerill Given @aricart explanation, let us know if you are able to make it work and I will close this issue.

**Comment by DavidCockerill** [comment]
Thanks for your quick response guys. Im still trying to get my head around it. 

if i call 

```
for (let x = 0; x < 3; x++) {
  await updateStreamSource(stream, x.toString(), jsm);
}
```

it works as i thought it should...

**Comment by DavidCockerill** [comment]
Thanks for your help with this @kozlovic and @aricart
