### ISSUE TITLE
Pull consumer - notify the client about stream/consumer no being available

### ISSUE THREAD

**Issue by piotrpio** [nats-io/nats-server#3603]
## Feature Request

Currently, a `$JS.API.CONSUMER.MSG.NEXT.<stream>.<consumer>` API call does not notify the client if a given stream or consumer does not exist. Because of this, clients have to rely on heartbeats to detect any issues, but that comes with a delay and does not give any context on the error.

#### Proposed Change:

Server should send a status message on the inbox, with details on why a pull has failed (stream/consumer does not exist) and terminate the pull request immediately.

**Comment by derekcollison** [comment]
The server can send them, and I have made that change locally but the client does not break out of the fetch call atm.

Should these be 409s or 408s?
