### ISSUE TITLE
Consumer Replica R3 -> R2 while Server is offline results in hung health probe

### ISSUE THREAD

**Issue by caleblloyd** [nats-io/nats-server#3636]
Issue reported by a customer

## Version

```
Version:  2.10.0-beta.1
Git:      [deadc05c]
Go build: go1.19.2
```

## Summary
3-pod cluster.  `Pod 0`, `Pod 1`, and `Pod 2`.  `Pod 1` was taken offline due to issues, and `Stream S` with `Consumer C` were changed from R3 to R2 to remove `Pod 1` as a peer

## Issue 1

`Pod 1` came back online.  It was stuck starting up because the `/healthz` endpoint reported that it was still trying to catch-up `Consumer C` even though that was an R2 consumer that was no longer assigned to `Pod 1`

## Fix Attempt 1

`Stream S` was changed from R2 back to R3

## Issue 2

Even though `Stream S` changed from R2 to R3 and `Consumer C` had num_replicas=0 (I think this means inherit replica count from stream)?, `Consumer C` still reflected that it was R2.  `Pod 1` was still stuck trying to catch up.

## Fix Attempt 2

`Consumer C` was deleted, and `Pod 1` finally started up

**Comment by ColinSullivan1** [comment]
We just scaled down the stream (and back R3 -> R2 -> R3) and did not remove the peer.

**Comment by derekcollison** [comment]
With top of main (2.9.10-beta.1) I can not get this to reproduce..

**Comment by derekcollison** [comment]
Tested via https://github.com/nats-io/nats-server/commit/f5d939ec2455995346cdb2fe32b0ca18621a7f04
