### ISSUE TITLE
JetStream last sequence mismatch error keeps occuring after every restart/deployment

### ISSUE THREAD

**Issue by sourabhaggrawal** [nats-io/nats-server#3644]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ ] Included `nats-server -DV` output
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:
2.9.6
#### OS/Container environment:
Ubuntu 20.04.4
#### Steps or code to reproduce the issue:
Our Performance Test  cluster is 5 node cluster on aws m5.4xlarge machine, with jetstream max memory configured as 60GB.

We are creating 500 R3 file streams with wildcards, and publishing to unique 320K subjects in parallel. We are consuming messages by calling the GetMsg of jetstream. 
After a while we started  getting  the error.
![Screenshot 2022-11-17 at 1 54 28 PM](https://user-images.githubusercontent.com/70515711/202394356-6bd75516-98b0-47f8-976c-1aadcdb484fc.png)

Also after restarting the same node again quorum for most stream got lost and cluster leader was repeatedly getting re-elected.

**Comment by sourabhaggrawal** [comment]
All nodes started throwing below WARN for different streams after restarting all node one after another.

Wrong index, ae is &{leader:8uhmr4oG term:121 commit:42723 pterm:121 pindex:42888 entries: 1}, index stored was 44229, n.pindex is 42888

**Comment by derekcollison** [comment]
Does your stream have AllowDirect set to True?

**Comment by sourabhaggrawal** [comment]
Yes @derekcollison all streams were created with allow direct true

**Comment by derekcollison** [comment]
For stream_360 I would do a `nats stream cluster step-down stream_360` and see if that resolves.

If it does not, you could scale that stream down to 1 and back up to 3.

`nats s update stream_360 --replicas 1 -f`

and then..

`nats s update stream_360 --replicas 3 -f`

If you want to review operation before executing remove the `-f`

**Comment by sourabhaggrawal** [comment]
Hi @derekcollison  
I could try this but I was getting this error for many streams. 

Now I changed the cluster node type from m5.4xlarge to c5.4xlarge to run the same setup and I  don't see this issue there. Restarted 2-3 times in middle of the load and cluster came back to healthy, there were some logs of stream quorum lost but they recovered soon, 
I noticed one issue related to "nats server report jetstream " command which I have raised [here](https://github.com/nats-io/nats-server/issues/3651) . This worked for me now, I will try your steps also on m5.4xlarge instance again.

**Comment by derekcollison** [comment]
I wonder if you were saturating the network? Do you monitor the network between nats-servers?

**Comment by ripienaar** [comment]
"up to" is mostly a lie, see https://twitter.com/dvassallo/status/1120171727399448576?lang=en and https://cloudonaut.io/ec2-network-performance-cheat-sheet/

**Comment by derekcollison** [comment]
Any updates here? Any data on network throughput and utilization while this was being experienced? Is issue still happening?

**Comment by sourabhaggrawal** [comment]
Hi @derekcollison did not get a chance to run this again. It does not occur on c5.4xlarge machine but soon gonna try this again on m5.4xlarge machine on which the issue was noticed.

**Comment by derekcollison** [comment]
I would recommend m5n.8xlarge..

**Comment by derekcollison** [comment]
Going to close this but feel free to re-open if needed.
