### ISSUE TITLE
Users able to subscribe to subject they are not allowed

### ISSUE THREAD

**Issue by no-cool-name** [nats-io/nats-server#3647]
## Defect 

We are trying to test the security model of the NATS. We found the user is able to subscribe to the subject it is not allowed to.

![image](https://user-images.githubusercontent.com/112496670/202458395-8789b767-9605-40fe-a585-a1db28d793b9.png)

#### Versions of `nats-server` and affected client libraries used:

`NATS Utility` cli, `nsc`

#### OS/Container environment:

macOS Ventura 13.0

#### Steps or code to reproduce the issue:

1. We create account `TestOperator` using coomand.

    `nsc add operator --generate-signing-key --sys --name TestOperator`

2. Add account `TestAccount` 
     `nsc add account TestAccount`

3. Generate the signing key
      `nsc edit account TestAccount --sk generate`

4. Add users `TestUser1` & `TestUser2` to the account
      `nsc add user --account TestAccount TestUser1`

5. Generate creds for both the users.
       `nsc generate creds -n TestUser1 > user1.creds`

6. Allow the user to publish and subscribe to the Subject
     `nsc edit user -n TestUser1 --account TestAccount --allow-pub "sub.user1" --allow-sub "sub.user1"`

      `nsc edit user -n TestUser2 --account TestAccount --allow-pub "sub.user2" --allow-sub "sub.user2"`
      
      
      I expected that `TestUser1` will be able to subscribe to subject `sub.user1` but it could also subscribe to `sub.user2` and same goes for the `TestUser2`.
      
      If I understand the security model right this should not be allowed. As these should restrict the subjects to which as user can subscribe and publish to.

#### Expected result:

Users should only allowed to subscribe to topics they are allowed.

#### Actual result:

User are able to subscribe to topics they are not allowed.

**Comment by bruth** [comment]
@no-cool-name Can you confirm the command you use to run the server with the generated operator config included? e.g. `nats-server -c operator.conf`

Here is an end-to-end example of setting up the server and testing out the permissions you defined. https://nats-by-example-na86bygzo-connecteverything.vercel.app/examples/auth/jwt-perms/cli

**Comment by aricart** [comment]
@no-cool-name on step #5 you generated the creds, but on step #6 is where you add the subscription/publish constraints.

Doing a quick test:

```bash
 nsc describe jwt -f /Users/aricart/.nkeys/creds/O/T/A.creds
+---------------------------------------------------------------------------------+
|                                      User                                       |
+----------------------+----------------------------------------------------------+
| Name                 | A                                                        |
| User ID              | UAFEGIDNNUNVYSGD76OGI5SXNP3N3Q3LJV5YNGTFPUVMQ6WZ6XW6CPSU |
| Issuer ID            | ACH3TWRZNRE42LCEHZVW5Z6HY74AVETJHBAZGFZQFEWRYALDUOZ4TCRF |
| Issued               | 2022-11-17 14:08:51 UTC                                  |
| Expires              |                                                          |
| Bearer Token         | No                                                       |
+----------------------+----------------------------------------------------------+
| Pub Allow            | sub.user1                                                |
| Sub Allow            | sub.user1                                                |
| Response Permissions | Not Set                                                  |
+----------------------+----------------------------------------------------------+
| Max Msg Payload      | Unlimited                                                |
| Max Data             | Unlimited                                                |
| Max Subs             | Unlimited                                                |
| Network Src          | Any                                                      |
| Time                 | Any                                                      |
+----------------------+----------------------------------------------------------+
```

```javascript
 const auth = Deno.readFileSync("/Users/aricart/.nkeys/creds/O/T/A.creds");
  const A = await connect({authenticator: credsAuthenticator(auth)});
  (async () => {
    for await (const s of A.status()) {
      console.log(s);
    }
  })().then();
  A.publish("sub.user2");
  A.subscribe("sub.user2", {
    callback: (err, msg) => {
      console.log(err);
    },
  });
  await delay(1000);

  await A.close();
  ```

```bash
auth - nsc ...
------- output -------
NatsError: 'Permissions Violation for Subscription to "sub.user2"'
    at Function.toError (file:///Users/aricart/Dropbox/code/src/github.com/nats-io/nats.deno/nats-base-client/protocol.ts:398:19)
    at ProtocolHandler.processError (file:///Users/aricart/Dropbox/code/src/github.com/nats-io/nats.deno/nats-base-client/protocol.ts:440:33)
    at ProtocolHandler.push (file:///Users/aricart/Dropbox/code/src/github.com/nats-io/nats.deno/nats-base-client/protocol.ts:553:14)
    at Parser.parse (file:///Users/aricart/Dropbox/code/src/github.com/nats-io/nats.deno/nats-base-client/parser.ts:352:31)
    at file:///Users/aricart/Dropbox/code/src/github.com/nats-io/nats.deno/nats-base-client/protocol.ts:285:25
{
  type: "error",
  data: "PERMISSIONS_VIOLATION",
  permissionContext: { operation: "publish", subject: "sub.user2" }
}
{
  type: "error",
  data: "PERMISSIONS_VIOLATION",
  permissionContext: { operation: "subscription", subject: "sub.user2" }
}

```

**Comment by aricart** [comment]
By the way to quickly test a sane server config do:

```bash
nsc generate config --mem-resolver --config-file /tmp/server.conf
nats-server -c /tmp/server.conf
```

**Comment by bruth** [comment]
> Yes I have used the very same command to start the server.

@no-cool-name If you are only using `nats-server -DV` them this means the operator mode kind of auth is not actually setup on the server. You are creating user credentials that are not being respected/enforced by the server since the operator mode is not actually setup.

**Comment by no-cool-name** [comment]
@bruth Thanks for the response. I was not sure if this is some bug or am I doing something wrong. 

Do I need to try something special too setup the operator?

**Comment by no-cool-name** [comment]
Thanks @aricart

**Comment by bruth** [comment]
I updated the example to reproduce what you are observing.. simply by removing the `resolver.conf` in my server config, everything else staying the same, I no longer get authorization errors: https://nats-by-example-9af2fncpu-connecteverything.vercel.app/examples/auth/jwt-perms/cli#output

> I was not sure if this is some bug or am I doing something wrong.

You are missing a couple steps to setup this operator auth properly. If you look first linked example above, you will see that you need to generate the resolver using nsc:

```
nsc generate config --nats-resolver --sys-account SYS > resolver.conf
```

And then you need to start the server with the resolver:

```
nats-server -c resolver.conf
```

Then you push the account(s) up to the server.

```
nsc push -A
```

(again, take a look at the example and it shows all the steps to setup properly).

All that said, even though its technically misconfiguration, this was useful for us to observe the behavior. Our takeaway is that the server should reject clients attempting to connect with credentials even though it is unaware of any authentication that is required.

**Comment by no-cool-name** [comment]
I did create the `resolver.conf` and `push` it but still saw this. I will try to do it again in clean way. Thanks for all the help @bruth @aricart
