### ISSUE TITLE
Jetstream summary shows stream 0 for some nodes after restart

### ISSUE THREAD

**Issue by sourabhaggrawal** [nats-io/nats-server#3651]
## Defect
Perf Setup of 5 node c5.4xlarge, created 500 R3 file streams (allow-direct enabled) and publishing to 320K unique subjects. 
Also usign js.GetMsg to read messages from 320K unique subjects.

Rebooted the node and ran the nats server report jetstream --creds sys.creds, for some of the node everything goes back to 0.

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ ] Included `nats-server -DV` output
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:
2.9.6
#### OS/Container environment:
Ubuntu 20.04.4
#### Expected result:
After reboot the jetstream should show the stream count it is holding. but shows 0, even after running the command multiple time I get the same result.
#### Actual result:

It should show the count same as before restart.

![Screenshot 2022-11-18 at 12 47 48 AM](https://user-images.githubusercontent.com/70515711/202538430-049a0b7a-14f2-4d7a-8913-d4cc77ea24cd.png)

![Screenshot 2022-11-18 at 12 48 19 AM](https://user-images.githubusercontent.com/70515711/202538519-e5b85309-2bc7-40b4-aa5e-b19b91ccaae1.png)

**Comment by derekcollison** [comment]
If the server can not restore/recover streams on startup (You should see log items warning of this), they will not be reported.

**Comment by derekcollison** [comment]
Is this still an issue?

**Comment by sourabhaggrawal** [comment]
Hi Derek, Not able to reproduce this now
