### ISSUE TITLE
Messages cannot be stored on stream after upgrade to 2.9.7

### ISSUE THREAD

**Issue by k15r** [nats-io/nats-server#3652]
## Defect

Nats could not store messages on the stream after upgrading the nats cluster to 2.9.7
```[ERR] JetStream failed to store a msg on stream '$G > sap': error opening msg block file [""]: open : no such file or directory```

Before the upgrade the 3 different cluster nodes reported different stream states for messages on stream.

After the upgrade the stream info looks like this:

```
Information for Stream sap created 2022-11-07 13:33:01

             Subjects: kyma.>
             Replicas: 3
              Storage: File

Options:

            Retention: Interest
     Acknowledgements: true
       Discard Policy: New
     Duplicate Window: 2m0s
    Allows Msg Delete: true
         Allows Purge: true
       Allows Rollups: false

Limits:

     Maximum Messages: unlimited
  Maximum Per Subject: unlimited
        Maximum Bytes: 900 MiB
          Maximum Age: unlimited
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited


Cluster Information:

                 Name: eventing-nats
               Leader: eventing-nats-2
              Replica: eventing-nats-0, current, seen 0.00s ago
              Replica: eventing-nats-1, current, seen 0.01s ago

State:

             Messages: 0
                Bytes: 0 B
             FirstSeq: 1,303,628,312 @ 0001-01-01T00:00:00 UTC
              LastSeq: 1,303,628,311 @ 2022-11-16T11:03:13 UTC
     Active Consumers: 2
   Number of Subjects: 2
```

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ ] Included nats.go version
 - [ ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats.go` and the `nats-server` if one was involved:
previous version of nats cluster was: 2.9.6
3 nats nodes in a cluster
1 stream (replication factor 3)
2 consumers (replication factor 3)

#### OS/Container environment:
previous image [2.9.6-alpine3.16](https://hub.docker.com/layers/library/nats/2.9.6-alpine3.16/images/sha256-abb4111e51c329aba5d98f59258cbcbe33991478a70ed25a4c1b5e53a05ab284?context=explore)
upgrade image [2.9.7-alpine3.16](https://hub.docker.com/layers/library/nats/2.9.7-alpine3.16/images/sha256-d4698031a0afeb1ed37b240a9632b22a2d0fcea5fd48af3c8b28e1eba3348033?context=explore)

#### Steps or code to reproduce the issue:
it happened with the upgrade.

#### Expected result:
everything works as expected

#### Actual result:
```[ERR] JetStream failed to store a msg on stream '$G > sap': error opening msg block file [""]: open : no such file or directory```

**Comment by derekcollison** [comment]
Thanks for the configs.

Would have been useful to be able to examine the storage directories for each server in that instance.

Is the cluster back up and running?

**Comment by k15r** [comment]
i have the storage directories of a cluster that showed similar symptoms later after upgrading to nightly a few days ago

**Comment by derekcollison** [comment]
I can see strange behavior from the files you sent, even just restoring the snapshot into a cluster I setup. Digging in more, will keep you posted.

**Comment by derekcollison** [comment]
Actually I do not see any strange behavior, was me testing sending to a subject but did not check that the consumers were filtered, which they are. So after I sent to one of those messages are retained and all working well.

I also did not see any errors like you showed when restoring from the snapshot you sent, but will plug in the actual data files not in raw form and check those.

**Comment by derekcollison** [comment]
ok so tested each directory, they all looked a bit different which was strange and one on recovery stated it recovered more messages than the others but when I did a stream info and tested that I could put new messages in they all were consistent.

Also not reports that matched 

`[ERR] JetStream failed to store a msg on stream '$G > sap': error opening msg block file [""]: open : no such file or directory`

**Comment by derekcollison** [comment]
Are you still seeing this issue at all?

**Comment by derekcollison** [comment]
What is the storage system underneath?

Direct attached? SAN, a volume under something like k8s?

**Comment by kino71** [comment]
Hi, I'm getting the same error on 2.9.9

[3350802] 2022/12/15 10:41:56.721781 [ERR] JetStream failed to store a msg on stream 'mercury_test > LMQS': error opening msg block file [""]: open : no such file or directory

**Comment by kino71** [comment]
This cluster is on 3 VMs with storage directly attached

**Comment by kino71** [comment]
I see this error in 2 out of 3 nodes.
stream info:

Information for Stream LMQS created 2022-05-10 16:48:35

             Subjects: QS.*.ORDER.LM, QS.*.EXEC.LM
             Replicas: 3
              Storage: File

Options:

            Retention: Interest
     Acknowledgements: true
       Discard Policy: Old
     Duplicate Window: 2m0s
           Direct Get: true
    Allows Msg Delete: true
         Allows Purge: true
       Allows Rollups: false

Limits:

     Maximum Messages: unlimited
  Maximum Per Subject: unlimited
        Maximum Bytes: unlimited
          Maximum Age: unlimited
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited


Cluster Information:

                 Name: fineco_stage
               Leader: vxr-dev-nats01
              Replica: vxr-dev-nats02, current, seen 0.02s ago
              Replica: vxr-dev-nats03, current, seen 0.02s ago

State:

             Messages: 0
                Bytes: 0 B
             FirstSeq: 6,566 @ 2022-12-15T08:04:11 UTC
              LastSeq: 6,565 @ 2022-12-15T08:04:11 UTC
     Active Consumers: 84

**Comment by derekcollison** [comment]
On the nodes where this is happening can you share what the storage directory for that stream looks like? A tree command would suffice.

**Comment by kino71** [comment]
Sure, tree output attached
[tree.txt](https://github.com/nats-io/nats-server/files/10237121/tree.txt)

**Comment by derekcollison** [comment]
You running latest server @kino71 ?

**Comment by derekcollison** [comment]
ok thanks. So if you try to add a message into the stream that succeeds but two of the three instances will log that they have an empty file name for the block they are trying to write to yes?

**Comment by derekcollison** [comment]
Did you do a server restart or had the servers been running for awhile?

**Comment by kino71** [comment]
It started after a server restart on Dec 13th.

We did a test, a publish with a c++ program (nats.c) failed with:
Unable to publish: nats: error opening msg block file [""]: open : no such file or directory

**Comment by kino71** [comment]
I apologize, it was a golang program (js.Publish)

**Comment by kino71** [comment]
Log line is very frequent:
...

[3350802] 2022/12/15 14:28:52.403022 [ERR] JetStream failed to store a msg on stream 'mercury_test > LMQS': error opening msg block file [""]: open : no such file or directory
[3350802] 2022/12/15 14:28:52.516587 [ERR] JetStream failed to store a msg on stream 'mercury_test > LMQS': error opening msg block file [""]: open : no such file or directory
[3350802] 2022/12/15 14:28:52.604339 [ERR] JetStream failed to store a msg on stream 'mercury_test > LMQS': error opening msg block file [""]: open : no such file or directory
[3350802] 2022/12/15 14:28:52.717993 [ERR] JetStream failed to store a msg on stream 'mercury_test > LMQS': error opening msg block file [""]: open : no such file or directory
[3350802] 2022/12/15 14:28:52.805563 [ERR] JetStream failed to store a msg on stream 'mercury_test > LMQS': error opening msg block file [""]: open : no such file or directory
.....

**Comment by kino71** [comment]
I just restart only one node with that issue, everything is back to normal.
Publish succeded, too

**Comment by derekcollison** [comment]
Trying to see if this recent bug fix could be responsible somehow.

https://github.com/nats-io/nats-server/commit/1a55eb5a7abde8c59b46b39b326966af091b5f8e

Can you share stream info for LMQS?

**Comment by kino71** [comment]
stream info for LMQS below.
If you compare that with previous post, you'll that first seq / last seq / deleted messages changed a lot.
That happend after the node restart


Information for Stream LMQS created 2022-05-10 16:48:35

             Subjects: QS.*.ORDER.LM, QS.*.EXEC.LM
             Replicas: 3
              Storage: File

Options:

            Retention: Interest
     Acknowledgements: true
       Discard Policy: Old
     Duplicate Window: 2m0s
           Direct Get: true
    Allows Msg Delete: true
         Allows Purge: true
       Allows Rollups: false

Limits:

     Maximum Messages: unlimited
  Maximum Per Subject: unlimited
        Maximum Bytes: unlimited
          Maximum Age: unlimited
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited


Cluster Information:

                 Name: fineco_stage
               Leader: vxr-dev-nats02
              Replica: vxr-dev-nats01, current, seen 0.51s ago
              Replica: vxr-dev-nats03, current, seen 0.51s ago

State:

             Messages: 2
                Bytes: 509 B
             FirstSeq: 6,244 @ 2022-11-30T10:16:39 UTC
              LastSeq: 799,271 @ 2022-12-15T13:51:00 UTC
     Deleted Messages: 793,026
     Active Consumers: 84
   Number of Subjects: 2

**Comment by derekcollison** [comment]
Can you show me consumer report for that stream as well?

**Comment by kino71** [comment]
con report in attach
[conreport.txt](https://github.com/nats-io/nats-server/files/10237592/conreport.txt)

**Comment by kino71** [comment]
yes, those belongs to programs that still have to be adapted to use nats

**Comment by derekcollison** [comment]
ok I think I might have found it.

**Comment by kino71** [comment]
thanks!
