### ISSUE TITLE
desabling/reenabling account leads to inconsistent jetstream info

### ISSUE THREAD

**Issue by JulienVdG** [nats-io/nats-server#3655]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included `nats-server -DV` output
 
[nats-server.log](https://github.com/nats-io/nats-server/files/10055820/nats-server.log)

 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

[commands.txt](https://github.com/nats-io/nats-server/files/10066410/commands.txt) (updated file)

#### Versions of `nats-server` and affected client libraries used:
nats-server 2.9.7

#### OS/Container environment:
debian 11

#### Steps or code to reproduce the issue:
see attached commands.txt

#### Expected result:
Pushing the jwt could reenable the account even without resigning it (this is more a feature request, but here again restarting the server makes the account valid again event on 2.9.6 where resigning was sufficient to get back the stream ).
Once jetstream is active on the restored account it should have the stream ready without restarting the server.

#### Actual result:
A restart is needed and the intermediate state is probably unsafe (ie: what if we try to re-create the existing stream ... untested)

**Comment by JulienVdG** [comment]
By the way I'm sorry I didn't find that earlier ...  I had issues in my test environment to fix that delayed testing with the fix in #3627

**Comment by JulienVdG** [comment]
Quite quick, Already fixed with another issue I guess. Can you point me to the fix so I can test it tomorrow ?

Oh ! :thinking:  or my comment was not clear, I apologized for not finding the issue, it's not fixed in v2.9.7 its even worse than before the fix in #3627 .

**Comment by derekcollison** [comment]
Apologies, will re-open.

**Comment by JulienVdG** [comment]
[commands.txt](https://github.com/nats-io/nats-server/files/10066410/commands.txt)
Here is an updated command file (I just found that I didn't save the last version of the file before ... :disappointed: )

**Comment by JulienVdG** [comment]
The important part is that after restoring the account, `nats str info MyStream` resturns an error
`nats: error: could not pick a Stream to operate on: no Streams are defined`

**Comment by derekcollison** [comment]
I believe this is handled, this will be in 2.9.10 release next week.

**Comment by wallyqs** [comment]
Fixed via #3687, thanks again for the commands to reproduce.
