### ISSUE TITLE
Subject mapping partition distribution

### ISSUE THREAD

**Issue by OpenGuidou** [nats-io/nats-server#3660]
## Defect

Testing the subject mapping with partitions, it seems that the distribution is only based on the second level of the subject.
When creating a mapping with more than 2 levels (see example below), the distribution is not correct anymore.
I discovered this behavior in my application cluster, and was able to reproduce it via unit tests in nats-server.

#### Versions of `nats-server` and affected client libraries used:
Latest

#### OS/Container environment:
Docker image + unit tests in server

#### Steps or code to reproduce the issue:
I created the following unit test in accounts_cycles_test.go, and executed it for various subjects:
```
func TestDistributedSubjectMapping(t *testing.T) {
	conf := createConfFile(t, []byte(`
		port: -1
		mappings = {
			"foo.*.*": "foo.$1.$2.{{partition(4,1)}}"
		}
	`))
	defer removeFile(t, conf)

	s, _ := RunServerWithConfig(conf)
	defer s.Shutdown()

	nc1 := clientConnectToServer(t, s)
	defer nc1.Close()

	numMessages := 40
	subjectsReceived := make(chan string)

	msg := []byte("HELLO")
	sub1, err := nc1.Subscribe("foo.>", func(m *nats.Msg) {
		subjectsReceived <- m.Subject
	})
	if err != nil {
		t.Fatalf("Unexpected error: %v", err)
	}
	sub1.AutoUnsubscribe(numMessages * 2)

	nc2 := clientConnectToServer(t, s)
	defer nc2.Close()

	// publish numMessages with an increasing id (should map to partition numbers with the range of 4 partitions)
	for i := 0; i < numMessages; i++ {
		err = nc2.Publish(fmt.Sprintf("foo.bar.%d", i), msg)
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
	}

	// verify all the partition numbers are in the expected range
	partitionsReceived := make([]int, numMessages)
	numMessagesPerPartition := make([]int, 4)

	for i := 0; i < numMessages; i++ {
		subject := <-subjectsReceived
		sTokens := strings.Split(subject, ".")
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		t1, _ := strconv.Atoi(sTokens[2])
		partitionsReceived[i], err = strconv.Atoi(sTokens[3])
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		numMessagesPerPartition[partitionsReceived[i]]++

		if partitionsReceived[i] > 4 || partitionsReceived[i] < 0 || t1 != i {
			t.Fatalf("Error received unexpected %d to partition %d", t1, partitionsReceived[i])
		}
	}
	for i := 0; i < 4; i++ {
		fmt.Println(fmt.Sprintf("Received %d messages on partition %d", numMessagesPerPartition[i], i))
	}
}
```
With the following mapping, I get a valid distribution:
"foo.*": "foo.$1.{{partition(4,1)}}"

Publishing on "foo.%d"

=== RUN   TestDistributedSubjectMapping
Received 11 messages on partition 0
Received 9 messages on partition 1
Received 9 messages on partition 2
Received 11 messages on partition 3

With one more level, then nothing is distributed anymore (I guess it's still doing the logic on $1, and it's static now).

"foo.*.*": "foo.$1.$2.{{partition(4,1)}}"

Publishing on "foo.bar.%d"

=== RUN   TestDistributedSubjectMapping
Received 0 messages on partition 0
Received 0 messages on partition 1
Received 40 messages on partition 2
Received 0 messages on partition 3

Can you tell me if my understanding of the mapping distribution is correct, and if it's a real issue ?

Best regards

**Comment by jnmoyne** [comment]
If you want to partition on more than one subject token (e.g. you want to use more than one token to create a 'composite key' on which you then partition) then you need to specify all of the wildcard indexes in the `{{Partition()}}` function call.

So your transform should actually be:
`"foo.*.*": "foo.$1.$2.{{partition(4,1,2)}}"`

Meaning partition (4 partitions) on a composite key made of the concatenation of subject wildcard tokens 1 and 2.

The transfer you had with `{{Partition(4,1)}}` means partition 4 ways according to subject token wildcard 1 (only), and since that token is always 'foo' in your example all your messages end up in the partition that foo maps to.

**Comment by ripienaar** [comment]
You can play with the “nats server mapping” command to try these without code or deployment.

**Comment by OpenGuidou** [comment]
Thanks guys, that answers entirely my question.
I think such an explanation would be nice in the documentation.
