### ISSUE TITLE
auth_required missed when upgrade to 2.9.8

### ISSUE THREAD

**Issue by RyouZhang** [nats-io/nats-server#3673]
in 2.9.7, auth_required = true server info returned 
when upgrading to 2.98 auth_required will not return

my nats server config:

server_name: xxx
port: 4222

resolver: URL(http://xxxxx/accounts/)
monitor_port: 8222

jetstream: enabled

jetstream {
  store_dir: /data
  max_mem: 256M
  max_file: 3G
}

cluster {
  name: "SAOP"
  port: 6222

  routes = [
  "nats://nats-be-0:6222",
  "nats://nats-be-1:6222",
  "nats://nats-be-2:6222",
  ]
}

operator = /etc/nats-config/SAOP.jwt
system_account = xxxxxxx

leaf {
  port: 7422
}

**Comment by RyouZhang** [comment]
i think the issue code is https://github.com/nats-io/nats-server/pull/3659

**Comment by derekcollison** [comment]
This is a known issue that is fixed in main. 

You can clear by sending a reload signal. 
If you are using a java client there is an upgraded library that resolves an issue where it fails to authenticate.

Will be part of 2.9.9 release.
