### ISSUE TITLE
JetStream invalid file usage causing server crash when is reaching max storage usage

### ISSUE THREAD

**Issue by tibrn** [nats-io/nats-server#3676]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included `nats-server -DV` output
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:
2.9.8
#### OS/Container environment:
K8s - 2.9.8-alpine
#### Steps or code to reproduce the issue:
![image](https://user-images.githubusercontent.com/37719049/205438601-797fc2c7-6137-4678-863a-dcf8fb19cc8e.png)
![image](https://user-images.githubusercontent.com/37719049/205438410-f5ada935-7727-4e61-86d7-47083734ecb1.png)
![image](https://user-images.githubusercontent.com/37719049/205438421-6858df01-e3e0-4763-a31e-28ed984292a4.png)
![image](https://user-images.githubusercontent.com/37719049/205438500-a8b710ed-aee1-4631-be9f-83862edc89c4.png)
![image](https://user-images.githubusercontent.com/37719049/205438514-bb294fbe-1543-46f0-8e1c-b28f73c42963.png)
![image](https://user-images.githubusercontent.com/37719049/205438526-8c1f554d-f2e4-46e5-bc84-ac342f416a6c.png)

#### Expected result:
File usage to be around 1GB and the same as hard disk usage.

#### Actual result:
File usage is around 10GB while the harddisk usage is around 1GB

**Comment by derekcollison** [comment]
I would imagine your streams may have significant interior deletes. Could you share `nats stream info` for all of the streams?

Also could you share `du -ha`  from the mounted storage directories as well?

We have conservative compaction but will be improving the compaction story for 2.10 release and should have some code next week on dev branch to test out.

Thanks.

**Comment by tibrn** [comment]
![image](https://user-images.githubusercontent.com/37719049/205452500-a79d1cca-7bb0-4ce3-b92f-91635080c3d9.png)
![image](https://user-images.githubusercontent.com/37719049/205452525-d55b2414-d024-4725-be99-f4c01e656be9.png)
![image](https://user-images.githubusercontent.com/37719049/205452538-0c9efda4-a5ed-4105-a5bc-d2564b9e09c0.png)
![image](https://user-images.githubusercontent.com/37719049/205452559-4172d159-0e0d-4898-b14b-d3c1840545d5.png)
![image](https://user-images.githubusercontent.com/37719049/205452575-ea70e3d8-68f0-4e8b-9a7c-71214728e23e.png)
![image](https://user-images.githubusercontent.com/37719049/205452586-48c7e3d9-f050-4dda-9bc2-d7f105ba0650.png)
![image](https://user-images.githubusercontent.com/37719049/205452605-58962c3d-b14c-4d9f-8435-3cecd8e621f4.png)
![image](https://user-images.githubusercontent.com/37719049/205452622-9243973f-8f61-4667-acc2-db8b69fd270d.png)
![image](https://user-images.githubusercontent.com/37719049/205452631-5a1661ad-af9b-433d-83e7-bc0ccf4a3f76.png)
![image](https://user-images.githubusercontent.com/37719049/205452645-21ea7820-ee30-419e-b1ce-239ba579ab52.png)
![image](https://user-images.githubusercontent.com/37719049/205452671-8c6bc727-6031-4d07-9c82-66eca44b8599.png)
![image](https://user-images.githubusercontent.com/37719049/205452686-49d481b3-355f-450d-b46b-6a6463125b65.png)
![image](https://user-images.githubusercontent.com/37719049/205452707-86aab394-5388-4840-8b26-f55460475cd2.png)
![image](https://user-images.githubusercontent.com/37719049/205452720-ceaa3e29-c19b-4d75-b6b7-ade84104f8c8.png)
![image](https://user-images.githubusercontent.com/37719049/205452728-ed15b584-6534-40dc-a79d-acc84e493dfd.png)
![image](https://user-images.githubusercontent.com/37719049/205452734-1749d6d0-577d-4fe7-9541-98570b1d1513.png)
![image](https://user-images.githubusercontent.com/37719049/205452749-9b9fcf6f-6282-4e5e-bd69-ac114e23d1b9.png)
![image](https://user-images.githubusercontent.com/37719049/205452775-782155bb-739a-49e7-9fc3-b38cd772db71.png)
![image](https://user-images.githubusercontent.com/37719049/205452789-62291f76-1fe5-4696-bea7-cf6b81bfb77a.png)
![image](https://user-images.githubusercontent.com/37719049/205452808-d41a4df2-188b-42df-af40-6de404a79fc0.png)

**Comment by derekcollison** [comment]
ok does not seem to be interior deletes so need more info via `tree` command to see how the space is being used from the storage directories.

Although what you show above seems to be consistent with the reporting of ~1.5G of data yes?

What is taking up 10Gb as in the initial report?

**Comment by tibrn** [comment]
the report from jetstream is saying that the file storage has 10GB even if the hard disk storage used is only ~1.5GB

**Comment by derekcollison** [comment]
Ah apologies. 

Any events, like leader elections, etc?

If you restart the servers do the values reflect correctly?

**Comment by tibrn** [comment]
yes, after a restart is ok but is still increasing in time, I get these warnings in logs 
![image](https://user-images.githubusercontent.com/37719049/205455121-a5a9eb1a-95ca-4ad5-9afb-b9ac8c02a627.png)

**Comment by tibrn** [comment]
https://github.com/nats-io/nats-server/blob/c4c876129356b785f3883d3a5e8a3b5d9511b979/server/jetstream.go#L101 I think that this is not updated correctly and is causing this increase and after some time is crushing the server as he believes that the storage limit is reached, even if that is not the case

**Comment by derekcollison** [comment]
Does `nats stream report` show any streams that have replicas lagging or with an `!` next to them?

**Comment by tibrn** [comment]
![image](https://user-images.githubusercontent.com/37719049/205459265-7f18ac21-237a-4e80-a142-6aa847c0afa5.png)
yes

**Comment by derekcollison** [comment]
That looks clean to me, if a replica was behind you would see a `!` next to the name. The `*` indicates which one is the leader.

**Comment by tibrn** [comment]
Is just on replica behind for the stream with 100k msgs on nats-1

**Comment by derekcollison** [comment]
For that stream issue and `nats stream cluster step-down`

**Comment by tibrn** [comment]
<img width="655" alt="image" src="https://user-images.githubusercontent.com/37719049/205555400-af54ab62-9993-4252-8a70-3e185776d7ae.png">
now the leader is nats-0

**Comment by tibrn** [comment]
<img width="727" alt="image" src="https://user-images.githubusercontent.com/37719049/205560351-c89716e0-fcfd-403f-8c2d-bfad746ec6c0.png">
is still increasing

**Comment by derekcollison** [comment]
Would it be possible for you to shutdown the cluster and tarball up all the storage directories for our team to try to triage the edge condition?

**Comment by tibrn** [comment]
I would like to do that, but I can't as it contains data that can't be shared with 3rd party

**Comment by derekcollison** [comment]
Understood.

Could you share `nats stream info` for the stream that has the bad replica?

**Comment by tibrn** [comment]
<img width="617" alt="image" src="https://user-images.githubusercontent.com/37719049/205654114-1ad63f2b-6eea-4cec-ace4-194c7e4307fa.png">

**Comment by derekcollison** [comment]
Are you running your system with the profiling port enabled?

**Comment by tibrn** [comment]
No

**Comment by tibrn** [comment]
tried, is the same result

**Comment by derekcollison** [comment]
ok, thanks. 

If you have monitoring enabled, for the server with the `!` could you go to `/stacks` and past that here, or send me private gist etc?

e.g. `https://demo.nats.io:8222/stacksz`

**Comment by tibrn** [comment]
[stacks.txt](https://github.com/nats-io/nats-server/files/10156770/stacks.txt)

**Comment by derekcollison** [comment]
Thanks. How many streams do yo have in the system when you did that stack dump? Are they all R3?

**Comment by tibrn** [comment]
17 streams and yes they are all R3

**Comment by derekcollison** [comment]
ok thanks. I saw that the stack had 17 monitorStream go routines..

**Comment by derekcollison** [comment]
How about `nats account info` what does that show?

**Comment by tibrn** [comment]
> Do you see any of these in any server logs?
> 
> `"Error applying entries to ..."`
yes

**Comment by derekcollison** [comment]
Do these repeat and never seem to end?

**Comment by tibrn** [comment]
Oke, I think that I found the problem, I had this stream `ares` configured for file retantion and I have push consumers configured with `delivery_subject`  `ares.{something}` and I was saving the events made by nats-server/push-consumer (not sure who is sending them), now that I removed the `ares` stream from jetstream it looks ok, It didn't grow the file usage in the last 30min, still is weird that even if the ares stream only ~250Mb the file usage was growing

**Comment by derekcollison** [comment]
ok keep us posted. Will close for now but feel free to reopen as needed.
