### ISSUE TITLE
Jetstream fails to properly create consumers and jetstream in case of parallel requests

### ISSUE THREAD

**Issue by omnilight** [nats-io/nats-server#3677]
## Defect

If you are trying to add the same stream in parallel, then you receive timeouts on parallel calls and created is stream is not usable: you can not publish anything there, just get timeout

#### Versions of `nats-server` and affected client libraries used:

2.9.8

#### OS/Container environment:

Macos, Linux (any)

#### Steps or code to reproduce the issue:

Just run a test:
https://github.com/nats-io/nats-server/compare/main...omnilight:nats-server:multiple_parallel_consumers_problem

Result:
```
=== RUN   TestJetStreamParallelConsumerCreation
    jetstream_cluster_1_test.go:785: Can not add stream, unexpected error: goroutine 7, context deadline exceeded
    jetstream_cluster_1_test.go:785: Can not add stream, unexpected error: goroutine 9, context deadline exceeded
    jetstream_cluster_1_test.go:785: Can not add stream, unexpected error: goroutine 5, context deadline exceeded
    jetstream_cluster_1_test.go:785: Can not add stream, unexpected error: goroutine 0, context deadline exceeded
    jetstream_cluster_1_test.go:785: Can not add stream, unexpected error: goroutine 6, context deadline exceeded
    jetstream_cluster_1_test.go:785: Can not add stream, unexpected error: goroutine 4, context deadline exceeded
    jetstream_cluster_1_test.go:785: Can not add stream, unexpected error: goroutine 1, context deadline exceeded
    jetstream_cluster_1_test.go:785: Can not add stream, unexpected error: goroutine 2, context deadline exceeded
    jetstream_cluster_1_test.go:785: Can not add stream, unexpected error: goroutine 3, context deadline exceeded
    jetstream_cluster_1_test.go:809: Can not publish message, unexpected error: nats: timeout
--- FAIL: TestJetStreamParallelConsumerCreation (20.74s)
```

if you change variable `numParallel = 1` (https://github.com/nats-io/nats-server/compare/main...omnilight:nats-server:multiple_parallel_consumers_problem#diff-c7ea4877e0bb3c57935948893945e9daa480c0b1e5988c57533c3c7086baa914R763), then test will pass

If you run `CreateStream` consistently, then test will pass also.

#### Expected result:

CreateStream operation should be idempotent and should be allowed to run in parallel

#### Actual result:

Test fails

**Comment by derekcollison** [comment]
We have a bunch of tests for this on our test suite, so I am fairly confident this works.

**Comment by derekcollison** [comment]
But will take a look at your test.

**Comment by omnilight** [comment]
Thanks a lot. I've found tests for concurrent adding different streams or concurrent adding subscriptions, but did not find a test for concurrent creation of the same stream

**Comment by derekcollison** [comment]
Will take a look..

**Comment by derekcollison** [comment]
ok I recreated this, thanks for the example!

I actually think this might be pointing to something that we have been chasing in some customer deployments. Not the timeout but something else, so thanks again!

Will work on a fix today.

**Comment by omnilight** [comment]
Thank you, Derek, we are waiting for a fix too!

**Comment by derekcollison** [comment]
I believe the fix for your test would be straightforward but I am looking deeply at the meta state.

**Comment by derekcollison** [comment]
This will be in nightly this evening and part of 2.9.9 release which will probably be this week..
