### ISSUE TITLE
Key value store access degrades with many consumers doing updates

### ISSUE THREAD

**Issue by halamah** [nats-io/nats-server#3693]
Hi,

This is not a real case, but some edge case to highlight the issue.

I have several threads:
* Thread 1 - Publish events: Create unique bucket, publish 300 events in a loop and try to get value out of this unique bucket with Key `A` within each loop iteration. Since this is always a new bucket the value doesn't exist in that bucket.
* Threads 2 - N - Consume events and optimistic update another value `B` of the same bucket Process 1 created.

So the issue is - the more threads I create (Thread 2 - N) the longer time required to get value from the same bucket in Thread 1 (Key `A` which is not updated or accessed by another threads).

For example:
* 1 thread to publish + 1 thread to consume - total time about 4 seconds for entire loop with 300 calls to `Bucket.Get(A)` + `PublishAsync`.
* 1 thread to publish + 4 threads to consume - total time about 10 seconds for loop with 300 calls to `Bucket.Update(B)`+ `PublishAsync`.

Publish time is almost the same, so the `Bucket.Get(A)` time only increased in Thread 1.

Why do you think performance degrades so significantly? CPU load is about 30%.

**Comment by derekcollison** [comment]
Could you share a gist with the actual code for the test?

**Comment by derekcollison** [comment]
Any updates to share?

Also what server version?
