### ISSUE TITLE
Message delivery/available based on time to consumers

### ISSUE THREAD

**Issue by brindasanth** [nats-io/nats-server#3705]
## Feature Request
Message delivery based on time to consumers

#### Use Case:
Consumer should re-consume the same message with certain time interval and n retries due to business exceptions in the consumer side. Consume shall take control, at what time this message will be consumed.

**Comment by derekcollison** [comment]
NATS JetStream consumers have the ability to signal they need more time and they also can NAK with a delay. The progress indicator adds in another ack wait time period. The NAK with delay will not redelivery the message to any other consumer until delay expires.

**Comment by brindasanth** [comment]
Thanks for the response.That may work with NAK workarounds. I wish If we have time based message availability feature in NATS will add more value and more decentralized scheduler based use cases around the super power NATS.

**Comment by derekcollison** [comment]
We get an overwhelming number of feature requests these days. We have heard this one mentioned but rarely and not by any current customers. And no one wants to sponsor the work to change the priority.
