### ISSUE TITLE
communication cross leadnodes

### ISSUE THREAD

**Issue by carr123** [nats-io/nats-server#3720]
## Feature Request
I have a nats-cluster A, and leadnode B1, B2 .  B1 and B2 are all connecting to A, but B1 and B2 are not within the same cluster(or they don't see each other).
a message is sent on topic T from B1,  an subscriber is waiting on topic T from B2. i want B2 can receive that message

#### Use Case:
cross leadnodes communication

#### Who Benefits From The Change(s)?
everyone

**Comment by derekcollison** [comment]
That works today as long as B1 and B2 have unique names/cluster names (other wise cluster A will suppress) and both B1 and B2 bind to the same account in cluster A.

**Comment by carr123** [comment]
thanks. it really works.
