### ISSUE TITLE
 jetstream+mirror + leaf mirror data lag

### ISSUE THREAD

**Issue by chenchunping** [nats-io/nats-server#3724]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included `nats-server -DV` output
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)
<img width="836" alt="image" src="https://user-images.githubusercontent.com/29721558/208663013-cf8ca4d9-9ef8-4459-b8c5-3768bec02d6f.png">

#### Steps or code to reproduce the issue:
Center [bench_test] streaminfo:
{"Created":"2022-12-20T10:42:20.139642819Z","name":"bench_test","subjects":["bench.test"],"retention":"limits","max_consumers":-1,"max_msgs":-1,"max_bytes":-1,"max_age":0,"max_msgs_per_subject":-1,"max_msg_size":-1,"discard":"old","storage":"file","num_replicas":2,"duplicate_window":120000000000,"allow_direct":false,"mirror_direct":false,"sealed":false,"deny_delete":false,"deny_purge":false,"allow_rollup_hdrs":false}

hengli [ _mirror_bench_test_center]  streaminfo:
{"Created":"2022-12-20T11:22:20.939848124Z","name":"_mirror_bench_test_center","retention":"limits","max_consumers":-1,"max_msgs":-1,"max_bytes":-1,"max_age":0,"max_msgs_per_subject":-1,"max_msg_size":-1,"discard":"old","storage":"file","num_replicas":2,"mirror":{"name":"bench_test","external":{"api":"$JS.centerAcct.hengli.API","deliver":"deliver.centerAcct.hengli"}},"allow_direct":false,"mirror_direct":false,"sealed":false,"deny_delete":false,"deny_purge":false,"allow_rollup_hdrs":false}

hengli [_cosumer_hengli_bench_test] consumer info 
{"Created":"2022-12-20T11:22:20.941090889Z","Name":"_cosumer_hengli_bench_test","durable_name":"_cosumer_hengli_bench_test","deliver_policy":"all","ack_policy":"explicit","ack_wait":10000000000,"max_deliver":-1,"replay_policy":"instant","max_ack_pending":20000,"deliver_subject":"_recv_hengli.bench.test","num_replicas":0}

Referenced https://github.com/nats-io/jetstream-leaf-nodes-demo
#### Expected result:
mirror normal usage
 
#### Actual result:

When I use bench_test with js, I find that this problem occurs when the msgSize is large

![image](https://user-images.githubusercontent.com/29721558/208662170-da5c1cea-d6d5-4baa-9770-81dc1ee8d928.png)

**Comment by chenchunping** [comment]
When I restart and data can't recover， 
nats --server nats://center:center@127.0.0.1:14222 bench bench.test --js --stream=bench_test  --pub 1 --msgs 100 --size=1024 --pubsleep=0s
[msgs=100] success
[megs=10000] failed

**Comment by derekcollison** [comment]
The system will mirror the messages as fast as possible.

Are you stating the streams never settle to the same number?

Also best to use latest patched server, which is 2.9.10.

**Comment by chenchunping** [comment]
> 系统将尽快镜像消息。
> 
> 您是说流永远不会稳定到相同的数字吗？
> 
> 也最好使用最新的补丁服务器，即 2.9.10。

When a part of the mirror to the local will not mirror the data again, unless the restart server will re-mirror part of the data (not all data)

**Comment by derekcollison** [comment]
Could you try to recreate with the latest server 2.9.10?

**Comment by chenchunping** [comment]
> Could you try to recreate with the latest server 2.9.10?

The problem still exists after pulling the code of 2.9.10, the sub side can no longer consume the data after consuming 1877 pieces of data
recreate streaminfo
hengli streaminfo [bench_test2]
{"Created":"2022-12-21T02:53:34.582934Z","name":"bench_test2","subjects":["bench.test2"],"retention":"limits","max_consumers":-1,"max_msgs":-1,"max_bytes":-1,"max_age":0,"max_msgs_per_subject":-1,"max_msg_size":-1,"discard":"old","storage":"file","num_replicas":1,"duplicate_window":120000000000,"allow_direct":false,"mirror_direct":false,"sealed":false,"deny_delete":false,"deny_purge":false,"allow_rollup_hdrs":false}
wsw streaminfo [_mirror_bench_test2_hengli]
{"Created":"2022-12-21T02:53:28.301348Z","name":"_mirror_bench_test2_hengli","retention":"limits","max_consumers":-1,"max_msgs":-1,"max_bytes":-1,"max_age":0,"max_msgs_per_subject":-1,"max_msg_size":-1,"discard":"old","storage":"file","num_replicas":1,"mirror":{"name":"bench_test2","external":{"api":"$JS.hengliAcct.wsw.API","deliver":"deliver.hengliAcct.wsw"}},"allow_direct":false,"mirror_direct":true,"sealed":false,"deny_delete":false,"deny_purge":false,"allow_rollup_hdrs":false}
wsw consumerinfo [_cosumer_hengli_bench_test2]
{"Created":"2022-12-21T02:53:28.302543Z","Name":"_cosumer_hengli_bench_test2","durable_name":"_cosumer_hengli_bench_test2","name":"_cosumer_hengli_bench_test2","deliver_policy":"all","ack_policy":"explicit","ack_wait":10000000000,"max_deliver":-1,"replay_policy":"instant","max_ack_pending":1000,"deliver_subject":"_recv_hengli.bench.test2","num_replicas":0}

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/29721558/208810285-1204f94d-6fe4-43fa-8cdb-2e7d432a2760.png">

**Comment by chenchunping** [comment]
> > Could you try to recreate with the latest server 2.9.10?
> 
> The problem still exists after pulling the code of 2.9.10, the sub side can no longer consume the data after consuming 1877 pieces of data recreate streaminfo hengli streaminfo [bench_test2] {"Created":"2022-12-21T02:53:34.582934Z","name":"bench_test2","subjects":["bench.test2"],"retention":"limits","max_consumers":-1,"max_msgs":-1,"max_bytes":-1,"max_age":0,"max_msgs_per_subject":-1,"max_msg_size":-1,"discard":"old","storage":"file","num_replicas":1,"duplicate_window":120000000000,"allow_direct":false,"mirror_direct":false,"sealed":false,"deny_delete":false,"deny_purge":false,"allow_rollup_hdrs":false} wsw streaminfo [_mirror_bench_test2_hengli] {"Created":"2022-12-21T02:53:28.301348Z","name":"_mirror_bench_test2_hengli","retention":"limits","max_consumers":-1,"max_msgs":-1,"max_bytes":-1,"max_age":0,"max_msgs_per_subject":-1,"max_msg_size":-1,"discard":"old","storage":"file","num_replicas":1,"mirror":{"name":"bench_test2","external":{"api":"$JS.hengliAcct.wsw.API","deliver":"deliver.hengliAcct.wsw"}},"allow_direct":false,"mirror_direct":true,"sealed":false,"deny_delete":false,"deny_purge":false,"allow_rollup_hdrs":false} wsw consumerinfo [_cosumer_hengli_bench_test2] {"Created":"2022-12-21T02:53:28.302543Z","Name":"_cosumer_hengli_bench_test2","durable_name":"_cosumer_hengli_bench_test2","name":"_cosumer_hengli_bench_test2","deliver_policy":"all","ack_policy":"explicit","ack_wait":10000000000,"max_deliver":-1,"replay_policy":"instant","max_ack_pending":1000,"deliver_subject":"_recv_hengli.bench.test2","num_replicas":0}
> 
> <img alt="image" width="1032" src="https://user-images.githubusercontent.com/29721558/208810285-1204f94d-6fe4-43fa-8cdb-2e7d432a2760.png">

In my reboot will pull some of the mirrored data and then stop mirroring

<img width="1467" alt="image" src="https://user-images.githubusercontent.com/29721558/208811917-ae2a9fe3-4114-433c-ab16-71034510e438.png">

**Comment by bruth** [comment]
Hi @chenchunping. I attempted to recreate this setup here and I am not observing any lag: https://nats-by-example-pyl9888lb-connecteverything.vercel.app/examples/issues/3724/cli

If you don't mind reading through and let me know if there are any differences (other than maybe names). Below the code is the output of the script running. I created a hub cluster and leaf cluster.. an R2 stream in the hub, an R1 mirror in the hub, followed by an R1 mirror of the hub mirror. The message size is 10k on the bench command with 10k messages flowing in the stream.

**Comment by chenchunping** [comment]
> Hi @chenchunping. I attempted to recreate this setup here and I am not observing any lag: https://nats-by-example-pyl9888lb-connecteverything.vercel.app/examples/issues/3724/cli
> 
> If you don't mind reading through and let me know if there are any differences (other than maybe names). Below the code is the output of the script running. I created a hub cluster and leaf cluster.. an R2 stream in the hub, an R1 mirror in the hub, followed by an R1 mirror of the hub mirror. The message size is 10k on the bench command with 10k messages flowing in the stream.

the linked  Unable to open https://nats-by-example-pyl9888lb-connecteverything.vercel.app/examples/issues/3724/cli

Can you paste your configuration?

**Comment by bruth** [comment]
https://github.com/ConnectEverything/nats-by-example/pull/78/files#diff-1f492de864258b0a187023cc7fadcd9118e61c4c520a74cf2934ae2d35c1b3c1

**Comment by chenchunping** [comment]
> https://github.com/ConnectEverything/nats-by-example/pull/78/files#diff-1f492de864258b0a187023cc7fadcd9118e61c4c520a74cf2934ae2d35c1b3c1

Thank you very much for your help and providing new ideas, but since our scenario is complex and involves jetstream shared across accounts

**Comment by bruth** [comment]
> involves jetstream shared across accounts

Can you expand on this so I can update to make it closer to your setup? Based on the diagram and screenshot, the two streams (origin and mirror) appear to be under the same account (`center`) since these are being listed together. The leaf connection is using the `center` account (in my example, i called it `APP`). And then the stream in that leaf cluster is mirroring the one in center.

**Comment by derekcollison** [comment]
Any updates here?

**Comment by chenchunping** [comment]
> Any updates here?

Very sorry, I just saw the email

I rewired the bug locally on nats 2.9.10

this is my configuration:


============nats config==============
a_1.conf
```conf

cluster : {
  name : hengli
  port : 15333
  routes : [nats-router://127.0.0.1:15333,nats-router://127.0.0.1:15334,nats-router://127.0.0.1:15335]
}
http_port : 18222
jetstream : {
  domain : hengli
  store_dir : /Users/edencpchen/Documents/UGit/databus/oneos/pkg/databus/storage/jetstream/hengli_1
}
leafnodes : {
  port : 14333
  remotes : [{
    account : hengli
    urls : [nats-leaf://_hengliConnUser_:_hengliConnUser_@127.0.0.1:24333,nats-leaf://_hengliConnUser_:_hengliConnUser_@127.0.0.1:24334,nats-leaf://_hengliConnUser_:_hengliConnUser_@127.0.0.1:24335]
  }]
}
port : 14222
server_name : hengli_1

accounts:{
  hengli:{
    jetstream: enabled
    users:[
      {user: _hengliConnUser_, password: _hengliConnUser_}
      {user: hengli, password: hengli, permissions: {
        publish:{
          allow:["hengli.to.wsw.test","$JS.API.>"]
        },
        subscribe:{
          allow:["$JS.ACK.hengli_to_wsw_test.>","_INBOX.>"]
        }
      }}
    ]
  }
}
```

===================
a_2.conf

```conf

cluster : {
  name : hengli
  port : 15334
  routes : [nats-router://127.0.0.1:15333,nats-router://127.0.0.1:15334,nats-router://127.0.0.1:15335]
}
http_port : 18223
jetstream : {
  domain : hengli
  store_dir : /Users/edencpchen/Documents/UGit/databus/oneos/pkg/databus/storage/jetstream/hengli_2
}
leafnodes : {
  port : 14334
  remotes : [{
    account : hengli
    urls : [nats-leaf://_hengliConnUser_:_hengliConnUser_@127.0.0.1:24333,nats-leaf://_hengliConnUser_:_hengliConnUser_@127.0.0.1:24334,nats-leaf://_hengliConnUser_:_hengliConnUser_@127.0.0.1:24335]
  }]
}
port : 14223
server_name : hengli_2

accounts:{
  hengli:{
    jetstream: enabled
    users:[
      {user: _hengliConnUser_, password: _hengliConnUser_},
      {user: hengli, password: hengli, permissions: {
        publish:{
          allow:["hengli.to.wsw.test","$JS.API.>"]
        },
        subscribe:{
          allow:["$JS.ACK.hengli_to_wsw_test.>","_INBOX.>"]
        }
      }}
    ]
  }
}
```

====================
a_3.conf

```conf

cluster : {
  name : hengli
  port : 15335
  routes : [nats-router://127.0.0.1:15333,nats-router://127.0.0.1:15334,nats-router://127.0.0.1:15335]
}
http_port : 18224
jetstream : {
  domain : hengli
  store_dir : /Users/edencpchen/Documents/UGit/databus/oneos/pkg/databus/storage/jetstream/hengli_3
}
leafnodes : {
  port : 14335
  remotes : [{
    account : hengli
    urls : [nats-leaf://_hengliConnUser_:_hengliConnUser_@127.0.0.1:24333,nats-leaf://_hengliConnUser_:_hengliConnUser_@127.0.0.1:24334,nats-leaf://_hengliConnUser_:_hengliConnUser_@127.0.0.1:24335]
  }]
}
port : 14224
server_name : hengli_3

accounts:{
  hengli:{
    jetstream: enabled
    users:[
      {user: _hengliConnUser_, password: _hengliConnUser_},
      {user: hengli, password: hengli, permissions: {
        publish:{
          allow:["hengli.to.wsw.test","$JS.API.>"]
        },
        subscribe:{
          allow:["$JS.ACK.hengli_to_wsw_test.>","_INBOX.>"]
        }
      }}
    ]
  }
}
```

==================
b_1.conf
```conf

cluster : {
  name : wsw
  port : 25333
  routes : [nats-router://127.0.0.1:25333,nats-router://127.0.0.1:25334,nats-router://127.0.0.1:25335]
}
jetstream : {
  domain : wsw
  store_dir : /Users/edencpchen/Documents/UGit/databus/oneos/pkg/databus/storage/jetstream/wsw_1
}
leafnodes : {
  port : 24333
}
port : 24222
server_name : wsw_1

accounts:{
  hengli:{
    jetstream: enabled
    users:[
      {user: _hengliConnUser_, password: _hengliConnUser_}
    ]
    exports:[
      {service: "$JS.hengli.API.>", response: stream},
      {stream: "deliver.hengli.wsw.>", accounts: ["wsw"]}
    ]
  },
  wsw:{
    jetstream: enabled
    users:[
      {user: _wswConnUser_, password: _wswConnUser_},
      {user: wsw, password: wsw, permissions: {
        publish:{
          allow:["$JS.ACK.hengli_to_wsw_test.>"]
        },
        subscribe:{
          allow:["_recv_wsw.hengli.to.wsw.test"]
        }
      }}
    ]
    imports:[
      {service:{account:"hengli", subject: "$JS.hengli.API.>"}, to: "$JS.hengli.wsw.API.>"},
      {stream:{account:"hengli", subject:"deliver.hengli.wsw.>"}}
    ]
  }
}

```

=======================
b_2.conf

```conf

cluster : {
  name : wsw
  port : 25334
  routes : [nats-router://127.0.0.1:25333,nats-router://127.0.0.1:25334,nats-router://127.0.0.1:25335]
}
jetstream : {
  domain : wsw
  store_dir : /Users/edencpchen/Documents/UGit/databus/oneos/pkg/databus/storage/jetstream/wsw_2
}
leafnodes : {
  port : 24334
}
port : 24223
server_name : wsw_2

accounts:{
  hengli:{
    jetstream: enabled
    users:[
      {user: _hengliConnUser_, password: _hengliConnUser_}
    ]
    exports:[
      {service: "$JS.hengli.API.>", response: stream},
      {stream: "deliver.hengli.wsw.>", accounts: ["wsw"]}
    ]
  },
  wsw:{
    jetstream: enabled
    users:[
      {user: _wswConnUser_, password: _wswConnUser_},
      {user: wsw, password: wsw, permissions: {
        publish:{
          allow:["$JS.ACK.hengli_to_wsw_test.>"]
        },
        subscribe:{
          allow:["_recv_wsw.hengli.to.wsw.test"]
        }
      }}
    ]
    imports:[
      {service:{account:"hengli", subject: "$JS.hengli.API.>"}, to: "$JS.hengli.wsw.API.>"},
      {stream:{account:"hengli", subject:"deliver.hengli.wsw.>"}}
    ]
  }
}

```

======================
b_3.conf

```conf


cluster : {
  name : wsw
  port : 25335
  routes : [nats-router://127.0.0.1:25333,nats-router://127.0.0.1:25334,nats-router://127.0.0.1:25335]
}
jetstream : {
  domain : wsw
  store_dir : /Users/edencpchen/Documents/UGit/databus/oneos/pkg/databus/storage/jetstream/wsw_3
}
leafnodes : {
  port : 24335
}
port : 24224
server_name : wsw_3

accounts:{
  hengli:{
    jetstream: enabled
    users:[
      {user: _hengliConnUser_, password: _hengliConnUser_}
    ]
    exports:[
      {service: "$JS.hengli.API.>", response: stream},
      {stream: "deliver.hengli.wsw.>", accounts: ["wsw"]}
    ]
  },
  wsw:{
    jetstream: enabled
    users:[
      {user: _wswConnUser_, password: _wswConnUser_},
      {user: wsw, password: wsw, permissions: {
        publish:{
          allow:["$JS.ACK.hengli_to_wsw_test.>"]
        },
        subscribe:{
          allow:["_recv_wsw.hengli.to.wsw.test"]
        }
      }}
    ]
    imports:[
      {service:{account:"hengli", subject: "$JS.hengli.API.>"}, to: "$JS.hengli.wsw.API.>"},
      {stream:{account:"hengli", subject:"deliver.hengli.wsw.>"}}
    ]
  }
}
```

===========jetstream configuration============
leafnode jetstream config
```json
{"Created":"2023-01-02T15:42:43.088361Z","name":"hengli_to_wsw_test","subjects":["hengli.to.wsw.test"],"retention":"limits","max_consumers":-1,"max_msgs":-1,"max_bytes":-1,"max_age":0,"max_msgs_per_subject":-1,"max_msg_size":-1,"discard":"old","storage":"file","num_replicas":2,"duplicate_window":120000000000,"allow_direct":false,"mirror_direct":false,"sealed":false,"deny_delete":false,"deny_purge":false,"allow_rollup_hdrs":false}
```

leafserver jetstream config
```json
{"Created":"2023-01-02T15:42:59.206394Z","name":"_mirror_hengli_to_wsw_test_hengli","retention":"limits","max_consumers":-1,"max_msgs":-1,"max_bytes":-1,"max_age":3600000000000,"max_msgs_per_subject":-1,"max_msg_size":-1,"discard":"old","storage":"file","num_replicas":2,"mirror":{"name":"hengli_to_wsw_test","external":{"api":"$JS.hengli.wsw.API","deliver":"deliver.hengli.wsw"}},"allow_direct":false,"mirror_direct":true,"sealed":false,"deny_delete":false,"deny_purge":false,"allow_rollup_hdrs":false}
```
leafserver jetstream's consumer config
```json
{"Created":"2023-01-02T15:42:59.208921Z","Name":"_cosumer_wsw_hengli_to_wsw_test","durable_name":"_cosumer_wsw_hengli_to_wsw_test","name":"_cosumer_wsw_hengli_to_wsw_test","deliver_policy":"all","ack_policy":"explicit","ack_wait":10000000000,"max_deliver":-1,"replay_policy":"instant","max_ack_pending":1000,"deliver_subject":"_recv_wsw.hengli.to.wsw.test","num_replicas":0}
```

================Testing process====================

step01: Separate runs nats-server
step02: use nats bench publish data
step03: lookup data


================Testing result====================
<img width="1595" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/29721558/210254963-f819662d-e77e-46c5-a54c-5d1e394559c1.png">


================Other notes====================
1.Mirroring is normal when the data volume is small, and stops when the data volume is large
2.If I restart wsw-serve into it, it will pull some of the data from the mirror source again, but not all of it

**Comment by bruth** [comment]
Thank you @chenchunping for the full configs. We nailed down the issue and it is a specific export and import that is required to ensure proper flow control between the mirror and the origins stream.

In the `hengli` account for the `b` nodes you need to add this to the `exports` list:

```
{service: "$JS.FC.>"}
```

and corresponding import for the `wsw` account:

```
{service: {account: "hengli", subject: "$JS.FC.>"}}
```

This subject allows the mirror to send requests back to the origin stream to indicate appropriate flow control adjustments. Without it, the origin sent the first batch but did not receive any flow control info back from the mirror since it was blocked.

Here is the updated [example](https://nats-by-example-1rudkil1z-connecteverything.vercel.app/examples/issues/3724/cli) with your configs and the corresponding [output](https://nats-by-example-1rudkil1z-connecteverything.vercel.app/examples/issues/3724/cli#output). The final two commands executed print the stream report for the origin and mirror and you can see the 120k messages are both present.

**Comment by chenchunping** [comment]
Thank you very much for your help, I tested this issue locally and it passed @bruth

**Comment by bruth** [comment]
Wonderful, thanks for pushing on this example. I am going to add this as a note in the documentation.

**Comment by chenchunping** [comment]
> Wonderful, thanks for pushing on this example. I am going to add this as a note in the documentation.

I also need to ask, in our configuration there will be multiple clusters to the same cluster aggregated data, there will be a node will exist more than one flow control data import, the configuration is as follows, but this is not allowed, how should I operate it?
<img width="504" alt="image" src="https://user-images.githubusercontent.com/29721558/221757902-149a556f-1aad-4b79-a8a8-c4d0c25c039f.png">

======== ener2 config============
```conf
cluster: {
  name: ener2
  port: 5333
  routes: [nats-router://192.168.11.136:5333,nats-router://192.168.12.25:5333]
}
jetstream: {
  domain: ener2
  store_dir: /app/data/databus.js
}
leafnodes: {
  port: 4333
}
log_file: /app/data/nats.log
logtime: true
port: 4222
server_name: ener2_2

accounts: {
  inner: {
    jetstream: enabled
    users: [
      {user: inner, password: inner}
    ]
  },
  $SYS: {
    users: [
      {user: admin, password: admin}
    ]
  },
  ener1: {
    jetstream: enabled
    users: [
      {user: _ener1ConnUser_, password: _ener1ConnUser_},
    ]
    exports: [
      {stream: "_test_.ener1.to.ener2.nomal", accounts: ["ener2"]},
      {service: "$JS.ener1.API.>", response: stream},
      {stream: "deliver.ener1.ener2.>", accounts: ["ener2"]},
      {service: "$JS.FC.>"}
    ]
    imports: [
      {service: {account: "ener2", subject: "_test_.ener1.to.ener2.rr"}}
    ]
  },
  ener3: {
    jetstream: enabled
    users: [
      {user: _ener3ConnUser_, password: _ener3ConnUser_},
    ]
    exports: [
      {stream: "_test_.ener3.to.ener2.nomal", accounts: ["ener2"]},
      {service: "$JS.ener3.API.>", response: stream},
      {stream: "deliver.ener3.ener2.>", accounts: ["ener2"]},
      {service: "$JS.FC.>"}
    ]
    imports: [
      {service: {account: "ener2", subject: "_test_.ener3.to.ener2.rr"}}
    ]
  },
  ener2: {
    jetstream: enabled
    users: [
      {user: _ener2ConnUser_, password: _ener2ConnUser_},
      {
        user: ener2User, password: ener2User, permissions: {
        publish: {
          allow: ["$JS.ACK._mirror__test__ener1_to_ener2_js_ener1._cosumer_ener2User__test__ener1_to_ener2_js.*.*.*.*.*", "_R_.>", "_test_.ener2.to.ener1.nomal", "_test_.ener2.to.ener1.js", "$JS.API.>", "_test_.ener2.to.ener1.rr", "_test_.ener2.to.ener3.nomal", "_test_.ener2.to.ener3.js", "_test_.ener2.to.ener3.rr", "$JS.ACK._mirror__test__ener3_to_ener2_js_ener3._cosumer_ener2User__test__ener3_to_ener2_js.*.*.*.*.*"]
        },
        subscribe: {
          allow: ["_test_.ener1.to.ener2.nomal", "_recv_ener2User._test_.ener1.to.ener2.js", "_test_.ener1.to.ener2.rr", "_INBOX.>", "_test_.ener3.to.ener2.nomal", "_recv_ener2User._test_.ener3.to.ener2.js", "_test_.ener3.to.ener2.rr"]
        }
      }
      }
    ]
    exports: [
      {service: "_test_.ener1.to.ener2.rr", accounts: ["ener1"]},
      {service: "_test_.ener3.to.ener2.rr", accounts: ["ener3"]}
    ]
    imports: [
      {stream: {account: "ener1", subject: "_test_.ener1.to.ener2.nomal"}},
      {service: {account: "ener1", subject: "$JS.ener1.API.>"}, to: "$JS.ener1.ener2.API.>"},
      {stream: {account: "ener1", subject: "deliver.ener1.ener2.>"}},
      {service: {account: "ener1", subject: "$JS.FC.>"}},
      {stream: {account: "ener3", subject: "_test_.ener3.to.ener2.nomal"}},
      {service: {account: "ener3", subject: "$JS.ener3.API.>"}, to: "$JS.ener3.ener2.API.>"},
      {stream: {account: "ener3", subject: "deliver.ener3.ener2.>"}},
      {service: {account: "ener3", subject: "$JS.FC.>"}}
    ]
  }
}

```
