### ISSUE TITLE
Allow messages to merge for a performance boost

### ISSUE THREAD

**Issue by Doslin** [nats-io/nats-server#3732]
#### Proposed Change:
nats-stream msg msg size can be increased to 200MB
#### Who Benefits From The Change(s)?
stream reading and writing speed

#### Alternative Approaches

There are too many files under this stream
![image](https://user-images.githubusercontent.com/29807388/208887186-4f5d0c8d-44aa-4bae-a1e1-a65ceb8701e0.png)

**Comment by derekcollison** [comment]
We plan to do some work here but note that the block size is what is an atomic unit currently that is loaded all or nothing into a server when a message needs to be read by the server.

So for the way the upper constructs work with the filestore that would not be a good result for a system that was even slightly multi-tenant, or for a large KV where gets are not necessarily concentrated at the tail / last msg block.
