### ISSUE TITLE
nats-server hangs for 30 minutes

### ISSUE THREAD

**Issue by Doslin** [nats-io/nats-server#3736]
My JetStream is configured with 1.3TB max
But now it's full, and it's stored 500W messages,
When I tried to send messages to the pub, there was insufficient resources. jetStream.PublishAsync cause error nats: timeout

Then I changed the maximum number of messages to 100W by `nn str edit zhilin_stream --max-msgs=1000000`,  
but nats-server could not do any JetStream pub or Consumer pull for the next 30 minutes

**Comment by derekcollison** [comment]
What does 500W mean?

What does `nats stream info` report for that stream?
What does `nats account info` report?

What does `nats server ls` report? (This has to be executed as a system user)

**Comment by Doslin** [comment]
这是复现的步骤
1. 启动配置中的最大大小配置（jetstream.max_file）足够低
2. JetStream 配置很大的  Maximum Messages(--max-msgs)

当这个JetStream 占用的磁盘达到了 启动配置中的大小的时候，任何的 pub 和 sub 命令都会 timeout,
此时我去更改这个 JetStream后，nats-server 会挂 30 分钟

This is the repeat step
1. The maximum size configuration (jetstream.max_file) in the startup configuration is low enough
2. JetStream configures large Maximum Messages(--max-msgs)

Any pub and sub commands will timeout when the JetStream disk size in the startup configuration is reached.
After I change this JetStream, nats-server will hang up for 30 minutes

**Comment by Doslin** [comment]
> What does 500W mean?
> 
 the stream has stored over 5000000 msgs
> What does `nats stream info` report for that stream? What does `nats account info` report?

  command timeout，response error
> What does `nats server ls` report? (This has to be executed as a system user)

command timeout，response error

**Comment by derekcollison** [comment]
What do the server logs say? I assume it shutdown JetStream since it ran out of resources..

**Comment by lovuikeng** [comment]
you might want to set TTL to your stream too, having a few millions messages in stream at any point in time sounds alarming

**Comment by derekcollison** [comment]
Will close the issue but feel free to reopen if needed.
