### ISSUE TITLE
default tiered limits

### ISSUE THREAD

**Issue by aricart** [nats-io/nats-server#3746]
## Feature Request

Currently, if a server has global limits, when creating a stream, with no `num_replicas` set, it will default to 1.
If tiered limits are enabled, the configuration has an R1, and nothing is specified, the server will return an error `no jetstream default or applicable tiered limit present` 

#### Proposed Change:

This is indirectly enforcing that the client should pick the replication, but perhaps the server should just simply pick the lowest replication allowed by the account.

Alternatively - the server should simply request that `num_replicas` be set when it doesn't have a global limit, as this would better describe the current intention of having the user specify the type of replication desired.

**Comment by jmordica** [comment]
Perfection!

**Comment by Jarema** [comment]
It's because the tier name is created before defaults are applied.
Because of that - it looks for `R0`.

I think the path of least surprise would be to default `num_replicas` to `1`, so it's consistent with defaults applied a little later.

**Comment by Jarema** [comment]
@aricart I think #3748 is enough for this issue to close it?

**Comment by aricart** [comment]
@Jarema yes I think at least the error will make more sense if the limit is not available.
