### ISSUE TITLE
Set nats severid over config

### ISSUE THREAD

**Issue by suikast42** [nats-io/nats-server#3749]
I am using https://github.com/nats-io/prometheus-nats-exporter for exporting metrics to prometheus with           "-use_internal_server_id" option. This works so far so good. but if I restart the nats server evrytime a new serverId is genererated and that makes the monitoring little confusing. 

Is it posbilble to set the server ID like the server name or does this breaks something with clustering?

**Comment by derekcollison** [comment]
ServerIDs are meant to be unique and one time use. 

ServerName should be stable across restarts.

**Comment by suikast42** [comment]
I feared that was the case 😜.  I think the reight way is to solve in that corner https://github.com/nats-io/prometheus-nats-exporter right?

**Comment by wallyqs** [comment]
@suikast42 that's right, we need to add an option flag for the exporter to support this.

**Comment by suikast42** [comment]
Ok I close this isue here. I have push a pull piull request for this. 

https://github.com/nats-io/prometheus-nats-exporter/pull/197
