### ISSUE TITLE
Duplicates on Jetstream work queue using push consumers

### ISSUE THREAD

**Issue by juan131** [nats-io/nats-server#3758]
## Context

I have a NATS cluster with 3 replicas & JetStream enabled running on a K8s cluster. Please find below the version & configuration:

- NATS servers version: v2.9.9
- NATS servers exposed using a K8s service in the `default` namespace, so clients can reach them using the URL `nats://nats.default.svc.cluster.local:4222`
- NATS servers configuration (where `NATS_SERVER_NAME` env. var is different on each server):

```
server_name: $NATS_SERVER_NAME
listen: 0.0.0.0:4222
http: 0.0.0.0:8222

# Logging options
debug: false
trace: false
logtime: false

# Pid file
pid_file: "/tmp/nats-server.pid"

# Some system overrides
max_connections: 1000
max_payload: 65536

# Clustering definition
cluster {
  name: "nats"
  listen: 0.0.0.0:6222
  routes = [
    nats://nats:6222
  ]
}

# JetStream configuration
jetstream: enabled
jetstream {
  store_dir: /data/jetstream
  max_memory_store: 1G
  max_file_store: 5G
}
```

I have also created a stream using the piece of code below (golang):

```go
jsc.AddStream(
	&nats.StreamConfig{
		Name: "delivery-queue",
		Subjects: []{"foo"},
		Replicas: 3,
		Discard: nats.DiscardNew,
		Retention: nats.WorkQueuePolicy,
		Storage: nats.FileStorage,
                 Duplicates: time.Hour,
		MaxAge: time.Hour,
		MaxMsgSize: 1024,
	},
)
```

The stream was successfully created:

```console
$ nats stream info delivery-queue
Information for Stream delivery-queue created 2023-01-03 12:34:56

             Subjects: foo
             Replicas: 3
              Storage: File

Options:

            Retention: WorkQueue
     Acknowledgements: true
       Discard Policy: New
     Duplicate Window: 1h0m0s
    Allows Msg Delete: true
         Allows Purge: true
       Allows Rollups: false

Limits:

     Maximum Messages: unlimited
  Maximum Per Subject: unlimited
        Maximum Bytes: unlimited
          Maximum Age: 1h0m0s
 Maximum Message Size: 1.0 KiB
    Maximum Consumers: unlimited

Cluster Information:

                 Name: nats
               Leader: nats-1
              Replica: nats-0, current, seen 0.37s ago
              Replica: nats-2, current, seen 0.37s ago
```

Then, I have one worker pod that writes ~1M messages on the stream in a synchronous way & I confirm that messages are successfully published:

```go
if _, err := js.Publish("foo", message); err != nil {
	return err
}
```

> IMPORTANT: **messages include a "code id" and each code id is unique.**

Finally, I have a deployment with N replicas consuming these messages in parallel. Each replica creates a channel subscription with M goroutines using the same push consumer. Here's the code I use:

```go
const maxAckPending int = 50000
(...)

msgsChannel := make(chan *nats.Msg, maxAckPending)
sub, err := jsc.ChanQueueSubscribe(
	"foo",
	"foo-workers",
	msgsChannel,
	nats.BindStream("delivery-queue"),
	nats.ManualAck(),
	nats.MaxAckPending(maxAckPending),
)
(...)

for i := 0; i < 50; i++ {
	go func() {
		for msg := range msgsChannel {
			processMsg(msg)
		}
	}()
}
(...)

func processMsg(natsMsg *nats.Msg) {
	(...)
	// LOGIC TO DETECT DUPLICATES HERE
	(...)
	if err := natsMsg.AckSync(); err != nil {
		(...)
		return
	}
}
```

Consumer info:

```consoler
$ nats consumer info delivery-queue foo-workers
Configuration:

                Name: foo-workers
    Delivery Subject: _INBOX.6Tad7UmMOYfIgHouEHXfcm
      Filter Subject: foo
      Deliver Policy: All
 Deliver Queue Group: foo-workers
          Ack Policy: Explicit
            Ack Wait: 30s
       Replay Policy: Instant
     Max Ack Pending: 50,000
        Flow Control: false

Cluster Information:

                Name: nats
              Leader: nats-1
             Replica: nats-0, current, seen 0.24s ago
             Replica: nats-2, current, seen 0.24s ago
```

### Issue

The worker pod that writes messages in the queue faster than consumers process them, after a while, there are around half a million messages in the stream:

```console
$ nats stream ls
╭─────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                             Streams                                             │
├──────────────────────────┬─────────────┬─────────────────────┬──────────┬────────┬──────────────┤
│ Name                     │ Description │ Created             │ Messages │ Size   │ Last Message │
├──────────────────────────┼─────────────┼─────────────────────┼──────────┼────────┼──────────────┤
│ delivery-queue           │             │ 2023-01-03 12:34:56 │ 373,378  │ 44 MiB │ 0.32s        │
```

Little by little, the consumer pods process the messages in the queue until it's empty. **However, the logic I implemented to detect duplicates (which is based in caching in a Redis instance every processed code id) is throwing me a lot of warnings alerting me that a message that was already processed is being processed again.**

### Extra data

- `processMsg()` takes ~1 sec to process each message.
- The "duplicates warnings" appear after a while (when pods have been processing messages for a couple of minutes approx.)
- The issue appears regardless the N (number of replicas) used (even with 1 replica).
- The issue appears regardless the M (number of goroutines) used.
- Golang client library: `github.com/nats-io/nats.go v1.19.0`
- The client library throws several `nats: slow consumer, messages dropped` errors.

**Comment by juan131** [comment]
Thanks so much for your reply @Jarema !! 

You're right, there was a typo in the snippet and `maxAckPending` is actually 50K. I'll give a try setting lower values until the `nats: slow consumer, messages dropped` errors disappear and retry my tests.

One question: `max_ack_pending` is unique per consumer, right? I mean, once I create the consumer for the 1s time I can't dynamically adapt it if I add more replicas (which means also more subscriptions to the same consumer), right?

**Comment by juan131** [comment]
Would it make sense to set `max_ack_pending` to `M*N` (where M is the number of goroutines per subscription & N the number of replicas)?

**Comment by Jarema** [comment]
Happy that it helped!

Yes, MaxAckPending is per-consumer instance.
You can tweak it as you suggested, but probably some sensible default will be fine for whatever number of replicas range you have. I would start with that at least, for simplicity.

**Comment by juan131** [comment]
Great, thanks so much for your help @Jarema . I'll start with `max_ack_pending` equal to `M` and later on I'll try to increase taking into account the number of replicas until I find the balance where no "slow consumers" errors appear while obtaining as much throughput as possible

Please consider this issue solved.
