### ISSUE TITLE
NATS storage problem

### ISSUE THREAD

**Issue by bautistamad** [nats-io/nats-server#3766]
Hi, I am using the Interest policy of nats in kubernetes with 3 replicas, and I have the following problem:
What is indicated in the stream is not what is actually stored on disk, the disk has much more capacity, I do not know if it is because the delated messages are stored, and the problem I have now is that I am filling the storage very quickly without knowing why.
![image](https://user-images.githubusercontent.com/75149705/210838775-a10e1436-1cb4-487f-a188-be52b91f29ae.png)

![image](https://user-images.githubusercontent.com/75149705/210839477-d5395509-f883-40f8-a4a2-e3b575208976.png)

this is the storage of one of my discs, all 3 replicas are the same:
![image](https://user-images.githubusercontent.com/75149705/210839636-d82fa88d-ed23-491e-a42c-ee8e07c61cfa.png)

The nats is deployed with helm, using the following version: 0.18.1.
nats-server version: 2.9.3
Each replica has its own PV with a storage of 10gb for each one. To allocate each volume we use longhorn, so the directory where it is stored is /var/lib/longhorn.

**Comment by bautistamad** [comment]
I will try to get the storage tree, I have already raised the issue, thank you very much.

**Comment by derekcollison** [comment]
Might be good to upgrade server to 2.9.10.

**Comment by derekcollison** [comment]
Can you send us a `tree -h` of the storage directory as specified by the server during startup?

Thanks.

**Comment by bautistamad** [comment]
This is three inside of PVC:

[tree.txt](https://github.com/nats-io/nats-server/files/10361401/tree.txt)

**Comment by derekcollison** [comment]
ok what does `nats stream ls -a` show?

**Comment by derekcollison** [comment]
The stream `sm` looks to be taking up most of the space.

**Comment by derekcollison** [comment]
What does `nats stream info sm` show?

**Comment by derekcollison** [comment]
Lots of interior deletes. If you are running latest server version we should compact those to some degree. We will be increasing compaction in 2.10, but if you run 2.9.10 server should improve.

**Comment by bautistamad** [comment]
Perfect, is there any place in the documentation where I can see better the compacting?
Regarding the compacting, once it reaches a certain point those messages are stored as I understand it.
We are going to upgrade to that version to see if it improves.

**Comment by derekcollison** [comment]
No docs since internal behavior that could change from release to release, but we are committed to making the compaction much better. It is a bit conservative right now but should help improve your situation hopefully. Keep us posted.

**Comment by bautistamad** [comment]
Keep you informed, close the issue or keep it open? Thanks for all.

**Comment by derekcollison** [comment]
Will keep open for now, and update us once the server is upgrade. 2.9.11 is the latest.

**Comment by bruth** [comment]
@bautistamad Closing this since this problem should have been solved as of 2.10 (which was released October 2023).
