### ISSUE TITLE
Cannot find an active JetStream from the list

### ISSUE THREAD

**Issue by Doslin** [nats-io/nats-server#3767]
![image](https://user-images.githubusercontent.com/29807388/210986390-28447a64-6559-442f-8ab9-4492f18f594c.png)
![image](https://user-images.githubusercontent.com/29807388/210987618-5db2b4ae-5c57-45dd-8419-ebacb69ce75b.png)

![image](https://user-images.githubusercontent.com/29807388/210988106-5a75271a-5f3c-4185-a89c-a6a25211730a.png)

**Comment by derekcollison** [comment]
What does `nats server report jetstream` show? Must be a system user for that request.
What does `nats account info` show from the user account?

**Comment by derekcollison** [comment]
Also what server version?

**Comment by Doslin** [comment]
nats server report jetstream
![image](https://user-images.githubusercontent.com/29807388/211200998-65bcc25f-c505-4c13-9c32-384bbe301f0f.png)
nats account info
![image](https://user-images.githubusercontent.com/29807388/211201063-ff45bced-3d3f-4fdb-967e-2276df4f011e.png)

![image](https://user-images.githubusercontent.com/29807388/211201035-cb64c842-74e3-4b66-be17-d03cf253fdd0.png)

nats-server version 
nats-server-v2.9.8-linux-amd64.zip

**Comment by derekcollison** [comment]
Upgrade to latest server and see if the stream is visible.

It is in the account your nats cli context is bound to correct?

**Comment by Doslin** [comment]
> Upgrade to latest server and see if the stream is visible.
> 
> It is in the account your nats cli context is bound to correct?

[root@nats001 install_dir]# nsys server info
Server information for nats006.xx.cn (NCQVRNPAXMKUEF7YX2Y52OENMX3N5HG6H46F7DXOBXM3ELH7JS7NWRL4)

Process Details:

         Version: 2.9.11
      Git Commit: 23ffc16
      Go Version: go1.19.4
      Start Time: 2023-01-12 02:49:15.090616084 +0000 UTC
          Uptime: 55m2s

Connection Details:

   Auth Required: true
    TLS Required: false
            Host: 0.0.0.0:4222
     Client URLs: 

JetStream:

              Domain: 
   Storage Directory: /data/jetstream
          Max Memory: 40 GiB
            Max File: 1.3 TiB
      Active Acconts: 1
       Memory In Use: 0 B
         File In Use: 0 B
        API Requests: 12
          API Errors: 1

Limits:

        Max Conn: 65536
        Max Subs: 0
     Max Payload: 1.0 MiB
     TLS Timeout: 2s
  Write Deadline: 10s

Statistics:

       CPU Cores: 8 0.00%
          Memory: 25 MiB
     Connections: 0
   Subscriptions: 436
            Msgs: 50,193 in 29,553 out
           Bytes: 2.8 MiB in 2.3 MiB out
  Slow Consumers: 0

Cluster:

            Name: nats
            Host: 0.0.0.0:6222
            URLs: nats006.xx.cn:6222
                  nats005.xx.cn:6222
                  nats004.xx.cn:6222
                  nats003.xx.cn:6222
                  nats002.xx.cn:6222
                  nats001.xx.cn:6222
[root@nats001 install_dir]# nn str info
? Select a Stream stream_03
Information for Stream stream_03 created 2023-01-06 18:09:41

             Subjects: out_test_feed_3
             Replicas: 3
              Storage: File

Options:

            Retention: Limits
     Acknowledgements: true
       Discard Policy: Old
     Duplicate Window: 2m0s
    Allows Msg Delete: true
         Allows Purge: true
       Allows Rollups: true

Limits:

     Maximum Messages: 3,000,000
  Maximum Per Subject: unlimited
        Maximum Bytes: unlimited
          Maximum Age: 12h0m0s
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited


Cluster Information:

                 Name: nats
               Leader: nats006.xx.cn
              Replica: nats003.xx.cn, outdated, not seen, 1 operation behind
              Replica: nats004.xx.cn, current, seen 0.89s ago

State:

             Messages: 0
                Bytes: 0 B
             FirstSeq: 0
              LastSeq: 0
     Active Consumers: 0

![image](https://user-images.githubusercontent.com/29807388/212040157-e5dcc458-bed2-4076-b73b-649c7491119d.png)
![image](https://user-images.githubusercontent.com/29807388/212040448-d1cea771-a4c4-4f45-a2dc-ad17191f4e71.png)

![image](https://user-images.githubusercontent.com/29807388/212039784-73f829c9-25f2-41e3-b1fc-d921f2339322.png)

![image](https://user-images.githubusercontent.com/29807388/212041414-94cdc35c-5a61-417e-875c-be31ab390f97.png)

**Comment by derekcollison** [comment]
Anything in the logs on startup about not being able to recover the stream?

**Comment by Doslin** [comment]
> ok thanks for upgrading. Seems the one stream is still not visible though correct?
> 
> What does `/healthz` report for each server?
![image](https://user-images.githubusercontent.com/29807388/212247429-bca853ce-ddd9-498c-9cf7-50c6538ea654.png)

**Comment by derekcollison** [comment]
Ok check the server logs on that server. Should have more info on why it can not recover the stream.

**Comment by Doslin** [comment]
> Ok check the server logs on that server. Should have more info on why it can not recover the stream.

At the beginning there were only three nodes, nats001, nats002, nats003, and only one jetstream, zhilin_03
Later I added nats004, nats005, nats006, and at the same time, I created stream003, a jetstream
Then I closed stream003 and reset the OS of nats004, nats005 and nats006.

The latest time I created stream003 again, this is what happened

**Comment by derekcollison** [comment]
Did you instruct the system to remove nats004, nats005 and nats006? If not the JetStream meta layer will still believe they are part of the group.

With the latest nats cli, what does `nats server report jetstream` show?

Use peer-remove to remove the servers that were once part of the system but are now removed and will not be coming back.

```
nats server raft peer-remove -h                                                                   ✔
usage: nats server raft peer-remove [<flags>] <name>

Removes a server from a JetStream cluster

Args:
  <name>  The Server Name or ID to remove from the JetStream cluster

Flags:
  -f, --force  Force removal without prompting
```

**Comment by Doslin** [comment]
> Did you instruct the system to remove nats004, nats005 and nats006? If not the JetStream meta layer will still believe they are part of the group.
> 
> With the latest nats cli, what does `nats server report jetstream` show?
> 
> Use peer-remove to remove the servers that were once part of the system but are now removed and will not be coming back.
> 
> ```
> nats server raft peer-remove -h                                                                   ✔
> usage: nats server raft peer-remove [<flags>] <name>
> 
> Removes a server from a JetStream cluster
> 
> Args:
>   <name>  The Server Name or ID to remove from the JetStream cluster
> 
> Flags:
>   -f, --force  Force removal without prompting
> ```

the `nats server report jetstream show` is 
![image](https://user-images.githubusercontent.com/29807388/212880301-4d3144d2-2595-49c1-a6df-c5f8dbcb1785.png)

so now that this has happened, I can only rebuild the whole cluster?

**Comment by derekcollison** [comment]
Can you grab the development version? Top of main branch and run the same command?

Will report if the system has peers that are offline.

And just to verify, you are running server version 2.9.11 yes?

**Comment by Doslin** [comment]
> Can you grab the development version? Top of main branch and run the same command?
> 
> Will report if the system has peers that are offline.
> 
> And just to verify, you are running server version 2.9.11 yes?

Yes, I am using 2.9.11
Why use the development version? Did you optimize it?

**Comment by derekcollison** [comment]
Top of main for the NATS cli.

**Comment by Doslin** [comment]
> Top of main for the NATS cli.

Yeah, I finally solved the problem.
When I used Top of main for the natscli, I found two jetstreams with the same name.
1. I removed one of the jetstreams
2. shut down the problematic machine with `nats-server --signal ldm` and `nats server raft peer-remove` commands.

**Comment by Doslin** [comment]
> Top of main for the NATS cli.

In addition, I would like to know what are the reasons for this problem?

**Comment by derekcollison** [comment]
Remove the peer from the stream possibly. 

With assets created from older versions of the system, the raft state could become corrupt.

You can reset these with 2.9.11 server by scaling to 1 and then back up to the desired replica count.

**Comment by Doslin** [comment]
> Remove the peer from the stream possibly.
> 
> With assets created from older versions of the system, the raft state could become corrupt.
> 
> You can reset these with 2.9.11 server by scaling to 1 and then back up to the desired replica count.

But when nats003 is down, no command from natscli is responding.
And I don't know which jetstreams are running on nats003, and I don't know which jetstreams need to be scaled down
In particular, the nats server raft peer-remove nats003 is not working properly. In this case, I can't do any repair unless I start nats003
![image](https://user-images.githubusercontent.com/29807388/215371560-ea3c0996-c569-46a2-8667-5e412b53bb6b.png)

**Comment by derekcollison** [comment]
That means you accidentally expanded the meta layer beyond the three peers, since when it is down you only have 2 peers, which if the set is 3 would be fine, but I would imagine it is 4 or greater and therefore can not get quorum and so the meta layer can not elect a leader.

**Comment by derekcollison** [comment]
This has nothing to do with that, you just accidentally (I believe) expanded your cluster size and the JetStream meta layer is remembering, so it needs 3 servers to all be active (meaning it thinks there are 4 or 5 members of the total peer set).

**Comment by Doslin** [comment]
> This has nothing to do with that, you just accidentally (I believe) expanded your cluster size and the JetStream meta layer is remembering, so it needs 3 servers to all be active (meaning it thinks there are 4 or 5 members of the total peer set).

My cluster has always been 6 machines with two jetstreams. i was simulating the problem with any one of the nodes going offline for a long time.

Now I'm running nsys server report jetstream with `WARNING: No cluster meta leader found. requires at least 4 upnodes
`, will the cluster succeed in pushing out the leader without my intervention?

**Comment by derekcollison** [comment]
No you will need to intervene and remove the peers, the system does not automatically remove peers.
