### ISSUE TITLE
Regular KV watch error when 1 server is down in a 3 servers cluster

### ISSUE THREAD

**Issue by albinou** [nats-io/nats-server#3791]
## Defect

With the following setup:

- cluster of 3 NATS servers
- a KV store created with "replicas=3" (when all servers are up)
- 1 of the 3 servers is going down

Every NATS operations works fine except the KV `watch` which sometimes produces the error `nats: error: context deadline exceeded` when 1 server is down.

Please find more details below:

- [x] `nats-server -DV` output (date of the servers is UTC and date the my client is CET so there is exactly 1 hour of delay between servers and client logs)

  1. [1st server logs](https://github.com/nats-io/nats-server/files/10447389/cluster-1-log.txt) (probably nothing to observe here)
  2. [2nd server logs](https://github.com/nats-io/nats-server/files/10447386/cluster-2-log.txt)  (the nats-cli connects to this server, look for the `Client connection created` line)
  3. [nats-cli logs](https://github.com/nats-io/nats-server/files/10447391/nats-cli-log.txt) (this output is the result of the command `strace -tt -f -e trace='%network' nats --trace --server nats://163.172.167.179:4222,nats://163.172.189.87:4222 --creds /path/to/the/file.creds kv watch mykv`)

 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

See section "Steps or code to reproduce the issue".

#### Versions of `nats-server` and affected client libraries used:

- nats-server version is v2.9.11
- nats-cli version is 0.0.35

#### OS/Container environment:

Ubuntu 20.04.5 LTS

#### Steps or code to reproduce the issue:

1. install a NATS cluster with 3 servers and create an account / user with JetStream enabled
2. create a KV with `replicas=3`: `nats kv add mykv --replicas=3`
3. put 2 keys/values: `nats kv put key1 value1` && `nats kv put key2 value2`
4. shutdown 1 of the 3 nats servers
5. run a watch: `nats kv watch mykv`

This last command fails sometimes with a `nats: error: context deadline exceeded`.
This error also happens even if `nats` is run with the `--server` option and a server that is up,

#### Expected result:

The `nats kv watch` should work because 2 servers are still up.
All other operations like `nats kv get` and `nats kv put` works very well.

#### Actual result:

Watching a KV sometimes fails with `nats: error: context deadline exceeded`.

Notes:

1. the issue is also reproduced with the nats.go Golang client.
2. after a `watch` failure, we can see some consumers that were not deleted when running `nats consumer ls KV_mykv`

**Comment by derekcollison** [comment]
Thanks for the report. Watchers will be creating a ephemeral R1 consumer under the covers and the meta layer may be selecting the downed server. 

How do you shutdown the server during testing?

**Comment by albinou** [comment]
Thanks for looking at my report.
I run my tests by shutting down the VM. But I just tested and the exact same problem occurs when shutting down the nats-server properly with a `systemctl stop nats-server.service`. The only difference is that logs show `[ERR] Error trying to connect to route (attempt 297): dial tcp 51.158.108.48:6222: connect: connection refused` instead of a connection timeout.

**Comment by derekcollison** [comment]
Can you share the systemd service definition you are using?

**Comment by albinou** [comment]
Oh sure.
As you can see, we are sending a SIGINT to stop the server.

```
[Unit]
Description=NATS Server
After=network.target ntp.service

[Service]
PrivateTmp=true
Type=simple
ExecStart=/usr/sbin/nats-server -c /etc/nats-server.conf
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/bin/kill -s SIGINT $MAINPID
User=nats
Group=nats
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
```

**Comment by derekcollison** [comment]
ok will take a deeper look.

When I start a 3 node cluster and ctrl-c one of the servers, as system user, `nats server report jetstream` will show that node immediately as offline. That should mean it will not be selected to be a target for a new consumer.

**Comment by albinou** [comment]
Thank you very much.
I just tested it with nats-server v2.9.14 and it works perfectly :smiley:
