### ISSUE TITLE
Allow RePublish stream option to be editable

### ISSUE THREAD

**Issue by amorey** [nats-io/nats-server#3803]
## Feature Request

Currently, NATS server doesn't allow clients to change the `RePublish` stream option after it has been defined. Allowing clients to remove/modify `RePublish` would allow users to disable republishing when it is no longer necessary and to make it easier to make modifications to the subject namespace over time.

In addition, it would be useful for the RePublish option to be a list so you can republish messages to multiple subjects.

#### Use Case:

The most immediate use cases are 1) disabling republishing when it is no longer necessary and 2) using the feature to make modifications to the subject namespace.

#### Proposed Change:

Allow the `RePublish` stream option to be editable.

#### Who Benefits From The Change(s)?

Users who want to disable RePublishing or change a destination subject.

#### Alternative Approaches

It should be possible to implement the same behavior by creating a new stream that uses the old stream as a source. Then once the streams are synced, you can set the desired `RePublish` option in the new stream and delete the old stream. To prevent data loss between deleting the old stream and subscribing the new stream to the old subjects, you can use subject mapping to redirect messages from the old stream to the new stream.

**Comment by derekcollison** [comment]
This is reasonable, @Jarema or @neilalexander could one of you take this on for 2.10?

**Comment by neilalexander** [comment]
Completed by #3811.

**Comment by ripienaar** [comment]
Will need a https://github.com/nats-io/nats-architecture-and-design/ issue for clients to support this

**Comment by amorey** [comment]
Wow! Very impressive turnaround! Thank you!! How difficult would it be to make the republish option available as a list?
