### ISSUE TITLE
Configure log timestamp as UTC

### ISSUE THREAD

**Issue by tbeets** [nats-io/nats-server#3826]
## Feature Request

Log timestamp can be enabled or disabled (default enabled), but timestamp is always in the host's currently configured timezone (e.g. PST).  The timezone is not recorded in the timestamp format.

Users would benefit from an option to log timestamp as UTC regardless of host's currently configured timezone.

#### Use Case:

Logs from multiple servers are scraped into a central log aggregator service where timezone normalization is needed or required.

#### Proposed Change:

Add a server configuration option (not default to preserve back compatibility) to always log timestamps (if enabled) as normalized UTC.

#### Who Benefits From The Change(s)?

Users who aggregate server logs from multiple hosts that may not always be uniformly configured as UTC timezone at host level.

#### Alternative Approaches

Output timestamp in format that preserves timezone information which could allow log aggregators to normalize downstream as required.

**Comment by wallyqs** [comment]
Fixed via #3833
