### ISSUE TITLE
Upgrade to NATS 2.9.14 logs consumer replica count errors

### ISSUE THREAD

**Issue by Kaarel** [nats-io/nats-server#3858]
Hi

We recently upgraded our NATS cluster from 2.9.10 to 2.9.14. Every node we upgraded logged the below errors:

```
[7180] 2023/02/07 08:39:41.415131 [ERR] consumer 'USERS > logs > ' MUST match replication (3 vs 0) of stream with interest policy
[7180] 2023/02/07 08:39:41.415134 [ERR] consumer 'USERS > logs > ' MUST match replication (3 vs 0) of stream with interest policy
```
and
```
[7180] 2023/02/07 08:39:42.856463 [WRN] RAFT [PCIUZRPn - C-R3F-KWx8T2ky] Wrong index, ae is &{leader:fMpQocsW term:332 commit:285538746 pterm:332 pindex:285538746 entries: 3}, index stored was 285538746, n.pindex is 285538746
[7180] 2023/02/07 08:39:42.856479 [WRN] RAFT [PCIUZRPn - C-R3F-KWx8T2ky] Error storing entry to WAL: raft: could not store entry to WAL
[7180] 2023/02/07 08:39:42.856505 [WRN] RAFT [PCIUZRPn - C-R3F-KWx8T2ky] Expected first catchup entry to be a snapshot and peerstate, will retry
[7180] 2023/02/07 08:39:45.668440 [WRN] RAFT [PCIUZRPn - C-R3F-nlSaHI6B] Wrong index, ae is &{leader:fMpQocsW term:310 commit:278795482 pterm:310 pindex:278795482 entries: 1}, index stored was 278795482, n.pindex is 278795482
[7180] 2023/02/07 08:39:45.668456 [WRN] RAFT [PCIUZRPn - C-R3F-nlSaHI6B] Error storing entry to WAL: raft: could not store entry to WAL
```

Not sure about the WRN messages but ERR seems to be related to this issue #3817 

We create streams and consumers with the dotnet client library. The stream builder code uses `.WithReplicas(3)` and consumer builder code does not call `.WithNumReplicas()` at all. The documentation of the method (https://github.com/nats-io/nats.net/blob/master/src/NATS.Client/JetStream/ConsumerConfiguration.cs#L725) suggests that when I don't set this value it will be implicitly inherited from the stream replica value.
> Sets the number of replicas for the consumer. When set do not inherit the replica count from the stream but specifically set it to this amount.

Clearly there seems to be a discrepancy somewhere in the pipeline. I'm just not sure where, the server or the client library.

`nats stream info logs`
```
Information for Stream logs created 2022-07-13 20:07:45

             Subjects: logs.>
             Replicas: 3
              Storage: File

Options:

            Retention: Interest
     Acknowledgements: true
       Discard Policy: Old
     Duplicate Window: 2m0s
    Allows Msg Delete: true
         Allows Purge: true
       Allows Rollups: false

Limits:

     Maximum Messages: unlimited
  Maximum Per Subject: unlimited
        Maximum Bytes: 1.0 GiB
          Maximum Age: 5d0h0m0s
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited


Cluster Information:

                 Name: nats-cluster
               Leader: n1
              Replica: n3, current, seen 0.15s ago
              Replica: n2, current, seen 0.15s ago

State:

             Messages: 0
                Bytes: 0 B
             FirstSeq: 240,381,314
              LastSeq: 240,381,313 @ 2023-02-09T08:21:49 UTC
     Active Consumers: 2
```

`nats consumer info logs c1`
```
Information for Consumer logs > c1 created 2022-12-02T14:34:46Z

Configuration:

        Durable Name: c1
    Delivery Subject: c1.logs
      Deliver Policy: All
 Deliver Queue Group: c1
          Ack Policy: Explicit
            Ack Wait: 30s
       Replay Policy: Instant
     Max Ack Pending: 1,000
        Flow Control: false

Cluster Information:

                Name: nats-cluster
              Leader: n1
             Replica: n3, current, seen 0.50s ago
             Replica: n2, current, seen 0.50s ago

State:

   Last Delivered Message: Consumer sequence: 240,309,679 Stream sequence: 240,381,475 Last delivery: 0.51s ago
     Acknowledgment floor: Consumer sequence: 240,309,679 Stream sequence: 240,381,475 Last Ack: 0.51s ago
         Outstanding Acks: 0 out of maximum 1,000
     Redelivered Messages: 0
     Unprocessed Messages: 0
          Active Interest: Active using Queue Group c1
```

We have a bunch of streams and consumers and microservices configured like that. What's the recommended approach to remedy this situation. Should there be any worry for us at the moment?

**Comment by theoilie** [comment]
I'm running into the same issue on v2.9.14 where logs get spammed with errors like:
```
[WRN] RAFT [hfKDr6Kx - S-R3F-9scDg7AZ] Wrong index, ae is &{leader:yIUmpQsm term:40 commit:674 pterm:40 pindex:674 entries: 1}, index stored was 674, n.pindex is 674
[WRN] RAFT [hfKDr6Kx - S-R3F-9scDg7AZ] Error storing entry to WAL: raft: could not store entry to WAL
[WRN] RAFT [hfKDr6Kx - S-R3F-9scDg7AZ] Expected first catchup entry to be a snapshot and peerstate, will retry
[WRN] RAFT [hfKDr6Kx - S-R3F-uvkx5XJe] Expected first catchup entry to be a snapshot and peerstate, will retry
[WRN] RAFT [hfKDr6Kx - S-R3F-RR7SrSxP] Expected first catchup entry to be a snapshot and peerstate, will retry
[WRN] RAFT [hfKDr6Kx - S-R3F-78KkE6BB] Expected first catchup entry to be a snapshot and peerstate, will retry
[WRN] RAFT [hfKDr6Kx - S-R3F-FHN4YWHa] Expected first catchup entry to be a snapshot and peerstate, will retry
[WRN] RAFT [hfKDr6Kx - S-R3F-lWqTaUzT] Expected first catchup entry to be a snapshot and peerstate, will retry
[WRN] RAFT [hfKDr6Kx - S-R3F-EW5Pnzwj] Wrong index, ae is &{leader:hfKDr6Kx term:59 commit:231 pterm:57 pindex:231 entries: 1}, index stored was 231, n.pindex is 231
[WRN] RAFT [hfKDr6Kx - S-R3F-EW5Pnzwj] Error storing entry to WAL: raft: could not store entry to WAL
WRN] RAFT [hfKDr6Kx - S-R3F-EW5Pnzwj] Expected first catchup entry to be a snapshot and peerstate, will retry
```

This happened after accidentally changing nats StoreDir on 3 of the 12 nodes. After setting the StoreDir back, I expected all nodes to self-heal. However, they all showed these errors. After stopping all 3 broken nodes and deleting their StoreDir, 2 of the 3 broken nodes were stopped showing errors. This third node, however keeps showing these errors no matter how many times I stop, delete the directories, and then restart. I first tried deleting specific stream files (e.g., `/nats/clusterName/jetstream/$SYS/_js_/S-R3F-9scDg7AZ` and after that failed tried just deleting the whole cluster directory (e.g., `/nats/clusterName`) to no avail.

**Comment by derekcollison** [comment]
This bug is fixed in top of main and will be released with 2.9.15. Its is also part of nightly builds from the dev branch.

You should not have to go in and remove directories underneath of NATS in general. If a consensus layer becomes inconsistent one trick to try is to scale the stream, and hence its consumers, down to 1 and back to the old R value.

This can be done with the nats cli tool.

`nats str <str-name> update --replicas=1`

**Comment by Kaarel** [comment]
Can report that with 2.9.15 I haven't seen these messages!

But ran into a different issue when scaling stream R value as described here https://github.com/nats-io/nats-server/issues/3953

**Comment by bruth** [comment]
Closing as this issue is resolved.
