### ISSUE TITLE
nats subject mapping does not work with jetstream

### ISSUE THREAD

**Issue by tamalsaha** [nats-io/nats-server#3868]
## Feature Request
I am trying to use NATS subject mapping where the dest subjects are used to create a jetstream. If I send request to the source subjects, I get `nats: no responders available for request` .

I would expect the jetstream to be able to ACK to the request even when subject mapping is used.

**Comment by ripienaar** [comment]
I use them with JS so best you show us some configs and code

**Comment by tamalsaha** [comment]
I followed the steps below using nats-server v2.9.14 .

```
nats-server -m 8222 -js
```

```
nats server mapping "ghactions.runs.*.*" "ghactions.machines.{{wildcard(1)}}.{{partition(3,2)}}"
```

```
> nats str create
? Stream Name ghactions
? Subjects ghactions.machines.*.*
? Storage file
? Replication 1
? Retention Policy Work Queue
? Discard Policy Old
? Stream Messages Limit -1
? Per Subject Messages Limit -1
? Total Stream Size -1
? Message TTL -1
? Max Message Size -1
? Duplicate tracking time window 2m0s
? Allow message Roll-ups No
? Allow message deletion Yes
? Allow purging subjects or the entire stream Yes
Stream ghactions was created
```

```
> nats request ghactions.runs.queued.1 "I need help!"

07:45:26 Sending request on "ghactions.runs.queued.1"
07:45:26 No responders are available
```

You can see the error `No responders are available`

**Comment by tamalsaha** [comment]
Related issue: https://github.com/nats-io/natscli/issues/703

**Comment by jnmoyne** [comment]
`nats server mapping` does not actually define and set a mapping on your existing running nats-serve(s), it's there only to test mappings.

With Core NATS you define the subject mappings either directly in the server configuration file, or (if you are using operator/JWT-based security) in the account JWT.

However it is most likely that the new/upcoming subject mapping transforms for streams is exactly what you are looking for. It has already been merged in the `dev` branch, and will be therefore included in the list of new features for NATS 2.10.
(see https://github.com/nats-io/nats-server/pull/3827)

**Comment by tamalsaha** [comment]
In that case `nats server mapping` should be `nats server test-mapping` so it is clear that this is just client side testing.

**Comment by jhaynie** [comment]
i just ran into this as well ... lol, spent about 10m until i finally came here and found this thread.
