### ISSUE TITLE
About Object store Experimental notice - is it safe to use?

### ISSUE THREAD

**Issue by OfirYemini** [nats-io/nats-server#3897]
Is the object store safe to use on production code. I ask because I've seen an **Experimental notice** note on the [docs](https://docs.nats.io/using-nats/developer/develop_jetstream/object). if not, when is it expected to be officially released?

**Comment by derekcollison** [comment]
You can use it now, we may change a few things from an API perspective but plan to be backward compatible with any assets stored.

/cc @aricart

**Comment by OfirYemini** [comment]
Thanks!
