### ISSUE TITLE
Datadog Integration

### ISSUE THREAD

**Issue by jared-mackey** [nats-io/nats-server#390]
Would be very nice to have a datadog integration if one does not exist already. (I couldn't find one)

Might be useful to have #351 for this.

**Comment by mcqueary** [comment]
See also #345 for Prometheus. We are interested in hearing if users strongly prefer one over the other.

**Comment by derekcollison** [comment]
Thanks will have someone from the team provide input. Again much appreciated!

/cc @nats-io/core

**Comment by wallyqs** [comment]
Thanks @irabinovitch we helped the team a bit when the PR was opened and just took another look left some comments (few typos and versions of the server that could be updated in the tests since there have been releases for both servers since then, list of metrics that are being tracked look good to me).

**Comment by OneCricketeer** [comment]
I think #1193 would go a long way towards getting better DD metric support

**Comment by derekcollison** [comment]
I believe we have a good approach with NATS 2.0 and the ability for a user on the system account to query for metrics from all servers. DD integration support should be pretty trivial at that point from a collection standpoint. Doing lots of k8s based POCs and having to setup http ports on every nats-server pod to have sidecar prometheus etc is painful.

**Comment by OneCricketeer** [comment]
> Doing lots of k8s based POCs and having to setup http ports on every nats-server pod to have sidecar prometheus etc is painful.

Right. Which is why I mentioned statsd

https://docs.datadoghq.com/developers/dogstatsd/?tab=hostagent

**Comment by derekcollison** [comment]
But then we have to run a dogstatsd on every nats-server pod correct?

**Comment by OneCricketeer** [comment]
Personally, I opt for for a SystemD service on the host.

**Comment by derekcollison** [comment]
Us being able to use NATS to poll all servers and then put metrics directly into datadog is nice. As long as you have good distributed health checks and are not relying on DD for health strictly.

**Comment by OneCricketeer** [comment]
> good distributed health checks and are not relying on DD for health strictly.

Consul, Nagios, or Zabbix 👍🏼

**Comment by derekcollison** [comment]
Closing for now but feel free to re-open as needed.
