### ISSUE TITLE
Recommended way of managing Streams creation and jetstream management ? 

### ISSUE THREAD

**Issue by andronachev** [nats-io/nats-server#3935]
Hello,

We just implemented the first message exchange between our services using nats jetstream server.. We are not using anything fancy just publish subscribe. We use C#/.NET so I've been looking into the NATS.NET client and all the  example code provided for publish subscribe etc. 

In any case my question is related to Streams creation and when are they best to be created ? As I've seen in the example code from NATS.NET the Streams are created or updated, or created if not exist at runtime, before the **subject publishing and/or subscribing**. 

However to me this seems like a devops / server management concern to create the Streams themselves, it does not seem right for a Client to configure the server at run-time. After all a stream is configuring message retention, message storage and many more (from what I've seen). It also implies a performance penalty to make the http calls each time, which 99.999% of the times will be useless, only the very first one will have a point of creating the Stream. 

So my question is what is the 'official' alternative, should we just use the nats-cli provided, automate it in anyway we see fit, or do it manually etc.  

edit: is it not possible to simply specify a default "catch all" Stream in the nats-server.config file ( or jetstream config file ??), that would be a nice alternative for now. I have not seen that in the docs.

edit2: previously we were using the old version: nats-streaming with the stan client, and there we did not have this concern of needing a stream before publish/subscribe, it just 'worked' to publish and subscribe to different subjects, channels etc

Thank you!

**Comment by caleblloyd** [comment]
There are a few options for Streams and Durable Consumers.

**DevOps approaches**

- [nack](https://github.com/nats-io/nack) if using Kubernetes
- [terraform-provider-jetstream](https://github.com/nats-io/terraform-provider-jetstream) if using Terraform

**App approaches**

Use a client that has a JetStream management APIs implemented.

- Treat similar to running database migrations from the app perspective.  Run them at startup in a single app instance or in a startup job that runs when a deployment is performed.
