### ISSUE TITLE
Provide another way to reload the nats config 

### ISSUE THREAD

**Issue by jarretlavallee** [nats-io/nats-server#3950]
## Feature Request
Provide a way to reload the server configuration through `natscli` and an SYS account API. 

#### Use Case:

Reloading the configuration is currently done through a `SIGHUP` or service restart. This requires access to the service which adds additional complexity in certain deployments. In the [helm chart](https://github.com/nats-io/k8s/blob/main/helm/charts/nats/templates/statefulset.yaml#L216), this is accomplished by using a shared namespace process to be able to send the HUP. Using `shareProcessNamespace` is a violation in CIS Benchmark for EKS version 1.0.1. To be compliant, one would need to disable the NATS configuration reload sidecar and identify another process for reloading the configuration. 

Having a mechanism to reload the configuration outside of a HUP would enable additional configuration change patterns.

#### Proposed Change:

Use the robust authentication, authorization, and auditing scheme in nats to provide a mechanism for reloading the server configuration. One possibility is to add an API for the SYS account to reload the server configuration. e.g `$SYS.REQ.SERVER.<id>.RELOAD`

#### Who Benefits From The Change(s)?

Users who want to reload the nats server config remotely, or through an automated process without access to the service.

#### Alternative Approaches

Restart the nats server on configuration changes or file security exceptions.

**Comment by Bhogster** [comment]
Any updates on this?

**Comment by jarretlavallee** [comment]
This was implemented in #4307 and can be called with `nats server config reload` in natscli v0.1.0+.
