### ISSUE TITLE
cannot find 'nsc' in user path

### ISSUE THREAD

**Issue by randyf2022** [nats-io/nats-server#3951]
I'm relatively new to nats so please bear with me. I was following the steps in [this video](https://www.youtube.com/watch?v=5pQVjN0ym5w) (How to set up Decentralized Authentication/Authorization in NATS | Rethink Connectivity Episode 6).  The steps are outlined [here](https://github.com/ConnectEverything/rethink_connectivity_examples/tree/main/episode_6).

When I got to the step where I enter

    nats context save --nsc "nsc://myorg/SYS/sys" my_org_sys

I get

    nats: error: cannot find 'nsc' in user path

Am I missing something in my environment setup?  Here is the output of running 'nsc env':

+----------------------------------------------------------------------------------------------------------+
|                                             NSC Environment                                              |
+--------------------+-----+-------------------------------------------------------------------------------+
| Setting            | Set | Effective Value                                                               |
+--------------------+-----+-------------------------------------------------------------------------------+
| $NSC_CWD_ONLY      | No  | If set, default operator/account from cwd only                                |
| $NSC_NO_GIT_IGNORE | No  | If set, no .gitignore files written                                           |
| $NKEYS_PATH        | No  | ~/.local/share/nats/nsc/keys                                                  |
| $NSC_HOME          | No  | ~/.config/nats/nsc                                                            |
| $NATS_CA           | No  | If set, root CAs in the referenced file will be used for nats connections     |
|                    |     | If not set, will default to the system trust store                            |
| $NATS_KEY          | No  | If set, the tls key in the referenced file will be used for nats connections  |
| $NATS_CERT         | No  | If set, the tls cert in the referenced file will be used for nats connections |
+--------------------+-----+-------------------------------------------------------------------------------+
| From CWD           |     | No                                                                            |
| Default Stores Dir |     | ~/.local/share/nats/nsc/stores                                                |
| Current Store Dir  |     | ~/.local/share/nats/nsc/stores                                                |
| Current Operator   |     | my_org                                                                        |
| Current Account    |     | TEAM_B                                                                        |
| Root CAs to trust  |     | Default: System Trust Store                                                   |
+--------------------+-----+-------------------------------------------------------------------------------+

Sorry for "unformatted-ness" of the output.

Web searches have turned up fruitless. Any idea?

Thx!

**Comment by codegangsta** [comment]
Is the `nsc` binary in your user path? What is the output of `which nsc` and `which nats`?

**Comment by randyf2022** [comment]
@codegangsta, that was the issue. It dawned on me then I saw your response. BTW, your videos are very helpful. Thx, Jeremy!
