### ISSUE TITLE
Ability to view the  undelivered messages

### ISSUE THREAD

**Issue by AvinashVenkatesaiah** [nats-io/nats-server#3998]
We use nats jetstream and have set up streams and consumers with "all" as the acknowledgement policy . Do we have an ability to view the undelivered messages becuase of the all acknowledgement policy . Based on our understanding , an all ack policy acknowledges all the prior messages as a result of which the messages may not be delivered . Would want to know if there is a way we can view such messages using either the nats cli or sdks

**Comment by derekcollison** [comment]
Should you select ExplicitAck instead?

**Comment by AvinashVenkatesaiah** [comment]
Hello @derekcollison  : Our use case demands we use the all acknolowdgement policy

**Comment by derekcollison** [comment]
You can get stream sequence number details on the pending messages and view them with direct gets from the stream by stream sequence number.

**Comment by bruth** [comment]
@AvinashVenkatesaiah Per:
