### ISSUE TITLE
NATS Timeout error

### ISSUE THREAD

**Issue by archsyscall** [nats-io/nats-server#4023]
Hi, I’m having trouble getting NATS to work in kubernetes.
I am using Jetstream NATS for EKS via helm. The cluster has a total of 3 replicas floating around.

Normally there is no problem, but if I publish a lot of messages to Jetstream in a short period of time, it causes a problem.
The pods are fine when running, but when I use NATS commands like nats str ls, I get the error below.

```
nats: error: setup failed: dial tcp xxx.xxx.xxx.xxx:4222: i/o timeout
```
Also, I don’t know if it’s directly related, but I’m getting the following logs from the pod.

```
JetStream cluster no metadata leader
Error trying to connect to route (attempt 327): lookup for host "nats-2.nats.nats.svc.cluster.local": lookup nats-2.nats.nats.svc.cluster.local on 172.20.0.10:53: no such host
JetStream cluster stream '$G > factorial-worker-queue' has NO quorum, stalled
```
How can I resolve this issue?

subscriber error
```
JetStream system temporarily unavailable
```

+ An additional issue we found is that there is a timeout when making the initial connection for a Pub or Sub.

**Comment by derekcollison** [comment]
I would join our slack group and post this under the k8s channel.
