### ISSUE TITLE
Failed snapshot restore could cause health probe to error.

### ISSUE THREAD

**Issue by derekcollison** [nats-io/nats-server#4076]
The snapshot restore process could leave a directory if aborted that the health probe could mistake for an account it should be able to resolve.

**Comment by savion1024** [comment]
hi @derekcollison,  u can assign this issue to me，I'd love to try and fix this。thx~

**Comment by derekcollison** [comment]
I actually already fixed this one. Forgot to reference.

**Comment by derekcollison** [comment]
Fixed in e25f89dc4df4949915133b8b8e402dd69253df04

**Comment by savion1024** [comment]
OK～

**Comment by derekcollison** [comment]
Thanks for being willing to help out!!
