### ISSUE TITLE
I have a push mode consumer. When using js.UpdateConsumer, an error occurred with the error message: max waiting not to be updated. However, my consumer's original max waiting is 0. I tried not assigning a value or assigning a value of 0, but it still reported the same error

### ISSUE THREAD

**Issue by ouzhou0110** [nats-io/nats-server#4077]
I have a push mode consumer. When using js.UpdateConsumer, an error occurred with the error message: max waiting not to be updated. However, my consumer's original max waiting is 0. I tried not assigning a value or assigning a value of 0, but it still reported the same error

nats-server version: 2.9.15
![image](https://user-images.githubusercontent.com/26115784/233251798-cef1786d-34e1-4ee1-990e-1aada23fdb01.png)

**Comment by savion1024** [comment]
Is there any more information to add? eg err info。

**Comment by savion1024** [comment]
look at this #3302,
It appears that the modification is currently not supported.

**Comment by bruth** [comment]
Thanks @savion1024. That PR did correctly reject the update. Closing as resolved. @ouzhou0110 Feel free to reopen if there are any additional questions.
