### ISSUE TITLE
Only one consumer allowed when using filter_subjects

### ISSUE THREAD

**Issue by cjbottaro** [nats-io/nats-server#4081]
> [workqueue] retention type allows for a set of consumers that have non-overlapping interest on subjects. In other words, if multiple consumers are bound to a work-queue stream, they must have disjoint filter subjects.

```elixir
stream_create("project-1", retention: "workqueue", subjects: ["project-1.*"])

consumer_create("project-1", "consumer-1", filter_subjects: ["project-1.subject-1"])
consumer_create("project-1", "consumer-2", filter_subjects: ["project-1.subject-2"])
```

Results in an error...
```
"multiple non-filtered consumers not allowed on workqueue stream"
```

Thanks for the help.

**Comment by ripienaar** [comment]
Error suggests your filter_subjects isn’t being used at all. 

Please show output of nafs consumer info for one of these.

**Comment by cjbottaro** [comment]
I think a part of the problem is that I don't know how to make the request properly.

`nats schema info io.nats.jetstream.api.v1.consumer_create_request` doesn't show how to specify multiple subjects, so I'm just going off of #3500, which seems to add a `filter_subjects` option.

But you're right, if I create a consumer with that option, I don't see anything about it reflected in `nats consumer info`. Also, that option isn't available in the nats command line.

**Comment by ripienaar** [comment]
Oh sorry I see what’s happening now. 

This is a upcoming 2.10 feature. So you need nightly server and nightly nats command.

**Comment by cjbottaro** [comment]
Oofa, sorry, I thought the current server version was 2.15, but it's actually 2.9.15. Ugh, sorry for the noise.

Anyway, looking forward to this feature. Thank you!
