### ISSUE TITLE
[question] streams for multiple environments

### ISSUE THREAD

**Issue by SpareShade** [nats-io/nats-server#4089]
Hi,

We have a single stream eg. `integration` that subscribes to eg. `events.*`

We are trying to use a single NATS instance to serve `dev` and `stage` environment messages, where the streams for each env would be `integration_dev` and `integration_stage`, and each subscribing to the same subject  `events.*`. 

This of course fails with `subjects overlap with an existing stream`.

Is there any way to achieve this with single instance?

**Comment by derekcollison** [comment]
Have a dev account and a stage account, each one can have the exact same stream in them.

**Comment by SpareShade** [comment]
Thanks @derekcollison  will it a go

**Comment by derekcollison** [comment]
Think of accounts as the path to multi-tenancy. By default they are isolated, but you can explicitly and securely share information between accounts via exports and imports as well.
