### ISSUE TITLE
Filter the `$JS.API.STREAM.NAMES` response by the user's permissions.

### ISSUE THREAD

**Issue by oderwat** [nats-io/nats-server#4091]
## Feature Request

I would like to have `$JS.API.STREAM.NAMES` filtering the returned streams by the permissions of the user who is calling the endpoint.

#### Use Case:

When using NATS JetStream in public clients, we currently need to provide access to `$JS.API.STREAM.NAMES` for some of our packages so that the client can discover streams from subjects or get a list of streams that exists for this user.

#### Proposed Change:

I would propose to filter the answer of this endpoint by the list of permitted subjects from the pub/sub permissions of the user. So, the user will not be able to see streams that he can't publish or subscribe too.

#### Who Benefits From The Change(s)?

I think that this will be beneficial for everybody because it adds security by not letting every client that needs access to the streams get a full list of all the streams in the system.

#### Alternative Approaches

One could add permission for access to streams (instead of just the subjects) and make the same check for those.

**Comment by oderwat** [comment]
Is this still being considered for an earlier release?

**Comment by derekcollison** [comment]
Not at this time.
