### ISSUE TITLE
JetStream - exceeded number of outstanding acks for push consumer

### ISSUE THREAD

**Issue by JTancula** [nats-io/nats-server#4112]
Hi

I encountered an unexpected situation that causes non-delivery of messages to the application. I'm not sure if this is a bug, or lack of understanding of push consumers.

The stream configuration is as follows:
![image](https://user-images.githubusercontent.com/9408579/234907144-00db91c3-56b9-48c6-8937-65a995722d5a.png)

Then my applications uses following push consumer:
![image](https://user-images.githubusercontent.com/9408579/234913867-7f6d9b74-473b-433a-b5b2-f52e02b10109.png)

The problem is with the `Max Ack Pending` parameter. My understanding of it is that the stream will not send more messages to the consumer at once than is set in it. 
For a while the app was working as expected. The maximum number of messages processed at once was equal to the value of the  `Max Ack Pending` parameter. 
Then, as a result of an unknown action, the number of pending messages exceeded the maximum number allowed. Which caused the following situation:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/9408579/234913541-91ca087f-16ab-444d-a744-01bb2f4aa837.png)

Of course, these redundant messages did not reach the application. From that moment, the stream was not able to deliver new messages to the consumer and the app basicly switched to idle mode.

Firstly I tried to debug my app, but I was unabled to find any problems with message processing (average processing time of single msg around 300ms). 
Then I started experimenting with the NATS server restarts and downtimes. The only clue I've found is that after restarting server with many accumulated messages in the stream and with max ack pending reached for push consumer, the stream, instead of waiting for messages to process, can somtimes send a huge number of new messages at once. However, I am not able to reproduce it every time.

Can anyone explain the exceeding of the MaxAckPending value? If so, how can this be prevented?

**Comment by derekcollison** [comment]
What server version?

**Comment by JTancula** [comment]
2.9.16

**Comment by derekcollison** [comment]
It could be due to redelivery logic. Will take a look.

**Comment by jakubnoga** [comment]
Hi @derekcollison any news?

**Comment by derekcollison** [comment]
Does this happen on latest 2.9.21? 

Do you know that messages are hitting max redelivery?

**Comment by derekcollison** [comment]
This should fix, will be part of 2.9.22 scheduled for next week.

https://github.com/nats-io/nats-server/pull/4427
