### ISSUE TITLE
Wrong link in nats-server v2.9.10 release notes

### ISSUE THREAD

**Issue by daviddeasy** [nats-io/nats-server#4113]
The PR link for the health check change in v2.9.10 goes to the wrong PR.
> Monitoring
>    /healthz?js-enabled=true behavior now properly asserts whether JetStream is enabled if it is expected to be and does not check for health of the assets. (https://github.com/nats-io/nats-server/pull/3699)

This is the correct PR: https://github.com/nats-io/nats-server/pull/3704
though I found the issue link https://github.com/nats-io/nats-server/issues/3703 provides a clearer description of the health check options.

**Comment by bruth** [comment]
Thanks for the correction! Updated the release notes. The PR references #3703, so folks can visit that as well.
