### ISSUE TITLE
Unable to set `nsc` signing key permissions for reserved `$` subjects

### ISSUE THREAD

**Issue by AshleySchaeffer** [nats-io/nats-server#4125]
I'm trying to set an Account's signing key permissions to restrict the use of a KV store. I intend on having an Account (A) have a local KV store that has Users whom can only read the value (they should only be able to get and watch the value for changes). Another Account (B) would then permissions to change the value.

I've found another issue that I've taken inspiration from to formulate the following command to assign permissions to the signing key of Account A #3548:

```bash
nsc edit signing-key --sk <signing key> --allow-pub "\$JS.API.STREAM.INFO.foo" --allow-pub "\$KV.foo" --allow-pub "\$JS.API.DIRECT.GET.KV_foo.\$KV.foo"
```
`nsc` returns output stating it successfully applied the permissions, however they are not reflected in neither the TUI or JWT JSON output:

```json
{
 "iat": 1682971073,
 "iss": "<snip>",
 "jti": "<snip>",
 "name": "<snip>",
 "nats": {
  "authorization": {
   "auth_users": null
  },
  "default_permissions": {
   "pub": {},
   "sub": {}
  },
  "exports": [
   {
    "name": "an-export",
    "subject": "a-subject",
    "token_req": true,
    "type": "stream"
   },
   {
    "name": "another-export",
    "subject": "b-subject",
    "token_req": true,
    "type": "stream"
   }
  ],
  "limits": {
   "conn": -1,
   "consumer": -1,
   "data": -1,
   "disk_max_stream_bytes": -1,
   "exports": -1,
   "imports": -1,
   "leaf": -1,
   "max_ack_pending": -1,
   "mem_max_stream_bytes": -1,
   "payload": -1,
   "streams": -1,
   "subs": -1,
   "wildcards": true
  },
  "signing_keys": [
   {
    "key": "<snip>",
    "kind": "user_scope",
    "role": "app",
    "template": {
     "data": -1,
     "payload": -1,
     "pub": {
      "allow": [
       "a-subject",
       "b-subject"
       // I expected the subjects I just added to be here
      ]
     },
     "sub": {},
     "subs": -1
    }
   }
  ],
  "type": "account",
  "version": 2
 },
 "sub": "<snip>"
}
```

For completeness, should the above work, I intend on exporting a service to `$KV.foo` that I'm hoping will then allow me to set the key from Account B.

So I have one potential issue, and a follow-up question:

1. How do I set the permissions up the way I'd like given that they don't appear to be being applied by `nsc`?
2. Is there another approach to what I'm trying to achieve assuming that adding permissions for reserved subjects isn't possible?

Thanks for your time. I sort of hope this is an issue and not just me missing and then asking for help in the wrong way.

I'm using the latest `nats:scratch` image from Dockerhub.

**Comment by jnmoyne** [comment]
In version 2.10 you would be able to do this probably a little bit simpler because you will be able to source a KV bucket from another KV bucket so you don't have to use 2 accounts and do an export between them, you can use just one account and two KV buckets and two users, one bucket that the first user only can write/read to and another bucket that sources the first one and that the second one that the second user can read from (but not write to).

**Comment by AshleySchaeffer** [comment]
@jnmoyne that makes sense, but unfortunately I want the two accounts for other segregation. I might explore your idea though and see if I can get it to work in a different way.

**Comment by AshleySchaeffer** [comment]
@bruth @aricart @derekcollison sorry I probably should have raised this in the nsc repository. Do you want me to move it?

**Comment by AshleySchaeffer** [comment]
This is definitely a me a problem. Sorry for raising, I think I've messed up setting up the signing key.
