### ISSUE TITLE
Nats.go and nats Server alignment of release binaries

### ISSUE THREAD

**Issue by gedw99** [nats-io/nats-server#4134]
Don’t know if this has come up but is there a way to know that the version of client matches server and it’s passed the testing etc.

for me as the client is embedded in iot , gui and Server consumers so when I lamb duck the nats cluster to upgrade its a slight risk sone part of the functionality can break on the clients.

I was even thinking of a ci script that swaps the dependencies out and upgrades them and compiles  and run tests. like a matrix test .

 A side thing is that all clients upgrade and slip stream the new binary in place using a process fork. They are consumers of a nats object store . The client binaries ( with nats.go imported ) are pushed into nats server obj store whenever a ci release happens. 
 
I might put the update ops system in a different nats system completely to isolate but prefer not. Stretch it as far as possible 

So it’s all quite coupled using nats for everything …

**Comment by derekcollison** [comment]
The goal is to always support clients with new server releases. You can still run client programs from over a decade ago with current servers.

When we do a server release, this is a bound client version which was used for all of the CI/CD tests. You can see this in the `go.mod` file in the top of the server directory.
