### ISSUE TITLE
JetStreamkv space consumption

### ISSUE THREAD

**Issue by xjpch** [nats-io/nats-server#4160]
## Defect

I encountered a problem in the process of using kv, my English is not very good,I try to express。

I started the server with the command
nats-server -a localhost -p 4278  -V -js -sd . --auth xxx

The following is the information of kv。

Configuration:

          Bucket Name: dog
         History Kept: 10
        Values Stored: 10
   Backing Store Kind: JetStream
          Bucket Size: 4.7 KiB
  Maximum Bucket Size: unlimited
   Maximum Value Size: unlimited
     JetStream Stream: KV_dog
              Storage: File

The following is meta.inf in the server file directory.

{"Created":"2023-05-14T09:34:28.903615347Z","name":"KV_dog","subjects":["$KV.dog.\u003e"],"retention":"limits","max_consumers":-1,"max_msgs":-1,"max_bytes":-1,"max_age":7200000000000,"max_msgs_per_subject":10,"max_msg_size":-1,"discard":"new","storage":"file","num_replicas":1,"duplicate_window":120000000000,"allow_direct":true,"mirror_direct":false,"sealed":false,"deny_delete":true,"deny_purge":false,"allow_rollup_hdrs":true}

#### Versions of `nats-server` and affected client libraries used:
 Version:  2.9.16

#### OS/Container environment:
Linux version 5.4.0-110-generic (buildd@ubuntu) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)) #124-Ubuntu 

#### Steps or code to reproduce the issue:

I created a jetstream kv use rust's async-nats . 
 async-nats = "0.29.0"

 let store = self.jetstream.create_key_value(async_nats::jetstream::kv::Config {
                bucket: "dog".to_string(),
                history: 10,
                max_age: Duration::from_secs(60*60*2),
                ..Default::default()
            }).await?;

//Only read once when the program starts
let datas = store .get("dog").await?;

After I insert and update data through the following pseudo code

let entry = store.entry("dog").await?;
if entry. is_none() {
      entry.put("dog", xxx).await?;
} else {
     store.update("dog", xxx, entry.revision).await?;
}

Whenever I insert data 1.blk file gets bigger。

#### Expected result:

kv only stores the latest 10 pieces of data and expires after 2 hours.No additional huge space consumption

#### Actual result:

kv only stores the latest 10 pieces of data and expires after 2 hours. It's ok.
But the size of a 1.blk file in the msgs directory has been growing and has never been reduced. I don't know what this file is used for.

I checked that the document stream has a discard policy, but it seems that it cannot be configured when using the rust client. The default is stream::DiscardPolicy::New

/// When a Stream has reached its configured `max_bytes` or `max_msgs`, this policy kicks in.
     /// `DiscardPolicy::New` refuses new messages or `DiscardPolicy::Old` (default) deletes old messages to make space

 Hope to get help.

**Comment by ripienaar** [comment]
The blk files is where messages are stored, I think they should be around 8MB big for KV max.

Once all messages in a block is expired the block will be removed.  In future versions we should also compact them, for now they should not grow very big each blk file.

How big is yours?

**Comment by xjpch** [comment]
> The blk files is where messages are stored, I think they should be around 8MB big for KV max.
> 
> Once all messages in a block is expired the block will be removed. In future versions we should also compact them, for now they should not grow very big each blk file.
> 
> How big is yours?

Thank you for your answer.
not very big. Only 4m. Because I just started using this function today, I found that the file size has been increasing, but I couldn't find the document how to limit it, so I was a little worried. I looked at the file data and it seems like every update is being logged.
Even after two hours, it didn't get any smaller.
If it can be deleted normally after exceeding 8mb, then there is no problem.

The last small problem, when I use it, all messages will not expire, because I have been updating this key, I currently only use a key with a fixed name.

I'll watch to see if it exceeds the 8mb size.

**Comment by ripienaar** [comment]
It will not get smaller, it will grow to 8Mb and then later when there are no more messages in it, it will be removed.

**Comment by derekcollison** [comment]
KV currently uses 4MB per blk, when they get mostly empty they will compact and when they are completley empty they will be removed.

If we have an empty block but its the last one we hold the empty blk with a empty message marker to recover the sequence numbers if the meta layer is corrupted, essentially re-using the last blk.

**Comment by ripienaar** [comment]
Ah, didn’t realise we compact them now - interior compacts or only at the ends?

**Comment by derekcollison** [comment]
Both, since 2.9 but we are very conservative, will become more aggressive in 2.10.
