### ISSUE TITLE
JetStream consumers got stuck only for one stream

### ISSUE THREAD

**Issue by avalchev94** [nats-io/nats-server#4168]
## Defect
Hi all! I am using JetStream with multiple consumers and streams, however recently all consumers for one specific stream got stuck(all other consumers for different streams were working). They had stopped(last received was 20d ago) receiving any new messages, even though new messages were successfully published. While debugging the issue, I tried to list some existing messages using the cli tool (`nats stream view/get`), however even they were failing(most of the time with `context deadline exceeded`). 

At the end, I had to purge the stream(`nats stream purge`) and everything started working as expected. Fortunately, I made a backup(will attach) before calling purge. I restored the backup to a clean nats instance, however I am still not able to read any messages from that stream, neither with nats cli nor by writing code.

**Backup:** 
[profile_nats_backup.zip](https://github.com/nats-io/nats-server/files/11485657/profile_nats_backup.zip)

#### Versions of `nats-server` and affected client libraries used:
nats-server v2.9.6
nats.go v1.20.0

#### OS/Container environment:
The OS where issue was initially reproduced is `photon:4.0-20210507`
The OS where i was testing the restore is `MacOS v12.5.1
`
#### Steps or code to reproduce the issue:
1. Restore the backup on a clean NATS instance usign nats cli: `nats stream restore`.
2. Try to read any old messages with nats-cli or writing code.

**Comment by Jarema** [comment]
Hi!

Thanks for detailed report and backup!

Will take a look into it.

**Comment by derekcollison** [comment]
Might be good to consider updating your server version to a more recent patch version, 2.9.16 is the latest and 2.9.17 will be released this week.

**Comment by EnneS** [comment]
Hello,
I am having the same issue under the 2.9.14 release.
Although I am not able to purge the corresponding stream (as I am getting the context deadline exceeded error again) and therefore confirm that purging it unstucks it.

**Comment by EnneS** [comment]
Upgraded to 2.9.17 and no longer getting the issue.
