### ISSUE TITLE
Add ability to query jetstream

### ISSUE THREAD

**Issue by dioptre** [nats-io/nats-server#4184]
#### Use Case:
Larger tools like pulsar make it easy to understand whats going on, like you can select * on a stream to show how many errors are being logged in the last minute for example

#### Proposed Change:
Allow querying of jetstream

#### Who Benefits From The Change(s)?
Everyone

#### Alternative Approaches
Not sure

**Comment by derekcollison** [comment]
All JetStream API access is evented through an audit subject.

`$JS.EVENT.ADVISORY.API`

Try listening to that or optionally placing all of them in a stream of their own for audibility.

**Comment by derekcollison** [comment]
Will close for now but if needed feel free to reopen.
