### ISSUE TITLE
NATS Server corrupts the meta.inf file when it gets killed/closed/exited during startup stream loading time.

### ISSUE THREAD

**Issue by BhatheyBalaji** [nats-io/nats-server#4195]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [X] Included `nats-server -DV` output
 - [X] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)
Logs are included. 
**nats-server.exe -DV**
[2684] 2023/05/26 01:08:32.952160 [[32mINF[0m] Starting nats-server
[2684] 2023/05/26 01:08:32.953198 [[32mINF[0m]   Version:  2.9.16
[2684] 2023/05/26 01:08:32.953720 [[32mINF[0m]   Git:      [f84ca24]
[2684] 2023/05/26 01:08:32.954231 [[36mDBG[0m]   Go build: go1.19.8
[2684] 2023/05/26 01:08:32.954257 [[32mINF[0m]   Name:     NAHUTXJA2HWFEV45HQ534LEZ54ZKESIX5NZ6VJKMYKY5XZ5H767XTS2G
[2684] 2023/05/26 01:08:32.954257 [[32mINF[0m]   ID:       NAHUTXJA2HWFEV45HQ534LEZ54ZKESIX5NZ6VJKMYKY5XZ5H767XTS2G
[2684] 2023/05/26 01:08:32.954257 [[36mDBG[0m] Created system account: "$SYS"
[2684] 2023/05/26 01:08:32.955842 [[32mINF[0m] Listening for client connections on 0.0.0.0:4222
[2684] 2023/05/26 01:08:32.955842 [[36mDBG[0m] Get non local IPs for "0.0.0.0"
[2684] 2023/05/26 01:08:32.960573 [[36mDBG[0m]   ip=1.7.19.7
[2684] 2023/05/26 01:08:32.962145 [[32mINF[0m] Server is ready
[2684] 2023/05/26 01:08:32.963720 [[36mDBG[0m] maxprocs: Leaving GOMAXPROCS=4: CPU quota u

#### Versions of `nats-server` and affected client libraries used:
**Version:  2.9.16**
#### OS/Container environment:
**Windows Server 2019 Version 1809 (OS Build 17763.4010)**
#### Steps or code to reproduce the issue:

1. Start the Nats-server, Enable Jetstream, Create a stream, Add many messages (possibly of bug size) this is to increase the time when nats-server starts up as per step No.5
2. Now Stop the nats-server process.
3. Have a script to kill/stop the nats-server service upon demand.
4. Start the nats-server service. (having the logs enabled)
5. When the server starts to "Starting restore for stream '$G > streamname' ", Kill the nats-server.exe.
6. Start the nats-server process newly again.
7. We see the error " **Error unmarshalling stream metafile** "C:\\\DataStore\\EventData\\jetstream\\$G\\streams\\STREAM_EI\\meta.inf": invalid character 'h' looking for beginning of value". This invalid character can change every time.
8. The stream could not be recovered at all.

9. This kill can also occur other times before the server is saying it is ready.
10. Also the same issue happens when System Time changes when server is doing step No. 5

#### Expected result:
When we start the service, the stream should be recoverable.

#### Actual result:
When we start the service and follow the steps, the stream meta file is updated / corrupted. leaving the stream un usable.
#### Actual Logs
[LogToSahre.txt](https://github.com/nats-io/nats-server/files/11564431/LogToSahre.txt) 
Some path and stream names are redacted, please do not mind those.

**Comment by savion1024** [comment]
how to kill/stop nats service, ctrl + c?  or something else operation?

**Comment by BhatheyBalaji** [comment]
I have seen the above problem in: 
1. **Windows Service stop** i.e. thorough Windows Service Controller (where we have registered nats-server.exe with parameters as a service).
2. It had stopped by itself (No Windows event viewer logs on this process closure).
3. When Time changed during refresh.

**Comment by savion1024** [comment]
My speculation is that the Windows system lacks the concept of signals, which prevents graceful service shutdown(lame duck mode), thus causing this issue。

**Comment by savion1024** [comment]
maybe you can try to reproduce it on a Linux system.

**Comment by derekcollison** [comment]
The `meta.inf` file is written once on creation and is not updated unless the stream itself has its properties updated through a stream update call.

**Comment by BhatheyBalaji** [comment]
> 
@derekcollison 
After seeing the data in that file (unencrypted format), I was also expecting there should be no File write/updates but it happens.
Personally I am happy if the server does not update the file which will get me out of this issue :)
I have seen (Both in encrypted and non eccrypted cases) When the nats server finishes  restore for stream, It writes the file into disk.
I have copied the file and check byte by byte.
1. In case of non encrypted the write/update happens but the contents is same
2. In case of Encryption, The contents of the file also changes I beleive the actual contents may not change but encrpyted data may be causing that drastic change.

**Comment by derekcollison** [comment]
Does the issue only seem to happen if the store is encrypted?

**Comment by derekcollison** [comment]
If you turn it off as an experiment does the problem go away?

Not suggesting you run in production that way just curious.

**Comment by BhatheyBalaji** [comment]
@derekcollison I tried multiple time without encryption, and that almost 99% of the time I am not able to reproduce this file corruption problem when encryption is turned off. I have not seen it occur even once when encryption is off. 

Any way to circumvent this problem will be helpful.

**Comment by derekcollison** [comment]
ok thanks for the feedback, will take a closer look.

Does the issue also happen with 2.9.17, the latest server release?

**Comment by BhatheyBalaji** [comment]
@derekcollison : Thanks, We have a updated information about the issue, Looks like the meta.key file is missing /removed when the crash/stop/time change happens. And when we start server without meta.key file it report this error may be it assumed some default key. But the core is the meta.key file goes missing.

I can check with 2.9.17 at the earliest.

**Comment by BhatheyBalaji** [comment]
@derekcollison The issue also happens with 2.9.17 server.exe as well.

**Comment by derekcollison** [comment]
ok will have @tbeets take a look when he has some free time.
