### ISSUE TITLE
nats restart so difficulty

### ISSUE THREAD

**Issue by Doslin** [nats-io/nats-server#4208]
![image](https://github.com/nats-io/nats-server/assets/29807388/9bdb827c-1bf9-4dce-95e3-5d1de2258a24)

**Comment by derekcollison** [comment]
What server version?

What does `nats server list` show?

How about `nats server report jetstream`?

**Comment by wallyqs** [comment]
Hi @Doslin make sure that you are running v2.9.17 in k8s and that your update strategy is parallel (`podManagementPolicy: Parallel`) and that the service is configured with `  publishNotReadyAddresses: true` (these are the defaults from the helm charts too)

**Comment by derekcollison** [comment]
Will close for now but if needed feel free to reopen.
