### ISSUE TITLE
Documentation mismatch

### ISSUE THREAD

**Issue by SUNsung** [nats-io/nats-server#4266]
Installed server version **2.9.15**
The documentation on the site (https://docs.nats.io) is practically useless.
Only commands on **nats-server** are relevant.
Most of the really necessary and important settings are done through the configuration file.
File with unknown configuration......

I tried the examples that are here: https://github.com/nats-io/nats-server/tree/main/server/configs (changing for myself)
I have carefully read the documentation (some pages many times).
Just because a config file passes **nats-server -t -c** validation doesn't mean that the server will work.
And this validation swears at half of the methods from the "documentation" (https://docs.nats.io/running-a-nats-service/configuration)
With the **nats-server --tls** command, I attached the tls files, but even there it tries to bind it to the 0.0.0.0 port, which does not change no matter what I write in the configuration file.

Excellent service, a lot of good features, a huge amount of documentation on the protocol, because of which you can run on anything.
But either I have a broken version or the documentation no longer corresponds to reality.
Here is my config to which I was unable to add auth, tls, or access levels.
This configuration consists of 90% installation manual and 10% authorization data.
I could not add anything except authorization after installing the server.
```
cluster {
 name: "XX-XX-XX"
 
  listen: 0.0.0.0:6222
  
       
}
 authorization {
     user: XX
     pass: XXX
     timeout: 2
 }
store_dir: "/var/lib/nats"
listen: "X.X.X.X:4222"
log_file: /var/log/nats/nats.log
```

**Comment by Jarema** [comment]
Hey @SUNsung 

We're sorry you had a bad experience. We put constant work into docs and are always happy to hear feedback.

As for TLS I think the config described here: https://docs.nats.io/running-a-nats-service/configuration/securing_nats/tls quite accurately describes how to work with it.

That translates to a simple config (pulled out from server tls tests):
```
tls {
  cert_file:  "./configs/certs/server.pem"
  key_file:   "./configs/certs/key.pem"
  timeout:    "2s"
}
```

The link even explains how to set it up and run it.
The same applies to other fields in the reference page you also linked.

Can you show us the config you tried, how you run it and what didn't work?
And if the example I gave you does work correctly for you?

**Comment by SUNsung** [comment]
Hi @Jarema.  
Thanks for the answer.
I can't answer this question now, I can on Monday.
I set up a cluster for two servers and now I'm testing embedded devices.  speed and loss.
the server is fairly stable and any required changes are needed more for security.  The current configuration is enough for tests.

There will be tests all weekend.  It is important to understand how NATS will behave in the event of a bad network, a broken connection, and thousands of similar situations.  The issue of checking the integrity of messages is also important (there is an idea to transfer files in pieces to update the firmware. NATS is more flexible than MQTT at the protocol level.)
If during testing we do not find anything critical for us, then we will continue this dialogue.
If it doesn’t work, then I will save the vps physically and distribute it as a torrent (you can see for yourself what is there and how)


In general, you have good documentation that lacks details.
I did the server setup according to a third-party example - the example on the official site is suitable for local launch, but not for installation on a server where it will work non-stop.
I also had to google the setup, because the documentation is more like a textbook.  If you just read out of interest, or if you are already familiar with all this, then the documentation is clear and complete.

So see you on Monday!

**Comment by Jarema** [comment]
Thanks for the context.

Just to clarify - your cluster with JetStream should have at least 3 servers forming it, as for formulae N/2+1 for the quorum, with 3 nodes it can still function when 1 node is down.

**Comment by SUNsung** [comment]
Hi, @Jarema,

Testing was successful, everyone is happy with the result)

According to the problems that arose, some of them were solved by brute force.

I can list the answers that will definitely arise when setting up the server and which are not in the documentation:

1.  The server requires root access. Without it, with configured permissions, it works fine, but the same tls requires root.
2.  The sequence in the configuration file is important. The "correct" sequence does not match the sequence described in the documentation.
3.  It comes from the second point - if some functionality is "enabled", there must be parameters to this functionality. If the functionality is disabled, then the parameters must be commented out, otherwise the server will not start.
4.  There are parameters that can only be passed as arguments when starting the server, and there are parameters that can only be passed in the configuration file.
5.  If there are active connections that will try to reconnect if lost, restarting the server may fail.(and the server doesn't start)

Other than that, I only have a couple of questions:

1.  is it possible to have a tls connection in parallel with nats? Currently, if tls is enabled, then nats is not available.
2.  Is it possible to get "statistics" directly inside the server, and not on external http?
3.  In the case of a cluster, statistics for each server separately or is it possible to get single statistics for the entire cluster?
4.  Does NATS support hooks? For example, launching a custom script when certain conditions are met (exceeding a given limit) or sending a web request?
