### ISSUE TITLE
Leak memory when creating a consumer name with jetstream.

### ISSUE THREAD

**Issue by VuongUranus** [nats-io/nats-server#4289]
I have problem leaking mem in sync.(*Map).Store in function github.com/nats-io/nats-server/v2/server.getHashSize.
I debug using go tool pprof.  Help me please!

**Comment by VuongUranus** [comment]
<img width="949" alt="Screenshot 2023-07-06 at 15 38 35" src="https://github.com/nats-io/nats-server/assets/80895977/62115aab-593d-4749-8432-87b824be82b0">

**Comment by VuongUranus** [comment]
<img width="848" alt="Screenshot 2023-07-06 at 15 39 35" src="https://github.com/nats-io/nats-server/assets/80895977/0ce545f4-22e6-4dad-bfd0-a54879c3a2c3">

**Comment by derekcollison** [comment]
As a system user what does `nats server ls` show? How about `nats server report jetstream`?

**Comment by derekcollison** [comment]
How many JetStream assets do you have running?

**Comment by VuongUranus** [comment]
I build a cluster of 3 jetstream nodes to serve to create a lot of ephemeral consumers to receive messages. The number of consumers is more than 10000. And I have a memory leak. The problem is that sync.Map stores the names of the consumers and doesn't release. I use the Go programming language and the nats.go library to do this. Don't know what I did wrong?

**Comment by VuongUranus** [comment]
I want memory to be freed when consumers are decremented. I see consumers are released very normally, but the problem is that sync.Map in this code is not freed, leading to memory leak.
<img width="722" alt="image" src="https://github.com/nats-io/nats-server/assets/80895977/34e28e0c-18a9-433b-b376-d481e659d8c5">

**Comment by VuongUranus** [comment]
<img width="533" alt="image" src="https://github.com/nats-io/nats-server/assets/80895977/628035cf-8148-4f6e-a514-99cbb5dc08cb">

**Comment by derekcollison** [comment]
Thanks will take a look, this is helpful. Much appreciated.

**Comment by derekcollison** [comment]
Should be resolved and will be in next release, 2.9.21 probably next week.

**Comment by VuongUranus** [comment]
Thank you very much!!
