### ISSUE TITLE
Error creating consumer for stream with work queue policy when having a mirror stream

### ISSUE THREAD

**Issue by mdawar** [nats-io/nats-server#4310]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included `nats-server -DV` output
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:
- nats-server: `v2.9.20`
- nats.go: `v1.27.1`

#### Server output

```
[1] [INF] Starting nats-server
[1] [INF]   Version:  2.9.20
[1] [INF]   Git:      [97dd7cb]
[1] [DBG]   Go build: go1.19.11
[1] [INF]   Name:     NB3HFH2ZFC543C43I4LKZIYEGUAHY2NXXLP7IILQ6FOFNQKCXMZ6BDOS
[1] [INF]   ID:       NB3HFH2ZFC543C43I4LKZIYEGUAHY2NXXLP7IILQ6FOFNQKCXMZ6BDOS
[1] [DBG] Created system account: "$SYS"
[1] [INF] Listening for client connections on 0.0.0.0:4222
[1] [DBG] Get non local IPs for "0.0.0.0"
[1] [DBG]   ip=172.17.0.2
[1] [INF] Server is ready
[1] [DBG] maxprocs: Leaving GOMAXPROCS=16: CPU quota undefined
```

#### OS/Container environment:
- OS: `linux`
-  Arch: `amd64`
- Go: `v1.20.5`

#### Steps or code to reproduce the issue:
1. Create a stream with a work queue policy
```go
nc, _ := nats.Connect(nats.DefaultURL)
defer nc.Close()

js, _ := jetstream.New(nc)

ctx, cancel := context.WithCancel(context.Background())
defer cancel()

_, err := js.CreateStream(ctx, jetstream.StreamConfig{
	Name:      "tasks",
	Subjects:  []string{"tasks.>"},
	Retention: jetstream.WorkQueuePolicy, // Required for the failure
})
```

2. Create a mirror stream
```go
_, err = js.CreateStream(ctx, jetstream.StreamConfig{
	Name:      "mirror",
	Retention: jetstream.InterestPolicy,
	Mirror: &jetstream.StreamSource{
		Name: "tasks",
	},
})
```

3. Create a consumer for the main stream
```go
_, err = js.CreateOrUpdateConsumer(ctx, "tasks", jetstream.ConsumerConfig{
	Durable:       "TaskConsumer",
	AckPolicy:     jetstream.AckExplicitPolicy,
	FilterSubject: "tasks.info", // Any filter conflicting with the mirror stream will cause an error
})
```

Complete example: https://github.com/mdawar/jetstream-api-demos/tree/main/mirrorstream

#### Expected result:
I expected the consumer to be created on the main stream.

#### Actual result:
The consumer is not created as the subject filter conflicts with the mirror stream.

I don't know much about the internals, but it seems that the mirror stream creates a consumer for the mirrored stream, the consumer can be created only if we use non conflicting subject filters on both the mirror stream and the consumer.

I'm using a mirror stream for monitoring purposes and I want to have multiple durable consumers with different subject filters, I got this error when I added a mirror stream.

**Comment by mdawar** [comment]
@MauriceVanVeen thank you for the info, my use case is distributing work using a stream with a work queue policy, since I can't use a mirror stream how can I monitor this stream's messages?

**Comment by MauriceVanVeen** [comment]
@mdawar if you're fine with mirroring, then you could create a Limits-based stream first. Then create your own consumer for observability/monitoring. And create a WorkQueue-based stream that mirrors from the Limits-based stream.
