### ISSUE TITLE
Callout spec (ADR-26) doesn't match implementation for 'aud' field of generated JWT token

### ISSUE THREAD

**Issue by hspaay** [nats-io/nats-server#4313]
[ADR-26](https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-26.md) says about the issued JWT:
>  the public account key can be seen as the audience for this request and the user_nkey represents the required subject for the signed user JWT response.

Doing this fails with the account not found error (in server mode).
However, using the account name works.

In auth_callout.go:212 (dev branch as of 2023-07-14):
```go
if !isOperatorMode {
// only allow placement if we are not in operator mode
    placement = arc.Audience
} else {
    placement = issuerAccount
}
targetAcc, err := s.LookupAccount(placement)
```
The lookup expects a name. 

Couple of options here. Update the spec if using the name is desired behavior, or change placement to use the public account key, or support both name and key.

A gist with a TestServer using callouts that demonstrates this behavior can be found at:  https://gist.github.com/hspaay/5da05a8bdbe83d59042c83f0cc29bdb9 .
The method 'createNewAuthToken' sets uc.Audience = "AppAccount" which is the account name. When using the public account key as per doc, this doesn't work.

**Comment by aricart** [comment]
@hspaay thanks for the inquiry. The server considers the public key of the account the `name` when in operator mode. In config mode, it is always the assigned name of the account (not a public key).

I have created https://github.com/nats-io/nats-architecture-and-design/pull/231

**Comment by hspaay** [comment]
Thank you for the clarification.
