### ISSUE TITLE
Allow callout issuer to issue token for a different account in server mode

### ISSUE THREAD

**Issue by hspaay** [nats-io/nats-server#4335]
## Feature Request

ADR-26 states: "The response to the request will be a signed user JWT that must be signed by the declared issuer in server configuration mode or an account signing key in operator mode". No rational is given for this constraint and it doesn't seem to solve a problem.

The feature request is to allow a different account signing key in server configuration mode as well.  

#### Use Case:

To enhance security it is good practice to use a separate callout account from the application account. After all, authentication is a completely different task than that what the application performs. 
Constraining the JWT signing account to the callout issuing account (in server mode) would mean that when using callouts only a single account can be used. 

A second use case is to use callout to issue tokens for different accounts. This allows multi-tenancy on an edge device. While rare it is a valid case.

#### Proposed Change:

Allow signing the user JWT by any  account known to the server.

#### Who Benefits From The Change(s)?

Embedded  systems will be able to apply best security practices by separating authn handling from the application. 

#### Alternative Approaches

Use operator mode, but that might not be practical in an edge device.

**Comment by derekcollison** [comment]
Yes you can change accounts.
