### ISSUE TITLE
Binary file accepted as valid configuration

### ISSUE THREAD

**Issue by mprimi** [nats-io/nats-server#4343]
## Defect

I mistakenly fed `nats-server` a binary rather than a configuration file, and `-t` tells me it is a valid configuration.

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included `nats-server -DV` output
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:

Noticed this on `2.9.21-RC.1`, but this has not changed recently.

#### OS/Container environment:

Not relevant

#### Steps or code to reproduce the issue:

Pass the path of a binary (or other non-textfile, like PDF) as configuration argument:
```
 ./nats-server -t -c ./nats-server
```

#### Expected result:
Non zero-exit code, and a message telling me I'm doing it wrong

#### Actual result:
`nats-server: configuration file ./nats-server is valid`

#### Details

Stepping through the configuration parsing steps, it seems like the entire binary is treated treated like as `itemKey`, and accepted.

Even setting `pedantic`, there are no errors and no warnings.

**Comment by derekcollison** [comment]
Hey @wallyqs I know you fixed this in dev IIRC, should we cherry pick to main?

**Comment by wallyqs** [comment]
fine to cherry pick I think, will make a PR
