### ISSUE TITLE
Leafnode cluster receiving message 3 times?

### ISSUE THREAD

**Issue by pcsegal** [nats-io/nats-server#4367]
I'm trying to establish communication between two NATS clusters (A and B).

**Cluster A** has multiple isolated customer accounts (`AccountA`, `AccountB`, `AccountC`). These accounts represent multiple instances of the same service running for different customers. So, for example, subject `mysubj` in `AccountA` is completely isolated from `mysubj` in `AccountB`; they are both handled by separate instances of an application, for example.

**Cluster B** has an account W from which I want to be able to send requests to those multiple accounts in cluster A. The idea is to use prefixes in the subject name to differentiate between accounts. For example, to send a request to `AccountA`'s `mysubj` in cluster A, I would make a request to `a.mysubj` from account W in cluster B. Likewise, a request to `b.mysubj` should reach `mysubj` in `AccountB`, and so on.

I'm trying to accomplish this using a leafnode connection where cluster A is the leafnode and cluster B is the hub.

However, I can't seem to get it right. With my current attempt, requests made from W to `a.mysubj` do reach `mysubj` in AccountA of cluster A, but messages are being received 3 times, rather than one.

In the example below, I included the configuration files and a test script, all of which should be in the same directory. Cluster A (the leafnode) has 3 nodes, but cluster B (the remote) has only 1 node to make it shorter.

What am I missing?

Thank you.

#### cluster-a-common.conf

```
accounts: {
    $SYS: {
        users: [
            {user: admin, password: pwd}
        ]
    },
    AccountA: {
        jetstream: enabled
        mappings: {
            a.>: ">"
        }
        exports: [
            {service: a.>}
        ]
        users: [
                {user: a, password: a}
        ]
    },
    AccountB: {
        jetstream: enabled
        mappings: {
            b.>: ">"
        }
        exports: [
            {service: b.>}
        ]
        users: [
                {user: b, password: b}
        ]
    },
    AccountC: {
        jetstream: enabled
        mappings: {
            c.>: ">"
        }
        exports: [
            {service: c.>}
        ]
        users: [
                {user: c, password: c}
        ]
    },
    AGG: {
        imports: [
            {service: {subject: a.>, account: AccountA}},
            {service: {subject: b.>, account: AccountB}},
            {service: {subject: c.>, account: AccountC}}
        ]
        users: [
                {user: agg, password: agg}
        ]
    },
}

leafnodes {
    remotes: [
        {
            urls: [
                nats-leaf://agg:agg@0.0.0.0:7422,
            ]
            account: AGG
        },
    ]
}
```

### cluster-a-0.conf:

```
port: 4222

http: 8222
server_name:cluster-a-0

jetstream {
    max_mem: 1Gi
    store_dir: /tmp/cluster-a-0
}
lame_duck_grace_period: 10s
lame_duck_duration: 30s

cluster {
    listen: 0.0.0.0:6222
    name: cluster-a
    routes = [
        nats://127.0.0.1:6222,
        nats://127.0.0.1:6223,
        nats://127.0.0.1:6224,
    ]
    connect_retries: 120
}

include cluster-a-common.conf
```

### cluster-a-1.conf

```
port: 4223

http: 8223
server_name:cluster-a-1

jetstream {
    max_mem: 1Gi
    store_dir: /tmp/cluster-a-1
}
lame_duck_grace_period: 10s
lame_duck_duration: 30s

cluster {
    listen: 0.0.0.0:6223
    name: cluster-a
    routes = [
        nats://127.0.0.1:6222,
        nats://127.0.0.1:6223,
        nats://127.0.0.1:6224,
    ]
    connect_retries: 120
}

include cluster-a-common.conf
```

## cluster-a-2.conf

```
port: 4224

http: 8224
server_name:cluster-a-2

jetstream {
    max_mem: 1Gi
    store_dir: /tmp/cluster-a-2
}
lame_duck_grace_period: 10s
lame_duck_duration: 30s

cluster {
    listen: 0.0.0.0:6224
    name: cluster-a
    routes = [
        nats://127.0.0.1:6222,
        nats://127.0.0.1:6223,
        nats://127.0.0.1:6224,
    ]
    connect_retries: 120
}

include cluster-a-common.conf
```
#### cluster-b-0.conf

```
port: 4225

http: 8225
server_name:cluster-b-0

jetstream {
    max_mem: 1Gi
    store_dir: /tmp/cluster-b-0
}
lame_duck_grace_period: 10s
lame_duck_duration: 30s

accounts {
    $SYS: {
        users: [
            {user: admin, password: pwd}
        ]
    },
    AGG: {
        jetstream: enabled
        exports: [
            {service: >}
        ]
        users: [
            {user: agg, password: agg}
        ]
    },
    W: {
        imports: [
            {service: {subject: >, account: AGG}}
        ]
        users: [
            {user: w, password: w}
        ]
    },
}

leafnodes {
    port: 7422
}
```

### test.sh

This script exemplifies the behavior that I'm seeing. When I run a responder for `mysubj` in `AccountA` and then send a request to `a.mysubj` from account `W` in cluster B, the request is received 3 times.

```
#!/bin/bash

set -euo pipefail

nats-server -c cluster-a-0.conf > /dev/null 2>&1 &
nats-server -c cluster-a-1.conf > /dev/null 2>&1 &
nats-server -c cluster-a-2.conf > /dev/null 2>&1 &

nats-server -c cluster-b-0.conf > /dev/null 2>&1 &

sleep 3

curl --fail --silent --retry 5 --retry-delay 1 http://localhost:8222/healthz > /dev/null
curl --fail --silent --retry 5 --retry-delay 1 http://localhost:8223/healthz > /dev/null
curl --fail --silent --retry 5 --retry-delay 1 http://localhost:8224/healthz > /dev/null
curl --fail --silent --retry 5 --retry-delay 1 http://localhost:8225/healthz > /dev/null

# Create a responder for mysubj in AccountA in cluster A
nats -s localhost:4222 reply mysubj 'replyA' --user a --password a &

sleep 1

# Send a request to a.mysubj from W in cluster B
nats -s localhost:4225 request a.mysubj 'requestA' --user w --password w

pkill -P $$
```

### Example output

```
12:37:33 Listening on "mysubj" in group "NATS-RPLY-22"
12:37:34 Sending request on "a.mysubj"
12:37:34 [#0] Received on subject "mysubj":
12:37:34 Nats-Request-Info: {"acc":"W","rtt":2060300}

requestA
12:37:34 [#1] Received on subject "mysubj":
12:37:34 Nats-Request-Info: {"acc":"W","rtt":2060300}

requestA
12:37:34 [#2] Received on subject "mysubj":
12:37:34 Nats-Request-Info: {"acc":"W","rtt":2060300}

requestA
12:37:34 Received with rtt 4.1203ms
replyA
```

**Comment by jnmoyne** [comment]
How to fix: Rather than doing the subject mapping at the account level in each account and then exporting the service without, do the mapping as part of the import. Meaning that in your example there should be no mapping in the account and it just exports `>` but on the import you can add a `to:` to do the mapping to a subject that references that account from which the service is imported.

So change `cluster-a-common.conf` to:
```
accounts: {
    $SYS: {
        users: [
            {user: admin, password: pwd}
        ]
    },
    AccountA: {
        jetstream: enabled
        exports: [
            {service: >}
        ]
        users: [
                {user: a, password: a}
        ]
    },
    AccountB: {
        jetstream: enabled
        exports: [
            {service: >}
        ]
        users: [
                {user: b, password: b}
        ]
    },
    AccountC: {
        jetstream: enabled
        exports: [
            {service: >}
        ]
        users: [
                {user: c, password: c}
        ]
    },
    AGG: {
        imports: [
            {service: {subject: >, account: AccountA}, to: a.>},
            {service: {subject: >, account: AccountB}, to: b.>},
            {service: {subject: >, account: AccountC}, to: c.>}
        ]
        users: [
                {user: agg, password: agg}
        ]
    },
}

leafnodes {
    remotes: [
        {
            urls: [
                nats-leaf://agg:agg@0.0.0.0:7422,
            ]
            account: AGG
        },
    ]
}
```

**Comment by pcsegal** [comment]
Some additional data: this triplication doesn't happen if I use `sub` and `pub` instead of `reply` and `request`, e.g.:

```
nats -s localhost:4222 sub mysubj --user a --password a &
nats -s localhost:4222 sub mysubj --user b --password b &

sleep 1

nats -s localhost:4225 pub a.mysubj "request" --user w --password w
```

However, it does happen if I use a queue name in `sub` via the `--queue` option, e.g.:

```
nats -s localhost:4222 sub mysubj --queue GRP1 --user a --password a &
nats -s localhost:4222 sub mysubj --queue GRP2 --user b --password b &
```

**Comment by derekcollison** [comment]
We have not but I would imagine its due to an introduction of a loop that the system can not detect properly since exports/imports are considered crossing a secure membrane, and leafnodes bind remote accounts to local accounts in a similar fashion.

Do you have a commercial agreement with Synadia?

**Comment by derekcollison** [comment]
ok I dig in a bit.

What is happening is a combination of multiple factors. Mostly having to do with the implicit queue groups when doing `nats reply`. This queue group information is weighted as it moves around the system. For instance across routes the interest remains but the weight changes etc. This weight is also propagated across leafnode boundaries as well, as a weighted update. When you do service imports, that is also a sense of interest.

The complications as to why this is not working properly is as follows. When the queue subscriber is imported across an account boundary, then a leafnode boundary, each leafnode is signaling interest. So what I mean by that is that since you have 3 servers in cluster A going into cluster B, which is a single node, that server sees all three leafnodes interested in the request, so it sends it to all three leafnodes, and hence the queue subscriber gets three requests.

I do believe this should work at some level, so I want to dig in and see if I can get it to work.

For now, if you change the subscriber to a plain subscriber, it will work as you want it.
If you connect the requestor to cluster A and account agg, it will also work as intended.
If you form a super cluster between cluster A and B vs leafnodes, it will also work they way you want it.

I will take a deeper look, but I will need to carve out a few hours to setup the test and really dig in to where we lose the signalling of a queue goup and weight and becomes a binary signal across all three leafnodes.
