### ISSUE TITLE
CrashLoopBackOff due to JetStream Encryption Key Size Error during Rolling Upgrade (nats-server 2.9.21)

### ISSUE THREAD

**Issue by dillonstreator** [nats-io/nats-server#4390]
**Versions of nats-server and affected client libraries used:**

nats-server 2.9.21
argo events chart [2.4.0](https://github.com/argoproj/argo-helm/releases/tag/argo-events-2.4.0)

**OS/Container environment:**

K8s

**Steps or code to reproduce the issue:**

1. Existing nats 2.9.12 cluster (3 instances) with Jetstream enabled
1. When executing rolling upgrade to 2.9.21 ordinal 1 and 2 pod successfully applied v2.9.21 while ordinal 3 pod is stuck in a `CrashLoopBackOff` with the error:
    ```sh
    ...
    [363] ... [ERR] Error creating filestore: encryption bad key size
    [363] ... [FTL] Can't start JetStream: encryption bad key size
    ...
    ```
https://github.com/nats-io/nats-server/blob/f2c7a9d37f1a7a612814abf9365c52ed6687ec4f/server/filestore.go#L703-L714

**Steps or code to resolve the issue:**

1. Get a debug container in the erroring pod with the jetstream data mounted https://github.com/kubernetes/kubectl/issues/1071#issuecomment-1437836931
1. Find `*.key` file(s) with invalid-looking file sizes (0 bytes in my case) in the jetstream store path (`/data/jetstream/store/jetstream/sys/_js_` in my case)
1. Delete the key file(s) (`/data/jetstream/store/jetstream/sys/_js_/_meta_/msgs/1.key` in my case)
1. Pod restarts with the following warning but otherwise successfully
    ```sh
    [52] ... [WRN] RAFT [4tE2YNRj - _meta_] Snapshot corrupt, too short
    ```

Update:
The resolution steps appear to be a bandaid as the problem continues to pop up after about a day of execution. We've wiped the PVC with the missing keys about 3 times now. Each time the missing key has been encountered, it has happened on the same ordinal node as initially described.

**Comment by vermaxik** [comment]
We had the same issue, but for `2.9.16` version, after node in k8s was crashed. I was wondering what is causing the issue that keys have 0 bytes.

Thank you a lot for sharing steps how to solve this issue @dillonstreator ❤️

**Comment by rwong2888** [comment]
would `2.10.x` fix this?

**Comment by dillonstreator** [comment]
Upgrading to `2.10.x` appears to have resolved the issue. To prepare for the `2.10.x` upgrade, we first upgraded to `2.9.22` in the event that we needed to revert. We didn't need to revert but this seemed like a reasonable approach.

https://github.com/nats-io/nats-server/releases/tag/v2.10.0
> 2.10.0 brings on-disk storage changes which bring significant performance improvements. Upgrade existing server versions will handle the new storage format transparently. However, if a downgrade from 2.10.0 occurs, the old version will not understand the format on disk with the exception 2.9.22 and any subsequent patch releases for 2.9. So if you upgrade from 2.9.x to 2.10.0 and then need to downgrade for some reason, it must be back to 2.9.22+ to ensure the stream data can be read correctly.

**Comment by Jarema** [comment]
Happy to hear that 2.10.x solved the problem!
I'm closing the issue.
Feel free to reopen if you feel its necessary.
