### ISSUE TITLE
Add tags for NATS Jetstream consumers

### ISSUE THREAD

**Issue by AbstractiveNord** [nats-io/nats-server#4409]
#### Use Case:
Select procedure in code based on tags on active consumer, group consumers by common parts of tag. I consider tag as comma or dot separated string.

#### Proposed Change:
Add tag system for consumers.

#### Who Benefits From The Change(s)?
Everyone, who have complex logic on the consumers.

#### Alternative Approaches
Drop the idea.

**Comment by Jarema** [comment]
You can use the Metadata feature that will be part of 2.10 release and is available in dev branch.

**Comment by bruth** [comment]
@AbstractiveNord As @Jarema noted, there will be a new metadata field (key-value pairs) for streams and consumers. Based on what you described, this should satisfy the request. Feel free to re-open if you had other ideas.
