### ISSUE TITLE
Authorization wildcard preceded by dash does not work

### ISSUE THREAD

**Issue by huberts90** [nats-io/nats-server#4471]
### What version were you using?

server: nats:2.9.0-alpine

### What environment was the server running in?

K3S: v1.26.5+k3s1

### Is this defect reproducible?

Authorization wildcard is not applicable if preceded by dash ("-"), e.g. `"SubjectName-*"`/`"SubjectName->"`.
It works if the wildcard is precede by dot ("."), e.g. `"SubjectName.*"`/`"SubjectName.>"`.

### Given the capability you are leveraging, describe your expectation?

Wildcard could work for every provided string.

### Given the expectation, what is the defect you are observing?

If the subject name contains inappropriate characters, then the authorization policy is weakened.

**Comment by derekcollison** [comment]
NATS subject tokens are separated by dot `.`, so this is expected.

**Comment by cesarvspr** [comment]
If this is expected I believe we can close this issue, right? @derekcollison

**Comment by huberts90** [comment]
Thank you @derekcollison for your reply!
