### ISSUE TITLE
When a message is published, the consumer will receive many messages.

### ISSUE THREAD

**Issue by manchurio** [nats-io/nats-server#4507]
### What version were you using?

nats-server: v2.9.21
nats.go    v1.28.0

### What environment was the server running in?

wsl2 ubuntu 22.04
amd 7945x

### Is this defect reproducible?

nats-server
```bash
./nats-server -js -m 8222 -DV
```
consumer
```go
package main

import (
	"fmt"
	"github.com/nats-io/nats.go"
	"os"
	"time"
)

func main() {
	url := os.Getenv("NATS_URL")
	if url == "" {
		url = "nats://localhost:4222"
	}

	nc, _ := nats.Connect(url, nats.ReconnectHandler(func(conn *nats.Conn) {
		fmt.Println("Reconnecting.......")
	}))

	js, _ := nc.JetStream()

	streamName := "EVENTS"

	js.AddStream(&nats.StreamConfig{
		Name:     streamName,
		Subjects: []string{"events.>"},
	})
	for {
		_, err := js.Subscribe("events.3", func(msg *nats.Msg) {
			fmt.Printf("received :%s %s\n", msg.Subject, string(msg.Data))
			msg.Ack()
		}, nats.OrderedConsumer(), nats.IdleHeartbeat(250*time.Millisecond),
			nats.StartTime(time.Now()))

		if err != nil {
			panic(err)
		}
	}
	select {}

}

```

publisher
```
nats pub events.3 hello
```

### Given the capability you are leveraging, describe your expectation?

The consumer should receive only one message, but in reality, it receives many messages (possibly more than 30).

### Given the expectation, what is the defect you are observing?

for the consumer:
```The consumer should receive only one message, but in reality, it receives many messages (possibly more than 30).```

for the server
```I only published one message, but the nats-server keeps logging incessantly, almost never stopping. I started the nats-server with the -DV flag.```

**Comment by wallyqs** [comment]
@manchurio you are calling `js.Subscribe` in a for loop so each call would be creating its own consumer and each would receive a copy of the message

**Comment by manchurio** [comment]
Oh! My bad, I'll  close it now
