### ISSUE TITLE
 strict authentication, if no  jwt authentication information, reject the connection?

### ISSUE THREAD

**Issue by cxcel** [nats-io/nats-server#4522]
### What motivated this proposal?

A very strict authentication mechanism is required: Is nats-server configured to force JWT authentication to be turned on? If the client does not provide jwt authentication information, reject the connection?

### What is the proposed change?

none

### Who benefits from this change?

Scenarios that require strict authentication

### What alternatives have you evaluated?

none

**Comment by derekcollison** [comment]
You can force JWT authentication today. Any client that does not present credentials, or present bad credentials, will be rejected.

**Comment by cxcel** [comment]
How to configure nat-server

**Comment by cxcel** [comment]
thanks, I found it
