### ISSUE TITLE
Ensure that no message is lost

### ISSUE THREAD

**Issue by mmm8955405** [nats-io/nats-server#4542]
### What motivated this proposal?

Persist messages to ensure that no message can be lost. Ensure persistence to the hard drive. Is there any implementation method for this function?

### What is the proposed change?

No more information found

### What alternatives have you evaluated?

redis aof

**Comment by agufagit** [comment]
I thought jetstream persist messages, no?

**Comment by manchurio** [comment]
Jetstream can meet your needs. https://docs.nats.io/nats-concepts/jetstream

**Comment by mmm8955405** [comment]
There are many ways to approach persistence. Most message queues in the market use asynchronous methods, which may result in message loss. With confirmation, I do not want any messages to be lost

**Comment by mmm8955405** [comment]
> Jetstream can meet your needs. https://docs.nats.io/nats-concepts/jetstream

I have looked at this page many times, but I am unable to determine the persistence method of Jetstream. Does it write persistence first before message notification? Any detailed information related to this aspect. But I saw your reply and I am sure it can be done without losing any messages. This is very important for me and I will continue to evaluate it

**Comment by derekcollison** [comment]
Streams can be backed by file or memory. If the replication factor is > 1 we run our own consensus algorithm based on RAFT. So the message is stored through to the kernel for each message, and for R > 1 a quorum of peers have done the same before the pubAck is sent to the application.

**Comment by mmm8955405** [comment]
I think I should close this issue

**Comment by derekcollison** [comment]
Yes we properly meet this objective.
