### ISSUE TITLE
Bug in https://docs.nats.io/running-a-nats-service/configuration#configuration-reloading

### ISSUE THREAD

**Issue by TomasVojacek** [nats-io/nats-server#4628]
### What version were you using?

2.10.1

### What environment was the server running in?

docker

### Is this defect reproducible?

Reload server doc is wrong:
accoring documentation does not work calling does not work:
`nats --user sys --password sys pub '$SYS.REQ.SERVER.<server-id>.RELOAD'`

called as request with empty payload work:
`nats --user sys --password sys request '$SYS.REQ.SERVER.<server-id>.RELOAD' ""` 

### Given the capability you are leveraging, describe your expectation?

nats pub/request require payload as parameter

internally zReq function is called 
See https://github.com/nats-io/nats-server/blob/beee6fc72aa52df505efc3f9de539d7f5ebd138b/server/events.go#L1889
so request must be used instead of pub

### Given the expectation, what is the defect you are observing?

Reading payload from STDIN
afer ^D nothing happen

**Comment by derekcollison** [comment]
Looping in @gcolliso to help out with a fix.

**Comment by gcolliso** [comment]
updated docs.nats.io accordingly [https://github.com/nats-io/nats.docs/pull/640](https://github.com/nats-io/nats.docs/pull/640)
