### ISSUE TITLE
Key-Value watch doesn't see delete caused by TTL

### ISSUE THREAD

**Issue by AbstractiveNord** [nats-io/nats-server#4640]
### What version were you using?

2.9.22

### What environment was the server running in?

Docker image nats:2.9.22

### Is this defect reproducible?

1. `nats kv add issue --ttl=10s`
2. `nats kv watch issue`
3. `nats kv put issue key value`
4. Watch doesn't show delete caused by TTL expire

### Given the capability you are leveraging, describe your expectation?

I expect to have a message about key TTL expiration

### Given the expectation, what is the defect you are observing?

No message about key with expired TTL is delivered

**Comment by derekcollison** [comment]
Known issue and on our plans to add in for next minor server version 2.11.
