### ISSUE TITLE
unexpected stream_seq: 18446744073709551614

### ISSUE THREAD

**Issue by Shadowfaxenator** [nats-io/nats-server#4677]
### Observed behavior

Running 50 durable consumers for aprox one month, two of them having an error due to 
stream_seq":18446744073709551614

`
16:19:36 <<< $JS.API.CONSUMER.INFO.beta-02_wallet.beta-02_wallet-projections-12
{"type":"io.nats.jetstream.api.v1.consumer_info_response","stream_name":"beta-02_wallet","name":"beta-02_wallet-projections-12","created":"2023-09-19T10:48:49.536589666Z","config":{"durable_name":"beta-02_wallet-projections-12","name":"beta-02_wallet-projections-12","deliver_policy":"all","ack_policy":"explicit","ack_wait":30000000000,"max_deliver":-1,"filter_subject":"beta-02_.wallet.12.\u003e","replay_policy":"instant","max_waiting":512,"max_ack_pending":1,"num_replicas":0},"delivered":{"consumer_seq":251228,"stream_seq":18446744073709551614},"ack_floor":{"consumer_seq":251228,"stream_seq":4395},"num_ack_pending":0,"num_redelivered":0,"num_waiting":2,"num_pending":0,"cluster":{"name":"dev","leader":"nats-development-03.b2bdev.pro","replicas":[{"name":"nats-development-01.b2bdev.pro","current":true,"active":703680576,"peer":"9e7929rG"},{"name":"nats-development-02.b2bdev.pro","current":true,"active":703655245,"peer":"IX5R0mzu"}]},"ts":"2023-10-18T16:19:36.361063538Z"}`

`nats: error: could not load Consumer beta-02_wallet > beta-02_wallet-projections-12: server response is not a valid "io.nats.jetstream.api.v1.consumer_info_response" message: /delivered/stream_seq: must be <= 1.8446744073709552e+19 but found 1.8446744073709552e+19
missing properties: 'error'
`

`State for Stream beta-02_wallet created 2023-09-19 10:00:22

Cluster Information:

                 Name: dev
               Leader: nats-development-02.b2bdev.pro
              Replica: nats-development-01.b2bdev.pro, current, seen 0.70s ago
              Replica: nats-development-03.b2bdev.pro, current, seen 0.75s ago

State:

             Messages: 13,843
                Bytes: 7.6 MiB
             FirstSeq: 1 @ 2023-09-19T10:31:49 UTC
              LastSeq: 13,843 @ 2023-10-18T15:55:19 UTC
     Active Consumers: 50
   Number of Subjects: 4,874`

### Expected behavior

stream_seq must not be stream_seq: 18446744073709551614

### Server and client version

nats-server: v2.10.3
cli: v0.1.1

### Steps to reproduce

using `nats con info` or any language SDK trying to request an exact corrupted consumer

**Comment by derekcollison** [comment]
Could you create a snapshot of the stream with consumers and share with the team at Synadia?

**Comment by Shadowfaxenator** [comment]
sent to derek@nats.io
subject: GitHub issues/4677

**Comment by derekcollison** [comment]
I see it now, was in spam folder. Will take a look.

**Comment by wallyqs** [comment]
Fixed on v2.10.14 as part of the fixes from #5270
