### ISSUE TITLE
redeliver backoff setting doesn't work

### ISSUE THREAD

**Issue by yongce** [nats-io/nats-server#4726]
### Observed behavior

We configured the consumer with redeliver backoff as following:

```
Configuration:

        Durable Name: gznx1_controller_11_11_6_111
         Description: cs_controller|v2
           Pull Mode: true
      Filter Subject: gznx1.controller.11.11.6.111
      Deliver Policy: All
          Ack Policy: Explicit
            Ack Wait: 30s
       Replay Policy: Instant
  Maximum Deliveries: 4
     Max Ack Pending: 32
   Max Waiting Pulls: 512
             Backoff: 30s, 30s, 30s
```

When a message was 'nak'ed with `msg.Nak()` , all message redeliveries happend right now and there was no delay.

### Expected behavior

We expect the message redeliveries happened with delay 30s.

### Server and client version

Server: 
```
         Version: 2.9.17
      Git Commit: 4f2c9a5
      Go Version: go1.19.9
```

client: v0.0.33

### Host environment

Debian 11
Linux mw12.dev.net-virt.lan 5.10.0-22-amd64 #1 SMP Debian 5.10.178-3 (2023-04-22) x86_64 GNU/Linux
Docker: 23.0.6

### Steps to reproduce

Request a message and nak it in the consumer.

**Comment by ripienaar** [comment]
Unfortunately this setting doesn’t apply to NaK. So in your client use NakWithDelay() or language equivalent. There you give it a next delivery time

**Comment by yongce** [comment]
Got it. Thanks!

**Comment by drewcorlin1** [comment]
Is this still the case? [The docs](https://docs.nats.io/nats-concepts/jetstream/consumers#:~:text=Yes-,Backoff,-A%20sequence%20of) make it sound like it will be respected. If it is, could the docs be updated to more clearly call out the behavior? Thanks!

**Comment by derekcollison** [comment]
NAK w/ delay works fine..

**Comment by ripienaar** [comment]
Backoff delay doesn't appliy to NAK only redeliveries due to ack wait expire.
