### ISSUE TITLE
Remove TLSHandshakeError EOF error logs

### ISSUE THREAD

**Issue by sylr** [nats-io/nats-server#4763]
### Proposed change

Since NATS only does the TLS handshake after the INFO message we have configured our prometheus blackbox exporter probes to only do tcp connections to nats to ensure nats servers are up.

It works well however our server logs are flooded with:

```
Nov 07 18:28:48 nats-euc1a-dev-01 nats-server[527]: [527] 2023/11/07 18:28:48.211660 [ERR] 10.132.30.245:34920 - rid:365 - TLS route handshake error: tls: client didn't provide a certificate
Nov 07 18:28:48 nats-euc1a-dev-01 nats-server[527]: [527] 2023/11/07 18:28:48.211681 [INF] 10.132.30.245:34920 - rid:365 - Router connection closed: TLS Handshake Failure
```

If would be nice if we could remove or at least log as debug the errors when they are `EOF`.

Regards.

### Use case

Monitoring

**Comment by derekcollison** [comment]
You health probes are connecting to the route ports vs client ports.

**Comment by sylr** [comment]
In fact we do both client and route ports.

We had a recent incident where we let NATS certificate expired because we forgot to reload the NATS processes.

To ensure it does not happen again we also set up blackbox TLS probes on the route ports so that we can check the expiration date of the cert used by NATS. We used the route port because it does standard TLS as opposed to the client port.

So we have:

- A TCP probe on the client port
- A TLS probe on the route port

**Comment by sylr** [comment]
All right, so after some thinking and digging I found the right prometheus blackbox exporter configuration to do TLS on the client port:

```
    nats_ping_tls:
      prober: tcp
      timeout: 5s
      tcp:
        query_response:
        - expect: "^INFO "
        - starttls: true
        preferred_ip_protocol: "ip4"
```

No need to connect to the route port anymore and TLS certificate expiration date is exposed in metrics.

**Comment by ripienaar** [comment]
fwiw, latest nats server allows TLS before INFO

**Comment by sylr** [comment]
Not without configuring clients too if I read correctly.

**Comment by ripienaar** [comment]
It does support old and new as a mix so it doesnt requie a big bang transition which generally wouldnt be possible.
