### ISSUE TITLE
Leafnode websocket connections: subpath in wrong order

### ISSUE THREAD

**Issue by yoadey** [nats-io/nats-server#4765]
### Observed behavior

When connecting leafnodes by websockets via a reverse proxy (e.g. in Kubernetes), the subpath for websocket is attached after the static `/leafnode` path instead of before it.

Currently, if in a leafnode configuration the following config is given:
```
leafnodes {
    remotes = [
        {
          url: "wss://user:pass@server.host.org:443/nats-leafnode/",
          account: "ACC"
        },
    ]
}
```

The websocket tries to connect to the following URL:
`server.host.org:443/leafnodenats-leafnode/` instead of `server.host.org:443/nats-leafnode/leafnode`

### Expected behavior

The websocket should connect to
`server.host.org:443/nats-leafnode/leafnode` instead of `server.host.org:443/leafnodenats-leafnode/`

### Server and client version

Both at 2.10.4

### Steps to reproduce

Deploy a NATS server after an NGINX with websocket support, which rewrites the websocket connection URL from somehost.org/nats/leafnode to somehost.org/leafnode.

Have a NATS server with leafnode support running behind the proxy and a NATS server acting as a leafnode connecting through the reverse proxy with following config:
```
leafnodes {
    remotes = [
        {
          url: "ws://user:pass@server.host.org:443/nats/",
          account: "ACC"
        },
    ]
}
```

# Additional Info

The following line probably causes this issue:
https://github.com/nats-io/nats-server/blob/9c2e109f9f770a2c74e33d2c2a675e120b0065c4/server/leafnode.go#L2792
and should probably be changed to something like:
```
path = curPath + path
```

**Comment by wallyqs** [comment]
Thanks for the report, this should be fixed after #4770 is merged and part of the next release.

To use it though it has to be as follows, for example given the following leaf remote URL config:

```
leafnodes {
    remotes = [
        {
          url: "ws://user:pass@127.0.0.1:8080/nats-leafnode/",
          account: "ACC"
        }
    ]
}
```

The nginx setup will have be look like this, notice the `/leafnode` prefix in the subpath:

```
    upstream websocket {
        server 127.0.0.1:8080;
    }
 
    server {
        location /leafnode/nats-leafnode {
        # ...
        }
```

**Comment by yoadey** [comment]
Sorry to say, but this doesn't help us at all and makes it very counterintuitive. Our goal was, to have all NATS related websockets/services available under the common path someserver.org/nats/[leafnode|websocket|monitoring]. As a user I would expect, that any static path used by NATS (e.g. leafnode) is added as a postfix. Could you please consider changing "/leafnode" to be a postfix instead of a prefix?

**Comment by derekcollison** [comment]
This not solve the issue?

https://github.com/nats-io/nats-server/commit/8d3253d907d8c3b4a09f714eb4a7b1695e8608dd

**Comment by yoadey** [comment]
No, as the custom path is a postfix instead of a prefix. As @wallyqs wrote, the server part would now be 
```
location /leafnode/mycustompart {
  # ...
}
```
instead of
```
location /mycustompart/leafnode {
  # ...
  }
```

**Comment by derekcollison** [comment]
He is working on fix AFAIK.

**Comment by yoadey** [comment]
Any news here?

**Comment by ripienaar** [comment]
Seems completed in https://github.com/nats-io/nats-server/pull/4774

**Comment by yoadey** [comment]
Didn't saw that, thank you very much! That's indeed what I was looking for.
