### ISSUE TITLE
nats-server support for lower go versions

### ISSUE THREAD

**Issue by mojixcoder** [nats-io/nats-server#4790]
### Observed behavior

`nats-server` is installed by some people for testing purposes(`github.com/nats-io/nats-server/v2/test`).  

I updated `nats-server` in my project and saw I get this error when building my Go app. `undefined: strings.CutPrefix`.  

`nats-server` **v2.10.5** cannot be installed on **Go1.19** because of this.  

I saw the code and it was used here: `https://github.com/nats-io/nats-server/blob/main/logger/log.go#L215`

### Expected behavior

`nats-server` should be installable in Go1.19 apps because people need it for testing purposes.

### Server and client version

Server: `v2.10.5`
Go: `v1.19`

**Comment by ripienaar** [comment]
We follow Go support policy which means latest 2 releases are supported.  This aligns with Go who only does security updates for the same. 

It's in everyones interest to follow along with this policy.

**Comment by mojixcoder** [comment]
Makes sence, if that's the policy then there is no problem.
