### ISSUE TITLE
`nats server check` or `nats sub ">"` commands not working as per example https://docs.nats.io/running-a-nats-service/clients

### ISSUE THREAD

**Issue by khanakia** [nats-io/nats-server#4796]
### Observed behavior

➜ nats server check
error: a subcommand from the list below is required, use --help for full help including flags and arguments

AND

➜ nats sub ">"
nats: error: nats: no servers available for connection

As you can see server is running fine
<img width="1307" alt="Screenshot 2023-11-15 at 6 14 49 PM" src="https://github.com/nats-io/nats-server/assets/2174170/931352e2-746a-4446-92bf-94addadc0c54">

### Expected behavior

It should work as per the example here https://docs.nats.io/running-a-nats-service/clients

### Server and client version

nats-server: v2.9.19
 nats --version: 0.1.1

### Host environment

localhost

### Steps to reproduce

1. Run `nats-server`
2. Now test using `nats server check`

**Comment by ripienaar** [comment]
Now `nats server check` should be `nats server check connection`.

When sub fails its trying to connect to localhost:4222 by default, you should configure your correct connection url with `--server`, if using docker you will need to specify correct host.

**Comment by khanakia** [comment]
Already tried that command too and getting below error
```
nats server check connection
CRITICAL Connection Crit:connection failed
```

**Comment by ripienaar** [comment]
In that case I guess also `telnet localhost 4222` fails (replace telnet with nc or whatever you user).

You need to tell us more about how this is run and verify basic connectivity.

**Comment by khanakia** [comment]
I just followed this tutorial https://docs.nats.io/running-a-nats-service/clients

No, telnet does not fail only that command fails`nats server check connection`
```sh
 telnet localhost 4222
Trying ::1...
Connected to localhost.
Escape character is '^]'.
INFO {"server_id":"NBK66J4KJAAXDCOCTSIAPGKDN6T2C72EKSUFNSPCSFZ6BB2D52O5S7VW","server_name":"NBK66J4KJAAXDCOCTSIAPGKDN6T2C72EKSUFNSPCSFZ6BB2D52O5S7VW","version":"2.9.19","proto":1,"go":"go1.20.5","host":"0.0.0.0","port":4222,"headers":true,"max_payload":1048576,"client_id":4,"client_ip":"::1"} 
```

**Comment by ripienaar** [comment]
I assume `127.0.0.1` also works rather than `localhost`? Hard to say, it seems fine

**Comment by khanakia** [comment]
Check this video please and also localhost is pointed already to 127.0.0.1
https://github.com/nats-io/nats-server/assets/2174170/7fb8b0f1-f2fc-47d5-b8e8-38ed055428f4

**Comment by ripienaar** [comment]
can you show `nats context ls`? also `nats server check connection --no-context`

**Comment by khanakia** [comment]
```sh
➜  ~ nats context ls
╭───────────────────────────────────────────────────────────────────────────────╮
│                                 Known Contexts                                │
├──────────────────────────┬────────────────────────────────────────────────────┤
│ Name                     │ Description                                        │
├──────────────────────────┼────────────────────────────────────────────────────┤
│ nats_development*        │ Local user access for NATS Development instance    │
│ nats_development_service │ Local service access for NATS Development instance │
│ nats_development_system  │ System user access for NATS Development instance   │
╰──────────────────────────┴────────────────────────────────────────────────────╯
```

```sh
➜  ~ nats server check connection --no-context
OK Connection OK:connected to nats://127.0.0.1:4222 in 3.658417ms OK:rtt time 106.791µs OK:round trip took 0.000356s | connect_time=0.0037s;0.5000;1.0000 rtt=0.0001s;0.5000;1.0000 request_time=0.0004s;0.5000;1.0000
```

**Comment by ripienaar** [comment]
ok, so `nats context rm nats_development`, and then you did `nats ctx select` which selected `nats_development` and so it was trying to connect to that. `(`nats server run` does not automatically select its context as default)

**Comment by khanakia** [comment]
So what exactly should I do? I tried running `nats ctx select` and then `nats server check connection` still same error.

So it seems the tutorial on docs is wrong? If yes, we should update it.

**Comment by ripienaar** [comment]
`nats context rm nats_development`

**Comment by khanakia** [comment]
Already tried

https://github.com/nats-io/nats-server/assets/2174170/6ea18881-6e09-4ab4-bda8-24bb075bac18

**Comment by ripienaar** [comment]
Ok, so show `nats ctx ls` again please (to see what you did when you ran `nats ctx select`)

**Comment by khanakia** [comment]
Here you go

https://github.com/nats-io/nats-server/assets/2174170/5402f8cb-bf55-494f-a7fb-012220707971

**Comment by khanakia** [comment]
Ok i figured it out basically nats trying to connect on port `64379` but server is listening on `4222` so when i update the port on ` /Users/test/.config/nats/context/nats_development.json` and then run the below command it works

```
nats server check connection                                 
OK Connection OK:connected to nats://0.0.0.0:4222 in 1.780542ms OK:rtt time 173.25µs OK:round trip took 0.000888s | connect_time=0.0018s;0.5000;1.0000 rtt=0.0002s;0.5000;1.0000 request_time=0.0009s;0.5000;1.0000
```

However, i am not sure why it started on different port?

**Comment by ripienaar** [comment]
OK, you had an error when running `nats ctx rm ...` that you didnt show me.  Delete the file `~/.config/nats/context.txt`

**Comment by khanakia** [comment]
No there was no error and deleted the file again and same thing.

Ok i figured it out basically nats trying to connect on port `64379` but server is listening on `4222` so when i update the port on ` /Users/test/.config/nats/context/nats_development.json` and then run the below command it works

```
nats server check connection                                 
OK Connection OK:connected to nats://0.0.0.0:4222 in 1.780542ms OK:rtt time 173.25µs OK:round trip took 0.000888s | connect_time=0.0018s;0.5000;1.0000 rtt=0.0002s;0.5000;1.0000 request_time=0.0009s;0.5000;1.0000
```

However, i am not sure why it started on different port?

**Comment by ripienaar** [comment]
Because at some point you used `nats server run` and then later you ran `nats ctx select` and selected that setup as default connection.

**Comment by khanakia** [comment]
Not exactly if you check the docs here i was just following that tutorila https://docs.nats.io/running-a-nats-service/clients

Running `nats-server` command started on Port 4222 even in the tutorial it showing port 4222

**Comment by khanakia** [comment]
Thanks for your great help and patience and for helping me solve the issue.
