### ISSUE TITLE
Nats JetStream consumers performance

### ISSUE THREAD

**Issue by sskserk** [nats-io/nats-server#4799]
### Observed behavior

Hi Nats Guys,

we are facing extremely low performance of JetStream consumers.

The following fragment code processes approximately 100 messages per second.  Then it hangs for a couple of seconds.

```
_, err := jStreamContext.QueueSubscribe(
			"subject",
			"queue",
			func(msg *nats.Msg) {
				m, _ := msg.Metadata()
				log.Info(m.Sequence.Stream)

			},
			nats.DeliverLastPerSubject(),
		)
```

Corresposind jStreamContext is created as:
```
jsm, _ := nc.JetStream()
jStreamContext, err = jsm.AddStream(&nats.StreamConfig{
			Name:     "streamName",
			Subjects: []string{"subject"},
			NoAck:    true,
		})
```

We have an increased amount of JetStream messages which we can't process on time.

### Expected behavior

Messages at least pushed by server with a higher rate

### Server and client version

Nats 2.3.2

### Host environment

Linux/Ubuntu

**Comment by derekcollison** [comment]
Is the server version really 2.3.2? The latest server release is 2.10.5.

**Comment by sskserk** [comment]
# nats-server version
nats-server: v2.9.22


Client lib in go.mod:
require (
github.com/nats-io/nats.go v1.31.0
)

**Comment by derekcollison** [comment]
ok latest on 2.9.x is 2.9.24.

Can we get more information?

Why no ack on the stream?
Do you see memory growth in the server?
How fast are messages entering the stream? What rate for msgs and bytes?
How many different subjects?

Can you share output of `nats stream info` for the above stream?
What does `nats consumer report` show for that stream as well?

**Comment by sskserk** [comment]
Setting the "NoAck" to True is just an attempt to fight the issue. Have a theory that ACKs just require much time. In reality, the "NoAck" doesn't provide observable boost in performance.

**Comment by sskserk** [comment]
Nats stream info
```

              Subjects: A2S_NOTIFICATIONS.*
              Replicas: 1
               Storage: File

Options:

             Retention: Limits
       Acknowledgments: false
        Discard Policy: Old
      Duplicate Window: 2m0s
     Allows Msg Delete: true
          Allows Purge: true
        Allows Rollups: false

Limits:

      Maximum Messages: unlimited
   Maximum Per Subject: unlimited
         Maximum Bytes: unlimited
           Maximum Age: 1h0m0s
  Maximum Message Size: unlimited
     Maximum Consumers: unlimited

Cluster Information:

                  Name: tantor
                Leader: devops-multi8nodes-nats-px-02.tantorlabs.ru

State:

              Messages: 29,408
                 Bytes: 130 MiB
        First Sequence: 1 @ 2023-11-16 03:21:23 UTC
         Last Sequence: 29,408 @ 2023-11-16 03:46:05 UTC
      Active Consumers: 1
    Number of Subjects: 1


```

**Comment by sskserk** [comment]
Nats consumer info:
```
? Select a Stream A2S_NOTIFICATIONS
? Select a Consumer queue-metric
Information for Consumer A2S_NOTIFICATIONS > queue-metric created 2023-11-16T03:35:46+03:00

Configuration:

                    Name: queue-metric
        Delivery Subject: _INBOX.H1xRi0QIWDD7xYZZgmK0BU
          Filter Subject: A2S_NOTIFICATIONS.*
          Deliver Policy: Last Per Subject
     Deliver Queue Group: queue-metric
              Ack Policy: Explicit
                Ack Wait: 30.00s
           Replay Policy: Instant
         Max Ack Pending: 1,000
            Flow Control: false

Cluster Information:

                    Name: tantor
                  Leader: devops-multi8nodes-nats-px-02.tantorlabs.ru

State:

  Last Delivered Message: Consumer sequence: 12,824 Stream sequence: 30,267 Last delivery: -473.001ms ago
    Acknowledgment Floor: Consumer sequence: 12,824 Stream sequence: 30,267 Last Ack: -474.442ms ago
        Outstanding Acks: 0 out of maximum 1,000
    Redelivered Messages: 0
    Unprocessed Messages: 0
         Active Interest: Active using Queue Group queue-metric

```

**Comment by sskserk** [comment]
+ message rate provided by multiple publishers is about 100 msg/second

**Comment by derekcollison** [comment]
The no-ack for publishing into a stream is not recommended unless there is a specific reason to do so. Normally it allows the server to receive messages at a higher rate then can be stored in the stream. We track this internally and reserve the right to drop these messages if the server is under pressure.

For your consumer, does a normal non-queue group consumer with normal delivery work? Meaning eliminate the queue group and the deliver last by subject?

Also, possible to upgrade to 2.10.5?

**Comment by sskserk** [comment]
Upgraded:
```
# nats-server version
nats-server: v2.10.5

```

The following code works, but the message rate is still very low.  

```
		qSubscription, err := jStreamContext.Subscribe(
			subjectName,
			func(msg *nats.Msg) {
				m, _ := msg.Metadata()
				log.Info(m.Sequence.Stream)

				msg.Ack()
			},
			nats.DeliverLastPerSubject(),
		)
```

**Comment by sskserk** [comment]
NATS configuration file:

```
server_name: devops-multi8nodes-nats-px-01
# Client port of 4222 on all interfaces
port: 4222
monitor_port: 8222
logfile: /opt/logs/nats/nats.log
logfile_size_limit: 1GB
jetstream {
  store_dir=/opt/data/nats
}

cluster {
name: tantor
listen: devops-multi8nodes-nats-px-01:6222 
connect_retries: 10
authorization: {
user: natsAdmin #you can use any name
password: ****
timeout: 0
}
routes = [
    nats://natsAdmin:****@devops-multi8nodes-nats-px-02:6222
    nats://natsAdmin:****@devops-multi8nodes-nats-px-03:6222
]}
tls { #certificates location
cert_file: "/opt/nats/certs/fullchain.pem"
key_file: "/opt/nats/certs/privkey.pem"
timeout: 10.0
}
```

**Comment by sskserk** [comment]
NATS bench
```
# nats bench --stream="A2S_NOTIFICATIONS" "queue-metric.*" --server devops-multi8nodes-nats-px-02 --sub 1 --pub 1
12:43:01 Starting Core NATS pub/sub benchmark [subject=queue-metric.*, multisubject=false, multisubjectmax=100000, msgs=100,000, msgsize=128 B, pubs=1, subs=1, pubsleep=0s, subsleep=0s]
12:43:01 Starting subscriber, expecting 100,000 messages
12:43:01 Starting publisher, publishing 100,000 messages
Finished      0s [============================================================================================================================================================================] 100%
Finished      0s [============================================================================================================================================================================] 100%

NATS Pub/Sub stats: 1,499,928 msgs/sec ~ 183.10 MB/sec
 Pub stats: 1,099,047 msgs/sec ~ 134.16 MB/sec
 Sub stats: 754,115 msgs/sec ~ 92.06 MB/sec

```

**Comment by sskserk** [comment]
@derekcollison we just noticed that our messages have the 40K payload. Can it be the reason?

What is a recommended approach - many small messages or a few big?

**Comment by derekcollison** [comment]
Have you tried removing the log.Info line from your sample program to see if that has an affect?

**Comment by sskserk** [comment]
@derekcollison sorry for the wrong alarm,

finally we found the issue. There is a mixture of factors:
1) out publishers send messages of a big size
2) max ack pending parameter used by queue groups was set to a miserable values
3) slow messages processing logic

After fixing the mentioned issues we do observe the perfect processing pace. NATS JetStreaming is just a amazing!! 
Thank you for the good product!

**Comment by YashasAnand** [comment]
> The no-ack for publishing into a stream is not recommended unless there is a specific reason to do so. Normally it allows the server to receive messages at a higher rate then can be stored in the stream. We track this internally and reserve the right to drop these messages if the server is under pressure.
> 
> For your consumer, does a normal non-queue group consumer with normal delivery work? Meaning eliminate the queue group and the deliver last by subject?
> 
> Also, possible to upgrade to 2.10.5?

Good day @derekcollison , hope you're doing well. Could you pls eloborate on what do you mean by we reserve right to drop messages if server under pressure. At what point is it considered that server is under pressure, could you pls highlight this. Are we talking in terms of cpu usage of nats broker?

**Comment by wallyqs** [comment]
@YashasAnand first symptom would be that the servers start logging `high message lag` for your streams: https://github.com/nats-io/nats-server/blob/78d477f00de1d3a024ff3f20174137a82abfc0ad/server/jetstream_cluster.go#L8138-L8140
in later versions there are protections to prevent this overloading the server, you can try on v2.11 RC.5 and set this for example so that at most the server buffers 500K msgs for a stream before deciding to drop them:

```
jetstream {
  max_buffered_msgs = 500000
}
```

**Comment by MauriceVanVeen** [comment]
Publishing messages into a stream without any sort of back-pressure would eventually lead to memory use to keep growing. It either needs to hold all of them in-memory and eventually serve them (what's done in and prior to 2.10.x), or it should start protecting the system at some point and drop publishes (what will start happening to some degree in 2.11, like @wallyqs mentions above).

As long as you're using `js.Publish` or `js.PublishAsync` in reasonable batches and waiting for publish acknowledgements into the stream, it will ensure you're properly applying back-pressure and don't try to run faster than the stream can persist them.

**Comment by YashasAnand** [comment]
- Thank you for the very quick response @wallyqs and @MauriceVanVeen .  As you suggest to use batching with publish async method. In a real world application where we are not sure what kind of request per second rate might hit the application servers at any point, and user interactions with application has to be instantaneous, how would you suggest using batching @MauriceVanVeen

**Comment by MauriceVanVeen** [comment]
For example looking at `js.PublishAsync` and using `js.PublishAsyncComplete()` like in https://natsbyexample.com/examples/jetstream/limits-stream/go.
You could call `js.PublishAsync` in batches of 100 for example, and then wait for `js.PublishAsyncComplete()`. Then once that's finished, publish another batch of messages.
