### ISSUE TITLE
Alter Deduplication Key

### ISSUE THREAD

**Issue by AbstractiveNord** [nats-io/nats-server#4815]
### Proposed change

Find and implement a solution for comfortable deduplication key migration, also known as Nats-Msg-Id header.

### Use case

Migrating pattern for deduplication key in already existing stream.

### Contribution

Yes

**Comment by Jarema** [comment]
Hey!
Thanks for creating the proposal.

Can you elaborate?


You mean some way of adding dedup keys into existing stream? Or something else?

**Comment by AbstractiveNord** [comment]
> Hey! Thanks for creating the proposal.
> 
> Can you elaborate?
> 
> You mean some way of adding dedup keys into existing stream? Or something else?

For example, it can be secondary key which message may contain. If one or both of keys contains in Jetstream deduplication window, discard message as duplicate.

**Comment by jnmoyne** [comment]
Have you taken a look at this blog post? https://nats.io/blog/new-per-subject-discard-policy/

If you have all of the keys you want to deduplicate on as part (tokens) of the subject then you can use this method to do de-duplication.

**Comment by Jarema** [comment]
Considering that deduplication header is valid just for a duration of the dedup window, I don't think that there is justification for adding migration feature. Especially that having more than one deduplication header could impact performance of hot path and icrease memory footprint of deduplication mechanism.

What @jnmoyne suggested might be a really nice solution though!

**Comment by AbstractiveNord** [comment]
Thanks for advice, gonna test it. Issue was about migrating some legacy stuff, but discard policy looks to be a good solution.

**Comment by AbstractiveNord** [comment]
Considered as useless due to usage of PerSubjectDiscardPolicy.
