### ISSUE TITLE
I often encounter this error when consumption increases. "Consumer assignment for '$G > STREAM_NAME > z2Ffrb3s' not cleaned up, retrying"

### ISSUE THREAD

**Issue by VuongUranus** [nats-io/nats-server#4841]
### Observed behavior

I use Jetstream with a cluster of 3 nodes, during the day it still operates very stably, but when the number of consumers suddenly increases to about 20k, I get the error "Consumer assignment for '$G > STREAM_NAME > z2Ffrb3s' not cleaned up, retrying". I use ephemeral consumer.

### Expected behavior

.

### Server and client version

nats-server: v2.9.21

**Comment by VuongUranus** [comment]
I updated to version 2.10.6 but the problem seems to be worse.

**Comment by derekcollison** [comment]
Can you share information on your system setup, how many consumers, etc?

**Comment by VuongUranus** [comment]
My number of consumers is about 50k and this is the log I look at.
![image](https://github.com/nats-io/nats-server/assets/80895977/9cbbf68a-a03c-4f81-8c9e-e7ca80a1f75f)
My nats-server version is 2.10.6.

**Comment by derekcollison** [comment]
This is logged when the meta leader is not cleaning up an inactive consumer that has been deleted by another server.
Be good to know more about what your setup is and what your goals are here.

**Comment by VuongUranus** [comment]
The problem here is that when I encounter this warning, I cannot subscribe and get a context deadline exceeded error.

**Comment by derekcollison** [comment]
What do you mean exactly by can not subscribe?

We need more information on the main stream, the nature of the consumers, how many etc.

**Comment by VuongUranus** [comment]
This is my code for stream.
```go
		_, err = js.AddStream(&nats.StreamConfig{
			Name:              "NOTIFY_LOYALTY",
			Subjects:          []string{"NOTIFY_LOYALTY.>"},
			Storage:           nats.MemoryStorage,
			Retention:         nats.LimitsPolicy,
			MaxAge:            1 * time.Second,
			MaxMsgSize:        3 << 20, 
			Discard:           nats.DiscardOld,
			MaxMsgsPerSubject: 1,
			Replicas:          3,
			AllowDirect:       true,
			AllowRollup:       true,
		}, nats.MaxWait(5*time.Second))
```
and this is for ephemeral consumer
```go
sub, err := n.Subscribe(channelName, func(msg *nats.Msg) {
			f(msg.Data)
},
			nats.DeliverNew(),
			nats.BindStream(gocfg.CONFIG.NATS_STREAM_NAME),
			nats.IdleHeartbeat(1*time.Minute),
			nats.InactiveThreshold(5*time.Minute),
		)
```
The number of consumers when my problem occurred was about 40k.

**Comment by derekcollison** [comment]
When this happens, what does `nats server report jetstream` show? This needs to be run as the system user..

**Comment by VuongUranus** [comment]
<img width="940" alt="image" src="https://github.com/nats-io/nats-server/assets/80895977/03efa7c6-1c3f-4a35-a93c-b8c907b57270">

**Comment by VuongUranus** [comment]
This is the threshold I have problems with.

**Comment by VuongUranus** [comment]
And these are the logs I see on my nodes.
<img width="1121" alt="image" src="https://github.com/nats-io/nats-server/assets/80895977/8e686a72-07ad-4686-abd2-ba2d90535840">
<img width="1163" alt="image" src="https://github.com/nats-io/nats-server/assets/80895977/77a46e37-5ece-40a5-b1fb-6105f613d9b4">
![Uploading image.png…]()

**Comment by VuongUranus** [comment]
<img width="874" alt="image" src="https://github.com/nats-io/nats-server/assets/80895977/6cf18afc-ef14-443f-bb0e-d6a44fb018c6">
<img width="1076" alt="image" src="https://github.com/nats-io/nats-server/assets/80895977/3debad5d-5cb7-4ea5-919c-ddd9e41c4e5b">

**Comment by VuongUranus** [comment]
<img width="900" alt="image" src="https://github.com/nats-io/nats-server/assets/80895977/cda59f54-d9da-4d92-aa83-f0d335730bda">
<img width="1001" alt="image" src="https://github.com/nats-io/nats-server/assets/80895977/9e8ce459-2b44-4cbf-b6b0-d508dbc82683">
<img width="1012" alt="image" src="https://github.com/nats-io/nats-server/assets/80895977/def22f1e-462f-4437-a5fb-45b6b20df37b">
<img width="1006" alt="image" src="https://github.com/nats-io/nats-server/assets/80895977/362d39b3-aa68-43dc-bdc9-7339f458a746">
Now if I subscribe to the topic on stream GOCHAT_NOTIFY_LOYALTY I will get a context deadline exceeded error.

**Comment by VuongUranus** [comment]
<img width="1112" alt="image" src="https://github.com/nats-io/nats-server/assets/80895977/227caab8-ca39-4af6-8792-3b823bc62a9d">
This is `nats server ls` show

**Comment by VuongUranus** [comment]
<img width="1091" alt="image" src="https://github.com/nats-io/nats-server/assets/80895977/18da2698-549d-4969-91bf-9e44f9f7c634">

**Comment by VuongUranus** [comment]
I also checked the cpu, ram, dick, I/O but didn't see anything unusual.

**Comment by VuongUranus** [comment]
Before using version 2.9.21 this situation was even less.

**Comment by derekcollison** [comment]
ok so system not overloaded. 

How many consumers are being created and abandoned?

**Comment by VuongUranus** [comment]
NATS is used for high-load production environments. So the number of consumers created and deleted is large and continuous.

**Comment by derekcollison** [comment]
You might want to engage with us at Synadia for a system architecture review. Just to make sure you are getting the mnost out of the system.

**Comment by VuongUranus** [comment]
How can I contact you at Synadia

**Comment by derekcollison** [comment]
derek@synadia.com works.
