### ISSUE TITLE
Offline Messages Lost in NATS as MQTT Broker with clean_session=False

### ISSUE THREAD

**Issue by colorado666** [nats-io/nats-server#4849]
### Observed behavior

The client does not receive any messages that were published while it was offline.

### Expected behavior

I expect the client to receive messages that were published during its offline period upon reconnection, due to `clean_session` being set to `false`.

### Server and client version

- NATS Version: 2.10.5
- MQTT Client Library: paho.mqtt in Python version 3.9.6

### Host environment

- NATS Version: 2.10.5
- MQTT Client Library: paho.mqtt in Python version 3.9.6
- Operating System: MacOS 14.1

### Steps to reproduce

1. Configure NATS as an MQTT broker.
2. Connect an MQTT client to NATS with `clean_session` set to `false`.
3. Subscribe to a topic.
4. Disconnect the client.
5. Publish messages to the topic while the client is offline.
6. Reconnect the client.

Test Environment and Setup:

The test code is written in Python and uses the paho.mqtt client library.
The MQTT client connects with a fixed clientID.

I have also tested this setup using EMQX as an MQTT broker, where the behavior of receiving offline messages with clean_session set to false works as expected. This leads me to believe that the issue might be specific to the NATS configuration or its handling of MQTT sessions.

Python Test Code：

```python

import signal
import sys
import random

from paho.mqtt import client as mqtt_client

broker = '127.0.0.1'
port = 1883

topic = "/test/A"
# generate client ID with pub prefix randomly
# client_id = f'python-mqtt-{random.randint(0, 100)}'
client_id = f'python-mqtt-sub-002'

def connect_mqtt() -> mqtt_client:
    def on_connect(client, userdata, flags, rc):
        if rc == 0:
            print("Connected to MQTT Broker!")
        else:
            print("Failed to connect, return code %d\n", rc)

    client = mqtt_client.Client(client_id= client_id,   clean_session=False)
    client.on_connect = on_connect
    client.connect(broker, port)
    return client


def subscribe(client: mqtt_client):
    def on_message(client, userdata, msg):
        print(f"Received `{msg.payload.decode()}` from `{msg.topic}` topic")

    client.subscribe(topic)
    client.on_message = on_message


def run():
    client = connect_mqtt()
    subscribe(client)

    def signal_handler(sig, frame):
        # print("do unsub and by")
        # client.unsubscribe(topic)
        print("by")
        sys.exit(0)

    # 设置信号处理器
    signal.signal(signal.SIGINT, signal_handler)   # 处理 Ctrl+C
    signal.signal(signal.SIGTERM, signal_handler)  # 处理终止信号


    client.loop_forever()


if __name__ == '__main__':
    run()

```

**Comment by colorado666** [comment]
here is the publisher:

```python
import signal
import sys
import random
import time

from paho.mqtt import client as mqtt_client


# broker = "broker.emqx.io"
broker = '127.0.0.1'
port = 1883

topic = "/test/A"
# generate client ID with pub prefix randomly
# client_id = f'python-mqtt-{random.randint(0, 1000)}'
client_id = f'python-mqtt-pub-001'


def connect_mqtt():
    def on_connect(client, userdata, flags, rc):
        if rc == 0:
            print("Connected to MQTT Broker!")
        else:
            print("Failed to connect, return code %d\n", rc)

    client = mqtt_client.Client(client_id= client_id)
    client.on_connect = on_connect
    client.connect(broker, port)
    return client


def publish(client):
    msg_count = 0
    while True:
        time.sleep(1)
        msg = f"messages: {msg_count}"
        result = client.publish(topic, msg)
        # result: [0, 1]
        status = result[0]
        if status == 0:
            print(f"Send `{msg}` to topic `{topic}`")
        else:
            print(f"Failed to send message to topic {topic}")
        msg_count += 1


def run():
    client = connect_mqtt()

    def signal_handler(sig, frame):
        print("by")
        sys.exit(0)

    # signal handler
    signal.signal(signal.SIGINT, signal_handler) 
    signal.signal(signal.SIGTERM, signal_handler)


    client.loop_start()

    publish(client)


if __name__ == '__main__':
    run()
```

**Comment by levb** [comment]
@colorado666 I think your example is using the default QOS (quality of service) 0 which does not provide any message persistence (or redelivery) guarantees. Perhaps, try setting `qos=1` in both Publish and Subscribe calls? Or am I missing setting QOS somewhere?

See https://github.com/eclipse/paho.mqtt.python#single and https://github.com/eclipse/paho.mqtt.python#using-callback. Also [[MQTT-3.1.2-4]](https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718028).
