### ISSUE TITLE
create a default ObjectStore at startup?

### ISSUE THREAD

**Issue by yangjinheng** [nats-io/nats-server#4876]
### Proposed change

nats-server add startup parameters

-store --default_store "foo"

### Use case

My program calls CreateObjectStore every time it starts, but when the election fails, my program also fails because of CreateObjectStore.

I deployed a jetstream cluster with 2 nodes

**Comment by neilalexander** [comment]
A 2 node cluster will only be able to operate any replicated asset if both NATS Server nodes are running. If one of those nodes fails or goes down, the system can no longer reach a >50% quorum and therefore those replicated assets will stop working.

If you want to be able to tolerate a node failure, you need a 3 node cluster at least.

**Comment by yangjinheng** [comment]
thanks. this is great.
