### ISSUE TITLE
Creating a Stream with Subject '$JS.>' Breaks Stream Listing

### ISSUE THREAD

**Issue by sebholstein** [nats-io/nats-server#4882]
### Observed behavior

When creating a stream with the subject `$JS.>`, it breaks the stream listing afterwards (and maybe also more stuff, but I couldn't check this).

### Expected behavior

It's questionable if it should be even allowed to create a stream with this subject.

I would expect that the stream listing still works.

### Server and client version

Server version: The one thats running on `nats://demo.nats.io:4222` (sorry for breaking the Demo  System 😄  ) 
NATS CLI: v0.1.1

## Creating the stream

```bash
nats stream create  --context demo

[demo] ? Stream Name advisory
[demo] ? Subjects $JS.>
[demo] ? Storage file
[demo] ? Replication 1
[demo] ? Retention Policy Limits
[demo] ? Discard Policy Old
[demo] ? Stream Messages Limit -1
[demo] ? Per Subject Messages Limit -1
[demo] ? Total Stream Size -1
[demo] ? Message TTL -1
[demo] ? Max Message Size -1
[demo] ? Duplicate tracking time window 2m0s
[demo] ? Allow message Roll-ups No
[demo] ? Allow message deletion Yes
[demo] ? Allow purging subjects or the entire stream Yes
Stream advisory was created
```

## Listing the streams afterwards
```bash
nats stream ls --context demo
nats: error: could not list streams: server response is not a valid "io.nats.jetstream.api.v1.stream_list_response" message: /type: value must be "io.nats.jetstream.api.v1.stream_list_response"
missing properties: 'error'
/streams: expected array, but got null
```

**Comment by derekcollison** [comment]
This is actually valid but you need to set no pub ack on the stream to not interfere.

For instance if you want an audit trail.
