### ISSUE TITLE
Misleading error when interacting with JetStream

### ISSUE THREAD

**Issue by pmzajaczkowski** [nats-io/nats-server#4907]
### Observed behavior

When you try to interact with JetStream from a SYS account you'll get information about "context deadline exceeded". Which suggests some timeout, hence networking issues.

### Expected behavior

One should get some more informative error message - like "your account has no JetStream enabled". Specifically 'timeout' is not a good error to present in such a situation :)

### Server and client version

2.10.7

### Host environment

Cluster of 3 processes running on the same machine, with 3 different config files used to spawn these processes and form a cluster. NATS CLI used to perform operations like `nats stream ls` - which was causing this error message, when using a context with a SYS user (plaintext credentials from a config file). 

### Steps to reproduce

Create a nats-server with two accounts - system and regular one. Enable JetStream on a global level, but not on the account level. Try to execute (using sys account) `nats server list` - should succeed, try now `nats stream ls` - you should get "context deadline exceeded" error.

**Comment by derekcollison** [comment]
Resolved with https://github.com/nats-io/nats-server/pull/4910
