### ISSUE TITLE
Changes to subjects of interest due to subject mappings amendments are not propagated to leaf nodes

### ISSUE THREAD

**Issue by vinopm** [nats-io/nats-server#4934]
### Observed behavior

Subjects of interest which are communicated to leaf nodes are not updated accordingly when subject mappings are updated on the main NATS server.

Assume we have a main NATS node and a leaf node. Assume we have a publisher connected to the leaf node, who is publishing to 'source1'. Assume we also have a subscriber who is connected to the main NATS node and subscribing to 'target'.
e.g. if the mapping is set up to be `source1` -> `target`, and we then change the mapping to `source2` -> `target`.
A subscriber (connected to main NATS node) on 'target' should start receiving data from a publisher (connected) to leaf node that is publishing to 'source2'.

Starting up a subscriber (connected to the main NATS node) on the subject 'source2' (instead of 'target') forces data to start streaming from the publisher on the leaf node to the subscriber who is listening for 'target' subject data. No data is received on the subscriber to 'source2' as expected because the NATS server is mapping the messages from source2 to target. However, it appears that because there is a subscriber to 'source2', the data on the leaf node is actually published out (due to an interested party in this subject). When we remove the subscriber to 'source2', the subscriber to 'target' stops receiving data.

### Expected behavior

When the subject mapping in the server config is changed, and a reload signal is issued, the expected behaviour should be to inform the leaf nodes of the updated subjects of interest.

e.g. if the mapping is set up to be `source1` -> `target`, and we change the mapping to `source2` -> `target`.
A subscriber (connected to main NATS node) on target should start receiving data from a publisher (connected) to leaf node that is publishing to source2.

### Server and client version

Issue exists on v2.9.24, v2.10.7.

### Host environment

Container optimised OS
Repeated test locally on Mac OS 13.2.1.

### Steps to reproduce

1. Create a `server.conf` file:
```
port: 4222
server_name: test-server

debug: true
trace: true

leafnodes {
  port: 7422
}

mappings = {
	"source1": "target",
}
```

2. Create a `leaf.conf` file:
```
port: 12543
server_name: test-leaf

debug: true
trace: true

leafnodes {
	remotes = [
	    {
	      url: "nats://localhost:7422"
	    },
	]
}
```

3. Start up a nats server: `nats-server -c server.conf`
4. Start up a nats leaf node: `nats-server -c leaf.conf`
5. Verify existing subject mapping works end to end by
a. Starting up a publisher on the leaf node: `nats publish --server=nats://localhost:12543 "source1" "" --count=1000 --sleep=1s`
b. Starting up a subscriber on the main NATS node: `nats sub --server=nats://localhost:4222 'target'`
c. Expect to see messages arrive on the subscriber at a rate of once a second.
6. Update the `server.conf` file to amend the subject mappings on the main NATS server:
```
port: 4222
server_name: test-server

leafnodes {
  port: 7422
}

mappings = {
        "source2": "target",
}
```
7. Issue a reload signal so that the new config is picked up, ensuring the correct PID for the main server is used (not the leaf node): `nats-server --signal reload=<PID>`
8. Expect to see `Reloaded server configuration` in main NATS server log.
9. Expect to see publisher continue to publish data out (via progress bar).
10. Expect to see no data received by subscriber to `target` subject.
11. Stop publisher on `source1` subject, and change it to publish to `source2`: `nats publish --server=nats://localhost:12543 "source2" "" --count=1000 --sleep=1s`
12. Should see issue now where subscriber on `target` subject does not receive the published data that is being published to `source2`.
13. Further observation is that starting a new and separate subscriber on `source2` (on main NATS node) forces the other subscriber (on `target` subject) to start receiving data, even though this new subscriber on `source2` will not receive any data. Stopping this new subscriber on `source2` will again stop data being received by the other subscriber on `target`.
14. Restarting the leaf node forces the subject interest to propagate properly, and the subscriber on `target` will start seeing data from the publisher on `source2`, which is the intended behaviour.

----------------------------------------------------

Diving into NATS server code, it seems that upon issuing a config reload signal, the global account is recreated and therefore it loses context of the currently connected leaf nodes. Therefore it doesn't think it needs to inform any leaf nodes of the changes to subjects of interest due to the new subject mapping changes that have been applied. I would expect [this block](https://github.com/nats-io/nats-server/blob/main/server/accounts.go#L704-L714) of code to execute, however nleafs is always 0 since the account object has been initialised as part of the config reload.

If I run nats server in embedded mode, I am able to remove the old mapping and add the new one correctly. I call AddMapping() on the global account, and since the account object is not recreated and the mapping is applied directly on the existing account object, it actually propagates the change in subject interest properly to the leaf node as we should expect.

**Comment by derekcollison** [comment]
Thanks for the report. Will be in 2.10.8.

**Comment by vinopm** [comment]
Thanks for the quick turn around @derekcollison. We're currently on 2.9.x in production. Any chance for a backport as well please? :slightly_smiling_face:

**Comment by derekcollison** [comment]
No that will not happen, best to upgrade to 2.10.8 when it is released.
