### ISSUE TITLE
No official Docker image for 2.10.9 release

### ISSUE THREAD

**Issue by svenfoo** [nats-io/nats-server#4953]
### Observed behavior

https://nats.io/download/ lists **2.10.9** as the latest release. However https://hub.docker.com/_/nats only has **2.10.8**.

### Expected behavior

Expecting an official Docker image for the latest stable release.

### Notes

Probably just an oversight that can be fixed easily. Just pointing this out here so that others see that it has already been reported.

**Comment by ripienaar** [comment]
Official images are built by the Docker team, it takes a while.

**Comment by svenfoo** [comment]
Docker images are now available. Kudos to the Docker team.
