### ISSUE TITLE
Pedantic mode for Stream and Consumer configuration APIs

### ISSUE THREAD

**Issue by ripienaar** [nats-io/nats-server#4959]
### Proposed change

Today there is a hierarchy of overrides/defaults for some properties of streams and consumers:

 * account `ack_pending` -> consumer default
 * stream `inactive_threshold` -> consumer `inactive_threshold`
 * stream `max_ack_pending` -> consumer `max_ack_pending`

Generally the behavior of these are summarized as `Maximum value for max_ack_pending for consumers of this stream. Acts as a default when consumers do not set this value.`.

This complicates matters for systems like Terraform/NACK and other desired state systems since they cant set good defaults and cant know whats appropriate defaults are and in some cases have their configuration altered - resulting in a desired state that can never be met.

Note this is not for all cases of setting defaults, we have many defaults like JsAckWaitDefault, JsDeleteWaitTimeDefault and JsDefaultMaxAckPending these are easily handled by just always supplying values from these systems and we already do that without problem.  The concern are the ones that sometimes do and sometimes don't need values and those where the value is dynamically supplied by users in account/stream configs. At present as far as I am aware it is only the 3 above.

Lets add a flag to the following API calls that would instead of all the dynamic defaults and potential changing of configs would:

 * Fail if one of these dynamic default/inherited settings are not set rather than set its default
 * Never change settings to be within limits but rather fail

List of APIs:

 * `$JS.API.STREAM.UPDATE` - `io.nats.jetstream.api.v1.consumer_create_request`
 * `$JS.API.STREAM.CREATE` - `io.nats.jetstream.api.v1.consumer_create_request`
 * `$JS.API.CONSUMER.CREATE.>` - `io.nats.jetstream.api.v1.consumer_create_request`
 * `$JS.API.CONSUMER.DURABLE.CREATE.>` - `io.nats.jetstream.api.v1.consumer_create_request`

We call it `Strict` and it's just a boolean to opt into this behavior

### Use case

Keep supporting TF/Nack etc

**Comment by bruth** [comment]
@Jarema you can decide who works on this, but this will be in scope for 2.11. The plan is to only propagate this new field to jsm.go in order to support the TF provider and NACK. It does not need to be added to clients.

**Comment by Jarema** [comment]
Sure, that makes senes to scope it like that.

**Comment by ripienaar** [comment]
Fields for which current defaulting behavior is fine:

Streams defaulting that is fine:

 * Default to file store
 * Default to replicas = 1 when clustered
 * Default max_msgs=-1
 * Default max_msgs_per_subject=-1
 * Default max_msg_size=-1
 * Default max_consumers=-1
 * Default duplicate_window only when it defaults to 2 minutes, when changing based on max age etc, error if pedantic

Some random notes on other settings:

 * MirrorDirect should error instead of defaulting when mirrored stream has direct in pedantic mode

Consumers defaulting that is fine:

 * Default max_waiting to JSWaitQueueDefaultMax
 * Default ack_wait to JsAckWaitDefault
 * Default max_deliver to -1
 * Default  `max_ack_pending` to JsDefaultMaxAckPending but for other scenarios error

Notes on other settings:

 * `ack_wait` changing when backoff is specified should error when pedantic and not change to backoff[0]
 * `max_ack_pending` should error and not inherit silently from stream  (see setConsumerConfigDefaults)
 * `inactive_threshold` should erorr and not inherit silently from stream (see setConsumerConfigDefaults)
 * `max_batch` should not inherit

**Comment by Jarema** [comment]
This is scheduled to be done between 5th and 16th of February.
I will be responsible for delivering it.

**Comment by Jarema** [comment]
Actively working on it.
