### ISSUE TITLE
When calling shutdown func with os.Exit

### ISSUE THREAD

**Issue by ccb1900** [nats-io/nats-server#4999]
### Observed behavior

I got nats server as embbed at goroutine.

when  enter ctrl c,it exit.my other goroutine not exit completely.

here,is it ok `return` instead.

<img width="982" alt="image" src="https://github.com/nats-io/nats-server/assets/3932305/f67f39ad-892b-4d88-9d1c-91ef710c6285">

### Expected behavior

graceful down

### Server and client version

2.10.9

### Steps to reproduce

as above

**Comment by ripienaar** [comment]
You should probably set the `NoSigs` option and then shut it down when you're ready based on your own signal handler.

**Comment by ccb1900** [comment]
> You should probably set the `NoSigs` option and then shut it down when you're ready based on your own signal handler.

Thank you.It works.
