### ISSUE TITLE
Send messages on MQTT client connected and disconnected 

### ISSUE THREAD

**Issue by rafsawicki** [nats-io/nats-server#5042]
### Proposed change

Some MQTT brokers have a built in mechanism of sending messages when a client connects or disconnects (e.g. [EMQX](https://www.emqx.io/docs/en/latest/observability/mqtt-system-topics.html#client-online-and-offline-events)). Other have a possibility of creating extensions and publishing such messages manually (e.g. [VerneMQ](https://docs.vernemq.com/plugin-development/sessionlifecycle#on_client_wakeup)). I want to know when a client connects or disconnects, but I don't see an option to do that in NATS, as I don't see any messages during those events (other than the first connect, for storing client information). It would be good if such messages would either be emitted automatically, or NATS would provide an extension mechanism to be able to do that manually.

### Use case

In my application, I keep track of each device online status based on connection status to the broker. Since I'm not able to find any client connection or disconnection messages, it's difficult to switch over to using NATS as a MQTT broker.

Additionally, having such messages (especially having them persisted) serves an audit purpose and allows to detect and fix devices that are having trouble keeping the connection and disconnect frequently.

### Contribution

I don't have enough golang knowledge for any meaningful contribution.

**Comment by derekcollison** [comment]
NATS sends events for connect and disconnect already..

https://github.com/nats-io/nats-server/blob/main/server/mqtt_test.go#L6264

**Comment by rafsawicki** [comment]
Thank you for pointing met out into the right direction. I didn't found those specific on MQTT pages, and I incorrectly assumed that such messages would be visible when subscribing to wildcard subscription without access to a SYS tree, since a few other MQTT audit messages are emitted there even without it.
