### ISSUE TITLE
Pass token via websockets cookie for auth callout

### ISSUE THREAD

**Issue by jonaskello** [nats-io/nats-server#5047]
### Proposed change

Make it possible to use a cookie to pass the token to the auth callout. 

Today if I try this config:

```
accounts {
  AUTH { users: [ { user: auth, password: auth } ] }
  SYS {}
  my-app {}
}

authorization {
  auth_callout {
    issuer: XXXXXXX
    account: AUTH
    users: [ auth ]
  }
}

system_account: SYS

# Client port of 4222 on all interfaces
port: 4222

# Limit the payload
max_payload: 20Mb

# HTTP monitoring port
monitor_port: 8222

# Websocket
websocket 
{
     port: 9222
     no_tls: true
     compression: true
     jwt_cookie: "my_jwt_cookie_name"
}
```

I get this error:

```
nats-server: trusted operators or trusted keys configuration is required for JWT authentication via cookie "my_jwt_cookie_name"
```

Today the javascript browser client connects like this and the `authToken` string is passed to the auth callout service:

```js
    const conn = await Nats.connect({ servers: servers, token: authToken });
```

What I would want is to skip the `token` parameter and have the value of the cookie named "my_jwt_cookie_name" passed as the token in this code:

```js
    const conn = await Nats.connect({ servers: servers }); // token is implicitly set from cookie value
```

### Use case

A browser based application that gets a cookie from a backend that contains a custom token that you want to validate in an auth callout service. Today we need to send the token value in the javascript client as parameter. We could still read it in the browser from a cookie but that means we cannot use a httpOnly cookie which will make it less secure.

### Contribution

The check seems to be done here:

https://github.com/nats-io/nats-server/blob/74a2fbda355633f441156d0a7ce3dd86cf3c5ebe/server/websocket.go#L1003

I will probably not be able to fix this myself.

**Comment by aricart** [comment]
@jonaskello the server currently has the websocket configuration, that allows configuring the cookie as you have seen:
```
# Name for an HTTP cookie, that if present will be used as a client JWT.
    # If the client specifies a JWT in the CONNECT protocol, this option is ignored.
    # The cookie should be set by the HTTP server as described [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies).
    # This setting is useful when generating NATS `Bearer` client JWTs as the
    # result of some authentication mechanism. The HTTP server after correct
    # authentication can issue a JWT for the user, that is set securely preventing
    # access by unintended scripts. Note these JWTs must be [NATS JWTs](https://docs.nats.io/nats-server/configuration/securing_nats/jwt).
    #
    # jwt_cookie: "my_jwt_cookie_name"
```

What this means is if your HTTP server sets the cookie, the server will honor it. As a matter of design, this is intended so HTTP servers set the cookie as `Secure` and `HttpOnly` and thus preventing the script from actually even looking at it.

The reason for an option in the client to set it for you is not viable is that such functionality is not possible in the _standard_ websocket API. Browser can telegraph it if it is available, but the client itself cannot manage them or set them for you.

**Comment by jonaskello** [comment]
Yes, I want the HTTP server to set the cookie as `Secure` and `HttpOnly` and the script should not be able to look at it. This part is exactly correct.

My request is to have the cookie value forwarded to my auth callout service which NATS will call when the client connects via websockets to NATS. So the script should never see the cookie, it should just pass it along to the auth callout service.

**Comment by aricart** [comment]
@jonaskello, I'm looking into it, but it looks a bit out of scope. Currently, the cookie feature requires that the server be configured using "operator mode" and the authentication presented during `CONNECT` not have a JWT. 

Delegated authentication also has the requirement that the client connect to the server using a JWT which places the connection in the callout's account.

Removing this restriction doesn't solve the problem because the authentication process will clear the JWT on websocket connections if the server is not configured in operator mode. Thus there are a few contradicting requirements in the way of making this work.

Will discuss with @derekcollison.

**Comment by aricart** [comment]
@jonaskello did some additional testing, and if you use delegated authentication, the bearer token will be added correctly for WebSocket connections. This is the correct behavior - that is, the credentials to connect to the authcallout can be set by the HTTP server as a cookie, and the client will transparently use that. If you need to provide additional information to specify additional user information, you should place that information on the "token" part of the auth. This way, the HTTP configuration does connection to the callout, but token part is done by your code using any API key that your callout can use to single out the client.

**Comment by jonaskello** [comment]
This sounds interesting but I'm not sure what "use delegated authentication" means here. Does it simply mean using [auth callout](https://docs.nats.io/running-a-nats-service/configuration/securing_nats/auth_callout) or are you refering to some other/additional way of delegating authentication?

**Comment by jonaskello** [comment]
@aricart I tried `token_cookie` config in the nightly build and it works perfectly! This is awesome, thank you!

So this issue is solved. Once I got passed this issue I realised there is one final thing holding us back from only using httpOnly cookie. I detailed it in [this discussion](https://github.com/nats-io/nats-server/discussions/5143).

**Comment by aricart** [comment]
> @aricart I tried `token_cookie` config in the nightly build and it works perfectly! This is awesome, thank you!
> 
> So this issue is solved. Once I got passed this issue I realised there is one final thing holding us back from only using httpOnly cookie. I detailed it in [this discussion](https://github.com/nats-io/nats-server/discussions/5143). 

The http only I believe is nothing we handle. This is just part of the cookie. So it should just work, unless I am missing something

**Comment by jonaskello** [comment]
@aricart Yes it fully works, and the httpOnly is set by the server as you say. So this issue is fully resolved and can be closed.

What I was referring to is a different problem that I bumped into once we now have the httpOnly cookie working during auth callout. It is about identifying the websocket client in subsequent rpc calls, for example by adding the identity of it to the subject. Having the httpOnly cookie is very good for security but it prevents the client from reading the value in it and adding it to the subject during rpc calls.. So I want to find some other way to do this part. This new problem is outlined more detailed in the github discussion I linked above, would be great to have your comments in that discussion too.

**Comment by aricart** [comment]
On the request subject, include a client id meaningful to the app. The client should only be able to publish to such clamped subjects.

**Comment by mikibella** [comment]
Hey guys is this also possible with the `token_cookie ` configuration added inside the nigthly?
What exactly does `trusted operators or trusted keys configuration is required for JWT authentication via cookie` mean?

**Comment by bella-wmi** [comment]
Hey guys is this also possible with the `token_cookie` configuration added inside the nigthly?
What exactly does `trusted operators or trusted keys configuration is required for JWT authentication via cookie` mean? Do i need a signed operator and all accounts signed by the operator?

**Comment by LautaroJayat** [comment]
@bella-wmi 
> Hey guys is this also possible without the token_cookie configuration added inside the nigthly?
What exactly does trusted operators or trusted keys configuration is required for JWT authentication via cookie mean? Do i need a signed operator and all accounts signed by the operator?

This feature is not included in v2.10, but is already merged to main.
If you wan to give it a try you can use (synadia/nats-server:nightly)[https://hub.docker.com/layers/synadia/nats-server/nightly/images/sha256-b0437162b78cb5696f89c604e5d448722fdd3f68355acb6425fd46bd45c677c5?context=explore] (see https://beta-docs.nats.io/download/server#nightly-builds)

**Comment by MamaMia777** [comment]
> [@aricart](https://github.com/aricart) I tried `token_cookie` config in the nightly build and it works perfectly! This is awesome, thank you!
> 
> So this issue is solved. Once I got passed this issue I realised there is one final thing holding us back from only using httpOnly cookie. I detailed it in [this discussion](https://github.com/nats-io/nats-server/discussions/5143).

What is proper way to access this cookie in auth_callout ?

**Comment by MamaMia777** [comment]
When this feature will be available on vanilla nats docker image ?
