### ISSUE TITLE
NATS JetStream slowing down over time

### ISSUE THREAD

**Issue by stefanLeo** [nats-io/nats-server#5098]
### Observed behavior

We see a constant degradation of E2E Latency over time (~24 test period) when having a constant load on the a single jetstream.
The degradation mainly can be seen in outliers - so the avg latency is not so much affected yet, but that will continue to degrade over time as well.

We see that, based on our latency Grafana DBs, that the degradtion comes from the producers side - The producer waits until a publish call is confirmed by the NATS cluster and then goes on. This duration is also monitored as a histogram as follows:
`lastPublish = System.nanoTime();`
`PublishAck pa = js.publish(msg, opts);`
`long deltaNano = System.nanoTime() - lastPublish;`

streamTimeout for publishoptions is set to 2 secs. deltaNano is monitored as a promehteus histogram.

Garafan DB as a proof: 
E2E Latency:
![image](https://github.com/nats-io/nats-server/assets/2332240/1c17b4ff-ca09-4bef-b04d-55df12011ca2)
Producer Latency:
![image](https://github.com/nats-io/nats-server/assets/2332240/51fdca18-e5a3-4ae4-8df8-6bb1cc0dc40f)

Note: In the middle (~18:00) we stopped prod & consumers to verify if the JetStream recovers when the load is gone. Apparently it did not as the latency outliers remained where the were when restarting producers/consumers. 
Note 2: We then started the exact same test again with another JetStream without restarting the NATS cluster. The latency was again fine in the beginning and followed the patterns as can be seen above. 
Note 3: Unfornately the producer latency histogram is capped in that test which is why the increase then is not visible any longer in the +INF bucket.

### Expected behavior

There is no continuous degration of E2E Latency over time. 

### Server and client version

Server. = 2.10.10
Client = Java v2.17.3

### Host environment

Openshift using NATS provided HELM charts

### Steps to reproduce

Single Jetstream on a 3 node cluster with R3.
10 Producers, 10 Consumers and 10 subjects (like test.1, test.2, test.10). Every producer/consumer form a pair (1:1 relation via subject). 
Producers provide messages in a constant rate of 100msg/sec. 

JetStream settings:
` StreamConfiguration sc = StreamConfiguration.builder()`
`                .name(streamName) ` 
`               .storageType(StorageType.Memory)`
`                .subjects(subjects)`
`                .retentionPolicy(RetentionPolicy.Limits)`
`                .discardPolicy(DiscardPolicy.Old)`
`                .replicas(3)`
`                .maxAge(Duration.ofMinutes(10))`
`                .maxBytes(500_000_000) //500MB`
`                .maxMessagesPerSubject(100_000)`
`                .build();`

Consumer Configuration:
` ConsumerConfiguration.Builder consumerBuilder = ConsumerConfiguration.builder()`
`                    .numReplicas(3)`
`                    .ackPolicy(AckPolicy.Explicit)`
`                    .name(exArgs.consumerName)`
`                    .ackWait(Duration.ofSeconds(5))`
`                    .inactiveThreshold(Duration.ofSeconds(60))`
`                    .filterSubject(exArgs.subject)`
`                    .deliverPolicy(DeliverPolicy.All)`
`                    .memStorage(true);`

Consumer is a pull consumer using "fetch"
`try (FetchConsumer consumer = consumerContext.fetch(consumeOptions)) {`

The paylod of messages is random and has the format:
SequenceNr + space + CurrentTimeMillis + space + String with 100 random characters 
UTF-coded to byte array.

**Comment by neilalexander** [comment]
Do you see an increase in CPU usage or memory utilisation on the NATS Server pods as the duration increases?

**Comment by stefanLeo** [comment]
![image](https://github.com/nats-io/nats-server/assets/2332240/53a7d16f-b25b-40f4-8e66-17a88c01a610)
slightly from the NATS Dashboard.
The CPU on the worker nodes is quite low overall... 
![image](https://github.com/nats-io/nats-server/assets/2332240/1b18d16d-32cb-4033-b65c-9ad157acfa4e)

**Comment by stefanLeo** [comment]
JetStream DB:
![image](https://github.com/nats-io/nats-server/assets/2332240/fc869983-ee74-4872-9459-3242c826d861)

**Comment by stefanLeo** [comment]
Short update from our side: 
We did some further tests and insights:
1) When the outliers occur, all producers are blocked at the same point in time.
2) We retested with just a single producer and consumer but the same overall msg load. Result is the same, with the difference that the outliers are less. This is expected as the NATS Server blocks new msg publishes and in this case it only blocks a single (threaded) producer. 

I.e. something inside the NATS Server's jetstream (some sort of jetstream wide operation) blocks msg ingestion at defined timeslots and this blocking operation gets worse over time.

**Comment by derekcollison** [comment]
Would you happen to have a test program that you could share that shows the issue?

**Comment by stefanLeo** [comment]
Sure. You can find my code here: https://github.com/stefanLeo/nats-example-client

I also uploaded the compiled and shaded jars if that helps you using it.

We start it as follows:
java -jar io-nats-test-0.1-PROD.jar -s nats://XYZ -mcnt 8000000 -rate 1000 -sub nats.test -promProd 9400 -strm natstest
java -jar io-nats-test-0.1-CONSUMER.jar -s nats://XYZ -mcnt 8000000 -rate 1000 -sub nats.test -promProd 9401 -strm natstest

mcnt = number of messages until test is stopped. 
rate = nubmer of msgs per sec
sub = subject
promPort = Prometheus port used for creating the Granafa histogram Heatmaps
strm = stream name

The code is basically taken over from Nats.Java Examples. 

[Uploading NATS_Clients.zip…]()

**Comment by stefanLeo** [comment]
Just a hint - we enabled profiling and think we might have tracked it down to memstores compact method.

**Comment by stefanLeo** [comment]
@derekcollison : I can confirm now that compact method causes the issue. I wrote a go test (see attached) that basically stresses the memstore by adding a lot of msgs and then enforces compact after each iteration. 
You can see that the time compact takes go up with every iteration to very high numbers.

A simple fix is to change the compact function to not always iterate back to 0. This fixes the test but apparently will still cause the memory leak of the map as delete does not really delete. I did this simple fix in my local fork only to confirm my hypothesis. 

You can see my changes and a test also in my private fork: 
https://github.com/stefanLeo/nats-server
https://github.com/stefanLeo/nats-server/commit/76fb7cc496b4cd583823429bba52c356438df95f

The test routine itself is again not very nice but shows the problem. Ideally you could count and return the nulls msgs within the loop, as this should acutally always be 0 for the purpose of this test... 
`if sm := ms.msgs[seq]; sm != nil {`

**Comment by derekcollison** [comment]
Will take a look. Thanks..

**Comment by derekcollison** [comment]
Great catch, made some minor suggestions on your branch. Feel free to post that as a PR when you are ready!

Thanks!

**Comment by derekcollison** [comment]
If you prefer we do this, we could re-use your tests etc, but want to make sure we give credit where credit is due!

**Comment by stefanLeo** [comment]
I will create the PR right now ;-) thx for the feedback!

**Comment by stefanLeo** [comment]
https://github.com/nats-io/nats-server/pull/5116 
Thank you again for having a look!
