### ISSUE TITLE
Changes to subjects of interest due to subject mappings amendments are not propagated to leaf nodes

### ISSUE THREAD

**Issue by jarretlavallee** [nats-io/nats-server#5099]
### Observed behavior

Subjects of interest which are communicated to leaf nodes are not updated accordingly when subject mappings are updated on the main NATS server.

Assume we have a main NATS node and a leaf node. Assume we have a publisher connected to the leaf node, who is publishing to 'source1'. Assume we also have a subscriber who is connected to the main NATS node and subscribing to 'target'.
e.g. if the mapping is set up to be `source` -> `target1`, and we then change the mapping to `source` -> `target2`.
A subscriber (connected to main NATS node) on 'target2' should start receiving data from a publisher (connected) to leaf node that is publishing to 'source'.

A similar issue was fixed in #4934, however, the issue exists for the value of the mappings.

The issue still exists when changing from 
```
mappings = {
 "source": "target1",
}
```

to

```
mappings = {
 "source": "target2",
}
```

### Expected behavior

When the subject mapping in the server config is changed, and a reload signal is issued, the expected behaviour should be to inform the leaf nodes of the updated subjects of interest.

e.g. if the mapping is set up to be `source` -> `target1`, and we change the mapping to `source` -> `target2`.
A subscriber (connected to main NATS node) on `target2` should start receiving data from a publisher (connected) to leaf node that is publishing to `source`.
behavior

### Server and client version

nats-server v2.10.11

### Steps to reproduce

See the steps in #4934.

1. Create a server.conf file:

```
port: 4222
server_name: test-server

debug: true
trace: true

leafnodes {
  port: 7422
}

mappings = {
	"source": "target1",
}
```

2. Create a leaf.conf file:
```
port: 12543
server_name: test-leaf

debug: true
trace: true

leafnodes {
	remotes = [
	    {
	      url: "nats://localhost:7422"
	    },
	]
}
```
3. Start up a nats server: `nats-server -c server.conf`
4. Start up a nats leaf node: `nats-server -c leaf.conf`
5. Verify existing subject mapping works end to end by
  a. Starting up a publisher on the leaf node: `nats publish --server=nats://localhost:12543 "source" "" --count=1000 --sleep=1s`
  b. Starting up a subscriber on the main NATS node: `nats sub --server=nats://localhost:4222 'target1'`
  c. Expect to see messages arrive on the subscriber at a rate of once a second.

6. Update the server.conf file to amend the subject mappings on the main NATS server:

```
port: 4222
server_name: test-server

leafnodes {
  port: 7422
}

mappings = {
        "source": "target2",
}
```
7. Issue a reload signal so that the new config is picked up, ensuring the correct PID for the main server is used (not the leaf node): `nats-server --signal reload=<PID>`
8. Expect to see Reloaded server configuration in main NATS server log.
9. Expect to see publisher continue to publish data out (via progress bar).
10. Expect to see no data received by the subscriber to `target1` subject.
11. Start up a subscriber on the main NATS node: `nats sub --server=nats://localhost:4222 'target2'`
12. Start publisher on source subject, and change it to publish to source: `nats publish --server=nats://localhost:12543 "source2" "" --count=1000 --sleep=1s`
13. Expect to see data received by the subscriber to `target2` subject

**Comment by derekcollison** [comment]
This test I just wrote in the server directory in top of main passes. Looks like we may have failed to pull this in to the 2.10.11 release. /cc @wallyqs @bruth 

```go
// https://github.com/nats-io/nats-server/issues/5099
func TestLeafNodeServerReloadSubjectMappingsWithSameSubject(t *testing.T) {
	stmpl := `
		listen: 127.0.0.1:-1
		server_name: test-server
		mappings = { "source": "target1" }
		leaf { listen: 127.0.0.1:-1 }
	`
	conf := createConfFile(t, []byte(stmpl))
	s, o := RunServerWithConfig(conf)
	defer s.Shutdown()

	tmpl := `
		listen: 127.0.0.1:-1
		server_name: test-leaf
		leaf {
			remotes: [ {
				urls: [ nats-leaf://127.0.0.1:{LEAF_PORT} ]
			} ]
		}
	`
	tmpl = strings.Replace(tmpl, "{LEAF_PORT}", fmt.Sprintf("%d", o.LeafNode.Port), 1)
	lConf := createConfFile(t, []byte(tmpl))
	l, _ := RunServerWithConfig(lConf)
	defer l.Shutdown()

	checkLeafNodeConnected(t, l)

	// Create our subscriber.
	nc := natsConnect(t, s.ClientURL())
	defer nc.Close()
	sub1 := natsSubSync(t, nc, "target1")
	sub2 := natsSubSync(t, nc, "target2")
	natsFlush(t, nc)

	// Create our publisher.
	ncl := natsConnect(t, l.ClientURL())
	defer ncl.Close()
	// Publish our message.
	ncl.Publish("source", []byte("OK"))

	// Make sure we receive it.
	checkSubsPending(t, sub1, 1)
	// Make sure the other does not.
	checkSubsPending(t, sub2, 0)

	// Now change mapping, but only the "to" subject, keeping same "from"
	reloadUpdateConfig(t, s, conf, strings.Replace(stmpl, "target1", "target2", 1))

	// Publish our new message.
	ncl.Publish("source", []byte("OK"))

	// Make sure we receive it.
	checkSubsPending(t, sub2, 1)
	// Make sure the other does not.
	checkSubsPending(t, sub1, 1)
}


```
