### ISSUE TITLE
Add a way to reduce (or silence) the error logs when a route goes down

### ISSUE THREAD

**Issue by DavidCockerill** [nats-io/nats-server#5114]
### Proposed change

With our Nats setup it is not unusual for a route to go down. 

When a route becomes unresponsive there are a lot of continuous error logs:
`Error trying to connect to route (attempt 1): dial tcp ... connect: connection refused`

These logs are helpful but if a route is down for more than a short while our logs can get very bloated. 

It would be great if they were logged less often or could be silenced?

### Use case

To prevent our logs from getting spammed.

**Comment by kozlovic** [comment]
You should have a look at `connect_error_reports` and `reconnect_error_reports` configuration parameters [here](https://docs.nats.io/running-a-nats-service/configuration#monitoring-and-tracing).
