### ISSUE TITLE
improvements in leaf loop detection logic

### ISSUE THREAD

**Issue by borjaetxebarria** [nats-io/nats-server#5117]
### Observed behavior

loop detection logic in leaf nodes can be defeated in simple setups   
Setup:  
B --[leaf]--> A  
C --[leaf]--> A    
C --[leaf] --> B

with the right permissions and startup sequence, the loop is not detected

### Expected behavior

loop is detected

### Server and client version

2.10.11

### Host environment

docker compose

### Steps to reproduce

see attached docker compose files and instructions to reproduce the issue
[leaf-loops.tgz](https://github.com/nats-io/nats-server/files/14368289/leaf-loops.tgz)

**Comment by derekcollison** [comment]
Appreciated, but I mean a server test. Running inside the system tests under server directory. Those are most actionable. In absence the server team needs to write them almost as a first step.

**Comment by derekcollison** [comment]
I can write the test, will queue up for my weekend work.

**Comment by derekcollison** [comment]
With a simple server test doing what you are doing, C detects the loop right away, so must be timing based. Will slow down the starting of the servers and see if that trips it.

**Comment by derekcollison** [comment]
If I delay between B and A for 2s I start to see it.

**Comment by derekcollison** [comment]
ok the bug is when C connect to A first before B does. I can use staggered reconnect intervals to force this.
