### ISSUE TITLE
Compatibility with MQTT Sparkplug B

### ISSUE THREAD

**Issue by bruth** [nats-io/nats-server#5150]
### Proposed change

Add remaining featuers to the NATS MQTT layer to satisfy the requirements of Sparkplug B compatibility. The minimum requirements include:

- QoS 0 and 1 ✅ 
- Retained Messages ✅ 
- Last Will and Testament

There is a Sparkplug technology compatibility kit (TCK) available [here](https://sparkplug.eclipse.org/compatibility/get-listed/#download-run-and-pass-the-tck) which can be downloaded and used to validate compatibility.

### Use case

Sparkplug B is a commonly used protocol in IIoT to ensure interoperability. Devices/clients that rely on this protocol will require the MQTT broker they are using to be compliant with the requirements of the protocol.

**Comment by levb** [comment]
Implemented with https://github.com/nats-io/nats-server/pull/5241

TCK result off `main`:
<img width="661" alt="image" src="https://github.com/nats-io/nats-server/assets/1187448/93fdf763-3cc4-4f62-8a79-0ab69ca417ff">
