### ISSUE TITLE
panic: runtime error: index out of range [-1]

### ISSUE THREAD

**Issue by jeremylowery** [nats-io/nats-server#5167]
### Observed behavior

I encountered this going through the tutorial. When have two subscribers publishing a message causes nats server to crash with the following panic.
<pre>
$ nats-server
[28028] 2024/03/03 14:46:09.770143 [INF] Starting nats-server
[28028] 2024/03/03 14:46:09.770173 [INF]   Version:  2.10.11
[28028] 2024/03/03 14:46:09.770175 [INF]   Git:      [5fc6051]
[28028] 2024/03/03 14:46:09.770177 [INF]   Name:     NAEV2I4BY4R24YLQNE5VVCAK4IEUVBRWYENFTQPE3RZI6QF6JGQ5AT34
[28028] 2024/03/03 14:46:09.770178 [INF]   ID:       NAEV2I4BY4R24YLQNE5VVCAK4IEUVBRWYENFTQPE3RZI6QF6JGQ5AT34
[28028] 2024/03/03 14:46:09.770571 [INF] Listening for client connections on 0.0.0.0:4222
[28028] 2024/03/03 14:46:09.770739 [INF] Server is ready

panic: runtime error: index out of range [-1]

goroutine 82 [running]:
github.com/nats-io/nats-server/v2/server.(*client).processMsgResults(0xa6a2000, 0xa52c000, 0xa5aa240, {0xa6ac26b, 0x16, 0x195}, {0x0, 0x0, 0x0}, {0xa6ac233, ...}, ...)
        github.com/nats-io/nats-server/v2/server/client.go:4569 +0x2052
github.com/nats-io/nats-server/v2/server.(*client).processInboundClientMsg(0xa6a2000, {0xa6ac26b, 0x16, 0x195})
        github.com/nats-io/nats-server/v2/server/client.go:3906 +0xb23
github.com/nats-io/nats-server/v2/server.(*client).processInboundMsg(0xa6a2000, {0xa6ac26b, 0x16, 0x195})
        github.com/nats-io/nats-server/v2/server/client.go:3744 +0x74
github.com/nats-io/nats-server/v2/server.(*client).parse(0xa6a2000, {0xa6ac200, 0x81, 0x200})
        github.com/nats-io/nats-server/v2/server/parser.go:497 +0x1e4b
github.com/nats-io/nats-server/v2/server.(*client).readLoop(0xa6a2000, {0x0, 0x0, 0x0})
        github.com/nats-io/nats-server/v2/server/client.go:1381 +0x1181
github.com/nats-io/nats-server/v2/server.(*Server).createClientEx.func1()
        github.com/nats-io/nats-server/v2/server/server.go:3247 +0x35
github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine.func1()
        github.com/nats-io/nats-server/v2/server/server.go:3730 +0x3d
created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine in goroutine 81
        github.com/nats-io/nats-server/v2/server/server.go:3728 +0xf7
</pre>

### Expected behavior

The server will go back and forth sending one request to each worker.

### Server and client version

```
nats --version   0.1.1

nats-server --version v2.10.11
```

### Host environment

- `Linux mint 21.2`
- `Linux razer15-mint 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linu`

### Steps to reproduce

- terminal 1  $ nats-server
- terminal 2  $ nats reply msg.test "hello from one"
- terminal 3  $ nats reply msg.test "hello from two"
- terminal 4 
 
       $ nats request msg.test < /dev/null
       $ nats request msg.test < /dev/null

On the second request the server will crash and all three clients will say:

     Disconnected due to: EOF, will attempt reconnect

**Comment by wallyqs** [comment]
Hi @jeremylowery thanks for the report. For the nats-server version did you use one of the binaries from the release ( https://github.com/nats-io/nats-server/releases/tag/v2.10.11) or did you install some different way?

**Comment by jeremylowery** [comment]
Opps. I just realized I downloaded the 32 bit deb files not the 64 bit deb files. After downloading the 64 bit ones it's working as expected. ty.
