### ISSUE TITLE
Typed Errors

### ISSUE THREAD

**Issue by tylertreat** [nats-io/nats-server#517]
Currently, gnatsd sends errors to the client in the form of `-ERR <error message>`, e.g. `-ERR 'Authorization Violation'`. This makes it hard to build typed errors with context in the clients and sometimes requires the user to string match on error messages. For example, if I receive an async error for one of my subscriptions because permissions changed on the server, I would want to know which subscription it is.

We should consider sending error messages as JSON would be more extensible and allow for sending error context that can be easily parsed by a client. Likewise, clients should expose typed errors to the user.

**Comment by ColinSullivan1** [comment]
One implementation approach could be to add a field to the client connect INFO sent to the server indicating it wants errors as JSON, to maintain backward compatibility for older clients.
