### ISSUE TITLE
Message count never zero

### ISSUE THREAD

**Issue by ro0NL** [nats-io/nats-server#5214]
### Observed behavior

We keeping seeing a message count of 1 on various streams, using `nats stream ls`

But when consume we see: `NATS/1.0 404 No Messages`

We cannot see what's in the stream due:

```
nats: error: work queue retention streams can only be paged if direct access is allowed
```

Which is enabled btw.

### Expected behavior

Message count of 0 on empty queue

### Server and client version

2.10.11

**Comment by derekcollison** [comment]
Upgrade to 2.10.12, if issue persists we will need quite a bit more information.

**Comment by ro0NL** [comment]
@derekcollison we have again queues that never reach zero. It's probably an invalid state issue caused by us, due a fresh rollout using k8 (`kubectl rollout restart statefulset`)

Not a  blocker, but i noticed the only way to reset it is to recreate the stream, which is far from ideal.

**Comment by ro0NL** [comment]
in case it helps:

```
receive HMSG handler.904ff13f 5ea388ad 28 28NATS/1.0 404 No Messages
```

```
nats -s $NATS_DSN s info test | grep -E '(Messages|Bytes)'
              Messages: 1
                 Bytes: 388 B
```

but im not sure how to debug those pending bytes

**Comment by derekcollison** [comment]
We have identified a few conditions where this can happen and expect to have fixes for them for 2.10.14 release which will probably be next week.

**Comment by ro0NL** [comment]
@derekcollison you mean v2.10.13? Any ETA for a bugfix?

**Comment by derekcollison** [comment]
Today.. but yes 2.10.14, we skip .13s..
