### ISSUE TITLE
Config reload backups

### ISSUE THREAD

**Issue by tylertreat** [nats-io/nats-server#522]
We've discussed the idea of dumping the last known good config to a backup file when config reload fails. However, there is one edge case with this: includes. A few options:

1) Backup every file in the config file tree. The problem with this is the files will not reference the backups. We could rewrite the includes in the backups, but this doesn't seem like a good idea. This also requires holding the config file contents in memory.

2) Write out the contents of the `Options` struct to a backup config file. This covers the include edge case and doesn't require holding file contents in memory, but it loses the fidelity of the source config (formatting, comments, structure, etc.).

3) Snapshot the config file tree on startup and write the backups to a backup directory. This might break if using absolute includes instead of relative. It also requires holding file contents in memory.

4) Don't do backups and just put the onus on operators to use version control.

@nats-io/core

**Comment by derekcollison** [comment]
MVP force version control by operators.

**Comment by RedShift1** [comment]
Definitely have version control be done by operators. Things get messy if gnatsd would try and copy files. What if it can't write anywhere? Does the daemon stop, crash or refuse to reload?

I would do it like Apache's httpd does it, it has a "check configuration file" option, which checks the validity of the configuration file. Issuing the reload command does the check for you, and if that check succeeds, only then httpd reloads. This would tie in nicely with systemd's "ExecReload", so if the operator issued "systemctl reload gnatsd", it does the check for him and if it fails, no harm done, gnatsd keeps on running.

**Comment by derekcollison** [comment]
We have the ability to check the config files now. Closing this for now, feel free to re-open if needed.
