### ISSUE TITLE
HSTS Missing From HTTPS for WebSockets

### ISSUE THREAD

**Issue by mcosta74** [nats-io/nats-server#5226]
### Observed behavior

One customer ran a security scanner and we got this report

```
HSTS Missing From HTTPS Medium 6.5 Configure the remote web server to use HSTS. Server (RFC 6797)
1 Affected Host(s): xxxxxxx
Initial Detection: 2024-03-11 21:08 UTC
Latest Detection: 2024-03-16 00:03 UTC
Description: The remote web server is not enforcing HSTS, as defined by RFC 6797. HSTS is an optional response header that can be configured on the server to instruct the browser to only communicate via HTTPS. The lack of HSTS allows downgrade attacks, SSL-stripping man-in-the-middle attacks, and weakens cookie-hijacking protections.
```

Is there a way to add this missing header ?

### Expected behavior

N/A

### Server and client version

`nats-server`: `v2.10.2`

**Comment by bruth** [comment]
Here is the [set of examples](https://datatracker.ietf.org/doc/html/rfc6797#section-6.2) and implications. In terms of implementation, setting the header if WebSocket TLS is enabled seems obvious. The question is whether additional server options are required to tune the age and subdomain option.
