### ISSUE TITLE
nats-server.exe reports high memory utilization in cluster (v2.10.4)

### ISSUE THREAD

**Issue by rdkumavat1** [nats-io/nats-server#5239]
Observing very high memory utilization by the nats-server.exe in 3 node cluster scenario with version 2.10.4.
Is there any active issue observed or a quick fix available for this?

Thanks

**Comment by neilalexander** [comment]
Please provide memory profiles if you can: https://docs.nats.io/running-a-nats-service/nats_admin/profiling

**Comment by neilalexander** [comment]
Also some information about your setup, number of nodes, rough load/number of assets/traffic etc.

**Comment by wallyqs** [comment]
Recommend looking to upgrade to v2.10.12 since there are memory related fixes since then, a couple being: 
https://github.com/nats-io/nats-server/pull/4988
https://github.com/nats-io/nats-server/pull/4969

**Comment by rdkumavat1** [comment]
> Please provide memory profiles if you can: https://docs.nats.io/running-a-nats-service/nats_admin/profiling

unable to fetch the memory profile as utilization has reached 99%, I will try If I can.

Meanwhile, I am uploading a configuration file for one of the nodes in the 
[nats-server.txt](https://github.com/nats-io/nats-server/files/14730967/nats-server.txt)
cluster.

**Comment by rdkumavat1** [comment]
Please suggest ways to effectively monitor the cluster environment, able to see some of the metrics using the HTTP monitoring port but I need additional runtime information about runtime

Thanks

**Comment by rdkumavat1** [comment]
Please consider this issue as closed.
