### ISSUE TITLE
Outbound gateway connections stuck waiting on first INFO response

### ISSUE THREAD

**Issue by wjordan** [nats-io/nats-server#5349]
### Observed behavior

I'm observing an issue with outbound gateway connections dropping during high cross-cluster packet loss, and remaining disconnected even after the network fully recovers. This leaves the super-cluster in a degraded state where messages aren't delivered across clusters because of the missing gateway connection.

Each server has explicitly-configured gateways with `reject_unknown_cluster` set in its config.

Inspecting the server logs, I see a `Creating outbound gateway connection to "[remote]"` entry but no corresponding `Outbound gateway connection to "[remote]" ([name]) registered` log entry afterwards.

Looking at the source code, it appears that for outbound gateway connections, the `PING` timers usually used to detect stale connections aren't initiated until _after_ the first `INFO` is received from the remote gateway connection. This means that if the initial `CONNECT` or the `INFO` response messages are lost, it does seem possible for the connection to get stuck indefinitely.

### Expected behavior

All explicitly-configured outbound gateway connections should continue retrying during periods of intermittent connectivity and eventually recover when network conditions resolve.

### Server and client version

We're running a somewhat old server version in production (2.7.4), but it appears this bug is still present in the latest commit as far as I can tell from inspecting the source code.

**Comment by kozlovic** [comment]
Thank you for the report. I will have a look at this today. I think it may be the same for leafnodes too.

**Comment by wjordan** [comment]
Thanks for the quick attention to this! The fix in #5356 is just what I had sketched out locally as well :+1:

**Comment by amitamit281** [comment]
@wjordan we have seen similar issue in 2.10.14. Do you know the steps to reproduce? we have seen similar issue during our network outage. thanks
