### ISSUE TITLE
Embedding NATS makes developers lose the opportunity to process os signals

### ISSUE THREAD

**Issue by yangjinheng** [nats-io/nats-server#5360]
### Proposed change

NewServer() -> s.handleSignals() -> os.Exit(0)

Is it possible to avoid os.Exit(1) after receiving a signal?

### Use case

https://docs.nats.io/running-a-nats-service/clients#embedding-nats

Embedding NATS is very practical for me

**Comment by ripienaar** [comment]
Set this option to true https://github.com/nats-io/nats-server/blob/8478886227971dc41aa2325693584a7fc20235c3/server/opts.go#L271

**Comment by yangjinheng** [comment]
That's great.
