### ISSUE TITLE
Getting consumer pending messages count is inconsistent [v2.9.16]

### ISSUE THREAD

**Issue by MENNAELMESALMY** [nats-io/nats-server#5367]
### Observed behavior

I have a Jetstream that we add and delete messages from, on startup we want to get the count of messages in the stream as follows:
```
var currentCount = sub.GetConsumerInformation().CalculatedPending;
```
We noticed that this sometimes returns a count more than the actual messages in the stream so for example, we see it returning  `1882`  while the stream only contains `1867` messages, we checked the count with `nats stream info <stream-name>` and it had indeed only `1867`.
Also, we check for the last message with `msg.MetaData.NumPending == 0` but we observed it having it set to 15 when in indeed it was the last message on the stream as per the cli `nats sub <subject-name> --last-per-subject`.
Setting the ackpolicy to `.WithAckPolicy(AckPolicy.None)` makes it return the correct count for some reason.

### Expected behavior

The returned pending messages count is consistent with the message count in the stream.

### Server and client version

Server version: 2.9.16
Client version (c# client): 1.0.4

**Comment by ripienaar** [comment]
You are running a very old server and there have been 100s of bug fixes since.

Please let us know if this is still happening after you upgrade to latest.

**Comment by MENNA123MAHMOUD** [comment]
will do, Thanks!
do you know of any particular fixed bug that can result in this behavior?

**Comment by ripienaar** [comment]
You can look through the changelog to see, it's not worth diagnosing bugs on such old versions at this point and so I wouldn't be certain which of the many fixes would impact you.

So to help us help you, please upgrade.

**Comment by wallyqs** [comment]
Will close for now since this is on v2.9, but feel free to re-open if find a similar condition on v2.10.X
