### ISSUE TITLE
Interest retention doesn't drop messages if not captured by consumer FilterSubjects

### ISSUE THREAD

**Issue by MauriceVanVeen** [nats-io/nats-server#5383]
### Observed behavior

An Interest stream should immediately drop published messages if they have no interest.

When using a consumer with `FilterSubjects`, all published messages are kept.

### Expected behavior

Only messages with interest based on consumer's `FilterSubjects` are kept.

### Server and client version

Server version: 2.10.14
CLI version: 0.1.4

### Steps to reproduce

```sh
nats str add interest-stream --subjects='interest.>' --retention=interest --defaults
nats con add interest-stream interest-consumer --filter='interest.a' --filter='interest.b' --pull --defaults

nats req 'interest.a' '' # should persist
nats req 'interest.b' '' # should persist
nats req 'interest.c' '' # should have no interest, not captured by consumer FilterSubjects

nats str info interest-stream # shows 3 messages, whereas it should be 2
```

**Comment by Jarema** [comment]
#4878 seems to be closely related, however the #5384 does not fix that one.

**Comment by MauriceVanVeen** [comment]
@Jarema have been looking at https://github.com/nats-io/nats-server/issues/4878 as well, and believe it's due to the following code existing when deleting a consumer, but not when updating it:
https://github.com/nats-io/nats-server/blob/main/server/consumer.go#L5225-L5252

If the same logic would be present for the update, but with a slight adjustment to `if mset.noInterest(seq, o)` (because it ignores the provided consumer), then it should be fixed.

I could work on a PR with a fix for that today, if that's okay?

**Comment by MauriceVanVeen** [comment]
Possibly have a fix for https://github.com/nats-io/nats-server/issues/4878, here: https://github.com/nats-io/nats-server/pull/5385
