### ISSUE TITLE
Comment at end of config file is a parse error

### ISSUE THREAD

**Issue by philpennock** [nats-io/nats-server#5396]
### Observed behavior

With a `nats.conf` file which has a `#` line-comment at the end of the file, 

Error from `nats-server -t`:
```
nats-server: Parse error on line 153: 'Expected a top-level value to end with a new line, comment or EOF, but got 'T' instead.'
```

The comment was:

```
# This is a dummy comment added to force a config deploy and server restart.
# $RANDOM number: 23566
```

and it is the `T` of `This` which is being reported.

### Expected behavior

A line-comment should be valid on any line, even after the last actual directive

### Server and client version

Server: v2.10.15-RC.6

**Comment by derekcollison** [comment]
Need more info, just test this and works fine.

```go
// https://github.com/nats-io/nats-server/issues/5396
func TestServerConfigLastLineComments(t *testing.T) {
	conf := createConfFile(t, []byte(`
		listen: 127.0.0.1:-1
		server_name: s-test

		# This is a dummy comment added to force a config deploy and server restart.
		# $RANDOM number: 23566
	`))

	s, _ := RunServerWithConfig(conf)
	defer s.Shutdown()

	// This should work of course.
	nc, err := nats.Connect(s.ClientURL(), nats.UserInfo("u", "pass"))
	require_NoError(t, err)
	defer nc.Close()
}
```

Is RANDOM defined?

**Comment by derekcollison** [comment]
And I tried both norma string and a quoted number..

**Comment by kozlovic** [comment]
Since it works for @derekcollison, @philpennock, could it be that you have an error prior to that line? Something like you started the definition of an object but don't have the closing `]` or `}`, something like that?

**Comment by philpennock** [comment]
Additional pre-condition for failure: using braces around a bunch of config.


### Valid

```
{
  "listen":  "0.0.0.0:4222"
}
```

```
{
# wibble
  "listen":  "0.0.0.0:4222"
}
```

```
# wibble
{
  "listen":  "0.0.0.0:4222"
}
```

### Invalid

```
{
  "listen":  "0.0.0.0:4222"
}
# wibble
```

**Comment by derekcollison** [comment]
Thanks will adapt the test.
