### ISSUE TITLE
Decentralized auth callout: Connections of revoked users are not closed immediately

### ISSUE THREAD

**Issue by ryad-eldajani** [nats-io/nats-server#5477]
### Observed behavior

We are using a decentralized auth callout handler [similar to the nats-by-example service](https://github.com/ConnectEverything/nats-by-example/blob/main/examples/auth/callout-decentralized/cli/service/main.go).

Following relevant accounts & users are in the system:

- `service-account` (auth-callout encryption target)
    - `sentinel-user`
- `customer-account`
    - `customer-user`

Customer accounts like `customer-account` are created in an automated manner. The signing keys for these accounts are stored in a KV for the auth callout handling service.

NATS clients are connecting to the NATS server using the `sentinel-user` and token info including the account ID like `customer-account`. The NATS server is requesting an auth callout to the handling service. The auth callout handling service is creating a `customer-user` and allowing the initial connection request.

Now `customer-user` is being added to the revocations list of `customer-account`. The `customer-account` JWT having `customer-user` in it's revocation list is then pushed to the NATS server. The initial connection from the NATS client remains open.

### Expected behavior

As with statically created users, it is expected that once the updated account JWT is pushed to the NATS server, the open connection from a user in the accounts revocation list is immediately closed ([as documented here for example](https://docs.nats.io/using-nats/nats-tools/nsc/revocation#pushing-the-changes-to-the-nats-servers)).

### Server and client version

Server v2.10.16
CLI Client v0.1.4 and nats.go v1.35.0

**Comment by ryad-eldajani** [comment]
Dear @derekcollison

We are using the [full resolver](https://docs.nats.io/running-a-nats-service/configuration/securing_nats/auth_intro/jwt/resolver#full).

We are pushing updated account JWTs to `$SYS.REQ.CLAIMS.UPDATE` using a SYS user with appropriate permissions.

**Comment by aricart** [comment]
@ryad-eldajani what is the revocation date for the user - and is the user ID stable? Note that the revocation date for the user (in seconds) means that all JWTs issued prior that date are revoked. Newer ones are not, at that point your callout service should be rejecting the user based on your internal logic.

**Comment by ryad-eldajani** [comment]
@aricart Thank you very much for your reply.

Essentially we use `accountClaims.Revoke(userClaims.Subject)` which revokes at `time.Now()`.

A client using that user claim is already connected to the server. The very same user claim has been created in the past by the auth callout handler.

Therefore, we would expect that the connection for that user claim is closed at `time.Now()` as soon as the account claim with the updated revocation including the public key of the user is pushed to the server.

Can you please explain what exactly you mean by "stable user id"?

**Comment by tomhiess** [comment]
Hi, I'm working together with @ryad-eldajani on that topic ... so let me join the discussion :)

- the user ids are not stable, meaning, for every callout we create a new user with a new id

I modified the decentralized auth callout demo from @bruth to demonstrate the problem: https://github.com/tomhiess/nats-by-example/tree/demo-revoke/examples/auth/callout-decentralized

**Comment by aricart** [comment]
@ryad-eldajani by stable user id, I mean the nkey representing the user.

**Comment by ryad-eldajani** [comment]
@aricart in this regard the user is not stable. User claims are created on each auth callout.
This is similar as in the example provided by @bruth : https://github.com/ConnectEverything/nats-by-example/blob/main/examples/auth/callout-decentralized/cli/service/main.go#L175

Concrete example process:

1. Connection to NATS is established:
- Client connects to NATS server using `sentinel-user` and token containing account info `AXYZ`
- NATS server requests `AUTH` endpoint
- `AUTH` endpoint receives token
    - reads account info `AXYZ` from token
    - creates user claims with public key `UXYZ`
    - signs user claims with `AXYZ` seed
    -  responds to the auth callout request with `uxyzJWT`
- NATS server establishes the connection `conn-uxyz` with `uxyzJWT`

2. User is being revoked:
- Public key `UXYZ` is being revoked with `time.Now()` in account `AXYZ`
- Updated `axyzJWT` containing `UXYZ` in its `revocations` is pushed to the server

Expected behavior would be that `conn-uxyz` is closed immediately, but it remains open.

**Comment by aricart** [comment]
@ryad-eldajani I found the issue - working on the fix.

**Comment by ryad-eldajani** [comment]
Dear @aricart any news on this one?

**Comment by aricart** [comment]
Will post PR today.
