### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by loongyiyao** [nats-io/nats-server#5525]
### Observed behavior

atal error: concurrent map read and map write

goroutine 61 [running]:
github.com/nats-io/nats-server/v2/server.(*fileStore).subjString(...)
	github.com/nats-io/nats-server/v2/server/filestore.go:5648
github.com/nats-io/nats-server/v2/server.(*msgBlock).subjString(...)
	github.com/nats-io/nats-server/v2/server/filestore.go:5659
github.com/nats-io/nats-server/v2/server.(*msgBlock).indexCacheBuf(0xc018422340, {0xc04a922000, 0x7ffdb5, 0x800000?})
	github.com/nats-io/nats-server/v2/server/filestore.go:5063 +0x794
github.com/nats-io/nats-server/v2/server.(*msgBlock).loadMsgsWithLock(0xc018422340)
	github.com/nats-io/nats-server/v2/server/filestore.go:5367 +0x489
github.com/nats-io/nats-server/v2/server.(*msgBlock).fetchMsg(0xc018422340, 0xd7758, 0xc02d03cec8?)
	github.com/nats-io/nats-server/v2/server/filestore.go:5397 +0xde
github.com/nats-io/nats-server/v2/server.(*fileStore).msgForSeq(0xc01841dc00, 0x9e58e5?, 0xc02c945950?)
	github.com/nats-io/nats-server/v2/server/filestore.go:5553 +0x145
github.com/nats-io/nats-server/v2/server.(*fileStore).LoadMsg(0x1052720?, 0x8ed4b8?, 0xc017348870?)
	github.com/nats-io/nats-server/v2/server/filestore.go:5664 +0x13
github.com/nats-io/nats-server/v2/server.(*stream).checkForInterest(0xc01841d880, 0x40a521e3?, 0xc01f54af00)
	github.com/nats-io/nats-server/v2/server/stream.go:5340 +0xc3
github.com/nats-io/nats-server/v2/server.(*stream).noInterest(...)
	github.com/nats-io/nats-server/v2/server/stream.go:5324
github.com/nats-io/nats-server/v2/server.(*consumer).stopWithFlags(0xc01f54af00, 0x1, 0x0, 0x1, 0x0)
	github.com/nats-io/nats-server/v2/server/consumer.go:5063 +0xb46
github.com/nats-io/nats-server/v2/server.(*jetStream).processClusterDeleteConsumer(0xc000182300, 0xc03bd5ebd0, 0x10?, 0x0)
	github.com/nats-io/nats-server/v2/server/jetstream_cluster.go:4357 +0x226
github.com/nats-io/nats-server/v2/server.(*jetStream).processConsumerRemoval(0xc000182300, 0xc03bd5ebd0)
	github.com/nats-io/nats-server/v2/server/jetstream_cluster.go:4074 +0x2b6
github.com/nats-io/nats-server/v2/server.(*jetStream).applyMetaEntries(0xc000182300, {0xc01f686ba0, 0x1, 0x0?}, 0x0)
	github.com/nats-io/nats-server/v2/server/jetstream_cluster.go:1921 +0xab7
github.com/nats-io/nats-server/v2/server.(*jetStream).monitorCluster(0xc000182300)
	github.com/nats-io/nats-server/v2/server/jetstream_cluster.go:1332 +0xbdc
github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine.func1()
	github.com/nats-io/nats-server/v2/server/server.go:3700 +0x32
created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine in goroutine 1
	github.com/nats-io/nats-server/v2/server/server.go:3698 +0x145

goroutine 1 [chan receive]:
github.com/nats-io/nats-server/v2/server.(*Server).WaitForShutdown(...)
	github.com/nats-io/nats-server/v2/server/server.go:2540
main.main()
	github.com/nats-io/nats-server/v2/main.go:139 +0x471

### Expected behavior

run normal

### Server and client version

V2.10.5

**Comment by neilalexander** [comment]
Thanks for the issue report, this issue was fixed some time ago. Please update to the latest version.

**Comment by neilalexander** [comment]
We spend a lot of time on bug fixes so we always recommend using the latest version where possible.

**Comment by loongyiyao** [comment]
> We spend a lot of time on bug fixes so we always recommend using the latest version where possible.

@neilalexander thanks!
