### ISSUE TITLE
panic: runtime error: index out of range [7] with length 0

### ISSUE THREAD

**Issue by loongyiyao** [nats-io/nats-server#5536]
### Observed behavior

2024.06.14 15:46:05 : ----------------------------------------------------------------------
2024.06.14 15:46:05 : start nats-server...
2024.06.14 15:46:05 : DDB_NAME=ddb_163052
2024.06.14 15:46:05 : DDB_IP=10.234.163.52, DDB_LISTEN=4222, DDB_M_LISTEN=172.30.225.200:8222, DDB_C_LISTEN=6222
2024.06.14 15:46:05 : icount=0, ip=10.234.163.50
2024.06.14 15:46:05 : icount=1, ip=10.234.163.51
2024.06.14 15:46:05 : icount=2, ip=10.234.163.52
2024.06.14 15:46:05 : MAX_MEM=5GiB, MAX_FILE=360GiB
2024.06.14 15:46:05 : nats-server started successfully !
panic: runtime error: index out of range [7] with length 0

goroutine 164 [running]:
encoding/binary.littleEndian.Uint64(...)
        encoding/binary/binary.go:106
github.com/nats-io/nats-server/v2/server.(*raft).readTermVote(0xc0004e2c08)
        github.com/nats-io/nats-server/v2/server/raft.go:3765 +0x119
github.com/nats-io/nats-server/v2/server.(*Server).startRaftNode(0xc000175b08, {0xc0002445ab, 0x5}, 0xc0006d4788, 0xc0003467b0)
        github.com/nats-io/nats-server/v2/server/raft.go:407 +0x933
github.com/nats-io/nats-server/v2/server.(*jetStream).createRaftGroup(0xc00024a200, {0xc0002445ab, 0x5}, 0xc0004004e0, 0x16, 0xc0003467b0)
        github.com/nats-io/nats-server/v2/server/jetstream_cluster.go:2090 +0xbcc
github.com/nats-io/nats-server/v2/server.(*jetStream).processClusterCreateStream(0xc00024a200, 0xc00021ea08, 0xc00037cb40)
        github.com/nats-io/nats-server/v2/server/jetstream_cluster.go:3692 +0x285
github.com/nats-io/nats-server/v2/server.(*jetStream).processStreamAssignment(0xc00024a200, 0xc00037cb40)
        github.com/nats-io/nats-server/v2/server/jetstream_cluster.go:3411 +0x456
github.com/nats-io/nats-server/v2/server.(*jetStream).applyMetaSnapshot(0xc00024a200, {0xc0001de036, 0x127c, 0x1285}, 0xc0006d5b10, 0x1)
        github.com/nats-io/nats-server/v2/server/jetstream_cluster.go:1619 +0xb89
github.com/nats-io/nats-server/v2/server.(*jetStream).applyMetaEntries(0xc00024a200, {0xc00068e6c0, 0x1, 0x0?}, 0xc0006d5b10)
        github.com/nats-io/nats-server/v2/server/jetstream_cluster.go:1883 +0xb34
github.com/nats-io/nats-server/v2/server.(*jetStream).monitorCluster(0xc00024a200)
        github.com/nats-io/nats-server/v2/server/jetstream_cluster.go:1370 +0xc30
github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine.func1()
        github.com/nats-io/nats-server/v2/server/server.go:3759 +0x32
created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine in goroutine 1
        github.com/nats-io/nats-server/v2/server/server.go:3757 +0x145

### Expected behavior

run normal

### Server and client version

v2.10.16

**Comment by neilalexander** [comment]
Thanks for the bug report, this was fixed in #5464 and the fix will be in 2.10.17. There are release candidates available to try if you'd like to verify they solve your problem: https://github.com/nats-io/nats-server/releases
