### ISSUE TITLE
After max_delivered attempts messages are not deleted from WQ Stream 

### ISSUE THREAD

**Issue by souravagrawal** [nats-io/nats-server#5564]
### Observed behavior

message which are failed to acknowledged by consumer even after max_redelivery attempts, are not getting deleted from WorkQueue Stream. Is it expected, if yes how to avoid this ?

### Expected behavior

If acknowledge after max_delivery attempt is also not succesfull then NATS should mark the message deleted. 

### Server and client version

nats-server 2.10.5
nats-client 1.35.0

### Host environment

macOS 12.3.1

### Steps to reproduce

Create a WorkQueue Stream
Create a PullBased Consumer with below configuration
- max_delivered = 3
- max_ack_pending = 1

Publish a message to stream
Start a consumer and do not Ack the message, after all redelivery attempts message are not deleted from stream and  consumer info shows no message to process.

**Comment by derekcollison** [comment]
This is correct behavior. That way the you can decide what to do with the message, in terms of deleting, retrying or moving to DLQ.
