### ISSUE TITLE
Unable to log messages or trace in debug mode in NATS Embedded server

### ISSUE THREAD

**Issue by iamshreeram** [nats-io/nats-server#5569]
### Observed behavior

When a message is posted to a given subject inside the NATS Embedded server, the trace or debug options do not print any details.

### Expected behavior

I expect the payload to be printed when a message is posted to a given subject inside the NATS Embedded server, enabling effective debugging and message logging.

### Server and client version

Server : 2.10
Client : 1.35

### Host environment

Mac

### Steps to reproduce

Start the embedded server with Trace or debug option like below - 
```
...
	natsServer := natsserver.NewNatsServer()
	ns := natsServer.StartNatsServer(&server.Options{TraceVerbose: true})
	defer ns.WaitForShutdown()
...
```

```
func (ns *natsServer) StartNatsServer(opts *server.Options) *server.Server {
	ns.server, _ = server.NewServer(opts)
	go ns.server.Start()
	if !ns.server.ReadyForConnections(4 * time.Second) {
		panic("not ready for connection")
	}
	return ns.server
}
```

**Comment by ripienaar** [comment]
You need to configure the logger to initialize logging, also supports passing in your own logger. 

https://github.com/nats-io/nats-server/blob/3d9cbb908704b1bea66be3f92805a18fd021ecac/server/log.go#L49

**Comment by iamshreeram** [comment]
@ripienaar , Thank you for the prompt reply. 

I did have `ns.ConfigureLogger()` in place, but the issue was with the Options. I mistakenly used `TraceVerbose` instead of `Trace`. Correcting this with the snippet below resolved the problem.

```
	natsServer := natsserver.NewNatsServer()
	ns := natsServer.StartNatsServer(&server.Options{Trace: true})
	ns.ConfigureLogger()
	defer ns.WaitForShutdown()
```
