### ISSUE TITLE
JetStream: incorrect consumer num_pending against stream with subjects ending in `.>`

### ISSUE THREAD

**Issue by scottf** [nats-io/nats-server#5608]
### Observed behavior

A new generic consumer reports more num_pending than actual messages in the stream.

### Expected behavior

The consumer reports the correct num_pending.

### Server version

2.10.10 or later. (Tested against 2.10.9 the information was reported correctly)

### Steps to reproduce

Create a consumer against attached data, `nats consumer create` give it a name and all defaults. Look at the consumer info, it shows "Unprocessed Messages: 5,803". There are only 5670 messages.

### Notes
All subjects end with .> (dot greater) as in `OrchestrationStream_08fa7d3dcd644745bace255d2c76fbc2.>`

### Data
[nats_cache.zip](https://github.com/user-attachments/files/16035760/nats_cache.zip)
[stree_wildcard.zip](https://github.com/user-attachments/files/16035761/stree_wildcard.zip)

**Comment by scottf** [comment]
```
C:\nats>nats s info OrchestrationStream_08fa7d3dcd644745bace255d2c76fbc2
Information for Stream OrchestrationStream_08fa7d3dcd644745bace255d2c76fbc2 created 2024-06-20 06:58:59

              Subjects: OrchestrationStream_08fa7d3dcd644745bace255d2c76fbc2.>
              Replicas: 1
               Storage: File

Options:

             Retention: Limits
       Acknowledgments: true
        Discard Policy: New
      Duplicate Window: 1y0d0h0m0s
     Allows Msg Delete: true
          Allows Purge: true
        Allows Rollups: false

Limits:

      Maximum Messages: unlimited
   Maximum Per Subject: unlimited
         Maximum Bytes: unlimited
           Maximum Age: 1y0d0h0m0s
  Maximum Message Size: unlimited
     Maximum Consumers: unlimited

State:

              Messages: 5,670
                 Bytes: 4.8 MiB
        First Sequence: 1,133 @ 2024-06-20 08:48:59
         Last Sequence: 359,729 @ 2024-06-28 06:32:40
      Deleted Messages: 352,927
      Active Consumers: 3
    Number of Subjects: 519
```

**Comment by scottf** [comment]
Originally reported as a discussion in the Java repo: https://github.com/nats-io/nats.net/discussions/905

**Comment by derekcollison** [comment]
Can this be re-produced against main?

**Comment by scottf** [comment]
> Can this be re-produced against main?
I originally verified the data that was provided against 2.10.17

**Comment by neilalexander** [comment]
Have figured out the problem. The stree `Match` was firing the callback twice for `OrchestrationStream_08fa7d3dcd644745bace255d2c76fbc2.>`, which had 133 messages, and 5803-133=5670. Posted a PR to fix it.
