### ISSUE TITLE
Panic nil pointer dereference

### ISSUE THREAD

**Issue by TroyKomodo** [nats-io/nats-server#5656]
### Observed behavior

Whilst consuming multiple streams concurrently nats panics.
```
seventv-nats-1  | panic: runtime error: invalid memory address or nil pointer dereference
seventv-nats-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa50dde]
seventv-nats-1  | 
seventv-nats-1  | goroutine 1 [running]:
seventv-nats-1  | github.com/nats-io/nats-server/v2/server/stree.(*SubjectTree[...]).Match(0xcc9180, {0xc065630860, 0x20, 0x20}, 0xc0003c6050)
seventv-nats-1  |       github.com/nats-io/nats-server/v2/server/stree/stree.go:107 +0xbe
seventv-nats-1  | github.com/nats-io/nats-server/v2/server.(*fileStore).NumPending(0xc000276e08, 0x173be30, {0xc065630860, 0x20}, 0x0)
seventv-nats-1  |       github.com/nats-io/nats-server/v2/server/filestore.go:3051 +0xcf5
seventv-nats-1  | github.com/nats-io/nats-server/v2/server.(*consumer).calculateNumPending(0xc0001e6f08)
seventv-nats-1  |       github.com/nats-io/nats-server/v2/server/consumer.go:4241 +0x135
seventv-nats-1  | github.com/nats-io/nats-server/v2/server.(*consumer).streamNumPending(0xc0001e6f08)
seventv-nats-1  |       github.com/nats-io/nats-server/v2/server/consumer.go:4203 +0x2c
seventv-nats-1  | github.com/nats-io/nats-server/v2/server.(*consumer).setLeader(0xc0001e6f08, 0x1)
seventv-nats-1  |       github.com/nats-io/nats-server/v2/server/consumer.go:1207 +0x3db
seventv-nats-1  | github.com/nats-io/nats-server/v2/server.(*stream).addConsumerWithAssignment(0xc000276a88, 0xc0a06e8028, {0x0, 0x0}, 0x0, 0x1, 0x0)
seventv-nats-1  |       github.com/nats-io/nats-server/v2/server/consumer.go:1037 +0x24e5
seventv-nats-1  | github.com/nats-io/nats-server/v2/server.(*Account).EnableJetStream(0xc00029c288, 0xc000025560)
seventv-nats-1  |       github.com/nats-io/nats-server/v2/server/jetstream.go:1402 +0x31df
seventv-nats-1  | github.com/nats-io/nats-server/v2/server.(*Server).configJetStream(0xc0001fbb08, 0xc00029c288)
seventv-nats-1  |       github.com/nats-io/nats-server/v2/server/jetstream.go:716 +0xeb
seventv-nats-1  | github.com/nats-io/nats-server/v2/server.(*Server).enableJetStreamAccounts(0xc0001fbb08)
seventv-nats-1  |       github.com/nats-io/nats-server/v2/server/jetstream.go:637 +0xad
seventv-nats-1  | github.com/nats-io/nats-server/v2/server.(*Server).enableJetStream(0xc0001fbb08, {0x2f17972800, 0x205f6b45000, {0xc000322110, 0xf}, 0x1bf08eb000, 0x0, {0x0, 0x0}, 0x0, ...})
seventv-nats-1  |       github.com/nats-io/nats-server/v2/server/jetstream.go:450 +0xa12
seventv-nats-1  | github.com/nats-io/nats-server/v2/server.(*Server).EnableJetStream(0xc0001fbb08, 0xc000249da0)
seventv-nats-1  |       github.com/nats-io/nats-server/v2/server/jetstream.go:224 +0x4a5
seventv-nats-1  | github.com/nats-io/nats-server/v2/server.(*Server).Start(0xc0001fbb08)
seventv-nats-1  |       github.com/nats-io/nats-server/v2/server/server.go:2280 +0x102d
seventv-nats-1  | github.com/nats-io/nats-server/v2/server.Run(...)
seventv-nats-1  |       github.com/nats-io/nats-server/v2/server/service.go:22
seventv-nats-1  | main.main()
seventv-nats-1  |       github.com/nats-io/nats-server/v2/main.go:127 +0x325
```

### Expected behavior

No panic

### Server and client version

client: `v0.1.1` (also latest rust client)
server: `nats:latest` `2.10.17`

### Host environment

Docker

### Steps to reproduce

Not sure. It just happened while I was consuming am unable to create a replication.

I have a single stream with ~30 consumers with a single filter topic on each consumer.

my application is listening to messages on all 30 consumers in a pull configuration.

I have 2 terminals open
```
watch nats stream ls
watch nats stream <stream> report
```

**Comment by wallyqs** [comment]
@TroyKomodo was this on a cluster setup or standalone node? could you share more info about the stream, consumers and subjects?

**Comment by TroyKomodo** [comment]
In prod we will obviously use a cluster deployment but this was just our dev container we are running with prod data to test before a deployment to stage

**Comment by TroyKomodo** [comment]
## app1:
mongodb change stream listener

reads changes from mongodb -> nats publish `<prefix>.(db).(collection)`

## app2: 
mongo typesense reindexer
creates a jet stream stream `mongo-typesense` `interest`
creates a consumer for each pull collection we support `29 in total` 

starts listening to messages from each collection `global total messages in flight = 50_000`

ack each message / nack or whatever depending on status

**Comment by wallyqs** [comment]
@TroyKomodo how unique are the subjects?

**Comment by TroyKomodo** [comment]
Not unique. 29 total subjects.

```
mongo-change-stream.7tv-new.users
```

**Comment by TroyKomodo** [comment]
related to https://github.com/nats-io/nats.rs/issues/1285

**Comment by neilalexander** [comment]
Can you please try with [2.10.18-RC.3](https://github.com/nats-io/nats-server/releases/tag/v2.10.18-RC.3)?

**Comment by kozlovic** [comment]
@derekcollison @neilalexander @wallyqs I had a look at this and it is quite confusing. The report seem to indicate that this happens while consuming, yet the panic points to the start of the server when enabling JetStream for a specific account. 

But that being said, and the new information that the user reported errors such as "loadBlock error: message block data missing" seem to indicate that there is a problem loading message block, which sets the `mb.fss` to nil and then the caller does not check the error returned by `mb.loadMsgsWithLock()` and proceeds to call `mb.fss.Match()` which causes the panic.

Note that if `mb.fss` is nil, the panic will not stop at `mb.fss.Match`, but will indeed go down to when `t` is dereferenced. So a simple test like this:
```
func TestIvan(t *testing.T) {
	mb := &msgBlock{}
	mb.fss.Match([]byte("foo"), func(bsubj []byte, ss *SimpleState) {
	})
}
```
will indeed produce similar stack:
```
panic({0x2477780?, 0x308d720?})
	/usr/local/go/src/runtime/panic.go:920 +0x270
github.com/nats-io/nats-server/v2/server/stree.(*SubjectTree[...]).Match(0x28c5440, {0xc00029209d, 0x3, 0x3}, 0x2667348)
	/Users/ivan/dev/go/src/github.com/nats-io/nats-server/server/stree/stree.go:107 +0x171
github.com/nats-io/nats-server/v2/server.TestIvan(0x0?)
	/Users/ivan/dev/go/src/github.com/nats-io/nats-server/server/filestore_test.go:7641 +0xb1
testing.tRunner(0xc000092ea0, 0x2662358)
	/usr/local/go/src/testing/testing.go:1595 +0x239
created by testing.(*T).Run in goroutine 1
	/usr/local/go/src/testing/testing.go:1648 +0x82b
FAIL	github.com/nats-io/nats-server/v2/server	0.305s
```

I have found 13 invocations (in main branch) of loadMsgsWithLock() where the error returned by this function is not checked, and 4 or so where few lines down we invoke `mb.fss.Match()`.
I am not sure what is the proper approach if this function fails, but ignoring the error clearly leads to issues here. But returning error to the top layer may have caused the server to stop to start anyway.

**Comment by derekcollison** [comment]
Thanks @kozlovic

**Comment by TroyKomodo** [comment]
> Can you please try with [2.10.18-RC.3](https://github.com/nats-io/nats-server/releases/tag/v2.10.18-RC.3)?

I am unable to reproduce the crash it seemed to happen randomly. I just thought I would open this issue in case others have similar crashes or if this is just some obvious oversight with the pointer management.

**Comment by derekcollison** [comment]
We will add more protection.
