### ISSUE TITLE
packets lost: subscribe to more topics and get message packets quickly. The first message packet of some topics is lost.

### ISSUE THREAD

**Issue by chgz** [nats-io/nats-server#5677]
### Observed behavior

![20240719105700](https://github.com/user-attachments/assets/f479fa5d-36d3-45d6-a6f4-546f439374d8)
In my test scenario, service A received 2,000 connections, and each connection completed the request and response through these two topics.
During the test, there was no waiting time, and the message was responded to immediately. In each test, the first packet of dozens of connections was lost, and the other packets were fine.

All processes, including NATS, are in the same host, so the possibility of network problems can be ruled out.
Since only the first packet is lost, we don't need to consider the configuration of buffer or queue size.

![20240719110853](https://github.com/user-attachments/assets/bf951e70-dd79-4db9-8fea-ec4e9fa1b3ab)
I counted and output the message packets and found that at position 1 in the figure, all packets were sent, but at position 2, fewer packets were received.

![20240719111302](https://github.com/user-attachments/assets/860b0e0f-87b4-40bf-ae0b-fc80fb374f65)
Finally, add sleep 500ms after Subscribe, and the first packet loss will not occur.
Is there any critical condition problem?

### Expected behavior

When used correctly, there will be no packet loss.

### Server and client version

nats server v2.10.11
test code:
github.com/nats-io/nats-server/v2 v2.10.16
github.com/nats-io/nats.go v1.35.0

**Comment by neilalexander** [comment]
Can you please check against the latest versions? That'd be NATS Server 2.10.18 and nats.go 1.36.0.

**Comment by kozlovic** [comment]
@chgz After subscribing, you publish the request to `aaa` with the reply subject being the name of the subject you want ServerB to publish to. Are you using the same NATS client connection to subscribe to topic "push" and sending the request to "aaa"? If not, it could be very well possible that the subscription interest has not been processed by the server yet when server B starts publishing. If you were to use the same connection, it should not happen. Alternatively, use a `nc.Flush()` after the subscribe to ensure that the subscription interest is processed before sending the request.
This is why "sleeping" a bit solved the issue.

**Comment by chgz** [comment]
@kozlovic You are right!
I use the different NATS Client（conn） to complete publishRequest and receive reply msgs. 
And，i cancelled the sleep-step and added a nc.Flush after the subscription, and the problem of first packet loss did not occur！
