### ISSUE TITLE
scoped signing keys can't be used for KV/OBJ buckets.

### ISSUE THREAD

**Issue by chezgi** [nats-io/nats-server#5681]
### Observed behavior

it seems that we can't use scoped signing keys for  KV/OBJ buckets.
we have some inconsistencies in NATS design decisions.

1. user tags is only applied to a whole section of topic, not to subsections. 
  but in KV service APIs, bucket name is part of an topic section. like: `$JS.API.STREAM.INFO.KV_bucket1`
  therefore we cant set permissions based on bucket name. 
  for example i cant restrict `$JS.API.STREAM.INFO` service to my bucket based on tags on scoped signing key.
  the tag `robucket:bucket1` ,  doesn't match  `$JS.API.STREAM.INFO.KV_{{tag(robucket)}}`

2. user tags is lower case,  but topics are case sensitive. and bucket names always prefixed by uppercase `KV_`
  for example `robucket:KV_bucket1`  will be converted to `robucket:kv_bucket1` and cant be used for template in permissions
  therefore we cant use tags at all for restriction on buckets.
 
  **when nats topics are case sensitive, why tags are designed to be lower case?**

### Expected behavior

expected that i can use scoped signing keys to allow/deny some groups of users to read/write access on KV/OBJ buckets.
how we can improve scoped signing keys to be usable for KV/OBJ buckets?
it seams that:
- tag parsing must be case sensitive
- templates cab be applied to subsections, not whole sections

### Server and client version

in latest nats-server

**Comment by derekcollison** [comment]
@chezgi We realize we want better abstractions for authZ, especially within the realm of JetStream. The server's primitives are low level and core based on subject permissions. I think that is correct. The question we are working on is not only what the higher level authZ abstractions may or may not look like, but where they are interpreted.

**Comment by derekcollison** [comment]
There are several things we are considering. But good to understand that the core server will always operate on subject based permissions. We can abstract ACLs that can be decomposed into core subject based permissions for sure.

We will also deliver a core callout option for any subject, similar to auth callout but for any subject, that would allow JS requests to be filtered through an external entity which can allow, modify or reject the request itself..

**Comment by derekcollison** [comment]
What do you mean by tags in this context?

**Comment by ripienaar** [comment]
Users can have tags which a scoped signing key can expand with the `tag()` function, iirc these are always downcase.  To me this seems like a good idea, it would be easy to make mistakes otherwise

**Comment by derekcollison** [comment]
Looping in @aricart here as well.

**Comment by aricart** [comment]
the tag restriction makes that impossible - not sure how not to break anyone using this by changing it to case-sensitive - perhaps JWT could change to be case-insensitive but case preserving on the value portions of tags only. This would allow simple tags like hello, be lowercased, but tags like "n:HelloWorld" work

**Comment by aricart** [comment]
I think I would change the API on jwt to have additional `Add()` and perhaps have `--case-insensitive-tag` option to trigger its use. I know this is arcane but this functionality even if used not very often, has been like this since the beginning of time.

**Comment by derekcollison** [comment]
Thanks @aricart, can you and @ripienaar come to a decision here.

Seems like case sensitive is important for this use case for sure since we depend on subjects herd.

**Comment by aricart** [comment]
Working on the PRs...

**Comment by aricart** [comment]
@chezgi I have released [nsc v2.9.0](https://github.com/nats-io/nsc/releases/tag/v2.9.0) which enables the use case. Let me know of any issues in the nsc repo

**Comment by aricart** [comment]
@chezgi I have retracted the `--strict-tags` feature on NSC, for now tags have to be downcased - this means that there's a new version of [JWT](https://github.com/nats-io/nsc/releases/tag/v2.10.0) and [nsc](https://github.com/nats-io/nsc/releases/tag/v2.10.0) - However until we can figure out a better strategy for case-preserving tags, I have opened a PR that will allow you to create templates where you can specify `KV_{{tag(something}}` which are not bounded by a subject token - see https://github.com/nats-io/nats-server/pull/5981

**Comment by aricart** [comment]
yes that will work. Realize that name/account-name are possibly really bad options if the account/user name has a space.

**Comment by aricart** [comment]
You can also do `my.topic.for_{{tag(name)}}` but the tag will be in lowercase
