### ISSUE TITLE
Slow Consumer policy

### ISSUE THREAD

**Issue by mcuadros** [nats-io/nats-server#57]
Can you explain the behaviour of a " Slow Consumer"? Why the connection is closed?
https://github.com/apcera/gnatsd/blob/7d820b762fbcc58264b7d688bd869e5949e8d175/server/client.go#L625

I am working in a stress tool and when i send 25k message to a client then the client becomes a slow consumer (not slow just busy) and the connection is closed.

https://github.com/mcuadros/natstress

Regards

**Comment by alvarolm** [comment]
is there a way to adjust the timeout that makes throw out the "slow consumer" err?

**Comment by derekcollison** [comment]
Currently no, but am looking into it. The head for master does have the ability to adjust how much we buffer before we enter the slow consumer state, but not the write timeout parameter.
