### ISSUE TITLE
Stream source | removing and recreating a source config replicates only messages after the last already replicated sequence number

### ISSUE THREAD

**Issue by pricelessrabbit** [nats-io/nats-server#5847]
### Observed behavior

after following the steps to reproduce:
- the (new) `source` stream contain 6 messages (m6, m7, m8, m9, m10, m11).
- the `destination` stream contain 6 messages (m1, m2, m3, m4, m5, m11). this happens because it replicates starting from the highest source sequence number.

### Expected behavior

I expect that after removing the `destination` sources config and re-creating it, the sourcing reset and all the messages in `source` are imported in `destination` (m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11)

### Server and client version

nats server 2.10.19

### Steps to reproduce

- create a `source` stream.
- create a `destination` stream that sources from `source`.
- send 5 messages (m1, m2, m3 ,m4, m5) in `source` . `destination` replicates the messages.
- delete and recreate `source` stream (messages seq restarts from 1).
- edit `destination` config to remove sources, save and re-edit recreating the sourcing from `source`.
- send  6 messages on `source` (m6, m7, m8, m9, m10, m11).

**Comment by derekcollison** [comment]
We dynamically figure out where to start for each source based on contents of destination stream. If you want to reset you can delete and recreate the destination stream vs source.

**Comment by pricelessrabbit** [comment]
probably i'm missing something, but deleting the destination stream for me is not a viable solution. concrete use case:
- destination stream on account HUB is aggregating streams from 3 other accounts (A , B, C) sourcing from them.
- some consumers are working in HUB stream
- at same point (suppose at seq number 10000) tenant A deletes and recreate his stream,

in this case i loose the first 10000 messages of A stream (HUB restart the replication at 10001), and deleting the entire HUB stream can be an issue because other streams are being aggregated in it and there are consumers working

**Comment by jnmoyne** [comment]
You should purge the stream being sourced instead of deleting it and re-creating it, as that doesn't reset the sequence number and the sourcing happens how you expect it to.

**Comment by pricelessrabbit** [comment]
@jnmoyne absolutely right but imho purge (or maybe re-create the source using manually setting the firsSeq) assumes that sourced stream "knows" that is being sourced so it cannot be deleted and is error prone. 

It would be great if setting a source ensures that all the messages are considered as unique (like if it have a uid) and always replicated automatically also in case of source deletion and re-creation without any manual intervention or workaround. 

It would be much more reliable especially if sourcing from other tenants that can decide to delete a stream unexpectedly.
