### ISSUE TITLE
backoff time overrides ack_wait time using nats.java [v2.10.18]

### ISSUE THREAD

**Issue by sudo-ankitmishra** [nats-io/nats-server#5861]
### Observed behavior

when providing ack_wait time as 60000 i.e 60secs and backoff as 3000 i.e 3 secs. Nats JAVA client sets ack_wait time to 3.00 secs. And If I don't pass backoff time it works properly then.

### Expected behavior

Want backoff time not to override ack_wait time.
Is there any relation between two?

### Server and client version

server: 2.10.18
client:  "io.nats:jnats:2.20.2"

### Host environment

host: kubernetes 1.26
3 Node Nats cluster deployment.

Also reproduced with docker container. Host [Linux-Ubuntu]

### Steps to reproduce

```
ConsumerConfiguration.builder()
      .filterSubjects("test.*")
      .ackPolicy(io.nats.client.api.AckPolicy.All)
      .ackWait(Duration.ofMillis(60000L))
      .backoff(Duration.ofMillis(3000L))
      .durable("sample-durable-consumer")
      .build()
```

```
Configuration:

                    Name: sample-durable-consumer
               Pull Mode: true
          Filter Subject: test.*
          Deliver Policy: All
              Ack Policy: All
                Ack Wait: 3.00s
           Replay Policy: Instant
         Max Ack Pending: 1,000
       Max Waiting Pulls: 512
                 Backoff: 3s
```

when backoff is not passed
```
ConsumerConfiguration.builder()
      .filterSubjects("test.*")
      .ackPolicy(io.nats.client.api.AckPolicy.All)
      .ackWait(Duration.ofMillis(60000L))
      // .backoff(Duration.ofMillis(3000L))
      .durable("sample-durable-consumer")
      .build();
```

```
Configuration:

                    Name: sample-durable-consumer
               Pull Mode: true
          Filter Subject: test.*
          Deliver Policy: All
              Ack Policy: All
                Ack Wait: 1m0s
           Replay Policy: Instant
         Max Ack Pending: 1,000
       Max Waiting Pulls: 512
```
Help me understand if I am missing anything.

**Comment by MauriceVanVeen** [comment]
This is actually intended behaviour. I tried it out with the Go client and realized this is checked by the server. 

Being given one or more `Backoff` durations, the `AckWait` is overwritten to the first entry in that list. In this case both will become 3 seconds. (Server code for reference: [consumer.go#L459](https://github.com/nats-io/nats-server/blob/main/server/consumer.go#L459))

By default without a manually specified `Backoff` you could see the `AckWait` as the backoff. Retrying to deliver a message after the "backoff" of `AckWait`, which is 30s by default.
If you specify a backoff, that becomes your `AckWait`. Either being one value, but probably more values with linear or even expontential backoff. First waiting 5s for the ack before redelivering, then waiting 30s before redelivering etc. etc.

This is also how it's documented:
> A sequence of durations controlling the redelivery of messages on nak or acknowledgment timeout. Overrides ackWait. The sequence length must be less than or equal to MaxDelivery. If backoff is not set, a nak will result in immediate redelivery. E.g., MaxDelivery=5 backoff=[5s, 30s, 300s, 3600s, 84000s] will re-deliver a message 5 times over one day.
https://docs.nats.io/nats-concepts/jetstream/consumers


So anyway, TLDR, you either set `AckWait` which is one value that's used as time between redeliveries, or you use `Backoff` to represent more/other values to be used between redeliveries. But not both.

**Comment by sudo-ankitmishra** [comment]
Thanks.
