### ISSUE TITLE
Publish to the mirrored stream succeeds on the leaf node even if the hub node is down 

### ISSUE THREAD

**Issue by niks3089** [nats-io/nats-server#5942]
### Observed behavior

I have 2 leaf nodes which mirrors the stream from the hub using jetstream. When I bring down the hub node, I am still able to publish to that stream via the leaf node. I don't want to publish directly to the hub but to the leaves since I will be adding few more. 

### Expected behavior

I would expect that the publish on the leaf for other subjects to succeed but for the mirrored stream, I would expect this to fail. This causes a problem because the application thinks it has successfully send the message but the message is not persisted and not delivered to the clients listening on the other leaf node so the publish shouldn't work at all 

### Server and client version

```
nats-server --version
nats-server: v2.10.14
```

```
nats --version
0.1.5
```

### Host environment

NATS server running on ubuntu 22.04 and the cli is being run on the mac

### Steps to reproduce

- Create multiple streams using jetstream on the hub node 
- Mirror those stream on the leaf nodes 
- Pub/Sub messages on the stream node via leaf node and check `stream ls` to see the message is being sent via the stream 
-  Bring down the hub node 
-  Publish the messages on the mirrored stream. Publish is successful and messages are received on the same leaf node 
- Messages are not received on the other leaf node 
- Bring up the hub. The messages are lost and never delivered to the other leaf nodes.

**Comment by roeschter** [comment]
The description is unfortunately incomplete as I cannot tell who exactly is publishing where on which subject. At minimum we would need all the config files and nats-cli commands which show what exactly is being done.

From what I can guess though, this is not a bug. I suspect you are publishing a plain NATS message rather than using the Jetstream API.

PS: You may want to discuss this on the nats.io slack channel.

**Comment by niks3089** [comment]
Hi, I just doing `nats pub project_stream "hello world" --count 10` where `project_stream` is the jetstream. This is being sent to the leaf node and gets sent to the hub and I see it when I run `nats stream ls`. When I bring the hub down, the message is sent to the plain NATS instead of publish failing. Can you confirm that if the hub is down, then the publish to the mirrored stream should fail?

**Comment by ripienaar** [comment]
You should use jetstream compatible publish - in code you would use the jetstream context publish function on CLI, for now, use “nats req” not pub and you will get errors.

**Comment by niks3089** [comment]
```
    let client =
        async_nats::ConnectOptions::with_user_and_password(username.into(), password.into())
            .connect(host)
            .await?;

    // Serialize the project event to bytes
    let mut project_buf = Vec::new();
    project_event.encode(&mut project_buf)?;
    let bytes_payload = Bytes::from(project_buf);

    // Publish the project event to the "project_stream" subject
    client
        .publish("project_stream.config", bytes_payload)
        .await?;
    println!("Project event sent successfully!");
 ```
 
 I am publishing the message like this and it fails when publishing to hub but succeeds when publishing to a leaf node

**Comment by neilalexander** [comment]
What is the `nats stream info` of the streams in question?

**Comment by Jarema** [comment]
@niks3089 your snippet does not use `jetstream` publish.

```rust
let jetstream = async_nats::jetstream::new(client);
jetstream.publish("project_stream.config", bytes_payload).await?.await?;
```

**Comment by niks3089** [comment]
> What is the `nats stream info` of the streams in question?

```
% nats stream info
[mdev-hub] ? Select a Stream project_stream
Information for Stream project_stream created 2024-10-16 17:27:25

              Subjects: project_stream.>
              Replicas: 1
               Storage: File

Options:

             Retention: Limits
       Acknowledgments: true
        Discard Policy: Old
      Duplicate Window: 2m0s
            Direct Get: true
     Allows Msg Delete: true
          Allows Purge: true
        Allows Rollups: false

Limits:

      Maximum Messages: unlimited
   Maximum Per Subject: unlimited
         Maximum Bytes: unlimited
           Maximum Age: 1d0h0m0s
  Maximum Message Size: unlimited
     Maximum Consumers: unlimited

Cluster Information:

                  Name: momentum-stage-root
                Leader: momentum-stage-root-lax

State:

              Messages: 0
                 Bytes: 0 B
        First Sequence: 46
         Last Sequence: 45 @ 2024-10-18 23:39:54
      Active Consumers: 0
 ```

> @niks3089 your snippet does not use `jetstream` publish.
> 
> ```rust
> let jetstream = async_nats::jetstream::new(client);
> jetstream.publish("project_stream.config", bytes_payload).await?.await?;
> ```

Tried with `jetstream.publish` and I am still able to publish to the leaf node when hub is down

**Comment by Jarema** [comment]
What does the returned `ack` for published messages say?
Can you please show the `nats stream report` & `nats stream info` on the leaf and the mirror that is there?

**Comment by niks3089** [comment]
> @niks3089 your snippet does not use `jetstream` publish.
> 
> ```rust
> let jetstream = async_nats::jetstream::new(client);
> jetstream.publish("project_stream.config", bytes_payload).await?.await?;
> ```

I was missing an `.await` and adding it fixes it. Wow.
