### ISSUE TITLE
first_info_timeout in the leaf remotes config returns error

### ISSUE THREAD

**Issue by TarasLykhenko** [nats-io/nats-server#6001]
### Observed behavior

If the first_info_timeout is set in the leaf remote config returns the error `unknown field "first_info_timeout"`.

### Expected behavior

No error and the value is set.

### Server and client version

nats-server: v2.10.21

**Comment by wallyqs** [comment]
Hi, this was not included in the v2.10 series so but it is available in one of the v2.11 nightlies or preview releases.
