### ISSUE TITLE
AWS Fargate Memory slowly increasing/leak over time

### ISSUE THREAD

**Issue by NevinDry** [nats-io/nats-server#6006]
### Observed behavior

We observe that our aws fargate containers serving clustered NATS have their memory usage increasing over time :

![image](https://github.com/user-attachments/assets/be49e13f-4ea5-4630-9819-c27f8bb17a96)
(metric : ecs.fargate.mem.usage)

What is weird is we can observe this behavior on our STG1 environement but not on our DEV environment. 
These two environments have no significant activity, and are deployed the same way through IaC. Nats is deployed using clustering on AWS fargate. 

The difference in memory usage between the two envs is very significant : 
dev:
![image](https://github.com/user-attachments/assets/a41f8276-a56b-4a1a-aa10-b3ef85ac17a2)

stg1:
![image](https://github.com/user-attachments/assets/c6f6482d-ae84-4fc6-a2b2-67f7127765cd)

If we look at the NATS memory metrics, both environements are stable : 
dev:
![image](https://github.com/user-attachments/assets/f60108da-d8ab-4de3-8277-fd7ff1b83c72)

stg1:
![image](https://github.com/user-attachments/assets/7163fcc4-c2d7-4586-92a1-2e8aefc0aacb)

There must be a leak somewhere but we are unable identify it.

### Expected behavior

The fargate containers memory shouldn't be increasing over time and should stay stable.
It should follow the NATS memory metrics and stay stable.

### Server and client version

Server version : 2.10.18
Go : go1.22.5

### Host environment

NATS clustering inside AWS fargate without jetstream.

Operating system/Architecture
Linux/X86_64
CPU | Memory
2 vCPU | 4 GB
Platform version
1.4.0
Launch type
FARGATE

Log-router and Datadog as side containers.

**Comment by neilalexander** [comment]
Can you please report the output of `free -m` within the containers when the memory usage is high?

**Comment by NevinDry** [comment]
Thanks for you answer @neilalexander. Our stg1 containers restarted yesterday so the memory has not increased much yet. I will keep you updated when the memory is high.
Here is the free command output in **stg1** ATM :

STG1 
CPU | Memory
1 vCPU | 2 GB
NODE 
/ # free -h
              total        used        free      shared  buff/cache   available
Mem:           3.6G      565.7M      292.2M      540.0K        2.8G        2.8G
Swap:             0           0           0

SEED
CPU | Memory
1 vCPU | 2 GB
/ # free -h
              total        used        free      shared  buff/cache   available
Mem:           3.8G      580.9M      275.3M      540.0K        2.9G        2.9G
Swap:             0           0           0


On **dev**, where the memory is stable, here is a free command output (note that the CPU/Memory provisioning is not the same, does this could have an impact ?) : 
DEV

NODE
CPU | Memory
.25 vCPU | .5 GB
/ # free -h
              total        used        free      shared  buff/cache   available
Mem:         927.8M      547.5M       67.0M      540.0K      313.3M      240.1M
Swap:             0           0           0


SEED
CPU | Memory
.25 vCPU | .5 GB
/ # free -h
              total        used        free      shared  buff/cache   available
Mem:         927.8M      559.9M       80.8M      544.0K      287.1M      229.2M
Swap:             0           0           0

(note that the total/used memory for both env are higher than the provisioned memory we set on our containers.

Thank you for your help.

**Comment by neilalexander** [comment]
What stands out to me is the `buff/cache` utilisation, which makes me think you're falling victim to kubernetes/kubernetes#43916. In short, Kubernetes is considering the kernel page cache when deciding whether a pod is under memory pressure. I suspect if you look at the RSS size (as is reported by `nats server ls` for example) that you'd see the process utilisation itself is stable.

Do you set both a memory request and a memory limit, or just one or the other?

**Comment by NevinDry** [comment]
Hi @neilalexander, we did not have memory soft/hardlimit set on our fargate containers. We are going to configure it and see what happens, I will keep you updated. 
On another note,  we observed that only containers with more than default memory value (512M) have their memory increasing over time.
Thanks for your guidance !

**Comment by NevinDry** [comment]
Hello @neilalexander,

Just to keep you updated, we found a way to mitigate this issue, let me try to explain.

The first important thing to notice is that the memory increase only occur on Fargate Memory metric, the memory issue does not appear in the NATS running inside the container.
To prevent the Fargate container to restart when it reaches max memory, we setup a value for the container "hard-limit" with the same value as the max memory. With this, our container won't exceed the max memory and it won't restart.

To monitor our Containers, we are now basing our observation and alerts on the NATS memory metric, not the Fargate memory. That way we can see what is the real memory used by our container. Here are both metrics, as you can see the NATS memory is stable :

![image](https://github.com/user-attachments/assets/19141f35-7343-4490-b61d-f1736efbe1e4)

There is still a weird behavior from Fargate memory, but it's not problematic anymore. We suspect an issue with the GO memory management with Fargate but we are not sure.

Hope it helps, thank you for helping us investigating.
