### ISSUE TITLE
Unresolved: NATS orphaned streams deleted after Snapshot corrupt, too short error

### ISSUE THREAD

**Issue by Zetanova** [nats-io/nats-server#6188]
### Observed behavior

The defect of [issue ](https://github.com/nats-io/nats-server/issues/4410) still persist.

Version: 2.9.25

I had it now 2 time, after 2 of 3 nodes restarted at the same time all mem and disk streams got "Detected orphaned stream"
including KV streams

What happend:

Two nodes got killed and restarting
survivor node 1 "Healthcheck failed: "JetStream has not established contact with a meta leader"
Node 2 and 3 started again and recovered the streams with messages including KV
"Restored 15 messages for stream 'ACY...XUH2I > KV_myconfig'
followed by "RAFT [yrzKKRBu - meta] Snapshot corrupt, too short" on both restarting nodes
node 2 and 3 cleared the streams in the "JetStream cluster recovering state" and after "Server is ready" with
"Detected orphaned stream 'ACY...XUH2I> KV_myconfig', will cleanup"

### Expected behavior

No data loss should occur.

### Server and client version

nats official container version: 2.9.25

### Host environment

kubernetes

### Steps to reproduce

kill 2 of 3 nodes.

**Comment by neilalexander** [comment]
There have been a ton of clustering improvements since 2.9.25, with many improvements already in GA in 2.10.22 and even more due to land in 2.10.23 next week (although release candidates are already available). Can you please upgrade to either the 2.10.22 GA or (preferably) 2.10.23-RC.7 and let us know how things look?

**Comment by wallyqs** [comment]
This would have been fixed by https://github.com/nats-io/nats-server/pull/5767
