### ISSUE TITLE
Issue with NATS Cluster Health Check and Jetstream on OpenShift: Recommendations Needed [v2.10.19]

### ISSUE THREAD

**Issue by mohamedsaleem18** [nats-io/nats-server#6217]
### Observed behavior

A NATS cluster with 3 nodes (Jetstream enabled) is installed on Red Hat OpenShift. Due to an issue with Jetstream, the NATS cluster shut down and was no longer accepting Jetstream connections. When we restarted the NATS pods one by one, the cluster formed with only two pods. One pod failed to start, throwing a "health check failed" error. As a result, the NATS cluster is up and running with only 2 NATS servers. Please find the NATS pod logs below. Could you please provide your recommendations to resolve this issue?

### Expected behavior

NATS cluster should be up and running with 3 nodes.

### Server and client version

NATS server --version : 2.10.19

### Host environment

Redhat OpenShift
[nats.txt](https://github.com/user-attachments/files/18012275/nats.txt)

**Comment by derekcollison** [comment]
We would need quite a bit more information. 

Might be good to consider a support agreement with Synadia.

**Comment by wallyqs** [comment]
hi @mohamedsaleem18, what you can try is to change the readiness probe to be done instead on `/varz` or change the `readinessprobe` to be `/healthz?js-server-enabled=true` instead, that way the service will not detach whenever you stop one of the pods. We are changing from this default settings in the next version.

**Comment by mohamedsaleem18** [comment]
hi @wallyqs,
        Thank you for your response. The readiness and liveness probes have already been configured as per your recommendation. Please refer to the image below.

The requirement is to trigger alerts when the NATS cluster stops accepting consumer connections. This typically occurs when the Jetstream state is corrupted due to storage issues or network connectivity problems.

<img width="218" alt="image" src="https://github.com/user-attachments/assets/0000e718-0329-4146-8bff-761f96a63c0c" />

**Comment by wallyqs** [comment]
hi @mohamedsaleem18 the readiness probe needs to be changed as well to be: `js-enabled-only` like the liveness probe, as it is configured right now on a restart the service will stop responding once the cluster loses meta leader quorum so we want to avoid that from happening

**Comment by mohamedsaleem18** [comment]
Thank you @wallyqs
