### ISSUE TITLE
expose stats about cluster reconnects/disconnects/errors

### ISSUE THREAD

**Issue by ripienaar** [nats-io/nats-server#623]
- [ ] Defect
 - [x] Feature Request or Change Proposal
 
#### Use Case:

improve visibility to operators of nats clusters
 
#### Proposed Change:

It would be good to keep stats about reconnects/disconnects/errors and maybe expose those in `/routez` or elsewhere thats more appropriate
 
#### Who Benefits From The Change(s)?

people who run clusters
 
#### Alternative Approaches

n/a

**Comment by bruth** [comment]
This is an old issue and appears to have been satisfied. We can open a new one if there are any remaining items.
