### ISSUE TITLE
Allow enabling JS for an account in an embedded nats server

### ISSUE THREAD

**Issue by Codebreaker101** [nats-io/nats-server#6261]
### Observed behavior

Currently there is no API to enable JetStream for an account in an embedded NATS. More details in [this discussion](https://github.com/nats-io/nats-server/discussions/6242). In summary, to enable jetstream for an account I must call `EnableJetStream()` function on the `*server.Account`. But to create users attached to an account I need to specify a `*server.Account` before the server has been created in the `*server.Options`. I could create an account using `server.NewAccount("APP")` but then this account will not be connected to the server and calling `EnableJetStream` will result in an error. 

### Expected behavior

For there to be a way to enable JetStream for an account inside go application that embeds NATS server.

### Server and client version

nats-server v2.10.23

**Comment by derekcollison** [comment]
You can lookup an account via `func (s *Server) LookupAccount(name string) (*Account, error)` and then as you note call `func (a *Account) EnableJetStream(limits map[string]JetStreamAccountLimits) error` on that account.
