### ISSUE TITLE
Req/reply in two-direction leaf connection

### ISSUE THREAD

**Issue by Naymi** [nats-io/nats-server#6263]
### Observed behavior

request/reply don't works for any configuration of leaf nodes connections

### Expected behavior

request/reply works for any configuration of leaf nodes connections

### Server and client version

nats-server: v2.10.20
nats-cli 0.1.4

### Host environment

MacOS 15.1.1 M2 Max

### Steps to reproduce

Start 3 servers 

```
# a.conf

listen: 127.0.0.1:4222;

leafnodes {
  listen = "0.0.0.0:7422"
}

```

```
# bridge.conf

listen: 127.0.0.1:4422;

leafnodes {
  remotes = [
    {
      url: "nats://127.0.0.1:7422"
    },
    {
      url: "nats://127.0.0.1:7522"
    },
  ]
}
```

```
# b.conf

listen: 127.0.0.1:4322;

leafnodes {
  listen = "0.0.0.0:7522"
}

```

```sh
nats-server -c a.conf &
nats-server -c b.conf &
nats-server -c bridge.conf
```

Start replier:

```sh
nats reply test test --server localhost:4222
```

Send request:

```sh
nats req test test --server localhost:4322
```

Received:

```
16:50:26 Sending request on "test"
16:50:26 No responders are available
```

Send request from bridge:

```
nats req test test --server localhost:4422
```

Received:

```
16:50:36 Sending request on "test"
16:50:36 Received with rtt 561.291µs
test
```

**Comment by derekcollison** [comment]
Please send complete configuration for the servers.

Req/Reply does work properly across leafnodes.

**Comment by kozlovic** [comment]
@Naymi This is not have you daisy-chain leaf nodes. In your setup "b" does not know and cannot reach "a". Instead, your "bridge" should have a leafnode listen port open, have only a single remote to "a", and "b" does not need a leaf nodes listen port, but instead just the remote to "bridge". In this case, the request from "b" will be forwarded to "a". I just tried and it works.

**Comment by Naymi** [comment]
We need to use exactly this topology due to a number of network limitations

**Comment by kozlovic** [comment]
> We need to use exactly this topology due to a number of network limitations

Ok, then we need to make one of the connection from the bridge to behave as if it was in the other direction. To that effect, you can set the `hub` property to `true` in one of the remote definition, say the one to `b` server:
```
{
      url: "nats://127.0.0.1:7522"
      hub: true
},
```

**Comment by Naymi** [comment]
Thanks for the suggestion! Can this be done without hub: true? Unfortunately, due to network restrictions, if I understand this flag correctly, we will not be able to use it.
