### ISSUE TITLE
System Privileges Issue in NATS Cluster Administration on OpenShift

### ISSUE THREAD

**Issue by mohamedsaleem18** [nats-io/nats-server#6275]
### Observed behavior

A NATS cluster (version 2.10.19) with 3 nodes is running on Red Hat OpenShift. A system account has been configured for cluster administration. When attempting to kick a client connection, the following error occurs: "nats: error: server request failed, ensure the account used has system privileges and appropriate permissions." Can you please assist with this issue?

```hcl
"accounts": {
  "$SYS": {
    "users": [
      {
        "user": "xedeusadmin",
        "password": "xyz"
      },
      {
        "user": "middlewareadmin",
        "password": "xyz"
      }
    ]
  }
```

<img width="938" alt="image" src="https://github.com/user-attachments/assets/ebedbaf8-714d-4e4f-bd90-8ff5c3d2677c" />

### Expected behavior

Client connection should be closed.

### Server and client version

nats CLI version:  0.1.5
nats server version : 2.10.19

**Comment by mprimi** [comment]
The `$SYS` account you created is not marked as a system account, I think you are missing the following:
```
system_account: $SYS
```

Here's a snippet from a configuration I know to work correctly:
```
accounts: {
    SYS: {
        users: [
            {user: sys, password: secret}
           ]
    },
}
system_account: SYS
```

**Comment by derekcollison** [comment]
If in server config mode $SYS is correct and can be upgraded to include users without the designation above.

**Comment by mohamedsaleem18** [comment]
@derekcollison ,  Based on your response, it seems the configuration in our end is correct, i.e "$SYS" is system account.  Can you please clarify the reason for the privilege error ?

**Comment by derekcollison** [comment]
Will take a look.

**Comment by Jarema** [comment]
@mohamedsaleem18 can you please retest?

Make sure that the config is properly passed and used. Maybe to limit layers of indirection - on locally spawn nats-server and explicitly passed config.

**Comment by mohamedsaleem18** [comment]
Thank you for your support. It works.
