### ISSUE TITLE
Decentralized AuthCallout Service not getting triggered on client connect

### ISSUE THREAD

**Issue by junpreetham** [nats-io/nats-server#6303]
### Observed behavior

I'm currently implementing my own auth callout service using NATS. I initially followed this [video](https://www.youtube.com/watch?v=VvGxrT-jv64) and everything worked perfectly. But now I've implemented the NATS full resolver in my config file. This does not allow me to explicitly set the auth_callout block in the config file. 

```
# Operator named test123
operator: <JWT>
# System Account named SYS
system_account: AAQP7PU45B6K4ZCYV2N7DY2PF3GDUN7CP5XHJZYK7T7JYY7BQKQU7FPN

# configuration of the nats based resolver
resolver {
    type: full
    # Directory in which the account jwt will be stored
    dir: './jwt'
    allow_delete: true
    interval: "2m"
    # Timeout for lookup requests in case an account does not exist locally.
    timeout: "1.9s"
}

resolver_preload: {
	AAQP7PU45B6K4ZCYV2N7DY2PF3GDUN7CP5XHJZYK7T7JYY7BQKQU7FPN: <JWT>
}
```

So I followed [this tutorial](https://natsbyexample.com/examples/auth/callout-decentralized/cli). I set up the AUTH account and a user named "auth", created a XKey, edited the "authcallout" config using NSC as stated in the tutorial and pushed it to the NATS server, again, using NSC. 

I then generated a creds file for the "auth" and used it to connect with the NATS server. This worked as expected. 
The code for the auth service (untouched while migrating from centralized to decentralized), 

```
var credsFile = await readFileSync("./auth.creds", "utf8");
credsFile = new TextEncoder().encode(credsFile);
var credsAuth = credsAuthenticator(credsFile);

var natsClient = await connect({ 
    servers: "nats://0.0.0.0:4222",
    authenticator: credsAuth
});

console.log("Connected to server!")

// Getting keypair from seed / secret key
var key = new TextEncoder().encode(secretKey);
var issuerKey = fromSeed(key);

const authService = await natsClient.services.add({
    name: `auth_service`,
    version: `1.0.0`,
    description: `Authorization service for relay`,
});

authService.stopped.then((err) => {
    console.log(`Service stopped ${err ? err.message : ""}`);
});

authService.addEndpoint("AUTH", {
    subject: "$SYS.REQ.USER.AUTH",
    handler: async (err, msg) => {
        console.log("Received request");
    }
});
```

But now when i try connecting to connect a client to this the server, i get an "AUTHORIZATION_VIOLATION" error (which is expected) but the service above does not execute. It worked in the centralized auth callout setup but not with the decentralized setup. 

I'm new to NATS and i can really use some help! Thank you so much!

### Expected behavior

Auth service should execute when client is trying to connect

### Server and client version

nats-server: v2.10.22

**Comment by aricart** [comment]
@junpreetham Can you print the JSON equivalent of the account where your callout lives, and the JWT for the user that you expect to connect using the callout.

If using nsc or something, do `nsc describe jwt --json -f <file>`

**Comment by junpreetham** [comment]
Hey @aricart, so the user JWT is a custom JWT i generated using the jsonwebtoken npm package. 

Here is the a description of the account JWT, 
```
{
 "iat": 1735217208,
 "iss": "OC5CGIWY243KSGMP4LHAJY375NX4WML7HHJEIXAQGU5HA5DJR26QDCAE",
 "jti": "H32OBHZZM3OC3UAJ4CQM2QU43TFR7EMLF6W5J2RMDKOGDS47DCJQ",
 "name": "AUTH",
 "nats": {
  "authorization": {
   "allowed_accounts": [
    "*"
   ],
   "auth_users": [
    "UDD5EOG7Q4OMLYD3MGLTEYYNIVFDW2MT26FQIGXRTDNGVMLX3GP2CQJX"
   ],
   "xkey": "XCEZM6LMIXAIC25GOQ5OPTJOZUXMPCSMH4H5KG6XCBXFO3TUGMJEWS6R"
  },
  "default_permissions": {
   "pub": {},
   "sub": {}
  },
  "limits": {
   "conn": -1,
   "consumer": -1,
   "data": -1,
   "disk_max_stream_bytes": -1,
   "exports": -1,
   "imports": -1,
   "leaf": -1,
   "max_ack_pending": -1,
   "mem_max_stream_bytes": -1,
   "payload": -1,
   "streams": -1,
   "subs": -1,
   "wildcards": true
  },
  "signing_keys": [
   "ABFK7AC7FQRAL43NEO4DSC2B576RVY7YUQJNSAG5QNZVH2QMJKPCNSH4"
  ],
  "type": "account",
  "version": 2
 },
 "sub": "ADUJNAFGXETZQYVZJXIMDIXOVST6LUJLCKCFQCWEZKZA4WNCLY57BAFH"
}

```

**Comment by aricart** [comment]
So above you have the account that will issue JWTs , but the user is indeed the next important part, because your service should be connecting with a JWT that identifies that `UDD5EOG7Q4OMLYD3MGLTEYYNIVFDW2MT26FQIGXRTDNGVMLX3GP2CQJX`.

**Comment by aricart** [comment]
Please show me the user JWT for the service, and one for the token you give users to connect to NATS.

**Comment by junpreetham** [comment]
JWT description of user "auth" which is a user under account "AUTH"

```
{
 "iat": 1735217147,
 "iss": "ADUJNAFGXETZQYVZJXIMDIXOVST6LUJLCKCFQCWEZKZA4WNCLY57BAFH",
 "jti": "3SURT3QTEYC7JN2O67LPQS4ONADU2KW25SESSHICHLY3JOMRCFBA",
 "name": "auth",
 "nats": {
  "data": -1,
  "payload": -1,
  "pub": {},
  "sub": {},
  "subs": -1,
  "type": "user",
  "version": 2
 },
 "sub": "UDD5EOG7Q4OMLYD3MGLTEYYNIVFDW2MT26FQIGXRTDNGVMLX3GP2CQJX"
}
```

As for the user JWT, it is a JWT generated used the `jsonwebtoken` npm package, so `nsc describe` will not work with it. My strategy here is to decode it using a secret key and using the data from the JWT, fetch some data from a DB and construct an authorization & user claim. I would then take this and generate a JWT that service will respond with to complete authentication

**Comment by junpreetham** [comment]
Here's the client JWT anyways => eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiQXJqdW4iLCJwcm9qZWN0X2lkIjoidGVzdF9wcm9qZWN0Iiwib3JnYW5pemF0aW9uIjoiYmV5b25kX3JvYml0aWNzIiwiaXNfdmFsaWQiOnRydWUsImlhdCI6MTczMDczNTUzOX0.AMkp492uQC0BgPjcA3cy8FId9gGw8nHyZHDK5o3MyMk

**Comment by aricart** [comment]
That JWT won't trigger the callout to work....

```
{
  "user": "Arjun",
  "project_id": "test_project",
  "organization": "beyond_robitics",
  "is_valid": true,
  "iat": 1730735539
}```

**Comment by aricart** [comment]
The JWT must be a credentials to connect to the server on the account that will interact with the callout.

**Comment by junpreetham** [comment]
Wow how did you decode it without the secret key? Because this is the exact same key i used to connect to the server when i tried the centralized auth callout as specified in the video and it worked. 

Let me try that and report back

**Comment by junpreetham** [comment]
Okay so i created an account and user using [this example](https://gist.github.com/theBoEffect/ccdfe18cff5ec7876c784a3c7a45d307)

Here are the JWT descriptions,
Account:
```
{
 "aud": "NATS",
 "iat": 1735446041,
 "iss": "OC5CGIWY243KSGMP4LHAJY375NX4WML7HHJEIXAQGU5HA5DJR26QDCAE",
 "jti": "6PuDOLrUCTQxGVUyif9mG8mhFFCHNd2v6A/BMLYefs9soFJVQ7ZB2qgPI1yCjpK/dAneywqtmzsRErvOm9SUrQ==",
 "name": "astroscale",
 "nats": {
  "limits": {
   "conn": -1,
   "data": -1,
   "disk_storage": -1,
   "exports": -1,
   "imports": -1,
   "leaf": -1,
   "mem_storage": -1,
   "payload": -1,
   "subs": -1,
   "wildcards": true
  },
  "type": "account",
  "version": 2
 },
 "sub": "ADH5ON5TPMA4HM4S35SKTBQQN5Z74JRQUCK6HBHVFM7U4YAFHEMJ52R5"
}
```

User:
```
{
 "aud": "NATS",
 "iat": 1735446041,
 "iss": "ADH5ON5TPMA4HM4S35SKTBQQN5Z74JRQUCK6HBHVFM7U4YAFHEMJ52R5",
 "jti": "IiGczSHFL+RtYwCGNoOnzsuky8Z/EhuDzFNYMGOCzpNwoWA/oOCb/YJYBUBfC2ra9kOP/vI1kdicVnR59f3aiA==",
 "name": "test user",
 "nats": {
  "data": -1,
  "issuer_account": "ADH5ON5TPMA4HM4S35SKTBQQN5Z74JRQUCK6HBHVFM7U4YAFHEMJ52R5",
  "payload": -1,
  "pub": {},
  "sub": {},
  "subs": -1,
  "type": "user",
  "version": 2
 },
 "sub": "UDQBYVVISGHX3P66TOQ6254UBUAVUXAYXD35A4DNQNPOT5GXMQJ4CLMI"
}
```

I can verified that worked because the `astroscale` account got pulled onto my system using `nsc pull`. I tried connecting to the server from my client using the creds file, this time, i got a `TIMEOUT` error instead of an `AUTHORIZATION_VIOLATION`.

The auth callout i described in the main question is running but it did not execute. Looking forward to your reply

**Comment by aricart** [comment]
Just really short way:

- The callout account configuration specifies an user ID (the subject of an user) that will be the _service_ for the callout. The account also specifies for what accounts it can return users..

These are the `auth_users` and `allowed_acocunts`, your service will connect with the specified user to nats (doesn't go through the callout). Generate an user on the callout account that has no permissions, and give that as credentials to users you want to authenticate via the callout. Provided your service is running it will get the requests. The User JWT generated by the callout must be signed by an account in `allowed_accounts` - The request response (containing the user) JWT must be signed by the callout account.

**Comment by aricart** [comment]
I wrote an example of a callout with the lib that I pointed you above, it has a script that builds an environment and the artifacts

See https://github.com/aricart/callout.go/tree/main/examples/delegated

**Comment by junpreetham** [comment]
That worked! Thank you so much for you help and patience! :D
