### ISSUE TITLE
Is it possible to embed gnatsd into my application?

### ISSUE THREAD

**Issue by Lazin** [nats-io/nats-server#64]
I'm working on distributed database and want to use NATS as a messaging middleware. The problem is that gnatsd is a separate deployment step. Client needs to deploy gnatsd first and only after that he or she will be able to deploy my system. I want to embed it into my application so client can only deploy once.

Another point is that gnats endpoints list will be managed using distributed configuration service (consul) so I will need to update gnatsd config at runtime. I have no idea how to do this if gnatsd will work in separate process.

**Comment by gianarb** [comment]
Hello! I think this process doesn't work with `go mod` based project, is it possible?
