### ISSUE TITLE
Feature Request: Add support for compression

### ISSUE THREAD

**Issue by trackroute** [nats-io/nats-server#739]
- [ X] Feature Request or Change Proposal
  
## Feature Requests
Please consider supporting optional compression of the connections between server<->client and server<->server (NATS clusters). 

I believe that compressing the entire message stream between a server<->client and server<->server is far more advantageous in many situations than just the compression of individual message payloads. I say this because if the whole stream is compressed then the subject names will also be compressed and it also means that duplicate payloads on the message stream that have much the same content (e.g. same JSON field names across messages etc) can be very effectively compressed.
 
#### Proposed Change:
Add compression support to NATS:
- In the server INFO message the server can announce a list of supported compression mechanisms, e.g: "compression_mechanisms": "gzip,deflate,plain"
- The client can then trigger the start of compression by sending a message to server like "STARTCOMPRESSION: gzip".
 
#### Who Benefits From The Change(s)?
- Anyone using NATS in applications where there aren't high bandwidth and low latency connections between servers and clients. i.e. Cross region and cross zone connections. 
- Stream compression will reduce bandwidth usage and consequently reduce egress and ingress costs (e.g. at AWS and GCE) where NATS is being used cross region and cross zone.
- Incorporating compression directly into NATS as a feature will save developers and administrators time, because then we can just enable compression on the NATS server and clients rather than having to resort to the far less effective compression of individual message payloads or alternatively trying to set up a compressed tunnel of some kind for the NATS traffic to run over.
- I realize that stream compression isn't useful in every use case (e.g. low latency message passing), but in other situations (low bandwidth, high latency) it is really useful.

**Comment by shajeeck** [comment]
Out of the Box compression with NATS would be great! any update on this?

**Comment by derekcollison** [comment]
Waiting on Go to support compression over TLS. As mentioned you can do an SSL tunnel with compression now.

**Comment by rigtorp** [comment]
> Waiting on Go to support compression over TLS. As mentioned you can do an SSL tunnel with compression now.

Maybe the Go developers won't bother since it's use with HTTP is dangerous (https://en.wikipedia.org/wiki/CRIME)?

Would be nice to support compression using https://github.com/facebook/zstd.

**Comment by rigtorp** [comment]
There is now a native zstd package for Go https://www.reddit.com/r/golang/comments/bvz8ts/ann_zstandard_go_compression_package/

**Comment by derekcollison** [comment]
Nice, still on our list but post 2.0 for sure.

**Comment by altmind** [comment]
Is there a formal process for feature introduction? I've noticed nats 2.0 was released, without compression and anything that can facilitate compression or encoding/feature negotiation. This ticket was not updated.

What can we do to facilitate this feature to land in master? What seems to be the be uttermost necessity - the discussion, ready specs, cliet or server implementation?

**Comment by derekcollison** [comment]
Since NATS 2.0, we introduced two additional network topologies which now means there are 4 in total.

1. client
2. route (v1.0 cluster)
3. Gateways (clusters of clusters)
4. Leafnodes

We are considering compression for the 4th and possibly the 2nd item above.

If go adds compresion to TLS we could also use that option, however it appears that will not happen in the near future.

**Comment by derekcollison** [comment]
I believe in trading cpu for bandwidth and have been watching this carefully trying to pick the best solution. However one size does not fit all as you would imagine and we need to be careful since we will need to support this forever.

**Comment by derekcollison** [comment]
I do believe leafnodes, and then gateways are the first choice. Client to server would be my last choice since we would be forcing an update for every client (> 32 now) to enable and would be taxing the client cpu to enable as well.

**Comment by jdrews** [comment]
I would be very interested in NATS compression. Especially for NATS connections across WAN links to edge nodes with limited bandwidth and high latency. I think the NATS protocol would lend itself well to compression as it's naturally a text based protocol. 

Combined with QUIC support (https://github.com/nats-io/nats-server/issues/457) this could make NATS a very compelling option on edge network use cases.

**Comment by derekcollison** [comment]
Websockets support compression and they are supported by leafnode connections, JS/TS and Go clients. We plan to add more clients in the future.

**Comment by derekcollison** [comment]
Closing for now but feel free to re-open as needed.

**Comment by zamazan4ik** [comment]
> Closing for now but feel free to re-open as needed.

So what are the NATS developers' plans in supporting compression without Websockets? I know that at least Kafka and Pulsar both support built-in compression. From another hand, RabbitMQ has no built-in support (at least I didn't find it in the documentation).

**Comment by derekcollison** [comment]
Its still on list for consideration.

**Comment by themartorana** [comment]
Compression across the wire would save us a lot of money in data transfer from various cloud providers. I know $ isn't the primary consideration, but about 40% of our hosting bill is data transfer (and the bulk of our data transfers over NATS connections), and reducing that via compression would be a significant win for us.

**Comment by derekcollison** [comment]
We have been looking into this. Stay tuned.

**Comment by jnmoyne** [comment]
Nowadays I suspect a large (vast?) majority of people are sending JSON as their payload on NATS messages and IMHO would see massively smaller on the wire and on file message sizes through compression.
Note that you control the format of the payload in your application code, so you can already implement compression yourself if all your applications agree on how to do it.

**Comment by altmind** [comment]
@derekcollison is there any place where you discuss that feature? i'm considering prototyping/hacking it, but i want to see what's the team idea on the impl.

**Comment by derekcollison** [comment]
Feel free to start a discussion, but we have been noodling on it a bit, especially for Gateways.
