### ISSUE TITLE
num_cache is greater than slCacheMax(1024) in version v1.3.0

### ISSUE THREAD

**Issue by lightwinglc** [nats-io/nats-server#744]
![default](https://user-images.githubusercontent.com/5235623/45281387-3fd4a100-b50a-11e8-913e-3576126cb8a0.png)
![default](https://user-images.githubusercontent.com/5235623/45281463-78747a80-b50a-11e8-99eb-d79616a2d266.png)
![default](https://user-images.githubusercontent.com/5235623/45281482-86c29680-b50a-11e8-984a-7a29297e363c.png)
here is part of gnatsd cluster, num_cache is 1024 in early version, why become so big in v1.3.0 and cache_hit_rate is very low, max_fanout and avg_fanout become zero.

**Comment by derekcollison** [comment]
The cache has changed to a sync.Map in 1.3. The sync.Map does not have a formal concept of members. We keep a count but the number can go over 1024, or slCacheMax. However the system should tune it back down. Could you give me some insight into the type of traffic and how many subscriptions the system is dealing with long term?

**Comment by lightwinglc** [comment]
All the subscriptions is long term, and when I restart one of the gnatsd cluster, num_cache of this gnatsd grow to 1024 and become 512, and continue doing this, 512->1024->512->1024...

**Comment by derekcollison** [comment]
That is the expected behavior if all subscriptions have active data on them.

**Comment by derekcollison** [comment]
What steps lead to having the subscription cache so high in the first place? Any information you can offer such that we can attempt to reproduce?

**Comment by lightwinglc** [comment]
After I restart all high cache gnastd servers, until now two of them happend again, and these two are in one physical machine, but I can not find what lead this situation, can you provide any method to trace this situation?

**Comment by derekcollison** [comment]
If you run monitoring, the following would be helpful.

/varz
/connz?subs=1

**Comment by lightwinglc** [comment]
OK, I will let you know if I find something
