### ISSUE TITLE
Daemon Mode?

### ISSUE THREAD

**Issue by derekcollison** [nats-io/nats-server#8]
Should we support daemon mode?

**Comment by passos** [comment]
But how? How to run it in daemon mode?

**Comment by derekcollison** [comment]
This is an old issue as you can see. I decided we would not directly support daemon mode, most production OSes have support for this from separate tooling.

**Comment by reejinbouk** [comment]
Hi, can you add daemon feature?
Can't daemonize it on tinycorelinux.
Thank you!

**Comment by ripienaar** [comment]
@reejinbouk it really isn't the way to run software in modern times :)

However, I believe TCL has start-stop-daemon that has a -b flag from busybox, so you dont need us to daemonize.
