### ISSUE TITLE
please update for the new nkeys package

### ISSUE THREAD

**Issue by aviau** [nats-io/nats-server#803]
Hello!

I am trying to get gnatsd in Debian but it cannot build due to the fact that the head of this repository does not build with the latest nkeys.

Could that be fixed?

Thanks!

**Comment by derekcollison** [comment]
I have fixed in my trust branch which should be merged this week. However nkeys should be vendored so should always build ok.

**Comment by aviau** [comment]
> Surely you would not take master when building for a distro anyway

If all of the latest tagged version build together then yes this is what we would do.

I am not done yet so I haven't tested that.

**Comment by derekcollison** [comment]
Would prefer for you to package the binary release for linux from Releases and not build on your own.

**Comment by aviau** [comment]
I am afraid I cannot do that, Debian is built from source and does not include binaries.

**Comment by derekcollison** [comment]
If it built from source then Go will honor the vendored dependencies as it should, correct?

**Comment by aviau** [comment]
No, we never honor vendored dependencies in any circumstances

**Comment by derekcollison** [comment]
That's pretty foolish IMO when the development language supports and encourages it and the developer ecosystem depend on it for building properly.

**Comment by aviau** [comment]
Every language supports it. While Go has built tools around it, other languages supports it with copy and paste.

We just can't have multiple vendored copies of every library, we don't have the manpower to support it.

**Comment by derekcollison** [comment]
Understood about multiple copies of dependencies. That being said, if the packaging system can not produce a binary as built from a tagged release with the correct dependencies, we the NATS maintainers would be challenged to properly support it. I am sure there is an answer somewhere, let us know if we can help.

**Comment by aviau** [comment]
This can be done if you don't release any version of nkeys that you don't want the world to use.

If you release any version of nkeys, people will start using it and depend on it, forcing us to update to it.

Just make sure you don't release nkeys before gnatsd can build with it.

This can be done by having non-release-ready development on a development branch where it wouldn't be reached by a typical user's go-get.

**Comment by derekcollison** [comment]
Nkeys is released but had changes. The nats-server vendors projects (even ones that we maintain) as a good practice for one project not breaking another. Nkeys tests pass and all utilities built with it are updated. The server is a larger beast. It has been updated to the newest version in the "trust" branch. But again, you **have** to build a release package with the exact same version we build with as tagged on github. That means the exact version of nkeys that is vendored.

**Comment by derekcollison** [comment]
Someone pointed this out, not sure if it is helpful.

https://go-team.pages.debian.net/packaging.html

**Comment by aviau** [comment]
Yeah, I do maintain about 150 Go packages in Debian so I am part of the team that writes these guidelines.

**Comment by derekcollison** [comment]
ok once gnatsd trust branch lands will resolve, but still would only build from tagged releases. I will tag a release for nkeys though..

**Comment by aviau** [comment]
I have applied the trust branch as a patch already and used the head of nkeys, I am now moving on with the streaming server, which is ultimately what I really need.

**Comment by aviau** [comment]
It looks like the streaming server requires an older version of raft than the one we have in Debian?

I haven't analysed the log yet...

```
# github.com/nats-io/nats-streaming-server/server
src/github.com/nats-io/nats-streaming-server/server/clustering.go:276:28: cannot use s.log (type *"github.com/nats-io/nats-streaming-server/logger".StanLogger) as type "github.com/nats-io/nats-streaming-server/logger".Logger in argument to newRaftLog:
	*"github.com/nats-io/nats-streaming-server/logger".StanLogger does not implement "github.com/nats-io/nats-streaming-server/logger".Logger (missing Warnf method)
src/github.com/nats-io/nats-streaming-server/server/monitor.go:207:10: cannot use limits.OpenFiles (type int64) as type int in assignment
src/github.com/nats-io/nats-streaming-server/server/server.go:872:7: cannot use ss.stan.log (type *"github.com/nats-io/nats-streaming-server/logger".StanLogger) as type "github.com/nats-io/nats-streaming-server/logger".Logger in assignment:
	*"github.com/nats-io/nats-streaming-server/logger".StanLogger does not implement "github.com/nats-io/nats-streaming-server/logger".Logger (missing Warnf method)
src/github.com/nats-io/nats-streaming-server/server/server.go:1451:37: cannot use s.log (type *"github.com/nats-io/nats-streaming-server/logger".StanLogger) as type "github.com/nats-io/nats-streaming-server/logger".Logger in argument to stores.NewFileStore:
	*"github.com/nats-io/nats-streaming-server/logger".StanLogger does not implement "github.com/nats-io/nats-streaming-server/logger".Logger (missing Warnf method)
src/github.com/nats-io/nats-streaming-server/server/server.go:1454:36: cannot use s.log (type *"github.com/nats-io/nats-streaming-server/logger".StanLogger) as type "github.com/nats-io/nats-streaming-server/logger".Logger in argument to stores.NewSQLStore:
	*"github.com/nats-io/nats-streaming-server/logger".StanLogger does not implement "github.com/nats-io/nats-streaming-server/logger".Logger (missing Warnf method)
src/github.com/nats-io/nats-streaming-server/server/server.go:1457:39: cannot use s.log (type *"github.com/nats-io/nats-streaming-server/logger".StanLogger) as type "github.com/nats-io/nats-streaming-server/logger".Logger in argument to stores.NewMemoryStore:
	*"github.com/nats-io/nats-streaming-server/logger".StanLogger does not implement "github.com/nats-io/nats-streaming-server/logger".Logger (missing Warnf method)
src/github.com/nats-io/nats-streaming-server/server/server.go:4425:18: cannot use s.log (type *"github.com/nats-io/nats-streaming-server/logger".StanLogger) as type "github.com/nats-io/nats-streaming-server/logger".Logger in argument to traceSubState:
	*"github.com/nats-io/nats-streaming-server/logger".StanLogger does not implement "github.com/nats-io/nats-streaming-server/logger".Logger (missing Warnf method)
dh_auto_build: cd obj-x86_64-linux-gnu && go install -gcflags=all=\"-trimpath=/home/aviau/git/debian-pkg/build-area/golang-github-nats-io-nats-streaming-server-0.11.2\+git20181112.636da8d/obj-x86_64-linux-gnu/src\" -asmflags=all=\"-trimpath=/home/aviau/git/debian-pkg/build-area/golang-github-nats-io-nats-streaming-server-0.11.2\+git20181112.636da8d/obj-x86_64-linux-gnu/src\" -v -p 4 github.com/nats-io/nats-streaming-server github.com/nats-io/nats-streaming-server/logger github.com/nats-io/nats-streaming-server/server github.com/nats-io/nats-streaming-server/spb github.com/nats-io/nats-streaming-server/stores github.com/nats-io/nats-streaming-server/test github.com/nats-io/nats-streaming-server/util returned exit code 2
```

**Comment by kozlovic** [comment]
You may have similar problems then because NATS Streaming vendors a bunch of repos (including gnatsd)
