### ISSUE TITLE
flaky tests

### ISSUE THREAD

**Issue by aviau** [nats-io/nats-server#805]
Hello!

Could it be that the tests are flaky?

On a loaded machine, they seem to sometimes pass and sometimes fail. Does the project contain timing-dependent tests?

For example:
```
--- FAIL: TestNoRaceRoutedQueueAutoUnsubscribe (10.23s)
	norace_test.go:176: Did not receive all 250 queue messages, received 250 for 'bar' and 238 for 'baz'
```

**Comment by derekcollison** [comment]
Could be. I am pretty sure I fixed this on on trust branch since I ran into it as well.

**Comment by derekcollison** [comment]
Actually I fixed another one, but same issue. Will fix this one.
