### ISSUE TITLE
Does NATS support MQTT?

### ISSUE THREAD

**Issue by hoang17** [nats-io/nats-server#812]
I would like to use NATS as MQTT broker. Is it possible?

**Comment by hoang17** [comment]
Thanks @derekcollison for your amazing product. So you mean it is in the time line?

**Comment by derekcollison** [comment]
We have tentative plan for it 1H 2019. /cc @ColinSullivan1

**Comment by hoang17** [comment]
cool thanks 🙏🏻

**Comment by robinbowes** [comment]
Any more concrete plans yet, @derekcollison ?

**Comment by derekcollison** [comment]
Yes we are planning on support, aiming for 1H 2019.

**Comment by goireu** [comment]
I'd be happy to help "beta" testing whenever possible !

**Comment by sonwa** [comment]
Is there a beta?

**Comment by derekcollison** [comment]
Not at the moment. Will keep everyone posted.

**Comment by sonwa** [comment]
I saw that it was already release 2.0.0. Does this version support MQTT?

**Comment by derekcollison** [comment]
No it was not planned for the 2.0 release but is still on the roadmap for 2019, but may slip depending on other priorities.

**Comment by nmarcetic** [comment]
Really looking forward to seeing MQTT support! Let us know if we can help somehow @derekcollison

**Comment by derekcollison** [comment]
Some feedback would be great. For now, what QoS do you most commonly use. Which MQTT servers are you using now? What auth/security is in place?

Thanks.

**Comment by goireu** [comment]
Derek,

we have 2 kind of brokers here : 
- shared ones with no message "persistence" (publish QoS 0/1, subscribe QoS 0, no retain messages, no will messages). These may be VerneMQ or Mosquitto.
- dedicated ones, with message "persistence" (any QoS, retain & will messages). These are Mosquitto ones, thinking about VerneMQ too now they have a new non-leaking distributed store.

Security is handled by a home made MQTT reverse proxy checking client IDs and/or TLS device certificate. This proxy also handles MQTT protocol limits' enforcement.

Kinda non-standard usage. Fact is we don't use our brokers, our customers do.

While we're talking about MQTT, please note MQTT5 has recently been published, it adds long awaited features, I'd recomment you directly go for it.

One last thing : a common problem with MQTT brokers is memory usage, it is 99% dependent on usage pattern and the protocol says little about how the broker should behave when customers send in terabytes of messages and politely ask the broker to retain them. Proper configuration items, such as memory limits, are to be kept in mind when designing a broker implementation.

**Comment by derekcollison** [comment]
Great feedback, thank you. I am aware of MQTT5 and even the SN version as well. Some good stuff in there, so agree with you on making sure we can support it.

**Comment by PTS93** [comment]
We usually use MQTT with QoS 0 or 2, practically never QoS 1. Broker is always Mosquitto and we make a lot of use of persistence, mostly for retained messages, almost never for will messages.
We seldom use encryption as we usually deploy in secured networks that have no access to the internet. When we do we use the built-in support for TLS with username and password auth.

**Comment by derekcollison** [comment]
Thanks!

**Comment by nmarcetic** [comment]
Hey Folks,

We at [Mainflux](https://github.com/mainflux/mainflux) works a lot with MQTT and some of our clients/partners has huge deployments and we faced with real-life problems a lot.
Ofc Thanks to NATS, which is the core of our platform, We are handling those deployments just fine ;)  

Here are my 50cents,
First of all, great feedback from @goireu he already mentioned important stuff :) 
Regarding QoS, there is no such thing as "preferred QoS", All QoS is must have, really it's not just optimistic advice, its reality. To be concurrent, NATS must support full MQTT spec at least 3.1.1 (which is not so big and complicated) and make plans for v5 in future :), besides this +1 for TLS and the very important stuff is modularity, NATS is pluggable used as lib I can hook into events and  whatever I need to do, this is a huge drawback most brokers. For example, at Mainflux we use a different kind of AuthX and AuthZ methods and if I want to check the identity of publisher I must hook into onPub event and make some gRPC's, etc... this is not possible with most of the brokers and it's a deal breaker for most of the proejcts IMHO. Ofc, not just onPub, there are plenty of events which gave you freedom.

We wanted to start with our own MQTT broker in Go, because we find missing features and problems in every broker so far...  but always some other priorities :) 

@derekcollison If there are plans for opensource it and chance to join, we are very interested to help and contribute.

**Comment by nuhamind2** [comment]
While I don't have big deployment, I like to chime in to. First,I wonder what qos1 and qos2 will affect nats complexity as server need to track message delivery. Even on qos0, there is this related issue #802 . Second, will it be implemented in the core nats or as proxy/connector keeping the core as simple.

Third, there is [this](https://volantmq.io/)

**Comment by nmarcetic** [comment]
This is a good idea @nuhamind2 

We are also discussing to build an MQTT proxy which will wrap the communication, do AuthX/AuthZ, etc... then just proxy messages so you can use any broker you want, keeping the core simple just plug and play. IMHO this is good for NATS MQTT support but again full blown MQTT broker in missing :)

**Comment by derekcollison** [comment]
I am considering the support being part of the core. We already have a way to bridge auth domains with leafnodes from NATS 2.0 which is a very powerful concept and think we will see that in use quite a bit for IoT, deployables, mobile and web.

**Comment by ujwal-setlur** [comment]
Any updated timeline for availability?

**Comment by ColinSullivan1** [comment]
We're looking at Q4, for 3.1, 5, and SN support.

**Comment by drasko** [comment]
@ColinSullivan1 is this still on-track?

**Comment by derekcollison** [comment]
Depends on JetStream TBH but yes, late Q4 though.

**Comment by rtmaster** [comment]
is this still on-track?

**Comment by derekcollison** [comment]
Most likely Q1, JetStream taking up alot of time.

**Comment by vinayxbox** [comment]
We will be very happy if the NATS Server support MQTT out of the box.
We use QoS-1. We use Mosquitto broker with Auth and ACL with Redis Plugin.
We are exploring alternatives as we have observed Mosquitto performance is not sufficient for us.

**Comment by derekcollison** [comment]
Yes this is on the roadmap. We are doing the work on JetStream first which will be bundled into the server and provide persistence engine that will be needed for QoS-1. 

Plan is Q1/Q2. We will start with v3.1 and QoS 0 and 1, but have plans for v5.0 and SN.

**Comment by igolaizola** [comment]
Any chances of having a "QoS-0 only" early version in order to avoid dependencies with JetStream/persistence?

**Comment by derekcollison** [comment]
NRE is possible, but lacking that most likely not. But I promise we are working as fast as we can. ;)

**Comment by max-koehler** [comment]
Is there a document to read up on what's planned for the first version or some way so see the current process?

**Comment by derekcollison** [comment]
Not yet, but fairly straightforward. Allow MQTT clients, even binary ones, to point to a NATS server and get full connectivity to all other MQTT clients (possibly bound to an account) and all other NATS clients for any size NATS extended cluster topology. We will support user/pass and client cert auth as specified by their spec. Plan to support QoS 0 and 1 for 3.1, 5.0 and S/N eventually.

**Comment by vinayxbox** [comment]
@derekcollison: When can we expect a tech preview for evaluation ?

**Comment by derekcollison** [comment]
We are hoping in Q2.

**Comment by vinayxbox** [comment]
Nats  with MQTT will support the same performance as stock Nats protocol ?

**Comment by derekcollison** [comment]
We will aim to have the highest performance we can get, but since the protocol is very different there may be constraints there from a blocking request/response pattern.

**Comment by nmarcetic** [comment]
I do not doubt you will get great performance, the biggest concern is clustering & message persistence (QoS 1 and 2, retain message etc...) . This is where most of the brokers on market fails, at least in the opensource version. I am currently doing [MQTT load test-ing](https://github.com/nmarcetic/mainflux-loadtest) with various brokers (both  Mainflux impl but also native brokers). So far, I am really not happy...This is where I am expecting boom :bomb:  from NATS and finally scalable MQTT broker that just works! :crossed_fingers:

**Comment by derekcollison** [comment]
As we complete clustering fro JetStream, the QoS 1 will use that so will inherit JetStreams persistence layer. Not sure about QoS 2 yet, does not seem to be wildly used and IMO is rarely implemented correctly. I think we did implement it correctly for TIBCO's EMS back in the 90s, but do not think it was worth it TBH.

The protocol, if it has any synchronous interactions, could also be a limiting factor.

**Comment by goireu** [comment]
QoS 2 (deliver at most once) is a very interesting pattern.

Suppose you want to send an SMS when a message is published on some topic. You want your subscribe-and-relay-to-sms software to send only 1 SMS per published message, not 2 because-of-some-network-issue.

More generally speaking I'd say:
- QoS 0 is for updating some unimportant value
- QoS 1 is for updating some important value
- QoS 2 is for triggering something (relaying, storing, reacting, ...)

**Comment by derekcollison** [comment]
QoS 2 or Exactly once is extremely hard to get correct in practice. Most implementations get it wrong IMO.

**Comment by derekcollison** [comment]
We will look at it though, our team has done these before, but most customers really never used it in production.

**Comment by goireu** [comment]
That's the technical side of the coin, just talking about usage patterns here.

I would say "exactly once" needs to go along with a strong data storage mechanism, which is something MQTT brokers typically are weak about compared to, let's say, AMQP brokers. I agree MQTT users typically want updates more than triggers, eventually implementing triggers by deduplicating updates.

Maybe NATS can bring the best of both worlds, that would be amazing! 😃

**Comment by derekcollison** [comment]
Will do our best!

What AMQP brokers do you feel are good at data storage? Just curious.

**Comment by goireu** [comment]
> What AMQP brokers do you feel are good at data storage? Just curious.
I'm not technical enough to answer this question with rock-solid arguments. I just observed in many places AMQP brokers being used to dispatch jobs and MQTT brokers being used to dispatch data. When dispatching jobs you want to avoid losing any of them. When dispatching data (especially updates) there are cases where you may lose some.

**Comment by PTS93** [comment]
We use QoS2 all the time in production. Whenever we have a trigger that absolutely has to happen and not more than once we rely on MQTT to do its thing and guarantee delivery of exactly one message. This is often hard to handle reliably on the client side otherwise.

**Comment by derekcollison** [comment]
I understand it is desirable, but in practice it rarely gives you what you want. Much longer conversation but you need to look closely at your state for processing a message and any state transformations, etc. and how they are linked to delivery and ack of a message.

**Comment by PTS93** [comment]
I never looked closely at how mosquitto implements QoS2 or our client libraries but in practice we never experienced an issue where it wasn't doing what its supposed to.
What I did notice a lot is that many broker services and clients do not implement QoS2 at all. Amazon IoT and MS IoT service being a notable example.

**Comment by nmarcetic** [comment]
Hehe exactly @PTS93 ,  AWS IoT is a good example they have also a lot of limitations regarding connection.  Google also doesn't provide QoS2. There must be a good reason :) 
I agree that most impl are wrong and in practice you with QoS 1 you will rarely get the message more than once + you can handle this on client-side. Both QoS 1 and 2 are actually hard to handle on client-side, storing msg etc...

**Comment by goireu** [comment]
My semi-educated guess for AWS/Azure not providing QoS2 is their underlying messaging infrastructure is not designed to provide this use pattern. Both offer an MQTT gateway to their messaging system, not an MQTT native broker.

**Comment by derekcollison** [comment]
Seems QoS2 has some pieces in the broker but is mainly a 4-way handshake between sender and receiver. Will dig in more and see what we can do as we get into the impl.

**Comment by vinayxbox** [comment]
Any update here ?

**Comment by derekcollison** [comment]
I m hoping to have work start in a few weeks.

**Comment by sonwa** [comment]
Can mqtt be used?

**Comment by derekcollison** [comment]
It is in the works, but just starting. Hope to deliver early Q3.

**Comment by ajaegle** [comment]
Is there any design document on how managing authentication for mqtt clients and authorization on topics will be handled? I’m really curious to learn more about the current state of the mqtt integration and would like to support testing some early versions for feedback.

**Comment by derekcollison** [comment]
The mqtt work is being led by @kozlovic, so he may have some input.

**Comment by kozlovic** [comment]
@ajaegle For MQTT clients auth, we don't have much choice (we plan to support 3.1.1 initially). It will be either username/password and/or TLS. The `mqtt{}` block in the configuration will be able to provide its own set of users and/or tls configuration.
There is a branch: https://github.com/nats-io/nats-server/tree/mqtt which is being worked on. Note that this branch may be updated and sometimes force-pushed at any time without warning, so if you work from this branch, be aware of that.

Note that at this point there is only QoS 0 and "clean session" support only. The rest will trickle slowly.

**Comment by nmarcetic** [comment]
This is huge so far. Great progress @kozlovic I didn't expect to see everything from scratch :) But IMHO, Not using paho is a good decision. 
Did you consider maybe to pull out this MQTT part from nats Core and use it as lib, #later ? It will be hell to maintain very soon.
Checking code

**Comment by kozlovic** [comment]
@nmarcetic Maybe, but I am not sure. As you can see, this is already quite in the guts of the server and that's before any use of persistence which will require accessing JetStream internals. So I am not sure it will be easy to externalize this work in separate library.
As for not using an existing library, we try to minimize dependencies and as explained above it may have been difficult anyway. Also, if there is a bug in our implementation it will be easier to fix :-).

**Comment by nmarcetic** [comment]
I see it will not be easy :) Stil I think you can keep server stuff in separate lib and have just handlers (check out what we exposed [here](https://github.com/mainflux/mproxy/blob/master/pkg/session/handler.go#L4)) in nats core where you will handle the logic, but keep this packet parsing, etc (1.5k + LOC)... in separate lib. 
Anyway, maybe its better to get working integration with nats ASAP, then refactor and polish :) 
Do you have some kind of rough roadmap somewhere public?

**Comment by max-koehler** [comment]
@kozlovic great work!
can you give any estimation or insights into the roadmap for QoS 1 and retained messages?

**Comment by kozlovic** [comment]
Late Q4: https://github.com/nats-io/nats-general#nats-roadmap. Note this will be based on MQTT v3.1.1 (in roadmap I see 3.1).

**Comment by nqd** [comment]
@kozlovic do you have a list of open tasks/issues that we can contribute?

**Comment by petedavis** [comment]
@kozlovic will the retained messages publish to native nats clients? And will a native nats client be able to publish retained messages, and reuse this capability that has been produced for MQTT producers?

**Comment by kozlovic** [comment]
@nqd Sorry for the delay and thank you for the offer. However, I enter the phase of retain/persistence and this will be really going deep in the guts of the server and have to mix with JetStream, so not sure what to ask community to contribute at this time. However, I would like ask for users feedback when something is ready for testing.

Also, I would like to know what users are especially looking for and if that matches what is going to be offered. That is, we have plans for MQTT v3.1.1 and only QoS 0 and 1. If everybody says that they need QoS 2 or it is useless, then we have a problem :-)

@petedavis: 
> will the retained messages publish to native nats clients

To be clear, are you saying that if MQTT publishes a retained message, you would want NATS subscriptions that start to receive this message? Or simply are MQTT published retained messages sent to existing NATS subscriptions? If the later then yes: an MQTT produced message will be delivered to all matching subscriptions (mqtt and NATS). However, having NATS Subscriptions that start receive MQTT retained messages would mean that we need to go through the list of all retained subjects to see if it matches the newly created subscription: this is what needs to be done for MQTT subs, but not sure if this is something we want to add to the non MQTT code path to be honest.

> And will a native nats client be able to publish retained messages

Until recently I would have to say no since you would have no way that I can think of (except maybe through config saying that all messages published to given subject from NATS are considered retained) to signal this behavior. With the introduction of NATS headers (slowly rolling into our client libraries), then it would be possible to notify that the NATS message should be retained, but that leads to performance considerations because now it means inspecting headers (which is very costly) for each incoming NATS message.

**Comment by nqd** [comment]
@kozlovic will test whenever MQTT feature release. I have been using MQTT for a while, no need QoS2 so far.

**Comment by nmarcetic** [comment]
@kozlovic ` If everybody says that they need QoS 2 or it is useless, then we have a problem :-)` We would ask for QoS 3 but there is no such service, yet :) If you ask the community, we will always ask for good but cheap, rather then bad and expensive. 
Joking.. but really, we expect the best possible effort, always.

IMHO, QoS 1 is quite sufficient for most use cases + Nats don't support QoS 2. 
 
`However, I would like ask for users feedback when something is ready for testing.` I would like to help also. I am more interested for contribution like participation in the development when you need help :)

**Comment by antong** [comment]
QoS 0 and QoS 1 is good! "Exactly once" might sound desirable, but for most practical applications, it just gives a false sense of security. For instance in the SMS sending example given as an example for when QoS 2 would be required: How does the consumer that would receive the exactly-once message from the broker guarantee that exactly one SMS is delivered? I highly doubt whatever device or service used to actually send SMS messages can give the exactly-once guarantees required for this to make a difference.

For one project, I'm currently using mosquitto with authentication and authorization based on mutual TLS (client certificates). For authorization, I have an ACL with patterns that include the MQTT user name, for example ("pattern read client/%u/to/#" and "pattern write client/%u/from/#"). Mosquitto fills in the user name (%u) using the authenticated client certificate subject CN. In this way mosquitto does not need to know anything about any client accounts, as it is all outsourced to an external, trusted PKI. Will something like this be possible with NATS MQTT?

Thank you for working on this!

**Comment by kozlovic** [comment]
> .. I highly doubt whatever device or service used to actually send SMS messages can give the exactly-once guarantees required for this to make a difference.

We definitively agree on that :-)

> In this way mosquitto does not need to know anything about any client accounts, as it is all outsourced to an external, trusted PKI. Will something like this be possible with NATS MQTT?

I would need to look into what mosquitto does in more details. As for NATS, we do offer authentication with user/password and/or TLS, including TLS map which allows to extract the user name to use from the certificate. NATS offers ACLs through permissions and accounts isolation. You can read more about auth here: https://docs.nats.io/nats-server/configuration/securing_nats/authorization, and accounts here: https://docs.nats.io/nats-server/configuration/securing_nats/accounts.

**Comment by autodidaddict** [comment]
Is there any updated ETA for native MQTT support in NATS?

**Comment by CuBiC3D** [comment]
> Is there any updated ETA for native MQTT support in NATS?

https://github.com/nats-io/nats-server/releases/tag/v2.2.0

**Comment by kozlovic** [comment]
Sorry for not notifying this issue. Indeed, MQTT is now available with the NATS Server 2.2.0 release. Here is some documentation regarding MQTT support in NATS Server: https://docs.nats.io/nats-server/configuration/mqtt

**Comment by voycey** [comment]
MQTTv5 is a pre-requisite, there are a bajillion services supporting MQTTv3, its an ancient protocol kept going by the fact that no one seems to bother implementing MQTTv5

**Comment by ben-cavli** [comment]
Does MQTT in NATS support features like **Webhooks** and **mountpoints** which are available in Verne MQ?
