### ISSUE TITLE
CRL support

### ISSUE THREAD

**Issue by ripienaar** [nats-io/nats-server#929]
#### Use Case:

Denying unwanted clients connections to the nats server based on standard PKI certificate revocation lists.  Gracefully handling client decomm ensuring that files the client might leave lying around could not be used to access the servers.
 
#### Proposed Change:
 
Support checking a local CRL file before a new client gets accepted. The list should support being updated without reloading or reconfiguring the server. 

#### Who Benefits From The Change(s)?
 
People running typical PKI infrastructure

#### Alternative Approaches

We could also support OCSP as an option.  Though CRL based on a local file should be the minimal supported feature with OCSP as a 2nd option

**Comment by derekcollison** [comment]
Reading in a file for every connection seems quite extreme but we could watch the file for any changes etc and load them in when we see them.

**Comment by selstam** [comment]
Usuallly CA certificates contain URL's for its CRL. Is there really a need for a local file? Periodically checking a CRL is quite easy and all CRL's have a validity period.

**Comment by ripienaar** [comment]
On large networks the url thing can be a pain so usually crl in files are supported

**Comment by derekcollison** [comment]
I think we will be doing OCSP but not crl files. @tbeets to confirm.

**Comment by tbeets** [comment]
In 2.10 we are supporting comprehensive OCSP checks of inbound clients (nats, websocket, mqtt, leaf spokes) against their CA's OCSP Responder(s).  TLS Verify (mTLS) must be enabled.  We are providing a server-scoped local OCSP response cache.  There may be shared-cache options and remote cache management features in later releases depending on demand.

We're not using or checking CRLs.

**Comment by tbeets** [comment]
We have back ported the new [OCSP Peer feature](https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-38.md) from the 2.10 train to [2.9.21](https://github.com/nats-io/nats-server/releases/tag/v2.9.21).  Current direction is to avoid the CRL morass (meaning NATS Server having to deal with CRL) altogether with aggressive support of fetching, caching, and validating client's CAs' OCSP Response for inbound mTLS.
