### ISSUE TITLE
Config includes aren't documented

### ISSUE THREAD

**Issue by JensRantil** [nats-io/nats-server#931]
I notice https://github.com/nats-io/gnatsd/blob/master/conf/simple.conf#L4. `git blame` tells me the `include` stanza was added two years, so I assume it's a released feature but it's not mentioned in https://github.com/nats-io/gnatsd/blob/master/README.md nor https://nats.io/documentation/server/gnatsd-config/.

**Comment by derekcollison** [comment]
We are working hard to upgrade the quality of our docs, look for changes in NATS 2.0.

**Comment by derekcollison** [comment]
https://nats-io.github.io/docs/nats_server/configuration.html#include-directive
