### ISSUE TITLE
Performance issues with locks and sublist cache

### ISSUE THREAD

**Issue by azrle** [nats-io/nats-server#941]
- [ ] Defect
 - [x] Feature Request or Change Proposal

#### Use Case:

We are using gnatsd 1.4.1 (compiled go 1.11.5).
During benchmark, we observed non-trivial latency (500 ms+, usually seconds) at gnatsd cluster.

As there is no slow consumers (with default 2 seconds threshold) and the OS rcv buffer got full and TCP window went to 0, it seems that the gnatsd server is somehow slow in read loop. We are trying to slow down the sender for one connection but we believe that gnatsd can also be improved. If you need more proofs of slowness of read loop, we might be able to provide some tcpdump snippets and tracing logs of gnatsd.

We also observe some parser errors happened rarely when gnatsd is under high load of reading.
The client is using cnats. However we are not sure who (cnats, OS, or gnatsd) was not doing right. After we found it out, we may open another issue to address the problem.
```
[8354] 2019/04/01 12:17:11.695815 [ERR] 10.228.255.129:44588 - cid:1253 - Client parser ERROR, state=0, i=302: proto='"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"...'
```

By the way, as gnatsd could detect slow consumer, is that possible for gnatsd to know itself becomes a slow consumer (slow read)?
The only idea I come up is to adjust OS buffer and let the upstream to know the pressure.
If you have any suggestions, please let me know.
 
#### Proposed Change:

1. Improve locks.
https://github.com/nats-io/gnatsd/compare/branch_1_4_0...azrle:enhance/processMsg_lock
Comparison of read loops between high load and low load:
![image](https://user-images.githubusercontent.com/2177709/56013585-6d95f880-5d2c-11e9-8c90-f53840b43cdb.png)
  Sync blocking graph:
![image](https://user-images.githubusercontent.com/2177709/56013628-ae8e0d00-5d2c-11e9-9a55-3ea8d0abccd8.png)

2. Ability to adjust sublist cache size or disable it.
https://github.com/nats-io/gnatsd/compare/branch_1_4_0...azrle:feature/opts-sublist_cache_size
According to our application characteristic, it doing sub/unsub very frequently and most of subjects are single-used. The hit rate of cache is under 0.5%.
However, it can cost gnatsd to maintenance the sublist cache. Besides locks for the cache,  `reduceCacheCount` is noticeable. Compared to other function's goroutines which are less than 50, the number of goroutines for `server.(*Sublist).reduceCacheCount` can climb up to near 18,000.

#### Who Benefits From The Change(s)?
Clients send messages heavily to gnatsd. And subscription changes frequently.
Under our test cases (with enough servers), the 99.9%tile of latency drops from 1500ms to 500ms (it's still slow though).

I noticed that gnatsd v2 is coming.  And the implementation changes a lot. But I am afraid that we may not have time to wait for it to get production-ready.

I sincerely hope the performance can be improved for v1.4.

Thank you in advance!

**Comment by derekcollison** [comment]
Can you describe in a bit more detail your usage of subjects? NATS favors designs that do not use rapidly changing subscriptions since they impact the network traffic for the interest graph updates. Even with Request() if you notice we will do a single session scoped wildcard subscription for replies that can be reused with no impact to interest graph updates.

**Comment by derekcollison** [comment]
Also, would a configuration flag to suppress the cache be what you would be looking for longer term?

**Comment by derekcollison** [comment]
Have you run the sublist proposed changes under the race detector?

**Comment by derekcollison** [comment]
Also have you ran these tests and your use case with the master branch (2.0-RC)?

**Comment by azrle** [comment]
> Can you describe in a bit more detail your usage of subjects? 

I have to apologize I could not give your the use case since it's confidential.
But let me put it in this way.

Image that we are forming small groups with N people in it.
A person in a group can broadcast a message to all members in the group. So we create a subject for each group.
As result, say N=3, and there are 3000 people come in a second, there will be 1000 new subjects. And at the same time, another 3000 people leave which leads 1000 subject to be destroyed in a second.

It can be actually more complicated. A person in a group can give a private price which must be unknown to others in the group. And there is a service server which will receive all prices and get the highest one, then notice all members in the group that who gave the highest price.

> NATS favors designs that do not use rapidly changing subscriptions since they impact the network traffic for the interest graph updates. 

Before we use NATS, we do not notice that. However we found it is true when we doing the test.
May be good to put it into the document?

> Also, would a configuration flag to suppress the cache be what you would be looking for longer term?

Yes. We clearly know the subscription pattern and the cache will not help in our case. In fact, it will slow down the NATS cluster.

> Have you run the sublist proposed changes under the race detector?

I only ran the `go test ./...` as suggested in README.
Here is a test result with '-race' option.
```
# go test -race ./...
?   	github.com/nats-io/gnatsd	[no test files]
ok  	github.com/nats-io/gnatsd/conf	2.358s
ok  	github.com/nats-io/gnatsd/logger	2.934s
ok  	github.com/nats-io/gnatsd/server	43.880s
ok  	github.com/nats-io/gnatsd/server/pse	2.287s
ok  	github.com/nats-io/gnatsd/test	37.409s
```

> Also have you ran these tests and your use case with the master branch (2.0-RC)?

No, not yet. We will try do so. But even so, as we are planing to put NATS into production, we hope that we could have a GA-released and production-ready version and get it fully tested in our case. However, I do not know how long the test can continue, it may be soon over since it's costly. I will try my best to give 2.0-RC a try! I will let you know the result if we tried.

**Comment by derekcollison** [comment]
Try 2.0 and let us know your experience with that. NATS 2.0 has been used in production settings already, but as always we want users/customers to test against their own setup.

Do the group subjects remain as members come and go? How do you prevent access?
Can members be directly messaged to outside of themselves sending a Request()?

Thanks.

**Comment by azrle** [comment]
> Do the group subjects remain as members come and go?

No. When the last member goes, it will be removed.

> How do you prevent access?

Sorry, I do not get your question. I don't think we prevent access.

>  Can members be directly messaged to outside of themselves sending a Request()?

Yes, messages can be directly send to a member. Let me explain a little more.
For a little more complicated case, actually we do have a subject for each member. The service server subscribes a group subject and every members publish messages to that group subject. The service server handles messages from the group subject, do some fancy things and then send responses back to all (or some) members.
Note that although a group contains very limited members, the total number of users can be large. It won't be good for every users to have their own connections to the NATS cluster. Thus, a connection to the NATS cluster is re-used by multiple users.
I hope this can help you understand the use case.

**Comment by derekcollison** [comment]
Thanks for the information. Do the processes messages differ from member to member?  Meaning if I send a message to the group do they all see the same message?

NATS has a noecho option such that you can treat a subject as a "bus" and everyone sends to it but the connection will not receive its own messages even though it has a matching subscription.

If subjects are used to send any amount of multiple messages the cache can help, and I think NATS 2.0 will alleviate some of the lock contention for the sublist cache.

We could also make the cache an option as you did, but I believe the example code you gave may suffer from race conditions.

**Comment by azrle** [comment]
> Thanks for the information. Do the processes messages differ from member to member? Meaning if I send a message to the group do they all see the same message?

Yes and no. It depends how the service server handle the message. However, I think they may be almost same.

> We could also make the cache an option as you did, but I believe the example code you gave may suffer from race conditions.

Thanks! You mean https://github.com/nats-io/gnatsd/compare/branch_1_4_0...azrle:enhance/processMsg_lock may suffer from race conditions? I would like to discuss about that. Is that okay for you to give me a branch for v1 version which I could send PR to?

**Comment by azrle** [comment]
Furthermore, we were trying the 2.0-RC5. However we failed to start the cluster (100+ servers).
Some of servers goes down due to out of memory on a 7 GB server.

```
  PID USER  PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
18618 xxx   20   0 11.127g 2.242g   9628 S   3.0 32.0   2:29.51 gnatsd
```

Even the health one consuming a lot memory.

We just replace the binary and therefore the config remains unchanged.
```
listen: $SERVICE_BIND
http: $HTTP_BIND

cluster {
  listen: $CLUSTER_BIND
  routes = [
    $ROUTE
  ]
}
```
Any advise?

We may file another issue about this.

**Comment by azrle** [comment]
We have a panic report of out of memory. I put it into another issue: https://github.com/nats-io/gnatsd/issues/954.

**Comment by derekcollison** [comment]
Do you run the servers with monitoring enabled? Could you share /varz and /subsz?

**Comment by azrle** [comment]
Yes, I believe I can share with your some metrics (`/varz`, `/subsz`) and data later today.

By the way, did `nats.io` domain change? It seems that it cannot be resolved right now.

**Comment by derekcollison** [comment]
So we have identified some areas where we were trying to do optimizations with stack preallocations that caused the memory bloat. I am fixing them now. Will keep you posted.

I believe nats.io had a small outage but should be back up now.

**Comment by kozlovic** [comment]
> Thanks! You mean branch_1_4_0...azrle:enhance/processMsg_lock may suffer from race conditions? I would like to discuss about that. Is that okay for you to give me a branch for v1 version which I could send PR to?

I think he was instead referring to the branch about the sublist max cache. It looks like you add a setter (that does not use any lock) and also access s.maxSize outside of any lock. A race detector would probably complain about that.

**Comment by azrle** [comment]
I see. When it comes to the sublist cache, I admit that I didn't fully check that code changes and the option name is not good either. Anyway, a option to disable the cache will help.

**Comment by azrle** [comment]
@derekcollison As memory problem solved, we tested NATS 2.0 (RC6) again.
It does not change too much from NATS 1.4.1 in our cases.

And here is varz and subsz may help you understand our cases.
* varz
```
{
  "server_id": "xxxx",
  "version": "2.0.0-RC6",
  "proto": 1,
  "go": "go1.11.5",
  "host": "0.0.0.0",
  "connect_urls": [ ... 180 entries ... ],
  "addr": "0.0.0.0",
  "max_connections": 65536,
  "ping_interval": 120000000000,
  "ping_max": 2,
  "http_host": "0.0.0.0",
  "http_port": 8222,
  "https_port": 0,
  "auth_timeout": 1,
  "max_control_line": 4096,
  "leaf_node": {},
  "tls_timeout": 0.5,
  "port": 4222,
  "max_payload": 1048576,
  "start": "2019-04-18T05:07:10.927096466Z",
  "now": "2019-04-18T05:50:48.714127876Z",
  "uptime": "43m37s",
  "mem": 2425114624,
  "cores": 8,
  "cpu": 370,
  "connections": 16,
  "total_connections": 4378,
  "routes": 179,
  "remotes": 179,
  "in_msgs": 17056876,
  "out_msgs": 17056876,
  "in_bytes": 4943499253,
  "out_bytes": 4943499253,
  "slow_consumers": 0,
  "max_pending": 67108864,
  "write_deadline": 2000000000,
  "subscriptions": 1371784,
  "http_req_stats": {
    "/": 0,
    "/connz": 174,
    "/routez": 175,
    "/subsz": 174,
    "/varz": 183
  },
  "config_load_time": "2019-04-18T05:07:10.927096466Z"
}
```
* subsz
```
{
  "num_subscriptions": 1375209,
  "num_cache": 240242,
  "num_inserts": 3970216,
  "num_removes": 2595007,
  "num_matches": 25437553,
  "cache_hit_rate": 0.08300208750425012,
  "max_fanout": 0,
  "avg_fanout": 0
}
```

By the way, I found another issue that `connect_urls` may not contain all nodes in the cluster. A few nodes are missing. It's not critical for us right now; but I will confirm it later.

**Comment by derekcollison** [comment]
Thanks for the info, will take a closer look in the morning PT time.

**Comment by azrle** [comment]
I would like to attach the comparison between low load (left) and high load (right) of sync block time percentage graph for NATS 2.0-RC6;
![Screen Shot 2019-04-18 at 18 00 03](https://user-images.githubusercontent.com/2177709/56349615-d89b6f80-6203-11e9-8db1-6aed28959854.png)

and sync block graph for high load:
![Screen Shot 2019-04-18 at 17 56 20](https://user-images.githubusercontent.com/2177709/56349641-e5b85e80-6203-11e9-8d5d-7599faa62454.png)

I hope they can help you do some performance tunings for 2.0.

**Comment by azrle** [comment]
I found another strange thing for NATS 2.0-RC6 when I double-checked metrics.

At the first test, after reaching the max load, from client's point of view, the 99.9%tile latency at NATS cluster can be kept at around 1.5s.

But when we shutdown all clients (all connections to NATS cluster were closed), and we started clients ran the same test again, the NATs cluster could not keep the latency at around 1.5s. The latency started increasing exponentially even before we got the max load. It looks like some of nodes in the cluster heavily stuck at somewhere; however it's very difficult to find bad ones. We didn't see this when we tested NATS 1.4.1 and therefore it was unlikely to be caused by the clients and test itself.

**Comment by derekcollison** [comment]
Again great feedback, thank you.

**Comment by derekcollison** [comment]
Can you give us a good description of the high load test so we can duplicate?

How many connections, how often do they come and go?

How many subs, and how often do they come and go?

How many messages received by subs, etc..

**Comment by azrle** [comment]
It may be difficult to simulate the load test completely.
But I will try my best to give some brief information may help build a similar test.
Meanwhile, could you please check the changes about locks and add option to disable the sublist cache? It indeed improved the latency from 1500ms to 500ms in our case. Thus, I hope it can be officially released in NATS 1.4.

Here is information and metrics for building a similar test.

The scenario is more much like the case described in https://github.com/nats-io/gnatsd/issues/941#issuecomment-483932837.

Here is a graph may help your understand the topology.

`Users` <--> `Agent` <--> `NATS cluster` <--> `Service`

`Agent` is the one who works as a connection pool to NATS cluster, many users shares a connection to NATS cluster. When users comes in, they form some small groups and `Service` will subscribe a subject for each group. Meanwhile, a user itself will subscribe a subject to receive responses from `Service`. After a user joined one and only one group, it will send messages to `Service`. `Service` handles messages and response to users who need to be replied. In most of cases, it responses to all members in the group. Finally, after a few minutes, the user decides to leave the group and unsubscribe the subject used to receive response from `Service`. Moreover, if he/she is the last one in the group, `Service` will unsubscribe the subject used to receive requests. `Agent` and `Service` can also subscribe some other subjects; but majority of traffic won't go there.

When it comes to "low" and "high" load, the basic traffic pattern does not change. The only changes is how many users are involved. As a connection at `Agent` is re-used by multiple users, as the number of users grows, a connection to NATS cluster become heavier. 

I will share some metrics of one of nodes in the cluster, that has around 200 nodes. Note that traffic and connections are distributed evenly to the NATS cluster from both `Agent` and `Service` sides.
A nodes has around 12 connections from `Agent` and 6 connections from `Service`. Each `Agent` connection has around 600-700 SUBS and each `Service` connection may have around 200-300 SUBS. The total In/Out message rate for a NATs node are around 50k/50k msgs/s respectively. And total In/Out message throughput for a NATs node are around 15MB/15MB per second.
And join/leave rate for a `AGENT` connection is around 2~5 users/s (I am not 100% sure about this number).

Moreover, how a latency is observed from application's point of view? After a user joined a group and subscribed a subject, it waits response from `Service` to send response to the subject that it just subscribed. The latency is how long it waits. As we are doing some tracing logs at our application, we are sure that the latency is not happened at application side and tcpdump shows messages did not get stuck at OS unless read loop of NATS is so slow that the read buffer is full and window size is dropped to zero.

Sorry about the long text. Hope I am making sense.

**Comment by derekcollison** [comment]
Thanks, will take a deeper look in am.

**Comment by azrle** [comment]
_It seems that the PR automatically close this issue. Hope it can be re-opened again._

**Comment by derekcollison** [comment]
This PR #968 should help a bit too with lock contention on account lookup etc. 

We have added tests and benchmarks, but if you would be so kind to rerun your exact setup that would be great.

The sublist change could be cherry picked back into 1.4.x branch possibly.

**Comment by azrle** [comment]
@derekcollison Thanks!
We will give it a try in May and share results with you.

**Comment by derekcollison** [comment]
Thanks!

**Comment by azrle** [comment]
We start new tests today and try RC11.

Unfortunately, we failed to run the tests done for previous versions.
1. Connection problem: https://github.com/nats-io/nats-server/issues/988
2. Connections are suddenly lost (disconnected). However we're not sure about the cause because current logs are not informative enough (working on that). There's no error log at nats-server side.

Realize RC11 is not released yet. Trying RC8...

**Comment by azrle** [comment]
RC8 does not have issues 1, 2.
But the 99.9%tile latency went as high as 10 seconds.
Here is the heaviest goroutine.
```
github.com/nats-io/gnatsd/server.(*Server).createRoute.func2
```

![Screenshot_2019-05-09 Goroutine github com nats-io gnatsd server ( Server) createRoute func2](https://user-images.githubusercontent.com/2177709/57448164-ad9cbc80-7293-11e9-929f-f51cb9238d52.png)
![Screen Shot 2019-05-09 at 19 48 48](https://user-images.githubusercontent.com/2177709/57448196-c2795000-7293-11e9-95c5-71026b09b73b.png)

It seems that nats-server 2.0 still has a lot of works to do.
I suggest that https://github.com/nats-io/nats-server/compare/branch_1_4_0...azrle:enhance/processMsg_lock could be reviewed and release a version of 1.4.2 with https://github.com/nats-io/nats-server/pull/967.

**Comment by derekcollison** [comment]
The high cardinality with clustering and possible leaf nodes in #988 was addressed. The sublist can have the cache disabled not but we currently do not dynamically do this, and deciding on whether to add in dynamic behavior and/or config options.

**Comment by azrle** [comment]
I see. I will also give it a try if you have any idea or modification of codes for tests.

**Comment by derekcollison** [comment]
I think its more that NATS was not originally optimized for high cardinality of subjects nor extremely large clusters. We support additional topologies with NATS 2.0 to get very large clusters, but these are clusters of clusters, and those clusters that were supported < 2.0 were not expected to be very large.

Question for me is why is your cluster so big? Do you run a server on each endpoint?

**Comment by derekcollison** [comment]
That being said, we are working to support your mode of using NATS as is. Working on it!

**Comment by azrle** [comment]
> why is your cluster so big?

Good point. First of all, at very beginning, we believe a small cluster can handle all traffics. However, after tests, we found that servers with 16 cores or more cannot fully use their resources (CPU < 50%) and the latency at readLoop happened. As results, we had to downgrade servers and scale out to make the cluster bigger.

We are thinking about sharding. But it may need more works to get there. Before that, we hope that we can make a cluster much stronger.

> Do you run a server on each endpoint?

Not sure about what the question means.

Glad to hear you are working on the large cluster! Thanks!
Also hope some works can be done before we release our products. :)

**Comment by derekcollison** [comment]
I personally, and the team, want you to be successful using NATS, so we will continue to push to meet your needs.

**Comment by azrle** [comment]
@derekcollison Congratulations on NATS 2.0 GA! Hope we did some helps to that.
It has been a while. Do you have any schedule about 1.4 updates that can share with us?

By the way, as NATS 2.0 comes out, do you have any recommendation for our use case? We will check if it's possible to make changes (to clients and architecture). If so, we will give NATs 2.0 another try.

**Comment by derekcollison** [comment]
Yes your feedback helped quite a bit, thank you. We would love you try NATS 2.0 release. We are also happy to jump on a Google hangout to discuss your goals and how the system is setup.

**Comment by azrle** [comment]
Cool. Thanks a lot!
I will discuss with the team to check how much information can be disclosed. And I might invite some other team members to discuss in more details.

By the way, your timezone is PDT, right?

**Comment by derekcollison** [comment]
Yes, PT but I can be up early or stay up late to make it work. Let's target some time mid next week if possible. Looking forward to it. Also if you need us to sign and NDA feel free to send over to us.

**Comment by azrle** [comment]
@derekcollison Will 6/19 (Wed.) 13:00-14:00 JST be okay? Sorry for the late time in night.

**Comment by derekcollison** [comment]
Let me sync with @kozlovic as I would like him to sit in as well. Possible to do Thurs 6/20 at 12:00 JST?

**Comment by azrle** [comment]
6/20 at 12:00 JST looks good to me. My email is azrlew@gmail.com. It would be helpful if could grant me permission to invite people.

**Comment by derekcollison** [comment]
Actually @kozlovic is traveling, could we make it on 27th or 28th?

derek@nats.io
ivan@nats.io

**Comment by azrle** [comment]
27th it is. Invitation sent.

**Comment by derekcollison** [comment]
Thanks.

**Comment by azrle** [comment]
@derekcollison 
As we discussed yesterday, we tested NATS2.0 today.
The good news is that we observed a great performance improvement and the result is acceptable for us. Thank you!
However, we got some other issues when it comes to stability.

There are two problems with a 200-nodes cluster:
1. 99.9%tile latency spikes periodically. We are also observing the following logs sometime (looks like we can measure read loop latency now!):
```
...
[27829] 2019/06/28 12:16:50.549063 [WRN] 10.228.197.150:34802 - cid:7511 - Readloop processing time: 2.564645243s
[27829] 2019/06/28 12:16:50.624079 [WRN] 10.228.197.107:39470 - cid:7503 - Readloop processing time: 3.027326666s
[27829] 2019/06/28 12:16:51.391432 [WRN] 10.228.197.145:55634 - cid:16872 - Readloop processing time: 3.197745253s
```

2. We configure one and only one node as a `nats-route` endpoint. And that server suddenly ate lots of memory during the test and got killed by OOM. Before that, there are some read loop warnings.
```
[28194] 2019/06/28 08:02:41.274746 [INF] 10.228.192.165:6222 - rid:1460 - Router connection closed
[28194] 2019/06/28 09:41:07.313723 [WRN] 10.228.197.112:44574 - cid:7249 - Readloop processing time: 3.08451843s
[28194] 2019/06/28 09:41:07.441878 [WRN] 10.228.197.159:48616 - cid:7252 - Readloop processing time: 2.120301913s
...
[28194] 2019/06/28 09:43:19.955885 [WRN] 10.228.197.108:43702 - cid:7243 - Readloop processing time: 2.637548101s
[28194] 2019/06/28 09:43:19.956135 [WRN] 10.228.197.112:44574 - cid:7249 - Readloop processing time: 2.978868603s
# killed by OOM.
# restarted by our system.
[20887] 2019/06/28 09:43:22.897075 [INF] Starting nats-server version 2.0.0
...
```

3. It seems that some memory leakage may happen as time goes by. But I am not sure if it's just the laziness of the golang GC.

If you need more details, you can find me (@azrle) on Slack. I just joined it.

**Comment by derekcollison** [comment]
That is great in terms of the original performance.

What version of Go are you using?

You said you had 200 nodes, how many client connections? How many subscriptions?
The readloop reporting is happening on client connections, not routes which is good, but it could be those clients are trying to send to routes. Depending on interest they could be trying to send to 199 routes.

How big are the messages you are trying to send? Also, how big is your network link between the NATS servers?

Thanks..

**Comment by azrle** [comment]
We recapped test configurations and discussed a little more details on Slack.
You suggested that a smaller cluster may work. Unfortunately, we tested it and it didn't work. We can discuss it later with some captured profiles.

I also have a good news. By doing analysis of profiles, the old problem - `reduceCacheCount` (sublist cache) came out again. After reviewing codes, I found that the following code 
https://github.com/nats-io/nats-server/blob/v2.0.0/server/sublist.go#L710
can impact the performance when we have a large sublist cache and meanwhile running monitoring program like [prometheus-nats-exporter](https://github.com/nats-io/prometheus-nats-exporter).


I tried to disable the cache. But it seems that it still cannot be done by configurations. So we do the following changes:
```diff
--- a/server/sublist.go
+++ b/server/sublist.go
@@ -99,7 +99,8 @@ func newLevel() *level {

 // NewSublist will create a default sublist
 func NewSublist() *Sublist {
-       return &Sublist{root: newLevel(), cache: &sync.Map{}}
+       // return &Sublist{root: newLevel(), cache: &sync.Map{}}
+       return &Sublist{root: newLevel(), cacheNum: slNoCache}
 }

 // NewSublistNoCache will create a default sublist without caching enabled.
@@ -295,7 +296,7 @@ func (s *Sublist) Match(subject string) *SublistResult {
        atomic.AddUint64(&s.matches, 1)

        // Check cache first.
-       if atomic.LoadInt32(&s.cacheNum) > 0 {
+       if atomic.LoadInt32(&s.cacheNum) > 0 && s.cache != nil {
                if r, ok := s.cache.Load(subject); ok {
                        atomic.AddUint64(&s.cacheHits, 1)
                        return r.(*SublistResult)
@@ -333,7 +334,7 @@ func (s *Sublist) Match(subject string) *SublistResult {
        s.RUnlock()

        // Reduce the cache count if we have exceeded our set maximum.
-       if n > slCacheMax && atomic.CompareAndSwapInt32(&s.ccSweep, 0, 1) {
+       if s.cache != nil && n > slCacheMax && atomic.CompareAndSwapInt32(&s.ccSweep, 0, 1) {
                go s.reduceCacheCount()
        }

@@ -707,16 +708,18 @@ func (s *Sublist) Stats() *SublistStats {
        // whip through cache for fanout stats, this can be off if cache is full and doing evictions.
        tot, max := 0, 0
        clen := 0
-       s.cache.Range(func(k, v interface{}) bool {
-               clen++
-               r := v.(*SublistResult)
-               l := len(r.psubs) + len(r.qsubs)
-               tot += l
-               if l > max {
-                       max = l
-               }
-               return true
-       })
+       if (s.cache != nil) {
+               s.cache.Range(func(k, v interface{}) bool {
+                       clen++
+                       r := v.(*SublistResult)
+                       l := len(r.psubs) + len(r.qsubs)
+                       tot += l
+                       if l > max {
+                               max = l
+                       }
+                       return true
+               })
+       }
        st.MaxFanout = uint32(max)
        if tot > 0 {
                st.AvgFanout = float64(tot) / float64(clen)
```

After doing that, the latency and performance became comparably stable.

__Could you please let us know how to disable sublist cache completely via configuration?__
We cannot find it out from https://github.com/nats-io/nats-server/pull/967.

Speaking of CPU utilization of NATS server, we can discuss further on Slack.

**Comment by derekcollison** [comment]
You do not need those changes, just call `NewSublistNoCache` instead as default for `NewSublist`. Will look into exposing as a parameter. Would this be global to the server, any and all sublists would not have L2 caching?

**Comment by azrle** [comment]
The change is because 1) I am not sure where sublist is build and the code is just to show that we disabled sublist cache entirely; 2) As you may noticed, without the change, the server will panic.

Global to server will be okay for us. Let's have option disable the sublist cache completely.

**Comment by derekcollison** [comment]
ok you are correct about the stats assuming the cache is there. Will look into exposing a configuration for the ability to disable.

**Comment by derekcollison** [comment]
https://github.com/nats-io/nats-server/pull/1054

**Comment by derekcollison** [comment]
This exposes a config parameter 'disable_sublist_cache'. Once merged be great if you and the team could rerun your load tests.

https://github.com/nats-io/nats-server/pull/1055

**Comment by derekcollison** [comment]
This has been merged. Add the following to your config file to test.

`disable_sublist_cache: true`

**Comment by azrle** [comment]
@derekcollison We tested 2.0.1 (master branch) today. It now works as we expected.
Thank you for great works!

Could you please release 2.0.1 so that we can freeze our codes with this version?
Then we can close this issue!

**Comment by derekcollison** [comment]
Yes we will release a version next week most likely.

**Comment by azrle** [comment]
Seeing 2.0.2 released, we believed this issue can be marked as resolved.
Great thanks!

**Comment by derekcollison** [comment]
Thanks again for your patience!
