### ISSUE TITLE
Weird instructions to build

### ISSUE THREAD

**Issue by JensRantil** [nats-io/nats-server#946]
https://github.com/nats-io/gnatsd/#build states

> Run go build inside the /nats-io/gnatsd directory.

. However, there is no `/nats-io/gnatsd` in the repo. I assume that `/main.go` contains the main function so, I propose simply writing

> Run `go build` in root of the checked out repository.

.

**Comment by derekcollison** [comment]
It means the top of the repo directory, we will clarify the docs..
