### ISSUE TITLE
Pure pub-sub

### ISSUE THREAD

**Issue by peng-w** [nats-io/nats-server#970]
Hi, Guys：

![image](https://user-images.githubusercontent.com/6479081/56705681-8945c980-6744-11e9-8768-fedaf61af062.png)

How do I understand the text on the picture？Who is audience？Why assume？Always “on” dial tone。What is dial tone？If the solution is troublesome, please tell me where to learn relevant knowledge.

Thank you very much!

**Comment by derekcollison** [comment]
Closing this since we have new docs. Feel free to re-open.
