### ISSUE TITLE
LeafNode: need to remember to switch GW to interest-mode only

### ISSUE THREAD

**Issue by kozlovic** [nats-io/nats-server#977]
Creating this issue for tracking purposes.

Right now, when a leaf node connects, through system events, the super-cluster is asked to switch to interest-mode only (for gateways).
Need to cover the case where a server joins a cluster after the fact. It needs to know to perform the switch without the presence of that event.

**Comment by PlatanoBailando** [comment]
@derekcollison This issue will also block us.  I spent some time today with @kozlovic exploring the consequences of this bug, but it will prevent us from moving into production.  It essentially prevents two leaf nodes from communicating through a "super cluster" that is gatewayed together, and at various points we need the ability to take nodes down and boot them back up without messing with the rest of the system for maintenance purposes.

**Comment by derekcollison** [comment]
@kozlovic and I are aware and will have a fix soon.
