### ISSUE TITLE
leaf node subscriptions to ">" don't propagate interest always

### ISSUE THREAD

**Issue by aricart** [nats-io/nats-server#982]
When the leaf account user has limits on publish/subscribe, subscribe interests on the leaf for '>' are not propagated unless an explicit subscription to an allow subject is made on the leaf.

## Steps

Create an operator:
`nsc add operator -n O`

Create an account:
`nsc add account -n A`

Create a user with full permissions:
`nsc add user -n U`

Create a user with pub to foo and sub to bar only:
`nsc add user -n leaf`
`nsc edit user -n leaf --allow-pub foo --allow-sub bar`

Start a nats-account-server:
`nats-account-server -nsc ~/.nsc/nats/O`

Start a server with the following config
```
operator: /Users/<youraccount>/.nsc/nats/O/O.jwt
resolver: URL(http://localhost:9090/jwt/v1/accounts/)
leafnodes {
	listen: "127.0.0.1:4000"
}
```

Start the non-limited subscriber on the server:
`nats-sub -creds ~/.nkeys/O/accounts/A/users/U.creds ">"`

Start a leaf with the following config:
```
port: 4111
leafnodes {
	remotes = [ 
		{ url: nats-leaf://localhost:4000, credentials: /Users/<youraccount>/.nkeys/O/accounts/A/users/leaf.creds },
	]
}
```

start a leaf subscriber:
`nats-sub -s localhost:4111 ">"`

Publish foo on the leaf:
`nats-pub -s localhost:4111 foo foo`
All subscribers get it

Publish bar on the leaf:
`nats-pub -s localhost:4111 bar bar`
The leaf subscriber gets it - the one of the server doesn't [OK]

Now repeat with an unlimited server publisher:
`nats-pub -creds ~/.nkeys/O/accounts/A/users/U.creds foo foo`
Only the server subscriber gets it [OK]

Now publish bar:
`nats-pub -creds ~/.nkeys/O/accounts/A/users/U.creds bar bar`
BUG: Only the server subscriber gets it (should have gotten it everywhere)

Now do a local subscriber on the leaf for bar:
`nats-sub -s localhost:4111 bar`

Republish on the server
`nats-pub -creds ~/.nkeys/O/accounts/A/users/U.creds bar bar`
All three subscribers get it. From now any pub of bar on the server will work.

**Comment by derekcollison** [comment]
I believe this has been fixed.
