### ISSUE TITLE
How to enable "verbose mode" by default?

### ISSUE THREAD

**Issue by michelgokan** [nats-io/nats-server#992]
Is there any way to enable "verbose mode" by default? (without any need for asking for it every time 'CONNECT {"verbose": true}')

**Comment by derekcollison** [comment]
Currently no, its client's choice. All supported clients from NATS team have `Verbose:false` and we suggest that of you need a point to know when  a server has processed outgoing messages or intereste directives (sub/unsub) that you use the client's Flush() call.
