### ISSUE TITLE
about write_deadline config

### ISSUE THREAD

**Issue by zhaodanwjk** [nats-io/nats-server#997]
hello：
The service does not want to disconnect over time. Can this parameter  ”write_deadline“  be deleted from the configuration.Make it inoperative.Thank you!

**Comment by derekcollison** [comment]
The write deadline is there to protect the server against clients that are too slow or possible stuck. Can you give us some more information on what you mean by the "service does not disconnect"?

**Comment by zhaodanwjk** [comment]
Now defined as a slow consumer, it is possible to close the connection. Our service does not want to disconnect the slow consumer. Is there such a configuration？

**Comment by derekcollison** [comment]
If the server is taking longer than 2 seconds to perform writes that should be a signal that something is off. The server is designed to protect itself from slow consumers.

What conditions are causing such long system calls?

**Comment by zhaodanwjk** [comment]
We use it to provide services for games. Some processing may be too slow to respond in time. We have to wait for the next response, so the connection cannot be disconnected.

**Comment by derekcollison** [comment]
The server is trying to write to the socket and can't write the payload in the specified 2 second deadline means the client is behind. When the server disconnects the client it will re-connect (most clients).

How much data (message size) is being transferred?

Having the client stay connected is not what you want in my opinion.

**Comment by zhaodanwjk** [comment]
We don't quite understand whether there is any correlation between "max_payload" and "write _ deal". Does the timeout disconnect occur only when the number of connections exceeds the maximum load?Thank you.

**Comment by ripienaar** [comment]
NATS fries to send data over the TCP connection and if that buffer is full or the write blocks and does not complete within deadline it disconnects that client. 

Can happen with just 1 connected too. This can be because your client receives messages in a for loop and tries to process the message in that for loop rather than put the messages in an internal queue for processing by another thread. Or due to network issues etc etc 

I don’t understand what you mean with not able to disconnect though

**Comment by derekcollison** [comment]
Which client are you using for your application?
Would you be willing to share some pseudo code with us showing the processing of inbound messages?

**Comment by zhaodanwjk** [comment]
Thank you very much, we used queue to process the message. through your answer, we should not have any worries. before, we just worried about instability after the service went online.
