### ISSUE TITLE
More than 1 hop when a gateway is used?

### ISSUE THREAD

**Issue by oliverhausler** [nats-io/nats-server#999]
- [X] Documentation: Possible omission, make more clear

https://github.com/nats-io/nats-server#full-mesh-required says:

>NATS servers have a forwarding limit of one hop.

Should probably read:

>Within the cluster, NATS servers have a forwarding limit of one hop. When a gateway connects two clusters, a message may travel up to 3 hops. (One in each cluster, and one between clusters.)

It doesn't become clear (or I overlooked it), but is my assumption correct that when a gateway is used as in https://github.com/nats-io/nats-server#connectivity there will be up to 3 hops per message?

**Comment by kozlovic** [comment]
Correct. Each server in a cluster has an outbound connection to the cluster they have a gateway to. So if your publisher connects to cluster A, server 1 (SA1) and your subscriber is connected to cluster B, server 2 (SB2), but SA1 has an outbound gateway connection to SB1, then yes, message will travel from SA1 to SB1, then routed to SB2.
